import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "In mainland China, call 120 for pre-hospital medical emergency rescue. For immediate or possibly uncontrolled danger, call now; do not wait for interpretation, insurance, payment or hospital research. Give exact location, observed condition/injury cause, approximate age/sex, actions taken, affected count, name and callback. Follow the dispatcher and stay connected until told to end." },
    { id: "answer", type: "callout", title: "Call first; organise later", tone: "decision", body: "120 is the nationwide mainland number. It does not guarantee English service, an arrival time, a fee, a payment method, insurance acceptance, hospital choice or facility capability. Hong Kong and Macao have separate systems. Do not generalise local numbers such as Beijing's 999." },
    { id: "scope", type: "callout", title: "Communication guide—not medical advice", tone: "warning", body: "This page neither diagnoses nor selects treatment. Avoid active hazards and follow dispatcher/clinical instructions. If control is uncertain, call 120 rather than self-classifying from an article." },
    { id: "call-heading", type: "heading", level: 2, text: "Build the 120 call in this order" },
    { id: "call-steps", type: "list", ordered: true, items: ["Request an ambulance; give city/district first.", "State street/site, building, floor, room/gate and landmark.", "Describe the observed condition or injury cause without diagnosis.", "Give approximate age/sex, known relevant history, actions taken and injured count.", "Give your name and a reachable callback.", "Answer, follow instructions and end only when told.", "If requested and safe, send someone to guide the crew from the agreed entrance/landmark."] },
    { id: "call-table", type: "table", caption: "Fill-in card; show Chinese to a helper", columns: ["Field", "Chinese", "Prepare"], rows: [["Request", "需要救护车。", "Need an ambulance"], ["Location", "地址是___，附近地标是___。", "Address, building/floor/room/gate, landmark"], ["Condition", "主要症状／伤情是___，原因是___。", "Observed condition/injury cause"], ["Person", "患者大约___岁，性别___。", "Approximate age/sex"], ["Actions/count", "已经采取___；伤员共___人。", "Actions; injured count"], ["Callback", "我的姓名是___，回拨电话是___。", "Name/reachable number"]] },
    { id: "no-delay", type: "callout", title: "Translation, money and insurance run in parallel", tone: "warning", body: "Call with what you know. While the caller stays with 120, a companion may find staff, records and insurance. Never make pre-authorisation or card checks a condition of rescue." },
    { id: "scenario-one-heading", type: "heading", level: 2, text: "Scenario: alone in a hotel room" },
    { id: "scenario-one", type: "paragraph", text: "Alone and unable to explain much Chinese, you think danger is possible. Call 120. Give hotel name, Chinese address, tower, floor, room, observed problem and callback. If workable, use speaker and ask reception to guide the crew. Do not wait for billing, an English-speaking hospital or insurance." },
    { id: "scene-heading", type: "heading", level: 2, text: "Keep the scene findable and communication recoverable" },
    { id: "scene-list", type: "list", items: ["Follow dispatcher/site direction around traffic, fire, electricity, violence or another hazard; do not create another casualty.", "Use the site's official Chinese address, not only a pin.", "Give entrance/gate/floor/platform and landmark to the greeter.", "Name one staff helper to call/interpret; never assume someone called.", "Keep the callback phone charged, audible and free; add a second number if available.", "Use observed facts; keep original medical records beside translations, not replaced by an app summary."] },
    { id: "translation-table", type: "table", caption: "Fallbacks must preserve the call", columns: ["Failure", "Fallback", "Boundary"], rows: [["No shared language", "Say ‘120’, show the card, ask staff to interpret", "Do not wait for a preferred interpreter"], ["Unclear address", "Read Chinese address/landmark; ask staff to meet crew", "Pin alone is insufficient"], ["Caller cannot continue", "Named helper gives same location/callback", "Link multiple calls to one event"], ["App/data fails", "Use voice, notes/card or safe staffed point", "Data is no rescue guarantee"]] },
    { id: "handoff-heading", type: "heading", level: 2, text: "Make the ambulance-to-hospital handoff usable" },
    { id: "handoff-steps", type: "list", ordered: true, items: ["Follow dispatcher/crew; do not select treatment here.", "Give name, age/sex estimate, available passport identity, observed timeline and actions.", "Share readily available records/medicine list; mark unknowns, never guess.", "Bring accepted ID, but never delay call or safe transfer searching for it.", "Ask which facility the patient will be taken to; record any available ambulance/dispatch reference.", "Note facility, arrival, department and receiving staff role; protect private data.", "Ask current payment methods and keep charges/receipts; contact insurance after rescue starts."] },
    { id: "record-table", type: "table", caption: "Private continuity record", columns: ["Record", "Minimum", "Purpose"], rows: [["Call", "Time, number, callback, instructions", "Reconstruct request"], ["Location", "Chinese address, entrance/landmark, screenshot", "Explain dispatch point"], ["Facts", "Timeline, condition/cause, count, reported actions", "Avoid retrospective diagnosis"], ["Transfer", "Facility, department, known ambulance reference", "Continue handoff"], ["Identity/payment", "ID used, payment reference, itemisation/receipts", "Hospital/insurer/card follow-up"], ["Contacts", "Hospital, insurer, companion case numbers", "Resume stalled process"]] },
    { id: "payment", type: "callout", title: "No universal billing promise", tone: "warning", body: "Processes vary. Do not promise direct billing, foreign-card acceptance, cashless treatment, reimbursement or any price. Ask the facility/insurer, preserve records and keep a payment fallback—but never delay 120." },
    { id: "scenario-two-heading", type: "heading", level: 2, text: "Scenario: an incident at an attraction with several people nearby" },
    { id: "scenario-two", type: "paragraph", text: "At an attraction incident, entrance, gate and injured count beat a long explanation. Name one staff caller and confirm connection, or call yourself. Report incident/observed condition, follow instructions and send a greeter. Link duplicate calls to the same event; never assume venue staff, guide or insurer called." },
    { id: "failure-heading", type: "heading", level: 2, text: "When the emergency chain fails" },
    { id: "failure-table", type: "table", caption: "Recover without inventing promises", columns: ["Failure", "Recovery", "Never"], rows: [["120 not connected", "Retry; use another phone/landline or ask named staff to call while you stay safe", "Generalise 999"], ["Crew cannot find you", "Repeat district, Chinese address, entrance/landmark; send greeter if instructed", "Use only a pin"], ["Language fails", "Use card, named helper, observed facts; stay connected", "Wait for English"], ["No data", "Use voice, written address or safe staffed point", "Assume eSIM voice"], ["Payment/insurance stalls", "Ask facility; preserve references; companion calls insurer/card issuer", "Interrupt transfer for approval"], ["Receiving plan changes", "Follow professionals; record facility/next step", "Guarantee hospital/capability"]] },
    { id: "nonurgent", type: "callout", title: "Care needed, no current danger", tone: "neutral", body: "Use an official facility channel, hotel or insurer care line; verify department, access, language and payment. Do not use 120 for convenience. If danger develops or control becomes uncertain, call 120." },
    { id: "change-table", type: "table", caption: "Facts that change the next action", columns: ["New fact", "Change"], rows: [["Danger/control uncertain", "Stop research; call 120"], ["Dispatcher instructs", "Follow it over this list"], ["Location changes", "Immediately give new address/landmark"], ["Affected count rises", "Update count/observations"], ["Phone/caller changes", "Give callback; link same event"], ["Official numbers conflict", "Preserve versions; ask health authority later; mainland emergency uses 120"]] },
    { id: "freshness", type: "paragraph", text: "Reviewed 2026-09-01; freshness class: high-risk dynamic. Recheck after changes to national rules, number guidance, dispatch, telecom, facility or billing/insurance routes. A 2022 NIA English guide lists 120 and 999 without clear geography; the NHC national rule and 2019 Chinese reply identify nationwide 120 and Beijing's additional 999. We disclose this and do not make 999 a mainland fallback. Preserve conflicting versions; ask NHC/local health authority later, never before an active 120 call." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final handoff check" },
    { id: "verify-list", type: "list", items: ["Danger/uncertainty triggered 120 before translation, payment or insurance.", "City/district, Chinese address, entrance/floor/room and landmark given.", "Observed condition/cause, age/sex, actions and count reported.", "Name and reachable callback given.", "Dispatcher confirmed you could end the call.", "Named helper met crew when requested/safe.", "Professional instructions overrode this page.", "Identity, timeline, facility and payment records kept private.", "No language, timing, cost, payment, insurance, hospital or treatment promise.", "999 not generalised; Hong Kong/Macao checked separately."] },
    { id: "links", type: "internal-links", title: "Prepare the practical backup before an emergency", items: [{ label: "China eSIM or local SIM", href: "/guides/china-esim-vs-local-sim/", description: "Know whether your setup includes voice calls and keep an independent contact route." }, { label: "Confirm shifted map pins in China", href: "/guides/china-map-coordinate-offset-explained/", description: "Save a verified Chinese address and landmark instead of relying on one pin." }, { label: "Set up tourist payments for China", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Prepare more than one payment route without delaying emergency care." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Guide to Working and Living in China — emergency contacts", url: "https://english.www.gov.cn/2025special/bizexpatsinchina2025", publisher: "State Council of the People's Republic of China", reviewedAt: "2026-09-01" }, { label: "Measures for the Administration of Pre-hospital Medical Emergency Care — formal regulation page", url: "https://www.nhc.gov.cn/fzs/c100048/201808/6878dddd2a3d48c59de1c43a6c68423d.shtml", publisher: "National Health Commission", reviewedAt: "2026-09-01" }, { label: "Chinese Citizens' Health Literacy: Basic Knowledge and Skills (2024)", url: "https://www.nhc.gov.cn/xcs/c100122/202405/f251e896a50a49ff8c632b4b3da93126/files/1734001844015_12363.pdf", publisher: "National Health Commission", reviewedAt: "2026-09-01" }, { label: "How to call 120 correctly", url: "https://www.beijing.gov.cn/fuwu/bmfw/sy/jrts/202607/t20260713_4759730.html", publisher: "Beijing Municipal Government / National Health Commission", reviewedAt: "2026-09-01" }, { label: "Welcome to China, page 46 — emergency contact methods", url: "https://www.nia.gov.cn/2022en/files/basic-html/page46.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-01" }, { label: "Official response on nationwide 120 and Beijing's 999", url: "https://www.nhc.gov.cn/wjw/jiany/201901/ac1b0f90398a4ab881a5854509edfd58.shtml", publisher: "National Health Commission", reviewedAt: "2026-09-01" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
