import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "A Beijing copper-pot mutton meal is ordered in rounds, not all at once. Take the pot with its broth, one plate of mutton for every two people, two vegetables, one starch and a sesame-paste dip. Vegetables in first, then the meat, cook everything through, and order the second round only when the first has gone. That sequence is the whole method. The rest of this page decodes the meat section of the menu, shows how four Beijing houses answer the same questions differently, and gives you sentences to say at the table.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The default first order, for two people",
      tone: "decision",
      body: "One copper pot with the house broth. One plate of mutton described as leg or upper shoulder, with fat running through the lean. One leaf vegetable and one absorbent item - Chinese cabbage and frozen tofu are the pairing Beijing's market regulator names. One sesame-paste dip each. One starch, ordered but held back. Nothing else until you have eaten that. Then add meat one plate at a time, for as long as you are still hungry.",
    },
    {
      id: "what-heading",
      type: "heading",
      level: 2,
      text: "What arrives, and what it is not",
    },
    {
      id: "what-p1",
      type: "paragraph",
      text: "The pot in front of you is a single ring of broth around a charcoal chimney. No divider, no second compartment and, in the older houses, no red oil. Beijing's market regulator describes the base as plain water with ginger slices, spring onion, goji berries and dried shrimp - a broth built to stay out of the way. When the mutton is thin and fresh, the pot's job is to cook it, not season it. That is the largest difference from the Sichuan and Chongqing pots most visitors meet first, where the broth carries the flavour and the dip is often only oil and garlic. Here the order is reversed.",
    },
    {
      id: "what-p2",
      type: "paragraph",
      text: "The pot is a specific object with named parts. The Ministry of Commerce entry for Yitiaolong, a Beijing halal house serving instant-boiled mutton since 1785, describes the copper pot it has kept since 1897 as having a clearly formed jar belly, ear curtain and gourd door - the swollen lower bowl, the flared lip ringing the chimney, and the shaped opening at the base of the flue where charcoal is fed. Donglaishun, whose technique joined the national intangible heritage list in 2008, tells the Dongcheng district government the same thing in one sentence: it kept the old Beijing habit of cooking in a copper pot, and uses machine-made charcoal because it burns long and does not pollute.",
    },
    {
      id: "pot-list-heading",
      type: "heading",
      level: 3,
      text: "Two things the pot tells you before you order",
    },
    {
      id: "pot-list",
      type: "list",
      items: [
        "A charcoal chimney means uneven heat: the broth boils hardest closest to the flue and slowest at the rim near you, so cook where the water is moving.",
        "One undivided ring means everything shares a liquid, so strong-smelling items change the pot for the whole table.",
      ],
    },
    {
      id: "menu-heading",
      type: "heading",
      level: 2,
      text: "Reading the meat section without guessing",
    },
    {
      id: "menu-p1",
      type: "paragraph",
      text: "The meat section is where most first orders go wrong, because its words describe three things at once: which part of the animal, how it was cut, and whether anything was added. Beijing's market regulator names two cuts for the pot - leg and upper shoulder - chosen because fat runs through the lean rather than sitting at the edge. Those two are the safe defaults, and a house offering nothing else is not a lesser house. Everything past them is preference, not upgrade.",
    },
    {
      id: "menu-table",
      type: "table",
      caption: "What the words in the meat section actually tell you",
      columns: ["What the menu says", "What it tells you", "What to ask"],
      rows: [
        [
          "Leg (yang tui rou)",
          "A cut the market regulator lists for the pot, fat distributed through the lean. Says nothing about when it was cut",
          "Is it hand-cut fresh, or a frozen roll?",
        ],
        [
          "Upper shoulder (yang shang nao)",
          "The regulator's other named cut; generally softer and more marbled than leg",
          "The same question, then order one of each and compare",
        ],
        [
          "Hand-cut (shou qie)",
          "A knife-work claim. Yangfang Shengli's heritage listing names four techniques - splitting, boning, paring, slicing - and a hand-cut crescent as its signature",
          "Nothing. Order it and look: hand-cut slices are irregular in outline",
        ],
        [
          "Roll (yang rou juan)",
          "Frozen into a block and sliced from it - a legitimate method, not a shortcut. Says nothing about what was in the block",
          "Is this whole-cut mutton, or a prepared roll?",
        ],
        [
          "Prepared or flavoured (tiao li, feng wei)",
          "On packaged retail meat, the regulator's own markers for a product with other ingredients worked in. No defined meaning on a restaurant menu",
          "Ask in plain words instead. See the caution below",
        ],
        [
          "A named breed or place, such as Tan sheep or Xilingol",
          "A sourcing claim the house makes publicly, though not a claim about today's plate",
          "Where is today's mutton from?",
        ],
      ],
    },
    {
      id: "menu-callout",
      type: "callout",
      title: "The one place this vocabulary does not transfer",
      tone: "warning",
      body: "The clearest published account of pure mutton versus a prepared mutton product comes from Beijing's market regulator, and it is written about packaged food sold in shops: pure mutton is divided, frozen and sliced with nothing added, while a prepared roll may have other ingredients and additives worked in. The regulator states plainly that no standard currently sets a minimum meat content for prepared products, so the proportion varies between manufacturers. That advisory tells you to read the product name and the ingredient list. A restaurant plate has neither. Ask instead.",
    },
    {
      id: "houses-heading",
      type: "heading",
      level: 2,
      text: "Four published versions that disagree with each other",
    },
    {
      id: "houses-p1",
      type: "paragraph",
      text: "There is no single Beijing copper-pot recipe, and the proof is paperwork rather than anecdote. Three houses have had their methods written up by a government body, and the city's market regulator has published a general version for cooking at home. Side by side they disagree about the broth, the sourcing, the knife and the dip - the four things a first-time diner assumes are fixed. This is not a ranking. It exists so that when the pot in front of you does not match what you read elsewhere, you know that is normal.",
    },
    {
      id: "houses-table",
      type: "table",
      caption: "Where four officially documented versions differ",
      columns: ["Documented by", "The broth", "The mutton", "The knife", "The dip and the table"],
      rows: [
        [
          "Beijing market regulator, general home version",
          "Plain water with ginger, spring onion, goji and dried shrimp",
          "Leg or upper shoulder, fat through the lean",
          "Not specified",
          "Sesame paste with fermented bean curd and chive-flower sauce; cabbage, crown daisy, frozen tofu",
        ],
        [
          "Donglaishun, national heritage list 2008, via Dongcheng district government",
          "Not specified; the copper pot and long-burning machine-made charcoal named instead",
          "The founding master's expertise covered the sheep's origin and the cut used",
          "Slicing named as part of that expertise; slices thin enough for a porcelain plate's pattern to show through",
          "A cloisonne pot developed alongside the plain copper one",
        ],
        [
          "Yangfang Shengli, Changping heritage listing, via Beijing municipal government",
          "A thick-yet-clear bone broth, not plain water",
          "Xilingol League mutton; selection and carcass preparation are steps one and two of seven",
          "Four techniques - splitting, boning, paring, slicing - and a hand-cut crescent",
          "An old-method dip and a traditional staple pairing, steps five and seven",
        ],
        [
          "Yitiaolong, Beijing municipal heritage list 2007, via the Ministry of Commerce",
          "Not specified; a charcoal-fired copper pot named as continuous practice since 1785",
          "Tan sheep from the Gansu area, small-framed and not gamey",
          "Hand-cut, plus a cold-pressing method for the frozen rolls",
          "Several dips, each blended from dozens of ingredients; a crab-shell sesame flatbread",
        ],
      ],
    },
    {
      id: "houses-p2",
      type: "paragraph",
      text: "Two conclusions follow. If you want the plain-water version you read about, you may have to go looking for it - a bone broth is not a corruption but one house's documented signature. And the sourcing claims are real claims, made in public records rather than on a wall: Yangfang Shengli names Xilingol mutton, Yitiaolong names Gansu Tan sheep. A house that has said this in a government record can be asked about it at the table.",
    },
    {
      id: "amount-heading",
      type: "heading",
      level: 2,
      text: "How much to order, without weighing anything",
    },
    {
      id: "amount-p1",
      type: "paragraph",
      text: "Plate sizes are not standard between houses, so any figure in grams is a number for one restaurant rather than a rule. Order by rounds instead. A round is one plate of meat, one vegetable, and whatever is already in the pot. Make the first round deliberately smaller than you want: the pot needs time to reach a rolling boil, and a table that orders everything at once crowds a pot that has not got there yet.",
    },
    {
      id: "amount-table",
      type: "table",
      caption: "First round by table size, with what to leave out on purpose",
      columns: ["People", "Order now", "Order once the first round has gone", "Leave out on round one"],
      rows: [
        [
          "One",
          "A half portion if offered, otherwise one plate; one leaf vegetable; one dip",
          "A second plate, only if you finished the first without pausing",
          "Starch, frozen tofu, anything sold as a set",
        ],
        [
          "Two",
          "One plate of meat; one leaf vegetable; one absorbent item; two dips",
          "One more plate, and a second vegetable if the pot looks bare",
          "Starch. Order it later or it arrives cold",
        ],
        [
          "Three to four",
          "Two plates, ideally two cuts; two vegetables; one absorbent item; a dip each",
          "Meat by the plate, alternating with vegetables so the broth stays clean",
          "Noodles, dumplings, anything that clouds the pot",
        ],
        [
          "Five or more",
          "One plate per two people; three vegetables; two absorbent items",
          "Single plates only, so nobody waits on a shared platter",
          "A second pot, unless the table cannot reach one",
        ],
      ],
    },
    {
      id: "amount-p2",
      type: "paragraph",
      text: "Example, written to show the arithmetic rather than to report a real meal. Four people order two plates of meat, three vegetables and four dips. The plates turn out generous, so the second round is one plate rather than two. Total: three plates for four people, decided after seeing the first two. Had the plates been small it would have been five. Neither number could have been chosen from the menu.",
    },
    {
      id: "dip-heading",
      type: "heading",
      level: 2,
      text: "The dip is the seasoning, so treat it like one",
    },
    {
      id: "dip-p1",
      type: "paragraph",
      text: "Because the broth is restrained, the bowl beside you does the work a Sichuan pot does in the liquid. The classic Beijing combination named by the city's market regulator is short: sesame paste, fermented bean curd and chive-flower sauce. Sesame paste is the body; fermented bean curd brings salt and savoury depth; chive-flower sauce, made from fermented garlic-chive buds, brings the sharp edge that keeps a fatty mouthful from flattening out. That trio is a reference point rather than the only version - Yitiaolong's record describes several distinct dips, each blended from dozens of ingredients.",
    },
    {
      id: "dip-list-heading",
      type: "heading",
      level: 3,
      text: "How to handle the dip bowl in practice",
    },
    {
      id: "dip-list",
      type: "list",
      items: [
        "If it arrives already mixed, taste before adding anything. Many houses have balanced it and additions only make it saltier.",
        "If it arrives as plain sesame paste beside a condiment tray, the tray is the point. Add the other two a little at a time, stirring, and stop when it coats the back of a spoon.",
        "Chive-flower sauce is what most first-timers dislike on the first taste and miss by the third mouthful. Add half what you think you want, eat some meat with it, then reconsider.",
        "If you truly do not want sesame paste, ask what else the house has. A soy-and-vinegar bowl with coriander and chilli oil is a normal alternative, and asking is not an insult.",
        "Do not thin the dip with broth from the pot. The bowl should be thick enough to cling, and liquid lifted from a working pot is not clean.",
        "Pickled sweet garlic sits beside the dip rather than in it, and it is not a garnish. Whole cloves cured in sweet vinegar reset the palate between rounds of fat.",
      ],
    },
    {
      id: "cook-heading",
      type: "heading",
      level: 2,
      text: "Once the charcoal is lit",
    },
    {
      id: "cook-p1",
      type: "paragraph",
      text: "There is a published order here, and it is not the one most people improvise. Beijing's market regulator states it as vegetables before meat. The reason is practical: leaf vegetables and frozen tofu entering a clean pot leave the broth better than they found it, while meat first leaves scum and fat that everything afterwards sits in. Starting with vegetables also gives the pot the minutes it needs to reach a real boil.",
    },
    {
      id: "cook-list-heading",
      type: "heading",
      level: 3,
      text: "The sequence, and the two habits worth building",
    },
    {
      id: "cook-list",
      type: "list",
      items: [
        "Wait for a genuine rolling boil at the chimney ring, not a simmer. This is the step people skip, and it costs the whole meal.",
        "Vegetables and frozen tofu first. Cabbage stems before leaves; frozen tofu takes longest and can go in early and stay in.",
        "Then meat, a few slices at a time, spread out. A whole plate dropped in at once drops the temperature and welds itself into a lump.",
        "Keep one pair of chopsticks for raw meat and eat with a different pair. Beijing's disease-control guidance defines raw as anything still needing heat, cooked as anything you can eat directly, and asks for separate tools between the two. A shared pot is exactly where that applies.",
        "Use the serving chopsticks if the house provides them. Beijing's health commission puts the rule as serve with the communal pair and eat with your own, citing shared-utensil transmission of Helicobacter pylori - which it reports at a national average infection rate of 59 per cent.",
        "Skim the surface when it greys over. Most houses will do it if you catch someone's eye.",
      ],
    },
    {
      id: "cook-callout",
      type: "callout",
      title: "There is no authoritative number of seconds",
      tone: "warning",
      body: "You will be told that mutton is done the moment it changes colour, or after some confident count of seconds. No Chinese food-safety authority publishes that figure, and this page will not invent one. What is published is the principle: cook food through. Beijing's disease-control guidance describes thorough cooking as poultry cooked until the juices run clear with no pink inside, eggs and seafood brought fully to the boil, and soups and stews boiled at least a minute, with large pieces needing longer - and separately notes that most micro-organisms struggle to survive above 70 degrees Celsius or below 4. Applied to a copper pot: a genuine boil, thin slices, a few at a time, and no piece leaving the pot while any part of it is still red. If you are cooking for a child, an older relative, someone pregnant or anyone immunocompromised, cook their portions longer than your own.",
    },
    {
      id: "cook-p2",
      type: "paragraph",
      text: "One thing to know before the end. Beijing's market regulator warns that a hotpot broth boiled for a long time is relatively high in purines and fat, and that people with gout or high blood lipids should be cautious about drinking it. Late-stage broth is also where noodles are traditionally cooked, so the noodles carry it. That is a reason to decide, rather than drift, about the meal's last twenty minutes.",
    },
    {
      id: "lang-heading",
      type: "heading",
      level: 2,
      text: "Sentences that actually get used",
    },
    {
      id: "lang-p1",
      type: "paragraph",
      text: "Copper-pot houses are loud and the staff are busy, so a long polite sentence loses to a short clear one. Say these, or point at the row.",
    },
    {
      id: "lang-table",
      type: "table",
      caption: "An ordering card for a copper-pot table",
      columns: ["What you want to say", "Chinese", "Roughly how it sounds"],
      rows: [
        ["Two people, one pot please", "两位，一个锅", "liang wei, yi ge guo"],
        ["Is this hand-cut fresh mutton, or a frozen roll?", "这是手切鲜羊肉还是冻羊肉卷？", "zhe shi shou qie xian yang rou hai shi dong yang rou juan"],
        ["Is it whole-cut mutton, with nothing added?", "是原切羊肉吗？没有添加别的吧？", "shi yuan qie yang rou ma, mei you tian jia bie de ba"],
        ["Which cut is this?", "这是哪个部位？", "zhe shi na ge bu wei"],
        ["Where is today's mutton from?", "今天的羊肉是哪儿的？", "jin tian de yang rou shi nar de"],
        ["One plate of leg, one of upper shoulder", "一盘羊腿肉，一盘上脑", "yi pan yang tui rou, yi pan shang nao"],
        ["Cabbage, crown daisy, frozen tofu", "白菜、茼蒿、冻豆腐", "bai cai, tong hao, dong dou fu"],
        ["Sesame dip, one each", "麻酱，一人一份", "ma jiang, yi ren yi fen"],
        ["More pickled garlic, please", "再来点糖蒜", "zai lai dian tang suan"],
        ["Could we have serving chopsticks?", "有公筷吗？", "you gong kuai ma"],
        ["Please top up the broth", "麻烦加点汤", "ma fan jia dian tang"],
        ["The flatbread now, please", "现在上烧饼", "xian zai shang shao bing"],
        ["That is enough, thank you", "够了，谢谢", "gou le, xie xie"],
      ],
    },
    {
      id: "repair-heading",
      type: "heading",
      level: 2,
      text: "When the plan breaks",
    },
    {
      id: "repair-p1",
      type: "paragraph",
      text: "Four situations account for almost every copper-pot evening that goes sideways. None is a disaster, and each has a move.",
    },
    {
      id: "repair-table",
      type: "table",
      caption: "Four common failures and the move that fixes each",
      columns: ["The situation", "What is actually happening", "What to do"],
      rows: [
        [
          "You are alone and the pot looks built for six",
          "Portions are sized for sharing, so a solo diner over-orders by default",
          "Ask for a half portion, take one vegetable, skip the starch. If the house cannot split a portion, order one plate and one vegetable, then add a second later.",
        ],
        [
          "No English, no pictures, no numbers you recognise",
          "You are reading a document when the meal needs four decisions",
          "Use the leg-and-upper-shoulder line from the card above, name the three vegetables, ask for sesame dip, stop. That order is complete in any copper-pot house in the city.",
        ],
        [
          "The cut you wanted is sold out",
          "Hand-cut mutton is limited by how much was cut that day - a sign of a kitchen working properly",
          "Take whichever named cut is left. If both are gone, ask what the house recommends today; a house that sells out of hand-cut mutton has told you something about itself.",
        ],
        [
          "The broth turns cloudy and grey halfway through",
          "Too much meat went in at once, or nobody has skimmed",
          "Skim it, ask for a top-up, go back to a few slices at a time. Do not compensate with more heat.",
        ],
      ],
    },
    {
      id: "culture-heading",
      type: "heading",
      level: 2,
      text: "Why the meal is shaped this way",
    },
    {
      id: "culture-p1",
      type: "paragraph",
      text: "The parts that feel like ceremony are mostly solved problems. Thin slicing exists because a shallow, unevenly heated pot cooks thin meat well and thick meat badly - and the Dongcheng district government notes that watching the Donglaishun master slice became a spectacle in its own right. Vegetables before meat exists because one undivided ring of broth is a shared resource. Even the geography is functional: Yangfang Shengli's listing traces the tradition to a sheep market on the north-western approach to the capital, where animals arriving from the grasslands were traded before reaching the city.",
    },
    {
      id: "culture-p2",
      type: "paragraph",
      text: "Two of the three houses named here are halal Muslim restaurants, a plain fact about who built this tradition in Beijing and stated in their own official records. It is not a certification claim, and this page does not verify certification or handle allergens - if either matters, ask the house and read its posted credentials. What the history does tell you is that the copper pot is not a costume: Yitiaolong's record describes the same charcoal-fired pot in continuous use since the eighteenth century.",
    },
    {
      id: "limits-heading",
      type: "heading",
      level: 2,
      text: "What this page deliberately will not do",
    },
    {
      id: "limits-list-heading",
      type: "heading",
      level: 3,
      text: "Four refusals",
    },
    {
      id: "limits-list",
      type: "list",
      items: [
        "No restaurant ranking, booking or prices. Houses are named only where a government record documents their method, and naming is not recommending.",
        "No cooking times in seconds. The published guidance is a principle, not a stopwatch, and inventing a number would be the one thing here that could hurt someone.",
        "No allergen or dietary guarantee. Sesame paste is central, chive-flower sauce and fermented bean curd are fermented allium and soy products, and a shared pot cannot be made free of anything.",
        "No page for each cut. Two cuts are named by the regulator and both work; the rest is preference.",
      ],
    },
    {
      id: "links",
      type: "internal-links",
      title: "Read next",
      items: [
        {
          label: "Your first shared meal in China",
          href: "/guides/first-shared-meal-in-china/",
          description: "The table mechanics this page assumes: who orders, how dishes are shared, how the bill works.",
        },
        {
          label: "Ordering a balanced first Hunan meal",
          href: "/guides/hunan-cuisine-balanced-first-meal/",
          description: "The same ordering problem where heat, not fat, is the variable to balance.",
        },
        {
          label: "How Guangzhou morning tea works",
          href: "/guides/how-guangzhou-morning-tea-works/",
          description: "Another meal where the order of operations matters more than the dish list.",
        },
        {
          label: "Building a regional food route across China",
          href: "/guides/china-regional-food-route/",
          description: "Where a Beijing copper pot fits across several regions rather than one city.",
        },
        {
          label: "How to pay in China as a tourist",
          href: "/guides/how-to-pay-in-china-as-a-tourist/",
          description: "Settling the bill at a busy counter, the last step of this workflow.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources",
      items: [
        {
          label: "A complete guide to old Beijing instant-boiled mutton",
          url: "https://scjgj.beijing.gov.cn/zwxx/scjgdt/202512/t20251215_4342165.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Consumer advisory on buying beef and mutton",
          url: "https://scjgj.beijing.gov.cn/hdjl/xfts/202001/t20200120_1619155.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Autumn and winter food-safety risk controls for caterers",
          url: "https://scjgj.beijing.gov.cn/zwxx/scjgdt/202510/t20251027_4241346.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-22",
        },
        {
          label: "The Donglaishun instant-boiled mutton technique",
          url: "https://www.bjdch.gov.cn/ztzl/cyqn/jsmsjy/202407/t20240730_3762490.html",
          publisher: "Dongcheng District People's Government, Beijing",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Yangfang Shengli instant-boiled mutton, Changping intangible heritage",
          url: "https://www.beijing.gov.cn/renwen/bjgk/cpgk/cpfy/202304/t20230403_2965858.html",
          publisher: "Beijing Municipal Government portal",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Yitiaolong, China Time-honoured Brand record",
          url: "https://zhlzh.mofcom.gov.cn/news/entp_view/5037",
          publisher: "Ministry of Commerce of the People's Republic of China",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Beijing CDC reminder: food safety at festive meals",
          url: "https://www.beijing.gov.cn/fuwu/bmfw/sy/jrts/202402/t20240210_3561570.html",
          publisher: "Beijing Center for Disease Prevention and Control",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Table manners: separate serving",
          url: "https://wjw.beijing.gov.cn/bmfw_20143/jkzs/jksh/202106/t20210623_2419757.html",
          publisher: "Beijing Municipal Health Commission",
          reviewedAt: "2026-08-22",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
