import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Order a Beijing copper-pot mutton meal in rounds. For two people, begin with the pot, one plate of mutton, two vegetables and a sesame-paste dip each; hold the starch until you know you still want it. A vegetables-first round is an optional way to start lighter, not a safety rule. Add meat in small batches, follow the restaurant's cooking guidance and order more only after seeing the first portions.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The default first order, for two people",
      tone: "decision",
      body: "One copper pot with the house broth. One plate labelled leg or upper shoulder - the two cuts named in Beijing's market-regulator guide. Add one leaf vegetable, one absorbent item such as frozen tofu and one sesame-paste dip each. Order starch later. Once you have seen the portion size and finished most of the first round, add meat one plate at a time.",
    },
    {
      id: "what-heading",
      type: "heading",
      level: 2,
      text: "What arrives, and what it is not",
    },
    {
      id: "what-p1",
      type: "paragraph",
      text: "The documented Beijing version uses one ring of broth around a charcoal chimney. Beijing's market regulator describes a base of plain water with ginger, spring onion, goji berries and dried shrimp, with much of the seasoning supplied by the dip. Individual restaurants may use a different broth; the officially documented Yangfang Shengli method, for example, names a bone broth.",
    },
    {
      id: "menu-heading",
      type: "heading",
      level: 2,
      text: "Reading the meat section without guessing",
    },
    {
      id: "menu-p1",
      type: "paragraph",
      text: "Meat-section labels can describe the cut, the slicing method or whether a retail product was prepared with other ingredients. Beijing's market regulator names leg and upper shoulder for the pot. Use those as two clear starting terms, not as a quality ranking, and ask how the restaurant prepared today's plate.",
    },
    {
      id: "menu-table",
      type: "table",
      caption: "What the words in the meat section actually tell you",
      columns: ["What the menu says", "What it tells you", "What to ask"],
      rows: [
        [
          "Leg (yang tui rou)",
          "A cut the market regulator lists for the pot, fat distributed through the lean. Says nothing about when it was cut",
          "Is it hand-cut fresh, or a frozen roll?",
        ],
        [
          "Upper shoulder (yang shang nao)",
          "The other cut named in the same regulator guide; the source gives no quality ranking against leg",
          "Is it hand-cut fresh, or a frozen roll?",
        ],
        [
          "Hand-cut (shou qie)",
          "A knife-work claim. Yangfang Shengli's heritage listing names four techniques - splitting, boning, paring, slicing - and a hand-cut crescent as its signature",
          "How was today's plate cut and prepared? Shape alone does not prove the method",
        ],
        [
          "Roll (yang rou juan)",
          "Frozen into a block and sliced from it; the label alone does not establish what was in the block",
          "Is this whole-cut mutton, or a prepared roll?",
        ],
        [
          "Prepared or flavoured (tiao li, feng wei)",
          "On packaged retail meat, the regulator's own markers for a product with other ingredients worked in. No defined meaning on a restaurant menu",
          "Ask in plain words instead. See the caution below",
        ],
        [
          "A named breed or place, such as Tan sheep or Xilingol",
          "A sourcing claim the house makes publicly, though not a claim about today's plate",
          "Where is today's mutton from?",
        ],
      ],
    },
    {
      id: "menu-callout",
      type: "callout",
      title: "The one place this vocabulary does not transfer",
      tone: "warning",
      body: "Beijing's market regulator explained pure versus prepared mutton in a 2020 advisory about packaged retail food: pure mutton was described as divided, frozen and sliced with nothing added, while a prepared roll could contain other ingredients and additives. The advisory said that, at publication, no standard set a minimum meat content for those prepared products. That dated retail statement is not a current restaurant-menu rule. A restaurant plate has no retail ingredient list, so ask in plain language what today's plate contains.",
    },
    {
      id: "houses-heading",
      type: "heading",
      level: 2,
      text: "Four published versions that disagree with each other",
    },
    {
      id: "houses-p1",
      type: "paragraph",
      text: "There is no single Beijing copper-pot recipe, and the proof is paperwork rather than anecdote. Three houses have had their methods written up by a government body, and the city's market regulator has published a general version for cooking at home. Side by side they disagree about the broth, the sourcing, the knife and the dip - the four things a first-time diner assumes are fixed. This is not a ranking. It exists so that when the pot in front of you does not match what you read elsewhere, you know that is normal.",
    },
    {
      id: "houses-table",
      type: "table",
      caption: "Where four officially documented versions differ",
      columns: ["Documented by", "The broth", "The mutton", "The knife", "The dip and the table"],
      rows: [
        [
          "Beijing market regulator, general home version",
          "Plain water with ginger, spring onion, goji and dried shrimp",
          "Leg or upper shoulder, fat through the lean",
          "Not specified",
          "Sesame paste with fermented bean curd and chive-flower sauce; cabbage, crown daisy, frozen tofu",
        ],
        [
          "Donglaishun, national heritage list 2008, via Dongcheng district government",
          "Not specified; the copper pot and long-burning machine-made charcoal named instead",
          "The founding master's expertise covered the sheep's origin and the cut used",
          "Slicing named as part of that expertise; slices thin enough for a porcelain plate's pattern to show through",
          "A cloisonne pot developed alongside the plain copper one",
        ],
        [
          "Yangfang Shengli, Changping heritage listing, via Beijing municipal government",
          "A thick-yet-clear bone broth, not plain water",
          "Xilingol League mutton; selection and carcass preparation are steps one and two of seven",
          "Four techniques - splitting, boning, paring, slicing - and a hand-cut crescent",
          "An old-method dip and a traditional staple pairing, steps five and seven",
        ],
        [
          "Yitiaolong, Beijing municipal heritage list 2007, via the Ministry of Commerce",
          "Not specified; a charcoal-fired copper pot named as continuous practice since 1785",
          "The record names Tan sheep from the Gansu area",
          "Hand-cut, plus a cold-pressing method for the frozen rolls",
          "Several dips, each blended from dozens of ingredients; a crab-shell sesame flatbread",
        ],
      ],
    },
    {
      id: "amount-heading",
      type: "heading",
      level: 2,
      text: "How much to order, without weighing anything",
    },
    {
      id: "amount-p1",
      type: "paragraph",
      text: "Plate sizes are not standard between houses, so any figure in grams is a number for one restaurant rather than a rule. Order by rounds instead. A round is one plate of meat, one vegetable, and whatever is already in the pot. Make the first round deliberately smaller than you want: the pot needs time to reach a rolling boil, and a table that orders everything at once crowds a pot that has not got there yet.",
    },
    {
      id: "amount-table",
      type: "table",
      caption: "First round by table size, with what to leave out on purpose",
      columns: ["People", "Order now", "Order once the first round has gone", "Leave out on round one"],
      rows: [
        [
          "One",
          "A half portion if offered, otherwise one plate; one leaf vegetable; one dip",
          "A second plate, only if you finished the first without pausing",
          "Starch, frozen tofu, anything sold as a set",
        ],
        [
          "Two",
          "One plate of meat; one leaf vegetable; one absorbent item; two dips",
          "One more plate, and a second vegetable if the pot looks bare",
          "Starch. Order it later or it arrives cold",
        ],
        [
          "Three to four",
          "Two plates, ideally two cuts; two vegetables; one absorbent item; a dip each",
          "Meat one plate at a time, after seeing the first portions",
          "Noodles and dumplings until you know how much room is left",
        ],
        [
          "Five or more",
          "One plate per two people; three vegetables; two absorbent items",
          "Single plates only, so nobody waits on a shared platter",
          "A second pot, unless the table cannot reach one",
        ],
      ],
    },
    {
      id: "dip-heading",
      type: "heading",
      level: 2,
      text: "The dip is the seasoning, so treat it like one",
    },
    {
      id: "dip-p1",
      type: "paragraph",
      text: "Because the broth is restrained, the bowl beside you does the work a Sichuan pot does in the liquid. The classic Beijing combination named by the city's market regulator is short: sesame paste, fermented bean curd and chive-flower sauce. Sesame paste is the body; fermented bean curd brings salt and savoury depth; chive-flower sauce, made from fermented garlic-chive buds, brings the sharp edge that keeps a fatty mouthful from flattening out. That trio is a reference point rather than the only version - Yitiaolong's record describes several distinct dips, each blended from dozens of ingredients.",
    },
    {
      id: "dip-list-heading",
      type: "heading",
      level: 3,
      text: "How to handle the dip bowl in practice",
    },
    {
      id: "dip-list",
      type: "list",
      items: [
        "If it arrives already mixed, taste before adding anything. Many houses have balanced it and additions only make it saltier.",
        "If it arrives as plain sesame paste beside a condiment tray, the tray is the point. Add the other two a little at a time, stirring, and stop when it coats the back of a spoon.",
        "Chive-flower sauce is assertive. Add a little, taste it with the meat, then decide whether to add more.",
        "If you do not want sesame paste, ask what other dip the restaurant can provide.",
        "Do not thin the dip with broth unless the restaurant recommends it; adding broth makes the seasoning harder to control.",
        "Pickled sweet garlic is normally served beside the dip; eat it separately rather than stirring it into the bowl.",
      ],
    },
    {
      id: "cook-heading",
      type: "heading",
      level: 2,
      text: "Once the charcoal is lit",
    },
    {
      id: "cook-p1",
      type: "paragraph",
      text: "Beijing's market regulator says diners may follow a vegetables-before-meat order. Treat that as an optional way to start lighter and learn the pot, not as a food-safety requirement. If the restaurant gives a different sequence for its broth or ingredients, follow the staff's guidance.",
    },
    {
      id: "cook-list-heading",
      type: "heading",
      level: 3,
      text: "The sequence, and the two habits worth building",
    },
    {
      id: "cook-list",
      type: "list",
      items: [
        "Wait for the broth to return to a proper boil before each small batch, following the staff's instructions for that pot.",
        "If you choose the vegetables-first option, add cabbage stems before leaves and ask staff how long frozen tofu should remain in the pot.",
        "Then meat, a few slices at a time, spread out. A whole plate dropped in at once drops the temperature and welds itself into a lump.",
        "Keep one pair of chopsticks for raw meat and eat with a different pair. Beijing's disease-control guidance defines raw as anything still needing heat, cooked as anything you can eat directly, and asks for separate tools between the two. A shared pot is exactly where that applies.",
        "Use serving chopsticks if the house provides them. Beijing's health commission puts the rule simply: serve with the communal pair and eat with your own.",
        "If the broth needs skimming or topping up, ask the staff rather than diagnosing it yourself.",
      ],
    },
    {
      id: "cook-callout",
      type: "callout",
      title: "No authoritative seconds, colour or temperature endpoint",
      tone: "warning",
      body: "None of the official sources used here gives a validated number of seconds, colour test or temperature endpoint for thin mutton slices in a copper pot. The general guidance is to cook food thoroughly, but poultry, soup and broad 70-degree statements cannot be converted into a precise endpoint for this dish. Keep the broth boiling, add only a few slices at a time and follow the restaurant's cooking instructions. Children, older adults, pregnant people, immunocompromised diners and anyone who needs extra food-safety caution should not rely on a personal colour or seconds test: ask staff to handle or confirm thorough cooking, or choose a fully cooked dish.",
    },
    {
      id: "cook-p2",
      type: "paragraph",
      text: "Beijing's market regulator warns that hotpot broth boiled for a long time is relatively high in purines and fat, and advises people with gout or high blood lipids to be cautious about drinking it. If that applies to you, do not treat the broth as a drink; follow your clinician's dietary advice.",
    },
    {
      id: "lang-heading",
      type: "heading",
      level: 2,
      text: "Sentences that actually get used",
    },
    {
      id: "lang-table",
      type: "table",
      caption: "An ordering card for a copper-pot table",
      columns: ["What you want to say", "Chinese", "Roughly how it sounds"],
      rows: [
        ["Two people, one pot please", "两位，一个锅", "liang wei, yi ge guo"],
        ["Is this hand-cut fresh mutton, or a frozen roll?", "这是手切鲜羊肉还是冻羊肉卷？", "zhe shi shou qie xian yang rou hai shi dong yang rou juan"],
        ["Is it whole-cut mutton, with nothing added?", "是原切羊肉吗？没有添加别的吧？", "shi yuan qie yang rou ma, mei you tian jia bie de ba"],
        ["Which cut is this?", "这是哪个部位？", "zhe shi na ge bu wei"],
        ["Where is today's mutton from?", "今天的羊肉是哪儿的？", "jin tian de yang rou shi nar de"],
        ["One plate of leg, one of upper shoulder", "一盘羊腿肉，一盘上脑", "yi pan yang tui rou, yi pan shang nao"],
        ["Cabbage, crown daisy, frozen tofu", "白菜、茼蒿、冻豆腐", "bai cai, tong hao, dong dou fu"],
        ["Sesame dip, one each", "麻酱，一人一份", "ma jiang, yi ren yi fen"],
        ["More pickled garlic, please", "再来点糖蒜", "zai lai dian tang suan"],
        ["Could we have serving chopsticks?", "有公筷吗？", "you gong kuai ma"],
        ["Please top up the broth", "麻烦加点汤", "ma fan jia dian tang"],
        ["The flatbread now, please", "现在上烧饼", "xian zai shang shao bing"],
        ["That is enough, thank you", "够了，谢谢", "gou le, xie xie"],
      ],
    },
    {
      id: "repair-heading",
      type: "heading",
      level: 2,
      text: "When the plan breaks",
    },
    {
      id: "repair-table",
      type: "table",
      caption: "Four common failures and the move that fixes each",
      columns: ["The situation", "What is actually happening", "What to do"],
      rows: [
        [
          "You are alone and the pot looks built for six",
          "Portions are sized for sharing, so a solo diner over-orders by default",
          "Ask for a half portion, take one vegetable, skip the starch. If the house cannot split a portion, order one plate and one vegetable, then add a second later.",
        ],
        [
          "No English, no pictures, no numbers you recognise",
          "You are reading a document when the meal needs four decisions",
          "Use the leg-and-upper-shoulder line from the card above, name the vegetables and ask for sesame dip. Confirm which cuts and portions that restaurant actually offers.",
        ],
        [
          "The cut you wanted is sold out",
          "Availability varies by restaurant and day; a sold-out label does not prove anything about quality or preparation",
          "Ask which cuts are available now and how they were prepared, then choose from the answer.",
        ],
        [
          "The broth turns cloudy and grey halfway through",
          "You cannot determine the cause from appearance alone",
          "Ask staff whether the broth should be skimmed or topped up, then return to small batches.",
        ],
      ],
    },
    {
      id: "links",
      type: "internal-links",
      title: "Read next",
      items: [
        {
          label: "Your first shared meal in China",
          href: "/guides/first-shared-meal-in-china/",
          description: "The table mechanics this page assumes: who orders, how dishes are shared, how the bill works.",
        },
        {
          label: "Ordering a balanced first Hunan meal",
          href: "/guides/hunan-cuisine-balanced-first-meal/",
          description: "The same ordering problem where heat, not fat, is the variable to balance.",
        },
        {
          label: "How Guangzhou morning tea works",
          href: "/guides/how-guangzhou-morning-tea-works/",
          description: "Another meal where the order of operations matters more than the dish list.",
        },
        {
          label: "Building a regional food route across China",
          href: "/guides/china-regional-food-route/",
          description: "Where a Beijing copper pot fits across several regions rather than one city.",
        },
        {
          label: "How to pay in China as a tourist",
          href: "/guides/how-to-pay-in-china-as-a-tourist/",
          description: "Settling the bill at a busy counter, the last step of this workflow.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources",
      items: [
        {
          label: "A complete guide to old Beijing instant-boiled mutton",
          url: "https://scjgj.beijing.gov.cn/zwxx/scjgdt/202512/t20251215_4342165.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Consumer advisory on buying beef and mutton",
          url: "https://scjgj.beijing.gov.cn/hdjl/xfts/202001/t20200120_1619155.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Autumn and winter food-safety risk controls for caterers",
          url: "https://scjgj.beijing.gov.cn/zwxx/scjgdt/202510/t20251027_4241346.html",
          publisher: "Beijing Municipal Administration for Market Regulation",
          reviewedAt: "2026-08-23",
        },
        {
          label: "The Donglaishun instant-boiled mutton technique",
          url: "https://www.bjdch.gov.cn/ztzl/cyqn/jsmsjy/202407/t20240730_3762490.html",
          publisher: "Dongcheng District People's Government, Beijing",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Yangfang Shengli instant-boiled mutton, Changping intangible heritage",
          url: "https://www.beijing.gov.cn/renwen/bjgk/cpgk/cpfy/202304/t20230403_2965858.html",
          publisher: "Beijing Municipal Government portal",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Yitiaolong, China Time-honoured Brand record",
          url: "https://zhlzh.mofcom.gov.cn/news/entp_view/5037",
          publisher: "Ministry of Commerce of the People's Republic of China",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Beijing CDC reminder: food safety at festive meals",
          url: "https://www.beijing.gov.cn/fuwu/bmfw/sy/jrts/202402/t20240210_3561570.html",
          publisher: "Beijing Center for Disease Prevention and Control",
          reviewedAt: "2026-08-23",
        },
        {
          label: "Table manners: separate serving",
          url: "https://wjw.beijing.gov.cn/bmfw_20143/jkzs/jksh/202106/t20210623_2419757.html",
          publisher: "Beijing Municipal Health Commission",
          reviewedAt: "2026-08-23",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
