export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "Choose Chengdu Panda Base if you are staying in central Chengdu and want the simpler first visit, with established public-transport links, extensive visitor facilities and museum-style interpretation. Choose Dujiangyan Panda Valley if your trip already includes Dujiangyan or Qingcheng Mountain and the field-research setting matters more than city convenience. Neither venue can promise smaller crowds, closer views or more active pandas.",
    },
    {
      id: "quick-decision",
      type: "callout",
      title: "The short version",
      body: "For most first-time visitors based in Chengdu, the city base is the practical default. Panda Valley becomes the stronger fit when Dujiangyan is already part of the route—not simply because someone online calls it the quieter panda base.",
      tone: "decision",
    },
    {
      id: "before-you-compare",
      type: "heading",
      level: 2,
      text: "First, make sure you are comparing the right places",
    },
    {
      id: "names-explained",
      type: "paragraph",
      text: "Chengdu Research Base of Giant Panda Breeding is the large visitor site at 1375 Panda Avenue in Chenghua District. Panda Valley is its affiliated field research centre in Yutang, close to central Dujiangyan. The same organisation runs both, but they have different entrances, reservations and tickets.",
    },
    {
      id: "third-venue-warning",
      type: "callout",
      title: "There is a third, easily confused site",
      body: "The China Conservation and Research Center for the Giant Panda also has a Dujiangyan Base near Qingcheng Mountain, previously promoted as Dujiangyan Panda Park. It belongs to a different institution and is not Panda Valley in Yutang. Check the Chinese name and map pin before paying for a ticket or transfer.",
      tone: "warning",
    },
    {
      id: "at-a-glance",
      type: "table",
      caption: "The practical difference between Chengdu Panda Base and Panda Valley",
      columns: ["Decision point", "Chengdu Panda Base", "Dujiangyan Panda Valley"],
      rows: [
        ["Where it is", "Chenghua District, about 10 km from Tianfu Square according to the operator", "Yutang in Dujiangyan, about 50 km from Chengdu and 3 km from central Dujiangyan according to the operator"],
        ["Best fit", "A first panda visit while staying in Chengdu", "A Dujiangyan or Qingcheng Mountain stay, or a trip built around the field-research context"],
        ["Visitor emphasis", "A broad visitor complex with multiple themed areas, museums and service facilities", "An affiliated field centre focused on conservation, pre-release training, reintroduction research and nature education"],
        ["Transport planning", "Official metro-to-shuttle or bus combinations are published", "Requires a separate Dujiangyan transfer plan; verify the last leg for the travel date"],
        ["Time to protect", "Homeground planning judgment: reserve at least half a day rather than treating it as a quick stop", "Homeground planning judgment: reserve a substantial Dujiangyan time block, especially if starting in Chengdu"],
        ["Ticket relationship", "Separate real-name ticket", "Separate real-name ticket; the city-base ticket is not valid here"],
      ],
    },
    {
      id: "choose-city-base",
      type: "heading",
      level: 2,
      text: "Choose Chengdu Panda Base for the easier city-based visit",
    },
    {
      id: "city-base-fit",
      type: "paragraph",
      text: "The city base is not just one viewing enclosure. Its official plan divides the complex into four themed zones, with panda enclosures, indoor spaces, the Chengdu Giant Panda Museum and visitor services spread across the site. That breadth is useful when this is your first panda-focused visit, but it also means you should decide which entrance and areas matter before arrival.",
    },
    {
      id: "city-base-reasons",
      type: "list",
      items: [
        "The operator publishes public-transport combinations from Line 3 metro stations to the South and West gates.",
        "South and West gate visitor centres offer free luggage storage and loans of strollers, wheelchairs, umbrellas and walking sticks, subject to availability.",
        "An internal sightseeing bus can reduce some walking. Its current separate fare and operating arrangements should be checked before the visit.",
        "Museums and indoor display spaces give the day more structure, although individual buildings can close for maintenance or operational reasons.",
      ],
    },
    {
      id: "city-base-limits",
      type: "callout",
      title: "What convenience does not mean",
      body: "A Chengdu address does not make this a one-hour attraction. The site is extensive, transfers between zones take time, and a sightseeing-bus ticket does not remove queues or guarantee access to every stop.",
      tone: "neutral",
    },
    {
      id: "choose-panda-valley",
      type: "heading",
      level: 2,
      text: "Choose Panda Valley when Dujiangyan belongs in the trip",
    },
    {
      id: "panda-valley-fit",
      type: "paragraph",
      text: "Panda Valley's formal role is different. The operator describes it as a field research centre for breeding, conservation, rescue, pre-release training and reintroduction work, alongside nature education and ecological tourism. Its published visitor map includes ecological giant-panda enclosures, red-panda areas, landscaped water and rest zones. Open areas can change, so treat that map as an orientation tool rather than a promise that every zone will be available.",
    },
    {
      id: "panda-valley-reasons",
      type: "list",
      items: [
        "It fits naturally if you are already sleeping in Dujiangyan or continuing towards Qingcheng Mountain.",
        "The field-centre purpose gives the visit a distinct conservation and reintroduction context rather than duplicating the city base exactly.",
        "The operator places it close to central Dujiangyan, so a regional itinerary can be more coherent than a return journey from central Chengdu.",
        "It has its own map and booking channel; use those, not the city-base ticket page.",
      ],
    },
    {
      id: "panda-valley-limits",
      type: "callout",
      title: "Do not choose it on a crowd promise",
      body: "The official sources do not support claims that Panda Valley is always quiet, always offers closer views or always has more active animals. Visitor levels, open areas, weather and animal-care decisions vary.",
      tone: "warning",
    },
    {
      id: "experience-not-count",
      type: "heading",
      level: 2,
      text: "Compare the experience, not a promised panda count",
    },
    {
      id: "no-panda-count",
      type: "paragraph",
      text: "Neither official site promises how many giant pandas or red pandas a visitor will see on a particular day. Published animal totals can become outdated, and an animal may be indoors, resting or temporarily off view. A responsible comparison therefore starts with location, layout and interpretation—not a claim that one ticket buys more pandas.",
    },
    {
      id: "morning-expectations",
      type: "paragraph",
      text: "An early admission can create more schedule buffer and may reduce your exposure to the hottest part of a summer day, but it is not an animal-performance guarantee. In hot weather, the city base may move pandas indoors according to enclosure conditions and animal behaviour. Rain, maintenance and welfare needs can also change what is visible at either site.",
    },
    {
      id: "animal-welfare",
      type: "callout",
      title: "Visitor rules protect the animals at both sites",
      body: "Both venues require quiet behaviour, prohibit feeding or teasing animals, and ban drones and pets. Chengdu Panda Base additionally states that visitors must not use flash and must stay at least three metres from animals in free-roaming red-panda areas. At Panda Valley, follow the posted rules for every animal area open that day.",
      tone: "neutral",
    },
    {
      id: "booking-and-hours",
      type: "heading",
      level: 2,
      text: "Tickets and opening hours need a final official check",
    },
    {
      id: "current-booking-facts",
      type: "table",
      caption: "Official booking information reviewed on 11 August 2026",
      columns: ["Item", "Chengdu Panda Base", "Dujiangyan Panda Valley"],
      rows: [
        ["Current adult admission", "CNY 55", "CNY 55"],
        ["Booking", "Online, real-name reservation; currently bookable up to 14 days ahead and subject to availability", "Real-name booking required; use the Panda Valley official channel for the exact date"],
        ["Passport", "Accepted for booking and entry; carry the original document", "Accepted for booking and entry; carry the original document"],
        ["Current published hours", "A 19 February adjustment notice sets 16 March–31 October 2026: morning entry 07:30–12:00, afternoon entry 12:00–17:00; clearing begins at 18:00", "The Chinese and English official pages currently show inconsistent seasonal times; confirm in the official Panda Valley WeChat account"],
        ["Walk-up assumption", "Plan on advance online booking; on-site purchase is only for special cases unable to pay online and remains subject to availability", "Do not rely on buying at the gate"],
        ["Combined ticket", "No", "No; book separately"],
      ],
    },
    {
      id: "valley-page-conflict",
      type: "paragraph",
      text: "Panda Valley's official English page currently says tickets for the next seven days can be reserved and lists one set of seasonal hours. Its Chinese page omits that booking window and shows different timing and limited walk-up details, some tied to earlier date ranges. Because those first-party pages are not aligned, this guide does not turn either version into a 2026 guarantee. Check the official Panda Valley WeChat account for your date; the published enquiry number is 028-87296600.",
    },
    {
      id: "passport-process",
      type: "paragraph",
      text: "Use the passport number exactly as it appears in the document and carry the same original passport, even when a booking QR code is issued. The gate may still need to verify the document or its details. Names, document numbers and eligibility for discounted or free admission should be checked before payment.",
    },
    {
      id: "transport",
      type: "heading",
      level: 2,
      text: "The transport difference matters more than the ticket price",
    },
    {
      id: "city-transit",
      type: "list",
      items: [
        "For the West Gate, the operator currently lists Metro Line 3 to Chengdu Junqu General Hospital station, followed by shuttle bus 409; other bus combinations involve a walk.",
        "For the South Gate, it currently lists Metro Line 3 to Panda Avenue station and shuttle bus 408, plus alternatives from Zoo station.",
        "Routes and shuttle services can change with traffic and operations. Recheck the official transit page and choose the gate that matches your intended first zone.",
      ],
    },
    {
      id: "valley-transit",
      type: "list",
      items: [
        "Panda Valley is at 408 Yutang Section of Huanshan Tourism Road in Dujiangyan. Save the Chinese address and the official map pin.",
        "The operator references the Chengdu–Dujiangyan expressway, rail and local roads, but it does not publish the same detailed English step-by-step connection as the city base.",
        "Build the last leg from your actual Dujiangyan station or hotel. Do not depend on a fixed taxi duration, an old blog's bus number or a transfer that leaves no buffer.",
      ],
    },
    {
      id: "both-in-one-day",
      type: "heading",
      level: 2,
      text: "Should you visit both in one day?",
    },
    {
      id: "same-day-analysis",
      type: "paragraph",
      text: "Two separate reservations, a cross-city transfer and the size of the city base make a same-day double visit fragile. A private car can make the map look possible, but delays, entry windows and the time needed inside each site still compete. Seeing two facilities quickly is not automatically better than understanding one well.",
    },
    {
      id: "same-day-decision",
      type: "callout",
      title: "Homeground planning judgment",
      body: "Choose one venue for one day. Consider both only if pandas are the main purpose of the trip, you can secure separate reservations, and you are willing to give the two sites separate half-day blocks—preferably on different days or while staying in both Chengdu and Dujiangyan.",
      tone: "decision",
    },
    {
      id: "families-and-mobility",
      type: "heading",
      level: 2,
      text: "Families and travellers with limited walking stamina",
    },
    {
      id: "family-planning",
      type: "paragraph",
      text: "For a stroller, wheelchair or limited walking stamina, the city base has the clearer published support: loans at its visitor centres and a paid internal sightseeing bus. That does not make every route step-free or every vehicle immediately available. Panda Valley's ecological setting should not be treated as proof of either easy or difficult access; ask the venue about the exact open route for your date.",
    },
    {
      id: "mobility-checks",
      type: "list",
      items: [
        "Choose the entrance before booking onward transport; the city base has South and West gates.",
        "Use the official map to identify rest areas, visitor centres and the few exhibits that matter most.",
        "Leave time for security, identity checks, toilets and meals instead of calculating only walking distance.",
        "If a wheelchair, stroller or internal bus is essential, contact the venue rather than assuming availability.",
      ],
    },
    {
      id: "decision-rules",
      type: "heading",
      level: 2,
      text: "A simple way to choose",
    },
    {
      id: "decision-list",
      type: "list",
      ordered: true,
      items: [
        "Staying in Chengdu, seeing pandas once and protecting the rest of the day? Choose Chengdu Panda Base.",
        "Already staying in Dujiangyan or Qingcheng Mountain? Compare Panda Valley first because it reduces route backtracking.",
        "Want museums, extensive interpretation and more published visitor services? Choose Chengdu Panda Base.",
        "Most interested in a field centre's conservation and reintroduction role? Panda Valley is the more distinctive match.",
        "Choosing only because a post promises fewer people or closer pandas? Do not decide yet; those outcomes are not guaranteed.",
      ],
    },
    {
      id: "fact-label",
      type: "callout",
      title: "What is fact, and what is judgment?",
      body: "Locations, institutional relationships and the dated ticket rules above come from official sources. The recommendations about which venue fits a route, how much time to protect and whether to split the visits are Homeground planning judgments based on those facts.",
      tone: "neutral",
    },
    {
      id: "final-check",
      type: "heading",
      level: 2,
      text: "Recheck these details before you go",
    },
    {
      id: "final-check-list",
      type: "list",
      items: [
        "The exact venue name, Chinese address and map pin.",
        "The official ticket channel, entry period and passport details for every traveller.",
        "Seasonal opening hours, last entry and any temporary area closures.",
        "The current metro, shuttle, intercity rail or road connection for your chosen entrance.",
        "Heat, rain and other conditions that may change outdoor animal viewing.",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Keep planning your China trip",
      items: [
        {
          label: "Explore China",
          href: "/explore/",
          description: "Browse destination-led guides and comparisons.",
        },
        {
          label: "Is your China itinerary too rushed?",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Test whether adding Dujiangyan creates too much transfer pressure.",
        },
        {
          label: "Do you need a tour guide in China?",
          href: "/guides/do-you-need-a-tour-guide-in-china/",
          description: "Compare independent travel, targeted support and guided days.",
        },
        { label: "Read Chengdu through its greenway", href: "/guides/chengdu-greenway-city-ring/", description: "Choose a manageable section of Chengdu's ring greenway, connect it to transit and neighbourhood life, and keep a practical exit plan." },
        { label: "Choose a Leshan Giant Buddha visit", href: "/guides/leshan-giant-buddha-land-or-boat-visit/", description: "Compare the mountain route and river view, understand their separate tickets and weather risks, and plan the return to Leshan or Chengdu without relying on a boat." },
        { label: "Plan a Sanxingdui museum visit", href: "/guides/sanxingdui-museum-booking-and-gallery-order/", description: "Use the official inbound-visitor booking channel, reach Guanghan from Chengdu and follow a gallery order that builds context before the famous bronzes." },
      ],
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official sources",
      items: [
        {
          label: "Institutional introduction and locations",
          url: "https://www.panda.org.cn/en/about/introduction/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Chengdu Panda Base ticket rules",
          url: "https://www.panda.org.cn/en/service/ticket/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026 adjusted seasonal opening-time notice",
          url: "https://www.panda.org.cn/cn/news/notice/2026-02-19/8855.html",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Chengdu Panda Base public transport",
          url: "https://www.panda.org.cn/en/service/transit/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Chengdu Panda Base visitor notice",
          url: "https://m.panda.org.cn/en/service/notice/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Chengdu Panda Base sightseeing bus",
          url: "https://www.panda.org.cn/en/service/sightseeingbus/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Panda Valley introduction",
          url: "https://www.panda.org.cn/en/pandavalley/tour/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Panda Valley English ticket page",
          url: "https://www.panda.org.cn/en/pandavalley/tickets/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Panda Valley Chinese ticket and visitor-rules page",
          url: "https://www.panda.org.cn/cn/pandavalley/tickets/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Panda Valley visitor map",
          url: "https://www.panda.org.cn/en/pandavalley/map/",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Panda Valley address and arrival notice",
          url: "https://www.panda.org.cn/cn/news/notice/2024-09-24/8553.html",
          publisher: "Chengdu Research Base of Giant Panda Breeding",
          reviewedAt: "2026-08-11",
        },
        {
          label: "China Conservation and Research Center and its four bases",
          url: "https://www.forestry.gov.cn/c/www/zsdw/376046.jhtml",
          publisher: "National Forestry and Grassland Administration",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026 record locating the separate Dujiangyan Base in Qingchengshan Town",
          url: "https://www.forestry.gov.cn/lyj/1/htgk/20260512/670619.html",
          publisher: "National Forestry and Grassland Administration",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Government record using the former Dujiangyan Panda Park name",
          url: "https://www.gwytb.gov.cn/local/201609/t20160905_11559704.htm",
          publisher: "Taiwan Affairs Office of the State Council",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const;
