export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "如果住在成都市区，又是第一次专程看熊猫，成都熊猫基地通常更省心：公共交通信息更完整，游客设施和科普空间也更丰富。如果行程本来就包含都江堰或青城山，而且你更看重野放研究中心的定位，可以优先考虑都江堰熊猫谷。无论选哪一处，都无法保证当天人少、观看距离近或熊猫更活跃。",
    },
    {
      id: "quick-decision",
      type: "callout",
      title: "先给结论",
      body: "大多数住在成都、第一次看熊猫的旅客，可以把成都熊猫基地作为默认选项。当都江堰本来就在路线里时，熊猫谷的地理位置和研究定位更容易转化为实际优势；不要仅仅因为网上有人把它说成“更清静的熊猫基地”就做决定。",
      tone: "decision",
    },
    {
      id: "before-you-compare",
      type: "heading",
      level: 2,
      text: "比较之前，先确认你说的是哪一处",
    },
    {
      id: "names-explained",
      type: "paragraph",
      text: "成都大熊猫繁育研究基地位于成华区熊猫大道1375号，是通常所说的“成都熊猫基地”。熊猫谷则是它设在都江堰玉堂的野放繁育研究中心，靠近都江堰城区。两处属于同一机构，但入口、预约和门票彼此独立。",
    },
    {
      id: "third-venue-warning",
      type: "callout",
      title: "还有一处名称很容易混淆",
      body: "中国大熊猫保护研究中心也有一处都江堰基地，位于青城山镇，曾以“都江堰熊猫乐园”的名称对外介绍。它属于另一家机构，不是玉堂的熊猫谷。购买门票或接送服务前，务必核对中文全名和地图定位。",
      tone: "warning",
    },
    {
      id: "at-a-glance",
      type: "table",
      caption: "成都熊猫基地与都江堰熊猫谷的实际区别",
      columns: ["决策维度", "成都熊猫基地", "都江堰熊猫谷"],
      rows: [
        ["位置", "成华区；运营方资料称距天府广场约10公里", "都江堰玉堂；运营方资料称距成都约50公里、距都江堰城区约3公里"],
        ["更适合", "住在成都、第一次安排熊猫参观", "住在都江堰或青城山一带，或特别关注野放研究背景"],
        ["参观重点", "包含多个主题片区、博物馆和游客服务设施的综合园区", "以保护、野化训练、放归研究和自然教育为重点的附属野外研究中心"],
        ["交通规划", "官网公布了地铁转摆渡车或公交的组合", "需要单独规划都江堰段交通，并在出发前确认最后一段接驳"],
        ["预留时间", "Homeground 规划判断：至少留出半天，不要把它当作快速打卡点", "Homeground 规划判断：尤其从成都出发时，应为都江堰段预留一段较完整的时间"],
        ["门票关系", "单独实名购票", "单独实名购票；成都熊猫基地门票在此无效"],
      ],
    },
    {
      id: "choose-city-base",
      type: "heading",
      level: 2,
      text: "想要更省心的城市参观，选成都熊猫基地",
    },
    {
      id: "city-base-fit",
      type: "paragraph",
      text: "成都熊猫基地并非只有一个熊猫观赏区。按照官方布局，园区分为四个主题片区，熊猫馆舍、室内空间、成都大熊猫博物馆和游客服务设施分散在不同位置。丰富的内容很适合第一次以熊猫为主题的参观，但也意味着出发前最好先选定入口和最想看的片区。",
    },
    {
      id: "city-base-reasons",
      type: "list",
      items: [
        "运营方公布了从地铁3号线多个站点前往南门和西门的公交、摆渡车组合。",
        "南门和西门游客中心提供免费行李寄存，并可免费借用婴儿车、轮椅、雨伞和手杖，具体以现场余量为准。",
        "园内观光车可以减少部分步行，但需另行购票；票价和运行安排应在参观前再次确认。",
        "博物馆和室内展示空间能让参观更有层次，但个别建筑仍可能因维护或运营安排临时关闭。",
      ],
    },
    {
      id: "city-base-limits",
      type: "callout",
      title: "交通方便，不等于一小时逛完",
      body: "虽然位于成都市内，园区仍然很大。不同片区之间移动需要时间，观光车票也不能消除排队，更不能保证每一站和每一处场馆都正常开放。",
      tone: "neutral",
    },
    {
      id: "choose-panda-valley",
      type: "heading",
      level: 2,
      text: "都江堰本来就在路线里，可以优先考虑熊猫谷",
    },
    {
      id: "panda-valley-fit",
      type: "paragraph",
      text: "熊猫谷的正式职能与成都熊猫基地不同。运营方把它定义为承担繁育、保护、救护、野化训练和放归研究的野外研究中心，同时开展自然教育和生态旅游。官方导览图列有大熊猫生态兽舍、小熊猫区域、水景和休息空间。实际开放区域会调整，因此导览图适合用来了解空间布局，不应视为所有区域当天必开的承诺。",
    },
    {
      id: "panda-valley-reasons",
      type: "list",
      items: [
        "如果已经住在都江堰，或之后前往青城山，地理上更容易顺路安排。",
        "野外研究中心的职能为参观增加了保护与放归研究的背景，不是把成都熊猫基地简单复制一遍。",
        "官方位置资料显示，熊猫谷靠近都江堰城区；从行程规划看，把它放进都江堰区域行程，通常比从成都当天往返更连贯。",
        "熊猫谷有自己的导览图和预约渠道，应使用这些页面，而不是成都熊猫基地的购票入口。",
      ],
    },
    {
      id: "panda-valley-limits",
      type: "callout",
      title: "不要因为“肯定人少”而选择",
      body: "官方资料并不支持熊猫谷永远更清静、观看距离一定更近或动物总是更活跃的说法。客流、开放区域、天气和动物照护安排都会变化。",
      tone: "warning",
    },
    {
      id: "experience-not-count",
      type: "heading",
      level: 2,
      text: "比较实际参观体验，不要比较无法保证的熊猫数量",
    },
    {
      id: "no-panda-count",
      type: "paragraph",
      text: "两处官网都不会承诺某一天能看到多少只大熊猫或小熊猫。官方曾公布的动物数量可能已经变化，动物也可能在室内、休息或暂不展示。可靠的比较应该从位置、空间和科普定位开始，而不是声称哪张票“能看到更多熊猫”。",
    },
    {
      id: "morning-expectations",
      type: "paragraph",
      text: "早点入园可以为当天留出更多缓冲，夏天也能减少在最热时段户外停留的时间，但不能因此保证熊猫会更活跃。高温时，成都熊猫基地可能根据馆舍条件和动物行为将熊猫引导回室内；降雨、维护和动物福利安排也会改变两处当天能看到的内容。",
    },
    {
      id: "animal-welfare",
      type: "callout",
      title: "两处都要遵守动物福利规则",
      body: "两处都要求低声参观，不得投喂或逗弄动物，并禁止携带宠物和使用无人机。成都熊猫基地的游客须知还明确禁止闪光灯，并要求在小熊猫自由活动区域与动物保持至少3米距离。熊猫谷当天开放的动物区域，则应以现场标识和工作人员指引为准。",
      tone: "neutral",
    },
    {
      id: "booking-and-hours",
      type: "heading",
      level: 2,
      text: "门票和开放时间必须在出发前再查一次",
    },
    {
      id: "current-booking-facts",
      type: "table",
      caption: "截至2026年8月11日核查到的官方预约信息",
      columns: ["项目", "成都熊猫基地", "都江堰熊猫谷"],
      rows: [
        ["成人票现价", "55元", "55元"],
        ["预约", "线上实名预约；目前最多可提前14天购买，售完为止", "实行实名预约；具体日期以“熊猫谷”官方渠道为准"],
        ["护照", "可用于预约和入园，须携带原件", "可用于预约和入园，须携带原件"],
        ["当前公布时间", "2月19日调整公告规定，2026年3月16日至10月31日：上午票7:30–12:00入园，下午票12:00–17:00入园，18:00开始清园", "中英文官网目前显示的季节时间不一致，应在“熊猫谷”官方微信公众号确认"],
        ["现场购票", "按提前线上预约规划；确因特殊原因无法线上支付时，现场购票仍取决于是否有余票", "不要把现场买票作为方案"],
        ["联票", "不提供联票", "不提供联票；需单独预约"],
      ],
    },
    {
      id: "valley-page-conflict",
      type: "paragraph",
      text: "熊猫谷英文官网目前注明可预约未来7日内的门票，并列出一组季节开放时间；中文页面没有写明这一预约窗口，且显示的开放时间和特殊现场购票说明与英文页不同，其中部分还对应较早的日期范围。由于两组一手资料尚未同步，本文不把其中任何一版写成2026年的确定规则。请按实际日期查看“熊猫谷”官方微信公众号；官网公布的咨询电话为028-87296600。",
    },
    {
      id: "passport-process",
      type: "paragraph",
      text: "预约时按护照所示准确填写证件号码；即使已经生成预约二维码，也应携带同一本护照原件，现场仍可能核验证件或证件信息。付款前，还应核对姓名和证件号码，并确认是否符合半价或免票条件。",
    },
    {
      id: "transport",
      type: "heading",
      level: 2,
      text: "真正拉开差距的是交通，而不是票价",
    },
    {
      id: "city-transit",
      type: "list",
      items: [
        "前往西门，官网目前列出地铁3号线军区总医院站转409路摆渡车；另有需要步行的公交组合。",
        "前往南门，官网目前列出地铁3号线熊猫大道站转408路摆渡车，也有从动物园站换乘公交的方案。",
        "线路和摆渡服务可能随交通与运营调整。出发前重查官方交通页，并根据计划先看的片区选择对应入口。",
      ],
    },
    {
      id: "valley-transit",
      type: "list",
      items: [
        "熊猫谷的官方游览地址为都江堰市环山旅游路玉堂段408号；请保存中文地址和官方地图定位。",
        "运营方提到成灌高速、成灌快铁和当地道路，但没有像成都熊猫基地那样提供完整的英文逐段公共交通说明。",
        "最后一段应根据你实际抵达的都江堰车站或入住酒店来规划。不要依赖固定的打车时长、旧攻略里的公交编号，也不要安排完全没有缓冲的换乘。",
      ],
    },
    {
      id: "both-in-one-day",
      type: "heading",
      level: 2,
      text: "能不能一天看两处？",
    },
    {
      id: "same-day-analysis",
      type: "paragraph",
      text: "两套独立预约、跨城移动，再加上成都熊猫基地本身的规模，会让一天连看两处的计划很容易被延误打乱。即使包车，地图上看似可行的安排仍会受到延误、入园时段和实际参观时间的挤压。匆匆看完两处场馆，并不一定比认真理解一处更有价值。",
    },
    {
      id: "same-day-decision",
      type: "callout",
      title: "Homeground规划判断",
      body: "一天只选一处。只有当熊猫是整趟旅行的核心、两边都能预约成功，而且能分别留出半天时，才考虑两处都去。最好分成两天；如果行程分别在成都和都江堰住宿，再各自就近安排。",
      tone: "decision",
    },
    {
      id: "families-and-mobility",
      type: "heading",
      level: 2,
      text: "亲子家庭和步行耐力有限的旅客",
    },
    {
      id: "family-planning",
      type: "paragraph",
      text: "如果需要婴儿车、轮椅或减少步行，成都熊猫基地公开的信息更完整：游客中心可借用相关设备，园内另有付费观光车。但这并不代表每条路线都无障碍，也不代表车辆随到随有。熊猫谷的生态环境本身既不能证明“很好走”，也不能证明“很难走”；应向场馆询问当天实际开放路线。",
    },
    {
      id: "mobility-checks",
      type: "list",
      items: [
        "预订后续交通前先选入口；成都熊猫基地有南门和西门。",
        "用官方地图标出休息区、游客中心和最想看的少数场馆。",
        "除了步行，还要给安检、证件核验、卫生间和用餐留时间。",
        "如果轮椅、婴儿车或观光车是必要条件，应直接联系场馆确认，不要假定一定有余量。",
      ],
    },
    {
      id: "decision-rules",
      type: "heading",
      level: 2,
      text: "用五个问题做决定",
    },
    {
      id: "decision-list",
      type: "list",
      ordered: true,
      items: [
        "住在成都，只安排一次熊猫参观，还想为当天其他活动留出时间？选成都熊猫基地。",
        "已经住在都江堰或青城山？先比较熊猫谷，因为它能减少折返。",
        "更想看博物馆、系统科普和较完整的游客设施？选成都熊猫基地。",
        "最在意野外研究中心的保护与放归职能？熊猫谷的定位更独特。",
        "只是因为一篇帖子承诺“人少、看得近”？先不要决定，因为这些结果没有保证。",
      ],
    },
    {
      id: "fact-label",
      type: "callout",
      title: "哪些是事实，哪些是判断？",
      body: "地点、机构关系和上文标有日期的票务规则来自官方资料；关于哪一处更适合某条路线、需要预留多久、是否应分开参观，则是 Homeground 基于这些事实给出的规划判断。",
      tone: "neutral",
    },
    {
      id: "final-check",
      type: "heading",
      level: 2,
      text: "出发前最后核对",
    },
    {
      id: "final-check-list",
      type: "list",
      items: [
        "场馆的准确名称、中文地址和地图定位。",
        "每位旅客的官方购票渠道、入园时段和护照信息。",
        "季节开放时间、停止入园时间和临时关闭区域。",
        "前往所选入口的最新地铁、摆渡车、城际铁路或公路路线。",
        "可能影响户外动物观赏的高温、降雨等天气条件。",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "继续规划中国旅行",
      items: [
        {
          label: "探索中国",
          href: "/zh/explore/",
          description: "浏览以目的地为核心的指南和比较文章。",
        },
        {
          label: "你的中国行程是不是太赶？",
          href: "/zh/guides/is-your-china-itinerary-too-rushed/",
          description: "检查加入都江堰后，转场压力是否过高。",
        },
        {
          label: "去中国旅行需要导游吗？",
          href: "/zh/guides/do-you-need-a-tour-guide-in-china/",
          description: "比较自由行、局部协助和单日导览。",
        },
      ],
    },
    {
      id: "official-sources",
      type: "sources",
      title: "官方来源",
      items: [
        {
          label: "机构介绍与地点",
          url: "https://www.panda.org.cn/en/about/introduction/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "成都熊猫基地英文票务规则",
          url: "https://www.panda.org.cn/en/service/ticket/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026年夏季开闭园时间调整公告",
          url: "https://www.panda.org.cn/cn/news/notice/2026-02-19/8855.html",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "成都熊猫基地公共交通",
          url: "https://www.panda.org.cn/en/service/transit/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "成都熊猫基地游客须知",
          url: "https://m.panda.org.cn/en/service/notice/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "成都熊猫基地观光车服务",
          url: "https://www.panda.org.cn/en/service/sightseeingbus/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "熊猫谷介绍",
          url: "https://www.panda.org.cn/en/pandavalley/tour/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "熊猫谷英文票务页",
          url: "https://www.panda.org.cn/en/pandavalley/tickets/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "熊猫谷中文票务与游览规则",
          url: "https://www.panda.org.cn/cn/pandavalley/tickets/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "熊猫谷导览地图",
          url: "https://www.panda.org.cn/en/pandavalley/map/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "熊猫谷地址与到达提示",
          url: "https://www.panda.org.cn/cn/news/notice/2024-09-24/8553.html",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-11",
        },
        {
          label: "中国大熊猫保护研究中心及四个基地",
          url: "https://www.forestry.gov.cn/c/www/zsdw/376046.jhtml",
          publisher: "国家林业和草原局",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026年资料：另一处都江堰基地位于青城山镇",
          url: "https://www.forestry.gov.cn/lyj/1/htgk/20260512/670619.html",
          publisher: "国家林业和草原局",
          reviewedAt: "2026-08-11",
        },
        {
          label: "使用“都江堰熊猫乐园”旧称的政府资料",
          url: "https://www.gwytb.gov.cn/local/201609/t20160905_11559704.htm",
          publisher: "国务院台湾事务办公室",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const;
