import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "Give every proposed stop exactly one structural role before assigning nights. Use day trip for a visit with no local hotel night: either return to the same room or pass through with bags to the next confirmed base. Exactly one local hotel night always remains one overnight, even when the traveller leaves that room for both evening and morning activities. A true base retains the same local room beyond one night and supports repeated local starts. Remove the stop when its purpose is replaceable or access is confirmed unworkable. If a controlling fact is not yet published or searchable, keep a provisional range between roles until a named decision deadline.",
    },
    {
      id: "four-roles",
      type: "comparison",
      title: "Four outcomes for one candidate stop",
      columns: [
        { heading: "Day trip", body: "Use no local hotel night. Return to the same room, or carry bags through the visit to the next confirmed base." },
        { heading: "One overnight", body: "Use exactly one local hotel night for a named cross-night, split-visit, recovery or forward-route gain." },
        { heading: "True base", body: "Retain the same local room beyond one night because repeated starts support several priorities or a regional cluster." },
        { heading: "Remove", body: "Drop the stop when it adds no distinct purpose, access is confirmed unworkable or its decision deadline passes without a viable chain." },
      ],
    },
    {
      id: "scope",
      type: "callout",
      tone: "neutral",
      title: "What this owner decides",
      body: "This guide owns the general choice among a no-local-night visit, exactly one overnight, a true base with repeated local starts and removal; it also compares returning-hub and forward-base geometry. It does not prescribe city combinations, train numbers, universal night counts or a public Route Reality score. Named destination guides still own local access and accommodation decisions; the rushed-itinerary guide owns whole-trip overload.",
    },
    { id: "role-heading", type: "heading", level: 2, text: "Give the stop a job before giving it a night" },
    {
      id: "role-copy",
      type: "paragraph",
      text: "A place name is not a reason to change hotels. Write the one thing the stop contributes that the rest of the route cannot replace: a timed collection, a landscape that needs early or late light, two unrelated local priorities, a necessary gateway, or a deliberate recovery night. Then test the smallest role that protects that purpose. Starting with ‘two nights here’ hides the decision; starting with the purpose shows whether the stop should be a spoke, an overnight, a base or no stop at all.",
    },
    {
      id: "role-proof",
      type: "table",
      caption: "The minimum proof each role needs",
      columns: ["Candidate role", "Evidence that supports it", "Evidence that defeats it"],
      rows: [
        ["Day trip", "A complete dated no-local-night chain, one protected purpose and a recoverable return or onward option", "The last edge is confirmed fragile, no workable bag path exists by the decision deadline, or the core value requires a night"],
        ["One overnight", "Exactly one local hotel night protects a named evening, morning, split-visit, recovery or forward-route gain", "The traveller arrives late, leaves early and gains nothing unavailable without the night"],
        ["True base", "The same local room is retained beyond one night and repeated starts support independent priorities or a substantial multi-block purpose", "The room serves one optional sight and creates another immediate checkout"],
        ["Remove", "The main route becomes stronger without the stop and loses no non-replaceable purpose", "A protected priority genuinely disappears and cannot move elsewhere"],
      ],
    },
    {
      id: "provisional-state",
      type: "callout",
      tone: "warning",
      title: "Unknown is a valid planning state",
      body: "If the venue has not yet published the relevant session, the transport date is not yet searchable or the hotel has not answered a luggage question, record a role range and status: provisional. List every missing field, its verifier and a decision deadline before a cancellation or route commitment becomes costly. If the controlling option is later confirmed unavailable—or the deadline passes without a viable answer—replace or remove the purpose unless another independently valuable role survives. A night never repairs an unavailable anchor by itself.",
    },
    { id: "block-heading", type: "heading", level: 2, text: "Count the whole hotel-door block, not the train minutes" },
    {
      id: "block-copy",
      type: "paragraph",
      text: "China Railway 12306 lets you search a specific origin, destination and date. That result is one edge of the route, not the whole excursion. A realistic block begins when the traveller leaves the room and ends when the traveller reaches the next useful door. It includes the correct station, the station approach, identity and security processes, waiting, the trip itself, destination transport, luggage and the fixed return when the room remains elsewhere. Do not invent one national station-arrival margin: 12306 says sales and ticket checks stop before departure and asks passengers to allow for station processes, while the exact cut-off belongs to the station and service.",
    },
    {
      id: "block-ledger",
      type: "table",
      caption: "Trace every route variant through its ending room door",
      columns: ["Route variant", "Complete chain", "Distinct burden to record"],
      rows: [
        ["Returning day trip", "Room A → exact departure node → candidate purpose → selected return → Room A", "Both local legs, station processes, purpose window, leave-by point and a later workable return"],
        ["Forward no-night visit", "Checkout Room A → bags → candidate purpose → bags → selected onward service → arrival-side leg → Room B", "Every bag handoff, storage opening, selected services and protection for the Room B booking"],
        ["Returning overnight; Room A retained", "Room A remains paid → day bag → candidate room → evening/sleep/morning → checkout → selected return → Room A", "Two concurrent rooms and rates, candidate check-in, next-day return and what happens if either room fails"],
        ["Forward overnight", "Checkout Room A → bags → candidate room/purpose → sleep/morning → bags and checkout → selected onward service → arrival-side leg → Room B", "Both hotel handoffs, purpose windows, every local edge and Room B arrival"],
        ["True base", "Checkout Room A → Base Room B → repeated Room B–priority–Room B cycles beyond one night → final checkout/bags → selected onward service → arrival-side leg → ending room", "All repeated starts and returns, final departure chain, recovery blocks and the final room door"],
      ],
    },
    {
      id: "no-fixed-tax",
      type: "callout",
      tone: "decision",
      title: "Use a ledger, not a universal transfer tax",
      body: "Homeground's editorial method starts every intercity change at zero sightseeing blocks and adds one only after the real chain leaves protected local time. It does not assign every move the same number of hours. A station beside one hotel and a mountain gate beyond several transfers cannot share a credible national average.",
    },
    { id: "day-trip-heading", type: "heading", level: 2, text: "A day trip must survive its final edge, not merely reach the destination" },
    {
      id: "day-trip-copy",
      type: "paragraph",
      text: "Here, day trip means the candidate gets no local hotel night. The common version returns to a useful existing room: bags stay put, one coherent purpose fits between arrival and departure, and the return does not sit on the last possible chain. A forward no-night visit is also possible, but checkout, carried or stored bags and the onward base become part of the same test. Neither version succeeds merely because one fast service exists. Exact station pairs, local transport, venue entry and a recoverable return or onward edge must all work on the same date.",
    },
    {
      id: "day-trip-gates",
      type: "list",
      ordered: true,
      items: [
        "Name the exact starting room, ending room and every departure or arrival node; a city with several railway stations is not one transport node.",
        "Protect the main purpose first, including its reservation window, last entry and the trip from the arrival station.",
        "Choose the attraction leave-by time before choosing the return or onward service, then add bag collection, station entry and the final trip to the ending room.",
        "Identify a real recovery option. A later service is useful only if it still reaches a node from which the group can reach its confirmed room safely.",
        "Keep any second activity replaceable. The day trip should still succeed when weather, queues or fatigue remove it.",
      ],
    },
    {
      id: "suzhou-example",
      type: "callout",
      tone: "neutral",
      title: "Method example: Shanghai room, Suzhou priority",
      body: "Shanghai and Suzhou are often treated as a simple fast-rail pair, yet Shanghai's official guide lists several railway stations and Suzhou Museum uses dated reservation and entry notices. A hypothetical filled test records the Shanghai room door, exact outward stations and selected service status, the museum session and passport process, both local legs, a leave-by point, the selected return and one later workable recovery, ending back at the same room. If every edge is confirmed, classify it as a returning day trip. If the later recovery vanishes, keep the result provisional or remove the visit; do not call it easy. A 2026 Suzhou metro adjustment shows why that local last leg needs a fresh check.",
    },
    {
      id: "day-trip-recovery",
      type: "table",
      caption: "Repair a day trip without endangering the main route",
      columns: ["Failure", "Immediate response", "Architecture response"],
      rows: [
        ["Outbound delay reduces the visit", "Keep the primary purpose and delete the optional second stop", "Returning form: retain the hub only if a safe return remains. Forward form: protect the onward service, baggage chain and Room B arrival; skip the candidate visit if that complete chain no longer fits"],
        ["Timed entry is not yet released", "Keep the role provisional and do not start until the return or onward chain and replacement are workable", "Set a decision deadline; a night is considered only when it has independent cross-night value"],
        ["Timed entry is confirmed unavailable", "Use a replaceable local activity only if the return or onward chain still works", "Remove the visit if no independent purpose survives; adding a night does not restore the missing anchor"],
        ["Return or onward recovery disappears before departure", "Do not start, or leave early on the last already-verified safe option", "Convert to an overnight only with a confirmed room and next-day route; otherwise remove the visit"],
        ["The verified edge disappears after arrival", "Stop optional sightseeing, contact the named operator and secure confirmed safe transport or accommodation before remaining options close", "Protect the next fixed booking, notify the affected hotel and revalidate the downstream route; never force an unverified late connection"],
      ],
    },
    { id: "overnight-heading", type: "heading", level: 2, text: "One overnight is the hardest role to justify" },
    {
      id: "overnight-copy",
      type: "paragraph",
      text: "One overnight means exactly one local hotel night, so it always remains the one-overnight role even if the traveller uses that room before an evening activity and again before a morning one. Its handling depends on geometry. A forward overnight can require checkout from the old base, luggage delivery or storage, the intercity leg, a wait for the new room, one sleep, another checkout and another luggage decision. A returning overnight can keep the original room and use a day bag, trading those handoffs for a second room cost and a next-day return; if the original room is released, add its checkout and later check-in instead. Write the actual actions, not a fixed penalty. The night still needs a named early, late, split-visit, recovery or forward-route gain.",
    },
    {
      id: "overnight-ledger",
      type: "table",
      caption: "Make one night prove a specific gain",
      columns: ["Question", "Keep the night when…", "Downgrade or remove it when…"],
      rows: [
        ["What changes after day visitors leave?", "A named evening activity or lawful late access is central to the trip", "The plan is simply dinner and sleep after a late arrival"],
        ["What changes before they arrive?", "A confirmed early access period, landscape window or morning appointment matters", "The group will not use the morning or the access is unconfirmed"],
        ["Does it split a demanding visit?", "Two shorter local blocks materially improve walking, weather or recovery", "Both blocks repeat the same optional experience"],
        ["Does it move the route forward?", "The next confirmed segment departs naturally from this stop", "A return to the previous base remains necessary; test a returning overnight with room overlap instead"],
        ["Can the night fail safely?", "A late arrival still leaves a room, a simple evening and a workable next morning", "One delay destroys the only local purpose and the following transfer"],
      ],
    },
    {
      id: "huangshan-example",
      type: "callout",
      tone: "neutral",
      title: "Method example: a Huangshan mountain night",
      body: "Huangshan's official transport page ties internal shuttle boundaries to ropeway operation and directs travellers to live cross-city notices. A mountain hotel page describes access to morning and evening viewpoints. Those sources establish a real cross-night purpose and a hard operating edge; they do not promise a visible sunrise, good weather or an open route. One night can be rational when the traveller values the location even if the sky disappoints. If the only aim is one daytime highlight, the gateway-base decision should be tested again rather than treating a mountain room as automatic.",
    },
    {
      id: "overnight-recovery",
      type: "table",
      caption: "One-night-stop failure recovery",
      columns: ["What fails", "Protect first", "What not to force"],
      rows: [
        ["Arrival is too late for the evening value", "Room access, food, rest and the next confirmed departure", "A rushed night activity simply to justify the hotel"],
        ["The morning anchor closes or weather defeats it", "Any safe indoor or low-dependency alternative already verified", "A second unverified excursion before checkout"],
        ["The property cannot hold bags as expected", "Keep bags with the traveller or use a confirmed official facility", "Leaving luggage on an assumed policy"],
        ["The room is unavailable, cancelled or refuses check-in", "Contact the property and booking channel, keep the group together and secure confirmed safe accommodation or transport", "An unverified late connection, closed route or informal room simply to preserve the stop"],
        ["The onward segment changes", "Pause optional activity, contact the operator, protect the next fixed booking and recalculate from the exact new node", "Returning to the previous base or moving late merely to preserve the old diagram"],
      ],
    },
    { id: "base-heading", type: "heading", level: 2, text: "A true base needs a cluster, not one famous sight" },
    {
      id: "base-copy",
      type: "paragraph",
      text: "A true base is not any city where the route sleeps. It retains the same local room beyond one night, separating it mechanically from a one-night stop even when that shorter stop has evening and morning departures. The room should make repeated local starts cleaner than they would be elsewhere. As a Homeground heuristic, look for at least two independent priorities, or one substantial multi-block purpose plus a clear gateway or recovery function. This is not an official minimum-night rule. A traveller with a mobility constraint may gain enough from stability with fewer sights; a light-bag traveller may need stronger local value before extending the stay into a base.",
    },
    {
      id: "base-test",
      type: "table",
      caption: "Evidence that a stop has earned base status",
      columns: ["Base evidence", "Strong signal", "False positive"],
      rows: [
        ["Independent priorities", "Two activities remain worthwhile if the other closes", "Two versions of the same replaceable attraction"],
        ["Local geography", "The room reduces repeated trips to the exact activity nodes", "The city label is central but the hotel is far from every departure"],
        ["Time value", "More than one protected local block begins without an intercity arrival", "Every day starts with another long spoke"],
        ["Forward route", "The next gateway or region lies naturally ahead", "The traveller later backtracks to the old gateway"],
      ],
    },
    {
      id: "guilin-yangshuo-example",
      type: "callout",
      tone: "neutral",
      title: "Method example: Guilin and Yangshuo are not single nodes",
      body: "The Li River scenic area's official transport page distinguishes railway stations, county access and several wharves, with some local services adjusted around arriving trains or boats. Therefore ‘stay in Yangshuo’ is not yet a base plan. The room must match the confirmed activities and handoffs. One attraction may justify a focused visit; several independent local priorities that remove repeated returns may justify a base. The named Guilin–Yangshuo transport and accommodation guides should execute that local decision.",
    },
    { id: "remove-heading", type: "heading", level: 2, text: "Remove a stop when it survives only on optimistic maths" },
    {
      id: "remove-copy",
      type: "paragraph",
      text: "Removal is not a verdict that a place lacks value. It means the stop does not earn scarce time inside this route. Begin with the smallest correction: turn a false base into one overnight, an unjustified overnight into a day trip, or a fragile day trip into a future-trip note. Remove it completely when the distinct purpose is weak, critical access is confirmed unworkable or remains unresolved at the named decision deadline, the route needs its recovery block, or the stop forces a backtrack that the traveller would not accept if it were shown honestly.",
    },
    {
      id: "remove-checks",
      type: "list",
      ordered: false,
      items: [
        "Delete the stop in a copy of the route. If no protected priority disappears, keep it deleted.",
        "Replace its activity with a lower-dependency experience in an existing base. If the trip still meets the same purpose, avoid the hotel move.",
        "Ask what absorbs a delay. If the answer is the next city's only full day, the optional stop is spending recovery the route does not own.",
        "Keep a rejected stop in a future-trip list, not as an unbooked promise inside the current itinerary.",
      ],
    },
    {
      id: "overload-boundary",
      type: "callout",
      tone: "warning",
      title: "Architecture and overload are different checks",
      body: "This four-role test decides what each stop should be. Afterward, the rushed-itinerary owner must still test the complete trip's usable days, consecutive transfers, fatigue and buffers. A logically classified route can still contain too many logically classified stops.",
    },
    { id: "geometry-heading", type: "heading", level: 2, text: "Onward geometry can reverse the answer" },
    {
      id: "geometry-copy",
      type: "paragraph",
      text: "The same place can be a sensible day trip in one route and a sensible overnight in another. If the traveller returns to the same international gateway, keeping one hub may avoid duplicated hotel handling. If the next major city lies naturally beyond the candidate stop, returning to the old room may create the very backtrack the hub was meant to prevent. Compare the confirmed arrival and departure gateways, not only the sightseeing map. An open-jaw flight can support a forward chain, but only after the real airfare, baggage, airport and change conditions are compared.",
    },
    {
      id: "geometry-table",
      type: "table",
      caption: "Route shape changes the preferred role",
      columns: ["Shape", "First role to test", "Reason to switch"],
      rows: [
        ["Out and back to the same room", "Day trip", "The fixed return is fragile or the cross-night value is essential"],
        ["Candidate lies on the confirmed forward corridor", "Forward no-night visit", "Use one night only for an independent cross-night or recovery gain; retain the room beyond that night to test true-base status"],
        ["Several spokes share one practical station and room", "True base (hub)", "Repeated station approaches consume the protected days"],
        ["A branch ends away from the onward gateway", "Remove or day trip", "The branch carries a non-replaceable priority worth the backtrack"],
      ],
    },
    { id: "traveller-heading", type: "heading", level: 2, text: "Traveller constraints change the cost even when the map stays the same" },
    {
      id: "traveller-scenarios",
      type: "comparison",
      title: "Three travellers, three different thresholds",
      columns: [
        { heading: "Light-bag first visit", body: "Two adults can accept one efficient forward move, but should still refuse a one-night stop that protects no distinct experience. Fast packing does not create local value." },
        { heading: "Family or mobility constraint", body: "A familiar room, predictable breakfast and fewer luggage handoffs may outweigh a theoretical saving. Test fewer, stronger bases and keep day trips replaceable." },
        { heading: "Early or late specialist interest", body: "A photographer, hiker or cultural visitor may rationally pay the one-night friction for a lawful morning, evening or multi-part visit that defines the trip." },
      ],
    },
    {
      id: "traveller-copy",
      type: "paragraph",
      text: "Do not translate these differences into a universal pace label. Write the operational constraint: who carries each bag, whether a child can handle two early departures, whether stairs or long station walks are workable, how the group recovers after disruption, and which missed experience would actually matter. The preferred structure should change when those facts change.",
    },
    { id: "verify-heading", type: "heading", level: 2, text: "Book only after the architecture passes six gates" },
    {
      id: "verify-workflow",
      type: "list",
      ordered: true,
      items: [
        "Purpose gate: name the non-replaceable purpose and assign the smallest role that protects it.",
        "Access gate: verify the dated venue rule, exact station or terminal, each local leg and the return or onward recovery.",
        "Lodging gate: verify the booked rate's cancellation terms, check-in and checkout, passport acceptance, room access and luggage handling directly with the property or platform contract.",
        "Fatigue gate: remove any activity that depends on the group performing perfectly after an arrival, checkout or long outing.",
        "Gateway gate: compare the final base with the actual international departure and add the flight-protection buffer outside this stop-level calculation.",
        "Recheck gate: repeat every dynamic check before the free-cancellation deadline and again shortly before travel.",
      ],
    },
    {
      id: "final-ledger",
      type: "table",
      caption: "The final route record should make every assumption visible",
      columns: ["Record", "What to write", "Status and recovery", "Primary verifier"],
      rows: [
        ["Role", "Day trip, one overnight, true base, remove, or a range between those roles", "Confirmed or provisional; state the missing field", "Homeground editorial decision from the completed ledger"],
        ["Every transport edge", "Start and end doors/nodes; scheduled departure/arrival for each selected service; a conservative range for every local, wait and transfer edge", "Booking/confirmation state, buffer and one workable recovery", "12306 and each named local operator, with checked date"],
        ["Anchor", "Reservation, entry document, arrival window, closure and replacement", "Confirmed, unavailable or unknown; latest safe leave-by point", "The venue's current official notice, with checked date"],
        ["Rooms and bags", "Every concurrent property and booked rate, check-in/out, each bag delivery/collection and ending room", "Each cancellation deadline and confirmed fallback", "Each property or contracted booking channel, with checked date"],
        ["Switch conditions", "Every missing field and change that would reclassify or delete the stop", "Decision/recheck deadline, next action and downstream booking protected", "Each official source that controls a condition"],
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      tone: "warning",
      title: "Live facts remain a final verification layer",
      body: "Rail inventory, station calls, attraction sessions, local last services, mountain access, hotel rates and cancellation terms can change. Holiday notices can override normal rules. This page gives the decision model; it never guarantees a service, room, view, ticket or transfer for an unsearched date.",
    },
    {
      id: "help-cta",
      type: "callout",
      tone: "decision",
      title: "Want a human to test the weak stop?",
      body: "Leave your dates, party size, approximate budget, arrival and departure gateways, candidate hotels and non-negotiable activities. Homeground can show which stop needs a verified day trip, one night, a real base or removal without pretending an unpublished timetable is confirmed.",
    },
    {
      id: "more-planning",
      type: "internal-links",
      title: "Continue planning",
      items: [
        { label: "Start with the first-trip planner", href: "/plan/", description: "Choose the next route decision after classifying each stop." },
        { label: "Check whether the complete route is too rushed", href: "/guides/is-your-china-itinerary-too-rushed/", description: "Test usable days, consecutive transfers and buffers after the stop-level decision." },
        { label: "Compare open-jaw and return gateways", href: "/guides/china-open-jaw-flights-route-planning/", description: "See whether different entry and exit cities remove a backtrack." },
        { label: "Build the route before rail inventory opens", href: "/guides/china-itinerary-booking-dependency-order/", description: "Keep the structure provisional until dated transport and fixed visits become executable." },
        { label: "Choose a hotel that supports daily departures", href: "/guides/china-hotel-near-metro/", description: "Test the actual address against the station and activity nodes." },
        { label: "Compare Shanghai, Hangzhou and Huangshan order", href: "/guides/shanghai-hangzhou-huangshan-route-order/", description: "Apply the framework to one named east-China corridor without copying a complete itinerary." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official and primary sources reviewed",
      items: [
        { label: "Journey search by origin, destination and date", url: "https://www.12306.cn/en/index.html", publisher: "China Railway 12306", reviewedAt: "2026-09-01" },
        { label: "Passenger, document and station-process FAQ", url: "https://www.12306.cn/en/faq.html", publisher: "China Railway 12306", reviewedAt: "2026-09-01" },
        { label: "Online accommodation service requirements, LB/T 094—2025", url: "https://zwgk.mct.gov.cn/zfxxgkml/hybz/202505/W020250520321654696062.pdf", publisher: "Ministry of Culture and Tourism of China", reviewedAt: "2026-09-01" },
        { label: "Shanghai railway-station guide", url: "https://english.shanghai.gov.cn/en-Transportation/20250126/484b92f86eeb49d7b26086d25010d782.html", publisher: "Shanghai Municipal Government", reviewedAt: "2026-09-01" },
        { label: "Suzhou Museum 2026 holiday visit notice", url: "https://www.suzhou.gov.cn/szsrmzf/mszx/202604/3c3c5288f66d4d91859d80abe1d6e30e.shtml", publisher: "Suzhou Municipal Government", reviewedAt: "2026-09-01" },
        { label: "Suzhou Metro August 2026 operating adjustment", url: "https://www.suzhou.gov.cn/szsrmzf/szyw/202608/a3b6dd444c6d474a8a6de03df7d47b24.shtml", publisher: "Suzhou Municipal Government", reviewedAt: "2026-09-01" },
        { label: "Huangshan scenic-area transfer guidance", url: "https://hsgwh.huangshan.gov.cn/lyfw/lyfw/jqhc/9197913.html", publisher: "Huangshan Scenic Area Administrative Committee", reviewedAt: "2026-09-01" },
        { label: "Huangshan Baiyun Hotel location and visitor use", url: "https://hsgwh.huangshan.gov.cn/lyfw/bgjd/jqnjd/9096939.html", publisher: "Huangshan Scenic Area Administrative Committee", reviewedAt: "2026-09-01" },
        { label: "Li River scenic-area transport nodes", url: "https://www.lijiangriver.com.cn/page/article/lyfw.jtcx", publisher: "Guilin Li River Scenic Area", reviewedAt: "2026-09-01" },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
