import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "푸톈·뤄후·난산은 호텔 핀 3개가 아니라 큰 구 3개입니다. 정확한 철도역·국경 검문소, 반복되는 업무／명소 주소, 저녁 끝점으로 선전 거점을 정하세요. ‘홍콩과 가까움’은 부족합니다. 검문소마다 다른 홍콩 교통망으로 이어집니다." },
  { id: "answer", type: "callout", title: "빠른 결론", tone: "decision", body: "중앙 업무의 균형, 푸톈역 또는 푸톈 검문소가 실제 일정이면 푸톈을 고르세요. 선전역·뤄후 검문소·둥먼／옛 상업 도심·동부 중심 일정에는 뤄후가 맞습니다. 기술／업무 주소, OCT 명소, 허우하이, 씨월드／서커우, 선전만 등 서부 일정이 여러 날이고 동부까지 긴 이동을 감수하면 난산을 고르세요." },
  { id: "boundary", type: "paragraph", text: "이 글은 구 선택 논리만 다룹니다. 홍콩 국경 이동 전체, 호텔 순위, 구 안의 모든 지점이 같다는 가정은 다루지 않습니다. 푸톈 검문소와 푸톈역은 다른 장소와 교통 체계이며 난산 안에도 여러 떨어진 묶음이 있습니다. 묶음을 정한 뒤 실제 로비와 역 입구를 확인하세요." },
  { id: "matrix", type: "table", caption: "서로 다른 교통 기준점의 세 구", columns: ["거점", "가장 잘 맞음", "주요 희생", "정확한 확인"], rows: [["푸톈", "중앙 업무·푸톈 철도·푸톈／황강 관련 일정", "모든 명소·검문소와 자동으로 가깝지 않음", "어느 푸톈역／검문소와 호텔 입구"], ["뤄후", "선전역·뤄후 검문소·둥먼·동부 중심", "난산 서부까지 더 김", "철도／검문소 입구·객실 소음·짐 경로"], ["난산", "OCT·허우하이·기술 지구·씨월드／서커우 등 서부", "뤄후와 일부 중앙／동부까지 더 김", "난산의 어느 묶음과 유용한 노선"]] },
  { id: "trip-fit", type: "table", caption: "반복 주소가 결정하게 하세요", columns: ["일정 패턴", "먼저 시험", "이유"], rows: [["중앙 선전에 회의 분산", "푸톈", "중앙 환승으로 반복 도시 횡단 감소"], ["푸톈 고속철과 중앙 일정", "쓸 역 입구 근처 푸톈", "철도 기준점과 일상이 일치"], ["뤄후 국경과 선전역 이용", "뤄후", "두 고정 기준점이 같은 동부 중심"], ["허우하이·OCT·기술원·서커우 여러 날", "반복 묶음 근처 난산", "매일 서쪽 통근 방지"], ["홍콩 하루, 나머지는 난산", "난산", "한 번의 국경이 매일 밤을 정하지 않음"]] },
  { id: "border", type: "heading", level: 2, text: "‘홍콩에 편한 호텔’보다 검문소를 먼저 고르세요" },
  { id: "border-copy", type: "paragraph", text: "선전 공식 국경 정보는 뤄후·푸톈·선전만 등 검문소를 구분합니다. 같은 홍콩 철도／도로망으로 가지 않습니다. 홍콩 목적지, 운영 시간, 짐, 귀환 시각을 정한 뒤 검문소를 고르세요. 푸톈 호텔이 뤄후 검문소와 가깝다는 뜻도, 난산 주소가 선전만 검문소의 최선이라는 뜻도 아닙니다." },
  { id: "border-warning", type: "callout", title: "검문소 시간과 절차는 변합니다", tone: "warning", body: "출발 직전에 선전 국경 당국의 현재 채널을 보세요. 블로그의 통과 시간을 고정하거나 같은 검문소가 늦은 귀환에도 된다고 가정하지 마세요. 중국어 검문소 이름과 필요한 시각에 운영하는 대안을 저장하세요." },
  { id: "futian", type: "heading", level: 2, text: "푸톈: 정확한 중앙 노드가 맞을 때만 균형적입니다" },
  { id: "futian-copy", type: "paragraph", text: "선전 공식 교통 자료는 푸톈역을 이톈루·선난대로 교차부와 2·3·11호선에 두고, 지하철망의 푸톈 검문소는 4호선에 둡니다. 이름은 비슷하지만 다른 여행을 해결합니다. 실제 사용할 노드와 가까우며 중앙 회의나 저녁이 반복될 때 푸톈 호텔이 가장 좋습니다." },
  { id: "luohu", type: "heading", level: 2, text: "뤄후: 철도·국경·옛 도심 조합" },
  { id: "luohu-copy", type: "paragraph", text: "선전시 자료는 선전역을 뤄후와 1·9호선에 두고 뤄후 검문소를 주요 육상 검문소로 안내합니다. 두 기준점이 모두 있으면 실용적입니다. 그래도 뤄후는 넓습니다. 둥먼 호텔, 철도역 호텔, 동쪽 주거 주소는 마지막 이동이 다르며 객실이 철도·도로·야간 상권을 향하는지도 확인해야 합니다." },
  { id: "nanshan", type: "heading", level: 2, text: "난산: 구 이름이 아니라 서부 묶음을 고르세요" },
  { id: "nanshan-copy", type: "paragraph", text: "난산은 OCT／세계지창, 대학·기술 지구, 허우하이, 난터우, 씨월드／서커우 등 다른 노드를 포함합니다. 반복할 사무실·명소를 찍고 호텔을 찾으세요. 11호선은 일부 공항·중앙 이동에 유용하지만 다른 묶음은 1·2／8·9·12·13호선에 의존합니다. 구 이름이 아니라 현재 공식 노선도로 결정하세요." },
  { id: "arrival", type: "heading", level: 2, text: "정확한 도착 허브를 사용하세요" },
  { id: "arrival-copy", type: "paragraph", text: "선전북역·푸톈역·선전역은 다른 철도 허브입니다. 표의 전체 이름을 검색하고 짐을 포함해 최종 두 호텔까지 실시간 경로를 비교하세요. 바오안공항도 실제 시각의 터미널부터 로비 계획이 필요합니다. 직통 노선도 긴 역 통로나 호텔 도보가 있을 수 있으므로 늦은 도착과 여러 짐에는 합법적인 도로 대안을 두세요." },
  { id: "business", type: "heading", level: 2, text: "업무 지구는 하나의 사무실 주소가 아닙니다" },
  { id: "business-copy", type: "paragraph", text: "모든 고정 회의의 중국어 주소와 가장 가까운 입구를 받으세요. ‘푸톈 CBD, 난산 테크파크, 첸하이’는 긴 마지막 구간을 숨길 수 있습니다. 이틀 이상 회의면 역 수가 아니라 해당 시간의 호텔부터 건물까지 도착을 비교하세요. 균등하게 나뉘면 쉬운 환승을 택하고 하루 긴 이동을 감수하되 매일 옮기지 마세요." },
  { id: "last-mile", type: "list", items: ["정확한 역／검문소 이름을 중국어와 영어로 확인하세요.", "구 중심이 아니라 호텔 로비부터 유용한 입구까지 재세요.", "짐·비를 위해 엘리베이터·지붕·차량 픽업을 확인하세요.", "캠퍼스·쇼핑몰·오피스 문이 귀가 전에 닫히는지 보세요.", "실제 도착 시각에 여권 체크인이 가능한지 프런트에 확인하세요."] },
  { id: "verify", type: "table", caption: "잘못된 선전 거점을 막는 질문", columns: ["질문", "쓸 수 있는 답"], rows: [["어느 홍콩 검문소?", "이름·홍콩 목적지·현재 운영 확인"], ["어느 철도역?", "‘선전역’ 일반 표현이 아닌 표의 전체 이름"], ["구 안의 어디?", "역·거리·업무 묶음 이름"], ["로비까지 어떻게?", "출구·도로 입구·엘리베이터·도보"], ["가장 늦은 저녁은 어디서 끝남?", "낮 편의가 아닌 완전한 귀가"], ["검문소／회의 변경 시?", "두 번째 경로 또는 취소 가능한 호텔"]] },
  { id: "failure", type: "table", caption: "기준점이 바뀔 때 복구", columns: ["변화", "즉시 대응", "계획 결정"], rows: [["표가 다른 선전역", "짐 포함 문전 경로 재계산", "반복되거나 도착이 취약할 때만 변경"], ["검문소 시간이 맞지 않음", "홍콩 목적지에 맞는 운영 중 검문소", "옛 검문소 때문에 호텔 유지하지 않음"], ["사무실이 다른 묶음", "지리적으로 회의 묶기", "여러 날 반복될 때만 낮에 한 번 이동"], ["마지막 지하철이 비실용적", "공식 도로 교통 사용", "남은 밤은 유용한 저녁 거점"], ["호텔이 주장한 노드와 멂", "실제 로비 경로 기록", "취소 조건으로 정확한 주소 숙소"]] },
  { id: "registration", type: "paragraph", text: "호텔은 외국인 투숙객을 등록합니다. 실제 숙소가 도착 시각에 모든 여권을 처리할 직원을 두는지 확인하세요. 복합 건물 안 서비스 데스크만으로는 충분한 증거가 아닙니다." },
  { id: "dynamic", type: "paragraph", text: "선전시 지하철·철도·국경 정보는 2026년 8월 13일에 재확인했습니다. 노선·검문소 시간·절차·역 접근은 바뀔 수 있습니다. 출발 전 공식 운영／국경 채널과 호텔을 확인하세요. 이 글은 고정 국경 소요 시간을 약속하지 않습니다." },
  { id: "links", type: "internal-links", title: "계속 계획하기", items: [{ label: "선전-홍콩 교통", href: "/ko/guides/shenzhen-hong-kong-transport-route/", description: "검문소와 전체 국경 이동을 고르세요." }, { label: "‘지하철 근처’ 판단법", href: "/ko/guides/china-hotel-near-metro/", description: "정확한 입구와 마지막 도보를 시험하세요." }, { label: "광저우·선전·홍콩 순서", href: "/ko/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "선전이 거점인지 환승인지 정하세요." }] },
  { id: "sources", type: "sources", title: "공식 출처와 이미지 크레디트", items: [{ label: "선전 지하철 공식 노선 정보", url: "https://www.sz.gov.cn/en_szgov/life/transport/metro/content/post_12870342.html", publisher: "선전시 인민정부", reviewedAt: "2026-08-13" }, { label: "선전 철도역 공식 정보", url: "https://www.sz.gov.cn/en_szgov/life/transport/trains/content/post_11538776.html", publisher: "선전시 인민정부", reviewedAt: "2026-08-13" }, { label: "선전-홍콩 검문소 공식 안내", url: "https://www.sz.gov.cn/en_szgov/news/infocus/modern/news/content/post_12638271.html", publisher: "선전시 인민정부", reviewedAt: "2026-08-13" }, { label: "대표 이미지: RBWS 20 EGUOF의 푸톈 시민센터, CC BY-SA 4.0, 크롭·변환", url: "https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3%E5%B8%82_Shenzhen_%E7%A6%8F%E7%94%B0%E5%8D%80_Futian_%E5%B8%82%E6%B0%91%E4%B8%AD%E5%BF%83_Civic_Center_Shennan_Road_outdoor_square_October_2019_SS2.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
