import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Futian, Luohu and Nanshan are large districts, not three hotel pins. The right Shenzhen base depends on the named railway station or border crossing, the business or attraction addresses that repeat, and where the evening ends. ‘Close to Hong Kong’ is not precise enough: different ports lead to different Hong Kong journeys." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose Futian for the most balanced central business base, Futian Railway Station or Futian Checkpoint when those are genuinely part of the plan. Choose Luohu for Shenzhen Railway Station, Luohu Checkpoint, Dongmen/older commercial-city days and an eastern central base. Choose Nanshan when several days belong to the west—technology/business addresses, OCT attractions, Houhai, Sea World/Shekou or Shenzhen Bay—and you accept longer east-side journeys." },
  { id: "boundary", type: "paragraph", text: "This guide chooses district logic; it does not teach the full Hong Kong crossing, rank hotels or treat every point in a district as equivalent. Futian Checkpoint and Futian Railway Station are different places and travel systems. Nanshan includes several separate clusters. After choosing the cluster, test the exact lobby and station entrance." },
  { id: "matrix", type: "table", caption: "Three districts with different transport anchors", columns: ["Base", "Best fit", "Main sacrifice", "Exact check"], rows: [["Futian", "Central business, Futian rail, Futian/Huanggang-linked plans", "Not automatically closest to every attraction or border", "Which Futian station/port and hotel entrance"], ["Luohu", "Shenzhen Railway Station, Luohu port, Dongmen and east-central days", "Longer west-side Nanshan trips", "Railway versus port entrance, room noise and luggage route"], ["Nanshan", "OCT, Houhai, technology districts, Sea World/Shekou or west-side days", "More travel to Luohu and some central/eastern plans", "Which Nanshan cluster and useful metro line"]] },
  { id: "trip-fit", type: "table", caption: "Let the repeated address decide", columns: ["Trip pattern", "First base to test", "Reason"], rows: [["Meetings spread around central Shenzhen", "Futian", "Central interchange options reduce repeated cross-city travel"], ["High-speed rail through Futian plus central appointments", "Futian near the useful station entrance", "The rail anchor and daily base align"], ["Crossing at Luohu and using Shenzhen Railway Station", "Luohu", "Two fixed transport anchors sit in the same east-central area"], ["Several days in Houhai, OCT, technology parks or Shekou", "Nanshan near the repeated cluster", "Avoids commuting west every day"], ["One Hong Kong day but all Shenzhen plans in Nanshan", "Nanshan", "One crossing should not choose every night; choose the port separately"]] },
  { id: "border", type: "heading", level: 2, text: "Choose the crossing before choosing a ‘Hong Kong hotel base’" },
  { id: "border-copy", type: "paragraph", text: "Shenzhen's official port information distinguishes Luohu, Futian, Shenzhen Bay and other checkpoints. They do not deliver travellers to the same Hong Kong rail or road network. Decide the Hong Kong endpoint, operating window, luggage and return time first; then choose the port. A Futian hotel does not make Luohu port close, and a Nanshan address does not automatically make Shenzhen Bay the best crossing." },
  { id: "border-warning", type: "callout", title: "Port hours and procedures are dynamic", tone: "warning", body: "Use the Shenzhen port authority's current channel shortly before travel. Do not freeze a crossing time from a blog or assume the same port works for a late return. Keep the Chinese port name and a fallback that still operates at the required hour." },
  { id: "futian", type: "heading", level: 2, text: "Futian: balanced only when the exact central node fits" },
  { id: "futian-copy", type: "paragraph", text: "Official Shenzhen transport information places Futian Railway Station at Yitian Road and Shennan Boulevard with Metro Lines 2, 3 and 11, while the metro network also serves Futian Checkpoint on Line 4. Those names sound similar but solve different journeys. A Futian hotel works best when it is near the node you will actually use and when central meetings or evenings repeat." },
  { id: "luohu", type: "heading", level: 2, text: "Luohu: choose it for the rail-port-old-city combination" },
  { id: "luohu-copy", type: "paragraph", text: "Shenzhen government information places Shenzhen Railway Station in Luohu with Lines 1 and 9 and identifies Luohu Checkpoint as a major land crossing. That makes the district practical when both anchors appear. The label is still broad: a Dongmen hotel, a railway-station hotel and an eastern residential address have different final walks. Confirm whether the room faces rail, road or nightlife noise." },
  { id: "nanshan", type: "heading", level: 2, text: "Nanshan: choose the western cluster, not the district name" },
  { id: "nanshan-copy", type: "paragraph", text: "Nanshan stretches across distinct areas including OCT/Window of the World, university and technology zones, Houhai, Nantou, Sea World/Shekou and other western nodes. Mark the repeated office or attraction before searching hotels. Line 11 can help some airport and central journeys, while other clusters rely on Lines 1, 2/8, 9, 12 or 13; the current official network map, not the district label, decides." },
  { id: "arrival", type: "heading", level: 2, text: "Use the exact arrival hub" },
  { id: "arrival-copy", type: "paragraph", text: "Shenzhen North, Futian and Shenzhen Railway Station are different rail hubs. Search the complete ticket name and compare the live route to the final two hotels with luggage. Bao'an Airport also needs a terminal-to-lobby plan at the actual hour. A direct line can still include a long station corridor or hotel walk; keep a legal road-transfer fallback for late arrival or a group with several cases." },
  { id: "business", type: "heading", level: 2, text: "A business district is not one office address" },
  { id: "business-copy", type: "paragraph", text: "Ask for the Chinese address and nearest entrance of every fixed meeting. ‘Futian CBD’, ‘Nanshan tech park’ or ‘Qianhai’ can hide a long final segment. For two or more appointment days, compare hotel-to-building arrival time at the relevant hour, not just metro stops. If meetings split evenly, choose the simplest interchange and accept one longer day rather than moving nightly." },
  { id: "last-mile", type: "list", items: ["Identify the exact station/port name in Chinese and English.", "Measure hotel lobby to the useful entrance, not the district centre.", "Confirm lift, covered route and road pickup for luggage or rain.", "Check whether a campus, mall or office gate closes before your return.", "Ask reception to confirm passport check-in at the actual arrival hour."] },
  { id: "verify", type: "table", caption: "Questions that prevent the wrong Shenzhen base", columns: ["Question", "What a useful answer contains"], rows: [["Which Hong Kong port?", "Named port, Hong Kong endpoint and current operating check"], ["Which railway station?", "Full ticket name, not ‘Shenzhen station’"], ["Which part of the district?", "Named station, street or business cluster"], ["How do we reach the lobby?", "Correct exit, road entrance, lift and walking route"], ["Where does the latest evening end?", "A complete return, not daytime convenience"], ["What if the port/meeting changes?", "A second workable route or cancellable hotel plan"]] },
  { id: "failure", type: "table", caption: "Recover when the anchor changes", columns: ["Change", "Immediate response", "Plan decision"], rows: [["Ticket uses another Shenzhen station", "Recalculate door-to-door with luggage", "Change hotel only if the journey repeats or arrival is fragile"], ["Chosen port hours do not fit", "Select a currently operating port by Hong Kong endpoint", "Do not keep the hotel just to preserve the old port"], ["Office is in another cluster", "Group appointments geographically", "Move once in daylight only for several repeated days"], ["Last metro route becomes impractical", "Use an official road-transfer option", "Choose a more useful evening base for remaining nights"], ["Hotel is far from the claimed node", "Document the lobby route", "Use cancellation terms and choose an exact-address property"]] },
  { id: "registration", type: "paragraph", text: "Hotels register foreign guests. Confirm the exact property has staff able to process every passport at your arrival time; a serviced desk inside a mixed-use tower is not enough evidence by itself." },
  { id: "dynamic", type: "paragraph", text: "Shenzhen municipal metro, railway and port information was reviewed on August 13, 2026. Lines, port hours, procedures and station access can change. Recheck the official operator/port channel and hotel shortly before travel; no fixed crossing duration is promised here." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Shenzhen to Hong Kong transport", href: "/guides/shenzhen-hong-kong-transport-route/", description: "Choose the port and complete cross-border journey." }, { label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Test the exact entrance and last walk." }, { label: "Guangzhou, Shenzhen and Hong Kong route order", href: "/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "Decide whether Shenzhen is a base or a transfer." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Shenzhen Metro official network information", url: "https://www.sz.gov.cn/en_szgov/life/transport/metro/content/post_12870342.html", publisher: "Shenzhen Municipal Government", reviewedAt: "2026-08-13" }, { label: "Official Shenzhen railway-station information", url: "https://www.sz.gov.cn/en_szgov/life/transport/trains/content/post_11538776.html", publisher: "Shenzhen Municipal Government", reviewedAt: "2026-08-13" }, { label: "Official Shenzhen-Hong Kong checkpoint guide", url: "https://www.sz.gov.cn/en_szgov/news/infocus/modern/news/content/post_12638271.html", publisher: "Shenzhen Municipal Government", reviewedAt: "2026-08-13" }, { label: "Hero: Futian Civic Center by RBWS 20 EGUOF, CC BY-SA 4.0; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3%E5%B8%82_Shenzhen_%E7%A6%8F%E7%94%B0%E5%8D%80_Futian_%E5%B8%82%E6%B0%91%E4%B8%AD%E5%BF%83_Civic_Center_Shennan_Road_outdoor_square_October_2019_SS2.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
