import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body={schemaVersion:"1.0.0",blocks:[
{id:"lead",type:"lead",text:"深圳东西跨度足以让错误住宿区变成每天跨城通勤。先写下固定地址——口岸、车站、办公室或景点群——再决定希望哪种夜间活动留在酒店附近。"},
{id:"answer",type:"callout",title:"先给结论",tone:"decision",body:"商务与城市体验混合、使用福田站，福田是较稳妥的综合基地；罗湖口岸、深圳站或东侧事务占主导，罗湖更顺；反复前往后海、深圳湾、蛇口或西侧科技与休闲片区，南山更合理。"},
{id:"matrix",type:"table",caption:"按固定端点选择",columns:["区域","更适合","牺牲","核对"],rows:[["福田","混合行程、福田站、市民中心与商务地址","并非离所有口岸或西侧都最近","准确车站／办公室与晚到路线"],["罗湖","罗湖口岸、深圳站、东侧事务","西侧行程更长","车票使用的完整口岸或站名"],["南山","后海、深圳湾、蛇口、西侧会议与景点","去罗湖及部分中心／东侧更远","南山内部准确片区，不把全区当一点"]]},
{id:"border",type:"callout",title:"“靠近香港”不是足够的住宿标签",tone:"warning",body:"深圳有多条跨境链路，不能互相替代。酒店要匹配实际使用的口岸与香港后续地址；开放安排与客运服务可能变化，必须按日期查口岸和交通官方信息。"},
{id:"fit",type:"comparison",title:"按行程倾向",columns:[{heading:"首次混合行程",items:["先比较福田","集中一天去南山","避免每日两次穿城"]},{heading:"铁路或罗湖过关",items:["能减少真实交接才选罗湖","把西侧行程集中","读完整站名"]},{heading:"西侧一周",items:["选择南山准确节点","靠近重复会议","有意识安排一次中心夜晚"]}]},
{id:"facts",type:"callout",title:"动态信息核验于2026年8月12日",tone:"neutral",body:"深圳市政府当前轨道页面列出横跨福田、罗湖与南山的线路和车站；市政府目的地页面把后海等西侧区域列于南山。这些是经核验地理事实，住宿建议属于编辑判断。出行前须复查实时轨道、口岸安排和车站进入。"},
{id:"check",type:"list",ordered:true,items:["写下完整车站或口岸名。","定位所有重复办公室或景点。","选择能消除最大每日交接的区域。","模拟一次晚归与去机场。","直接确认物业入口和住宿登记。"]},
{id:"help",type:"callout",title:"需要比较节点？",tone:"decision",body:"提供日期、人数、准确口岸或车站、重复地址与大致预算，Homeground可以比较区域，而不是给酒店排名。"},
{id:"links",type:"internal-links",title:"继续规划",items:[{label:"商业公寓酒店还是住宅短租",href:"/zh/guides/commercial-aparthotel-or-residential-rental-china/",description:"需要空间与西侧工作周时先看运营模式。"},{label:"上海首次住宿区域",href:"/zh/guides/shanghai-where-to-stay-first-trip/",description:"比较另一座多中心城市。"},{label:"深圳—香港交通",href:"/zh/guides/shenzhen-hong-kong-transport-route/",description:"选择真实跨境链路。"}]},
{id:"sources",type:"sources",title:"官方来源与图片署名",items:[{label:"深圳当前轨道线路与车站",url:"https://www.sz.gov.cn/en_szgov/life/transport/metro/content/post_12583635.html",publisher:"深圳市人民政府",reviewedAt:"2026-08-12"},{label:"南山区官方访客信息",url:"https://www.sz.gov.cn/en_szgov/news/infocus/SZCitywalk/Explore/Districts/NanshanDistrict/index.html",publisher:"深圳市人民政府",reviewedAt:"2026-08-12"},{label:"后海与南山区域官方资料",url:"https://www.sz.gov.cn/en_szgov/travel/areas/content/post_10684425.html",publisher:"深圳市人民政府",reviewedAt:"2026-08-12"},{label:"首图：RBWS 20 EGUOF拍摄福田市民中心，CC BY-SA 4.0，已裁切转换",url:"https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3%E5%B8%82_Shenzhen_%E7%A6%8F%E7%94%B0%E5%8D%80_Futian_%E5%B8%82%E6%B0%91%E4%B8%AD%E5%BF%83_Civic_Center_Shennan_Road_outdoor_square_October_2019_SS2.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"},{label:"CC BY-SA 4.0许可证",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-12"}]}
]} as const satisfies StructuredPageBody; export default body;
