import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body={schemaVersion:"1.0.0",blocks:[
{id:"lead",type:"lead",text:"Shenzhen is long enough that choosing the wrong side can create a cross-city commute. Start with the fixed address—border, station, office or attraction cluster—then decide which evenings you want near the hotel."},
{id:"answer",type:"callout",title:"The short decision",tone:"decision",body:"Futian is the strongest general base for mixed business, central city life and Futian rail connections. Luohu is logical when Luohu Port, Shenzhen Railway Station or east-side errands dominate. Nanshan is better when the itinerary repeatedly uses Houhai, Shenzhen Bay, Shekou or west-side technology and leisure districts."},
{id:"matrix",type:"table",caption:"Choose by the fixed endpoint",columns:["Base","Best fit","Sacrifice","Verify"],rows:[["Futian","Mixed central trip, Futian station, civic and business addresses","Not closest to every border or west-side stop","Exact station/office and late arrival route"],["Luohu","Luohu Port, Shenzhen Railway Station, east-side tasks","Longer west-side days","Which port or station your ticket actually uses"],["Nanshan","Houhai, Shenzhen Bay, Shekou, west-side meetings and attractions","Longer to Luohu and some central/east tasks","Exact Nanshan sub-area; it is not one compact centre"]]},
{id:"border",type:"callout",title:"‘Near Hong Kong’ is not a sufficient label",tone:"warning",body:"Shenzhen has multiple cross-border routes and they are not interchangeable. Match the hotel to the crossing and onward address you will actually use. Opening arrangements and passenger service can change; verify the official port and transport information for the date."},
{id:"fit",type:"comparison",title:"Which area fits which trip",columns:[{heading:"First mixed visit",items:["Start with Futian","Cluster one Nanshan day","Avoid crossing the city twice daily"]},{heading:"Rail or Luohu border task",items:["Use Luohu when it removes a real handoff","Keep west-side plans together","Read the full station name"]},{heading:"West-side week",items:["Choose the exact Nanshan area","Stay near repeated meetings","Plan one central evening intentionally"]}]},
{id:"facts",type:"callout",title:"Dynamic facts checked August 12, 2026",tone:"neutral",body:"Shenzhen's official current metro page lists the network and stations across Futian, Luohu and Nanshan, while municipal destination pages place Houhai and major west-side areas in Nanshan. These are verified geographic facts; the recommended base is editorial judgement. Check live metro, border-port arrangements and station access before travel."},
{id:"check",type:"list",ordered:true,items:["Write the full rail station or border-port name.","Pin every repeated office or attraction.","Choose the district containing the most expensive daily handoff.","Test one late return and the airport journey.","Confirm the property entrance and registration directly."]},
{id:"help",type:"callout",title:"Need the stay areas compared?",tone:"decision",body:"Send dates, party size, exact border or station, addresses you will revisit and approximate budget. Homeground can compare the bases without turning the answer into a hotel ranking."},
{id:"links",type:"internal-links",title:"Continue planning",items:[{label:"Commercial aparthotel or residential rental?",href:"/guides/commercial-aparthotel-or-residential-rental-china/",description:"Useful when space and a west-side workweek matter."},{label:"Shanghai first-trip areas",href:"/guides/shanghai-where-to-stay-first-trip/",description:"Compare another multi-centre city."},{label:"Shenzhen–Hong Kong transport",href:"/guides/shenzhen-hong-kong-transport-route/",description:"Choose the actual cross-border chain."}]},
{id:"sources",type:"sources",title:"Official sources and image credit",items:[{label:"Current Shenzhen metro lines and stations",url:"https://www.sz.gov.cn/en_szgov/life/transport/metro/content/post_12583635.html",publisher:"Shenzhen Municipal Government",reviewedAt:"2026-08-12"},{label:"Nanshan district visitor information",url:"https://www.sz.gov.cn/en_szgov/news/infocus/SZCitywalk/Explore/Districts/NanshanDistrict/index.html",publisher:"Shenzhen Municipal Government",reviewedAt:"2026-08-12"},{label:"Official Houhai and Nanshan area information",url:"https://www.sz.gov.cn/en_szgov/travel/areas/content/post_10684425.html",publisher:"Shenzhen Municipal Government",reviewedAt:"2026-08-12"},{label:"Hero: Futian Civic Center by RBWS 20 EGUOF, CC BY-SA 4.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3%E5%B8%82_Shenzhen_%E7%A6%8F%E7%94%B0%E5%8D%80_Futian_%E5%B8%82%E6%B0%91%E4%B8%AD%E5%BF%83_Civic_Center_Shennan_Road_outdoor_square_October_2019_SS2.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"},{label:"CC BY-SA 4.0 licence",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-12"}]}
]} as const satisfies StructuredPageBody; export default body;
