import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body={schemaVersion:"1.0.0",blocks:[
{id:"lead",type:"lead",text:"선전은 동서로 길어 잘못 고르면 매일 도시를 가로지르게 됩니다. 국경, 역, 사무실, 명소처럼 고정된 주소를 먼저 적고 어떤 저녁을 숙소 가까이에 둘지 정하세요."},
{id:"answer",type:"callout",title:"빠른 선택",tone:"decision",body:"업무와 도시 관광을 섞고 푸톈역을 쓰면 푸톈이 가장 무난합니다. 뤄후항·선전역·동쪽 업무가 중심이면 뤄후, 허우하이·선전완·서커우 또는 서쪽 기술·여가 지역을 반복 방문하면 난산이 낫습니다."},
{id:"matrix",type:"table",caption:"고정 목적지로 고르기",columns:["거점","잘 맞는 여행","감수할 점","확인"],rows:[["푸톈","혼합 일정, 푸톈역, 시민·업무 주소","모든 국경·서쪽 지점에 가장 가깝지는 않음","정확한 역·사무실과 늦은 도착"],["뤄후","뤄후항, 선전역, 동쪽 일정","서쪽 일정이 길어짐","표에 적힌 전체 항구·역 이름"],["난산","허우하이, 선전완, 서커우, 서쪽 회의·명소","뤄후와 동쪽까지 거리가 김","난산 안의 정확한 하위 지역"]]},
{id:"border",type:"callout",title:"‘홍콩과 가까움’만으로는 부족합니다",tone:"warning",body:"선전의 여러 국경 경로는 서로 바꿔 쓸 수 없습니다. 실제 이용할 출입국 지점과 홍콩의 다음 주소에 숙소를 맞추고 날짜별 운영은 공식 정보로 확인하세요."},
{id:"fit",type:"comparison",title:"일정별 무게",columns:[{heading:"첫 혼합 여행",items:["푸톈부터 비교","난산 일정 하루로 묶기","하루 두 번 횡단 피하기"]},{heading:"철도·뤄후 국경",items:["실제 환승을 줄일 때 뤄후","서쪽 일정 묶기","전체 역명 읽기"]},{heading:"서쪽에서 한 주",items:["난산의 정확한 노드 선택","반복 회의 가까이","중심부 저녁은 의도적으로 한 번"]}]},
{id:"facts",type:"callout",title:"변동 정보 확인일: 2026년 8월 12일",tone:"neutral",body:"선전시 공식 최신 지하철 페이지는 푸톈·뤄후·난산의 노선을 열거하며, 시 관광 페이지는 허우하이 등 서쪽 지역을 난산에 둡니다. 이는 확인된 지리 사실이고 숙소 추천은 편집 판단입니다. 실제 지하철·국경·역 접근은 출발 전에 재확인하세요."},
{id:"check",type:"list",ordered:true,items:["전체 역명·출입국 지점명을 적습니다.","반복할 사무실·명소를 찍습니다.","가장 큰 매일의 인계를 없애는 지역을 고릅니다.","늦은 귀가와 공항 이동을 시험합니다.","숙소 입구와 등록을 직접 확인합니다."]},
{id:"help",type:"callout",title:"거점을 비교할까요?",tone:"decision",body:"날짜, 인원, 정확한 국경·역, 반복 방문할 주소와 대략적인 예산을 보내면 Homeground가 호텔 순위 없이 거점을 비교할 수 있습니다."},
{id:"links",type:"internal-links",title:"계속 계획하기",items:[{label:"상업형 아파트호텔과 주거용 단기 임대",href:"/ko/guides/commercial-aparthotel-or-residential-rental-china/",description:"공간과 서쪽 업무 주간에 운영 형태를 확인합니다."},{label:"상하이 첫 숙소 지역",href:"/ko/guides/shanghai-where-to-stay-first-trip/",description:"또 다른 다핵 도시를 비교합니다."},{label:"선전–홍콩 이동",href:"/ko/guides/shenzhen-hong-kong-transport-route/",description:"실제 국경 이동 사슬을 고릅니다."}]},
{id:"sources",type:"sources",title:"공식 출처와 이미지 크레디트",items:[{label:"선전 최신 지하철 노선과 역",url:"https://www.sz.gov.cn/en_szgov/life/transport/metro/content/post_12583635.html",publisher:"선전시 인민정부",reviewedAt:"2026-08-12"},{label:"난산구 공식 방문 정보",url:"https://www.sz.gov.cn/en_szgov/news/infocus/SZCitywalk/Explore/Districts/NanshanDistrict/index.html",publisher:"선전시 인민정부",reviewedAt:"2026-08-12"},{label:"허우하이·난산 공식 지역 정보",url:"https://www.sz.gov.cn/en_szgov/travel/areas/content/post_10684425.html",publisher:"선전시 인민정부",reviewedAt:"2026-08-12"},{label:"대표 이미지: RBWS 20 EGUOF의 푸톈 시민센터, CC BY-SA 4.0, 크롭·변환",url:"https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3%E5%B8%82_Shenzhen_%E7%A6%8F%E7%94%B0%E5%8D%80_Futian_%E5%B8%82%E6%B0%91%E4%B8%AD%E5%BF%83_Civic_Center_Shennan_Road_outdoor_square_October_2019_SS2.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"},{label:"CC BY-SA 4.0 라이선스",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-12"}]}
]} as const satisfies StructuredPageBody; export default body;
