import type { StructuredPageBody } from "../../../lib/content-system/page-body";
import type { HomegroundLocale } from "../../../lib/homegroundI18n";

const copies = {
  en: {
    lead: "The fast train from Shanghai makes Hangzhou look like an easy excursion, but the real decision is door to door. Use a day trip when West Lake is the single priority, the group travels light and the return is protected. Stay two nights when Lingyin, Longjing or local morning and evening time matters; add a third night only when the Grand Canal or Liangzhu is a purpose of its own.",
    decisionTitle: "The useful default",
    decisionBody: "A disciplined day trip can explain West Lake. Two nights let the lake, the western hills and a local morning coexist. Three nights create room for a second heritage geography. Extra time should change the kind of city you understand, not merely add pins.",
    fitHeading: "Who Hangzhou suits — and what each traveller must omit",
    fitColumns: ["Traveller", "Best use", "Main caution"],
    fitRows: [
      ["First-time visitor based in Shanghai", "Focused West Lake day or a two-night contrast", "A short train ride is not a short hotel-to-lake day"],
      ["Cultural-heritage traveller", "West Lake, Lingyin, Grand Canal and possibly Liangzhu", "These are separate geographies, not one old-town zone"],
      ["Slow traveller or photographer", "Early and late lake time plus the wooded western hills", "A lake-branded hotel helps only when its exact shore and access work"],
      ["Family or slower walker", "Short shore segments, one cultural anchor and planned vehicle handoffs", "Causeways, hill roads and archaeological grounds add hidden walking"],
    ],
    nightsHeading: "What one day, two nights and three nights actually buy",
    nightsColumns: ["Time shape", "What becomes realistic", "Leave out"],
    nightsRows: [
      ["Shanghai day return", "One West Lake orientation, one connected cultural stop and a protected return", "Liangzhu, a full canal day and an ambitious lake–Lingyin–Longjing chain"],
      ["Two nights", "A local evening and morning, one lake side at a better pace, plus Lingyin or Longjing", "Liangzhu, canal and every lake sector in the same stay"],
      ["Three nights", "A second geography such as the Grand Canal or Liangzhu, with weather recovery", "Turning every surrounding water town or mountain into a Hangzhou side trip"],
    ],
    stayHeading: "Where to stay: choose the side of the city, not the marketing label",
    stayColumns: ["Area", "Best for", "Trade-off"],
    stayRows: [
      ["Hubin / east shore", "First visit, short stay, dining and evening waterfront", "Strongest visitor pressure and frequent poor-value lake-view pricing"],
      ["Beishan / Wulin", "Cultural north shore with a functioning city base", "Beishan and Wulin are different micro-areas; verify the exact pin"],
      ["Lingyin / Longjing side", "Temple, tea landscape and quiet western priorities", "Weaker metro reach, hill-road traffic and awkward early departures"],
      ["Hangzhou East Station area", "Late arrival, early train or heavy luggage", "A logistics base east of the visitor landscape, not a West Lake stay"],
    ],
    gatewayHeading: "HGH and four railway stations solve different journeys",
    gatewayIntro: "Search the actual date and complete station pair. Hangzhou West is not a West Lake station, and the fastest train can lose its advantage in the transfer to the hotel. For a Shanghai day return, design the return before buying the outbound; for an overnight stay, let the hotel and onward city influence the station.",
    gatewayColumns: ["Gateway", "Useful when", "Mistake to prevent"],
    gatewayRows: [
      ["HGH Xiaoshan Airport", "A direct flight or open-jaw route avoids returning to Shanghai", "Treating the airport as central Hangzhou or assuming a protected rail connection"],
      ["Hangzhou / Chengzhan", "A dated train fits the older central-city side", "Assuming every result named Hangzhou means this station"],
      ["Hangzhou East", "Broad high-speed-rail choice and many Shanghai links", "Ignoring the transfer to Hubin, Lingyin or a west-side hotel"],
      ["Hangzhou West", "A western/Yuhang address or date-specific corridor fits", "Reading West as West Lake"],
      ["Hangzhou South", "A Xiaoshan or south/east-side address fits", "Using it as a substitute for the old city without checking the last mile"],
    ],
    clusterHeading: "Read Hangzhou as six spatial clusters",
    clusterColumns: ["Cluster", "What it contributes", "Keep separate from"],
    clusterRows: [
      ["East-shore entrance", "Where downtown meets West Lake; easiest first orientation", "Liangzhu and a full canal task"],
      ["North shore / Beishan", "Causeways, Gushan, museums and literary-historical layers", "A promise to finish the western hills and south line the same day"],
      ["South line", "A second lake perspective around Leifeng and the southern landscape", "A forced full circuit when traffic or weather works against it"],
      ["Lingyin and Longjing", "Temple, rock-carving and tea-landscape geography in the western hills", "A single compound or a guaranteed harvest demonstration"],
      ["Grand Canal", "Working-waterway history around a northern urban corridor", "Another shore of West Lake"],
      ["Liangzhu", "Prehistoric urbanism, museum interpretation and archaeological landscape", "A casual add-on after Lingyin or a station transfer"],
    ],
    boundaryTitle: "What this city guide covers",
    boundaryBody: "This city guide covers the broad Hangzhou decision: day trip or stay, nights, base, gateways, cluster relationships and next city. The linked detailed guides handle station-pair execution, Liangzhu venue order, White Snake evidence, canal interpretation and tea provenance. Use this as the overview rather than looking for a second generic Hangzhou travel guide.",
    readingTitle: "Use the detailed guide when the decision becomes executable",
    links: [
      ["Choose the Shanghai–Hangzhou station pair", "shanghai-hangzhou-transport-route", "Door-to-door rail, exact stations and wrong-station recovery."],
      ["Plan Liangzhu Museum and the ruins park", "liangzhu-ruins-park-and-museum-sequence", "Treat the two venues as a dedicated suburban heritage day."],
      ["Read Hangzhou's Grand Canal", "grand-canal-everyday-urban-history", "Separate protected heritage, working waterway and neighbourhood life."],
      ["Put Longjing in China's tea landscapes", "tea-landscape-regions-of-china", "Landscape, craft and provenance without promising a harvest performance."],
      ["Separate White Snake story from site evidence", "white-snake-legend-hangzhou-zhenjiang", "Broken Bridge, Leifeng archaeology and later reconstruction have different evidence."],
      ["Choose the wider Yangtze Delta order", "shanghai-suzhou-hangzhou-nanjing-route-order", "Decide a chain, Shanghai base or two-base route before adding hotels."],
    ],
    stayReadingTitle: "Finish the property decision with the nationwide stay guides",
    stayLinks: [
      ["Test whether ‘near the metro’ is useful", "china-hotel-near-metro", "Verify the exact exit and complete lobby route; a West Lake or station label is not enough."],
      ["Verify an actually usable accessible room", "china-accessible-hotel-room-verification", "Check road or station to lobby, lift, room and bathroom before paying."],
      ["Can foreigners stay at any hotel in China?", "foreigners-china-hotel", "Separate the legal rule, platform display and the exact property's current registration operation."],
      ["Plan the final night before an international flight", "china-last-night-before-international-flight", "Work backwards from the named HGH terminal or the actual departure airport and flight."],
    ],
    quoteTitle: "Ask for a human Hangzhou property-fit check",
    quoteBody: "Use the general planner only for a first contact. In the initial form, share travel dates, the city or areas being compared, traveller and room counts, and an approximate accommodation budget if useful. You may say that you want to discuss family or accessibility arrangements later, but do not submit children's ages, mobility, medical or accessibility details, passport or other document information, booking or payment records, or identifiable material intended for a hotel, DMC or other supplier. A planner can arrange a separate human follow-up; those details are discussed only when appropriate and with suitable consent. Nothing is shared with a supplier without separate, purpose-specific consent, and this is not live inventory or a guarantee of price, availability, guest acceptance, room type or accessibility.",
    onwardHeading: "Nearby does not mean it belongs inside the Hangzhou day",
    onwardColumns: ["Place", "Use it when", "Boundary"],
    onwardRows: [
      ["Shanghai", "It remains the main gateway or a day-trip base", "Pudong, Hongqiao and central Shanghai produce different journeys"],
      ["Suzhou", "Gardens and canal urbanism have a distinct purpose", "It is a separate city, not an interchangeable Jiangnan label"],
      ["Shaoxing", "Lu Xun, waterways or deeper Zhejiang is the real next step", "It is not a Hangzhou neighbourhood"],
      ["Huangshan", "The route has time for gateway, mountain base and weather decisions", "It is not a Hangzhou day sight"],
      ["Wuzhen", "A managed water-town experience justifies its transfer", "It is in Tongxiang, Jiaxing, not central Hangzhou"],
    ],
    recheckHeading: "Recheck these shortly before travel",
    recheckItems: [
      "The exact HGH metro and road access, plus first and last services for the required time.",
      "The exact Hangzhou station on every 12306 result and ticket.",
      "Current Lingyin and Feilai Peak access, reservation and separate ticket arrangements.",
      "Liangzhu Museum and park notices separately, including Monday and severe-weather treatment.",
      "West Lake boats, traffic controls and crowd measures for the travel date.",
      "Any tea visit by named producer and activity; a season does not guarantee harvest or processing.",
    ],
    faqHeading: "Common questions",
    faqs: [
      ["Day trip or two nights?", "Choose a day trip only when West Lake is the single priority and the return has a safe margin. Two nights are the stronger default for Lingyin, Longjing or a local morning and evening."],
      ["Which Hangzhou station is best?", "The one that makes the complete journey work on the actual date. East often has the broadest choice, Chengzhan can fit the old centre, West serves a different western geography and South is in Xiaoshan."],
      ["Can West Lake, Lingyin and Longjing fit in one day?", "Only as a selective, transport-aware day with limited stops. It is a poor promise for a first-time Shanghai return; overnight visitors should separate the lake and the western-hill block."],
      ["Is Liangzhu worth a day?", "Yes for archaeology, early urbanism, water management and jade interpretation. No if it is included only because it sits inside wider Hangzhou administration."],
      ["Should the final night be near HGH?", "Not automatically. Work backwards from the international flight, named terminal, check-in requirement and a dated route. Use an HGH-side final night when a city hotel cannot preserve that margin, or when children, older travellers, accessibility needs or heavy luggage make the transfer fragile. Reconfirm the exact property's road, metro or stated shuttle operation, passport check-in and fallback; an airport label is not a live transport or room guarantee."],
    ],
    planningTitle: "Turn the city choice into a whole route",
    planningLinks: [
      ["Check whether the itinerary is too rushed", "is-your-china-itinerary-too-rushed", "Count station access, luggage and the cost of another hotel move."],
      ["Review an existing China itinerary", "../china-itinerary-review", "Bring the current day-by-day route for an evidence-based weak-link review."],
    ],
    sourcesTitle: "Official sources and review record",
    sourceLabels: [
      "West Lake Cultural Landscape of Hangzhou",
      "West Lake scenic-area authority and current notices",
      "HGH airport metro access",
      "China Railway 12306 date-specific search",
      "Liangzhu official venue and weather notices",
      "Archaeological Ruins of Liangzhu City",
    ],
  },
  zh: {
    lead: "上海到杭州的高铁很快，容易让人把杭州看成一次简单郊游，但真正要比较的是门到门。西湖是唯一重点、轻装早出且返程受保护时，可以一日往返；灵隐、龙井或本地早晚时间重要时，住两晚；只有大运河或良渚本身就是目的，第三晚才真正有价值。",
    decisionTitle: "更实用的默认判断",
    decisionBody: "克制的一日往返可以解释西湖；两晚能让湖、西部山地与本地清晨同时存在；三晚为第二套遗产地理留出空间。多出的时间应改变你理解城市的方式，而不是只增加坐标点。",
    fitHeading: "杭州适合谁——每类旅客又应主动舍弃什么",
    fitColumns: ["旅客", "最适合的用法", "主要风险"],
    fitRows: [
      ["以上海为基地的第一次来华旅客", "集中游西湖，或住两晚与上海形成对照", "车程短不等于酒店到湖边的一天也短"],
      ["文化遗产旅客", "西湖、灵隐、大运河，必要时加良渚", "这些是分散的地理单元，不是同一片古城"],
      ["慢旅行或摄影旅客", "湖边早晚时间与西部山地", "带“西湖”字样的酒店，只有位置与接驳合适才有用"],
      ["家庭或步行较慢者", "短岸线、一个文化锚点和计划好的车辆接驳", "堤岸、山路与考古公园会增加隐性步行"],
    ],
    nightsHeading: "一日、两晚和三晚分别真正买到什么",
    nightsColumns: ["时间形态", "现实可行", "应主动排除"],
    nightsRows: [
      ["上海一日往返", "一个西湖定向、一个相连的文化点和受保护的返程", "良渚、完整运河日，以及西湖—灵隐—龙井全塞"],
      ["两晚", "本地一晚一早、较从容的一段湖岸，再加灵隐或龙井", "同时完成良渚、运河和全部湖区"],
      ["三晚", "大运河或良渚这样的第二地理单元，并保留天气恢复", "把周边所有水乡和山岳都叫作杭州周边游"],
    ],
    stayHeading: "住哪里：选城市的哪一侧，不要只看营销名称",
    stayColumns: ["区域", "适合", "代价"],
    stayRows: [
      ["湖滨 / 东岸", "第一次、短住、餐饮与夜间湖边", "客流压力最大，湖景房常不值差价"],
      ["北山 / 武林", "北岸文化景观与城市功能之间的平衡", "北山和武林不是同一微区，必须核对准确坐标"],
      ["灵隐 / 龙井一侧", "寺院、茶景观与安静的西部重点", "地铁覆盖弱、山路拥堵，早班交通不方便"],
      ["杭州东站附近", "晚到、早班车或大件行李", "是游览核心以东的物流基地，不等于住西湖"],
    ],
    gatewayHeading: "HGH机场与四座铁路站解决的是不同旅程",
    gatewayIntro: "按真实日期搜索完整车站组合。杭州西站不是西湖站，最快车次也可能在去酒店的最后一程失去优势。上海一日往返应先设计返程再买去程；住杭州时，让酒店和下一站共同决定车站。",
    gatewayColumns: ["门户", "何时有用", "要避免的错误"],
    gatewayRows: [
      ["HGH萧山机场", "直飞或开口程能避免返回上海", "把机场当作杭州中心，或假定空铁联程受保护"],
      ["杭州站 / 城站", "具体日期的车次适合老城一侧", "看到“杭州”就以为所有结果都是城站"],
      ["杭州东站", "高铁选择多，上海方向车次丰富", "忽略去湖滨、灵隐或西侧酒店的接驳"],
      ["杭州西站", "余杭或西部地址、特定线路合适", "把“西”误读成“西湖”"],
      ["杭州南站", "萧山或南/东侧地址合适", "不核对最后一程就拿它替代老城车站"],
    ],
    clusterHeading: "把杭州读成六个空间分区",
    clusterColumns: ["分区", "它提供什么", "不要混在一起"],
    clusterRows: [
      ["东岸城市入口", "市中心与西湖相接，最容易第一次定向", "良渚与完整运河任务"],
      ["北岸 / 北山", "堤岸、孤山、博物馆与文学历史层", "同日完成西部山地和南线的承诺"],
      ["南线", "雷峰与南部山水关系提供第二种湖景", "交通和天气不利时强行完整环湖"],
      ["灵隐与龙井", "西部山地中的寺院、石刻与茶景观", "把它们当成一个院落，或承诺一定看到采茶炒茶"],
      ["大运河", "北部城市走廊中的工作水路历史", "把它叫作西湖另一岸"],
      ["良渚", "史前城市、博物院解释与考古景观", "灵隐之后顺手加，或当作车站过渡"],
    ],
    boundaryTitle: "本城市指南涵盖什么",
    boundaryBody: "本城市指南回答杭州的整体选择：一日往返还是住下、住几晚、选哪个基地和门户、怎样理解分区关系，以及下一站去哪里。车站组合、良渚场馆顺序、白蛇传证据、运河解读和茶叶产地证据，分别由下方对应的详细指南处理；无需再寻找另一篇泛杭州旅行指南。",
    readingTitle: "进入执行阶段后，打开对应的详细指南",
    links: [
      ["选择上海—杭州车站组合", "shanghai-hangzhou-transport-route", "门到门铁路、准确车站与走错站补救。"],
      ["安排良渚博物院与遗址公园", "liangzhu-ruins-park-and-museum-sequence", "把两个场馆作为独立的郊区遗产日。"],
      ["读懂杭州大运河", "grand-canal-everyday-urban-history", "分清受保护遗产、工作水路与街区生活。"],
      ["把龙井放进中国茶乡景观", "tea-landscape-regions-of-china", "讲景观、工艺与来源，不承诺采茶表演。"],
      ["分开白蛇故事与地点证据", "white-snake-legend-hangzhou-zhenjiang", "断桥、雷峰遗址和后建塔属于不同证据层。"],
      ["选择长三角整体顺序", "shanghai-suzhou-hangzhou-nanjing-route-order", "增加酒店前，先决定串联、上海基地或双基地。"],
    ],
    stayReadingTitle: "用全国住宿指南完成具体物业判断",
    stayLinks: [
      ["检验‘靠近地铁’是否真的有用", "china-hotel-near-metro", "核对准确出口与到大堂的完整路线；西湖或车站标签并不足够。"],
      ["核验真正可用的无障碍酒店房", "china-accessible-hotel-room-verification", "付款前核对从道路或车站到大堂、电梯、房间与浴室。"],
      ["外国旅客能住中国任何酒店吗？", "foreigners-china-hotel", "分开法律规则、平台显示与具体物业当前的登记执行。"],
      ["规划国际航班前的最后一晚", "china-last-night-before-international-flight", "从具名的HGH航站楼，或真正离境的机场与航班倒推。"],
    ],
    quoteTitle: "需要人工核对杭州候选物业？",
    quoteBody: "现有通用规划入口只用于初次联系。初始表单仅填写旅行日期、准备比较的城市或区域、旅客与房间数量，以及必要时的大致住宿预算。可以说明希望稍后讨论家庭或无障碍安排，但不要提交儿童具体年龄、行动、医疗或无障碍细节、护照或其他证件资料、订单或付款记录，或任何准备转交酒店、地接等供应商的可识别资料。规划师会另行安排人工跟进；这些细节只在确有需要并取得适当同意后讨论。未经另行、针对明确目的的同意，Homeground 不会把资料分享给供应商；这里也不是实时库存系统，不保证价格、房态、外宾接待、房型或无障碍适用性。",
    onwardHeading: "离得近，不代表属于杭州这一天",
    onwardColumns: ["地点", "何时连接", "边界"],
    onwardRows: [
      ["上海", "仍是主要国际门户或一日往返基地", "浦东、虹桥与上海市中心是不同旅程"],
      ["苏州", "园林与运河城市形态有独立目的", "它是另一座城市，不是可互换的江南标签"],
      ["绍兴", "鲁迅、水路或深入浙江是下一站目的", "它不是杭州街区"],
      ["黄山", "有时间处理门户、山上山下基地与天气", "它不是杭州一日景点"],
      ["乌镇", "管理型水乡体验值得专程接驳", "它在嘉兴桐乡，不在杭州中心"],
    ],
    recheckHeading: "临行前重新核对",
    recheckItems: [
      "HGH机场当前地铁与道路接驳，以及所需时段的首末班。",
      "每个12306结果和车票上的准确杭州车站。",
      "灵隐与飞来峰当前进入、预约及是否分开售票。",
      "分别核对良渚博物院和各遗址公园通知，包括周一与极端天气。",
      "出行日的西湖游船、交通管制和客流措施。",
      "任何茶访问都核对具名经营者与活动；季节不等于一定采摘或炒制。",
    ],
    faqHeading: "常见问题",
    faqs: [
      ["一日往返还是住两晚？", "只有西湖是唯一重点且返程有安全余量时才选一日往返。灵隐、龙井或本地早晚重要时，两晚是更稳的默认。"],
      ["哪个杭州站最好？", "实际日期下让全程最顺的那一座。东站通常选择最多，城站可适合老城，西站服务另一套西部地理，南站位于萧山。"],
      ["西湖、灵隐和龙井能一天完成吗？", "只有限制停留点并精确安排交通才勉强成立，不适合第一次从上海往返。住杭州时，应把湖区和西部山地分成两个时段。"],
      ["良渚值得一天吗？", "对考古、早期城市、水利与玉器解释有兴趣就值得；如果只是因为它行政上属于大杭州，就不值得硬加。"],
      ["国际航班前一晚要住HGH附近吗？", "不一定。请从国际航班、准确航站楼、值机要求和出行日路线倒推。市区酒店无法保住余量，或儿童、老人、无障碍需求和大件行李让接驳变脆弱时，才优先考虑HGH一侧末晚。仍须复核具体物业的道路、地铁或其书面接驳安排、护照入住与备用方案；‘机场附近’标签不保证实时交通或房态。"],
    ],
    planningTitle: "把城市决定放回完整路线",
    planningLinks: [
      ["检查行程是否太赶", "is-your-china-itinerary-too-rushed", "计算进站、行李和再换一家酒店的成本。"],
      ["审阅已有中国行程", "../china-itinerary-review", "带着现有逐日路线，检查真正薄弱的连接。"],
    ],
    sourcesTitle: "官方来源与复核记录",
    sourceLabels: ["杭州西湖文化景观", "西湖风景名胜区管理机构与当前通知", "HGH机场地铁接驳", "中国铁路12306按日期查询", "良渚官方场馆与天气通知", "良渚古城遗址"],
  },
  ko: {
    lead: "상하이에서 빠른 열차가 있어 항저우를 쉬운 근교 여행처럼 보게 되지만 실제 판단은 문에서 문까지입니다. 서호만이 목적이고 가벼운 짐으로 일찍 출발해 귀환을 보호할 수 있으면 당일치기, 링인·룽징 또는 현지의 아침과 저녁이 중요하면 2박, 대운하나 량주 자체가 목적일 때만 3박째가 의미 있습니다.",
    decisionTitle: "실용적인 기본값",
    decisionBody: "절제된 당일치기는 서호를 설명할 수 있습니다. 2박은 호수와 서쪽 구릉, 현지의 아침을 함께 담고, 3박은 두 번째 유산 지리를 넣습니다. 시간 추가는 핀 개수가 아니라 이해하는 도시의 종류를 바꿔야 합니다.",
    fitHeading: "항저우가 맞는 여행자와 반드시 뺄 것",
    fitColumns: ["여행자", "가장 좋은 이용법", "주의점"],
    fitRows: [
      ["상하이에 머무는 중국 첫 방문자", "서호 중심 하루 또는 상하이와 대비되는 2박", "열차가 짧아도 호텔에서 호수까지의 하루는 짧지 않음"],
      ["문화유산 여행자", "서호, 링인, 대운하와 필요하면 량주", "서로 떨어진 지리를 하나의 옛 도심으로 합치지 말 것"],
      ["느린 여행자·사진 여행자", "이른 아침과 저녁 호숫가, 서쪽 구릉", "호텔 이름보다 실제 물가 방향과 접근이 중요"],
      ["가족·느리게 걷는 여행자", "짧은 물가 구간, 문화 거점 하나, 계획한 차량 이동", "제방·산길·고고학 공원에 숨은 보행이 큼"],
    ],
    nightsHeading: "당일, 2박, 3박이 실제로 더해 주는 것",
    nightsColumns: ["시간 형태", "현실적인 범위", "제외할 것"],
    nightsRows: [
      ["상하이 당일 왕복", "서호 방향 잡기 하나, 연결된 문화 장소 하나, 보호된 귀환", "량주, 대운하 하루, 호수–링인–룽징 몰아넣기"],
      ["2박", "현지 저녁과 아침, 여유 있는 호수 한쪽, 링인 또는 룽징", "량주·운하·모든 호수 구역을 한 숙박에 완성"],
      ["3박", "대운하 또는 량주 같은 두 번째 지리와 날씨 회복", "주변 모든 수향·산을 항저우 근교로 묶기"],
    ],
    stayHeading: "숙소: 홍보 이름이 아니라 도시의 어느 쪽인지 고르세요",
    stayColumns: ["지역", "잘 맞는 경우", "대가"],
    stayRows: [
      ["후빈 / 동쪽 물가", "첫 방문, 짧은 숙박, 식사와 저녁 호숫가", "방문객 압력이 크고 호수 전망 추가요금 가치가 낮을 수 있음"],
      ["베이산 / 우린", "북쪽 문화경관과 도시 기능의 균형", "서로 다른 미세 지역이므로 정확한 핀 확인 필요"],
      ["링인 / 룽징 쪽", "사원, 차 경관과 조용한 서쪽 우선순위", "지하철 약함, 산길 정체, 이른 출발 불편"],
      ["항저우동역 권역", "늦은 도착, 이른 열차, 큰 짐", "관광 중심 동쪽의 물류 거점이지 서호 숙박이 아님"],
    ],
    gatewayHeading: "HGH와 네 기차역은 서로 다른 여정을 해결합니다",
    gatewayIntro: "실제 날짜와 완전한 역 조합을 검색하세요. 항저우서역은 서호역이 아니며, 가장 빠른 열차도 호텔까지 이동에서 장점을 잃을 수 있습니다. 상하이 당일치기는 돌아오는 편을 먼저 설계하고, 숙박은 호텔과 다음 도시가 역을 결정하게 하세요.",
    gatewayColumns: ["관문", "유용한 경우", "막을 실수"],
    gatewayRows: [
      ["HGH 샤오산공항", "직항 또는 오픈조가 상하이 회귀를 없앰", "공항을 도심으로 보거나 철도 환승이 보호된다고 가정"],
      ["항저우역 / 청잔", "해당 날짜 열차가 옛 도심 쪽에 맞음", "항저우라는 검색 결과가 모두 이 역이라고 생각"],
      ["항저우동역", "고속철 선택과 상하이 연결이 많음", "후빈·링인·서쪽 호텔까지 이동을 무시"],
      ["항저우서역", "위항·서쪽 주소 또는 특정 노선에 맞음", "서쪽을 서호로 해석"],
      ["항저우남역", "샤오산 또는 남·동쪽 주소에 맞음", "마지막 이동 확인 없이 옛 도심 역 대신 사용"],
    ],
    clusterHeading: "항저우를 여섯 공간 구역으로 읽으세요",
    clusterColumns: ["구역", "보여 주는 것", "분리할 것"],
    clusterRows: [
      ["동쪽 도시 입구", "도심과 서호의 만남, 가장 쉬운 첫 방향", "량주와 대운하 전체 과제"],
      ["북쪽 / 베이산", "제방, 구산, 박물관과 문학·역사 층", "같은 날 서쪽 구릉과 남쪽까지 완성 약속"],
      ["남쪽 구간", "레이펑과 남쪽 경관의 두 번째 호수 시선", "교통·날씨가 불리한데 억지로 한 바퀴"],
      ["링인과 룽징", "서쪽 구릉의 사원·석각·차 경관", "한 단지 또는 보장된 수확 시연"],
      ["대운하", "북쪽 도시 회랑의 살아 있는 수로 역사", "서호의 다른 물가라고 부르기"],
      ["량주", "선사 도시, 박물관 해석과 고고학 경관", "링인 뒤에 덧붙이거나 역 환승 중 방문"],
    ],
    boundaryTitle: "이 도시 가이드가 다루는 범위",
    boundaryBody: "이 도시 가이드는 당일치기 또는 숙박, 숙박일 수, 거점, 관문, 구역 관계와 다음 도시라는 항저우의 큰 결정을 다룹니다. 역 조합, 량주 장소 순서, 백사전의 근거, 운하 해석과 차 원산지는 아래의 해당 상세 가이드에서 각각 다룹니다. 별도의 일반 항저우 가이드를 다시 찾을 필요는 없습니다.",
    readingTitle: "실행 단계에서는 해당 상세 가이드를 여세요",
    links: [
      ["상하이–항저우 역 조합 고르기", "shanghai-hangzhou-transport-route", "문에서 문까지 철도, 정확한 역과 잘못 간 역 대처."],
      ["량주박물관과 유적공원 계획", "liangzhu-ruins-park-and-museum-sequence", "두 장소를 독립된 교외 유산 하루로 다룹니다."],
      ["항저우 대운하 읽기", "grand-canal-everyday-urban-history", "보호유산, 살아 있는 수로와 동네 생활을 나눕니다."],
      ["룽징을 중국 차 경관에 놓기", "tea-landscape-regions-of-china", "수확 시연을 약속하지 않고 경관·기술·원산지를 봅니다."],
      ["백사전 이야기와 장소 증거 나누기", "white-snake-legend-hangzhou-zhenjiang", "단교, 레이펑 유적과 후대 탑은 다른 증거입니다."],
      ["장강삼각주 전체 순서 고르기", "shanghai-suzhou-hangzhou-nanjing-route-order", "호텔을 추가하기 전 연결형·상하이 거점·두 거점을 정합니다."],
    ],
    stayReadingTitle: "전국 숙박 가이드로 숙소 결정을 마무리하세요",
    stayLinks: [
      ["‘지하철 근처’가 실제로 유용한지 검사", "china-hotel-near-metro", "정확한 출구와 로비까지 전체 경로를 확인하세요. 서호나 역 이름만으로는 부족합니다."],
      ["실제로 쓸 수 있는 접근성 객실 확인", "china-accessible-hotel-room-verification", "결제 전에 도로나 역부터 로비, 엘리베이터, 객실과 욕실까지 확인하세요."],
      ["외국인은 중국의 모든 호텔에 묵을 수 있을까?", "foreigners-china-hotel", "법적 규칙, 플랫폼 표시, 해당 숙소의 현재 등록 운영을 구분하세요."],
      ["국제선 전 마지막 밤 계획", "china-last-night-before-international-flight", "이름이 확인된 HGH 터미널 또는 실제 출국 공항과 항공편에서 거꾸로 계산하세요."],
    ],
    quoteTitle: "항저우 후보 숙소를 사람과 함께 확인하고 싶다면",
    quoteBody: "현재 일반 플래너 창구는 첫 연락에만 이용하세요. 초기 양식에는 여행 날짜, 비교할 도시나 지역, 여행자 수와 객실 수, 필요하다면 대략적인 숙박 예산만 적으세요. 가족 또는 접근성 준비를 나중에 상의하고 싶다고 표시할 수는 있지만, 어린이의 구체적인 나이, 이동·의료·접근성 세부 정보, 여권이나 기타 신분증 정보, 예약·결제 기록, 호텔·DMC 등 공급업체에 전달하려는 식별 가능한 자료는 제출하지 마세요. 플래너가 별도의 후속 상담을 안내하며, 이런 세부 정보는 필요한 경우 적절한 동의를 받은 뒤에만 논의합니다. 별도의 목적별 동의 없이는 공급업체와 자료를 공유하지 않으며, 이 창구는 실시간 재고가 아니므로 가격·객실 가능 여부·외국인 투숙·객실 유형·접근성을 보장하지 않습니다.",
    onwardHeading: "가깝다고 항저우 하루 안에 속하지는 않습니다",
    onwardColumns: ["장소", "연결할 때", "경계"],
    onwardRows: [
      ["상하이", "주요 국제 관문 또는 당일치기 거점", "푸둥·훙차오·도심은 다른 여정"],
      ["쑤저우", "정원과 운하 도시 형태가 독립된 목적", "별도 도시이며 교환 가능한 장난 라벨이 아님"],
      ["사오싱", "루쉰·수로 또는 저장 심화가 다음 목적", "항저우 동네가 아님"],
      ["황산", "관문·산 위아래 거점·날씨를 처리할 시간이 있음", "항저우 당일 명소가 아님"],
      ["우전", "관리형 수향 경험이 이동을 정당화", "자싱 퉁샹에 있으며 항저우 도심이 아님"],
    ],
    recheckHeading: "출발 직전에 다시 확인하세요",
    recheckItems: ["HGH의 현재 지하철·도로 접근과 필요한 시간대 첫차·막차.", "모든 12306 결과와 표의 정확한 항저우 역.", "링인·페이라이펑의 현재 입장·예약·분리 티켓.", "량주박물관과 각 공원 공지를 따로 확인하고 월요일·악천후 처리 보기.", "여행 날짜의 서호 배·교통 통제·인원 조치.", "차 방문은 이름 있는 운영자와 활동을 확인하며 계절을 수확 보장으로 보지 않기."],
    faqHeading: "자주 묻는 질문",
    faqs: [
      ["당일치기인가 2박인가?", "서호만이 목적이고 귀환 여유가 안전할 때만 당일치기입니다. 링인·룽징 또는 현지 아침과 저녁이 중요하면 2박이 더 강한 기본값입니다."],
      ["어느 항저우역이 가장 좋은가?", "실제 날짜의 완전한 이동이 가장 좋은 역입니다. 동역은 선택이 많고, 청잔은 옛 도심에 맞을 수 있으며, 서역은 다른 서쪽 지리, 남역은 샤오산을 맡습니다."],
      ["서호, 링인과 룽징을 하루에 볼 수 있나?", "정류 지점을 줄이고 교통을 정확히 짜야만 가능합니다. 첫 상하이 왕복에는 좋지 않으며 숙박한다면 호수와 서쪽 구릉을 나누세요."],
      ["량주는 하루 가치가 있나?", "고고학, 초기 도시, 수리와 옥 해석이 목적이면 그렇습니다. 넓은 항저우 행정 안에 있다는 이유만이면 넣지 마세요."],
      ["국제선 전날 HGH 근처에 묵어야 하나?", "항상 그렇지는 않습니다. 국제선 항공편, 정확한 터미널, 체크인 요건과 여행일 경로에서 거꾸로 계산하세요. 도심 호텔에서 필요한 여유를 지킬 수 없거나 어린이·고령자·접근성 필요·큰 짐 때문에 이동이 취약할 때 HGH 쪽 마지막 밤을 우선 검토합니다. 해당 숙소의 도로·지하철 또는 서면 셔틀 운영, 여권 체크인과 대안을 다시 확인하세요. ‘공항 근처’ 표시는 실시간 교통이나 객실을 보장하지 않습니다."],
    ],
    planningTitle: "도시 선택을 전체 동선으로 돌려놓기",
    planningLinks: [
      ["일정이 너무 빠른지 확인", "is-your-china-itinerary-too-rushed", "역 접근, 짐과 호텔 이동 하나를 더하는 비용을 셉니다."],
      ["기존 중국 일정 검토", "../china-itinerary-review", "현재 일별 동선을 가져와 실제 약한 연결을 점검합니다."],
    ],
    sourcesTitle: "공식 출처와 검토 기록",
    sourceLabels: ["항저우 서호 문화경관", "서호 경관구 관리기관과 현재 공지", "HGH 공항 지하철 접근", "중국철도 12306 날짜별 검색", "량주 공식 장소·기상 공지", "량주 고성 유적"],
  },
} as const;

const sourceUrls = [
  ["https://whc.unesco.org/en/list/1334/", "UNESCO World Heritage Centre"],
  ["https://westlake.hangzhou.gov.cn/", "Hangzhou West Lake Scenic Area Management Committee"],
  ["https://www.hzairport.com/en/guide/metro.html", "Hangzhou Xiaoshan International Airport"],
  ["https://www.12306.cn/en/index.html", "China Railway 12306"],
  ["https://www.lzsite.cn/", "Hangzhou Liangzhu Archaeological Site Administrative District"],
  ["https://whc.unesco.org/en/list/1592/", "UNESCO World Heritage Centre"],
] as const;

function guidePath(locale: HomegroundLocale, slug: string) {
  return locale === "en" ? `/guides/${slug}/` : `/${locale}/guides/${slug}/`;
}

export function buildHangzhouBody(locale: HomegroundLocale): StructuredPageBody {
  const c = copies[locale];
  return {
    schemaVersion: "1.0.0",
    blocks: [
      { id: "lead", type: "lead", text: c.lead },
      { id: "decision", type: "callout", title: c.decisionTitle, body: c.decisionBody, tone: "decision" },
      { id: "fit-heading", type: "heading", level: 2, text: c.fitHeading },
      { id: "fit", type: "table", caption: c.fitHeading, columns: c.fitColumns, rows: c.fitRows },
      { id: "nights-heading", type: "heading", level: 2, text: c.nightsHeading },
      { id: "nights", type: "table", caption: c.nightsHeading, columns: c.nightsColumns, rows: c.nightsRows },
      { id: "stay-heading", type: "heading", level: 2, text: c.stayHeading },
      { id: "stay", type: "table", caption: c.stayHeading, columns: c.stayColumns, rows: c.stayRows },
      { id: "gateway-heading", type: "heading", level: 2, text: c.gatewayHeading },
      { id: "gateway-intro", type: "paragraph", text: c.gatewayIntro },
      { id: "gateways", type: "table", caption: c.gatewayHeading, columns: c.gatewayColumns, rows: c.gatewayRows },
      { id: "cluster-heading", type: "heading", level: 2, text: c.clusterHeading },
      { id: "clusters", type: "table", caption: c.clusterHeading, columns: c.clusterColumns, rows: c.clusterRows },
      { id: "boundary", type: "callout", title: c.boundaryTitle, body: c.boundaryBody, tone: "neutral" },
      { id: "reading", type: "internal-links", title: c.readingTitle, items: c.links.map(([label, slug, description]) => ({ label, href: guidePath(locale, slug), description })) },
      { id: "stay-owners", type: "internal-links", title: c.stayReadingTitle, items: c.stayLinks.map(([label, slug, description]) => ({ label, href: guidePath(locale, slug), description })) },
      { id: "stay-quote-handoff", type: "callout", title: c.quoteTitle, body: c.quoteBody, tone: "neutral" },
      { id: "onward-heading", type: "heading", level: 2, text: c.onwardHeading },
      { id: "onward", type: "table", caption: c.onwardHeading, columns: c.onwardColumns, rows: c.onwardRows },
      { id: "recheck-heading", type: "heading", level: 2, text: c.recheckHeading },
      { id: "recheck", type: "list", items: c.recheckItems },
      { id: "faq-heading", type: "heading", level: 2, text: c.faqHeading },
      ...c.faqs.flatMap(([question, answer], index) => [
        { id: `faq-${index + 1}-heading`, type: "heading" as const, level: 3 as const, text: question },
        { id: `faq-${index + 1}`, type: "paragraph" as const, text: answer },
      ]),
      { id: "planning", type: "internal-links", title: c.planningTitle, items: c.planningLinks.map(([label, target, description]) => ({
        label,
        href: target.startsWith("..")
          ? locale === "en" ? "/china-itinerary-review/" : `/${locale}/china-itinerary-review/`
          : guidePath(locale, target),
        description,
      })) },
      { id: "sources", type: "sources", title: c.sourcesTitle, items: sourceUrls.map(([url, publisher], index) => ({ label: c.sourceLabels[index], url, publisher, reviewedAt: "2026-08-20" })) },
    ],
  };
}
