import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Two things decide this visit, and neither is the ticket. First, whether you will be comfortable on a narrow reinforced-concrete walkway bolted to a cliff face, moving in a queue that cannot easily stop. Second, whether the reservation, the shuttle and the timing actually put you onto the route you pictured, because reaching the site and getting onto the high walkways are two different achievements. Settle both before you book. The rest — the sculpture, which is extraordinary — takes care of itself." },

  { id: "answer", type: "callout", title: "The two questions to answer before you reserve", tone: "decision", body: "One: can you walk a continuous, narrow, elevated route with steps, at someone else's pace, without stopping to rest wherever you like? The site's own management publishes visitor rules that assume you cannot linger and cannot photograph while on the walkways. Two: have you reserved a time slot through the official channel, and does that slot leave enough of the day for the shuttle, the ticket check and the climb? If either answer is no, fix it before you travel rather than at the gate." },

  { id: "what-heading", type: "heading", level: 2, text: "What the site is, and why there are walkways at all" },
  { id: "what-copy", type: "paragraph", text: "Maijishan is a single isolated hill in Maiji District, southeast of Tianshui in Gansu, named for its resemblance to a stack of harvested wheat. The Dunhuang Academy, which administers the site, records it as roughly 142 metres of rock standing at an elevation of about 1,671 metres, carrying 221 surviving caves, 10,632 statues of various kinds and more than 1,000 square metres of wall painting — enough for the epithet \"museum of Eastern sculpture\". It was listed by the State Council in 1961 in the first batch of nationally protected cultural relic sites, and in 2014 it was inscribed on the World Heritage List as one of the thirty-three component sites of the Silk Roads: the Routes Network of Chang'an-Tianshan Corridor." },
  { id: "what-copy2", type: "paragraph", text: "The walkways are not a modern convenience bolted onto an old site. Carving began under the Later Qin of the Sixteen Kingdoms and peaked under the Northern Wei; work continued through the Western Wei and the Northern Zhou, whose Seven Buddha Niche is the largest undertaking on the cliff; by the Sui the rock face was already covered with caves and with the walkways that reached them. The Academy also records what happened when those walkways failed: in the Ming and Qing, part of the west cliff walkway collapsed and the route was severed, and with no one to repair it, some caves were not entered again after the seventeenth century. Access has always been the whole problem here." },
  { id: "what-callout", type: "callout", title: "The walkway you will use is a 1970s engineering work, and it is itself protected", tone: "neutral", body: "A cultural relics management institute was established at Maijishan in September 1953, and its first task was how to stabilise the cliff with modern engineering. After survey work from 1960 and a 1973 approval, a shotcrete-and-anchor scheme was adopted in 1976. The Academy describes it as the largest and longest-running grotto reinforcement project in China's history, and it won a national science and technology progress award in 1985. That project did two things at once: it stabilised the rock, and it replaced the original timber walkways with reinforced concrete. The institute's deputy director notes that the walkway is now regarded as part of the grotto complex in its own right, with heritage value of its own." },

  { id: "booking-heading", type: "heading", level: 2, text: "Reserve first, and know that there are two kinds of ticket" },
  { id: "booking-copy", type: "paragraph", text: "Maijishan operates on timed reservation. Tickets are booked through the site's official channel in advance, and you check in at the visitor centre for your reserved slot rather than turning up and queueing. There is no useful way to improvise this on the day in high season, and this page will not tell you what capacity exists on any given date, because that is exactly the kind of thing that changes." },
  { id: "booking-list", type: "list", ordered: true, items: [
    "Book through the site's own official ticket channel. The Dunhuang Academy directs visitors to the official ticketing account and to the Maijishan Grottoes ticketing site for ticket detail; the scenic area publishes its own timed-reservation notices.",
    "Note that two ticket types exist, designated A and B, at different prices. They are not the same visit. Read what each one admits you to before you choose, on the operator's own ticketing page, on the date you are booking.",
    "If you qualify for a free or reduced ticket, the concession is processed in person. The Academy publishes that free-entry categories are handled at a designated window at the Xiamen visitor service centre, within a stated morning-to-afternoon window, valid for that day only. Build that into your arrival time.",
    "Confirm the opening season you are travelling in. The site is open all year, on a peak-season schedule from 1 April to 31 October and an off-season schedule from 1 November to 31 March, with different opening and closing times.",
    "Park at the visitor centre and expect to take the scenic-area shuttle rather than driving to the foot of the cliff.",
    "Keep the ticketing enquiry number the Academy publishes, and use it rather than a reseller if something is unclear.",
  ]},
  { id: "booking-warning", type: "callout", title: "Do not buy from a reseller you cannot identify", tone: "warning", body: "This page names no supplier and ranks no platform. The operator publishes its own channels and its own enquiry numbers, and a reservation that does not appear in the operator's system is not a reservation. If a listing promises you specific caves, a guaranteed slot or access to areas the operator does not advertise, treat that as a reason to walk away rather than a bargain." },

  { id: "walkway-heading", type: "heading", level: 2, text: "The walkway, described precisely" },
  { id: "walkway-copy", type: "paragraph", text: "It is worth being exact here rather than atmospheric, because the honest description is neither terrifying nor trivial. The Maijishan Grottoes Art Research Institute's deputy director has described the structure in engineering terms: the walkway is made of cantilever beams, inclined beams, deck slabs, steps and railings. The cantilever beams are anchored generally about four metres into the cliff, project generally two to four metres, and are spaced about three metres apart. The design safety factor is not less than 2.5, and the design live load is 350 kilograms per square metre. The institute has also described plans for a dedicated walkway monitoring system covering visitor numbers, component deformation, stress and strain, and vibration, with visitor numbers controlled by section and at key points according to what the walkway is designed to carry." },
  { id: "walkway-copy2", type: "paragraph", text: "In plain terms: this is a properly engineered structure, regularly maintained, with a designed margin — and it is also narrow, elevated, continuous and shared with everyone else on it at the same time. Those two facts are both true and neither cancels the other. What actually determines whether you will enjoy it is not the engineering; it is whether you are comfortable being high up, in a queue, on a route you cannot casually step off." },
  { id: "walkway-table", type: "table", caption: "The operator's own visitor rules, and what each one tells you about the experience", columns: ["What the site's rules say", "What that means on the walkway"], rows: [
    ["Visitors should assess their own physical condition before entering the cave area, and those with high blood pressure or low blood sugar should be cautious about entering the walkways", "The operator itself flags this as a self-assessment. It is not a fitness test at the gate, and nobody will make the judgement for you"],
    ["All hanging items - water bottles, keys, phones - must be inside a bag or left at storage before the core cave area", "You are above other people. A dropped object is a hazard to someone below, not just a lost object"],
    ["The walkways are narrow: queue, enter in order, keep a steady pace, do not photograph on the walkway, avoid lingering", "You move at the group's pace. If stopping whenever you like is what makes heights bearable for you, plan accordingly"],
    ["No flash photography of the grottoes, no touching; violation ends the visit immediately", "This is enforced, and it applies to phones as well as cameras"],
    ["In rain or snow the cliff sheds small rockfall; at the west cliff exit, keep to the inner side and pass quickly", "Weather changes the walk itself, not just the view"],
    ["There are two toilets, at the west cliff exit and below the plaza steps; there are none on the walkways", "Once you are on the route, you are on it. Plan the stop before you climb"],
    ["No smoking and no pets in the cave area", "Straightforward, and worth knowing before you arrive with either"],
  ]},

  { id: "self-heading", type: "heading", level: 2, text: "A self-assessment, not a medical opinion" },
  { id: "self-copy", type: "paragraph", text: "This guide is not qualified to tell you whether you can do this, and it will not try. What it can do is turn the operator's own guidance into questions specific enough to answer honestly at home, where you have time, rather than at the ticket check, where you do not. The institute's deputy director put the same point more warmly: the route is very well maintained, but you still need to take stock of your own stamina." },
  { id: "self-list", type: "list", ordered: false, items: [
    "Have you walked a continuous flight of outdoor steps, with more steps at the top, without needing to stop? The route is not flat and the ascent is sustained.",
    "Are you comfortable on an elevated walkway with a railing, with open air on one side, for a period measured in tens of minutes rather than seconds?",
    "Can you move at a pace set by the people around you, without pulling over? The rules ask you not to linger.",
    "Would being unable to turn back easily, once you are partway along, be a problem for you?",
    "Do you have a condition the operator specifically names, or any other condition where a sustained climb at altitude would matter? If so, that is a conversation with your own clinician before the trip, not a question for a travel guide.",
    "If you are travelling with someone who would answer no to any of these, have you agreed in advance what that person does while the others go up?",
  ]},
  { id: "self-callout", type: "callout", title: "If the walkways are not for you, say so before you buy", tone: "decision", body: "There is no shame in this and it is far better decided in advance. The site is a hillside complex with a visitor centre, an approach, temple buildings at the foot of the cliff and a view of the whole rock face that is genuinely worth the trip on its own — the cliff read from below is how most people in history saw it. What this page will not do is invent a lower-exposure route through the caves, because whether such a route exists, and what it admits you to, is the operator's to state and can change. Ask the operator directly, using the enquiry numbers it publishes, and take its answer over anyone else's." },

  { id: "arrival-heading", type: "heading", level: 2, text: "Reaching the site and getting onto the route are two different things" },
  { id: "arrival-copy", type: "paragraph", text: "This is the distinction that most often turns a good day into a rushed one. Arriving at Maijishan means getting to the visitor centre in Maiji District. Getting onto the high walkways means, in order: having a valid reservation for the slot you are standing in; parking and taking the shuttle rather than driving to the cliff; passing the ticket check; walking the approach; and then climbing. Each of those has its own clock, and the last two are the ones people forget when they plan the day around a train time." },
  { id: "arrival-table", type: "table", caption: "Two different achievements, and where each one fails", columns: ["Stage", "What can go wrong", "What protects it"], rows: [
    ["Having a valid, correctly timed reservation", "Booking the wrong date, the wrong ticket type, or a slot too late in the day", "Book on the operator's own channel and read what the ticket type admits you to"],
    ["Getting from the visitor centre to the foot of the cliff", "Assuming you can drive to the caves", "Plan on parking at the visitor centre and taking the shuttle"],
    ["The ticket check and any concession processing", "Concessions are processed in person, at a window, within a stated daily window", "Arrive early enough that the window is still open, and carry the documents"],
    ["The approach and the climb", "Underestimating that this is the part with the steps", "Treat it as the main physical event of the day, not the last item"],
    ["The visit itself", "A slot late in the day against a fixed closing time", "Check the seasonal closing time for the date you are going and work backwards"],
    ["Leaving in time for onward travel", "Building a same-day train or flight too tightly around a timed slot", "Give the site the morning and the journey the afternoon, not the reverse"],
  ]},
  { id: "arrival-note", type: "callout", title: "Onward transport is not this page's job", tone: "neutral", body: "The site's own pages do publish public transport routes from Tianshui's stations and airport to the scenic area, and those are the right place to check them, on the date you travel. This guide deliberately does not reproduce bus numbers or journey times: transport between Tianshui's hubs and the site belongs with a transport guide, and printed route numbers age badly. What matters here is only the shape — you arrive at a visitor centre, and a shuttle takes you the rest of the way." },

  { id: "weather-heading", type: "heading", level: 2, text: "Weather, conservation and the parts that close" },
  { id: "weather-copy", type: "paragraph", text: "Maiji's mist is famous and is one of the classic sights of the region, but the same rainy, humid climate is a conservation problem. The institute describes water seepage as a long-term challenge and has set out a working principle of sealing inside the caves and draining across the cave area, while explicitly acknowledging that seepage control cannot be solved in one go. The operator's visitor rules make the immediate consequence plain: in rain or snow, the cliff sheds small rockfall, and visitors are told to keep to the inner side at the west cliff exit and pass through quickly." },
  { id: "weather-comparison", type: "comparison", title: "Three states you may arrive into", columns: [
    { heading: "Normal opening", items: ["The reserved slot, the shuttle, the climb, the walkways", "Move at the queue's pace and keep hands free", "Storage before the core area", "This is the ordinary case and it is well organised"] },
    { heading: "Rain or snow", items: ["The route can still be open with extra caution required", "Rockfall guidance applies at the west cliff exit", "Surfaces and steps are less forgiving", "Consider whether an exposed climb in poor weather is what you came for"] },
    { heading: "Restricted or closed sections", items: ["Conservation work, monitoring, maintenance or weather can close parts of a route", "Which caves are open on a given day is never guaranteed to anyone", "Your ticket type also determines what is included", "Ask at the visitor centre rather than assuming a closure is permanent"] },
  ]},

  { id: "cannot-heading", type: "heading", level: 2, text: "What this page will not promise you" },
  { id: "cannot-copy", type: "paragraph", text: "Three refusals, stated plainly, because the alternative is a guide that sets you up for disappointment. First, no specific cave is promised. Which caves are open depends on conservation status, the day, and your ticket type, and no honest source can fix that in advance. Second, no capacity or quota figure is given, because the operator manages numbers against the walkway's design load and by section, and any number printed here would be a snapshot of one moment. Third, no walkway condition is asserted for your date — the structure is maintained and monitored, and that is a process rather than a guarantee about a Tuesday in October." },
  { id: "cannot-copy2", type: "paragraph", text: "What you can rely on is the shape of the thing: an isolated rock face, an engineered walkway system in place of the timber ones that failed centuries ago, a timed reservation, a shuttle from a visitor centre, two ticket types, and a set of published rules that assume you are moving in a queue at height with your hands free. Everything in this guide is built on that shape, and the shape is stable even when the details move." },

  { id: "facts", type: "callout", title: "Reviewed 22 August 2026", tone: "neutral", body: "Cave, statue and mural counts, the 1961 and 2014 protection and inscription dates, the hill's height and elevation, the carving chronology, the Ming-Qing walkway collapse, the 1953 founding of the management institute, the reinforcement project and its 1985 award, and the walkway's construction, anchor depths, spacing, safety factor and design live load are all as published by the Dunhuang Academy, quoting the Maijishan Grottoes Art Research Institute. Opening seasons and hours, ticket types, concession processing at the visitor service centre, and the visitor rules quoted throughout are as published on the Academy's Maijishan visitor page. **Tianshui municipal and Gansu provincial government sites could not be opened from the network used for this research**; the timed-reservation and shuttle arrangements are corroborated from indexed municipal pages rather than directly verified, and are flagged as such in the source log. No ticket price, capacity figure, cave list or bus route number appears on this page. Confirm hours, ticket types and reservation availability with the operator for your date." },

  { id: "help", type: "callout", title: "Not sure whether the walkways are right for your group?", tone: "decision", body: "Tell us who is travelling, what a normal day of walking looks like for them, and what else is fixed in the trip. Homeground can help you decide whether to build the day around the climb or around the view from below, and how to place it against your onward travel. We do not sell tickets, hold reservations or know which caves will be open — those answers come from the operator." },

  { id: "links", type: "internal-links", title: "Continue planning", items: [
    { label: "Visiting the Mogao Caves independently", href: "/guides/mogao-caves-independent-visit-workflow/", description: "The other Dunhuang Academy site with a reservation-first workflow, kept as its own guide." },
    { label: "Yungang Grottoes: cave order and the museum", href: "/guides/yungang-grottoes-cave-order-and-museum/", description: "A very different site with its own owner; this page makes no comparison between them." },
    { label: "Wheelchair-accessible route planning in China", href: "/guides/wheelchair-accessible-china-route-planning/", description: "If step-free travel is a requirement rather than a preference." },
    { label: "Hub-and-spoke or multi-base routes", href: "/guides/china-hub-and-spoke-or-multi-base-route/", description: "Where a Tianshui day sits in a wider corridor." },
    { label: "China's climate regions and when to travel", href: "/guides/china-climate-regions-for-trip-timing/", description: "Because rain here changes the walk, not just the photographs." },
    { label: "Qilian Mountains: choosing a lawful public gateway", href: "/guides/qilian-mountains-public-gateways-and-access/", description: "If the trip continues northwest into Gansu's mountain country." },
    { label: "Dougong and reading a Chinese timber frame", href: "/guides/dougong-and-chinese-timber-frame-reading/", description: "Useful before you look up at the cliff pavilions." },
  ]},

  { id: "sources", type: "sources", title: "Official sources and image credit", items: [
    { label: "Maijishan Grottoes visitor information: opening seasons, ticket types, concessions, visitor rules and the visitor service centre", url: "https://www.dha.ac.cn/skxl/mjssk.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-08-22" },
    { label: "Conservation at Maijishan: cave and statue counts, protection status, the reinforcement project, and the walkway's construction and design loads", url: "https://www.dha.ac.cn/info/1018/5848.htm", publisher: "Dunhuang Academy, quoting the Maijishan Grottoes Art Research Institute and the Gansu Provincial Cultural Heritage Bureau", reviewedAt: "2026-08-22" },
    { label: "Dunhuang Academy announcements, including weather-related closure notices for the sites it administers", url: "https://www.dha.ac.cn/xwzx/tzgg.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-08-22" },
    { label: "Maijishan Grottoes official ticketing site", url: "http://www.mjssk.cn/", publisher: "Maijishan Grottoes", reviewedAt: "2026-08-22" },
    { label: "Hero: Maijishan Grottoes, the cliff face with its tiered walkways, by Tgasrio, CC0 public domain dedication; cropped and converted to WebP", url: "https://commons.wikimedia.org/wiki/File:Maijishan_grottoes.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" },
    { label: "Hero licence: CC0 1.0 Universal", url: "https://creativecommons.org/publicdomain/zero/1.0/", publisher: "Creative Commons", reviewedAt: "2026-08-22" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
