import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "‘Huangshan’ can mean a summit hotel, Tangkou by the south-gate transfer centre, the scenic area's hot-spring zone, or the urban Tunxi/rail base. They do different jobs. Choose the night by the first gate you must reach in the morning and the train, flight or recovery time you must protect afterward." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Sleep on the summit only when sunrise/sunset access and splitting the mountain walk justify limited inventory, high prices, weather uncertainty and carrying a small bag. Use Tangkou for the practical night before or after the south gate. Use the hot-spring area only when that scenic-area stay is intentional and current internal transport is confirmed. Use Huangshan city/Tunxi for a late rail arrival, early onward train or urban evening—not as if it were the mountain entrance." },
  { id: "boundary", type: "paragraph", text: "This page chooses a base, not a hiking route or hotel ranking. It does not promise sunrise visibility, cableway operation or a fixed transfer timetable. Decide the open entrances and route from current scenic-area notices, then apply the lodging decision." },
  { id: "matrix", type: "table", caption: "Four bases with four jobs", columns: ["Base", "Best job", "Cost", "Verify"], rows: [["Summit", "Sunrise/sunset access and dividing a mountain route", "Limited rooms, weather, carrying essentials, less flexibility", "Open hotel, exact route, cableway/footpath and meal plan"], ["Tangkou / south-gate area", "Efficient pre/post-mountain transfer night", "Little reason to stay for an urban evening", "Distance to transfer centre, pickup and luggage storage"], ["Hot-spring area", "Deliberate scenic-area rest", "Another internal transport link", "Current vehicle access, operating property and onward connection"], ["Huangshan city / Tunxi", "Rail buffer, airport/urban needs and Tunxi evening", "Road transfer before mountain entry", "Exact station, next-day departure and gate"]] },
  { id: "pattern", type: "table", caption: "Choose by the shape of the mountain visit", columns: ["Plan", "Best starting point", "Reason"], rows: [["One full mountain day from the south gate", "Tangkou the previous night", "Protects the first scenic-area transfer without paying for a summit room"], ["Two mountain segments with sunrise/sunset as a priority", "Summit, if the route and room are confirmed", "Avoids descending between the two segments"], ["Late train into Huangshan North or another named rail station", "City/rail-accessible base or confirmed late transfer", "Do not assume the mountain gateway remains reachable"], ["Mountain day then early onward train", "Descend and sleep near the correct rail chain", "Protects the departure from weather and scenic transport"], ["Older traveller or uncertain walking capacity", "Tangkou or accessible scenic hotel after exact route review", "A summit room does not remove steps or mountain walking"]] },
  { id: "summit", type: "heading", level: 2, text: "A summit night buys position, not a sunrise" },
  { id: "summit-copy", type: "paragraph", text: "The summit option can remove a same-day descent and place you on the mountain before day visitors arrive. It does not control cloud, rain, wind or visibility. Choose it for the route even if the view disappears. Ask the hotel which open trail and cableway/footpath combination reaches it, how far you still walk, where dinner and breakfast come from, and what happens if weather or an operating notice changes the approach." },
  { id: "luggage", type: "heading", level: 2, text: "Split the bag before you enter the scenic area" },
  { id: "luggage-copy", type: "paragraph", text: "Carry only the summit night essentials, medicine, weather protection, power and valuables. Confirm in writing where the main suitcase can remain and when it can be collected; do not assume every gateway hotel stores luggage for a non-consecutive booking. Keep the next train's documents and essential medicines with you. A cableway reduces ascent but does not turn the transfer into a curb-to-room journey." },
  { id: "tangkou", type: "heading", level: 2, text: "Tangkou is a transfer base, so judge it by the handoff" },
  { id: "tangkou-copy", type: "paragraph", text: "Official scenic-area information identifies the south-gate transfer system and onward points including the hot-spring area, Ciguangge and Yungu Temple. A Tangkou hotel is useful when it shortens the hotel-to-transfer-centre chain. Ask whether you can walk with bags, whether the property provides a lawful pickup, when reception serves breakfast, and how luggage is stored after check-out. ‘Near Huangshan’ is too broad." },
  { id: "hotspring", type: "heading", level: 2, text: "The hot-spring area is an intentional stay, not Tangkou under another name" },
  { id: "hotspring-copy", type: "paragraph", text: "The hot-spring area sits inside the scenic transport logic. It can suit a slower scenic stay, but adds a handoff that must work with current vehicles, property access and your route. Confirm whether the booked property is operating, how guests enter with luggage, how you reach the intended trail/cableway and what happens after the last internal service. Do not book it merely because the map pin looks closer to the peaks." },
  { id: "city", type: "heading", level: 2, text: "Huangshan city and Tunxi protect rail and urban time" },
  { id: "city-copy", type: "paragraph", text: "An urban base is useful for an evening in Tunxi, a late arrival, an early onward train or a recovery night after descending. It is not a substitute name for Tangkou. Search the full station printed on the ticket and build the road transfer to the chosen gate. If you arrive late, get written confirmation of the final transfer or sleep near the rail chain and enter the mountain the next morning." },
  { id: "weather", type: "callout", title: "Do not make one fragile chain", tone: "warning", body: "Avoid stacking a late train, unverified road transfer, scenic-area shuttle, cableway and long ascent with no buffer. Weather and operating notices can change the mountain portion even when the intercity train is on time. Protect either the mountain morning or the onward train by placing a night on the correct side of the uncertainty." },
  { id: "mobility", type: "heading", level: 2, text: "A cableway is not an accessibility guarantee" },
  { id: "mobility-copy", type: "paragraph", text: "Every mountain base still requires a route-level review: vehicle transfer, queues, cableway cabin access, stone steps, gradients and the walk to the room. Ask the scenic area and property about the exact route for the traveller, not whether Huangshan ‘has cable cars’. Families should also confirm child carrying, toilets, meals and a turn-back point before fatigue becomes a safety problem." },
  { id: "verify", type: "list", items: ["Which named scenic-area entrance and transfer centre will we use?", "Which cableway or footpath is expected to be open for our route?", "How far is the walk from the transport stop to the actual hotel entrance?", "Where is the main suitcase stored and during what hours can it be reclaimed?", "Are dinner, breakfast and drinking-water arrangements confirmed for the summit night?", "What is the weather/closure fallback, and which onward train must not be risked?"] },
  { id: "failure", type: "table", caption: "When conditions change", columns: ["Change", "Immediate decision", "Safer fallback"], rows: [["Summit view forecast deteriorates", "Keep the room only if the route split still has value", "Tangkou base and one-day route"], ["Cableway or section closes", "Use the official notice to redraw the route", "Do not invent a footpath replacement beyond ability"], ["Late arrival misses confirmed transfer", "Stay at a staffed rail/urban property", "Enter through the verified gate next morning"], ["Traveller tires early", "Use the pre-agreed turn-back point", "Do not continue merely to reach a summit booking"], ["Descent is delayed", "Contact the onward hotel/transport", "Sacrifice a flexible urban plan, not a fixed train or flight"]] },
  { id: "registration", type: "paragraph", text: "Ask every property—summit, gateway or city—to confirm the passport check-in process and actual reception hours. The remote setting does not remove normal accommodation-registration duties." },
  { id: "dynamic", type: "paragraph", text: "Huangshan Scenic Area committee service, transfer and accommodation information was reviewed on August 12, 2026. Open areas, cableways, vehicles and property operations can change with maintenance and weather. Check official notices immediately before the visit; the live notice overrides this planning framework." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Minsu, homestay or hotel", href: "/guides/minsu-homestay-or-hotel-china/", description: "Verify a gateway property's service and registration." }, { label: "Is shoulder-season value worth it?", href: "/guides/china-shoulder-season-value-tradeoff/", description: "Protect the weather-dependent mountain experience." }, { label: "China rail-only route planning", href: "/guides/china-rail-only-route/", description: "Check whether the road last mile breaks a rail-only plan." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Huangshan Scenic Area official committee", url: "https://hsgwh.huangshan.gov.cn/", publisher: "Huangshan Scenic Area Administrative Committee", reviewedAt: "2026-08-12" }, { label: "Official scenic-area transfer information", url: "https://hsgwh.huangshan.gov.cn/lyfw/lyfw/jqhc/9197913.html", publisher: "Huangshan Scenic Area Administrative Committee", reviewedAt: "2026-08-12" }, { label: "Official accommodation and no-camping FAQ", url: "https://hsgwh.huangshan.gov.cn/zwgk/public/6617641/11062588.html", publisher: "Huangshan Scenic Area Administrative Committee", reviewedAt: "2026-08-12" }, { label: "Hero: Huangshan sunrise by Politizer, CC BY 3.0; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:Huangshan_sunrise.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
