import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "decision-lead",
      type: "lead",
      text: "上海浦东国际机场（PVG）和上海虹桥国际机场（SHA）服务同一座城市，却会形成两套完全不同的行程。更合适的机场，应该同时具备可用航班，并能更顺畅地衔接酒店、虹桥铁路枢纽、迪士尼计划或下一段固定行程；不能只看哪个机场被称为“离市中心更近”。",
    },
    {
      id: "quick-answer",
      type: "callout",
      title: "先看结论",
      tone: "decision",
      body: "先由航班做第一轮筛选。如果真正可用的直飞、受保护联程或合适票价只出现在一座机场，通常已经有了答案。两场都有合理航班时，上海西部住宿或衔接上海虹桥站，先比较SHA；住浦东东部、搭乘不少国际长航线，或以上海迪士尼区域为起点和终点，先比较PVG。付款前还要补上航站楼步行、交通运营时间、行李和恢复余量。",
    },
    {
      id: "scope-callout",
      type: "callout",
      title: "这里只负责一次机场选择，不继续拆页",
      tone: "neutral",
      body: "本文止于订票前的PVG与SHA选择。浦东机场到迪士尼的详细路线、中国开口程策略、国际航班前一晚缓冲、全国高铁乘车流程和酒店真实地铁距离，继续由Homeground既有文章负责。不新增航站楼、航空公司、酒店榜单或“哪个机场离市区近”等近义页面。",
    },
    {
      id: "flight-heading",
      type: "heading",
      level: 2,
      text: "第一道门：航班真的给了你选择吗？",
    },
    {
      id: "flight-checklist",
      type: "list",
      ordered: true,
      items: [
        "按真实城市组合和出行日期搜索，把每个可用航班的机场代码和航站楼完整写下。",
        "先比较时刻、票价规则、行李、经停次数和联程保障，再衡量市内交通便利。",
        "行程若要求在上海跨机场，把它标成一次陆侧转场，不要当作普通同楼联程。",
        "只有PVG和SHA都保留为可行选项后，才计算机场到酒店、酒店到机场或机场到铁路站的完整链条。",
        "如果地理上方便的机场带来无法使用的抵达时间、过早起飞或脆弱的分票衔接，就应淘汰。",
      ],
    },
    {
      id: "airport-code-warning",
      type: "callout",
      title: "机场代码、航站楼和交通系统要一起看",
      tone: "warning",
      body: "PVG是上海浦东国际机场；SHA是上海虹桥国际机场。上海虹桥站不是机场代码SHA。虹桥机场1号航站楼、2号航站楼和上海虹桥站，都是虹桥大枢纽内不同的实际终点。只要行程有时间压力，就不要把它们都简称为“虹桥”。",
    },
    {
      id: "matrix-heading",
      type: "heading",
      level: 2,
      text: "完整行程决策矩阵",
    },
    {
      id: "whole-trip-matrix",
      type: "table",
      caption: "用行程坐标确定先比较哪座机场，但不能推翻已出票的机场信息",
      columns: ["行程坐标", "选择PVG的理由", "选择SHA的理由", "什么可能改变答案"],
      rows: [
        [
          "只有一个合适航班",
          "所需国际长航线、直飞或受保护行程只在PVG运营时，选择PVG",
          "实用的国内或区域航班只在SHA运营时，选择SHA",
          "严重不合适的时刻、票规或分票衔接，可能抵消所有地面便利",
        ],
        [
          "住浦东金融区或浦东东部",
          "机场和酒店同在上海东侧，通常先比较PVG",
          "仍然可用，但公路或轨道会横跨更多城区",
          "酒店具体入口、航站楼、抵达时段和实时路线",
        ],
        [
          "住人民广场、南京东路或外滩区域",
          "可用地铁2号线或公路，但从航站楼到酒店仍是一段完整接驳",
          "T2接入地铁2号线，公路距离也常让SHA具有吸引力",
          "最后步行、T1还是T2、行李和首末班交通",
        ],
        [
          "住静安、原法租界、古北或上海西部",
          "如果航班明显更好，仍可能值得多走一段地面交通",
          "SHA位于城市西侧，且10号线服务两座航站楼，通常先比较SHA",
          "酒店真正有用的地铁站和出入口，而不是行政区名称",
        ],
        [
          "衔接上海虹桥站",
          "机场联络线到虹桥2号航站楼站，再沿枢纽导向通道前往铁路站",
          "通常最有优势，尤其是T2；T1仍需单独接驳",
          "铁路站名、车次时间、航站楼、行李和完整空铁缓冲",
        ],
        [
          "上海迪士尼度假区",
          "通常先比较PVG；机场联络线的上海国际旅游度假区站在城市东侧，但不在乐园门口",
          "SHA也能乘机场联络线前往度假区站，只是从上海另一端出发",
          "实际航班，以及终点是乐园、迪士尼酒店还是园外酒店",
        ],
        [
          "晚到或早走",
          "PVG可能有必须搭乘的航班，但市区接驳可能更长或超过公共交通时间",
          "SHA常能缩短西部和部分市中心接驳，但T1/T2和首末班仍会改变结果",
          "下飞机后的入境、取行李、楼内步行、等车、路况和酒店抵达",
        ],
      ],
    },
    {
      id: "matrix-note",
      type: "paragraph",
      text: "上海官方交通指南说明，浦东机场同时运营国际和国内航班；虹桥机场以国内及东亚区域航班为主。这只是搜索方向，不是实时航线表。航空公司会新增、移动或取消航班，同一城市也可能同时由两场服务。最终证据始终是已选行程上的机场代码。",
    },
    {
      id: "airport-comparison",
      type: "comparison",
      title: "从机场到酒店门口，两场分别改变了什么",
      columns: [
        {
          heading: "浦东机场 / PVG",
          body: "位于上海东部的综合性国际门户，同时也运营国内航班。",
          items: [
            "不少国际长航线或特定国际服务会直接决定使用PVG",
            "住浦东东部或迪士尼区域时通常先比较PVG",
            "地铁2号线、磁浮线、机场联络线、巴士和公路分别对应不同接驳链",
            "航站楼较大，入境和取行李会让计划落地时间无法代表真正出机场时间",
          ],
        },
        {
          heading: "虹桥机场 / SHA",
          body: "位于上海西部，以国内及东亚区域航班为主，并与虹桥综合交通枢纽相连。",
          items: [
            "国内航班、上海西部酒店或虹桥铁路衔接通常先比较SHA",
            "T1接入地铁10号线；T2接入2号线、10号线和机场联络线",
            "T2可通过枢纽通道前往上海虹桥站",
            "T1航班不会自动获得T2的铁路和机场联络线便利",
          ],
        },
      ],
    },
    {
      id: "airport-link-figure",
      type: "figure",
      src: "/images/guides/shanghai-pudong-or-hongqiao-airport/airport-link-pvg-sha-diagram-1440.webp",
      alt: "Homeground 绘制的机场联络线方位示意图，展示虹桥2号航站楼至浦东1号、2号航站楼之间的七座车站。",
      width: 1440,
      height: 720,
      caption: "方位示意图，不按比例绘制。机场联络线连接七座车站；公布的乘车时间不包含出航站楼、等车、入境、取行李和下一次值机。",
    },
    {
      id: "hotel-heading",
      type: "heading",
      level: 2,
      text: "按酒店大门匹配机场，不要按“上海市中心”匹配",
    },
    {
      id: "hotel-table",
      type: "table",
      caption: "酒店地理位置会改变第一公里和最后一公里",
      columns: ["住宿情况", "优先比较的机场", "隐藏摩擦"],
      rows: [
        [
          "浦东金融区、张江或浦东东部",
          "PVG",
          "酒店仍可能离2号线、磁浮线或机场联络线换乘站很远",
        ],
        [
          "人民广场或南京东路",
          "两场都比较",
          "两边都能接入2号线体系，真正决定因素是航站楼、人流、行李和最后步行",
        ],
        [
          "外滩或老城边缘",
          "两场都比较",
          "景区不是机场地铁站，最后一段公路或步行可能抵消所谓直达",
        ],
        [
          "静安、原法租界或上海南部",
          "通常SHA",
          "10号线或西侧公路方向可能有利，但具体酒店仍可能远离有用入口",
        ],
        [
          "古北、虹桥商务区或国家会展中心周边",
          "通常SHA",
          "必须确认T1还是T2，并计入枢纽内部步行；“虹桥附近”不是精确终点",
        ],
        [
          "迪士尼区域酒店",
          "通常PVG",
          "机场联络线车站不在乐园门口，园外酒店的班车也不一定服务任何机场",
        ],
      ],
    },
    {
      id: "hotel-rule",
      type: "callout",
      title: "酒店位置必须落到街面入口",
      tone: "neutral",
      body: "保存酒店的准确中文名称和入口，按抵达或出发时段检查有用的地铁出入口、电梯、过街方式和车辆能否合法停靠。Homeground的酒店近地铁指南负责这套入口级判断；本文只把判断结果用于PVG与SHA比较。",
    },
    {
      id: "rail-heading",
      type: "heading",
      level: 2,
      text: "虹桥铁路枢纽可能让SHA成为明显答案，但要先确认航站楼",
    },
    {
      id: "rail-copy",
      type: "paragraph",
      text: "上海虹桥站属于更大的虹桥综合交通枢纽。上海官方信息明确提到，铁路站与虹桥机场2号航站楼之间有带导向的连接通道。机场联络线车站名是虹桥2号航站楼站，因此从PVG乘车到达后，仍需下车并沿枢纽实际路线走向铁路站。不要用“在同一个枢纽”省略步行、铁路进站和行李移动。",
    },
    {
      id: "rail-comparison",
      type: "comparison",
      title: "三种虹桥空铁衔接并不等价",
      columns: [
        {
          heading: "SHA T2 ↔ 上海虹桥站",
          items: [
            "机场与铁路几何关系最有优势",
            "沿现场导向通道前往，并确认当日航站楼出入口",
            "仍需加入行李、铁路安检和走到候车区的时间",
          ],
        },
        {
          heading: "SHA T1 ↔ 上海虹桥站",
          items: [
            "T1位于机场另一侧，是不同的实际终点",
            "按实时10号线或公路路线接驳，不要把T2步行套过来",
            "T1航班仍可能合适，但空铁优势会减弱",
          ],
        },
        {
          heading: "PVG ↔ 上海虹桥站",
          items: [
            "机场联络线提供前往虹桥T2方向的直达计划铁路连接",
            "公布的机场到机场车程不是飞机落地到铁路站台的总时间",
            "确认真实铁路站名，并非所有上海列车都从虹桥站出发",
          ],
        },
      ],
    },
    {
      id: "rail-warning",
      type: "callout",
      title: "一张固定火车票也可能直接消除机场选择",
      tone: "warning",
      body: "航班落地后很快要从上海虹桥站乘车时，SHA可能成为唯一合理的机场，但仍要有安全的落地到站台余量。航班落在PVG时，不要用机场联络线约40分钟的计划车程证明可以赶上火车。铁路12306、护照、行李、安检和检票流程请继续阅读Homeground第一次坐中国高铁指南。",
    },
    {
      id: "disney-heading",
      type: "heading",
      level: 2,
      text: "迪士尼通常把比较拉向上海东部，但不会直接送到乐园门口",
    },
    {
      id: "disney-copy",
      type: "paragraph",
      text: "上海迪士尼度假区位于浦东东部，因此以度假区作为行程起点或终点时，通常先比较PVG。机场联络线也把上海国际旅游度假区站设在PVG与SHA之间。但该站不是乐园入口：抵达后，应按度假区最新指引继续前往乐园或具体酒店。如果SHA航班明显更好，完整行程仍可能选择SHA。",
    },
    {
      id: "disney-callout",
      type: "callout",
      title: "迪士尼详细接驳保留在既有canonical页面",
      tone: "neutral",
      body: "确定使用PVG后，再到Homeground浦东机场到上海迪士尼指南比较机场联络线、浦东50路、车辆、行李和真实终点。本文不重复这些步骤，也不会声称选择PVG就已经完成接驳。",
    },
    {
      id: "flight-pattern-heading",
      type: "heading",
      level: 2,
      text: "国际还是国内，只能决定先搜哪里，不能直接决定机场",
    },
    {
      id: "flight-pattern-table",
      type: "table",
      caption: "用两场分工开始搜索，用实时航班结束决策",
      columns: ["航班情况", "先从哪里搜索", "最终检查"],
      rows: [
        [
          "国际长航线",
          "先搜PVG",
          "确认真实直飞、航站楼、时刻、票规和进入上海后的接驳",
        ],
        [
          "港澳台或东亚短程航线",
          "PVG与SHA都搜",
          "另一端使用市区机场可能改变完整行程，但航班仍按日期变化",
        ],
        [
          "中国内地国内航班",
          "先搜SHA，再搜PVG",
          "两场都有国内航班，按具体时刻、酒店和铁路衔接比较",
        ],
        [
          "国际转国内",
          "先把受保护的联程结构放在优先位置",
          "核对是否跨机场、行李是否直挂，以及错过后续航班由谁负责",
        ],
        [
          "从一座中国城市入境、另一座离境",
          "比较完整开口程",
          "国际门户策略、签证或过境条件和回头路由开口程指南负责",
        ],
      ],
    },
    {
      id: "flight-pattern-rule",
      type: "callout",
      title: "不要为了短一点的出租车路程付出过大的航班代价",
      tone: "decision",
      body: "必须用同一出行日、行李、票价灵活性、联程保障和真实抵达时间比较。地面便利可以打破接近的平局，但无法自动解决过夜转机、无保障分票或明显不合适的航班。",
    },
    {
      id: "late-heading",
      type: "heading",
      level: 2,
      text: "早班和晚班会把机场地图变成运营时间测试",
    },
    {
      id: "dated-window-table",
      type: "table",
      caption: "动态交通快照核查于2026年8月11日",
      columns: ["接驳", "官方快照", "对行程的影响"],
      rows: [
        [
          "虹桥机场T2开往PVG的机场联络线",
          "按2026年4月1日运行图，首班05:45、末班22:00、间隔15分钟",
          "T1、铁路站、酒店接驳和航空公司截止时间都要另加",
        ],
        [
          "PVG开往虹桥机场T2的机场联络线",
          "同一运行图下，首班06:00、末班22:15、间隔15分钟",
          "航班在22:15前落地，仍可能因入境、取行李和楼内步行赶不上末班",
        ],
        [
          "上海地铁",
          "PVG接入2号线；SHA T1接入10号线；SHA T2接入2号线和10号线",
          "可用首末班取决于方向和每次换乘，必须按日期查询",
        ],
        [
          "公路和深夜地面交通",
          "机场官网持续发布出租车、巴士和指定上车区信息，可能随交通组织调整",
          "保存当日航站楼上车点，并选择能容纳所有人和行李的车型",
        ],
      ],
    },
    {
      id: "time-warning",
      type: "callout",
      title: "计划落地时间不是地面交通出发时间",
      tone: "warning",
      body: "抵达时要加上滑行、下机、需要时的边检、取行李和航站楼步行；出发时要从航空公司最新值机、托运和登机截止时间倒推。旧时刻表或节假日延时通知不能证明普通出行日仍有同样服务。",
    },
    {
      id: "door-heading",
      type: "heading",
      level: 2,
      text: "比较完整门到门时间",
    },
    {
      id: "door-steps",
      type: "list",
      ordered: true,
      items: [
        "从真实起点开始：飞机座位、酒店入口、铁路到达厅或迪士尼区域酒店。",
        "加入需要时的边检、取行李、洗手间和走到正确交通系统的时间。",
        "加入购票或定位上车点、等下一班车和所有出站换乘。",
        "用预计时段的实时路线加入车上时间，不套用固定博客估算。",
        "加入最终出站、过街、酒店步行、枢纽通道或航站楼安检流程。",
        "在比较两组总数前，加入延误余量和一个真正可执行的后备方案。",
      ],
    },
    {
      id: "luggage-comparison",
      type: "comparison",
      title: "两场接近时，让最困难的行李交接打破平局",
      columns: [
        {
          heading: "轨道交通可能更好",
          items: [
            "运营时间覆盖完整链条，并保留安全余量",
            "每个人都能独立控制自己的行李通过闸机、站台和通道",
            "酒店或铁路终点从下车站确实容易到达",
          ],
        },
        {
          heading: "车辆可能更好",
          items: [
            "儿童、父母、婴儿车或多件大箱子使换乘变得脆弱",
            "一行人走到交通层时，实用轨道服务已经结束",
            "准确的航站楼和酒店上车点可以消除多次交接",
          ],
        },
        {
          heading: "航班仍可能压倒地理位置",
          items: [
            "更好的时刻可以省掉一晚住宿或一次分票衔接",
            "一张票保护后续行程，而另一个选项没有保障",
            "地理方便的机场带来不可接受的票价或改签规则",
          ],
        },
      ],
    },
    {
      id: "recovery-heading",
      type: "heading",
      level: 2,
      text: "发现机场不匹配时，要在余量消失前止损",
    },
    {
      id: "recovery-warning",
      type: "callout",
      title: "PVG与SHA之间没有空侧接驳",
      tone: "warning",
      body: "跨机场是在上海完成的一次陆侧行程。国际过境旅客可能需要入境许可：上海出入境管理部门明确说明，依赖24小时免签过境的旅客如果要离开过境区域跨机场，必须在抵达边检申请临时入境许可。没有确认入境依据和票务责任前，不要购买跨机场衔接。",
    },
    {
      id: "recovery-steps",
      type: "list",
      ordered: true,
      items: [
        "停止移动，打开实时行程，确认PVG还是SHA、航站楼、航班号、日期、起飞时间和当前状态。",
        "立即联系承运航空公司或购票渠道，询问错过值机或衔接后的处理；不要只看地图就开始穿城。",
        "行程仍有可能时，用实时机场联络线与准确定位的公路路线比较，并加入出航站楼、等车、行李、虹桥枢纽步行和完整航司截止时间。",
        "轨道已经停运或余量明显不安全时，先询问当前改签或重订选择，不要把剩余时间全部花在成功率很低的转场上。",
        "同行人、护照和行李保持在一起。航班状态明确后，再重建酒店、火车、迪士尼或后续接驳。",
      ],
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "发现不匹配的时间不同，正确处理也不同",
      columns: ["情况", "立即处理", "不要想当然"],
      rows: [
        [
          "尚未订票",
          "在同一张比较表中加入更合适的机场和完整地面链条",
          "最便宜机票加上跨机场、额外酒店或损失一天后仍最便宜",
        ],
        [
          "已经出票，距离出行还有数周",
          "查看票价改签选项，再与保留机场并规划接驳的成本比较",
          "按上海城市代码搜索意味着航空公司可以免费更换机场",
        ],
        [
          "国际航班抵达一场、后续航班从另一场出发",
          "确认入境许可、行李处理、联程保障和完整陆侧时间线",
          "行李自动跨场转运，或航司一定保护无关的地面行程",
        ],
        [
          "已经到错出发机场",
          "立即联系航司；只有真实余量仍存在时，再检查实时机场联络线或公路路线",
          "约40分钟机场联络线车程等于完整航站楼到登机口时间",
        ],
        [
          "值机关闭或已经误机",
          "向航空公司或购票渠道询问这张票当前的处理方式",
          "旧博客中的改签规则、固定费用或当日补救适用于所有机票",
        ],
      ],
    },
    {
      id: "recovery-figure",
      type: "figure",
      src: "/images/guides/shanghai-pudong-or-hongqiao-airport/hongqiao-t2-railway-wayfinding-1440.webp",
      alt: "从上海虹桥站通往虹桥机场2号航站楼的有标识通道。",
      width: 1440,
      height: 960,
      caption: "这条通道从上海虹桥站通往机场2号航站楼。在虹桥枢纽内，应按交通系统和航站楼前进，不要只认“虹桥”两个字。照片：Shwangtianyuan，CC BY-SA 4.0；已裁剪。",
    },
    {
      id: "verify-heading",
      type: "heading",
      level: 2,
      text: "付款前最后检查",
    },
    {
      id: "verification-list",
      type: "list",
      items: [
        "准确机场代码、航站楼、航班号、承运航司和出行日期",
        "直飞或联程结构、行李路径、票价改签和误接责任",
        "酒店准确入口或迪士尼真实终点的中文名称",
        "准确铁路站、车次时间和合理的空铁衔接余量",
        "所需方向上最新的机场联络线、地铁、磁浮、巴士或公路运营窗口",
        "门到门总时间中的每次等待、通道、出站、最后步行和航空公司截止时间",
        "行李箱、婴儿车、儿童、步行较慢者和需要的协助",
        "任何国际陆侧或跨机场过境所需的入境许可",
        "一条止损线：什么时候应停止穿城，先处理航班",
      ],
    },
    {
      id: "fact-check-box",
      type: "callout",
      title: "动态机场信息核查于2026年8月11日",
      tone: "neutral",
      body: "截至本次核查，PVG同时运营国际和国内航班，接入地铁2号线、磁浮线和机场联络线。SHA以国内和东亚区域航班为主；T1接入10号线，T2接入2号线、10号线和机场联络线。2026年4月运行图列明，虹桥T2开往PVG的首末班为05:45和22:00，PVG开往虹桥T2为06:00和22:15，间隔15分钟；机场到机场计划轨道车程约40分钟。航班库存、航站楼、航司截止时间、铁路时刻、交通运营时间、上车区和入境许可仍须按日期和具体机票核对。",
    },
    {
      id: "help-callout",
      type: "callout",
      title: "需要人工检查完整链条？",
      tone: "decision",
      body: "提交出行日期、拟选航班或路线、人数、大致需求、酒店区域、火车或迪士尼计划、行李和任何固定截止时间。Homeground可以指出哪些机场到门口的交接需要核查；实时航班和交通仍须按日期复核。",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "继续处理真正属于下一步的问题",
      items: [
        {
          label: "规划PVG到上海迪士尼的详细接驳",
          href: "/zh/guides/pudong-airport-to-shanghai-disneyland/",
          description: "选定PVG后，再比较机场联络线、浦东50路、车辆、行李和迪士尼真实终点。",
        },
        {
          label: "选择更大的国际门户和开口程结构",
          href: "/zh/guides/china-open-jaw-flights-route-planning/",
          description: "比较不同入境和离境城市，不把国际航线策略缩减成上海两场问题。",
        },
        {
          label: "保护国际航班前最后一晚",
          href: "/zh/guides/china-last-night-before-international-flight/",
          description: "围绕真实机场和航站楼建立受保护或自行承担风险的离境缓冲。",
        },
        {
          label: "第一次乘坐中国高铁",
          href: "/zh/guides/china-high-speed-train-first-time-guide/",
          description: "虹桥空铁衔接可行后，再了解12306、护照、席别、行李、安检和乘车流程。",
        },
        {
          label: "检查酒店真实地铁位置",
          href: "/zh/guides/china-hotel-near-metro/",
          description: "用真正有用的出入口、最后步行、电梯和行李路线判断酒店区域。",
        },
        { label: "选择上海住宿区", href: "/zh/guides/shanghai-where-to-stay-first-trip/", description: "从步行、轨道覆盖、夜间活动、行李和人流取舍比较外滩、人民广场与原法租界片区。" },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "官方来源与核查记录",
      items: [
        {
          label: "浦东与虹桥的航班分工、航站楼、地铁、出租车和跨场交通",
          url: "https://english.shanghai.gov.cn/en-Transportation/20231214/649e06ea38f74aaeb573fa2debbe97d3.html",
          publisher: "上海市人民政府；来源：上海机场集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "机场联络线车站、换乘、计划车程和行李设施",
          url: "https://english.shanghai.gov.cn/en-Transportation/20241231/f66f14bbd4b549ab88e6f3aec375790c.html",
          publisher: "上海市人民政府；来源：上海申通地铁集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026年4月1日起实施的机场联络线运行图",
          url: "https://www.shanghai.gov.cn/nw17239/20260401/5131b375c3d44c22a2222266ede0a326.html",
          publisher: "上海市人民政府；来源：上海申通地铁集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "浦东机场实时航班、航站楼与地面交通",
          url: "https://www.shairport.com/enpd/",
          publisher: "上海机场集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "虹桥机场地面交通信息",
          url: "https://www.shairport.com/ensh/dmjt/index.html",
          publisher: "上海机场集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "上海虹桥站至T2连接通道及高峰交通组织",
          url: "https://www.shanghai.gov.cn/nw31406/20250208/9ebf6c54a952436791e13d2923029d2a.html",
          publisher: "上海市人民政府；来源：上海公安",
          reviewedAt: "2026-08-11",
        },
        {
          label: "上海迪士尼机场联络线与度假区轨道交通信息",
          url: "https://www.shanghaidisneyresort.com/en/experience/guest-service/rail",
          publisher: "上海迪士尼度假区",
          reviewedAt: "2026-08-11",
        },
        {
          label: "跨机场过境与临时入境许可要求",
          url: "https://english.shanghai.gov.cn/en-ImmigrationCustoms/20251022/2d236278d33f4fbfbd178a9343fb1902.html",
          publisher: "上海市公安局出入境管理局",
          reviewedAt: "2026-08-11",
        },
        {
          label: "中国铁路实时车次查询",
          url: "https://www.12306.cn/en/left-ticket.html?linktypeid=dc",
          publisher: "中国铁路12306",
          reviewedAt: "2026-08-11",
        },
        {
          label: "首图：上海机场联络线列车（已裁剪）",
          url: "https://commons.wikimedia.org/wiki/File:Train_of_Airport_Link_Line.jpg",
          publisher: "Greencarp，经 Wikimedia Commons；CC0 1.0",
          reviewedAt: "2026-08-11",
        },
        {
          label: "照片：上海虹桥站通往机场2号航站楼的通道（已裁剪）",
          url: "https://commons.wikimedia.org/wiki/File:Shanghai_Hongqiao_Railway_Station_channel_to_Hongqiao_Airport_T2.jpg",
          publisher: "Shwangtianyuan，经 Wikimedia Commons；CC BY-SA 4.0",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
