import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "황학루(黄鹤楼), 악양루(岳阳楼), 등왕각(滕王阁) 아래에 서면 가장 먼저 뜻밖의 사실을 마주하게 된다. 이름을 널리 알린 글이 눈앞의 건물보다 오래되었다는 점이다. 우한의 황학루는 1985년 새 부지에서 문을 연 철근콘크리트 재건축물이다. 악양루는 1880년에 확립된 청대 목조 형식과 위치를 이어 오며, 이후 부재를 해체해 보수하는 보존 공사를 거쳤다. 난창의 현 등왕각은 목조건축의 외관을 구현한 철근콘크리트 재건축물로 1989년에 완공되었다. 어느 건물이 가장 오래돼 보이는지가 아니라, 어떤 종류의 연속성을 살펴보고 싶은지에 따라 선택하자.",
    },
    {
      id: "direct-answer",
      type: "callout",
      tone: "decision",
      title: "대부분의 여행에서는 누각 하나만 선택하자",
      body: "오래된 문학적 정체성을 품은 현대 우한의 도시·강변 랜드마크를 보고 싶다면 황학루, 남아 있는 목재와 수리된 목재를 함께 살펴보고 싶다면 악양루, 왕보의 글과 송대 양식을 현대적으로 재구성한 건축 아이디어가 궁금하다면 등왕각을 선택하자. 명성만으로 세 도시를 따로 돌 이유는 없다. 이 가이드는 확인하지 않은 이동 비용을 감춘 채 세 곳을 하나의 문화 코스처럼 제시하지 않는다.",
    },
    {
      id: "continuity-heading",
      type: "heading",
      level: 2,
      text: "세 누각은 서로 다른 세 종류의 연속성을 보존한다",
    },
    {
      id: "continuity-table",
      type: "table",
      caption: "현재 서 있는 건물부터 확인한 뒤 문학의 계보를 더하자",
      columns: ["장소", "오늘날 서 있는 것", "살펴볼 만한 연속성", "주장하면 안 되는 것"],
      rows: [
        ["우한 황학루", "1985년에 문을 연 새 부지의 철근콘크리트 재건축물", "거듭 재건된 이름, 도시를 바라보는 시점, 과거 누각 형식에 대한 현대적 해석", "현 누각이 삼국시대 건물이라는 주장, 또는 옛 건물을 통째로 현재 위치에 옮겼다는 주장"],
        ["웨양의 악양루", "현재 형식과 위치가 1880년에 정해졌고 이후 해체 수리를 거친 청대 목조 주루", "부재 하나하나를 통해 살펴볼 수 있는 재료·형식·보존의 연속성", "모든 부재가 1880년 제작이라는 주장, 또는 3세기부터 손대지 않은 채 서 있었다는 주장"],
        ["난창 등왕각", "1989년에 완공된 철근콘크리트 목조 모사 건축군", "문헌·회화·건축 연구를 관람용 건물로 옮긴 현대 설계", "현 건물이 왕보가 보았던 당대 등왕각이라는 주장, 또는 변함없는 한 터 위에 세운 스물아홉 번째 건물이라는 주장"],
      ],
    },
    {
      id: "continuity-rule",
      type: "paragraph",
      text: "‘원형’이라는 말은 무엇의 원형인지 밝히지 않으면 쓸모가 없다. 그 주장이 이름, 터, 주요 형식, 목재 부재, 설계 참고자료, 시문, 관광 해설 중 무엇에 관한 것인지 물어야 한다. 악양루는 역사적 건축 재료가 가장 많이 남았지만, 문헌으로 확인되는 이전과 대규모 보존 공사 때문에 ‘손대지 않은 원형’이라고 부를 수는 없다. 반면 황학루와 등왕각은 20세기 설계자들이 문학적 기억을 어떻게 눈에 보이는 건축으로 바꾸었는지를 보여 준다.",
    },
    {
      id: "poetry-heading",
      type: "heading",
      level: 2,
      text: "건물은 사라졌는데 글은 왜 살아남았을까?",
    },
    {
      id: "poetry-line",
      type: "paragraph",
      text: "각 이름은 건물이 거듭 사라지는 동안에도 글과 조망의 기억을 축적했다. 최호와 이백과의 연관은 황학루를 우한 너머까지 알렸고, 범중엄은 악양루를 공적 책임과 둥팅호에 연결했으며, 왕보는 등왕각을 직접 본 적 없는 독자에게도 익숙한 문학적 기준점으로 만들었다. 그러나 어느 글도 하나의 건축 도면을 고정해 남기지는 않았다. 그 글들은 후대 건축가에게 이름을 되살리고 조망을 다시 연출할 이유를 주었다.",
    },
    {
      id: "poetry-boundary",
      type: "callout",
      tone: "neutral",
      title: "시는 수용의 역사를 보여 주는 증거이지 실측 도면이 아니다",
      body: "문학은 어떤 누각·조망·이름이 작가와 후대 독자에게 중요했다는 사실을 보여 줄 수 있다. 하지만 문학만으로 모든 들보, 방, 입면, 옛 터를 특정할 수는 없다. 현대의 명문, 벽화, 공연은 안내 표지가 더 오래된 유물과 문서화된 전래 경위를 명확히 밝히지 않는 한 현대 관광 해설의 층위에 속한다. 글은 건물과 함께 읽되, 글만으로 건축 연대를 판정하지 말자.",
    },
    {
      id: "yellow-heading",
      type: "heading",
      level: 2,
      text: "황학루: 현대 도시를 숨기지 않는 1985년 재건축",
    },
    {
      id: "yellow-history",
      type: "paragraph",
      text: "우한의 공원 관리 기관은 황학루의 계보를 223년부터 설명하지만, 중남건축설계원 프로젝트 페이지에는 233년이라고 적혀 있다. 이번 검토에서는 233년을 별도로 확립된 두 번째 연대설로 볼 근거를 찾지 못했다. 그렇다고 두 공식 페이지의 충돌을 조용히 하나로 맞추지도 않았다. 관람 판단에 중요한 사실은 양쪽이 일치한다. 누각은 여러 차례 소실되고 재건되었고, 1868년에 세운 청대 누각은 1884년 화재로 사라졌다. 교량 공사 때문에 옛 터에 다시 세울 수 없었으며, 새 부지의 건물은 1985년 6월에 문을 열었다.",
    },
    {
      id: "yellow-material",
      type: "paragraph",
      text: "설계원 자료는 현 누각을 높이 51.4미터의 철근콘크리트 구조로 설명하며, 외관은 다섯 단이고 내부는 아홉 층이라고 밝힌다. 외관 언어는 청대 누각을 참고하되 지붕 구성과 관람 수용력을 확대했다. 이는 문서로 확인되는 현대적 해석이지, 남아 있는 청대 건축 재료가 아니다. 안내 표지에서 ‘재현’이나 ‘재건’이라는 말을 보면 어느 시대를 참고했는지와 새 건물을 언제 지었는지를 모두 찾아보자.",
    },
    {
      id: "yellow-onsite",
      type: "paragraph",
      text: "먼저 밖에서 시작하자. 외관의 다섯 단을 세어 본 뒤, 내부 동선이 그 실루엣과 일대일로 대응하지 않는다는 점을 살펴본다. 처마에서 시선을 돌려 양쯔강 다리를 보자. 변한 도시는 사진에서 잘라 낼 배경이 아니라 중요한 증거다. 공식 페이지는 청대 누각에서 살아남은 동제 꼭대기 장식이 있다고 설명하지만, 2026년 현재 관람 가능 여부는 확인되지 않았다. 반드시 볼 수 있는 유물로 약속하지 말고, 현장에서 확인할 조사 항목으로만 두자.",
    },
    {
      id: "yellow-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yellow-crane-bridge-view-1200.webp",
      alt: "황학루에서 바라본 우한 양쯔강 대교와 시가지",
      width: 1200,
      height: 800,
      caption: "다리와 현대의 스카이라인은 현 누각이 변화한 도시의 터에 속한다는 사실을 설명한다. 현대 도시가 없는 척하는 것보다 이 조망이 훨씬 많은 정보를 준다.",
    },
    {
      id: "yueyang-heading",
      type: "heading",
      level: 2,
      text: "악양루: 수리 사실까지 드러내는 가장 강한 재료적 연속성",
    },
    {
      id: "yueyang-history",
      type: "paragraph",
      text: "악양루의 공식 서사는 더 먼 과거까지 거슬러 올라가지만, 현재 주루를 이해하는 안전한 기준선은 1880년이다. 지방지에는 장더룽이 주도한 청대 재건 때 누각을 동쪽 안쪽으로 여섯 장(丈) 넘게 옮겼다고 기록되어 있다. 따라서 이 누각은 삼국시대부터 한 지점에 고정되어 있지 않았다. 지금의 3층 목조 형식에는 청말 재건의 틀과 이후 보존·수리·교체된 재료가 함께 들어 있다.",
    },
    {
      id: "yueyang-conservation",
      type: "paragraph",
      text: "부재를 해체하는 보존 공사는 1983년에 시작되었고 누각은 1984년에 다시 문을 열었다. 2025년 성급 문화 당국 자료에 따르면 부재를 평가한 뒤 보수 전 재료의 55퍼센트 이상을 남겼다. 이를 ‘55퍼센트가 1880년 제작’이라는 말로 바꾸면 안 된다. 보존했다는 사실만으로 각 부재의 제작 연대를 알 수는 없다. 수리와 교체는 보존 과정을 보여 주는 증거이지, 눈에 보이는 모든 표면이 같은 시대 것이라는 증명이 아니다.",
    },
    {
      id: "yueyang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-side-1200.webp",
      alt: "목조 골조와 투구 모양 지붕이 보이는 악양루 측면",
      width: 1200,
      height: 800,
      caption: "측면에서 보면 청대 목조 형식과 독특한 지붕을 더 쉽게 읽을 수 있다. 다만 이 사진만으로 기둥·공포·기와 각각의 연대를 알 수는 없다.",
    },
    {
      id: "yueyang-onsite",
      type: "paragraph",
      text: "들어가기 전에 외부를 한 바퀴 돌자. 현판만 보지 말고 기둥 간격, 공포가 놓인 구역, 투구 모양 지붕을 읽는다. 내부에서는 나무 색이 어둡다는 이유로 연대를 판단하지 말고 결, 이음, 수리 흔적을 비교한다. 공식 페이지는 《악양루기》 서예 조각 병풍을 설명하면서 복제품과 제작 시기가 다른 판본도 언급한다. 2026년 전시 상태는 확인되지 않았다. 당일 표지를 기준으로 서예가, 조각 시기, 재료, 복제 여부를 기록하자.",
    },
    {
      id: "yueyang-ceiling-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-ceiling-1200.webp",
      alt: "악양루 내부의 목조 천장 구조",
      width: 1200,
      height: 800,
      caption: "천장은 막연히 오래되었다는 인상보다 부재가 서로 어떻게 연결되는지에 시선을 돌리게 한다. 현재의 출입 및 촬영 규정은 별도로 따라야 한다.",
    },
    {
      id: "tengwang-heading",
      type: "heading",
      level: 2,
      text: "등왕각: 건축 아이디어를 재구성한 1989년 건물",
    },
    {
      id: "tengwang-history",
      type: "paragraph",
      text: "난창의 공식 계보는 653년부터 시작하지만, 현 건물은 1985년에 착공해 1989년 10월 8일에 완공되었다. 공식 보호 목록 문서는 이를 제29차 재건이라고 부른다. 이는 당국이 사용하는 계수 방식이지, 이번 검토가 모든 소실·이전·재건을 각각 독립적으로 확인해 센 횟수는 아니다. 긴 이름의 계보와 문학 이야기를 소개하기 전에 현 건물의 연대와 재료부터 밝히자.",
    },
    {
      id: "tengwang-design",
      type: "paragraph",
      text: "등왕각은 철근콘크리트 구조에 목조건축의 외관 언어를 입힌 건물이다. 공식 자료와 설계자 기록은 송대 회화와 《영조법식(营造法式)》을 참고해 량쓰청과 모쭝장이 1942년에 만든 개념 스케치를 설계의 출발점으로 든다. 재수록된 총설계자 천싱원 인터뷰는 새 부지 선정, 규모 확대, 측면 익랑, 현대적 기능을 설명한다. 모두 20세기에 내린 선택이지, 되찾아 낸 당대 설계도가 아니다.",
    },
    {
      id: "tengwang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-exterior-900.webp",
      alt: "아래에서 올려다본 난창의 현 등왕각",
      width: 900,
      height: 1200,
      caption: "채색 공포, 겹겹의 처마, 측면 건물은 송대에서 영감을 받은 디자인을 표현한다. 그러나 1989년에 완공된 하중 지지 구조는 남아 있는 목조 누각이 아니라 철근콘크리트다.",
    },
    {
      id: "tengwang-onsite",
      type: "paragraph",
      text: "멀찍이 물러서서 주 건물의 덩어리와 양쪽 익랑을 하나의 현대적 구성으로 본다. 가까이에서는 채색 공포 이미지, 발코니, 지붕선과 그 뒤의 구조 체계를 구분한다. 간강과 스카이라인을 이용해 터의 성격을 이해하자. 벽화, 모형, 디지털 설치물, 공연은 교체될 수 있는 현대 해설이며, 이 글은 어느 것도 반드시 볼 수 있다고 약속하지 않는다. 그것 하나를 입장권 구매 이유로 삼기 전에 당일 층별 안내도를 확인하자.",
    },
    {
      id: "tengwang-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-river-view-1200.webp",
      alt: "현 등왕각 사이로 보이는 간강과 난창 스카이라인",
      width: 1200,
      height: 800,
      caption: "현대의 강 조망은 등왕각을 지금의 도시 환경과 연결한다. 왕보나 그 이전 방문객이 보았던 풍경을 그대로 재현하는 것은 아니다.",
    },
    {
      id: "choice-heading",
      type: "heading",
      level: 2,
      text: "이번 여행에서는 어느 곳을 골라야 할까?",
    },
    {
      id: "choice",
      type: "comparison",
      title: "전국 순위가 아니라 질문에 따라 선택하자",
      columns: [
        {
          heading: "황학루",
          items: [
            "이미 우한이 여행 동선에 있고 양쯔강과 도시를 함께 보는 조망이 중요할 때 가장 알맞다",
            "현대 랜드마크가 오래된 이름과 문학적 정체성을 어떻게 이어 가는지 살펴보기에 좋다",
            "철근콘크리트 재건축물에 실망할 사람이라면 옛 건축 재료를 보는 우선순위에서는 제외하자",
          ],
        },
        {
          heading: "악양루",
          items: [
            "목재, 보존, 둥팅호 배경이 핵심 질문일 때 가장 알맞다",
            "수리 사실을 숨기지 않으면서 역사적 재료의 연속성을 살펴보기에는 세 곳 중 가장 강하다",
            "웨양만 따로 우회해야 하고 큰 실내 전시가 주목적이라면 건너뛰자",
          ],
        },
        {
          heading: "등왕각",
          items: [
            "왕보, 재건 설계, 대규모 강변 구성이 관심의 중심일 때 가장 알맞다",
            "연구 참고자료와 20세기 목조 모사 결과물을 비교하기에 좋다",
            "상당량의 오래된 건축 재료가 있어야 문화유산이라고 생각한다면 건너뛰자",
          ],
        },
      ],
    },
    {
      id: "scenario-one",
      type: "paragraph",
      text: "우한에 이미 머무는 첫 방문 여행자라면 보통 이름값 때문에 웨양이나 난창을 덧붙이기보다 황학루를 그대로 선택하는 편이 낫다. 누각과 다리만으로도 현대 재건이라는 질문에 완결된 답을 얻을 수 있다. 건축 보존을 공부하는 학생에게는 악양루의 목재와 부재별 보존 결정이 다른 선택을 정당화할 수 있다. 다만 웨양이 실행 가능한 기존 동선에 들어갈 때에만 그렇다.",
    },
    {
      id: "scenario-two",
      type: "paragraph",
      text: "왕보의 글을 읽었고 이미 장시성을 지나가는 여행자라면, 건물이 더 새것이어도 등왕각에서 가장 직접적인 연결감을 얻을 수 있다. 오래된 건축 재료가 꼭 필요한 사람은 수리라는 단서를 붙여 악양루를 고르거나 세 곳 모두 건너뛰어야 한다. 세 곳을 모두 간다고 이해가 세 배가 되는 경우는 드물다. 문 앞에서 문 앞까지 드는 이동 비용, 짐 처리, 실제로 쓸 수 있는 반나절을 확인하지 않은 상태에서 이 페이지는 도시 간 일정을 만들지 않는다.",
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "어느 누각에서도 같은 여섯 단계 반일 관람법을 쓰자",
    },
    {
      id: "sequence",
      type: "list",
      ordered: true,
      items: [
        "표를 사기 전에 기준선을 읽는다. 현 건물의 연대, 재료, 터와의 관계, 문서로 확인되는 전신을 파악하자.",
        "멀리 물러나 전체 실루엣을 본다. 구조적 덩어리, 지붕 구성, 익랑, 주변 도시나 물을 서로 구분하자.",
        "한 곳의 시공 구역에 가까이 간다. 악양루에서는 목재 이음과 수리, 황학루나 등왕각에서는 콘크리트가 받치는 목조 모사 표현을 살펴본다.",
        "문학 안내판이나 명문 하나를 고른다. 누가 썼는지, 그 판본을 언제 만들었는지, 원유물인지 후대 조각인지 복제품인지 확인하자.",
        "바깥 조망을 이용한다. 우한의 다리, 웨양의 둥팅호, 난창의 간강을 보되 오늘의 스카이라인이 시인이 보았던 정확한 풍경이라고 주장하지 않는다.",
        "현재의 층별 안내도로 마무리한다. 전시, 공연, 승강기, 폐쇄 층, 촬영 규정은 오늘의 운영 조건이지 영구적인 역사 사실이 아니다.",
      ],
    },
    {
      id: "pace-rule",
      type: "paragraph",
      text: "모든 층을 서둘러 도는 대신 이 순서를 지키자. 외부 한 바퀴, 시공 구역 하나, 문학 유물 하나, 바깥 조망 하나면 일관된 반일 관람이 된다. 대기 줄이나 이동 제약 때문에 상층에 갈 수 없다면 지상에서 확인할 수 있는 증거에 집중하자. 확인되지 않은 유물을 기다리지 말고 계속 보이는 재료와 풍경으로 옮겨 가면 된다.",
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "유명한 이름을 손대지 않은 단 하나의 건물로 오해하지 말자",
    },
    {
      id: "layers-table",
      type: "table",
      caption: "네 가지 증거 층위를 분리해서 보자",
      columns: ["층위", "확인할 수 있는 것", "예시", "경계"],
      rows: [
        ["역사 및 물질 증거", "연대가 확인된 건축·이전·화재·수리·부재 또는 문서화된 설계", "악양루의 1880년 형식과 1983–84년 보존 공사", "눈에 보이는 모든 부분의 연대를 자동으로 알려 주지는 않는다"],
        ["문학", "작가와 후대 독자가 장소를 어떻게 상상했는지", "왕보의 서문이나 범중엄의 산문", "시공 도면이나 현재의 층별 안내도가 아니다"],
        ["건축적 해석", "현대 설계자가 참고자료를 고르고 새로운 기능을 해결한 방식", "1985년 황학루와 1989년 등왕각 프로젝트", "남아 있는 고대 건축 재료가 아니다"],
        ["관광 해설", "현 장소가 이야기를 어떻게 설명·공연·홍보하는지", "벽화, 모형, 공연, 재현 서예", "교체되거나 폐쇄될 수 있고 논쟁적인 역사를 단순화할 수 있다"],
      ],
    },
    {
      id: "mistakes",
      type: "callout",
      tone: "warning",
      title: "거부해야 할 다섯 가지 지름길",
      body: "세 곳 모두를 ‘천년 고건축’이라고 부르지 말자. 황학루를 통째로 현재 위치로 옮겼다고 말하지 말자. 악양루의 ‘원래 터와 형식’이라는 표현을 3세기부터 끊김 없이 존속했다는 뜻으로 바꾸지 말자. 등왕각의 공식 ‘제29차 재건’을 한 터에서 이루어진 횟수를 독립적으로 검증한 결과처럼 취급하지 말자. 마지막으로 현대 전시물을 안내 표지 없이 촬영한 뒤 고대 실내의 증거로 사용하지 말자.",
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "예고한 유물·상층·조망을 볼 수 없을 때",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "증거는 남기고 약속은 지우자",
      columns: ["문제", "유지할 것", "바꾸거나 삭제할 것"],
      rows: [
        ["황학루의 동제 유물이 보이지 않는다", "유물 하나가 남았다는 공식 기록과 1985년 건물의 외관", "독자가 특정 동선에서 반드시 찾을 것이라는 주장"],
        ["악양루 서예 병풍이 전시되지 않는다", "글과 병풍 전통에 관한 출처 있는 역사", "특정 층·패널·사진·관람 시간을 보장하는 표현"],
        ["등왕각 모형·벽화·공연이 없다", "1989년 건물과 문서화된 설계 자료", "교체되는 전시를 방문 이유로 삼는 표현"],
        ["상층이 폐쇄되거나 승강기 이용이 제한된다", "외부 순환, 지상에서 보이는 재료, 안내 표지, 공공 경관", "무리한 계단 이동 또는 상층 없이는 관람이 불완전하다는 주장"],
        ["비·연무·인파 통제로 조망을 볼 수 없다", "지붕선, 터와의 관계, 시공 증거", "시적인 파노라마를 보장하는 표현"],
      ],
    },
    {
      id: "dynamic",
      type: "paragraph",
      text: "운영 시간, 입장권, 예약, 승강기, 일방통행 동선, 공연, 촬영 규정은 바뀐다. 실제 방문 날짜의 운영 주체 공지를 다시 확인하고 예약 규정 화면이나 문구를 저장해 두자. 이 글은 실시간 시간표·가격·전시를 약속하지 않는다. 운영 주체의 안내가 불명확하다면 외부부터 보는 방문으로 계획하고, 실내·전시물·식별 가능한 사람을 촬영하기 전에 물어보자.",
    },
    {
      id: "respect",
      type: "callout",
      tone: "neutral",
      title: "먼저 읽고, 그다음 촬영하자",
      body: "현판, 서예 패널, 보존 흔적은 안내 표지와 맥락이 함께 있어야 쓸모 있는 증거가 된다. 목재를 만지거나 난간에 장비를 기대지 말고, 대칭 사진을 찍겠다고 계단을 막지 말자. 다른 방문객이 어기더라도 촬영 금지 및 삼각대 규정을 지켜야 한다. 현대 번역문, 공연 녹화물, 전시문을 길게 복제하지 말고 증거를 요약하면서 출처를 보존하자.",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "이 비교가 유용한 사람과 건너뛰어도 되는 사람은?",
    },
    {
      id: "who",
      type: "paragraph",
      text: "이 비교는 문학 독자, 건축 전공자, 재건에 관심 있는 여행자에게 잘 맞는다. 기존 동선이 다른 도시를 받쳐 주지 못하거나, 계단과 인파가 관람을 소진시키거나, 사라진 ‘원형’만 가치 있다고 생각한다면 도시 하나를 더하지 말자. 한 누각을 천천히 읽으면 오늘의 도시 생활과 세심하게 구성된 문학 이미지가 어디에서 만나는지도 보인다. 가장 유명한 조망이나 전시가 사라진 뒤에도 그곳의 증거에 관한 질문이 흥미롭게 남는 누각이 자신에게 가장 좋은 누각이다.",
    },
    {
      id: "help",
      type: "callout",
      tone: "decision",
      title: "현재 운영 정보를 확인해야 하나요?",
      body: "실제로 쓸 수 있는 관광일을 희생하지 않고 어느 곳이 맞는지 사람이 직접 확인해 주길 원한다면 날짜, 인원, 대략적인 예산을 보내 주세요. 출입, 발권, 승강기, 전시, 촬영 정보는 2026년 8월 14일 기준 변동 정보로 취급했으며 실제 여행 날짜에 다시 확인해야 합니다.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "건축과 경관을 계속 읽어 보기",
      items: [
        {
          label: "성벽·성문·재건의 여러 층위 읽기",
          href: "/ko/guides/chinese-city-walls-gates-and-urban-order/",
          description: "남아 있는 재료, 수리, 재건, 고고학 증거를 구분하는 같은 방법을 적용해 보세요.",
        },
        {
          label: "공포와 목조 골조 읽는 법 배우기",
          href: "/ko/guides/dougong-and-chinese-timber-frame-reading/",
          description: "악양루의 목조 체계와 현대의 목조 모사 표현을 더 세밀하게 비교해 보세요.",
        },
        {
          label: "시가 쑤저우 정원 관람을 빚는 방식 보기",
          href: "/ko/guides/how-to-read-a-suzhou-garden/",
          description: "문학이 제안하는 시선과 건축 재료의 연대에 관한 주장을 계속 구분해 보세요.",
        },
        {
          label: "쯔보 랴오자이의 증거 층위 구분하기",
          href: "/ko/guides/liaozhai-zibo-former-residence-liqu-liaozhai-city/",
          description: "문학과 물질 증거를 나누는 방법을 옛집, 살아 있는 리취 전통과 현대 관광지에 적용합니다.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "공식·설계·기록·연구 자료",
      items: [
        {"label":"황학루 관리 및 역사 개요","url":"https://ylj.wuhan.gov.cn/zwgk/zwxxgkzl_12298/jggk_12304/xsdwszjzz_12308/202001/t20200110_726398.shtml","publisher":"우한시 정원·임업국","reviewedAt":"2026-08-13"},
        {"label":"황학루 프로젝트 기록","url":"https://csadi.com.cn/xmzs/dbzp/whhz_2094/201505/t20150508_52086.html","publisher":"중남건축설계원","reviewedAt":"2026-08-13"},
        {"label":"황학루 현대 재건 연구","url":"https://sjjb.cbpt.cnki.net/portal/journal/portal/client/paper/769f0bd2e3b912b72ad5fa0428cdc30a","publisher":"《세계건축》·CNKI 학술지 플랫폼","reviewedAt":"2026-08-13"},
        {"label":"황학루에서 최호와 이백을 받아들인 문학사","url":"https://xb.yrctu.edu.cn/article/doi/10.13681/j.cnki.cn41-1282/tv.2009.01.018","publisher":"황허수리직업기술대학 학술지","reviewedAt":"2026-08-13"},
        {"label":"악양루 공식 소개","url":"https://www.yueyang.gov.cn/you/content_1630539.html","publisher":"웨양시 인민정부","reviewedAt":"2026-08-13"},
        {"label":"악양루 역사 연표와 1880년 누각 이전 기록","url":"https://www.yueyang.gov.cn/yysqw/43332/43334/43511/44276/content_1267358.html","publisher":"웨양시 지방지 편찬실","reviewedAt":"2026-08-14"},
        {"label":"악양루 보존과 기존 부재 유지","url":"https://whhlyt.hunan.gov.cn/whhlyt/news/mtjj/202503/t20250326_33623203.html","publisher":"후난성 문화관광청","reviewedAt":"2026-08-13"},
        {"label":"1983–84년 악양루 해체 보존 공사","url":"https://daj.yueyang.gov.cn/6658/6667/content_370327.html","publisher":"웨양시 기록관","reviewedAt":"2026-08-13"},
        {"label":"악양루 재건 및 이전 기록","url":"https://dfz.hunan.gov.cn/dfz/dqsj/202211/t20221122_29134400.html","publisher":"후난성 지방지편찬원","reviewedAt":"2026-08-13"},
        {"label":"등왕각 역사 및 건축 개요","url":"https://www.nc.gov.cn/ncszf/rwfg/202505/caef4edf190a44099b002d0891a3d0f8.shtml","publisher":"난창시 인민정부","reviewedAt":"2026-08-13"},
        {"label":"등왕각 보호 목록 기록","url":"https://www.nc.gov.cn/attachment/upload/file/20250806/1754472189182067198.pdf","publisher":"난창시 인민정부","reviewedAt":"2026-08-13"},
        {"label":"등왕각 총설계자 천싱원 인터뷰","url":"https://www.tsinghua.org.cn/info/1951/19465.htm","publisher":"칭화대 교우총회, 설계자 인터뷰 재수록","reviewedAt":"2026-08-13"},
        {"label":"대표 사진: Xiquinho Silva의 현대 황학루, CC BY 2.0; 중앙 크롭·크기·톤 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:Yellow_Crane_Tower_61426-Wuhan_(49150471556).jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"본문 사진: Yumeto가 황학루에서 촬영한 우한 장강대교, CC BY-SA 4.0; 크롭·크기 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:20231125_Wuhan_Yangtze_River_Bridge_seen_from_the_Yellow_Crane_Tower.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"본문 사진: Huangdan2060의 악양루 측면, CC0 1.0; 크롭·크기 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:Yueyang_Tower,_photographed_from_the_side.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"본문 사진: A J Butler의 악양루 천장, CC BY 3.0; 크롭·크기 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:Ceiling_of_Yueyang_Tower_-_panoramio.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"본문 사진: 沈澄心의 현대 등왕각 외관, CC0 1.0; 크기 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:Pavilion_of_Prince_Teng_20231017_32.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"본문 사진: 沈澄心이 등왕각에서 촬영한 감강 풍경, CC0 1.0; 크롭·크기 조정 후 WebP로 변환","url":"https://commons.wikimedia.org/wiki/File:Pavilion_of_Prince_Teng_20231017_08.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"황학루 크롭 파생 이미지에 적용되는 CC BY 2.0 라이선스","url":"https://creativecommons.org/licenses/by/2.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"우한 다리 풍경 크롭 파생 이미지에 적용되는 CC BY-SA 4.0 라이선스","url":"https://creativecommons.org/licenses/by-sa/4.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"악양루 천장 크롭 파생 이미지에 적용되는 CC BY 3.0 라이선스","url":"https://creativecommons.org/licenses/by/3.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"악양루 측면과 등왕각 파생 이미지의 CC0 1.0 공개 선언","url":"https://creativecommons.org/publicdomain/zero/1.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"}
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
