import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "站在黄鹤楼、岳阳楼或滕王阁下，最先要意识到的是：名篇往往比眼前的建筑更古老。武汉黄鹤楼是1985年在新址开放的钢筋混凝土重建建筑；岳阳楼保留了1880年确立的清代木构形制与位置，后来又经过落架维修；南昌现存滕王阁则是1989年落成的钢筋混凝土仿木建筑。不要按谁看起来最古老来选，而要看自己想理解哪一种延续。",
    },
    {
      id: "direct-answer",
      type: "callout",
      tone: "decision",
      title: "多数行程只需选一座",
      body: "想看一座承载古老文学身份、又属于现代武汉江城景观的地标，选黄鹤楼；想观察留存与修缮后的木构，选岳阳楼；想理解王勃名篇如何被转译成一座现代宋式意象建筑，选滕王阁。三座楼的名气本身都不足以支持一次三城绕行；本文也不会把未经核算的换城成本包装成文化路线。",
    },
    {
      id: "continuity-heading",
      type: "heading",
      level: 2,
      text: "三座名楼，延续的是三种不同事物",
    },
    {
      id: "continuity-table",
      type: "table",
      caption: "先认清现存建筑，再接上文学脉络",
      columns: ["地点", "今天矗立的建筑", "值得读的延续", "不能据此声称"],
      rows: [
        ["武汉黄鹤楼", "1985年在新址开放的钢筋混凝土重建建筑", "反复重建的楼名、城市视点，以及现代人对旧楼形制的诠释", "现楼就是三国建筑，或旧楼曾被完整搬到这里"],
        ["湖南岳阳楼", "形制与位置可追溯至1880年的清代木构主楼，后来经过落架维修", "可以逐件观察的材料、形制与保护修缮延续", "每件构件都来自1880年，或此楼自三世纪起从未改变"],
        ["南昌滕王阁", "1989年落成的钢筋混凝土仿木建筑群", "现代设计如何把文字、图像和建筑研究转译为游客可进入的空间", "它就是王勃时代的唐阁，或是同一基址上未经变动的第二十九座建筑"],
      ],
    },
    {
      id: "continuity-rule",
      type: "paragraph",
      text: "不说明对象，“原”这个字几乎没有意义。要问一项说法指的是楼名、地点、主体形制、木构件、设计依据、诗文，还是当代展陈。岳阳楼的历史材料最强，但有据可查的迁移和大修使“未经触动的原物”并不成立。黄鹤楼与滕王阁的价值，则在于展示20世纪设计者如何让文学记忆重新可见。",
    },
    {
      id: "poetry-heading",
      type: "heading",
      level: 2,
      text: "建筑消失以后，文字为什么还能留下？",
    },
    {
      id: "poetry-line",
      type: "paragraph",
      text: "三座名楼都在反复毁建中积累了文章与观看方式。崔颢、李白的关联让黄鹤楼声名远播；范仲淹把岳阳楼、洞庭湖与士人的公共担当联系起来；王勃则让未曾亲见滕王阁的读者也能想象它。这些作品没有冻结一套建筑图纸，却不断给后来者提供恢复楼名、重新组织登临视野的理由。",
    },
    {
      id: "poetry-boundary",
      type: "callout",
      tone: "neutral",
      title: "诗文能证明名楼如何被接受，不是实测图纸",
      body: "文学可以证明某座楼、某种景观或一个名称对作者和后世读者很重要，却不能单独确定每根梁、每个房间、立面和历史基址。现代题刻、壁画与演出都属于旅游展示层；只有标签明确说明旧物身份和可靠来源时，才能另作判断。要把文字与建筑对读，不能用文字给建筑断代。",
    },
    {
      id: "yellow-heading",
      type: "heading",
      level: 2,
      text: "黄鹤楼：不回避现代城市的1985年重建",
    },
    {
      id: "yellow-history",
      type: "paragraph",
      text: "武汉园林主管部门把黄鹤楼沿革起点写作223年，中南建筑设计院项目页则写233年。本次核查没有找到足以把233年视作另一套已确立年代体系的依据，但仍保留这项官方口径冲突，而不擅自调和。与参观最相关的事实一致：历代楼宇屡毁屡建；1868年建成的清楼于1884年焚毁；长江大桥工程使旧基址无法复建；新址建筑于1985年6月开放。",
    },
    {
      id: "yellow-material",
      type: "paragraph",
      text: "设计院记载，现楼为高51.4米的钢筋混凝土结构，外观五层，内部九层。外部语言取法清代黄鹤楼，同时放大屋顶组合与接待容量。它是有明确记录的现代诠释，不是清代木构遗存。标签若写“再现”或“重建”，还要继续确认它参考哪个时代，以及新建筑何时建成。",
    },
    {
      id: "yellow-onsite",
      type: "paragraph",
      text: "先从室外读起：数清外观五层，再留意内部动线并不与轮廓逐层对应。随后把视线从飞檐转向长江大桥——改变后的城市本身就是证据，不应被裁掉。官方页面提到一件清楼遗存铜顶，但尚未确认它在2026年是否展出。把它当作临行查证问题，不要承诺读者一定看到。",
    },
    {
      id: "yellow-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yellow-crane-bridge-view-1200.webp",
      alt: "从黄鹤楼眺望武汉长江大桥与城市",
      width: 1200,
      height: 800,
      caption: "大桥和现代天际线说明现楼属于一个已经改变的城市基址。与其假装现代城市不存在，不如把这层关系读清。",
    },
    {
      id: "yueyang-heading",
      type: "heading",
      level: 2,
      text: "岳阳楼：材料延续最强，但修缮必须明说",
    },
    {
      id: "yueyang-history",
      type: "paragraph",
      text: "岳阳楼的官方沿革可以上溯更早，但现存主楼最稳妥的基线是1880年。地方志记载，清代张德容重建时将楼向东、向内迁移六丈有余。因此，它并非从三国起一直固定在同一点。今天的三层木构形制，结合了晚清重建和后来留存、修补或替换的材料。",
    },
    {
      id: "yueyang-conservation",
      type: "paragraph",
      text: "落架维修始于1983年，岳阳楼于1984年重新开放。湖南省文化主管部门2025年的说明称，维修时逐件评估构件，并保留了超过55%的维修前材料。不能把它改写成“55%都来自1880年”：保留比例并不能给每件构件断代。修补和替换也是保护证据的一部分，而非所有表面同样古老的证明。",
    },
    {
      id: "yueyang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-side-1200.webp",
      alt: "从侧面看岳阳楼的木构架与盔顶",
      width: 1200,
      height: 800,
      caption: "侧面更容易读出清代木构形制和独特盔顶，但照片不能说明每根柱、斗拱或瓦件的年代。",
    },
    {
      id: "yueyang-onsite",
      type: "paragraph",
      text: "入楼前先绕看外部，观察柱网、斗拱区域与盔顶，不要只拍匾额。入内后比较木纹、接榫和维修痕迹，也不要仅凭颜色深浅判断年代。官方页面讨论过《岳阳楼记》书法雕屏，其中包括复制品和年代不同的版本，但2026年陈列状态尚未确认。应以当天标签为准，记录书写者、雕刻年代、材质和复制品身份。",
    },
    {
      id: "yueyang-ceiling-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-ceiling-1200.webp",
      alt: "岳阳楼内部的木构天花",
      width: 1200,
      height: 800,
      caption: "天花让注意力回到构件关系，而不是含混的“古老”印象；现场开放和摄影规定仍须遵守。",
    },
    {
      id: "tengwang-heading",
      type: "heading",
      level: 2,
      text: "滕王阁：用1989年的建筑重构一种建筑意象",
    },
    {
      id: "tengwang-history",
      type: "paragraph",
      text: "南昌官方沿革从653年讲起，但现存建筑1985年开工，1989年10月8日落成。一份官方保护名录称其为第二十九次重建；这是主管部门采用的计数口径，并非本文对每次毁坏、迁址和重建逐项独立核验后的结论。介绍时应先说清现楼年代与材料，再讲更长的名称和文学传承。",
    },
    {
      id: "tengwang-design",
      type: "paragraph",
      text: "现阁采用钢筋混凝土结构和仿木语言。官方与设计者资料把设计源头追溯到梁思成、莫宗江1942年的意向草图，并参考宋画与《营造法式》。总设计师陈星文的转载访谈还谈到新址选择、尺度放大、两翼和现代功能。这些都是20世纪的设计决定，不是失而复得的唐代施工图。",
    },
    {
      id: "tengwang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-exterior-900.webp",
      alt: "从下方仰望南昌现存滕王阁",
      width: 900,
      height: 1200,
      caption: "彩绘斗拱、层叠屋檐和两翼表达宋式设计意向；真正承重的1989年建筑是钢筋混凝土，并非留存下来的木阁。",
    },
    {
      id: "tengwang-onsite",
      type: "paragraph",
      text: "先退远，把主体与两翼看作一套现代构图；走近后，再把彩绘斗拱意象、阳台和屋面轮廓与背后的结构系统分开。借赣江和天际线理解选址。壁画、模型、数字装置与演出都属于可能轮换的解释内容，本文不保证其存在。不要先把某项展陈当作购票理由，应查看当天楼层图。",
    },
    {
      id: "tengwang-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-river-view-1200.webp",
      alt: "从现存滕王阁框景中看到的赣江与南昌天际线",
      width: 1200,
      height: 800,
      caption: "现代江景把滕王阁与今天的城市环境联系起来，却不是王勃或任何古代登临者所见景观的精确复原。",
    },
    {
      id: "choice-heading",
      type: "heading",
      level: 2,
      text: "这次旅行究竟该选哪一座？",
    },
    {
      id: "choice",
      type: "comparison",
      title: "按问题选择，不做全国排名",
      columns: [
        {
          heading: "黄鹤楼",
          items: [
            "武汉本就在行程中，而且长江与城市视点很重要时，最合适",
            "适合观察现代地标怎样承载更古老的名称和文学身份",
            "若最在意历史建筑材料，且钢筋混凝土重建会让你失望，可以跳过",
          ],
        },
        {
          heading: "岳阳楼",
          items: [
            "最关心木构、保护维修和洞庭湖环境时，最合适",
            "三者中最适合在明示维修的前提下观察历史材料延续",
            "若岳阳是孤立绕行，而你主要想看大型室内展览，可以跳过",
          ],
        },
        {
          heading: "滕王阁",
          items: [
            "最关心王勃、重建设计和大型滨江构图时，最合适",
            "适合比较研究依据与20世纪仿木成果之间的转译",
            "若你认定遗产必须包含大量老建筑材料，可以跳过",
          ],
        },
      ],
    },
    {
      id: "scenario-one",
      type: "paragraph",
      text: "第一次到中国、已经住在武汉的旅客，通常应保留黄鹤楼，而不是只为名气再加岳阳或南昌。楼与桥已经能完整回答现代重建这一问题。建筑保护专业学生可能会因岳阳楼木构及构件处理而作出不同选择，但前提仍是岳阳能自然嵌入一条可执行路线。",
    },
    {
      id: "scenario-two",
      type: "paragraph",
      text: "已经读过王勃、又会经过江西的旅客，即使知道滕王阁较新，也可能在那里获得最直接的对应。必须看老材料的人，应带着维修边界选择岳阳楼，或三座都不选。看遍三座名楼，也很少能让理解增加三倍；在门到门成本、行李处理和有效半天未经核验前，本文不设计跨城行程。",
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "任一名楼都可使用同一套六步半日阅读法",
    },
    {
      id: "sequence",
      type: "list",
      ordered: true,
      items: [
        "购票前先读基线：现楼年代、材料、与基址的关系，以及有据可查的前身。",
        "退远看完整轮廓：分清主体体量、屋顶组合、两翼，以及周围城市或水面。",
        "走近一处构造：在岳阳看木构接榫和维修；在黄鹤楼或滕王阁看由混凝土支撑的仿木表达。",
        "只选一处文学标签或题刻：查明作者、当前版本制成年代，以及它是原物、后刻还是复制品。",
        "利用对外视野：武汉与大桥、岳阳与洞庭湖、南昌与赣江；绝不把今天的天际线说成诗人的精确所见。",
        "最后查看当日楼层图：展览、演出、电梯、封闭楼层和摄影规定属于今日运营，不是永久历史事实。",
      ],
    },
    {
      id: "pace-rule",
      type: "paragraph",
      text: "要保护阅读顺序，不必竞速打卡每层楼。绕看外观、一处构造、一件文学对象和一个向外视野，已经构成完整半日。排队或行动限制使高层不可用时，就留在地面读证据；不要苦等未经确认的展品，转向仍然可见的材料与景观。",
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "不要把一个著名楼名误当成一座未被触动的建筑",
    },
    {
      id: "layers-table",
      type: "table",
      caption: "始终分开四层证据",
      columns: ["层次", "能够证明什么", "例子", "边界"],
      rows: [
        ["历史与材料证据", "有年代的建造、迁移、火灾、维修、构件或设计记录", "岳阳楼1880年形制与1983—1984年维修", "不能自动确定所有可见部分的年代"],
        ["文学", "作者及后世读者如何想象这个地方", "王勃序文或范仲淹文章", "不是施工图或当前楼层图"],
        ["建筑诠释", "现代设计者如何选择依据并解决新功能", "1985年黄鹤楼与1989年滕王阁项目", "不是留存的古代材料"],
        ["旅游展示", "景区现在如何解释、演绎或推广故事", "壁画、模型、演出和再制书法", "可能轮换、关闭或简化有争议的历史"],
      ],
    },
    {
      id: "mistakes",
      type: "callout",
      tone: "warning",
      title: "拒绝五种捷径",
      body: "不要把三者统称为“千年古建筑”；不要说旧黄鹤楼被完整搬到现址；不要把岳阳楼“原址原貌”的表述改写成自三世纪起从未中断的留存；不要把滕王阁官方“第二十九次重建”当作同一基址上经独立核实的次数；也不要脱离标签拍摄现代展品，再拿它证明古代室内原貌。",
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "承诺中的展品、高层或景观无法使用时怎么办？",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "保留证据，删除承诺",
      columns: ["故障", "保留", "替换或删除"],
      rows: [
        ["看不到黄鹤楼铜顶遗存", "关于遗存存在的官方记录和1985年建筑外观", "读者会在特定动线找到它的说法"],
        ["岳阳楼书法雕屏未展出", "名篇与雕屏传统的有据历史", "承诺的楼层、屏面、照片或观看时段"],
        ["滕王阁模型、壁画或演出缺席", "1989年建筑和有记录的设计依据", "把轮换展陈当作参观理由"],
        ["高层关闭或电梯受限", "外部绕看、地面材料、标签与公共景观", "强迫登楼或声称参观因此不完整"],
        ["雨雾或人流管控遮蔽视野", "屋顶轮廓、基址关系与构造证据", "保证一定出现的诗意全景"],
      ],
    },
    {
      id: "dynamic",
      type: "paragraph",
      text: "开放时间、门票、预约、电梯、单向动线、演出和摄影规则都会变化，应按实际日期向运营方复核并保留预订规则。本文不发布实时场次、价格或展览承诺。运营信息不清时，先按外观可读来规划；拍摄室内、展品或可识别人物前先询问。",
    },
    {
      id: "respect",
      type: "callout",
      tone: "neutral",
      title: "先阅读，再拍照",
      body: "匾牌、书法屏或维修标记只有连同标签和语境才有意义。不要触摸木构，不要把设备靠在栏杆上，也不要为对称照片堵住楼梯。即使他人无视规定，也要遵守禁拍和三脚架规则。不要大段复制现代译文、演出录像或展览文字；概括证据并保留来源。",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "谁会从比较中获益，谁可以跳过？",
    },
    {
      id: "who",
      type: "paragraph",
      text: "这项比较适合文学读者、建筑学生和对重建感兴趣的旅客。如果路线无法支持多加一城、楼梯与人潮会消耗参观，或你只看重已经消失的“原楼”，就不要绕行。慢慢读一座楼，也能看见当代城市生活如何与经过整理的文学形象相接。最值得看的名楼，是即使最著名的景观或展品消失，它提出的证据问题仍让你感兴趣的那一座。",
    },
    {
      id: "help",
      type: "callout",
      tone: "decision",
      title: "需要核对当前运营细节？",
      body: "如果希望人工判断哪一座能嵌入行程、又不牺牲一个有效游览日，请留下日期、人数和大致预算。出入、票务、电梯、展陈与摄影信息在2026年8月14日均按动态事实处理，旅行前仍须再次核验。",
    },
    {
      id: "links",
      type: "internal-links",
      title: "继续阅读建筑与景观",
      items: [
        {
          label: "从城墙、城门与重建层次读城市",
          href: "/zh/guides/chinese-city-walls-gates-and-urban-order/",
          description: "继续区分原存材料、修缮、复建与考古证据。",
        },
        {
          label: "读懂斗拱与中国木构架",
          href: "/zh/guides/dougong-and-chinese-timber-frame-reading/",
          description: "更准确地比较岳阳楼木构体系与现代仿木表达。",
        },
        {
          label: "看诗意如何塑造苏州园林的观看方式",
          href: "/zh/guides/how-to-read-a-suzhou-garden/",
          description: "继续把文学观看方法与材料年代判断分开。",
        },
        {
          label: "分清淄博聊斋的证据层",
          href: "/zh/guides/liaozhai-zibo-former-residence-liqu-liaozhai-city/",
          description: "把文学与物质证据分开的方法带到故居、活态俚曲与现代景区。",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "官方、设计、档案与研究来源",
      items: [
        {"label":"黄鹤楼管理与历史沿革","url":"https://ylj.wuhan.gov.cn/zwgk/zwxxgkzl_12298/jggk_12304/xsdwszjzz_12308/202001/t20200110_726398.shtml","publisher":"武汉市园林和林业局","reviewedAt":"2026-08-13"},
        {"label":"黄鹤楼项目记录","url":"https://csadi.com.cn/xmzs/dbzp/whhz_2094/201505/t20150508_52086.html","publisher":"中南建筑设计院","reviewedAt":"2026-08-13"},
        {"label":"黄鹤楼现代重建研究","url":"https://sjjb.cbpt.cnki.net/portal/journal/portal/client/paper/769f0bd2e3b912b72ad5fa0428cdc30a","publisher":"《世界建筑》／中国知网期刊平台","reviewedAt":"2026-08-13"},
        {"label":"黄鹤楼崔颢与李白文学接受研究","url":"https://xb.yrctu.edu.cn/article/doi/10.13681/j.cnki.cn41-1282/tv.2009.01.018","publisher":"黄河水利职业技术学院学报","reviewedAt":"2026-08-13"},
        {"label":"岳阳楼官方介绍","url":"https://www.yueyang.gov.cn/you/content_1630539.html","publisher":"岳阳市人民政府","reviewedAt":"2026-08-13"},
        {"label":"岳阳楼历史事件与1880年迁移","url":"https://www.yueyang.gov.cn/yysqw/43332/43334/43511/44276/content_1267358.html","publisher":"岳阳市地方志办公室","reviewedAt":"2026-08-14"},
        {"label":"岳阳楼保护维修与保留构件","url":"https://whhlyt.hunan.gov.cn/whhlyt/news/mtjj/202503/t20250326_33623203.html","publisher":"湖南省文化和旅游厅","reviewedAt":"2026-08-13"},
        {"label":"岳阳楼1983—1984年落架维修","url":"https://daj.yueyang.gov.cn/6658/6667/content_370327.html","publisher":"岳阳市档案馆","reviewedAt":"2026-08-13"},
        {"label":"岳阳楼重建与迁移记录","url":"https://dfz.hunan.gov.cn/dfz/dqsj/202211/t20221122_29134400.html","publisher":"湖南省地方志编纂院","reviewedAt":"2026-08-13"},
        {"label":"滕王阁历史与建筑概述","url":"https://www.nc.gov.cn/ncszf/rwfg/202505/caef4edf190a44099b002d0891a3d0f8.shtml","publisher":"南昌市人民政府","reviewedAt":"2026-08-13"},
        {"label":"滕王阁保护名录记录","url":"https://www.nc.gov.cn/attachment/upload/file/20250806/1754472189182067198.pdf","publisher":"南昌市人民政府","reviewedAt":"2026-08-13"},
        {"label":"滕王阁总设计师陈星文访谈","url":"https://www.tsinghua.org.cn/info/1951/19465.htm","publisher":"清华校友总会（转载设计师访谈）","reviewedAt":"2026-08-13"},
        {"label":"首图：Xiquinho Silva拍摄现代黄鹤楼，CC BY 2.0；已居中裁切、缩放、调整色调并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Yellow_Crane_Tower_61426-Wuhan_(49150471556).jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：Yumeto从黄鹤楼拍摄武汉长江大桥，CC BY-SA 4.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:20231125_Wuhan_Yangtze_River_Bridge_seen_from_the_Yellow_Crane_Tower.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：Huangdan2060从侧面拍摄岳阳楼，CC0 1.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Yueyang_Tower,_photographed_from_the_side.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：A J Butler拍摄岳阳楼天花，CC BY 3.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Ceiling_of_Yueyang_Tower_-_panoramio.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：沈澄心拍摄现代滕王阁外观，CC0 1.0；已缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Pavilion_of_Prince_Teng_20231017_32.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：沈澄心从滕王阁拍摄赣江景观，CC0 1.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Pavilion_of_Prince_Teng_20231017_08.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"黄鹤楼裁切衍生图适用的CC BY 2.0许可","url":"https://creativecommons.org/licenses/by/2.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"武汉桥景裁切衍生图适用的CC BY-SA 4.0许可","url":"https://creativecommons.org/licenses/by-sa/4.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"岳阳楼天花裁切衍生图适用的CC BY 3.0许可","url":"https://creativecommons.org/licenses/by/3.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"岳阳楼侧景与滕王阁衍生图的CC0 1.0贡献声明","url":"https://creativecommons.org/publicdomain/zero/1.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"}
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
