import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Below Yellow Crane Tower, Yueyang Tower or Tengwang Pavilion, the first surprise is that the famous writing is older than the building in front of you. Wuhan has a reinforced-concrete reconstruction opened on a new site in 1985. Yueyang keeps a Qing timber form and position established in 1880, with later dismantling conservation. Nanchang's present pavilion is a reinforced-concrete, faux-timber reconstruction completed in 1989. Choose by the continuity you want to examine, not by which looks oldest.",
    },
    {
      id: "direct-answer",
      type: "callout",
      tone: "decision",
      title: "For most trips, choose one tower",
      body: "Choose Yellow Crane Tower for a modern Wuhan city-and-river landmark carrying an older literary identity; Yueyang for surviving and repaired timber fabric; or Tengwang for Wang Bo's text and a reconstructed Song-style idea. None justifies a three-city detour by reputation alone, and this guide does not disguise unchecked transfer costs as a cultural route.",
    },
    {
      id: "continuity-heading",
      type: "heading",
      level: 2,
      text: "Three towers preserve three different kinds of continuity",
    },
    {
      id: "continuity-table",
      type: "table",
      caption: "Start with the present structure, then add the literary line",
      columns: ["Site", "What stands today", "Continuity worth reading", "Do not claim"],
      rows: [
        ["Yellow Crane Tower, Wuhan", "A reinforced-concrete reconstruction on a new site, opened in 1985", "A repeatedly rebuilt name, city viewpoint and modern interpretation of earlier tower forms", "That the current tower is the Three Kingdoms building, or that it was physically moved intact"],
        ["Yueyang Tower, Yueyang", "A Qing timber main tower whose present form and location date to 1880, conserved through later dismantling repair", "Material, form and conservation continuity that can be examined member by member", "That every component is from 1880, or that the tower has stood untouched since the third century"],
        ["Tengwang Pavilion, Nanchang", "A reinforced-concrete faux-timber complex completed in 1989", "A modern design translating textual, pictorial and architectural research into a visitor building", "That this is Wang Bo's Tang pavilion, or the twenty-ninth building on one unchanged footprint"],
      ],
    },
    {
      id: "continuity-rule",
      type: "paragraph",
      text: "The word 'original' is useless without a noun. Ask whether a claim concerns the name, site, main form, timber member, design reference, poem or visitor presentation. Yueyang has the strongest historic fabric, but its documented move and major conservation rule out 'untouched original.' Yellow Crane and Tengwang instead reveal how twentieth-century designers made literary memory visible.",
    },
    {
      id: "poetry-heading",
      type: "heading",
      level: 2,
      text: "Why did the writing survive when the buildings did not?",
    },
    {
      id: "poetry-line",
      type: "paragraph",
      text: "Each name gathered texts and views through repeated loss. Cui Hao and Li Bai associations carried Yellow Crane beyond Wuhan; Fan Zhongyan tied Yueyang to public responsibility and Dongting Lake; Wang Bo made Tengwang a reference for readers who never saw it. None froze one architectural plan. The writings gave later builders reasons to recover a name and stage a view again.",
    },
    {
      id: "poetry-boundary",
      type: "callout",
      tone: "neutral",
      title: "A poem is evidence of reception, not a measured drawing",
      body: "Literature can establish that a tower, view or name mattered to an author and later readers. It cannot by itself identify every beam, room, elevation or historic footprint. Modern inscriptions, murals and performances are tourism-presentation layers unless their labels identify an older object and a documented provenance. Read the words with the building; do not use the words to date the building.",
    },
    {
      id: "yellow-heading",
      type: "heading",
      level: 2,
      text: "Yellow Crane Tower: a 1985 reconstruction that does not hide the modern city",
    },
    {
      id: "yellow-history",
      type: "paragraph",
      text: "Wuhan's park authority starts the lineage in 223; the Central-South Architectural Design Institute project page prints 233. This review found no basis for treating 233 as a second established chronology, but retains the official-page conflict instead of silently harmonising it. The visitor-critical facts agree: towers were repeatedly lost and rebuilt; the Qing tower erected in 1868 burned in 1884; bridge works prevented rebuilding on the old footprint; and the new-site building opened in June 1985.",
    },
    {
      id: "yellow-material",
      type: "paragraph",
      text: "The institute describes a 51.4-metre reinforced-concrete structure with five visible levels and nine internal floors. Its outward language draws on the Qing tower while expanding roof composition and visitor capacity. This is documented modern interpretation, not surviving Qing fabric. When a label says 'reappearance' or 'reconstruction,' find both the referenced period and the new construction date.",
    },
    {
      id: "yellow-onsite",
      type: "paragraph",
      text: "Begin outside. Count five exterior levels, then notice that interior circulation does not map one-to-one onto the silhouette. Turn from the eaves to the Yangtze bridge: the changed city is evidence, not background to crop away. Official pages describe a surviving copper top from the Qing tower, but its 2026 visibility is unconfirmed. Treat it as a research prompt, not a promised object.",
    },
    {
      id: "yellow-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yellow-crane-bridge-view-1200.webp",
      alt: "The Wuhan Yangtze River Bridge and city seen from Yellow Crane Tower",
      width: 1200,
      height: 800,
      caption: "The bridge and contemporary skyline explain why the current tower belongs to a changed urban site. This view is more informative than pretending the modern city is absent.",
    },
    {
      id: "yueyang-heading",
      type: "heading",
      level: 2,
      text: "Yueyang Tower: the strongest material continuity, with repair made explicit",
    },
    {
      id: "yueyang-history",
      type: "paragraph",
      text: "Yueyang's official narrative reaches earlier, but the safe baseline for the present main tower is 1880. A local chronicle records that Zhang Derong's Qing reconstruction moved it eastward and inward by more than six zhang. The tower therefore has not occupied one fixed point since the Three Kingdoms. Its three-storey timber form combines the late Qing reconstruction with material later retained, repaired or replaced.",
    },
    {
      id: "yueyang-conservation",
      type: "paragraph",
      text: "Dismantling conservation began in 1983 and the tower reopened in 1984. A 2025 provincial cultural-authority account says components were assessed and more than 55 percent of pre-repair material retained. Do not convert that into '55 percent dates to 1880': retention does not date every member. Repairs and replacements are part of the conservation evidence, not proof that all surfaces are equally old.",
    },
    {
      id: "yueyang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-side-1200.webp",
      alt: "A side view of Yueyang Tower showing its timber frame and helmet-shaped roof",
      width: 1200,
      height: 800,
      caption: "The side view makes the Qing-period timber form and distinctive roof easier to read. It does not identify the date of each individual column, bracket or tile.",
    },
    {
      id: "yueyang-onsite",
      type: "paragraph",
      text: "Circle the exterior before entering. Read column spacing, bracket zones and the helmet-shaped roof, not only the plaque. Inside, compare grain, joins and repair marks without dating wood by darkness. Official pages discuss calligraphic screens for the Memorial to Yueyang Tower, including reproductions and differently dated versions. Their 2026 display is unconfirmed: use the day's label, recording calligrapher, carving date, material and replica status.",
    },
    {
      id: "yueyang-ceiling-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/yueyang-ceiling-1200.webp",
      alt: "The timber ceiling structure inside Yueyang Tower",
      width: 1200,
      height: 800,
      caption: "The ceiling directs attention to structural relationships rather than a vague claim of antiquity. Current access and photography rules must still be followed.",
    },
    {
      id: "tengwang-heading",
      type: "heading",
      level: 2,
      text: "Tengwang Pavilion: a 1989 building that reconstructs an architectural idea",
    },
    {
      id: "tengwang-history",
      type: "paragraph",
      text: "Nanchang's official lineage begins in 653, but the present building was begun in 1985 and completed on 8 October 1989. An official protection-list document calls it the twenty-ninth reconstruction; that is the authority's convention, not a count independently verified here across every loss, move and rebuild. Introduce the current date and material before the longer name and literary line.",
    },
    {
      id: "tengwang-design",
      type: "paragraph",
      text: "The pavilion is reinforced concrete with a faux-timber language. Official and designer accounts trace it to 1942 concept sketches by Liang Sicheng and Mo Zongjiang, informed by Song images and Yingzao Fashi. A republished interview with chief designer Chen Xingwen describes new-site selection, enlarged scale, side wings and modern functions. These are twentieth-century choices, not a recovered Tang blueprint.",
    },
    {
      id: "tengwang-exterior-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-exterior-900.webp",
      alt: "The present Tengwang Pavilion in Nanchang viewed from below",
      width: 900,
      height: 1200,
      caption: "Painted brackets, layered eaves and side volumes express a Song-inspired design, while the load-bearing building completed in 1989 is reinforced concrete rather than a surviving timber pavilion.",
    },
    {
      id: "tengwang-onsite",
      type: "paragraph",
      text: "Stand back to see the main mass and wings as one modern composition. Close up, separate painted bracket imagery, balconies and rooflines from the structural system behind them. Use the Gan River and skyline to understand the site. Murals, models, digital installations and performances are rotating interpretation; none is promised here. Check the day's floor map before making one the reason to buy a ticket.",
    },
    {
      id: "tengwang-view-figure",
      type: "figure",
      src: "/images/guides/three-literary-towers-comparison/tengwang-river-view-1200.webp",
      alt: "The Gan River and Nanchang skyline framed by the present Tengwang Pavilion",
      width: 1200,
      height: 800,
      caption: "The modern river view connects the pavilion to its urban setting. It does not recreate the exact landscape that Wang Bo or any earlier visitor saw.",
    },
    {
      id: "choice-heading",
      type: "heading",
      level: 2,
      text: "Which one should you choose for this trip?",
    },
    {
      id: "choice",
      type: "comparison",
      title: "Choose by the question, not by a national ranking",
      columns: [
        {
          heading: "Yellow Crane Tower",
          items: [
            "Best when Wuhan is already on the route and the Yangtze-city viewpoint matters",
            "Useful for studying how a modern landmark carries an older name and literary identity",
            "Skip as a heritage-fabric priority if reinforced-concrete reconstruction disappoints you",
          ],
        },
        {
          heading: "Yueyang Tower",
          items: [
            "Best when timber, conservation and the Dongting Lake setting are the main questions",
            "The strongest of the three for examining historic material continuity with repairs disclosed",
            "Skip if Yueyang is an isolated detour and you mainly want a large interior exhibition",
          ],
        },
        {
          heading: "Tengwang Pavilion",
          items: [
            "Best when Wang Bo, design reconstruction and a large riverfront composition are the focus",
            "Useful for comparing research references with a twentieth-century faux-timber result",
            "Skip if your definition of heritage requires substantial old building fabric",
          ],
        },
      ],
    },
    {
      id: "scenario-one",
      type: "paragraph",
      text: "A first-time visitor already staying in Wuhan should normally keep Yellow Crane rather than add Yueyang or Nanchang for name recognition. Tower and bridge answer a complete question about modern rebuilding. For an architectural-conservation student, Yueyang's timber and component decisions may justify the different choice—but only if Yueyang already fits a workable route.",
    },
    {
      id: "scenario-two",
      type: "paragraph",
      text: "A reader of Wang Bo already crossing Jiangxi may find Tengwang the most direct encounter despite its newer building. Someone requiring old fabric should choose Yueyang with the repair caveat, or skip the trio. Visiting all three rarely triples understanding. Without checked door-to-door costs, luggage handling and usable half-days, this page does not build a cross-city itinerary.",
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "Use the same six-step half-day reading method at any tower",
    },
    {
      id: "sequence",
      type: "list",
      ordered: true,
      items: [
        "Read the baseline before the ticket: current building date, material, site relationship and documented predecessor.",
        "Step back for the full silhouette: separate structural mass, roof composition, wings and surrounding city or water.",
        "Move close to one construction zone: timber join and repair at Yueyang; concrete-supported faux-timber expression at Yellow Crane or Tengwang.",
        "Choose one literary label or inscription: identify who wrote it, when that version was made and whether it is an original object, later carving or reproduction.",
        "Use the outward view: bridge and Wuhan, Dongting Lake and Yueyang, or Gan River and Nanchang; never claim today's skyline is the poet's exact view.",
        "Finish with the current floor map: treat exhibits, performances, lifts, closed levels and photo rules as today's operations, not permanent historical facts.",
      ],
    },
    {
      id: "pace-rule",
      type: "paragraph",
      text: "Protect the sequence instead of racing every floor. An exterior circuit, one construction zone, one literary object and one outward view make a coherent half-day. If queues or mobility remove upper levels, stay with ground-level evidence. Do not wait for an unconfirmed artefact; move to material and landscape that remain visible.",
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "Do not mistake a famous name for one untouched building",
    },
    {
      id: "layers-table",
      type: "table",
      caption: "Keep four evidence layers separate",
      columns: ["Layer", "What it can establish", "Example", "Boundary"],
      rows: [
        ["History and material evidence", "A dated build, move, fire, repair, component or documented design", "Yueyang's 1880 form and 1983–84 conservation", "Does not automatically date every visible part"],
        ["Literature", "How an author or later readers imagined the place", "Wang Bo's preface or Fan Zhongyan's prose", "Is not a construction drawing or current floor plan"],
        ["Architectural interpretation", "How modern designers selected references and solved new functions", "The 1985 Yellow Crane and 1989 Tengwang projects", "Is not surviving ancient fabric"],
        ["Tourism presentation", "How the site currently explains, performs or markets the story", "Murals, models, shows and recreated calligraphy", "May rotate, close or simplify contested history"],
      ],
    },
    {
      id: "mistakes",
      type: "callout",
      tone: "warning",
      title: "Five shortcuts to reject",
      body: "Do not call all three 'thousand-year-old buildings.' Do not say Yellow Crane Tower was moved intact to its current site. Do not turn Yueyang's 'original site and form' language into uninterrupted survival since the third century. Do not treat the official 'twenty-ninth reconstruction' at Tengwang as an independently verified count on one footprint. And do not photograph a modern display without its label, then use it as proof of an ancient interior.",
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "If the promised object, upper floor or view is unavailable",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Keep the evidence; remove the promise",
      columns: ["Failure", "Keep", "Replace or remove"],
      rows: [
        ["Yellow Crane copper remnant is not visible", "The official record that one survives and the 1985 building's exterior", "Any claim that the reader will find it on a particular route"],
        ["Yueyang calligraphic screen is off display", "The sourced history of the text and screen tradition", "A promised floor, panel, photograph or viewing time"],
        ["Tengwang model, mural or show is absent", "The 1989 building and documented design sources", "The rotating exhibit as a reason for the visit"],
        ["Upper levels close or lifts are restricted", "Exterior circuit, ground-level fabric, labels and public landscape", "A forced climb or claim that the visit is incomplete"],
        ["Rain, haze or crowd control removes the view", "Roofline, site relationship and construction evidence", "A guaranteed poetic panorama"],
      ],
    },
    {
      id: "dynamic",
      type: "paragraph",
      text: "Hours, tickets, reservations, lifts, one-way routes, performances and photography rules are dynamic. Recheck the operator for the actual date and retain the booking rule. This article publishes no live timetable, price or exhibition promise. If the operator is unclear, plan an exterior-first visit and ask before photographing interiors, displays or identifiable people.",
    },
    {
      id: "respect",
      type: "callout",
      tone: "neutral",
      title: "Read first, photograph second",
      body: "A plaque, calligraphy panel or conservation mark is useful only with its label and context. Do not touch timber, lean equipment against railings or block stairs for a symmetrical photograph. Obey no-photo and tripod rules even when another visitor ignores them. Avoid reproducing long modern translations, performance recordings or exhibition text; summarize the evidence and preserve the source.",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "Who gains from this comparison—and who can skip it?",
    },
    {
      id: "who",
      type: "paragraph",
      text: "This comparison suits readers, architecture students and travellers curious about reconstruction. Skip an extra city if the route does not support it, stairs and crowds would consume the visit, or a vanished 'original' is all you value. A slow reading of one tower also reveals where present city life meets a carefully arranged literary image. The best tower is the one whose evidence question remains interesting after its most famous view or exhibit disappears.",
    },
    {
      id: "help",
      type: "callout",
      tone: "decision",
      title: "Need the current operating details checked?",
      body: "Send your dates, party size and approximate budget if you want a human to verify which one fits without sacrificing a usable sightseeing day. Current access, ticketing, lift, display and photography information was treated as dynamic on 13 August 2026 and should be checked again for the travel date.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue reading buildings and landscapes",
      items: [
        {
          label: "Read city walls, gates and layers of rebuilding",
          href: "/guides/chinese-city-walls-gates-and-urban-order/",
          description: "Use the same distinction between surviving fabric, repair, reconstruction and archaeological evidence.",
        },
        {
          label: "Learn to read dougong and timber frames",
          href: "/guides/dougong-and-chinese-timber-frame-reading/",
          description: "Compare Yueyang's timber system with modern faux-timber expression more carefully.",
        },
        {
          label: "See how poetry shapes a Suzhou garden visit",
          href: "/guides/how-to-read-a-suzhou-garden/",
          description: "Continue separating literary ways of seeing from claims about material age.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official, design, archival and research sources",
      items: [
        {"label":"Yellow Crane Tower management and historical outline","url":"https://ylj.wuhan.gov.cn/zwgk/zwxxgkzl_12298/jggk_12304/xsdwszjzz_12308/202001/t20200110_726398.shtml","publisher":"Wuhan Gardens and Forestry Bureau","reviewedAt":"2026-08-13"},
        {"label":"Yellow Crane Tower project record","url":"https://csadi.com.cn/xmzs/dbzp/whhz_2094/201505/t20150508_52086.html","publisher":"Central-South Architectural Design Institute","reviewedAt":"2026-08-13"},
        {"label":"Yellow Crane Tower modern reconstruction study","url":"https://sjjb.cbpt.cnki.net/portal/journal/portal/client/paper/769f0bd2e3b912b72ad5fa0428cdc30a","publisher":"World Architecture / CNKI journal platform","reviewedAt":"2026-08-13"},
        {"label":"Literary reception of Cui Hao and Li Bai at Yellow Crane Tower","url":"https://xb.yrctu.edu.cn/article/doi/10.13681/j.cnki.cn41-1282/tv.2009.01.018","publisher":"Yellow River Conservancy Technical Institute journal","reviewedAt":"2026-08-13"},
        {"label":"Yueyang Tower official introduction","url":"https://www.yueyang.gov.cn/you/content_1630539.html","publisher":"Yueyang Municipal People's Government","reviewedAt":"2026-08-13"},
        {"label":"Yueyang Tower historical events and 1880 move","url":"https://www.yysqw.gov.cn/43332/43334/43511/44276/content_1267358.html","publisher":"Yueyang Local Chronicles Office","reviewedAt":"2026-08-13"},
        {"label":"Yueyang Tower conservation and retained components","url":"https://whhlyt.hunan.gov.cn/whhlyt/news/mtjj/202503/t20250326_33623203.html","publisher":"Hunan Department of Culture and Tourism","reviewedAt":"2026-08-13"},
        {"label":"1983–84 Yueyang Tower dismantling conservation","url":"https://daj.yueyang.gov.cn/6658/6667/content_370327.html","publisher":"Yueyang Municipal Archives","reviewedAt":"2026-08-13"},
        {"label":"Yueyang Tower rebuilding and movement record","url":"https://dfz.hunan.gov.cn/dfz/dqsj/202211/t20221122_29134400.html","publisher":"Hunan Provincial Local Chronicles Office","reviewedAt":"2026-08-13"},
        {"label":"Tengwang Pavilion historical and architectural outline","url":"https://www.nc.gov.cn/ncszf/rwfg/202505/caef4edf190a44099b002d0891a3d0f8.shtml","publisher":"Nanchang Municipal People's Government","reviewedAt":"2026-08-13"},
        {"label":"Tengwang Pavilion protection-list record","url":"https://www.nc.gov.cn/attachment/upload/file/20250806/1754472189182067198.pdf","publisher":"Nanchang Municipal People's Government","reviewedAt":"2026-08-13"},
        {"label":"Interview with Tengwang Pavilion chief designer Chen Xingwen","url":"https://www.tsinghua.org.cn/info/1951/19465.htm","publisher":"Tsinghua Alumni Association, republished designer interview","reviewedAt":"2026-08-13"}
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
