import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"윈강석굴 자유 관람은 세 가지 결정을 이어서 하면 됩니다. 실제로 가져갈 여권으로 실명 예약을 마치고, 당일 개방 동선을 따라 의미 있는 몇 개의 동굴군을 읽은 뒤, 다퉁으로 돌아갈 시간을 지키면서 박물관까지 볼지 정하세요. 동굴 번호는 체크리스트가 아닙니다. 보존을 위한 폐쇄, 일방통행과 혼잡 관리에 따라 당일 관람 범위가 달라질 수 있습니다."},
{id:"live-rule",type:"callout",title:"2026년 동적 규정—8월 12일 확인",body:"다퉁시 정부 자료에 따르면 윈강석굴은 2026년 4월 15일부터 사전 예약 기간을 7일에서 15일로 늘렸고, 무료 대상자도 예약해야 합니다. 영구 규정으로 단정하지 말고 게시 직전과 여행 전에 ‘윈강연구원’ 또는 ‘윈강문화관광’ 미니프로그램과 최신 공지를 다시 확인하세요.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"QR 코드가 아니라 본인·날짜·시간대를 예약합니다"},
{id:"booking",type:"list",items:["현재 공식 ‘윈강연구원’ 또는 ‘윈강문화관광’ 채널에서 여권과 정확히 맞는 증명서 종류를 선택하세요.","여권 이름과 번호를 원본대로 입력하고 중국 신분증 번호를 임의로 만들지 마세요. 같은 원본 여권을 가져가야 합니다.","일반 입장권, 우대 예약 또는 다른 상품인지 확인하세요. 무료 대상이어도 예약이 면제된다고 가정할 수 없습니다.","주문과 시간대를 오프라인으로 저장하세요. 2025년 공식 공지의 외국 여권 전용 창구 번호는 현장 운영 정보이므로 도착 후 확인해야 합니다.","현장 구매 가능성에 하루를 걸지 마세요. 공식 안내는 온라인 실명 예약을 기본으로 둡니다."]},
{id:"sequence-heading",type:"heading",level:2,text:"당일 동선을 지키며 동굴을 몇 개의 장으로 읽으세요"},
{id:"sequence",type:"table",caption:"윈강석굴을 해석의 장으로 묶기",columns:["장","볼 것","활용법"],rows:[["16–20굴을 포함한 초기 거대 석굴","탄야오 오굴의 큰 불상, 규모와 황실 조성 배경.","혼잡할 때는 모든 정면 사진보다 관찰 위치를 차분히 확보하세요."],["5–10굴 부근의 짝을 이룬 화려한 석굴","서로 다른 공간 구성, 쌍굴과 촘촘한 조각.","한두 곳을 천천히 보세요. 어두운 실내와 통제된 이동은 번호만 빠르게 훑기에 맞지 않습니다."],["후기 석굴과 작은 감실","후원자, 크기와 시각적 밀도의 변화.","마지막 몇 분이 아니라 남은 집중력을 배분하세요."],["유적 박물관","연대, 보존과 석굴을 연결하는 맥락.","해석이 중요하면 남기고 고정된 귀환 시간이 다가올 때만 줄이세요."]]},
{id:"no-universal-order",type:"callout",title:"모두에게 맞는 ‘비밀 순서’는 없습니다",body:"번호가 절벽을 따라 이어져도 정답은 그날 개방된 관람 동선입니다. 현장 표지, 임시 폐쇄와 직원 지시가 온라인 공략보다 우선합니다. 위 표는 해석의 틀이지 역주행하거나 통제선을 넘는 허가가 아닙니다.",tone:"neutral"},
{id:"timing",type:"paragraph",text:"첫 방문이라면 입장 후 몇 분만 계산하지 말고 다퉁 출발부터 반나절 규모로 잡는 편이 낫습니다. 왕복 교통, 보안 검색, 개방 석굴, 박물관과 귀환 여유를 합쳐야 합니다. 설명을 천천히 읽거나 오래 서 있기 어렵거나 사진 관찰을 원하는 여행자는 시간을 더 두세요."},
{id:"transport-heading",type:"heading",level:2,text:"다퉁 복귀도 관람 계획에 넣으세요"},
{id:"transport",type:"list",items:["넓은 유산 지역명이 아니라 정확한 윈강석굴 관람객 입구를 지도에 저장하세요.","버스 노선과 마지막으로 쓸 수 있는 출발편은 당일 다퉁 교통 정보로 확인하세요. 번호와 간격은 바뀔 수 있습니다.","택시나 호출차량에는 중국어 목적지 ‘云冈石窟’를 저장하고 허용된 승차 지점을 확인하세요.","관람 직후 고속철을 촘촘하게 연결하지 마세요. 시내 교통, 단지 내 보행과 차량 대기가 각각 변수입니다.","전용차라면 기사가 기다리는지, 정확한 만남 지점과 관람이 늦어질 때의 처리까지 합의하세요."]},
{id:"guide",type:"paragraph",text:"석굴의 시대 차이, 도상과 보존 제약을 이해하는 것이 핵심이면 해설의 가치가 큽니다. 통제된 길을 걷기 위해서만 가이드가 필요한 것은 아닙니다. 언어, 만남 장소, 해설만인지 다퉁 왕복 교통도 포함하는지 확인하세요."},
{id:"final-check",type:"list",items:["공식 예약 정보가 원본 여권과 일치합니다.","개방 시간과 입장 마감 시간을 다시 확인했습니다.","당일 통제선과 동굴 폐쇄를 따릅니다.","박물관 시간은 의도적인 선택입니다.","귀환 교통과 열차 사이에 실제 여유가 있습니다."]},
{id:"internal-links",type:"internal-links",title:"다퉁 일정을 연결하세요",items:[{label:"중국 고속철 첫 이용 안내",href:"/ko/guides/china-high-speed-train-first-time-guide/",description:"정확한 역명, 여권과 귀환 여유를 함께 관리하세요."},{label:"중국 여행에 가이드가 필요할까",href:"/ko/guides/do-you-need-a-tour-guide-in-china/",description:"해설을 미리 마련할 가치가 있는지 판단하세요."},{label:"부모님과 중국 여행",href:"/ko/guides/china-with-older-parents-route-guide/",description:"서 있는 시간, 보행 속도와 교통 확실성을 조정하세요."},{label:"중국 공휴일 여행",href:"/ko/guides/china-public-holidays-travel-guide/",description:"혼잡 통제가 하루에 미칠 영향을 확인하세요."}]},
{id:"consultation",type:"callout",title:"다퉁 도착·출발일에 윈강을 넣어야 하나요?",body:"Homeground의 실제 여행 상담원이 날짜별 예약 경로, 교통 여유와 동굴·박물관 우선순위를 함께 확인할 수 있습니다. 여권 종류, 다퉁 숙소나 역, 이동 필요와 고정 출발 시간을 알려 주세요.",tone:"neutral"},
{id:"sources",type:"sources",title:"확인한 공식·이미지 출처",items:[{label:"2026년 사전 예약 기간 변경",url:"https://www.dt.gov.cn/dtszf/bmdt/202604/87ae16347ecf462488743c37ee9c06f0.shtml",publisher:"다퉁시 인민정부",reviewedAt:"2026-08-12"},{label:"공식 실명 예약 안내",url:"https://www.dt.gov.cn/dtszf/zstpwhhdhd/202512/a253744527454c3fa5251853732e5d3d.shtml",publisher:"다퉁시 인민정부",reviewedAt:"2026-08-12"},{label:"외국인 관람객 서비스와 해설 배경",url:"https://www.dt.gov.cn/dtszf/bumdtq/202503/2679535d2a1c44e28b4ef9e6def213d1.shtml",publisher:"다퉁시 인민정부",reviewedAt:"2026-08-12"},{label:"윈강석굴 세계유산 등재 자료",url:"https://whc.unesco.org/en/list/1039/",publisher:"UNESCO 세계유산센터",reviewedAt:"2026-08-12"},{label:"대표 이미지: Felix Andrews, CC BY-SA 3.0; 자르기·변환",url:"https://commons.wikimedia.org/wiki/File:Yungang_caves.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
