import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"Treat Yungang as three decisions: secure a real-name ticket with the document you will carry, follow the live visitor flow through a few meaningful cave groups, then decide whether the site museum fits before your return to Datong. Cave numbers are not a checklist. Conservation closures, one-way controls and crowd management can change what is accessible on the day."},
{id:"live-rule",type:"callout",title:"Current rule, checked 12 August 2026",body:"Datong's official portal says Yungang extended advance booking from 7 to 15 days on 15 April 2026. It also says concession visitors must reserve. This is a 2026 fact, not a permanent promise: recheck the Yungang Research Academy or Yungang Culture and Tourism mini-program and the newest notice before publication and before travel.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"Book the person, date and time—not just a QR code"},
{id:"booking",type:"list",items:["Use the live official Yungang Research Academy or Yungang Culture and Tourism booking channel and select the document type that exactly matches your passport.","Enter passport names and numbers without improvising a Chinese ID number. Carry the same original passport to the gate.","Check whether the selected product is a standard admission, concession reservation or another named product; do not assume an exemption removes the reservation requirement.","Save the order and time slot offline. A 2025 official notice described an international-passport service lane, but lane numbers and hardware are operational details to verify on arrival.","Do not build the day around walk-up availability. Official information says online real-name reservation is the normal system."]},
{id:"sequence-heading",type:"heading",level:2,text:"Read the caves in chapters, while obeying the live route"},
{id:"sequence",type:"table",caption:"Yungang cave groups as interpretive chapters",columns:["Chapter","What to notice","How to use it"],rows:[["Early monumental group, including Caves 16–20","Large imperial images and the scale of the Tanyao Five Caves.","If crowds are heavy, choose viewpoints patiently rather than trying to photograph every façade."],["Paired and richly decorated caves around 5–10","Different spatial schemes, paired compositions and dense carving.","Slow down for one or two interiors; low light and controlled movement make rapid comparison unhelpful."],["Later groups and smaller niches","A shift in patronage, scale and visual density beyond the headline caves.","Use remaining attention here, not merely remaining minutes."],["Site museum","Context, conservation and a way to connect objects and chronology.","Keep it if interpretation matters; shorten it only to protect a fixed return."]]},
{id:"no-universal-order",type:"callout",title:"There is no responsible universal cave order",body:"The numbered grottoes extend along the cliff, but the correct sequence is the route open on your date. Signage, closures and staff directions override any online ‘secret order’. The table is an interpretation framework, not permission to reverse barriers or skip controlled sections.",tone:"neutral"},
{id:"timing",type:"paragraph",text:"For most first visits, protect roughly half a day from Datong rather than assigning only the time inside the ticket gate. The useful variable is not a promised number of hours: it is transport buffer plus security, the open cave route, museum time and the trip back. Travellers who read labels slowly, use mobility support or want photography pauses should allow more."},
{id:"transport-heading",type:"heading",level:2,text:"Make the Datong return part of the plan"},
{id:"transport",type:"list",items:["Pin the exact Yungang Grottoes visitor entrance, not a map label for the wider heritage area.","Check the current public-bus route and last useful departure with Datong's live transport information; route numbers and frequency can change.","For a taxi or ride-hail, keep the Chinese destination 云冈石窟 and arrange a pickup point where vehicles are permitted.","Do not schedule a tight high-speed-train departure after the visit. City traffic, gate walking and a pickup queue are separate risks.","If using a hired vehicle, agree whether the driver waits, the exact pickup location and what happens if the cave route takes longer."]},
{id:"guide",type:"paragraph",text:"A guide adds value when your main task is distinguishing the cave phases, iconography and conservation constraints. A guide is not necessary merely to walk the controlled route. If you book one, verify the language, meeting point and whether the service includes only interpretation or also Datong transport."},
{id:"final-check",type:"list",items:["Official reservation matches the original passport.","Current opening and last-entry times are rechecked.","The route follows live barriers and cave closures.","Museum time is a choice, not an accidental leftover.","Return transport leaves a real buffer before any train."]},
{id:"internal-links",type:"internal-links",title:"Build the wider Datong day",items:[{label:"China high-speed trains for first-time visitors",href:"/guides/china-high-speed-train-first-time-guide/",description:"Keep exact station names, passports and a return buffer together."},{label:"Do you need a tour guide in China?",href:"/guides/do-you-need-a-tour-guide-in-china/",description:"Decide whether interpretation is worth arranging."},{label:"China with older parents",href:"/guides/china-itinerary-with-older-parents/",description:"Adjust standing time, walking pace and transport certainty."},{label:"China public holidays",href:"/guides/china-public-holidays-travel-calendar/",description:"Check whether crowd controls may affect the day."}]},
{id:"consultation",type:"callout",title:"Need Yungang fitted around a Datong arrival or departure?",body:"A Homeground travel consultant can check the live booking path, transport buffer and a realistic cave-and-museum priority for your date. Share your passport type, Datong hotel or station, mobility needs and fixed departure.",tone:"neutral"},
{id:"sources",type:"sources",title:"Official and image sources reviewed",items:[{label:"2026 advance-booking window update",url:"https://www.dt.gov.cn/dtszf/bmdt/202604/87ae16347ecf462488743c37ee9c06f0.shtml",publisher:"Datong Municipal People's Government",reviewedAt:"2026-08-12"},{label:"Official reservation system explanation",url:"https://www.dt.gov.cn/dtszf/zstpwhhdhd/202512/a253744527454c3fa5251853732e5d3d.shtml",publisher:"Datong Municipal People's Government",reviewedAt:"2026-08-12"},{label:"International-visitor service and interpretation context",url:"https://www.dt.gov.cn/dtszf/bumdtq/202503/2679535d2a1c44e28b4ef9e6def213d1.shtml",publisher:"Datong Municipal People's Government",reviewedAt:"2026-08-12"},{label:"Yungang Grottoes World Heritage listing",url:"https://whc.unesco.org/en/list/1039/",publisher:"UNESCO World Heritage Centre",reviewedAt:"2026-08-12"},{label:"Hero: Yungang caves by Felix Andrews, CC BY-SA 3.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:Yungang_caves.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
