import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "In China, minsu, homestay, inn, guesthouse and boutique hotel are useful search labels but unreliable service specifications. A ‘homestay’ may be a professionally run group of rooms with no host living there; a ‘hotel’ may be tiny and personal. Choose the operating reality, not the English translation." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose a conventional hotel when a staffed arrival, predictable room, lift, breakfast or quick problem recovery matters. Choose a minsu when the exact setting or small-scale stay improves the trip and the operator can verify passport registration, vehicle-to-room access, bathroom, climate control and arrival support. Do not choose either category for ‘authenticity’ alone." },
  { id: "boundary", type: "paragraph", text: "This page explains lodging labels and guest fit. It does not decide whether a private residential rental is a safe operating model, rank properties or replace a city-area guide. First choose the right location, then use this test on the exact property." },
  { id: "labels", type: "table", caption: "What common labels tell you—and what they do not", columns: ["Label", "Reasonable inference", "Still unproven"], rows: [["Hotel / 酒店", "A hotel-style accommodation operation", "Room consistency, foreign-language service, lift or 24-hour reception"], ["Minsu / 民宿", "A small tourism accommodation identity or marketing label", "Living with a family, official grade, passport handling or rural setting"], ["Homestay", "An English platform translation", "Host presence, shared meals or cultural exchange"], ["Inn / guesthouse / 客栈", "Often smaller scale or a heritage/scenic setting", "Private bathroom, vehicle access, sound control or staffing"], ["Boutique hotel", "A design and positioning claim", "Independent quality standard or a particular service level"]] },
  { id: "standard", type: "heading", level: 2, text: "An official grade is specific, not implied" },
  { id: "standard-copy", type: "paragraph", text: "China's current national standard GB/T 41648-2022 is titled Basic Requirements and Classification for Homestay Inn and took effect on February 1, 2023. The Ministry of Culture and Tourism publishes named lists of nationally graded Class A and Class B tourism minsu. A listing is not officially graded merely because it calls itself ‘premium’, ‘five-star’, ‘boutique’ or ‘high-class’. If the grade matters, match the property's full Chinese name and location to an official published list." },
  { id: "fit", type: "table", caption: "Choose by the trip's non-negotiable need", columns: ["Traveller or trip", "Start with", "Accept a minsu only when"], rows: [["First arrival in China or late flight", "Hotel", "A named person confirms delayed arrival and passport process"], ["Older traveller, wheelchair, stroller or large cases", "Hotel with verified step-free route", "Curb-to-room access, lift and bathroom are confirmed"], ["Historic town, village or scenic gateway", "Either", "The setting saves daily travel and the luggage handoff works"], ["Light sleeper", "Property evidence, not label", "Assigned-room exposure and quiet policy are answered"], ["Family needing adjoining rooms", "Hotel", "The minsu confirms exact rooms, separation and child safety"], ["Traveller seeking host interaction", "Minsu after asking", "The host actually lives or works on site and states what interaction is offered"]] },
  { id: "room", type: "heading", level: 2, text: "Inspect the assigned room, not the courtyard gallery" },
  { id: "room-list", type: "list", items: ["Ask whether the photos show your room category, a sample room or only shared spaces.", "Confirm an external window, private bathroom, toilet type, hot-water arrangement and heating or cooling for your dates.", "Ask the floor, number of steps, lift route and distance from vehicle drop-off with luggage.", "Identify exposure to the street, reception, breakfast room, courtyard, stairs, lift machinery or neighbouring construction.", "For children, check open railings, low windows, ponds, loft stairs and whether the booked beds are real beds or floor mattresses.", "For limited mobility, ask for doorway, shower and lift facts; ‘accessible’ and ‘ground floor’ are not enough without the whole route."] },
  { id: "service", type: "heading", level: 2, text: "Small scale changes the recovery plan" },
  { id: "service-copy", type: "paragraph", text: "A well-run minsu can be attentive precisely because it is small. The same scale can mean one person handles reception, breakfast, transport and repairs. Ask what happens if that person is away, a key fails or the room has no hot water. Confirm staffed hours, after-hours contact, housekeeping frequency, luggage storage and whether an alternative room exists. A warm chat before booking is not a substitute for a failure process." },
  { id: "registration", type: "heading", level: 2, text: "Clarify hotel or non-hotel registration before paying" },
  { id: "registration-copy", type: "paragraph", text: "Under National Immigration Administration guidance, hotels register foreign guests. At accommodation outside hotels, the foreign guest or the person providing the stay must register within 24 hours. The NIA online route is currently a pilot in Hebei, Liaoning, Zhejiang, Hubei, Guangxi, Chongqing and Sichuan; elsewhere, confirm the current local route. First-time online registration in a pilot region commonly requires the accommodation provider's help with the address. The word minsu does not reveal which route applies; ask the operator directly." },
  { id: "arrival", type: "callout", title: "Late arrival needs a named human", tone: "warning", body: "Send the actual arrival window, not the scheduled landing time. Ask for the Chinese address, vehicle stop, final walking route, phone number and no-show rule in writing. If entry depends on a host who stops answering at 22:00, use a staffed hotel for the first night and move after breakfast." },
  { id: "scenic", type: "heading", level: 2, text: "A scenic location can save a day or complicate every transfer" },
  { id: "scenic-copy", type: "paragraph", text: "A minsu beside a historic lane, mountain gate or village can provide quieter mornings and remove a daily commute. It can also add pedestrian lanes, stone paving, shuttle schedules or a last kilometre that cars cannot enter. Ask where the main bag stays, who can legally carry it, what happens in rain and whether the final night should move back to a rail or airport base. Evaluate the location separately from the room charm." },
  { id: "verify", type: "table", caption: "Eight answers to obtain in writing", columns: ["Question", "A usable answer includes"], rows: [["What kind of operation is this?", "Hotel or non-hotel status and named operator"], ["How is my passport handled?", "The matching registration route, not a vague ‘no problem’"], ["Who checks us in?", "Name or role, staffed hours and late-arrival fallback"], ["Which room?", "Category, floor, window, bathroom and bed configuration"], ["How do we enter?", "Chinese address, vehicle stop, steps and lift"], ["How quiet is it?", "Room exposure and current construction, not ‘quiet area’"], ["What is serviced?", "Cleaning, linens, breakfast, luggage and repairs"], ["What if it fails?", "Backup contact, replacement room or refund/escalation path"]] },
  { id: "failure", type: "heading", level: 2, text: "Recover without losing the trip" },
  { id: "failure-copy", type: "paragraph", text: "If the entrance, room or registration differs materially from the written answer, document the issue before moving your belongings. Ask once for the promised room or a workable replacement and set a clear deadline. Keep children, older travellers and luggage in a staffed public place while resolving access. Move to a conventional hotel when no responsible person is available, the room is unsafe, the bathroom or bed configuration is unusable, or the operator asks you to hide the stay." },
  { id: "switch", type: "callout", title: "When to change the plan", tone: "decision", body: "Use a hotel for the arrival night, departure night or whole stay when the minsu cannot prove the exact room, legal check-in, luggage path and after-hours help. Use the minsu when those basics are clear and its setting genuinely changes the experience—not merely because its listing looks more local." },
  { id: "dynamic", type: "paragraph", text: "The national minsu standard, 2025 official grading announcement and accommodation-registration guidance were reviewed on August 13, 2026. Grades and individual operations can change; verify the full Chinese property name and current process. Homeground does not infer a grade from a booking-platform badge." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Commercial aparthotel or residential rental", href: "/guides/commercial-aparthotel-or-residential-rental-china/", description: "Separate operating models when the listing is an apartment." }, { label: "Beijing courtyard or modern hotel", href: "/guides/beijing-courtyard-hotel-or-modern-hotel/", description: "Apply the property test to a heritage stay." }, { label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Verify the complete final walk." }] },
  { id: "sources", type: "sources", title: "Official sources", items: [{ label: "GB/T 41648-2022 tourism minsu standard record", url: "https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=2E96A4B6C7B13B97FC67FD71736EAF01", publisher: "State Administration for Market Regulation", reviewedAt: "2026-08-13" }, { label: "2025 national Class A and Class B tourism minsu announcement", url: "https://zwgk.mct.gov.cn/zfxxgkml/scgl/202601/t20260126_964398.html", publisher: "Ministry of Culture and Tourism", reviewedAt: "2026-08-13" }, { label: "Online registration for foreigners staying outside hotels", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
