import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "For several full Canton Fair days, start with Pazhou: reducing the repeated hotel-to-hall leg usually matters more than having Guangzhou's broadest evening choice. Choose Tianhe when client offices, dinners or meetings there repeat after the fair. Choose Yuexiu only when its non-fair work or established central-city operations outweigh a longer venue trip. The correct answer comes from your exact hall and evening calendar, not a list of famous hotels.",
    },
    {
      id: "short-answer",
      type: "callout",
      title: "Short answer",
      tone: "decision",
      body: "Use Pazhou for three or more venue-heavy days, an early exhibitor call, heavy samples or a schedule that leaves little energy for commuting. Use Tianhe when the fair is only part of the workday and meetings at Zhujiang New Town, Tianhe Road or another specific Tianhe address recur. Use Yuexiu for a mixed business-and-city stay only after mapping the exact property to Pazhou or Xingangdong. A ‘Canton Fair hotel’, badge desk or advertised shuttle is not permanent proof: verify the current session, pickup pin, seat eligibility, return runs and Metro fallback in writing.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This page begins after you have decided to attend a particular Fair phase. It does not choose the phase, product section or supplier, explain invitation or badge applications, rank hotels, quote room prices or replace the broad Guangzhou guide. It chooses the sleeping base that best supports the halls and work already on your calendar.",
    },
    {
      id: "areas-heading",
      type: "heading",
      level: 2,
      text: "Define the three bases before comparing them",
    },
    {
      id: "area-comparison",
      type: "comparison",
      title: "Area labels are starting points, not door-to-door answers",
      columns: [
        {
          heading: "Pazhou",
          body: "The exhibition-island and nearby Haizhu stay belt around the Canton Fair Complex. It minimizes the recurring venue leg, but one property can still be inconvenient for your hall, evening meal or actual pedestrian route.",
        },
        {
          heading: "Tianhe",
          body: "A large modern business district. For this decision, the useful sub-areas are the exact business addresses around Zhujiang New Town, Tianhe Road or a Line 11/connected-station route—not the district name by itself.",
        },
        {
          heading: "Yuexiu",
          body: "A broad central district with older business, hotel and city-life clusters. It can suit repeat meetings or a mixed stay, but ‘central Guangzhou’ does not mean close to the Fair and different Yuexiu streets create different transfers.",
        },
      ],
    },
    {
      id: "venue-heading",
      type: "heading",
      level: 2,
      text: "Start with your hall, not the words ‘near the Canton Fair’",
    },
    {
      id: "venue-table",
      type: "table",
      caption: "Translate the current Fair guide into a hotel-location requirement",
      columns: ["Known input", "What it changes", "Evidence to save", "Do not assume"],
      rows: [
        ["Exact phase, area and hall", "Determines which side of the very large complex you approach repeatedly", "Current official buyer guide and hall number", "Every hall is equally close to one Pazhou address"],
        ["Badge already collected or still needed", "May add a first-day registration leg", "Current official collection point and hours", "A hotel used as a badge desk last session still offers it"],
        ["First appointment and entry role", "An exhibitor setup, buyer meeting and ordinary visitor day can begin differently", "Written appointment, gate or host instruction", "The closest Metro exit is the correct entrance that morning"],
        ["Evening meetings", "Can move the daily centre of gravity from the venue to Tianhe or Yuexiu", "Named address and finish time for each fixed meeting", "A district-level pin is enough to plan the return"],
        ["Samples and luggage", "Makes transfers, stairs and improvised pickup points more costly", "What may enter the venue, storage plan and exact hotel set-down", "The hotel or Fair will hold commercial items without agreement"],
      ],
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "Choose by the leg that repeats",
    },
    {
      id: "decision-matrix",
      type: "table",
      caption: "The strongest base removes the most expensive repeated friction",
      columns: ["Trip pattern", "Pazhou", "Tianhe", "Yuexiu", "Decision"],
      rows: [
        ["Three or more full Fair days", "Strong default: shortest recurring venue leg", "Accept only if evening work repeats there", "Usually too much repeated venue travel", "Start in Pazhou, then test the exact door-to-hall chain"],
        ["One Fair day in a broader Guangzhou trip", "May create an unnecessary hotel move", "Good if modern-CBD work or evenings dominate", "Good if old-centre plans or a trusted operating base dominate", "Keep the hotel beside the other days and make one verified Fair trip"],
        ["Early exhibitor call or fixed first appointment", "Best starting hypothesis", "Works only with a checked early transport chain", "Higher transfer risk", "Count backward from the gate, including walking and security"],
        ["Daily client dinners in Zhujiang New Town", "Easy venue day, repeated evening transfer", "Often the balanced choice", "Useful only if meetings sit there instead", "Put the hotel by the fixed evening address if fatigue after dinner matters most"],
        ["Older traveller, wheelchair, heavy cases or samples", "Can remove a long transfer but still needs route proof", "May offer a better specific property, at the cost of commuting", "Same trade-off; district cannot prove access", "Verify vehicle set-down, station entrance, lifts and assigned-room chain"],
        ["Arrive late before the first Fair morning", "Worth positioning here when reception and exact property are confirmed", "Choose when the first morning is not early or meetings begin in Tianhe", "Use only with a protected morning transfer", "Do not add a dark, unverified last mile merely to be ‘near’ the venue"],
      ],
    },
    {
      id: "verification-heading",
      type: "heading",
      level: 2,
      text: "Verify a property in this order",
    },
    {
      id: "verification-list",
      type: "list",
      ordered: true,
      items: [
        "Save the full Chinese property name, street address, entrance pin and staffed contact; do not rely on a translated neighbourhood badge.",
        "Save the current official phase, hall, venue area and instructed gate. Recheck when the organiser releases a newer guide.",
        "Map the public route from the actual hotel entrance to Pazhou or Xingangdong and then to the named venue side; inspect station entrance, lifts, crossings and the final outdoor walk.",
        "If the hotel advertises a Fair shuttle, request dates, outbound runs, return runs, pickup photo or pin, reservation rule, eligible guests, luggage rule and what happens when it is full or missed.",
        "Confirm reception coverage for the real arrival time, foreign-guest registration, the booked room configuration and any access requirement with the exact property.",
        "Place every fixed evening address on the same map. One repeated client transfer can outweigh a short morning commute saved elsewhere.",
        "Choose a Metro and a road fallback. Save Chinese venue, hotel and meeting addresses offline in case a driver or app cannot find the English name.",
        "Keep the booking terms and one acceptable alternative in another area; do not wait until a session-week disruption to discover every fallback is unsuitable.",
      ],
    },
    {
      id: "shuttle-boundary",
      type: "callout",
      title: "A shuttle label is not a transport contract",
      tone: "warning",
      body: "Official Guangzhou material shows that some properties offered complimentary Fair shuttles for a named session. That proves a dated service existed, not that your hotel, phase, day, seat or return is covered. A useful written answer names the property, session dates, pickup point, departure and return windows, reservation method and missed-bus alternative. If those details are absent, choose the base as if the shuttle did not exist.",
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Three schedules, three sensible answers",
    },
    {
      id: "scenario-pazhou-heading",
      type: "heading",
      level: 3,
      text: "Scenario 1: exhibitor, four venue-heavy days",
    },
    {
      id: "scenario-pazhou",
      type: "list",
      ordered: true,
      items: [
        "Choose a verified Pazhou property whose actual entrance works for the assigned hall side.",
        "Collect the badge before the first early call when the current official process allows; do not choose a hotel solely because an old list showed a desk there.",
        "Use the saved walking or Metro route as the primary chain and treat any hotel shuttle as an optional improvement.",
        "Keep client dinners near the venue or accept a deliberate evening trip; avoid moving hotels during the working phase unless it removes multiple fixed transfers.",
      ],
    },
    {
      id: "scenario-tianhe-heading",
      type: "heading",
      level: 3,
      text: "Scenario 2: buyer, two Fair days and three Tianhe evenings",
    },
    {
      id: "scenario-tianhe",
      type: "list",
      ordered: true,
      items: [
        "Base beside the repeated Tianhe meeting address and a simple verified transit route, not anywhere in the district.",
        "Travel light to the Fair and allow for entry, station and complex walking rather than budgeting only train time.",
        "Schedule the first venue appointment after a realistic arrival chain and keep the exact Area A/B/C/D destination in Chinese.",
        "Return to the same hotel after dinner, preserving one check-in and one luggage base across the whole business stay.",
      ],
    },
    {
      id: "scenario-yuexiu-heading",
      type: "heading",
      level: 3,
      text: "Scenario 3: one Fair day within a Yuexiu-led trip",
    },
    {
      id: "scenario-yuexiu",
      type: "list",
      ordered: true,
      items: [
        "Keep a suitable Yuexiu property when meetings, an established team base or city plans repeat there on the other days.",
        "Make one dedicated Fair day with the current official station and entrance guidance saved offline.",
        "Do not switch to Pazhou for a single night unless the first appointment is unusually early or the one move solves another fixed handoff.",
        "If the return becomes crowded or a shuttle fails, use the pre-checked Metro/road fallback rather than following an unverified pickup message.",
      ],
    },
    {
      id: "move-heading",
      type: "heading",
      level: 2,
      text: "Should you split the stay?",
    },
    {
      id: "move-table",
      type: "table",
      caption: "A hotel move must remove more friction than it creates",
      columns: ["Condition", "Keep one base", "Move once", "Hidden cost to count"],
      rows: [
        ["One Fair day", "Usually", "Only for a protected early start or linked airport/ferry handoff", "Packing, storage, two receptions and room readiness"],
        ["Several consecutive Fair days", "Use Pazhou if it already fits", "Move after the final Fair day when later work clearly shifts west/central", "Samples and work material must move securely"],
        ["Fair days separated by city work", "Use the strongest overall business base", "Rarely; only when each block has enough nights", "A ‘varied’ stay can become repeated checkout time"],
        ["Team with different schedules", "Prefer one property with independent fallback routes", "Only when teams genuinely operate in separate zones", "Communication, room allocation and item custody"],
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Failure recovery",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Recover the working day without turning a service claim into a crisis",
      columns: ["Failure", "Immediate action", "Evidence to preserve", "Next accommodation decision"],
      rows: [
        ["Hotel shuttle is full, changed or absent", "Use the verified Metro or official pickup fallback; contact the property through the booking record", "Advertised wording, written schedule, time and staff reply", "Keep the hotel if the independent route still works; otherwise change after the day's work"],
        ["You reach the wrong side of the complex", "Follow current organiser signs or staff direction; do not cross traffic barriers informally", "Current hall, area, gate and time", "Recalculate the correct hotel-to-hall chain before the next morning"],
        ["Badge desk is not operating at the hotel", "Use the current official registration location and process", "Official notice and the hotel's message", "Do not move hotels merely for a badge service that lasts one visit"],
        ["Late return has no practical Metro chain", "Use an authorised official pickup area and share the Chinese hotel address privately with the driver", "Receipt, route and property contact", "Move only if late returns repeat; one disruption does not prove the whole area wrong"],
        ["Property cannot complete check-in or provide the booked room", "Follow the foreign-guest check-in and refusal-recovery guide linked below, contact the platform through the booking record and preserve the reservation and property replies", "Reservation, property replies and front-desk outcome without posting passport data", "Choose the nearest verified fallback that protects the next fixed Fair appointment"],
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      title: "Recheck the session, not just the hotel",
      tone: "neutral",
      body: "Reviewed 1 September 2026: the latest retrievable 139th-session official transport material identified Pazhou and Xingangdong as the venue Metro approaches, while the Canton Fair had separately published a 2026 overseas-buyer attendance guide. Exact phase halls, entrance directions, service hours, badge locations, designated hotels, shuttle runs and traffic measures remain session-specific; recheck the latest guide for the session you will attend. This page deliberately gives no permanent timetable, journey time, room price, availability or property guarantee.",
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "Final booking check",
    },
    {
      id: "booking-checklist",
      type: "list",
      items: [
        "Current Fair phase, exact hall, area and first fixed appointment",
        "Full Chinese hotel name, address, entrance pin and staffed contact",
        "Door-to-station-to-hall route, including the correct exits and outdoor walk",
        "Every repeated evening meeting address and realistic return chain",
        "Written shuttle detail, with a no-shuttle Metro and road fallback",
        "Reception, foreign-guest registration, booked room and accessibility confirmation",
        "Sample/luggage custody and whether every transfer can handle it",
        "Booking terms and one verified fallback that protects the next fixed event",
      ],
    },
    {
      id: "consultation-boundary",
      type: "callout",
      title: "If you want a human area check",
      tone: "neutral",
      body: "In the initial planner, send only minimum non-sensitive context: travel dates, Canton Fair session or hall if known, the public areas you are comparing, traveller and room counts, and an optional broad budget. You may say that you want to discuss family or accessibility arrangements later, but do not submit children's exact ages; mobility, medical or accessibility details; passport or identity documents; booking or payment records; or identifiable information intended for a hotel, DMC or other supplier. Those details require a separate human follow-up, an appropriate purpose and consent; nothing is shared with a supplier without separate consent. This is not a live inventory service and does not guarantee price, availability, foreign-guest acceptance, room type, accessibility suitability, shuttle operation or current-session services.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue the stay plan",
      items: [
        {
          label: "Browse accommodation decisions",
          href: "/stay/",
          description: "Compare other China stay areas, property types and recovery workflows.",
        },
        {
          label: "Understand Guangzhou before choosing the base",
          href: "/destinations/guangzhou/",
          description: "Use the city Hub for broad geography, neighbourhoods and trip planning.",
        },
        {
          label: "Test whether a hotel is really near the Metro",
          href: "/guides/china-hotel-near-metro/",
          description: "Check the correct station entrance, walking surface, lift and luggage route.",
        },
        {
          label: "Prepare for foreign-guest check-in or refusal",
          href: "/guides/foreigners-china-hotel/",
          description: "Separate the accommodation-registration rule from a platform label and recover if the front desk cannot check you in.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official Fair, Guangzhou transport and image sources",
      items: [
        {
          label: "2026 Attendance Guide for Overseas Buyers",
          url: "https://www.cantonfair.org.cn/en-US/pages/598494791797825536",
          publisher: "China Import and Export Fair",
          reviewedAt: "2026-09-01",
        },
        {
          label: "139th Canton Fair Buyer Guide landing page",
          url: "https://www.cantonfair.org.cn/en-US/pages/682045446818172928",
          publisher: "China Import and Export Fair",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Your Canton Fair travel guide: how to reach the complex",
          url: "https://www.eguangzhou.gov.cn/gzspecialreports/139thCantonFair/content/post_42667.html",
          publisher: "Guangzhou municipal international portal",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Metro guide for the 139th Canton Fair",
          url: "https://www.gz.gov.cn/guangzhouinternational/Canton%20Fair/content/post_10769860.html",
          publisher: "Guangzhou Municipal People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Easy Canton Fair badge registration for overseas buyers",
          url: "https://www.cantonfair.org.cn/en-US/posts/1006458668226895872",
          publisher: "China Import and Export Fair",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Guangzhou hotels' dated services for the 139th Canton Fair",
          url: "https://www.eguangzhou.gov.cn/gzlatest/content/post_42773.html",
          publisher: "Guangzhou municipal international portal",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Hero: Canton Fair Complex aerial view by Tim Wu, CC BY-SA 4.0",
          url: "https://commons.wikimedia.org/wiki/File:Aerial_View,_Canton_Fair_Complex_20230701-A.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-09-01",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
