import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "在重庆，酒店在平面地图上很近，走到街上却可能很难。解放碑、观音桥和沙坪坝不是三个可以互换的中心区；它们会把夜间活动、抵达交接和反复跨城，放在这座陡峭立体城市的不同位置。" },
  { id: "answer", type: "callout", title: "先给结论", tone: "decision", body: "首次短停以渝中景点、两江夜晚和密集游客核心为主，选解放碑；多个夜晚或办事地点在两江以北，现代商业基地比出门就是老城更重要，选观音桥；磁器口等西侧日程重复、西侧铁路抵达真正控制行程，或愿意用更长的渝中通勤换本地生活基地，选沙坪坝。" },
  { id: "boundary", type: "paragraph", text: "本文只在三个基地中选择，不做酒店排名、不承诺某区最便宜，也不写成重庆交通大全。每一区里，具体楼栋、大堂所在高度和地铁出口都可能推翻区域结论。选区后，再使用全国“靠近地铁”标准核对酒店。" },
  { id: "matrix", type: "table", caption: "三个基地完成不同任务", columns: ["基地", "最适合", "主要代价", "物业级核验"], rows: [["解放碑", "首次渝中核心、中心夜游与两江景点", "人流、夜间噪音，部分地址车辆难进", "大堂高度、下客点、坡度与地铁入口"], ["观音桥", "反复在北侧用餐、商务或夜间活动", "去老城和南／西侧会增加过江", "大商业区的具体位置和末班返程"], ["沙坪坝", "磁器口、西侧日程、部分西侧抵达", "渝中夜游后返回更长", "准确车站／枢纽、换乘次数和晚到路线"]] },
  { id: "trip-fit", type: "table", caption: "让重复的那一天选择酒店", columns: ["行程模式", "先测试", "原因"], rows: [["两三晚首次到访，多个渝中地标", "解放碑", "减少每天回游客核心的移动"], ["多次在观音桥及北侧聚餐或开会", "观音桥", "夜晚结束后不再额外过江"], ["磁器口加高校／西侧日程超过一天", "沙坪坝", "不把一天西侧安排变成多次跨城"], ["只去一次磁器口，其余都在中心", "解放碑", "一次西行不应决定每晚住宿"], ["老人、婴儿车或大行李", "能证明下客到房间最容易的物业", "地形可能大于区域优势"]] },
  { id: "vertical", type: "heading", level: 2, text: "先看高度，再看距离" },
  { id: "vertical-copy", type: "paragraph", text: "重庆市官方访客资料用魁星楼说明渝中立体地形：看似地面的地方，可能比另一条街高出许多楼层。很短的直线可能藏着楼梯、陡路、天桥、楼内电梯或会随大楼关闭的通道。应询问酒店大堂开向哪条街、哪一层，不要只导航到建筑名称。" },
  { id: "last-mile", type: "list", items: ["分别索要车辆入口和步行大堂的地图点位，两者可能不同。", "确认从真正有用的地铁出口是否全程无台阶，深夜是否仍开放。", "路线若经过商场、写字楼或公共电梯，问清关门后怎么办。", "轮椅、婴儿车或大行李要核验下客、坡道、电梯、门和房间全链条。", "保存中文楼名、塔楼和大堂层；英文酒店名未必能把司机带到正确一侧。"] },
  { id: "jiefangbei", type: "heading", level: 2, text: "解放碑：中心城市就是行程时最合适" },
  { id: "jiefangbei-copy", type: "paragraph", text: "解放碑位于渝中核心，官方资料把它与魁星楼、十八梯等立体城市景观联系起来。多个中心景点和两江夜晚反复出现时，它通常最省事。风险是为了高层景观订到地面入口困难的楼，或客房正对深夜步行区。应确认车辆进入、大堂高度、早晚餐条件和安静侧房间。" },
  { id: "guanyinqiao", type: "heading", level: 2, text: "观音桥：为反复出现的北侧日程而住" },
  { id: "guanyinqiao-copy", type: "paragraph", text: "行程多次在观音桥结束，例如餐饮、现代商业、商务地址或亲友都在两江以北，观音桥才有价值。不能只因为全市地图上看着居中就选。列出最常重复的观光日、最晚夜归和离开日，比较完整路线。写着“观音桥”的酒店若在大商圈另一端，最后步行仍可能很长。" },
  { id: "shapingba", type: "heading", level: 2, text: "沙坪坝：西侧基地，不是万能低价替代" },
  { id: "shapingba-copy", type: "paragraph", text: "重庆官方资料确认磁器口古镇位于沙坪坝区。磁器口或其他西侧安排重复，或者准确抵达枢纽与酒店刚好匹配，住沙坪坝才合理；若短行程每晚都回渝中，则不够有力。必须按票面搜索完整车站名称，“重庆站”这种模糊说法不能用于选区。" },
  { id: "arrival", type: "heading", level: 2, text: "让准确抵达方式决定第一晚" },
  { id: "arrival-copy", type: "paragraph", text: "使用完整机场／铁路站名、计划到达、现实出站时间和行李，实时比较最终两家酒店的门到门路线，再向物业索要车辆入口。晚到时，有人值守且道路简单的酒店可能胜过理论最佳区域。不要把不确定晚间换乘、陡坡和自助入住压在同一晚。" },
  { id: "evening", type: "callout", title: "重复夜晚要计分，一次例外不要计分", tone: "decision", body: "三晚都在观音桥吃饭可以支持住观音桥，一晚不可以；两个渝中两江夜晚支持解放碑，一次磁器口上午不自动支持沙坪坝。把酒店给重复模式，例外当天再移动。" },
  { id: "verify", type: "table", caption: "发给最后两家酒店的问题", columns: ["问题", "为何在重庆重要"], rows: [["大堂开向哪条路、哪一层？", "一栋楼能在不同高度连接多条街"], ["带行李车辆停哪里？", "中心步行地址可能无法到门"], ["哪个地铁出口可用？", "最近点位可能要爬楼或大绕行"], ["路线是否穿过其他建筑？", "室内捷径会关门"], ["哪些房间避开街道／夜生活噪音？", "夜间基地可能牺牲睡眠"], ["所报时段前台能否处理护照？", "晚到需要实际值班能力"]] },
  { id: "failure", type: "table", caption: "基地失效时如何补救", columns: ["问题", "立即处理", "改变方案"], rows: [["找错大堂或楼层", "电话联系并用中文入口点位", "不要拖行李走立体路线，改道路接驳"], ["室内捷径关闭", "回到有人值守街面走公共路线", "换有独立入口的物业"], ["客房太吵", "要求已证明安静侧的房间", "只有重复夜晚不再成立才换区"], ["晚到变得更晚", "更新时段并再次确认值班", "无人接待则订简单抵达酒店"], ["跨城通勤占满时间", "按城市一侧重排日程", "白天搬一次可能优于天天往返"]] },
  { id: "registration", type: "paragraph", text: "旅馆为外国住客登记，非旅馆住宿则在24小时内走单独登记流程。请问具体物业如何运营、所报时段谁在值班；选择哪个区都不能跳过这一步。" },
  { id: "dynamic", type: "paragraph", text: "重庆市目的地资料与全国住宿登记政策复核于2026年8月12日。它们支持地理差异和立体地形提醒，不证明固定车程或酒店品质。请按旅行日期重查实时路线、地铁出口与物业进入。" },
  { id: "stay-quote-handoff", type: "callout", title: "需要人工核对候选住宿？", tone: "neutral", body: "如需人工比较候选物业，请提供旅行日期、人数、房间数量与床型组合、准确的抵离航站楼或火车站、住宿预算及币种、行李情况、儿童年龄，以及老人或无障碍需求，并说明对区域、房型或备用酒店的调整空间。如果物业已回复车辆入口和大堂所在楼层，也请一并提供。规划师可以按这些条件核对物业当前的书面回复，并协助组织供应商中立的询价。每家物业、每种房型、外籍住客护照登记流程和完整无障碍通路仍须人工复核；这不保证实时价格、房态、接待资格、房型或无障碍适用性。" },
  { id: "links", type: "internal-links", title: "继续规划", items: [{ label: "如何判断靠近地铁", href: "/zh/guides/china-hotel-near-metro/", description: "检验地铁出口和立体最后步行。" }, { label: "核验真正可用的无障碍酒店房", href: "/zh/guides/china-accessible-hotel-room-verification/", description: "核对立体城市中从路缘到房间的完整通路，而不只看电梯图标。" }, { label: "外国旅客能住中国任何酒店吗？", href: "/zh/guides/foreigners-china-hotel/", description: "核验具体物业在实际抵达时段的护照登记。" }, { label: "国际航班前中国最后一晚", href: "/zh/guides/china-last-night-before-international-flight/", description: "保护重庆行程之后实际机场的出境安排。" }, { label: "民宿、homestay还是酒店", href: "/zh/guides/minsu-homestay-or-hotel-china/", description: "核对小型物业真实运营。" }, { label: "一个基地还是多个住宿点", href: "/zh/guides/china-hub-and-spoke-or-multi-base-route/", description: "判断反复跨城是否值得换住宿区。" }, { label: "理解重庆的立体城市", href: "/zh/guides/chongqing-upper-lower-city-orientation/", description: "把重庆当作三维城市来读：短距离步行前先核对道路高度、车站出口和建筑入口。" }] },
  { id: "sources", type: "sources", title: "官方来源与图片署名", items: [{ label: "渝中立体城市与解放碑官方介绍", url: "https://english.cq.gov.cn/latestnews/Editor/202606/t20260608_15735957.html", publisher: "重庆市人民政府", reviewedAt: "2026-08-12" }, { label: "确认磁器口位于沙坪坝的官方资料", url: "https://english.cq.gov.cn/latestnews/activities/202606/t20260608_15735764.html", publisher: "重庆市人民政府", reviewedAt: "2026-08-12" }, { label: "旅馆以外住宿登记网上办理政策解读", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "国家移民管理局", reviewedAt: "2026-08-12" }, { label: "首图：Baycrest拍摄解放碑夜景，CC BY-SA 2.5，已裁切转换", url: "https://commons.wikimedia.org/wiki/File:Jiefangbei_night.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
