import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "In Chongqing, a hotel can be close on a flat map and difficult in the street. Jiefangbei, Guanyinqiao and Shapingba are not three interchangeable central districts: they place your evenings, arrival handoff and repeated cross-city journeys on different parts of a steep, multi-level city." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose Jiefangbei for a short first visit centred on Yuzhong sights, river evenings and a dense visitor core. Choose Guanyinqiao when several nights or appointments are north of the rivers and a modern commercial base matters more than walking out into the historic core. Choose Shapingba when west-side days such as Ciqikou repeat, a west-side rail arrival controls the trip or a quieter local base justifies longer journeys to Yuzhong." },
  { id: "boundary", type: "paragraph", text: "This page chooses among three bases; it does not rank hotels, promise one district is cheapest or teach the full Chongqing transport system. Within every district, the exact tower, lobby level and station entrance can reverse the recommendation. Apply the nationwide ‘near the metro’ test after choosing the district." },
  { id: "matrix", type: "table", caption: "Three bases with different jobs", columns: ["Base", "Best fit", "Main cost", "Property-level check"], rows: [["Jiefangbei", "First-trip Yuzhong core, central evening walks, river-facing sightseeing cluster", "Crowds, nightlife noise and difficult vehicle approaches at some addresses", "Lobby level, road drop-off, slope and station entrance"], ["Guanyinqiao", "Repeated north-side dining, business or evenings", "More crossings for old-city and south/west sightseeing", "Which part of the large commercial area and last return"], ["Shapingba", "Ciqikou, west-side plans, some west-side arrivals", "Longer returns from Yuzhong river nights", "Exact station/hub, transfer count and late arrival route"]] },
  { id: "trip-fit", type: "table", caption: "Let the repeated day choose the hotel", columns: ["Your itinerary pattern", "First base to test", "Why"], rows: [["Two or three nights, first visit, several Yuzhong landmarks", "Jiefangbei", "It reduces repeated returns to the visitor core"], ["Several dinners or meetings around Guanyinqiao and north-side Chongqing", "Guanyinqiao", "The night ends near the room instead of after another river crossing"], ["Ciqikou plus university/west-side plans on more than one day", "Shapingba", "It prevents one western day from becoming repeated cross-city commuting"], ["One Ciqikou visit but all other plans central", "Jiefangbei", "One west-side trip should not choose every night"], ["Older parents, stroller or large bags", "Whichever property proves the easiest curb-to-room route", "Terrain can outweigh district advantage"]] },
  { id: "vertical", type: "heading", level: 2, text: "Read height before distance" },
  { id: "vertical-copy", type: "paragraph", text: "Chongqing's municipal visitor material uses Kuixing Tower—where what looks like street level can be many floors above another street—to illustrate Yuzhong's vertical form. A short straight line can hide stairs, steep roads, an overpass, a lift inside a building or a route that closes with the building. Ask the hotel which street and floor the lobby opens onto; do not navigate only to the building name." },
  { id: "last-mile", type: "list", items: ["Request a map pin for the vehicle entrance and a separate pin for the pedestrian lobby if they differ.", "Ask whether the route from the useful station exit is step-free and remains open late.", "Check if a mall, office tower or public lift is part of the route and what happens after it closes.", "For wheelchairs, strollers or heavy luggage, verify curb, ramp, lift, doorway and room—not just one elevator.", "Save the Chinese building, tower and lobby level; the English hotel name may not guide a driver to the right side."] },
  { id: "jiefangbei", type: "heading", level: 2, text: "Jiefangbei: best when the central city is the itinerary" },
  { id: "jiefangbei-copy", type: "paragraph", text: "Jiefangbei anchors central Yuzhong, and municipal material connects it with the layered Kuixing Tower and Shibati landscape. It is the easiest of the three choices when several central sights and river evenings repeat. The risk is choosing a dramatic-view tower with an awkward ground entrance or a room facing a late-night pedestrian area. Confirm road access, lobby elevation, breakfast/food availability and the quiet side of the building." },
  { id: "guanyinqiao", type: "heading", level: 2, text: "Guanyinqiao: choose it for north-side repetition" },
  { id: "guanyinqiao-copy", type: "paragraph", text: "Guanyinqiao works when the trip repeatedly ends there: restaurants, modern shopping, a business address or friends north of the rivers. It should not win merely because it looks central on a citywide map. List the three journeys you will repeat—main sightseeing day, latest evening and departure—and compare complete routes. A hotel on the wrong edge of a broad commercial label may still add a long final walk." },
  { id: "shapingba", type: "heading", level: 2, text: "Shapingba: a west-side base, not a universal budget alternative" },
  { id: "shapingba-copy", type: "paragraph", text: "Official Chongqing material places Ciqikou Ancient Town in Shapingba. Staying in the district can make sense when Ciqikou or other west-side commitments repeat, or when the exact arrival hub and hotel align. It is less convincing for a short trip whose every evening ends in Yuzhong. Search the full railway-station name on the ticket; ‘Chongqing station’ is not enough to choose a district." },
  { id: "arrival", type: "heading", level: 2, text: "Match the first night to the exact arrival" },
  { id: "arrival-copy", type: "paragraph", text: "Use the complete airport or railway terminal name, scheduled arrival, realistic exit time and luggage. Compare door-to-door routes to the final two hotels in a live map, then ask each property for the actual vehicle entrance. After a late arrival, a staffed hotel with a simple road approach can beat the theoretically best district. Do not combine an uncertain late transfer, difficult slope and self-check-in." },
  { id: "evening", type: "callout", title: "Let repeated evenings count; ignore one exceptional night", tone: "decision", body: "Three dinners in Guanyinqiao can justify staying there. One dinner does not. Two river evenings in Yuzhong favour Jiefangbei; one Ciqikou morning does not automatically favour Shapingba. Give the hotel to the pattern that repeats, then travel for the exception." },
  { id: "verify", type: "table", caption: "Questions to send the final two properties", columns: ["Question", "Why it matters in Chongqing"], rows: [["Which road and level is the lobby on?", "One building can meet several streets at different heights"], ["Where can a car stop with luggage?", "A central pedestrian address may not be curb-accessible"], ["Which station exit is usable?", "The nearest pin may require stairs or a large vertical detour"], ["Is the route through another building?", "Indoor shortcuts can close"], ["Which rooms avoid street or nightlife noise?", "A central evening base can compromise sleep"], ["Can reception handle our passports at the stated hour?", "Late arrival requires actual staff capability"]] },
  { id: "failure", type: "table", caption: "Recovery when the base fails", columns: ["Problem", "Immediate response", "Plan change"], rows: [["Wrong lobby or level", "Call the property and use the Chinese entrance pin", "Use road transfer rather than dragging luggage through vertical routes"], ["Indoor shortcut closed", "Return to a staffed street and use the public route", "Choose a property with an independent entrance"], ["Room is too noisy", "Request a proven quiet-side room", "Move district only if the repeated evening no longer justifies it"], ["Late arrival becomes much later", "Send the revised time and confirm staff again", "Book a simple arrival hotel if no one can admit you"], ["Cross-city commute dominates", "Regroup days by side of the city", "One daytime hotel move may be better than repeating it"]] },
  { id: "registration", type: "paragraph", text: "A hotel registers foreign guests; a non-hotel stay follows the separate registration route within 24 hours. Ask the exact property how it operates and who is on duty. District choice does not remove this check." },
  { id: "dynamic", type: "paragraph", text: "Chongqing municipal destination material and national accommodation-registration guidance were reviewed on August 12, 2026. They support the geographic distinctions and vertical-terrain warning, not any fixed journey time or hotel quality. Recheck live routes, station exits and property access for the travel date." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Test the station exit and vertical final walk." }, { label: "Minsu, homestay or hotel", href: "/guides/minsu-homestay-or-hotel-china/", description: "Check a smaller property's operating reality." }, { label: "One hub or multiple travel bases?", href: "/guides/china-hub-and-spoke-or-multi-base-route/", description: "Decide when repeated cross-city travel justifies changing base." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Official Yuzhong vertical-city and Jiefangbei feature", url: "https://english.cq.gov.cn/latestnews/Editor/202606/t20260608_15735957.html", publisher: "Chongqing Municipal Government", reviewedAt: "2026-08-12" }, { label: "Official reference placing Ciqikou in Shapingba", url: "https://english.cq.gov.cn/latestnews/activities/202606/t20260608_15735764.html", publisher: "Chongqing Municipal Government", reviewedAt: "2026-08-12" }, { label: "Online registration for foreigners staying outside hotels", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-12" }, { label: "Hero: Jiefangbei at night by Baycrest, CC BY-SA 2.5; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:Jiefangbei_night.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
