import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "외국인도 상하이 디즈니랜드를 자유여행으로 방문할 수 있지만 하루에는 두 시스템이 있습니다. 입장 전에는 신원, 입장 뒤에는 우선순위입니다. 여권 기록, 주문과 공식 채널이 일치해야 하고, 안에서는 공식 앱이 실시간 운영층이 됩니다. 정적인 글은 방문일의 놀이기구, 대기시간, 공연이나 프리미어 액세스를 보장할 수 없습니다." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "리조트가 현재 공식 또는 공인 파트너로 밝힌 채널에서만 구매하고 여권 정보를 정확히 입력해 같은 원본 여권을 지참하세요. 공식 앱을 미리 설치합니다. 서로 다른 실패 유형의 필수 경험 세 가지를 고르고 각 근처에 실내 또는 낮은 부담의 대안을 둡니다. 입장 뒤에는 오래된 인터넷 일정이 아니라 실시간 앱으로 순서를 정하세요." },
  { id: "before-heading", type: "heading", level: 2, text: "결제 전: 맞는 사람과 날짜를 연결하세요" },
  { id: "identity", type: "table", caption: "신원 연결", columns: ["기록", "확인", "이유"], rows: [["공식/공인 주문", "파크, 날짜, 상품과 인원", "결제 알림만으로 전원 등록을 증명할 수 없음"], ["여권", "이름, 번호와 유효기간이 주문과 일치", "실명 규정은 지정된 원본 신분증을 요구"], ["공식 앱 계정", "로그인과 현재 연결/도움 경로", "상품마다 연결 흐름이 달라질 수 있음"], ["그룹 역할", "누구 계정·주문·원본이 입장을 통제하는지", "한 휴대전화 고장이 전원을 막지 않게 함"]] },
  { id: "channels", type: "callout", title: "검색 광고가 ‘공식’을 정하게 두지 마세요", tone: "warning", body: "리조트는 웹사이트, 앱, 위챗, 예약센터와 지정 공식 스토어·여행 파트너를 안내합니다. 리조트 자체 채널 페이지에서 시작하세요. 디즈니 이미지를 쓰거나 상품명에 ‘공식’이 있다고 공인된 것은 아닙니다." },
  { id: "passport", type: "list", ordered: true, items: ["별명이나 번역명이 아닌 여권 신원면 그대로 입력합니다.", "결제 전 모든 방문자와 날짜를 확인합니다.", "여권 이미지 대신 주문번호와 공식 고객센터 경로를 저장합니다.", "같은 원본 여권을 지참합니다. 사진이나 사본을 확실한 대체물로 보지 마세요.", "주문이 보이지 않으면 파크로 가기 전에 구매 채널이나 공식 서비스로 해결합니다."] },
  { id: "app-heading", type: "heading", level: 2, text: "앱은 준비하되 버튼 하나에 하루를 걸지 마세요" },
  { id: "app", type: "paragraph", text: "호텔 Wi-Fi에서 상하이 디즈니 리조트 공식 앱을 설치·업데이트하고 중국 교통 규정을 충족하는 보조배터리를 준비하세요. 운영시간, 어트랙션 상태, 엔터테인먼트, 지도와 게스트 서비스 위치를 익힙니다. 연결, 파티, 유료 접근 흐름은 상품과 판매 채널마다 달라질 수 있으니 현행 안내를 따르세요." },
  { id: "priorities-heading", type: "heading", level: 2, text: "놀이기구 순위 대신 우선순위 삼각형" },
  { id: "priorities", type: "comparison", title: "서로 다른 기억 세 가지", columns: [{ heading: "대표 어트랙션 하나", body: "다른 계획이 바뀌어도 방문 가치를 만드는 것을 고르고 현행 키·건강·접근 조건을 확인합니다." }, { heading: "분위기 또는 캐릭터 목표", body: "랜드, 퍼레이드, 캐릭터나 성 순간은 놀이기구 중단에도 가치를 남깁니다. 시간과 제공은 실시간입니다." }, { heading: "전원이 함께할 경험", body: "그룹 모두에게 실제로 맞는 것을 고릅니다. 어린이, 노약자, 멀미가 있는 사람이 빨리 회복한다고 가정하지 마세요." }] },
  { id: "morning", type: "paragraph", text: "입장 뒤 실시간 지도를 먼저 보세요. 대표 어트랙션이 운영 중이고 동선이 합리적이면 시작하되, 지연되면 근처 대안으로 갑니다. 오전에는 한 구역을 마무리하고 대기 숫자가 잠깐 내려갔다고 파크를 가로지르지 마세요." },
  { id: "midday", type: "paragraph", text: "점심에는 제대로 먹고 그룹 상태를 다시 봅니다. 더위, 비, 젖은 옷, 저혈당과 배터리가 이론상의 효율을 무너뜨립니다. 실내나 앉는 구간을 하나 지키고 남은 필수 항목은 늦은 오후에 봅니다. 야간 공연만이 유일한 성공 결말이면 안 됩니다." },
  { id: "day-shapes", type: "table", caption: "실행 가능한 하루 스타일", columns: ["스타일", "지킬 것", "받아들일 것"], rows: [["첫 방문 하이라이트", "대표 어트랙션, 성/랜드 분위기, 공연 하나", "모든 인기 기구는 불가능"], ["가족 속도", "키에 맞는 기구, 식사, 화장실, 그늘과 휴식", "성인이 짧게 나뉠 수 있음"], ["스릴 우선", "맞는 고수요 기구 2~3개와 가까운 동선", "캐릭터·쇼핑·퍼레이드 위치가 줄어듦"]] },
  { id: "failure-heading", type: "heading", level: 2, text: "완벽한 순서보다 회복이 중요합니다" },
  { id: "failure", type: "table", caption: "계획이 깨질 때", columns: ["문제", "대응"], rows: [["여권/주문 불일치", "다른 신원을 쓰지 말고 판매 채널이나 입구 게스트 서비스 이용"], ["앱에서 주문이 안 보임", "주문과 여권을 보관하고 상품별 공식 연결 도움 이용"], ["필수 기구 중단", "근처 대안 후 나중에 확인; 재개 보장은 없음"], ["비·더위", "준비한 실내/휴식 구간으로 이동하고 수분과 안전 우선"], ["휴대전화 고장", "두 번째 기기, 주문 정보와 게스트 서비스를 쓰고 낯선 사람에게 계정 공유 금지"]] },
  { id: "paid-access", type: "callout", title: "프리미어 액세스는 선택적·동적 상품입니다", tone: "neutral", body: "재고, 포함 기구, 가격과 조건은 바뀝니다. 현행 약관을 읽고 리조트가 지정한 직접 채널에서만 구매하세요. 유료 상품은 운영, 이용 제한이나 여권 요건을 없애지 않습니다." },
  { id: "transport-boundary", type: "callout", title: "푸둥공항–디즈니 이동은 별도 글의 책임", tone: "neutral", body: "이 글은 파크 하루만 다룹니다. 공항 이동, 막차 보장이나 같은 날 항공 연결을 반복하지 않습니다. 전용 공항 가이드와 호텔 대안을 쓰세요." },
  { id: "final-check", type: "list", items: ["전원의 여권 정보와 날짜가 확인 주문에 맞습니다.", "원본 여권을 그룹이 직접 소지합니다.", "공식 앱이 업데이트·로그인되어 있고 가능하면 충전된 두 번째 기기가 있습니다.", "당일 달력, 운영시간, 제한과 날씨를 다시 확인했습니다.", "세 우선순위, 근처 대안, 식사·휴식과 귀환 계획이 있습니다."] },
  { id: "links", type: "internal-links", title: "상하이 계획 이어가기", items: [{ label: "푸둥공항–상하이 디즈니랜드", href: "/ko/guides/pudong-airport-to-shanghai-disneyland/", description: "정확한 환승 종점과 지연 대안을 고릅니다." }, { label: "상하이 도시 허브", href: "/ko/destinations/shanghai/", description: "숙박일과 파크·도시 관계를 정합니다." }, { label: "푸둥 또는 훙차오 공항", href: "/ko/guides/shanghai-pudong-or-hongqiao-airport/", description: "디즈니가 아닌 전체 여행 기준으로 고릅니다." }, { label: "중국 보조배터리 규정", href: "/ko/guides/china-power-bank-rules-flights-trains/", description: "교통 규정에 맞게 앱 배터리를 지킵니다." }, { label: "중국 공휴일", href: "/ko/guides/china-public-holidays-travel-calendar/", description: "날짜표 구매 전 혼잡일을 봅니다." }, { label: "상하이 숙소 지역", href: "/ko/guides/shanghai-where-to-stay-first-trip/", description: "파크와 도시 일정을 균형 있게 둡니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "공식 티켓 규정·공인 채널·원본 신분증", url: "https://www.shanghaidisneyresort.com/en/ticket/", publisher: "Shanghai Disney Resort", reviewedAt: "2026-08-22" }, { label: "상하이 정부의 실명 티켓 안내", url: "https://english.shanghai.gov.cn/en-Latest-WhatsNew/20241121/16891d39bb1e4c0aa66e65254027adc3.html", publisher: "상하이시 인민정부", reviewedAt: "2026-08-22" }, { label: "대표 사진: Fayhoo의 성, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Enchanted_Storybook_Castle_of_Shanghai_Disneyland.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
