import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {schemaVersion:"1.0.0",blocks:[
  {id:"lead",type:"lead",text:"Wenchang is not one space attraction behind one gate. The coastal city contains a national launch site, the separate Hainan International Commercial Aerospace Launch Center, a wider aerospace-city development programme, industrial compounds and projects at different stages. Public-facing arrangements are conditional and can change by mission, venue and date. A useful plan starts by naming the exact entity, then separates stable context from event-specific access."},
  {id:"answer",type:"callout",title:"The short answer",body:"Do not plan around a standing public viewing point or routine launch-site visit. At this review date, Homeground could not independently verify an evergreen workflow for foreign visitors or a named viewing point that can be recommended for every launch. Treat any venue visit or launch-day viewing arrangement as conditional on a current official notice and direct operator confirmation. Never arrive at either launch-site gate expecting entry, and never present a planned museum, park or industrial project as open.",tone:"decision"},
  {id:"ledger-heading",type:"heading",level:2,text:"Five labels that must not be collapsed"},
  {id:"ledger",type:"table",caption:"Wenchang's space entities and their visitor meaning",columns:["Entity","Verified role","Visitor interpretation","Do not assume"],rows:[
    ["Wenchang Spacecraft Launch Site","The national launch system handles major state spaceflight missions; the official crewed-space programme describes its launch and support role.","Operational infrastructure seen only from approved public contexts unless a current official tour says otherwise.","‘Open launch site’ means walk-in pad access."],
    ["Hainan International Commercial Aerospace Launch Center (海南商业航天发射场)","A separate commercial launch facility near, but not identical to, the national site; it completed its first launch in 2024.","An operating facility, not a routine attraction.","Its calendar, pads or industrial buildings are open to casual visitors."],
    ["Wenchang International Aerospace City","A development and industry programme covering launch, manufacturing, data and related zones.","A framework for understanding the local economy and geography.","The word ‘city’ identifies a single visitor campus."],
    ["Event-specific public information and visitor arrangements","Authorities or operators may publish a viewing or science-visit arrangement for a particular event or venue.","Conditional only: this review found no evergreen foreign-visitor workflow or named viewing point to recommend.","An old event notice, beach, roof or roadside remains an approved public point."],
    ["Planned projects","Official plans discuss new museums, parks, factories, visitor facilities and later phases.","Future context only until an operator announces opening and booking.","A construction rendering or policy target is an operating service."]
  ]},
  {id:"geography-heading",type:"heading",level:2,text:"Read the geography before choosing a base"},
  {id:"geography",type:"paragraph",text:"Wenchang city, Longlou town, the coast and the two launch compounds are related but not interchangeable map pins. Wenchang has rail access and broader city services; Longlou is closer to the launch coast and may face event-day pressure. Industrial and operational zones can lie only a few kilometres apart while remaining legally and functionally separate. Save the exact Chinese name and entrance only after a public venue or event arrangement is confirmed by its operator. A map label, old viewing guide or photo location does not grant access."},
  {id:"base-heading",type:"heading",level:2,text:"Choose the base by the task, not the brand"},
  {id:"base",type:"comparison",title:"Two sensible bases",columns:[
    {heading:"Wenchang urban area",items:["Best for: Rail arrival, ordinary city services and a trip not dependent on launch timing.","Trade-off: Requires a separately planned road transfer to Longlou/coast.","If plans change: Easier to continue with city, food and coastal alternatives."]},
    {heading:"Longlou and the launch coast",items:["Best for: Only an event-specific plan confirmed through a current official notice or a separately verified public venue.","Trade-off: Demand, traffic controls and service patterns can change sharply around launches.","If plans change: Closer launch context, but fewer reasons to stay if the conditional arrangement disappears."]}
  ]},
  {id:"launch-heading",type:"heading",level:2,text:"A launch day is an event operation, not a normal sightseeing day"},
  {id:"launch",type:"list",items:["Use only a mission announcement from the responsible space authority or launch operator; reposted countdowns are leads, not confirmation.","Expect timing, weather, technical readiness and safety controls to change. Never build a non-refundable onward connection around an exact ignition time.","Check whether a current local public-safety or transport notice names a public viewing arrangement. If it does not, do not invent one from old guides or social posts.","If an arrangement is published, follow its rules on identity, equipment, parking, drones, temporary structures and prohibited areas.","Keep a fixed meeting point because mobile networks and road movement may become difficult when crowds concentrate.","After a postponement, wait for an official update; do not move closer to a pad, closed beach or restricted road seeking a better view."]},
  {id:"ordinary-heading",type:"heading",level:2,text:"What an ordinary, no-launch day can still explain"},
  {id:"ordinary",type:"table",caption:"Build value that does not depend on ignition",columns:["Question","Public evidence to seek","Useful takeaway"],rows:[
    ["Why Wenchang?","Coastal geography, latitude explanations and official science interpretation.","Why location, sea transport and eastward flight paths matter."],
    ["Why a second launch site?","Current official explanations of commercial demand and separate operations.","The commercial site is additional infrastructure, not a renamed national site."],
    ["What is an aerospace city?","Official planning material and urban change visible from ordinary public areas.","Manufacturing, data and services extend beyond the launch pad."],
    ["What can visitors enter?","Only a current operator notice naming the venue, address, opening status, identity rule and booking method.","No evergreen foreign-visitor workflow was independently verified for this guide; public communication and operational access remain separate."]
  ]},
  {id:"scenarios-heading",type:"heading",level:2,text:"Three travellers, three decisions"},
  {id:"scenarios",type:"table",caption:"Do not force the same Wenchang plan on everyone",columns:["Traveller","Core plan","Stop rule"],rows:[
    ["Space enthusiast with flexible dates","Keep dates flexible, but add viewing only if a current official notice names a lawful public arrangement.","Leave if the mission window or public arrangement falls outside the trip; do not chase restricted access."],
    ["Family visiting Hainan without a scheduled launch","Use town and coastal geography as context; add a science venue only after direct operator confirmation.","Skip any venue whose current opening, age rule or foreign-passport handling cannot be confirmed."],
    ["Industry-curious traveller","Study the entity ledger and public exhibitions; arrange a professional visit only through an authorized host.","No cold arrival at industrial parks, factories or launch-site gates." ]
  ]},
  {id:"route-heading",type:"heading",level:2,text:"A one-day visit that does not depend on a launch"},
  {id:"route",type:"list",items:["Before travel: identify whether this is an ordinary city visit, an event-specific public arrangement or an authorized professional visit.","Save the exact Chinese names of the national site and Hainan International Commercial Aerospace Launch Center; add a public venue or viewing pin only after current confirmation.","Morning: use a public science venue only if its operator confirms the address, opening and foreign-visitor process for that date.","Midday: pause in Wenchang or Longlou rather than lingering outside an operational perimeter.","Afternoon: read the coastal geography from an ordinary lawful public place without presenting it as an official viewing point.","Evening: follow a temporary viewing and traffic scheme only when a current official notice explicitly applies. Otherwise leave without waiting for rumours.","Afterward: label photos accurately—coast, town, or distant launch infrastructure—rather than ‘inside the launch base’." ]},
  {id:"boundaries-heading",type:"heading",level:2,text:"Operational and community boundaries"},
  {id:"boundaries",type:"list",items:["Never enter a signed restricted road, beach, construction zone or industrial compound.","Do not fly a drone; launch periods and sensitive infrastructure can carry strict airspace and equipment controls.","A homestay roof or private field is not public access without the owner's permission and current safety approval.","Avoid photographing security posts, staff credentials or operational detail where notices prohibit it.","Use designated waste and sanitation facilities; a launch crowd does not turn villages or beaches into disposable viewing platforms.","Ask before close photography of residents, workers or children, especially during high-pressure launch days."]},
  {id:"failure-heading",type:"heading",level:2,text:"If the expected plan disappears"},
  {id:"failure",type:"table",caption:"Change the day without crossing visitor boundaries",columns:["Change","What to do","Do not do"],rows:[
    ["Launch postponed","Keep only independently confirmed public activities and ordinary city/coast context; wait for the next official window.","Follow an unofficial car convoy toward a restricted viewpoint."],
    ["Public venue closed or booking fails","Use official online interpretation, town/coastal geography and a non-space Wenchang backup.","Claim the industrial park exterior is a visitor experience."],
    ["Road control blocks the intended point","Use another area only if police or the local authority explicitly designates it; otherwise abandon viewing.","Walk through villages, fields or closed shore to bypass control."],
    ["Cloud or rain hides the view","Prioritize the launch sound/sequence only from the safe point, or treat the event as cancelled for your plan.","Move onto exposed rocks or unsafe water edges." ]
  ]},
  {id:"verify-heading",type:"heading",level:2,text:"Final verification checklist"},
  {id:"verify",type:"list",items:["Exact mission and latest official time window, if applicable","Whether a current official notice names any public viewing arrangement; if not, no viewing plan","Exact Chinese name, address and entrance of any proposed public venue","Direct operator confirmation of opening, reservation, foreign-passport and payment rules","Written distinction between the national site and Hainan International Commercial Aerospace Launch Center","Weather, sun and rain protection plus a cancelled-launch backup","No drone, trespass, private-land or old-viewing-guide assumption","No planned facility represented as already open"]},
  {id:"help",type:"callout",title:"Need Wenchang to fit a wider Hainan trip?",body:"Tell Homeground whether your priority is a particular mission, public science interpretation or simply understanding the new commercial-space city. A real planner can recheck the event and access layers and keep the rest of the island trip workable if the launch changes.",tone:"neutral"},
  {id:"links",type:"internal-links",title:"Plan the surrounding logistics",items:[
    {label:"Understand China's climate regions",href:"/guides/china-climate-regions-for-trip-timing/",description:"Treat Hainan's conditions separately from other regions and prepare for weather disruption."},
    {label:"Compare domestic-flight fare bundles",href:"/guides/china-domestic-flight-fare-bundle-baggage/",description:"Protect Hainan connections from baggage and fare assumptions."},
    {label:"Check China's public-holiday travel calendar",href:"/guides/china-public-holidays-travel-calendar/",description:"Add demand and transport pressure to any launch-day plan."}
  ]},
  {id:"sources",type:"sources",title:"Official and independent sources",items:[
    {label:"Hero image — Wenchang launch infrastructure seen across the coast from a nearby beach, photographed 2022-06-10; not evidence of a current designated viewing point or access",url:"https://commons.wikimedia.org/wiki/File:Wenchang_Space_Launch_Site_02.jpg",publisher:"Shujianyang — CC BY-SA 4.0; attribution only, no endorsement implied",reviewedAt:"2026-08-13"},
    {label:"Hero image licence — CC BY-SA 4.0",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-13"},
    {label:"Wenchang launch-site system",url:"https://www.cmse.gov.cn/gygc/xtzc/hnfscxt/",publisher:"China Manned Space Agency",reviewedAt:"2026-08-13"},
    {label:"National and commercial launch-site distinction",url:"https://www.digitalchina.gov.cn/2024/xwzx/szkx/202412/t20241206_4941536.htm",publisher:"Digital China / People's Daily",reviewedAt:"2026-08-13"},
    {label:"Wenchang International Aerospace City",url:"https://en.hainan.gov.cn/englishsite/iind/202507/86c1710bb0a1432287184de0e337d7ab.shtml?ddtab=true",publisher:"Hainan Provincial Government",reviewedAt:"2026-08-13"},
    {label:"Wenchang aerospace-tourism update",url:"https://en.hainan.gov.cn/englishsite/Updates/202605/c176115729174a24964bc275c2e09ef1.shtml?ddtab=true",publisher:"Hainan Provincial Government",reviewedAt:"2026-08-13"},
    {label:"Commercial space clusters in China",url:"https://spacenews.com/chinese-provinces-are-fueling-the-countrys-commercial-space-expansion/",publisher:"SpaceNews",reviewedAt:"2026-08-13"}
  ]}
]} as const satisfies StructuredPageBody;

export default body;
