import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {schemaVersion:"1.0.0",blocks:[
  {id:"lead",type:"lead",text:"Wenchang is not one space attraction behind one gate. The coastal city contains a national launch site, a separate commercial launch site, a wider aerospace-city development programme, industrial compounds, public viewing and science-tourism products, and projects that exist only in plans. A useful visit begins by naming which object you mean. It then separates a launch event—which can change or be postponed—from things that can still be understood on an ordinary day."},
  {id:"answer",type:"callout",title:"The short answer",body:"Base yourself in Wenchang or Longlou only after confirming your purpose. For a launch, use a currently designated public viewing area and obey the temporary safety plan. Without a launch, choose one currently operating science or visitor product and use the coastal town as context. Do not arrive at either operational launch-site gate expecting a factory tour, and never treat a planned museum, theme park or industrial project as open.",tone:"decision"},
  {id:"ledger-heading",type:"heading",level:2,text:"Five labels that must not be collapsed"},
  {id:"ledger",type:"table",caption:"Wenchang's space entities and their visitor meaning",columns:["Entity","Verified role","Visitor interpretation","Do not assume"],rows:[
    ["Wenchang Spacecraft Launch Site","The national launch system handles major state spaceflight missions; the official crewed-space programme describes its launch and support role.","Operational infrastructure seen only from approved public contexts unless a current official tour says otherwise.","‘Open launch site’ means walk-in pad access."],
    ["Hainan Commercial Spacecraft Launch Site","A separate commercial launch site near, but not identical to, the national site; it completed its first launch in 2024.","An operating launch facility, not automatically a daily attraction.","Its launch calendar, pad or industrial buildings are open to casual visitors."],
    ["Wenchang International Aerospace City","A development and industry programme covering launch, manufacturing, data and related zones.","A framework for understanding the local economy and geography.","The word ‘city’ identifies a single visitor campus."],
    ["Public viewing and science-tourism areas","Designated viewing points and currently advertised science products sit outside operational compounds.","The legitimate visitor layer; exact product and access must be current.","Every beach, roof or roadside is a safe viewing point."],
    ["Planned projects","Official plans discuss new museums, parks, factories, visitor facilities and later phases.","Future context only until an operator announces opening and booking.","A construction rendering or policy target is an operating service."]
  ]},
  {id:"geography-heading",type:"heading",level:2,text:"Read the geography before choosing a base"},
  {id:"geography",type:"paragraph",text:"Wenchang city, Longlou town, the coastal viewing areas and the two launch compounds are related but not interchangeable map pins. Wenchang has rail access and broader city services; Longlou is closer to the launch coast and carries more launch-day pressure. Industrial and operational zones may lie only a few kilometres apart while remaining legally and functionally separate. Save the exact Chinese name and entrance for any confirmed public venue, plus a second pin for your approved viewing area. A map label alone does not grant access."},
  {id:"base-heading",type:"heading",level:2,text:"Choose the base by the task, not the brand"},
  {id:"base",type:"comparison",title:"Two sensible bases",leftTitle:"Wenchang urban area",rightTitle:"Longlou and the launch coast",rows:[
    {label:"Best for",left:"Rail arrival, ordinary city services and a visit not dependent on launch timing.",right:"A confirmed launch-viewing plan or an early start near a verified coastal venue."},
    {label:"Trade-off",left:"Requires a separately planned road transfer to Longlou/coast.",right:"Demand, traffic controls and service patterns can change sharply around launches."},
    {label:"Failure recovery",left:"Easier to continue with city, food and coastal alternatives.",right:"Stronger immediate launch context, but fewer reasons to stay if the only plan is cancelled."}
  ]},
  {id:"launch-heading",type:"heading",level:2,text:"A launch day is an event operation, not a normal sightseeing day"},
  {id:"launch",type:"list",items:["Use only a mission announcement from the responsible space authority or launch operator; reposted countdowns are leads, not confirmation.","Expect mission timing, weather, technical readiness and safety controls to change. Never build a non-refundable onward connection around an exact ignition time.","Check the Wenchang/local public-safety and transport notice for designated viewing points, road controls and prohibited areas.","Arrive with water, sun or rain protection and a charged phone, but follow any restrictions on equipment, parking, drones and temporary structures.","Keep a fixed meeting point because mobile networks and road movement may become difficult when crowds concentrate.","After a postponement, wait for an official update; do not move closer to a pad, beach closure or restricted road seeking a better view."]},
  {id:"ordinary-heading",type:"heading",level:2,text:"What an ordinary, no-launch day can still explain"},
  {id:"ordinary",type:"table",caption:"Build value that does not depend on ignition",columns:["Question","Public evidence to seek","Useful takeaway"],rows:[
    ["Why Wenchang?","Coastal geography, latitude explanations and official science interpretation.","Why location, sea transport and eastward flight paths matter."],
    ["Why a second launch site?","Current official explanations of commercial demand and separate operations.","The commercial site is additional infrastructure, not a renamed national site."],
    ["What is an aerospace city?","Public exhibitions, city planning context and visible urban change from lawful public areas.","Manufacturing, data and services extend beyond the launch pad."],
    ["What can visitors enter?","A current operator page naming an address, opening status, identity rule and booking method.","Public science communication is a separate layer from operational access."]
  ]},
  {id:"scenarios-heading",type:"heading",level:2,text:"Three travellers, three decisions"},
  {id:"scenarios",type:"table",caption:"Do not force the same Wenchang plan on everyone",columns:["Traveller","Core plan","Stop rule"],rows:[
    ["Space enthusiast with flexible dates","Hold two Wenchang nights, confirm an approved viewing point, and protect the following day from tight connections.","Leave if the new official mission window falls outside the trip; do not chase restricted access."],
    ["Family visiting Hainan without a scheduled launch","Use one verified science product plus coast/town context, with shade and rest built in.","Skip any venue whose current opening, age rule or passport handling cannot be confirmed."],
    ["Industry-curious traveller","Study the entity ledger and public exhibitions; arrange a professional visit only through an authorized host.","No cold arrival at industrial parks, factories or launch-site gates." ]
  ]},
  {id:"route-heading",type:"heading",level:2,text:"A responsible one-day execution chain"},
  {id:"route",type:"list",items:["Before travel: identify whether this is a launch day, ordinary visitor day or authorized professional visit.","Save official Chinese names for the national site, commercial site, confirmed public venue and approved viewing area so drivers do not substitute one for another.","Morning: use one operating public science venue or official exhibition; verify the address and booking the day before.","Midday: pause in Wenchang or Longlou rather than lingering outside an operational perimeter.","Afternoon: observe the coastal geography from a lawful public place and connect it to what the exhibition explained.","Evening: if an officially confirmed launch is scheduled, follow the temporary viewing and traffic scheme. Otherwise leave the coast without waiting for rumours.","Afterward: label photos accurately—public viewing coast, town, national-site infrastructure in the distance, or commercial-site context—rather than ‘inside the launch base’." ]},
  {id:"boundaries-heading",type:"heading",level:2,text:"Operational and community boundaries"},
  {id:"boundaries",type:"list",items:["Never enter a signed restricted road, beach, construction zone or industrial compound.","Do not fly a drone; launch periods and sensitive infrastructure can carry strict airspace and equipment controls.","A homestay roof or private field is not public access without the owner's permission and current safety approval.","Avoid photographing security posts, staff credentials or operational detail where notices prohibit it.","Use designated waste and sanitation facilities; a launch crowd does not turn villages or beaches into disposable viewing platforms.","Ask before close photography of residents, workers or children, especially during high-pressure launch days."]},
  {id:"failure-heading",type:"heading",level:2,text:"Failure recovery"},
  {id:"failure",type:"table",caption:"What to do when the headline plan disappears",columns:["Failure","Recovery","Do not do"],rows:[
    ["Launch postponed","Keep the science/coast day and wait for the next official window.","Follow an unofficial car convoy toward a restricted viewpoint."],
    ["Public venue closed or booking fails","Use official online interpretation, town/coastal geography and a non-space Wenchang backup.","Claim the industrial park exterior is a visitor experience."],
    ["Road control blocks the intended point","Follow police/local authority diversion to another designated area or abandon viewing.","Walk through villages, fields or closed shore to bypass control."],
    ["Cloud or rain hides the view","Prioritize the launch sound/sequence only from the safe point, or treat the event as cancelled for your plan.","Move onto exposed rocks or unsafe water edges." ]
  ]},
  {id:"verify-heading",type:"heading",level:2,text:"Final verification checklist"},
  {id:"verify",type:"list",items:["Exact mission and latest official time window, if applicable","Current designated viewing area and temporary traffic plan","Exact Chinese name, address and entrance of any public venue","Current opening, reservation, passport and payment rules","Written distinction between the national site and commercial site in your notes","Weather, sun and rain protection plus a cancelled-launch backup","No drone, trespass or private-land assumption","No planned facility represented as already open"]},
  {id:"help",type:"callout",title:"Need Wenchang to fit a wider Hainan trip?",body:"Tell Homeground whether your priority is a particular mission, public science interpretation or simply understanding the new commercial-space city. A real planner can recheck the event and access layers and keep the rest of the island trip workable if the launch changes.",tone:"neutral"},
  {id:"links",type:"internal-links",title:"Plan the surrounding logistics",items:[
    {label:"Understand China's climate regions",href:"/guides/china-climate-regions-for-trip-timing/",description:"Treat Hainan's conditions separately from other regions and prepare for weather disruption."},
    {label:"Compare domestic-flight fare bundles",href:"/guides/china-domestic-flight-fare-bundle-baggage/",description:"Protect Hainan connections from baggage and fare assumptions."},
    {label:"Check China's public-holiday travel calendar",href:"/guides/china-public-holidays-travel-calendar/",description:"Add demand and transport pressure to any launch-day plan."}
  ]},
  {id:"sources",type:"sources",title:"Official and independent sources",items:[
    {label:"Wenchang launch-site system",url:"https://www.cmse.gov.cn/gygc/xtzc/hnfscxt/",publisher:"China Manned Space Agency",reviewedAt:"2026-08-13"},
    {label:"National and commercial launch-site distinction",url:"https://www.digitalchina.gov.cn/2024/xwzx/szkx/202412/t20241206_4941536.htm",publisher:"Digital China / People's Daily",reviewedAt:"2026-08-13"},
    {label:"Wenchang International Aerospace City",url:"https://en.hainan.gov.cn/englishsite/iind/202507/86c1710bb0a1432287184de0e337d7ab.shtml?ddtab=true",publisher:"Hainan Provincial Government",reviewedAt:"2026-08-13"},
    {label:"Wenchang aerospace-tourism update",url:"https://en.hainan.gov.cn/englishsite/Updates/202605/c176115729174a24964bc275c2e09ef1.shtml?ddtab=true",publisher:"Hainan Provincial Government",reviewedAt:"2026-08-13"},
    {label:"Commercial space clusters in China",url:"https://spacenews.com/chinese-provinces-are-fueling-the-countrys-commercial-space-expansion/",publisher:"SpaceNews",reviewedAt:"2026-08-13"}
  ]}
]} as const satisfies StructuredPageBody;

export default body;
