import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "answer-first",
      type: "lead",
      text: "A foreign passport is not a reason to search for a hotel with a special ‘foreign guest licence.’ Current national measures say qualification requirements should not be used to block accommodation operators from receiving overseas guests, and a hotel should not refuse you solely because it claims to lack ‘foreign-related qualifications.’ But ‘any hotel’ is not an unconditional booking guarantee. A valid reservation, an accepted travel document, ordinary check-in conditions and the exact property’s ability to complete registration still matter.",
    },
    {
      id: "three-layers",
      type: "comparison",
      title: "Keep three records separate",
      columns: [
        {
          heading: "Official rule",
          body: "The hotel checks the document, registers the guest and submits hotel-stay information. The rule does not create a special licence for travellers to find.",
          items: ["Use official policy for a qualification-based refusal.", "Do not use it to prove room availability."],
        },
        {
          heading: "Platform record",
          body: "The listing, guest-policy label, payment, confirmation and chat record show what was sold. They are transaction evidence, not law.",
          items: ["Save the exact branch and terms.", "A label may be stale or wrong."],
        },
        {
          heading: "Front-desk execution",
          body: "The staff on duty must find the booking, check the document and use the registration process. Training or system uncertainty can still cause failure.",
          items: ["Confirm staffed arrival in writing.", "Escalate calmly when execution fails."],
        },
      ],
    },
    {
      id: "answer-boundaries",
      type: "table",
      caption: "The reason changes the solution",
      columns: ["What blocks check-in", "What it means", "First response"],
      rows: [
        ["‘No foreign-guest qualification’", "This conflicts with current national policy.", "Ask the duty manager to check the official notice and registration procedure."],
        ["Wrong branch, date, name or no room", "This is primarily a booking or inventory problem.", "Have platform support reconcile the live reservation."],
        ["Missing, expired or unusable document", "A platform confirmation cannot replace identity verification.", "Seek document guidance from 12367 and the relevant authority or consulate."],
        ["An ordinary condition or lawful restriction", "The national notice does not erase every valid check-in condition.", "Ask for the precise rule and written explanation before deciding the remedy."],
      ],
    },
    {
      id: "before-booking-heading",
      type: "heading",
      level: 2,
      text: "Verify the exact property before arrival",
    },
    {
      id: "prebooking-checklist",
      type: "list",
      items: [
        "Save the property’s Chinese name, branch, full address, map pin and front-desk number.",
        "State that every foreign guest will use an original valid passport or other accepted travel document.",
        "Give the arrival date and time; ask whether reception will be staffed and the room held after late check-in.",
        "Ask whether this exact property completes hotel accommodation registration at check-in.",
        "Keep the answer in platform chat and save an offline screenshot with branch name and timestamp.",
        "Read cancellation and no-show terms; do not assume a refusal automatically creates a refund or price-difference payment.",
      ],
    },
    {
      id: "confirmation-messages",
      type: "table",
      caption: "Three short messages to create a usable record",
      columns: ["Purpose", "Message to send", "Chinese to show"],
      rows: [
        ["Passport and registration", "I will arrive with a [country] passport. Can this exact branch complete hotel accommodation registration?", "我将持[国家]护照入住。请确认这家具体门店可以为我办理旅馆住宿登记。"],
        ["Late arrival", "Will reception be staffed at [time], and will you hold my confirmed room?", "请确认[时间]前台有人值班，并会保留我已确认的房间。"],
        ["Exact branch", "Please reply in this booking chat and include the full branch name.", "请在订单聊天中书面回复，并写明完整门店名称。"],
      ],
    },
    {
      id: "registration-heading",
      type: "heading",
      level: 2,
      text: "What happens at hotel registration",
    },
    {
      id: "desk-materials",
      type: "list",
      ordered: true,
      items: [
        "Go to the exact branch and show the booking name and confirmation.",
        "Each foreign guest presents the original valid passport or other accepted international travel document.",
        "Let staff inspect and record the information required for hotel accommodation registration.",
        "Check that spelling or document details collected by the platform do not point to a different guest.",
        "Ask for the manager if the desk confuses hotel registration with the separate process for a private residence.",
      ],
    },
    {
      id: "hotel-nonhotel",
      type: "table",
      caption: "Registration responsibility depends on the stay type",
      columns: ["Stay", "Who registers", "Traveller check"],
      rows: [
        ["Hotel accommodation", "The hotel registers the guest and submits the hotel-stay information.", "Bring the original document and confirm staffed check-in."],
        ["Private home or another non-hotel residence", "The foreigner or host completes registration within 24 hours.", "Ask which current local online or in-person route applies."],
        ["Unclear apartment, guesthouse or minsu", "First establish whether it operates as hotel or non-hotel accommodation.", "Do not assume a door code or platform label completes registration."],
      ],
    },
    {
      id: "nonhotel-pilot",
      type: "callout",
      title: "The online pilot is not a hotel check-in method",
      body: "The NIA page reviewed on 13 August 2026 still describes online non-hotel registration as a pilot in seven provincial-level regions. It does not replace a hotel’s registration duty. Recheck the NIA and local process for a private stay.",
      tone: "warning",
    },
    {
      id: "refusal-heading",
      type: "heading",
      level: 2,
      text: "If a confirmed hotel refuses check-in",
    },
    {
      id: "recovery-order",
      type: "list",
      ordered: true,
      items: [
        "Verify the branch, date, booking name, room status and original document once.",
        "Ask the duty manager for the exact reason, not only ‘system problem’ or ‘policy.’",
        "If the sole reason is missing foreign-related qualification, show the official Chinese notice and ask the manager to check the registration procedure.",
        "Open platform support from the active booking; ask it to call the property and record the hotel’s reason.",
        "Tell both sides not to mark you as a no-show. Do not cancel until the platform states in writing how fees will be handled.",
        "Set a short resolution limit, then move to a staffed alternative that has confirmed your document and arrival time.",
        "Keep the original dispute open and save replacement-room and transport receipts for later review.",
      ],
    },
    {
      id: "frontdesk-script",
      type: "table",
      caption: "Calm lines for the front desk",
      columns: ["Task", "Chinese", "Meaning"],
      rows: [
        ["Clarify", "请问无法入住的具体原因是什么？是订单、证件，还是登记流程问题？", "Is the exact problem the booking, document or registration process?"],
        ["Escalate", "请联系值班经理，并核对现行的境外人员住宿规定。", "Please contact the duty manager and check the current rule."],
        ["Protect the record", "请在订单中注明酒店无法办理入住，不要标记为客人未到店。", "Record that the hotel could not check me in; do not mark a no-show."],
        ["Seek an alternative", "请联系预订平台，协助安排已书面确认可以办理入住的替代住宿。", "Please help the platform arrange a replacement that has confirmed check-in."],
      ],
    },
    {
      id: "midnight-scenario",
      type: "callout",
      title: "Scenario: refusal after midnight with children or an older traveller",
      body: "Protect the group before debating the whole case. Record the unresolved refusal, obtain a platform case number, confirm a safe staffed alternative and move. Continue the refund or complaint from the new room.",
      tone: "decision",
    },
    {
      id: "platform-heading",
      type: "heading",
      level: 2,
      text: "Ask the platform for a written operational answer",
    },
    {
      id: "platform-asks",
      type: "list",
      items: [
        "Open a case against the live reservation and provide the reference.",
        "Call the exact property and identify whether the cause is inventory, booking, document or registration.",
        "Write the property’s answer into the order record and protect the guest from no-show treatment.",
        "Explain the options under the live terms: hotel resolution, replacement, penalty-free cancellation or refund review.",
        "State whether replacement and transport receipts may be reviewed; never promise reimbursement before written approval.",
      ],
    },
    {
      id: "alternative-scenarios",
      type: "table",
      caption: "Choose the replacement for the failure you actually face",
      columns: ["Situation", "Replacement priority", "Avoid"],
      rows: [
        ["Late-night refusal", "A nearby staffed desk that confirms the exact passport and arrival time.", "Another remote or door-code check-in."],
        ["Family, mobility need or heavy luggage", "A simple legal transfer and confirmed curb-to-room access.", "Rebooking by district name alone."],
        ["Original dispute remains open", "A separate new confirmation and itemised receipts.", "Letting support cancel or overwrite the disputed record without written terms."],
      ],
    },
    {
      id: "evidence-heading",
      type: "heading",
      level: 2,
      text: "Keep enough evidence, not unnecessary personal data",
    },
    {
      id: "evidence-table",
      type: "table",
      caption: "A privacy-safe record pack",
      columns: ["Record", "Why keep it", "Privacy rule"],
      rows: [
        ["Confirmation and terms", "Proves branch, date, guest and transaction conditions.", "Redact payment details when sharing outside support."],
        ["Dated listing screenshot", "Shows the platform wording at booking time.", "Treat it as transaction evidence, not law."],
        ["Hotel refusal note or chat", "Records time, stated reason and manager review.", "Collect staff names only when offered and necessary."],
        ["Platform case and resolution", "Records what support confirmed and offered.", "Keep the case number; do not publish the transcript."],
        ["Replacement and transport receipts", "Shows reasonable recovery costs.", "Share only with the platform or competent complaint channel."],
      ],
    },
    {
      id: "channel-heading",
      type: "heading",
      level: 2,
      text: "Use each official channel for its actual role",
    },
    {
      id: "channels",
      type: "table",
      caption: "Official channels do not replace the room for you",
      columns: ["Channel", "Use", "Boundary"],
      rows: [
        ["12367", "Immigration-management and accommodation-registration policy questions.", "It does not decide a platform refund."],
        ["12345", "Non-emergency local-government information, help, complaints and routing.", "It is not an emergency police line."],
        ["12315", "A documented consumer dispute with the hotel or platform.", "It does not produce an immediate room or automatic compensation."],
        ["110", "A genuine immediate threat, suspected crime or police emergency.", "Do not use it for a routine booking or refund argument."],
      ],
    },
    {
      id: "failure-cases-heading",
      type: "heading",
      level: 2,
      text: "Two common scenarios that change the answer",
    },
    {
      id: "failure-cases",
      type: "table",
      caption: "Do not turn every refusal into the same dispute",
      columns: ["Scenario", "Decision", "Recovery"],
      rows: [
        ["The desk says ‘no foreigner qualification,’ but the booking and passport are valid.", "Treat it as a policy/execution problem.", "Manager, official notice, platform record, then 12367 or 12345 if needed."],
        ["The hotel says ‘no room’ or cannot find the reservation.", "Treat it as inventory/transaction failure, not proof of a passport rule.", "Have the platform reconcile or replace under the live terms."],
        ["A self-service apartment sends only a door code.", "The operating and registration model is unclear.", "Ask who registers the stay; use a staffed alternative if the answer remains vague."],
        ["The passport is lost or unusable.", "The booking cannot substitute for a valid document.", "Contact 12367, the local exit-entry authority and the relevant embassy or consulate."],
      ],
    },
    {
      id: "final-checklist",
      type: "callout",
      title: "The two checklists to remember",
      body: "Before arrival: exact branch, original documents, staffed time, written registration confirmation and saved terms. After refusal: exact cause, manager, platform case, no-show protection, confirmed replacement and necessary receipts. Resolve safety first; pursue the commercial or official remedy second.",
      tone: "decision",
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Continue the stay decision",
      items: [
        { label: "Stay in China", href: "/stay/", description: "Return to the accommodation decision collection." },
        { label: "How to pay in China as a tourist", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Prepare payment backups for deposits and replacement bookings." },
        { label: "How to judge a China hotel near the metro", href: "/guides/china-hotel-near-metro/", description: "Verify the usable door-to-platform route separately." },
        { label: "Why are hotels in China so cheap?", href: "/guides/why-are-hotels-in-china-so-cheap/", description: "Compare property type and value without confusing price with registration." },
      ],
    },
    {
      id: "light-help",
      type: "callout",
      title: "Need a human check?",
      body: "Send the dates, traveller count, cities, approximate nightly budget and any late arrival. Homeground can help assess the property questions and backup sequence without ranking hotel apps or promising check-in.",
      tone: "neutral",
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official sources checked on 13 August 2026",
      items: [
        { label: "Measures facilitating accommodation for overseas visitors", url: "https://www.mofcom.gov.cn/zwgk/zcfb/art/2024/art_10ddb29858c24ece86b3f575bda1d9c4.html", publisher: "Ministry of Commerce and six departments", reviewedAt: "2026-08-13" },
        { label: "English summary of the accommodation measures", url: "https://english.www.gov.cn/news/202407/26/content_WS66a2d827c6d0868f4e8e975c.html", publisher: "State Council website", reviewedAt: "2026-08-13" },
        { label: "Response on refusal for lack of foreign-related qualification", url: "https://www.gov.cn/hudong/202405/content_6952770.htm", publisher: "China Government Network", reviewedAt: "2026-08-13" },
        { label: "Hotel and non-hotel accommodation registration interpretation", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-13" },
        { label: "Beijing accommodation registration guide", url: "https://english.beijing.gov.cn/livinginbeijing/applicationfordocuments/202107/t20210719_2439278.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-13" },
        { label: "Official route to the 12315 consumer platform", url: "https://www.samr.gov.cn/hd/xfzn/art/2022/art_9d22351e9bee4da38b89c15e843207b4.html", publisher: "State Administration for Market Regulation", reviewedAt: "2026-08-13" },
        { label: "Boundary between 12345 and 110", url: "https://www.beijing.gov.cn/zhengce/gwywj/202205/t20220516_2711529.html", publisher: "State Council General Office via Beijing Government", reviewedAt: "2026-08-13" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
