import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "answer-first",
      type: "lead",
      text: "持外国护照入住中国酒店，不需要专门寻找所谓“涉外宾馆许可证”。现行国家政策明确，地方部门和平台不应以资质要求限制住宿经营者接待境外人员，旅馆也不得仅以“没有涉外资质”为由拒绝接待。不过，“任何酒店都一定能住”仍然是过度承诺：订单必须真实有效，旅客要出示可接受的有效旅行证件并满足正常入住条件，具体门店也必须能够正确完成住宿登记。",
    },
    {
      id: "three-layers",
      type: "comparison",
      title: "把三类记录分开判断",
      columns: [
        {
          heading: "官方规则",
          body: "酒店查验证件、登记住客，并报送旅馆住宿信息。规则里没有要求旅客寻找某种特殊“涉外许可证”。",
          items: ["因“没有涉外资质”被拒时，使用官方政策沟通。", "官方规则不能证明某间客房仍然有库存。"],
        },
        {
          heading: "平台记录",
          body: "房源页面、住客政策标签、付款、确认单和聊天记录说明交易时展示或承诺了什么，但它们不是法律。",
          items: ["保存具体门店和实际条款。", "平台标签可能过时或标错门店。"],
        },
        {
          heading: "前台执行",
          body: "当班员工必须找到订单、查验证件并使用登记系统。培训不足或系统操作不熟，仍可能导致现场失败。",
          items: ["提前书面确认抵达时有人值班。", "执行失败时冷静升级处理。"],
        },
      ],
    },
    {
      id: "answer-boundaries",
      type: "table",
      caption: "被卡住的原因不同，处理方法也不同",
      columns: ["无法入住的原因", "意味着什么", "第一步"],
      rows: [
        ["“没有涉外接待资质”", "这一说法与现行国家政策冲突。", "请值班经理核对官方通知和住宿登记流程。"],
        ["门店、日期或姓名不对，或酒店无房", "这首先是订单或库存问题。", "请平台客服核对当前有效订单。"],
        ["证件遗失、过期或无法使用", "平台确认单不能替代身份查验。", "向12367、有关主管机关或领事机构咨询证件处理。"],
        ["普通入住条件或合法限制未满足", "国家通知不会取消所有正当入住条件。", "先要求对方说明准确规则并留下书面解释，再决定后续处理。"],
      ],
    },
    {
      id: "before-booking-heading",
      type: "heading",
      level: 2,
      text: "抵达前核验具体门店",
    },
    {
      id: "prebooking-checklist",
      type: "list",
      items: [
        "保存酒店中文名称、具体门店、完整地址、地图定位和前台电话。",
        "说明每位境外旅客都会携带护照原件或其他可接受的有效旅行证件。",
        "告知抵达日期和时间，确认届时有人值班，晚于常规时间抵达时仍会保留房间。",
        "询问这家具体门店是否会在入住时办理旅馆住宿登记。",
        "尽量让酒店在平台订单聊天中回复，并保存带门店名称和时间的离线截图。",
        "查看取消和未到店条款；不要默认被拒后一定自动退款、补差价或报销交通。",
      ],
    },
    {
      id: "confirmation-messages",
      type: "table",
      caption: "用三条短消息建立可用记录",
      columns: ["用途", "可发送的英文", "给酒店看的中文"],
      rows: [
        ["护照和登记", "I will arrive with a [country] passport. Can this exact branch complete hotel accommodation registration?", "我将持[国家]护照入住。请确认这家具体门店可以为我办理旅馆住宿登记。"],
        ["较晚抵达", "Will reception be staffed at [time], and will you hold my confirmed room?", "请确认[时间]前台有人值班，并会保留我已确认的房间。"],
        ["锁定门店", "Please reply in this booking chat and include the full branch name.", "请在订单聊天中书面回复，并写明完整门店名称。"],
      ],
    },
    {
      id: "registration-heading",
      type: "heading",
      level: 2,
      text: "旅馆住宿登记会怎样进行",
    },
    {
      id: "desk-materials",
      type: "list",
      ordered: true,
      items: [
        "到达订单上的准确门店，出示预订姓名和确认单。",
        "每位境外住客出示有效护照原件或其他可接受的国际旅行证件。",
        "让前台查验证件，并采集旅馆住宿登记所需信息。",
        "如果平台曾采集姓名或证件资料，核对拼写和号码没有指向另一位住客。",
        "前台若把旅馆登记与私人住所的登记流程混为一谈，请值班经理复核。",
      ],
    },
    {
      id: "hotel-nonhotel",
      type: "table",
      caption: "住宿形式决定由谁办理登记",
      columns: ["住宿形式", "登记责任", "旅客需要核验"],
      rows: [
        ["旅馆住宿", "酒店为住客办理登记并报送旅馆住宿信息。", "携带证件原件，并确认抵达时有前台。"],
        ["私人住宅或其他非旅馆住所", "外国人本人或留宿人在入住后24小时内办理登记。", "询问当地现行线上或现场办理方式。"],
        ["经营形式不清的公寓、客栈或民宿", "先确认它究竟按旅馆还是非旅馆住宿运营。", "不要以为门锁密码或平台标签已经完成登记。"],
      ],
    },
    {
      id: "nonhotel-pilot",
      type: "callout",
      title: "线上试点不是酒店入住方式",
      body: "截至2026年8月13日，国家移民管理局页面仍把非旅馆住宿线上登记描述为七个省级地区的试点。它不会取代酒店应承担的登记责任。住私人住所时，要按旅行日期重新核对国家移民管理局和当地流程。",
      tone: "warning",
    },
    {
      id: "refusal-heading",
      type: "heading",
      level: 2,
      text: "确认订单被拒时，按顺序恢复",
    },
    {
      id: "recovery-order",
      type: "list",
      ordered: true,
      items: [
        "只核对一次门店、日期、预订姓名、房间状态和证件原件。",
        "请值班经理说明准确原因，不要只接受“系统问题”或“政策规定”这种笼统说法。",
        "如果唯一理由是“没有涉外资质”，出示官方中文通知，请经理核对现行登记流程。",
        "从仍然有效的订单进入平台客服，请客服致电门店，并把酒店给出的原因写入记录。",
        "要求酒店和平台不要标记为客人未到店。平台未书面说明费用处理前，不要自行取消。",
        "设定很短的解决时限；超过时限，就转移到已经确认你的证件和抵达时间、并且有人值班的替代住宿。",
        "保持原纠纷工单开放，并保存替代房费和交通凭证，供后续审核。",
      ],
    },
    {
      id: "frontdesk-script",
      type: "table",
      caption: "在前台可以平静使用的句子",
      columns: ["任务", "中文", "表达重点"],
      rows: [
        ["确认原因", "请问无法入住的具体原因是什么？是订单、证件，还是登记流程问题？", "把问题限定为订单、证件或登记流程。"],
        ["要求升级", "请联系值班经理，并核对现行的境外人员住宿规定。", "请当班负责人核查当前规则。"],
        ["保护订单", "请在订单中注明酒店无法办理入住，不要标记为客人未到店。", "记录酒店无法办理，不要写成住客未出现。"],
        ["寻找替代", "请联系预订平台，协助安排已书面确认可以办理入住的替代住宿。", "请酒店与平台协助寻找已经确认的替代房。"],
      ],
    },
    {
      id: "midnight-scenario",
      type: "callout",
      title: "情境：半夜被拒，同行有儿童或老人",
      body: "先保证团队安全，不要在前台把整场纠纷争完。记录问题尚未解决，取得平台工单号，确认一家具备前台的安全替代住宿后立即转移。退款或投诉可以到新酒店后继续。",
      tone: "decision",
    },
    {
      id: "platform-heading",
      type: "heading",
      level: 2,
      text: "要求平台给出书面、可执行的答案",
    },
    {
      id: "platform-asks",
      type: "list",
      items: [
        "针对当前有效订单建立客服工单，并提供编号。",
        "致电准确门店，查明原因是库存、订单、证件还是登记。",
        "把门店答复写入订单记录，并避免把住客标记为未到店。",
        "按本订单实时条款解释可选方案：门店解决、换订、无罚取消或退款审核。",
        "明确替代住宿和交通凭证能否提交审核；没有书面批准前，不承诺一定报销。",
      ],
    },
    {
      id: "alternative-scenarios",
      type: "table",
      caption: "替代住宿要针对实际故障来选",
      columns: ["情境", "替代方案的优先项", "避免"],
      rows: [
        ["深夜被拒", "附近有前台，并书面确认具体护照和抵达时间。", "再次选择远程或仅密码入住。"],
        ["家庭、行动不便或行李很多", "合法、简单的转移路线和已确认的下客点至房间通路。", "只按片区名称重新预订。"],
        ["原订单纠纷仍在进行", "另建一份清晰的新订单并保存明细凭证。", "没有书面条款就让客服取消或覆盖原记录。"],
      ],
    },
    {
      id: "evidence-heading",
      type: "heading",
      level: 2,
      text: "保存够用的证据，不收集多余个人信息",
    },
    {
      id: "evidence-table",
      type: "table",
      caption: "隐私安全的留证包",
      columns: ["记录", "用途", "隐私边界"],
      rows: [
        ["确认单和条款", "证明门店、日期、住客与交易条件。", "向客服以外分享时遮盖支付信息。"],
        ["带日期的房源截图", "证明预订时平台展示的文字。", "它是交易证据，不是法律。"],
        ["酒店拒绝记录或聊天", "记录时间、所述原因和经理是否复核。", "只有对方主动提供且确有必要时才记录员工姓名。"],
        ["平台工单和处理结果", "证明客服确认了什么、提出了什么方案。", "保存工单号，不公开聊天全文。"],
        ["替代房费与交通凭证", "说明为恢复行程发生的合理成本。", "只提供给平台或有权处理投诉的渠道。"],
      ],
    },
    {
      id: "channel-heading",
      type: "heading",
      level: 2,
      text: "按官方渠道的真实职责使用",
    },
    {
      id: "channels",
      type: "table",
      caption: "官方热线不会替你立即变出一间客房",
      columns: ["渠道", "适用问题", "边界"],
      rows: [
        ["12367", "移民管理和住宿登记政策咨询。", "不决定平台是否退款。"],
        ["12345", "地方政府的非紧急咨询、求助、投诉和转办。", "不是紧急报警电话。"],
        ["12315", "针对酒店或平台的有记录消费纠纷。", "不会立即提供房间，也不代表自动赔偿。"],
        ["110", "真实、紧迫的人身财产威胁、涉嫌犯罪或警务紧急情况。", "不要用于普通订单或退款争议。"],
      ],
    },
    {
      id: "failure-cases-heading",
      type: "heading",
      level: 2,
      text: "两类常见情境会改变结论",
    },
    {
      id: "failure-cases",
      type: "table",
      caption: "不要把所有被拒都处理成同一类纠纷",
      columns: ["情境", "判断", "恢复步骤"],
      rows: [
        ["订单和护照都有效，前台却说“没有涉外资质”。", "这是政策理解或前台执行问题。", "找经理、出示官方通知、记录平台工单，必要时咨询12367或12345。"],
        ["酒店说“没有房”或找不到订单。", "这是库存或交易失败，不等于外国护照规则。", "让平台按实时条款核单、换订或处理退款。"],
        ["自助公寓只发送门锁密码。", "经营方式和登记责任不清楚。", "询问由谁办理住宿登记；回答仍模糊就改住有前台的物业。"],
        ["护照遗失或无法使用。", "订单不能替代有效证件。", "联系12367、当地出入境管理机关和有关使领馆。"],
      ],
    },
    {
      id: "final-checklist",
      type: "callout",
      title: "只需要记住两份清单",
      body: "抵达前：准确门店、证件原件、有人值班的时间、书面登记确认和已保存条款。被拒后：准确原因、值班经理、平台工单、未到店保护、已确认替代住宿和必要凭证。先恢复安全，再追究商业或官方处理。",
      tone: "decision",
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "继续完成住宿决策",
      items: [
        { label: "中国住宿", href: "/zh/stay/", description: "返回住宿决策内容集合。" },
        { label: "外国游客如何在中国付款", href: "/zh/guides/how-to-pay-in-china-as-a-tourist/", description: "为押金和临时换订准备付款备用方案。" },
        { label: "如何判断中国酒店是否真的靠近地铁", href: "/zh/guides/china-hotel-near-metro/", description: "另行核验从酒店门口到站台的可用路线。" },
        { label: "中国酒店为什么这么便宜？", href: "/zh/guides/why-are-hotels-in-china-so-cheap/", description: "比较物业类型和价值，不把价格与住宿登记混为一谈。" },
      ],
    },
    {
      id: "light-help",
      type: "callout",
      title: "需要人工帮你核对？",
      body: "提供旅行日期、人数、城市、大致每晚预算和较晚抵达安排。Homeground 可以协助检查物业问题与备用顺序，但不会做酒店 App 排名或承诺一定入住。",
      tone: "neutral",
    },
    {
      id: "official-sources",
      type: "sources",
      title: "2026年8月13日复核的官方来源",
      items: [
        { label: "便利境外人员住宿若干措施", url: "https://www.mofcom.gov.cn/zwgk/zcfb/art/2024/art_10ddb29858c24ece86b3f575bda1d9c4.html", publisher: "商务部等七部门", reviewedAt: "2026-08-13" },
        { label: "便利住宿措施英文摘要", url: "https://english.www.gov.cn/news/202407/26/content_WS66a2d827c6d0868f4e8e975c.html", publisher: "中国政府网英文版", reviewedAt: "2026-08-13" },
        { label: "不得以无涉外资质为由拒绝接待的官方答复", url: "https://www.gov.cn/hudong/202405/content_6952770.htm", publisher: "中国政府网", reviewedAt: "2026-08-13" },
        { label: "旅馆与非旅馆住宿登记政策解读", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "国家移民管理局", reviewedAt: "2026-08-13" },
        { label: "北京市外国人住宿登记指南", url: "https://english.beijing.gov.cn/livinginbeijing/applicationfordocuments/202107/t20210719_2439278.html", publisher: "北京市人民政府", reviewedAt: "2026-08-13" },
        { label: "全国12315消费投诉渠道", url: "https://www.samr.gov.cn/hd/xfzn/art/2022/art_9d22351e9bee4da38b89c15e843207b4.html", publisher: "国家市场监督管理总局", reviewedAt: "2026-08-13" },
        { label: "12345与110职责边界", url: "https://www.beijing.gov.cn/zhengce/gwywj/202205/t20220516_2711529.html", publisher: "国务院办公厅（北京市政府转载）", reviewedAt: "2026-08-13" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
