import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const en = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "The first thing you see at Chengdu's Du Fu Thatched Cottage may look like a poet's preserved home. It is not. The useful visit begins by separating four places that now share one garden: Du Fu's documented Chengdu life, Tang-period remains found by archaeology, a memorial landscape repeatedly rebuilt after him, and a modern reconstruction of a thatched dwelling. Once those layers are kept apart, the museum becomes more moving—not less." },
    { id: "answer", type: "callout", title: "The direct answer", body: "Come for a literary memorial, not an intact Tang house. Homeground's preferred order is: orient yourself on the map, read the archaeological evidence, follow the later memorial axis, and finish at the reconstructed hut. A poem can help you imagine insecurity and shelter; it cannot serve as an architectural survey.", tone: "decision" },
    { id: "layers-h", type: "heading", level: 2, text: "Which parts belong to Du Fu, and which belong to his afterlife?" },
    { id: "layers-p", type: "paragraph", text: "The museum dates Du Fu's Chengdu period from 759 to 765 and associates roughly three years and nine months with the cottage. It also credits this Sichuan period with more than 240 poems. Those are biographical and literary facts. They do not establish that the timber, tiles or thatch now in front of you were handled by the poet." },
    { id: "layers-table", type: "table", caption: "Four evidence layers in one museum", columns: ["Layer", "What it can tell you", "What it cannot prove"], rows: [["History", "Du Fu's movements, relationships and writing in Chengdu", "That one current building is his surviving home"], ["Archaeology", "Tang-period occupation at the site through excavated remains", "That every remain belonged personally to Du Fu"], ["Memorial history", "How later generations constructed a place for remembering him", "The exact appearance of the eighth-century cottage"], ["Tourism presentation", "A legible hut scene and visitor route", "Original Tang fabric or a literal scene from one poem"]] },
    { id: "bio-h", type: "heading", level: 2, text: "Why Chengdu matters in Du Fu's biography" },
    { id: "bio-p1", type: "paragraph", text: "Du Fu reached Chengdu after years of upheaval and movement. With help from friends, he established a home near Huanhua Stream. The relative stability of this period mattered because it gave him a place from which to write about household life, neighbours, weather, illness, public disorder and moral responsibility. The cottage is therefore not important because a roof survived. It is important because a temporary home became a productive viewpoint." },
    { id: "bio-p2", type: "paragraph", text: "Use that biography carefully. The famous poem usually translated as “Song of My Cottage Unroofed by Autumn Gales” records a literary response to damage and vulnerability, but poetry selects, orders and enlarges experience. Paraphrase its concern with shelter; do not turn each line into a floor plan or claim that a reconstructed room is where a specific verse was written." },
    { id: "arch-h", type: "heading", level: 2, text: "Begin with the Tang remains, even if they look modest" },
    { id: "arch-p1", type: "paragraph", text: "The museum reports that Tang-period remains were excavated in 2001 and subsequently protected and interpreted. This is the strongest material bridge to the period in which Du Fu lived. It may be visually quieter than the red halls or the thatched reconstruction, so read the excavation label before judging the view. Record the feature type, date assigned by archaeologists, find location and whether you are seeing exposed fabric, a protected outline, a model or an image." },
    { id: "arch-p2", type: "paragraph", text: "Archaeology still has limits. A Tang wall, well or occupation layer at the site can confirm period activity; personal ownership requires another chain of evidence. Avoid the attractive leap from “Tang” to “Du Fu touched this.” If the archaeological section is closed for conservation, use the official site plan and museum explanation, then keep the claim at site-period level." },
    { id: "axis-h", type: "heading", level: 2, text: "Read the memorial axis as a history of remembering" },
    { id: "axis-p1", type: "paragraph", text: "The named halls and courtyards—among them Daxie (大廨), Poetry History Hall (诗史堂) and the Ministry of Works Shrine (工部祠)—belong to the long institutional life of the memorial. The museum's present axial pattern owes much to major work in 1500 and 1811. Those dates are not disappointing footnotes. They show how Ming and Qing patrons gave Du Fu an official, spatial biography." },
    { id: "axis-list", type: "list", ordered: true, items: ["At Daxie, ask what the hall introduces: the person, the place or the memorial institution.", "At Poetry History Hall, separate the later judgment that Du Fu's poems preserve history from any claim that the hall is Tang-period.", "At the Ministry of Works Shrine, notice that the title by which Du Fu is remembered is part of his later commemorative identity.", "At every old-looking doorway, look for a construction or repair date before assigning a dynasty."] },
    { id: "hut-h", type: "heading", level: 2, text: "What should you do at the reconstructed hut?" },
    { id: "hut-p1", type: "paragraph", text: "Treat the hut as an interpretation device. Its thatch, low profile, bamboo and small rooms make the idea of precarious domestic shelter immediately legible. That visual clarity is exactly why it can overwhelm the evidence. Say “reconstructed cottage precinct” in your notes and photographs. Do not caption it “Du Fu's house, built in 760.”" },
    { id: "hut-p2", type: "paragraph", text: "Then make the reconstruction work harder. Compare what the poem communicates—exposure, household pressure, concern for others—with what the scene designer chose to show. Which necessities are visible? Which signs of labour, water, food or writing are supplied by labels, and which are your assumptions? The point is not to accuse the scene of being false; it is to identify the kind of knowledge it offers." },
    { id: "poetry-h", type: "heading", level: 2, text: "How can you read poetry on site without turning it into evidence it is not?" },
    { id: "poetry-p", type: "paragraph", text: "Choose one short theme rather than trying to decode the whole Du Fu canon: shelter, the stream, family life, war at a distance or the ethics of care. Read the museum's Chinese title and authorship information, then use a translation you obtained legally. Modern translations are copyrighted; photographing a full translated panel for republication is not automatically permitted. The poem supplies perspective and language. Archaeology and building records supply material claims." },
    { id: "route-h", type: "heading", level: 2, text: "A practical visit that survives closures" },
    { id: "route-table", type: "table", caption: "Use this sequence, not fixed minutes", columns: ["Stop", "Question", "If unavailable"], rows: [["Official map", "Where are archaeology, memorial axis and hut?", "Photograph the map or ask staff for the current route"], ["Tang remains", "What is original material, outline, model or label?", "Use the official archaeology explanation"], ["Memorial halls", "Which later generation shaped this space?", "Read exterior labels without assuming room access"], ["Tablet/hut zone", "What is commemoration and what is reconstruction?", "View from the permitted path; do not cross barriers"], ["Final gallery", "Which claim changed after seeing the layers?", "Write a four-line recap outdoors"]] },
    { id: "misread-h", type: "heading", level: 2, text: "Do not leave with these three misunderstandings" },
    { id: "misread-list", type: "list", ordered: false, items: ["“The cottage is fake, so the visit has no value.” A reconstruction can be useful when its status is clear; the memorial and archaeology carry other values.", "“Everything old-looking is Ming or Qing original.” The site has repairs, replacements and later displays; identify the component.", "“The poem proves the reconstruction.” Literature records and reshapes experience; it is not measured architectural documentation."] },
    { id: "who-h", type: "heading", level: 2, text: "Who should prioritise this museum?" },
    { id: "who-p", type: "paragraph", text: "Prioritise it if one poem, one writer's life or the making of cultural memory can sustain your attention for several linked stops. It also works well for travelers learning how Chinese memorial sites accumulate layers. Skip or shorten it if you want an intact residence, a compact object museum, or a complete introduction to Tang poetry. The current official website should decide hours, booking, accessible routing and room closures immediately before travel." },
    { id: "links", type: "internal-links", title: "Continue reading places by evidence", items: [{ label: "Original, restored, rebuilt or relocated?", href: "/guides/how-to-read-heritage-sites-in-china/", description: "Use a national intervention vocabulary after this site-specific walk." }, { label: "How to visit an archaeological site museum", href: "/guides/how-to-visit-an-archaeological-site-museum/", description: "Connect remains, labels and displayed finds without overstating certainty." }, { label: "Walk Lu Xun's Shaoxing through text and place", href: "/guides/luxun-shaoxing-literary-walk/", description: "Compare another writer's later memorial landscape without treating fiction as a site plan." }, { label: "Compare China's three literary towers", href: "/guides/three-literary-towers-comparison/", description: "See how later architecture turns poetry and memory into different visit tasks." }, { label: "Watch Sichuan opera with context", href: "/guides/sichuan-opera-face-changing-with-context/", description: "Continue from Chengdu's literary memory to a living performance tradition." }] },
    { id: "sources", type: "sources", title: "Core institutional sources reviewed", items: [{ label: "Du Fu Thatched Cottage Museum", url: "https://www.cddfct.cn/", publisher: "Chengdu Du Fu Thatched Cottage Museum", reviewedAt: "2026-08-20" }, { label: "Museum history and site introduction", url: "https://www.cddfct.cn/go-c11.htm", publisher: "Chengdu Du Fu Thatched Cottage Museum", reviewedAt: "2026-08-20" }, { label: "Du Fu's Chengdu period", url: "https://www.cddfct.cn/go-a116.htm", publisher: "Chengdu Du Fu Thatched Cottage Museum", reviewedAt: "2026-08-20" }, { label: "Tang-dynasty archaeological remains", url: "https://www.cddfct.cn/go-a1133.htm", publisher: "Chengdu Du Fu Thatched Cottage Museum", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

const zh = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "走进成都杜甫草堂，眼前最像“诗人旧居”的地方，反而最需要先放慢判断：它不是保存至今的唐代住宅。一次可靠的参观，要把同一园林里的四层地点分开——杜甫确有文献支撑的成都经历、考古发现的唐代遗存、后世反复营建的纪念园林，以及今天帮助游客想象茅屋生活的复建场景。分清以后，草堂不会失去故事，反而会更有分量。" },
    { id: "answer", type: "callout", title: "直接答案", body: "把这里当作文学纪念地，而不是完整唐代故居。Homeground建议先看地图，再读考古遗存，随后沿后世纪念轴线前行，最后看复建茅屋。诗歌可以帮助理解居所的不安与庇护，却不能充当建筑测绘图。", tone: "decision" },
    { id: "layers-h", type: "heading", level: 2, text: "哪些属于杜甫，哪些属于他的身后记忆？" },
    { id: "layers-p", type: "paragraph", text: "馆方把杜甫在成都的时期界定为759至765年，其中与草堂相关的生活约三年九个月，并指出他在四川留下二百四十余首诗。这些是人物和文学史事实，却不能证明今天所见木柱、瓦片或茅草由杜甫亲手接触过。" },
    { id: "layers-table", type: "table", caption: "一座博物馆里的四层证据", columns: ["层次", "能说明什么", "不能证明什么"], rows: [["历史", "杜甫在成都的行止、人际和写作", "某座现存建筑就是他的原宅"], ["考古", "遗址在唐代存在活动与占用", "每处遗存都归杜甫本人所有"], ["纪念史", "后人怎样为杜甫塑造纪念空间", "八世纪茅屋的精确外观"], ["旅游展示", "便于理解的茅屋场景和游线", "唐代原构或某首诗的逐字复原"]] },
    { id: "bio-h", type: "heading", level: 2, text: "为什么成都在杜甫生平中重要？" },
    { id: "bio-p1", type: "paragraph", text: "经历动荡和辗转后，杜甫于759年来到成都，在友人帮助下于浣花溪附近安顿。相对稳定的居所，使他得以从日常家庭生活出发，书写邻里、天气、疾病、远方战乱与道德关怀。草堂的重要性，不在于屋顶有没有保存下来，而在于一处暂时的家成为持续观察世界的位置。" },
    { id: "bio-p2", type: "paragraph", text: "《茅屋为秋风所破歌》常被用来连接诗人与茅屋。它确实提供了受损、脆弱和关怀他人的文学经验，但诗歌会选择、组织并放大经验。可以概括它对庇护的关注，不能把每句诗变成平面图，更不能断言复建房间就是某一诗句的写作现场。" },
    { id: "arch-h", type: "heading", level: 2, text: "先看不那么醒目的唐代遗存" },
    { id: "arch-p1", type: "paragraph", text: "馆方记录显示，草堂在2001年发现唐代遗存，之后进行了保护和展示。这是现场连接杜甫生活年代最强的物质证据。它可能不如红墙厅堂和茅屋醒目，所以先读发掘说明：遗迹类型是什么，考古学家怎样断代，你看到的是暴露原物、保护后的轮廓、模型还是图片。" },
    { id: "arch-p2", type: "paragraph", text: "考古也有边界。唐代墙基、水井或生活层可以证明此地在唐代有人活动；要进一步证明属于杜甫个人，还需要更完整的证据链。不要从“唐代”直接跳到“杜甫摸过”。若考古区因保护暂时关闭，可用官方平面图和馆方说明，把结论停在“地点与时代”层面。" },
    { id: "axis-h", type: "heading", level: 2, text: "把纪念轴线当作“后人怎样记住杜甫”的历史来读" },
    { id: "axis-p1", type: "paragraph", text: "大廨、诗史堂、工部祠等命名空间，属于草堂漫长的纪念制度史。今天轴线格局的重要基础来自1500年和1811年的大规模营建。这些日期并非令人失望的附注，而是说明明清时期如何把诗人的形象、评价与身份变成可以行走的空间。" },
    { id: "axis-list", type: "list", ordered: true, items: ["到大廨先问：它介绍的是诗人本人、地点，还是纪念机构？", "在诗史堂，分清“以诗证史”的后世评价与建筑本身的年代。", "到工部祠，注意“工部”这一称谓如何成为杜甫身后身份的一部分。", "每遇一座看起来很古的门厅，先找建造或维修年代，再判断。"] },
    { id: "hut-h", type: "heading", level: 2, text: "到了复建茅屋，应该看什么？" },
    { id: "hut-p1", type: "paragraph", text: "把它看成解释工具。茅草、低矮轮廓、竹林与小房间，能迅速把“不稳定的家庭庇护”变得可见；正因为它容易理解，也最容易盖过其他证据。笔记和图片请写“复建茅屋景区”，不要写成“760年建成的杜甫故居”。" },
    { id: "hut-p2", type: "paragraph", text: "再反过来检验展示：诗歌表达了暴露、家庭压力与对他人的关切；场景设计选择呈现了什么？水、食物、劳动与书写的线索，是由标签提供，还是你自己补上的？目的不是指责复建“虚假”，而是辨认它提供的是哪一种知识。" },
    { id: "poetry-h", type: "heading", level: 2, text: "怎样在现场读诗，又不把诗误当物证？" },
    { id: "poetry-p", type: "paragraph", text: "不要试图一次读完整个杜甫作品体系，选一条主题即可：庇护、溪流、家人、远方战争或照顾他人的伦理。先核对馆方给出的中文篇名与作者，再使用合法取得的译文。现代译本通常受版权保护，拍下整块译文展板不等于可以公开转载。诗歌提供视角和语言；考古记录与建筑档案负责物质判断。" },
    { id: "route-h", type: "heading", level: 2, text: "一条遇到闭馆也能继续的参观顺序" },
    { id: "route-table", type: "table", caption: "按问题走，不写死分钟", columns: ["停点", "要问的问题", "不可用时"], rows: [["官方地图", "考古、纪念轴线和茅屋分别在哪里？", "拍地图或询问当天游线"], ["唐代遗存", "原物、轮廓、模型和标签分别是什么？", "改读馆方考古说明"], ["纪念厅堂", "是哪一代人塑造了这个空间？", "只读外部说明，不假定室内开放"], ["碑亭与茅屋", "哪些是纪念，哪些是复建？", "在允许路线外观察，不跨越围挡"], ["最后一处展陈", "分层后，哪一项判断改变了？", "在室外写四行总结"]] },
    { id: "misread-h", type: "heading", level: 2, text: "离开前，不要带走这三种误解" },
    { id: "misread-list", type: "list", ordered: false, items: ["“茅屋是复建，所以整座草堂没有价值。”状态标清的复建可以帮助理解，纪念史与考古另有价值。", "“看起来古老的都是明清原构。”现场还包含维修、替换与后来的展示，判断必须落实到具体构件。", "“诗歌证明复建完全准确。”文学记录并重组经验，不是测量档案。"] },
    { id: "who-h", type: "heading", level: 2, text: "谁最适合把草堂列为重点？" },
    { id: "who-p", type: "paragraph", text: "如果一首诗、一个作家的生活，或“文化记忆怎样形成”足以支撑你连续看几个节点，这里值得优先。它也适合第一次学习中国纪念地分层的旅客。若你只想看完整故居、紧凑文物展或唐诗通史，可缩短或跳过。出发前应以馆方官网确认开放、预约、无障碍路线和临时闭室。" },
    { id: "links", type: "internal-links", title: "继续按证据读地点", items: [{ label: "原存、修缮、重建还是迁建？", href: "/zh/guides/how-to-read-heritage-sites-in-china/", description: "从草堂个案进入全国性的遗产干预判断方法。" }, { label: "怎样参观考古遗址博物馆", href: "/zh/guides/how-to-visit-an-archaeological-site-museum/", description: "把原址遗迹、标签和出土物重新连起来。" }, { label: "沿鲁迅作品走读绍兴", href: "/zh/guides/luxun-shaoxing-literary-walk/", description: "比较另一处作家纪念景观，不把小说误当成地点平面图。" }, { label: "比较中国三大文学名楼", href: "/zh/guides/three-literary-towers-comparison/", description: "看后世建筑怎样把诗歌与记忆变成不同的参观任务。" }, { label: "带着背景看川剧变脸", href: "/zh/guides/sichuan-opera-face-changing-with-context/", description: "从成都文学记忆继续理解一项仍在实践的表演传统。" }] },
    { id: "sources", type: "sources", title: "已核对的核心机构来源", items: [{ label: "成都杜甫草堂博物馆", url: "https://www.cddfct.cn/", publisher: "成都杜甫草堂博物馆", reviewedAt: "2026-08-20" }, { label: "草堂沿革与场馆介绍", url: "https://www.cddfct.cn/go-c11.htm", publisher: "成都杜甫草堂博物馆", reviewedAt: "2026-08-20" }, { label: "杜甫成都时期", url: "https://www.cddfct.cn/go-a116.htm", publisher: "成都杜甫草堂博物馆", reviewedAt: "2026-08-20" }, { label: "唐代遗址", url: "https://www.cddfct.cn/go-a1133.htm", publisher: "成都杜甫草堂博物馆", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

const ko = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "청두 두보초당에서 가장 ‘시인의 옛집’처럼 보이는 곳부터 판단을 늦춰야 합니다. 지금의 초가는 당대 집이 그대로 남은 것이 아닙니다. 한 정원에는 네 장소가 겹칩니다. 기록으로 확인되는 두보의 청두 생활, 발굴된 당대 유구, 후대에 거듭 조성한 기념 경관, 그리고 초가 생활을 이해하도록 만든 현대 재현입니다. 이 층을 나누면 장소의 의미가 줄어드는 것이 아니라 더 또렷해집니다." },
    { id: "answer", type: "callout", title: "바로 답하면", body: "온전한 당대 고택이 아니라 문학 기념지로 방문하세요. Homeground가 권하는 순서는 공식 지도로 방향 잡기, 고고학 증거 읽기, 후대 기념 축 따라가기, 재현 초가로 마무리하기입니다. 시는 불안정한 거처와 보호의 의미를 상상하게 하지만 건축 실측도는 아닙니다.", tone: "decision" },
    { id: "layers-h", type: "heading", level: 2, text: "어디까지가 두보이고 어디부터가 사후의 기억일까요?" },
    { id: "layers-p", type: "paragraph", text: "박물관은 두보의 청두 시기를 759~765년으로 설명하고, 초당과 관련된 생활을 약 3년 9개월로 봅니다. 쓰촨 시기에 남긴 시도 240여 수라고 소개합니다. 이는 전기와 문학사의 사실이지만, 눈앞의 목재·기와·초가를 두보가 직접 만졌다는 뜻은 아닙니다." },
    { id: "layers-table", type: "table", caption: "한 박물관의 네 증거 층", columns: ["층", "알 수 있는 것", "증명하지 못하는 것"], rows: [["역사", "두보의 청두 행적·관계·창작", "현존 건물이 그의 원래 집이라는 주장"], ["고고학", "이 장소의 당대 활동과 점유", "모든 유구가 두보 개인 소유였다는 주장"], ["기념의 역사", "후대가 두보를 기억하는 공간을 만든 방식", "8세기 초가의 정확한 외형"], ["관광 해석", "이해하기 쉬운 초가 장면과 관람 동선", "당대 원형 부재나 시 한 편의 문자 그대로의 복원"]] },
    { id: "bio-h", type: "heading", level: 2, text: "두보의 삶에서 청두는 왜 중요할까요?" },
    { id: "bio-p1", type: "paragraph", text: "전란과 이동을 거친 두보는 759년 청두에 도착해 지인의 도움으로 완화계 부근에 거처를 마련했습니다. 비교적 안정된 시기였기에 가족생활, 이웃, 날씨, 질병, 먼 곳의 전쟁과 윤리적 책임을 일상에서 바라보며 쓸 수 있었습니다. 초당은 지붕이 남아서가 아니라 임시의 집이 지속적인 관찰 지점이 되었다는 점에서 중요합니다." },
    { id: "bio-p2", type: "paragraph", text: "《茅屋为秋风所破歌》, 곧 흔히 ‘가을바람에 초가가 무너진 노래’로 옮기는 작품은 시인과 집을 연결합니다. 손상과 취약함, 타인을 향한 돌봄을 문학적으로 보여 주지만 시는 경험을 선택하고 배열하며 확장합니다. 한 구절을 평면도로 바꾸거나 재현 방을 특정 시구의 집필 장소라고 단정하지 마세요." },
    { id: "arch-h", type: "heading", level: 2, text: "눈에 덜 띄는 당대 유구부터 보세요" },
    { id: "arch-p1", type: "paragraph", text: "박물관 기록에 따르면 2001년 당대 유구를 발굴한 뒤 보호·전시했습니다. 이것이 두보가 살았던 시대와 현장을 잇는 가장 강한 물질 증거입니다. 붉은 전각이나 초가보다 조용해 보일 수 있으므로 먼저 발굴 설명을 읽으세요. 유구의 종류, 고고학적 연대, 노출 원물인지 보호 윤곽인지 모형·사진인지를 적어 두면 됩니다." },
    { id: "arch-p2", type: "paragraph", text: "고고학에도 한계가 있습니다. 당대 벽기초·우물·생활층은 이곳의 당대 활동을 확인하지만 개인 소유를 말하려면 다른 증거가 더 필요합니다. ‘당대’에서 곧바로 ‘두보가 만진 것’으로 뛰지 마세요. 보존 때문에 구역이 닫혔다면 공식 평면도와 설명으로 장소-시대 수준의 결론만 유지합니다." },
    { id: "axis-h", type: "heading", level: 2, text: "기념 축을 ‘후대가 두보를 기억한 역사’로 읽으세요" },
    { id: "axis-p1", type: "paragraph", text: "다셰(大廨), 스스탕(诗史堂), 궁부츠(工部祠) 같은 공간은 초당의 긴 기념 제도사에 속합니다. 오늘의 축선은 1500년과 1811년의 큰 조영에서 중요한 형태를 얻었습니다. 이 연대는 실망스러운 각주가 아니라 명·청대 사람들이 두보의 평가와 신분을 걸을 수 있는 공간으로 만든 증거입니다." },
    { id: "axis-list", type: "list", ordered: true, items: ["다셰에서는 인물·장소·기념기관 중 무엇을 소개하는지 묻습니다.", "스스탕에서는 두보의 시를 ‘시로 쓴 역사’로 보는 후대 평가와 건물 연대를 분리합니다.", "궁부츠에서는 ‘공부’라는 관직명이 사후 기억의 이름이 된 과정을 봅니다.", "오래되어 보이는 문과 전각마다 건립·보수 연대를 먼저 찾습니다."] },
    { id: "hut-h", type: "heading", level: 2, text: "재현 초가에서는 무엇을 해야 할까요?" },
    { id: "hut-p1", type: "paragraph", text: "초가를 해석 장치로 보세요. 짚 지붕, 낮은 윤곽, 대나무와 작은 방은 불안정한 생활공간을 빠르게 이해시킵니다. 바로 그 명료함 때문에 다른 증거를 덮기도 합니다. 메모와 캡션에는 ‘재현 초가 구역’이라고 쓰고 ‘760년에 지은 두보의 집’이라고 쓰지 않습니다." },
    { id: "hut-p2", type: "paragraph", text: "그다음 재현에 질문을 돌려주세요. 시가 표현한 노출, 가족의 압박, 타인에 대한 관심 중 무엇을 장면이 골랐습니까? 물·음식·노동·글쓰기의 단서는 라벨이 알려 줍니까, 내가 덧붙인 상상입니까? 재현을 가짜라고 몰아붙이는 것이 아니라 어떤 지식을 주는지 분류하는 작업입니다." },
    { id: "poetry-h", type: "heading", level: 2, text: "현장에서 시를 읽되 물증으로 오해하지 않는 법" },
    { id: "poetry-p", type: "paragraph", text: "두보 작품 전체를 한 번에 이해하려 하지 말고 보호, 시냇물, 가족, 멀리 있는 전쟁, 돌봄의 윤리 중 한 주제를 고르세요. 박물관의 중국어 제목과 저자를 먼저 확인하고 합법적으로 구한 번역을 이용합니다. 현대 번역은 저작권 보호 대상이므로 번역 패널 전체를 찍었다고 공개 전재할 권리가 생기지 않습니다. 시는 시선과 언어를, 고고학과 건물 기록은 물질 판단을 제공합니다." },
    { id: "route-h", type: "heading", level: 2, text: "폐쇄 구간이 있어도 작동하는 관람 순서" },
    { id: "route-table", type: "table", caption: "고정 시간보다 질문으로 걷기", columns: ["지점", "질문", "이용 불가 시"], rows: [["공식 지도", "고고학·기념 축·초가는 각각 어디인가?", "지도를 찍거나 당일 동선을 문의"], ["당대 유구", "원물·윤곽·모형·라벨 중 무엇인가?", "공식 고고학 설명으로 대체"], ["기념 전각", "어느 시대 사람들이 이 공간을 만들었나?", "외부 라벨만 읽고 실내 개방을 가정하지 않기"], ["비정·초가", "기념과 재현은 각각 무엇인가?", "허용된 길에서 보고 울타리를 넘지 않기"], ["마지막 전시", "층을 나눈 뒤 어떤 판단이 바뀌었나?", "밖에서 네 줄로 정리"]] },
    { id: "misread-h", type: "heading", level: 2, text: "이 세 오해는 남기지 마세요" },
    { id: "misread-list", type: "list", ordered: false, items: ["“초가가 재현이니 전체가 가치 없다.” 상태가 명확한 재현은 유용하고, 기념사와 고고학은 별도의 가치를 가집니다.", "“낡아 보이는 것은 모두 명·청대 원형이다.” 보수·교체·후대 전시가 섞이므로 구성요소를 특정해야 합니다.", "“시가 재현의 정확성을 증명한다.” 문학은 경험을 기록하면서 다시 구성하지 실측 기록이 아닙니다."] },
    { id: "who-h", type: "heading", level: 2, text: "누가 두보초당을 우선해야 할까요?" },
    { id: "who-p", type: "paragraph", text: "시 한 편, 작가의 생활, 문화적 기억의 형성 과정이 여러 지점을 이어 볼 충분한 이유라면 우선하세요. 중국 기념지의 층을 처음 배우는 여행자에게도 좋습니다. 온전한 고택, 압축된 유물전, 당나라 시 전체 입문을 원한다면 짧게 보거나 건너뛰어도 됩니다. 운영시간·예약·무장애 동선·임시 폐실은 출발 직전 공식 홈페이지에서 확인하세요." },
    { id: "links", type: "internal-links", title: "증거로 장소 읽기 계속하기", items: [{ label: "원형 보존·보수·재건·이건 구분하기", href: "/ko/guides/how-to-read-heritage-sites-in-china/", description: "초당의 사례에서 전국 유산 개입 용어로 확장합니다." }, { label: "고고유적 박물관 방문법", href: "/ko/guides/how-to-visit-an-archaeological-site-museum/", description: "현장 유구, 라벨, 출토품을 과장 없이 연결합니다." }, { label: "루쉰의 글을 따라 사오싱 걷기", href: "/ko/guides/luxun-shaoxing-literary-walk/", description: "또 다른 작가 기념 경관을 비교하되 소설을 장소 도면으로 오해하지 않습니다." }, { label: "중국의 세 문학 누각 비교하기", href: "/ko/guides/three-literary-towers-comparison/", description: "후대 건축이 시와 기억을 서로 다른 방문 과제로 만드는 방식을 봅니다." }, { label: "맥락과 함께 쓰촨 변검 보기", href: "/ko/guides/sichuan-opera-face-changing-with-context/", description: "청두의 문학 기억에서 현재도 이어지는 공연 전통으로 확장합니다." }] },
    { id: "sources", type: "sources", title: "검토한 핵심 기관 자료", items: [{ label: "청두 두보초당박물관", url: "https://www.cddfct.cn/", publisher: "청두 두보초당박물관", reviewedAt: "2026-08-20" }, { label: "초당 연혁과 장소 소개", url: "https://www.cddfct.cn/go-c11.htm", publisher: "청두 두보초당박물관", reviewedAt: "2026-08-20" }, { label: "두보의 청두 시기", url: "https://www.cddfct.cn/go-a116.htm", publisher: "청두 두보초당박물관", reviewedAt: "2026-08-20" }, { label: "당대 고고 유구", url: "https://www.cddfct.cn/go-a1133.htm", publisher: "청두 두보초당박물관", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

export const bodies = { en, zh, ko };
