import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "주자자오, 퉁리와 우전은 운하, 돌다리와 장난 건축을 공유하지만 서로 다른 여행을 해결합니다. 주자자오는 상하이에서 부담이 낮은 당일 수향, 퉁리는 주민 마을과 중요한 고전 정원을 묶고, 우전은 동·서 구역과 야간 운영이 있는 완성도 높은 숙박 환경입니다. 이동 부담과 전체 일정에 빠진 경험으로 하나만 고르세요." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "상하이에서 간단한 당일이면 주자자오, 쑤저우와 퇴사원 그리고 조용한 운하 조직이 중요하면 퉁리, 1박이 가능하고 연출된 저녁 환경을 가치 있게 보면 우전을 고릅니다. 수향 역사가 여행의 주제가 아니라면 비슷한 다리 사진을 위해 이틀을 쓰지 않아도 됩니다." },
  { id: "matrix-heading", type: "heading", level: 2, text: "세 마을 결정표" },
  { id: "matrix", type: "table", caption: "마을 하나, 역할 하나", columns: ["마을", "최적 사용", "주 대가"], rows: [["주자자오", "상하이 반일/당일, 도시 간 부담 최소", "당일 혼잡과 낮은 숙박 필요"], ["퉁리", "쑤저우 연계 당일/조용한 1박, 운하와 퇴사원", "별도 이동과 현행 장소 확인"], ["우전", "목적성 있는 1박, 서책 야경과 큰 리조트형 수향", "가장 큰 투자; 구역표와 환승이 짧은 반일에 비효율"]] },
  { id: "zhujiajiao-heading", type: "heading", level: 2, text: "주자자오: 접근성과 거리 생활" },
  { id: "zhujiajiao", type: "paragraph", text: "상하이 정부는 주자자오를 도심에서 약 40km 떨어진 역사문화 구역으로 소개하며 다리, 운하와 보존 건물을 설명합니다. 상하이 여행 체계 안에 있다는 점이 가장 큰 장점입니다. 호텔이나 도시 간 철도를 더하지 않고 수향 질감을 원할 때 좋습니다. 입구 첫 다리의 혼잡을 벗어나고 유료 실내 하나만 골라 귀환 시간을 남기세요." },
  { id: "tongli-heading", type: "heading", level: 2, text: "퉁리: 정원으로 수향을 읽기" },
  { id: "tongli", type: "paragraph", text: "쑤저우 정부는 퉁리를 운하가 섬으로 나누고 오래된 다리가 잇는 마을로 설명합니다. 퇴사원은 쑤저우 고전정원 세계유산에 포함됩니다. 따라서 다리만 보는 것보다 개인 정원, 주택, 골목과 수로가 생활 공간을 이루는 방식을 읽는 구체적 임무가 있습니다. 쑤저우가 일정에 있을 때 가장 자연스럽습니다." },
  { id: "wuzhen-heading", type: "heading", level: 2, text: "우전: 저녁에서 아침으로 바뀌는 경험" },
  { id: "wuzhen", type: "paragraph", text: "우전 공식 관광 사이트는 동책과 더 큰 서책을 구분하고 서책을 숙박, 배, 서비스와 야간 조명을 가진 관람·휴식 환경으로 개발했다고 설명합니다. 이 관리된 완성도가 어떤 이에게 장점, 다른 이에게 대가입니다. 밤과 아침을 보기 위해 선택하고 가장 상업성이 없거나 손대지 않은 곳이라고 말하지 마세요." },
  { id: "what-you-miss", type: "comparison", title: "전체 일정에 없는 층을 보충하세요", columns: [{ heading: "쑤저우도, 숙박 여유도 없음", body: "주자자오가 일정 파괴 없이 수향 하루를 추가합니다." }, { heading: "이미 쑤저우 정원 방문", body: "퉁리가 정원·운하 이야기를 확장할 수 있으나 반복이면 건너뜁니다." }, { heading: "느린 1박 필요", body: "우전이 낮–밤 변화를 가장 강하게 주며 일찍 도착해 이동 가치를 회수해야 합니다." }] },
  { id: "day-overnight-heading", type: "heading", level: 2, text: "당일 또는 숙박" },
  { id: "day-overnight", type: "table", caption: "숙박 결정", columns: ["패턴", "맞는 곳", "이유"], rows: [["상하이 반일", "주자자오", "늦은 시작도 회복하며 호텔 이동 없음"], ["쑤저우 기반 하루", "퉁리", "도시·정원 맥락이 가까움"], ["전용 1박", "우전", "조명과 이른 거리가 가치 핵심"], ["큰 짐 환승일", "대체로 없음", "보관·환승·체크인이 유산 방문을 압도"]] },
  { id: "authenticity", type: "callout", title: "‘진정성’을 한 숫자로 평가하지 마세요", tone: "neutral", body: "세 곳 모두 주민, 보전, 관광과 상업이 다른 비율로 만든 살아 있는 장소입니다. 우전은 계획된 보전·관광 모델을 공개하고, 퉁리는 주민 마을과 유료 유산을 함께 가지며, 주자자오는 열린 골목과 관리 관광지를 섞습니다. 관광이 없었던 척할 곳보다 이해에 도움이 되는 형식을 고르세요." },
  { id: "transport", type: "list", items: ["마을을 먼저 고르고 교통을 삽니다. 비슷한 역과 경관 입구는 같지 않습니다.", "도시 간 열차뿐 아니라 마지막 도로/지하철과 귀환을 확인합니다.", "우전에서는 동책·서책·방문자센터·숙박 체크인 지점을 구분합니다.", "퉁리에서는 정원과 유료 장소의 당일 개방을 확인합니다.", "주자자오에서는 저녁 혼잡과 날씨를 견디는 상하이 귀환을 둡니다."] },
  { id: "failure", type: "table", caption: "문제와 회복", columns: ["문제", "대응"], rows: [["비", "덮인 실내와 짧은 운하 동선; 젖은 돌 주의"], ["유료 장소 폐쇄", "마을 산책과 공식 대안 하나; 비공식 우회 금지"], ["너무 붐빔", "입구 첫 다리에서 벗어나고 쇼핑 축소"], ["환승 지연", "호텔/마지막 귀환을 보호하고 유료 구역 강행 금지"], ["비슷한 마을을 이미 봄", "고유 정원·운영·역사만 보거나 둘째를 뺌"]] },
  { id: "boundary", type: "callout", title: "선택은 한 비교 페이지가 소유합니다", tone: "decision", body: "‘상하이 근처 최고의 수향’, ‘주자자오 vs 퉁리’, ‘우전 숙박 가치’는 이 페이지로 합칩니다. 얇은 쌍대 비교를 만들지 않고 상하이–쑤저우–항저우–난징 도시 순서를 대체하지 않습니다." },
  { id: "links", type: "internal-links", title: "장난 루트 연결", items: [{ label: "상하이 도시 허브", href: "/ko/destinations/shanghai/", description: "수향이 다른 상하이 하루보다 나은지 봅니다." }, { label: "상하이·쑤저우·항저우·난징 순서", href: "/ko/guides/shanghai-suzhou-hangzhou-nanjing-route-order/", description: "도시와 숙박을 먼저 배치합니다." }, { label: "쑤저우 정원 읽기", href: "/ko/guides/how-to-read-a-suzhou-garden/", description: "퉁리를 다르게 만드는 정원 언어를 봅니다." }, { label: "상하이–항저우 교통", href: "/ko/guides/shanghai-hangzhou-transport-route/", description: "도시 간 이동과 수향 우회를 분리합니다." }, { label: "일정이 너무 바쁜가요?", href: "/ko/guides/is-your-china-itinerary-too-rushed/", description: "추가 환승의 실제 가치를 시험합니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "주자자오 역사문화 구역", url: "https://english.shanghai.gov.cn/en-HeritageZones/20240827/66903de4b44047a5aeb1284a2148fc09.html", publisher: "상하이시 인민정부", reviewedAt: "2026-08-22" }, { label: "퉁리 고진", url: "https://english.suzhou.gov.cn/szsenglish/sz5ajjq/201911/5212c69295364f8cb2c55ee5d5f13dcc.shtml", publisher: "쑤저우시 인민정부", reviewedAt: "2026-08-22" }, { label: "우전 공식 소개와 보전 모델", url: "https://www.wuzhen.com.cn/web/introduction?id=2", publisher: "우전 관광", reviewedAt: "2026-08-22" }, { label: "우전 현행 방문·티켓 정보", url: "https://www.wuzhen.com.cn/web/traver/info", publisher: "우전 관광", reviewedAt: "2026-08-22" }, { label: "대표 사진: Chensiyuan의 주자자오, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:1_zhujiajiao_ancient_water_town_2023.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
