import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "징더전은 기념품 가게에 둘러싸인 박물관 하나가 아닙니다. 도자기 이야기는 공간적입니다. 타오양리와 어요는 고고학, 황실 생산과 옛 골목을 역사 중심에 둡니다. 타오시촨은 20세기 도자기 공장을 산업유산과 현대 창작 구역으로 바꿉니다. 싼바오는 작업실, 레지던시와 농촌 창작 공간이 계곡에 퍼져 있습니다. 어떤 도자기 도시를 만날지 먼저 고르세요." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "하루라면 타오양리/어요와 타오시촨을 연결하세요. 옛 도시 생산사를 먼저 읽고 산업유산이 오늘의 창작을 담는 모습을 봅니다. 싼바오는 별도 반나절, 확인된 작업실 약속 또는 계곡 창작 생태라는 강한 목적이 있을 때만 추가합니다. 고고학이 핵심이면 어요 구역을 깊게 보고 전용 글로 박물관을 읽으세요." },
  { id: "matrix-heading", type: "heading", level: 2, text: "세 구역은 도자기 역사의 세 층" },
  { id: "matrix", type: "table", caption: "과제로 구역 선택", columns: ["구역", "주 과제", "흔한 오류"], rows: [["타오양리/어요", "황실 가마 고고학, 박물관 건축과 옛 생산 동네", "새 박물관을 전체 유적으로 보거나 모든 골목을 손대지 않은 작업실로 봄"], ["타오시촨", "산업유산, 현대 디자인, 시장과 옛 공장 재사용", "고대 가마 구역으로 부르거나 매일 시장을 가정"], ["싼바오", "분산 작업실·레지던시와 농촌 창작 생태", "한 번에 걷는 폐쇄 관광지로 생각"]] },
  { id: "imperial-heading", type: "heading", level: 2, text: "타오양리: 고고학과 옛 도시부터" },
  { id: "imperial", type: "paragraph", text: "징더전 정부는 타오양리를 약 3.2㎢ 역사관광구역으로 소개하며 국가 보호 어요 유적, 어요박물관, 골목, 길드회관·도자기 상점, 작업장 흔적과 산업유산을 포함한다고 합니다. 핵심은 연속과 변화입니다. 황실 생산, 도시 생활, 고고학, 복원과 현대 전시가 함께 있지만 같은 시대는 아닙니다." },
  { id: "imperial-route", type: "list", ordered: true, items: ["집중력이 좋을 때 고고학과 박물관부터 봅니다.", "전시로 출토물, 재건과 신축 디자인을 구분합니다.", "주변 골목은 범위 있는 한 묶음만 걷습니다.", "물건, 가마 흔적, 현대 해석과 상업 작업장을 구분해 기록합니다.", "두 번째 박물관이 타오시촨 대비를 지우기 전에 이동합니다."] },
  { id: "taoxichuan-heading", type: "heading", level: 2, text: "타오시촨: 시장보다 공장을 먼저 읽기" },
  { id: "taoxichuan", type: "paragraph", text: "시 정부는 타오시촨 1단계가 옛 우주 도자기공장을 중심으로 산업유산 보전·재사용을 통해 만들어졌다고 설명합니다. 공장 규모, 굴뚝, 생산건물과 그 안의 갤러리·상점·작업실을 보세요. 창작시장은 현재 제작자를 더하지만 날짜, 판매자와 날씨가 변하므로 소셜 일정에 전부 의존하지 않습니다." },
  { id: "sanbao-heading", type: "heading", level: 2, text: "싼바오: 마지막 들름이 아닌 계곡 계획" },
  { id: "sanbao", type: "callout", title: "이름 있는 목적지를 갖고 가세요", tone: "decision", body: "정부는 싼바오를 문화, 디자인, 작업실과 숙박이 모인 국제 도자기 계곡으로 설명하지만 시설은 분산되어 있습니다. 방문을 확인한 작업실·기관·공공공간 한두 곳을 고르고 정확한 중국어 주소를 저장하세요. 기사에게 ‘싼바오’만 말하고 완전한 보행 명소를 기대하지 마세요." },
  { id: "day-heading", type: "heading", level: 2, text: "인기보다 시대로 하루를 배열" },
  { id: "day", type: "table", caption: "하루 순서", columns: ["구간", "질문", "삭제"], rows: [["타오양리/어요", "황실 생산은 옛 도시를 어떻게 만들고 고고학은 지금 어떻게 보이나?", "박물관/유적 한 동선과 제한된 골목"], ["이동·식사", "실제 교통에서 구역은 얼마나 떨어져 있나?", "약속 없는 먼 작업실 금지"], ["타오시촨", "현대 공장이 창작 기반으로 어떻게 변했나?", "산업/갤러리 하나, 시장은 보너스"], ["저녁", "현행 프로그램이 다른 층을 주나?", "미확인 또는 쇼핑 반복이면 종료"]] },
  { id: "two-day", type: "comparison", title: "둘째 날이 있다면", columns: [{ heading: "작업실·제작자", body: "확인 약속과 싼바오/생산 구역을 쓰고 대화 시간을 둡니다. 사람·과정·디자인 촬영은 허락부터." }, { heading: "박물관·고고학", body: "어요 해석에 깊이를 더하고 보완 컬렉션 하나, 재료·소성·용도로 도자기를 읽습니다." }, { heading: "근거 있는 구매", body: "특정 기법 제작자나 시장을 고르고 작가·소성·포장을 묻습니다. 가격은 연대·진위를 증명하지 않습니다." }] },
  { id: "buying", type: "callout", title: "아름답다고 골동품·지역산·수공예는 아닙니다", tone: "warning", body: "누가 만들고 어디서 구웠는지, 전사인지 손그림인지, 포장 방법을 물으세요. 수출·문화재 조언을 판매 말만으로 믿지 마세요. 이 글은 감정, 판매자 순위나 워크인 접수를 보장하지 않습니다." },
  { id: "failure", type: "table", caption: "문제와 회복", columns: ["문제", "대응"], rows: [["박물관/시장 폐쇄", "구역 공간 이야기를 남기고 공식 대안 하나; 잠긴 곳 우회 금지"], ["싼바오 핀이 모호", "멈추고 이름 있는 장소에 연락·정확 주소; 미확정이면 도시 복귀"], ["비", "실내 박물관·산업유산 보호, 확인된 작업실만"], ["쇼핑이 일정 소모", "구매 시간을 정하고 역사 질문으로 복귀"], ["‘고대’ 주장 충돌", "급하게 사지 말고 독립 전문가 근거"]] },
  { id: "boundary", type: "callout", title: "어요 전용 글과의 canonical 경계", tone: "neutral", body: "이 글은 타오양리/어요, 타오시촨과 싼바오의 공간 선택을 담당합니다. 어요 전용 글은 고고학, 박물관 해석과 깊은 읽기를 담당합니다. 시장·골목·작업실별 얇은 페이지를 만들지 않습니다." },
  { id: "links", type: "internal-links", title: "도자기 루트 이어가기", items: [{ label: "중국 고속철 첫 이용", href: "/ko/guides/china-high-speed-train-first-time-guide/", description: "도시 구역 전에 철도 도착을 처리합니다." }, { label: "야간열차와 주간 고속철", href: "/ko/guides/china-night-train-or-daytime-high-speed-rail/", description: "징더전 첫날을 실제로 쓸 수 있는 환승을 고릅니다." }, { label: "오픈조 항공 동선", href: "/ko/guides/china-open-jaw-flights-route-planning/", description: "같은 도시로 되돌아가느라 도자기 도시 체류를 압축하지 않습니다." }, { label: "중국 공휴일", href: "/ko/guides/china-public-holidays-travel-calendar/", description: "하루 동선을 확정하기 전 휴관과 혼잡 압력을 확인합니다." }, { label: "일정이 너무 바쁜가요?", href: "/ko/guides/is-your-china-itinerary-too-rushed/", description: "농촌 작업실 하루가 이동 예산에 맞는지 봅니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "타오양리 어요 관광구역", url: "https://www.jdz.gov.cn/zjcd/mljdz/sj/t932856.shtml", publisher: "징더전시 인민정부", reviewedAt: "2026-08-22" }, { label: "타오시촨 창작 구역", url: "https://www.jdz.gov.cn/zjcd/mljdz/sj/t932854.shtml", publisher: "징더전시 인민정부", reviewedAt: "2026-08-22" }, { label: "싼바오와 도시 도자기 구역", url: "https://jdz.gov.cn/zwzx/jrcd/t1092010.shtml", publisher: "징더전시 인민정부", reviewedAt: "2026-08-22" }, { label: "대표 사진: Zhu Pei의 어요박물관, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:01-Jingdezhen_Imperial_Kiln_Museum.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
