import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Do not choose a hotel in China by asking whether an international chain is automatically safer or a local hotel is automatically better value. Choose the exact property that can document the room, foreign-passport check-in, payment, arrival route and problem-resolution process your trip needs. A familiar brand can make documentation or escalation easier at some branches; a local hotel can have the better location and a fully workable front-desk operation. Neither label answers the booking on its own.",
    },
    {
      id: "scope",
      type: "paragraph",
      text: "This page covers the property-choice method. The separate foreign-guest guide covers the legal rule, accommodation registration and refusal-recovery sequence. The hotel-value guide covers prices; the metro guide covers exit-level walking checks. Here, ‘international’ and ‘local’ are discovery labels only. The final decision is about one named branch, one room category, one booking channel and one arrival.",
    },
    {
      id: "four-records",
      type: "table",
      caption: "Separate the four records before comparing hotels",
      columns: ["Record", "What it can establish", "What it cannot establish"],
      rows: [
        ["Brand or group", "Reservation, loyalty or service channels", "That this branch has your room or can execute check-in"],
        ["Exact property", "Published address, facilities, hours and contact", "That an old page remains accurate"],
        ["Registered operator", "The business identity, if correctly matched", "Room quality, language or remedy"],
        ["Booking channel", "Live terms, payment, cancellation and support", "The law or the night desk's response"],
      ],
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "Start with the part of the trip that cannot fail",
    },
    {
      id: "decision-matrix",
      type: "table",
      caption: "Use risk and evidence, not brand origin",
      columns: ["Trip condition", "Evidence to prioritise", "Decision effect"],
      rows: [
        ["First night or arrival after 22:00", "Staffed desk, written booking hold and duty contact", "Choose whichever proves all three"],
        ["Children, older travellers or much luggage", "Beds, step route, drop-off and replacement support", "Verified usability beats vague space"],
        ["Early train or fixed appointment", "Correct branch, Chinese address and door-to-door route", "Location can defeat familiarity"],
        ["Business paperwork or complex deposit", "Issuing entity, invoice, card network and deposit terms", "Prefer the documented process"],
        ["Specific accessibility need", "Measured curb-to-room and bathroom evidence", "Use the accessible-room method, not either label"],
      ],
    },
    {
      id: "short-answer",
      type: "callout",
      title: "The useful default",
      tone: "decision",
      body: "When two properties fit the route equally, choose the one that gives clearer written, branch-specific evidence and a usable recovery channel. That may be an international chain on one trip and a local hotel on another. Familiarity is a tiebreaker only after the actual stay works.",
    },
    {
      id: "verification-heading",
      type: "heading",
      level: 2,
      text: "Run one verification chain for both properties",
    },
    {
      id: "verification-chain",
      type: "list",
      ordered: true,
      items: [
        "Record the exact Chinese branch name, address, telephone and map pin; similar names are not interchangeable.",
        "Contact the property, not only the group. Give dates, arrival time, group size and each foreign guest’s valid original document.",
        "Name the room category; confirm beds, occupancy, smoking status, window, connecting room and extra bed.",
        "Ask whether that desk can register every foreign guest. Save the reply; a website or platform label is not law.",
        "Confirm balance and deposit methods, including the international card networks accepted.",
        "Confirm arrival-time staffing, late-arrival hold, taxi drop-off and luggage storage.",
        "Identify the seller and read its cancellation and modification terms; the property, group and platform may control different parts of a failure.",
        "Keep replies, room terms and one confirmed backup offline. Recheck shortly before arrival.",
      ],
    },
    {
      id: "must-verify",
      type: "table",
      caption: "Turn broad promises into testable property facts",
      columns: ["Decision area", "Ask the exact property", "Do not infer from the label"],
      rows: [
        ["Room", "Which features belong to this category?", "International does not fix bed size; local does not mean small"],
        ["Foreign guests", "Who handles passport check-in then?", "A logo or guest tag is not the legal rule"],
        ["Payment", "Which networks and methods work; what deposit applies?", "A card icon does not prove authorisation"],
        ["Location", "Where does the taxi stop; what is the real route?", "An address or ‘near metro’ phrase is not an audit"],
        ["Support", "Who is on duty if the room is unavailable?", "A global hotline cannot create inventory"],
        ["Documents", "Which entity issues the receipt or invoice?", "Storefront and operator names may differ"],
      ],
    },
    {
      id: "property-examples",
      type: "callout",
      title: "Property pages are evidence about that property only",
      tone: "warning",
      body: "On August 13, 2026, the Four Points by Sheraton Qingtian page listed that property’s phone, check-in, card acceptance, 24-hour desk and Chinese and English service. A Huazhu page for Crystal Orange Beijing Qianmen listed its phone, address and payment methods and displayed ‘内宾’. Neither page proves what every Marriott or Huazhu property does. ‘内宾’ or a platform guest label is not law; obtain current branch confirmation and use the foreign-guest guide if needed.",
    },
    {
      id: "evidence-heading",
      type: "heading",
      level: 2,
      text: "Know what each piece of evidence is worth",
    },
    {
      id: "evidence-list",
      type: "list",
      items: [
        "A branch-and-date-specific written reply is strong operational evidence, not a guarantee against disruption.",
        "A current property page establishes published facilities and contacts; essential facts still need confirmation.",
        "The enterprise publicity system helps match an operator name, not service, inventory or foreign-guest execution.",
        "A confirmation proves the transaction, not the law or acceptance of a special request.",
        "Reviews reveal questions such as noise or access; they are not policy authority.",
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Two trips can produce opposite answers",
    },
    {
      id: "scenarios",
      type: "table",
      caption: "Apply the same method, then let the result differ",
      columns: ["Scenario", "Verified evidence", "Decision"],
      rows: [
        ["Family arriving at 00:30", "The international branch confirms staffing, passports, family bedding, payment and late hold; the local property gives a generic reply", "Choose the verified branch because responsibility for this arrival is documented—not because all international chains are safer"],
        ["Solo traveller with an early train", "A local hotel by the correct station confirms passports, desk, quiet room, luggage and map pin; the international branch adds a long transfer", "Choose the local hotel: evidence and route fit outweigh familiarity"],
      ],
    },
    {
      id: "flip-heading",
      type: "heading",
      level: 2,
      text: "Conditions that should change the conclusion",
    },
    {
      id: "flip-list",
      type: "list",
      items: [
        "Switch if foreign-passport handling is unconfirmed for your arrival time.",
        "Reconsider when beds, step-free access, non-smoking or connecting rooms remain requests rather than confirmed features.",
        "Switch when payment or deposit needs an unreliable method.",
        "Let location overturn brand preference when a fixed event or the slowest traveller makes the transfer material.",
        "Let the seller matter when the group cannot change or refund a third-party booking.",
        "Keep a backup when nobody accepts responsibility for a midnight problem.",
      ],
    },
    {
      id: "recovery-heading",
      type: "heading",
      level: 2,
      text: "When something fails, identify who controls that step",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "First actions when the stay does not match the record",
      columns: ["Failure", "Immediate action", "Evidence to keep"],
      rows: [
        ["Missing reservation or wrong branch", "Verify branch, date, name and channel; contact manager and seller before cancelling", "Confirmation, Chinese branch name, case number, reason"],
        ["Wrong room or missing essential", "Inspect before unpacking; take privacy-safe photos and request the confirmed room or written alternative", "Category, promise, photos, offered remedy"],
        ["Card or deposit fails", "Separate room charge from deposit; use a confirmed second method and obtain receipts", "Terminal message, slip, release terms"],
        ["Foreign-passport refusal", "Ask for the reason and manager, then use the dedicated refusal workflow", "Property message, booking and stated reason"],
        ["Unsafe or unusable room", "Request a change; if none is safe, move to a confirmed alternative", "Privacy-safe photos, timestamps, replacement receipts"],
      ],
    },
    {
      id: "channel-boundary",
      type: "paragraph",
      text: "The property controls the physical room and on-site response. The group can act only within its management and reservation system. The booking channel controls the transaction path it sold. For an unresolved consumer dispute, China’s 12315 route can receive complaints, but it does not produce a room for the night. For nationality-based refusal or registration questions, follow the separate official-channel workflow rather than treating an international brand as the backup plan.",
    },
    {
      id: "move-callout",
      type: "callout",
      title: "Set a safe-room deadline",
      tone: "decision",
      body: "With children, an older traveller, accessibility needs or a late hour, do not spend unlimited time proving which logo should have worked. Ask for the manager, create the support record, document that you arrived and should not be marked as a no-show, then move to a property that has confirmed check-in for the real arrival time. Preserve the dispute after everyone is safe.",
    },
    {
      id: "checklist-heading",
      type: "heading",
      level: 2,
      text: "Final property verification checklist",
    },
    {
      id: "checklist",
      type: "list",
      items: [
        "Chinese branch name, address, phone and map pin",
        "Room category, beds, occupancy and essential features",
        "Written foreign-guest and arrival-time confirmation",
        "Original valid travel document",
        "Payment network, balance, deposit and release",
        "Late hold, staffed desk and duty contact",
        "Drop-off, entrance, step route and luggage storage",
        "Seller, cancellation, modification and support",
        "Receipt or invoice issuer",
        "Privacy-safe offline confirmations",
        "One equally verified backup",
      ],
    },
    {
      id: "dynamic-note",
      type: "paragraph",
      text: "National accommodation, registration and consumer-service sources and the example property pages were reviewed on August 13, 2026. Property staffing, room configuration, payment terminals, group participation and published page wording can change. Recheck the exact branch shortly before arrival; Homeground does not certify either example property or any brand.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue the accommodation decision",
      items: [
        { label: "Where to stay in China", href: "/stay/", description: "Return to the accommodation collection." },
        { label: "Can foreigners stay at any hotel in China?", href: "/guides/foreigners-china-hotel/", description: "Use the dedicated registration and refusal-recovery guide." },
        { label: "Why are hotels in China so cheap?", href: "/guides/why-are-hotels-in-china-so-cheap/", description: "Compare like-for-like value." },
        { label: "Is the hotel really near the metro?", href: "/guides/china-hotel-near-metro/", description: "Audit the exit and walking route." },
        { label: "How to pay in China as a tourist", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Prepare a payment backup." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official and first-party sources",
      items: [
        { label: "Guide to Working and Living in China as Business Expatriates (2025)", url: "https://english.www.gov.cn/2025special/bizexpatsinchina2025", publisher: "State Council of the People's Republic of China", reviewedAt: "2026-08-13" },
        { label: "Measures to facilitate accommodation for overseas visitors", url: "https://www.mofcom.gov.cn/xwfb/rcxwfb/art/2024/art_6e5fd351d24c460cad01512ce52d3f83.html", publisher: "Ministry of Commerce of the People's Republic of China", reviewedAt: "2026-08-13" },
        { label: "National Enterprise Credit Information Publicity System overview", url: "https://www.samr.gov.cn/xw/mtjj/art/2024/art_cc4c238f12954079a735470b318fe8d7.html", publisher: "State Administration for Market Regulation", reviewedAt: "2026-08-13" },
        { label: "Official 12315 consumer complaint channels", url: "https://www.samr.gov.cn/hd/xfzn/art/2022/art_9d22351e9bee4da38b89c15e843207b4.html", publisher: "State Administration for Market Regulation", reviewedAt: "2026-08-13" },
        { label: "Four Points by Sheraton Qingtian property information", url: "https://www.marriott.com.cn/hotels/wnzfp-four-points-qingtian/overview/", publisher: "Marriott International", reviewedAt: "2026-08-13" },
        { label: "Marriott reservation FAQ", url: "https://www.marriott.com.cn/help/reservations-faq.mi", publisher: "Marriott International", reviewedAt: "2026-08-13" },
        { label: "Crystal Orange Beijing Qianmen property information", url: "https://m.huazhu.com/Hotel/Detail/1000506", publisher: "H World Group", reviewedAt: "2026-08-13" },
        { label: "Hero photograph: Haiyu Hotspring Hotel exterior, Jpbowen (CC BY-SA 4.0)", url: "https://commons.wikimedia.org/wiki/File:Entrance_of_the_Haiyu_Hotspring_Hotel,_Beibei,_Chongqing.JPG", publisher: "Wikimedia Commons", reviewedAt: "2026-08-13" }
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
