import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body: StructuredPageBody = {schemaVersion: "1.0.0", blocks: [
  {id: "answer-first", type: "lead", text: "12306 train food delivery is a timed relay, not a courier chasing the train. The current platform shows eligible delivery stations and merchants for the entered journey. A merchant prepares the order, station delivery staff move it through the controlled handoff, and railway staff or the station's delivery chain route it to the stated carriage and seat. If the journey does not return an eligible option, do not assume another train or old station list applies."},
  {id: "relay", type: "table", caption: "The order changes hands at defined points", columns: ["Stage", "Action", "Main failure risk"], rows: [
    ["Journey match", "Enter the real train/date or select the journey tied to the booking.", "Wrong train, date or passenger record."], ["Delivery-station choice", "Choose from stations returned by the current platform.", "Assuming every stop supplies food."], ["Merchant preparation", "The selected merchant accepts and prepares the order.", "Merchant cutoff or stock is stricter than the platform minimum."], ["Station handoff", "The order reaches the station's railway delivery process before the train.", "Late preparation or a disrupted train."], ["Train handoff", "Packages are matched to train, carriage and seat.", "Seat or contact details are wrong."], ["Seat delivery", "The order is brought to the recorded location under the service process.", "Seat change or missed contact delays identification."]
  ]},
  {id: "cutoff", type: "callout", title: "For outside merchants, the 60-minute rule uses the delivery station", body: "The current 12306 catering agreement says orders from outside merchants cannot be placed or cancelled within 60 minutes of the train's scheduled departure from the delivery station, unless that merchant sets an earlier cutoff. This is not 60 minutes before you leave your origin station, and it should not be generalised to every train-operated meal. Follow the cutoff shown for the actual product.", tone: "warning"},
  {id: "order-method", type: "list", ordered: true, items: [
    "Open the current Railway 12306 catering/specialty entry and match the actual journey.",
    "Use only the delivery stations and merchants returned for that train and date.",
    "Check the delivery-station departure time and the merchant's displayed cutoff.",
    "Confirm passenger, working mobile contact, carriage and seat details before paying; a no-seat passenger must give the train, carriage and contact number.",
    "Save the order record and check whether the merchant confirms or rejects it; the agreement allows ten minutes during business hours before an unconfirmed paid order is automatically rejected and refunded.",
    "If the train, carriage or seat changes, open the meal order separately and verify its delivery record; do not assume a ticket change has updated it."
  ]},
  {id: "not-guaranteed", type: "heading", level: 2, text: "Decide whether delivery is a convenience or a dependency"},
  {id: "not-guaranteed-copy", type: "comparison", title: "Use the service when it adds choice; carry food when failure matters", columns: [
    {heading: "Reasonable delivery candidate", items: ["The live journey returns an eligible future station and merchant.", "Your contact, payment, train, carriage and seat details work.", "You can use the payment methods currently offered and accept the official recovery process."]},
    {heading: "Bring a verified meal instead", items: ["A serious allergy, strict diet or medication timing makes the meal critical.", "Contact or payment verification is uncertain.", "The only eligible station has a narrow window or the journey may change."]}
  ]},
  {id: "fallback", type: "table", caption: "Safe fallback when the order does not work", columns: ["Problem", "Response"], rows: [
    ["No eligible station appears", "Buy food before boarding from a verified outlet, allowing time for security and the gate, or use confirmed onboard sales where available."], ["Payment or contact verification fails", "Do not invent contact data. The agreement lists Alipay and WeChat, while a municipal explainer also mentions cards; trust only the methods shown in live checkout."], ["Ticket is changed or refunded", "The meal is a separate order and cannot be changed to the new train: cancel it yourself within its permitted window, then place a new order if the new journey is eligible."], ["Train is disrupted", "The agreement defines automatic cancellation/refund cases for a stopped train, cancelled passenger call at the delivery station or a delivery-station delay over 30 minutes; follow the order message."], ["Order has not arrived", "Check order status and ask train staff without leaving the train. A no-seat passenger should wait in the recorded carriage or contact delivery staff and use the final five digits of the order phone number for collection."], ["Long station stop looks tempting", "Do not step off to hunt for food; dwell time and boarding control can change."]
  ]},
  {id: "dynamic-boundary", type: "callout", title: "Checked 13 August 2026", body: "The service agreement and official explainers were checked on this date. Participating journeys, stations, menus, interfaces, merchant cutoffs and delivery conditions remain dynamic. The conservative backup is food carried from the departure station, not an improvised platform run.", tone: "decision"},
  {id: "help", type: "callout", title: "Need a long rail day checked around meals?", body: "Send Homeground the date, train, boarding and arrival stations, group size, dietary constraints and any children, older travellers or medication timing involved. We can identify where a carried meal is safer than relying on delivery; 12306 and the merchant control live availability and fulfilment.", tone: "neutral"},
  {id: "internal-links", type: "internal-links", title: "Keep the rail journey itself in the right guide", items: [
    {label: "China high-speed rail first-trip guide", href: "/guides/china-high-speed-train-first-time-guide/", description: "Use the canonical guide for booking, documents and boarding."},
    {label: "Power-bank rules for flights and trains", href: "/guides/china-power-bank-rules-flights-trains/", description: "Check current power rules before a long travel day."},
    {label: "First shared meal in China", href: "/guides/first-shared-meal-in-china/", description: "Plan a fuller food experience away from the transfer day."}
  ]},
  {id: "sources", type: "sources", title: "Official and independent sources", items: [
    {label: "Catering and specialty-ordering service agreement", url: "https://kyfw.12306.cn/otn/gonggao/excater.html", publisher: "China Railway 12306", reviewedAt: "2026-08-13"},
    {label: "How to order food on high-speed trains", url: "https://english.shanghai.gov.cn/en-Transportation/20241213/1a3e604aa23140619e06d90e8d3004f4.html", publisher: "Shanghai Municipal Government", reviewedAt: "2026-08-13"},
    {label: "Beijing South internet-meal service update", url: "https://www.bjwmb.gov.cn/yw/10119254.html", publisher: "Beijing Civilization Office", reviewedAt: "2026-08-13"},
    {label: "Railway meal delivery chain", url: "https://www.ndrc.gov.cn/xwdt/ztzl/cjsjyth1/xwzx/202111/t20211115_1303935_ext.html", publisher: "National Development and Reform Commission", reviewedAt: "2026-08-13"},
    {label: "Optimization of on-demand meal ordering on high-speed railway", url: "https://www.hznu.edu.cn/upload/resources/file/2023/05/06/7774953.pdf", publisher: "Hangzhou Normal University repository", reviewedAt: "2026-08-13"}
  ]}
]}; export default body;
