import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"For a first Xi'an visit, book Shaanxi History Museum's Main Building at 91 Xiaozhai East Road, carry the original passport used in the order and read the basic collection chronologically before adding a paid or temporary exhibition. Do not navigate to the separate Qin-Han Gallery by mistake. A focused 90-minute visit can build the context for the Terracotta Warriors; a deeper visit needs two to three hours and selective reading, not an attempt to inspect every case."},
{id:"venue-warning",type:"callout",title:"Two venues, different entry logic",body:"Shaanxi History Museum's Main Building is in central Xi'an near Xiaozhai and Dayanta stations. The Qin-Han Gallery is in Xixian New Area. The museum's live guide lists separate addresses, hours and admission rules. This article covers the Main Building only; never assume one venue's order, exemption or ticket grants access to the other.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"Reserve the Main Building with the document you will carry"},
{id:"booking",type:"list",items:["Use the official Shaanxi History Museum WeChat account. The live museum guide says the Main Building accepts passports for non-mainland visitors.","As of 12 August 2026, the system releases visits five days ahead at 17:00. Pre-filling traveller data is not a reservation; check that a successful order appears.","Match the passport name and number exactly and carry the original. Entry requires the successful order, original reserved document and the correct time slot.","Cancel inside the official system if plans change. The current policy penalises no-shows with a 180-day reservation restriction.","The museum says it has not authorised third-party platforms, agencies or individuals to sell or bundle Main Building tickets."]},
{id:"current-hours",type:"paragraph",text:"The live guide currently lists 08:30–19:00 with last ticket check at 18:00 for the Main Building from 6 May to 14 November 2026, with statutory-holiday hours subject to new notices. The English page also shows these hours, a 12,000-person daily maximum and free admission by reservation. Treat all of these as dated operational facts and recheck before publication and travel."},
{id:"route-heading",type:"heading",level:2,text:"Choose a collection task before entering"},
{id:"route",type:"table",caption:"Collection plans by available time",columns:["Available time","Core task","What to leave optional"],rows:[["About 90 minutes","Follow the basic display's broad chronology: prehistoric cultures, Zhou ritual order, Qin and Han state formation, then Sui-Tang cosmopolitan life. Choose one anchor object or case in each chapter.","Temporary exhibitions, repeat rooms and the paid Tang mural collection unless separately planned."],["About 2–3 hours","Read the same chronology more slowly, compare burial objects, metalwork, ceramics and cross-cultural material, then add one current special exhibition.","Any second paid exhibition that turns the visit into a race."],["History-focused half day","Use the permanent narrative first, take a break, then add a preselected paid or temporary exhibition with its own ticket conditions.","An unrelated same-day monument if it removes all transport and meal buffer."]]},
{id:"collection-method",type:"list",items:["Prehistoric: establish how long settled life in the region predates imperial Xi'an.","Zhou: look for ritual vessels and how objects express rank, ceremony and political order.","Qin and Han: connect state systems and funerary practice to the later visit at the imperial mausoleum landscape.","Sui and Tang: slow down for trade, religion, dress and foreign connections rather than reducing the dynasty to ‘golden age’. ","At every stage, read fewer labels well. The goal is a usable historical spine, not object-count completion."]},
{id:"paid-exhibitions",type:"callout",title:"Free basic admission and paid exhibitions are separate decisions",body:"The live guide currently says the Tang Dynasty Mural Treasures Gallery and a named special exhibition use separate paid tickets, and that an online advance purchase for those paid exhibitions removes the need to repeat the Main Building free reservation. That product list and entry relationship can change; confirm it on the current purchase screen before relying on it.",tone:"neutral"},
{id:"arrival-heading",type:"heading",level:2,text:"Arrive at the right side of Xi'an"},
{id:"arrival",type:"list",items:["Save the address: 91 Xiaozhai East Road, Yanta District, Xi'an.","The museum lists Xiaozhai on Metro Lines 2 and 3 about 778 metres away, and Dayanta on Lines 3 and 4 about 834 metres away.","Allow time for the walk, queue, security and document check; the booked slot is not the time to leave your hotel.","Large luggage and restricted items complicate entry. Check the current prohibited-items list and use your hotel or a verified storage option rather than arriving with a travel-day load."]},
{id:"warriors-boundary",type:"paragraph",text:"This museum and the Terracotta Warriors solve different tasks. The Main Building explains a long regional chronology and helps place the Qin empire among earlier and later periods. The mausoleum museum is a separate out-of-centre visit with its own reservation, transport and site sequence. Do not treat one as a substitute ticket for the other or squeeze both into one unbuffered morning."},
{id:"guide",type:"paragraph",text:"A guide is useful when you need a coherent selection across crowded cases or want to connect objects to a later Qin, Han or Tang site. An audio guide or selective label reading can be enough for independent visitors. Whichever method you use, choose the interpretation goal before entering rather than joining the first sales pitch outside."},
{id:"final-check",type:"list",items:["Order says Main Building and matches the original passport.","Successful order—not only prefilled data—is visible.","Arrival respects the reserved slot and security buffer.","A 90-minute, 2–3-hour or half-day collection task is chosen.","Paid exhibition conditions are checked separately."]},
{id:"internal-links",type:"internal-links",title:"Connect the Xi'an context",items:[{label:"Terracotta Warriors without a tour",href:"/guides/terracotta-warriors-without-tour/",description:"Use the museum context, then execute the separate mausoleum-day chain."},{label:"China high-speed trains for first-time visitors",href:"/guides/china-high-speed-train-first-time-guide/",description:"Keep station and passport records separate from the museum reservation."},{label:"China with older parents",href:"/guides/china-itinerary-with-older-parents/",description:"Plan seats, standing time and a selective collection route."},{label:"Do you need a tour guide in China?",href:"/guides/do-you-need-a-tour-guide-in-china/",description:"Decide whether interpretation adds enough value."}, { label: "Plan a Sanxingdui museum visit", href: "/guides/sanxingdui-museum-booking-and-gallery-order/", description: "Use the official inbound-visitor booking channel, reach Guanghan from Chengdu and follow a gallery order that builds context before the famous bronzes." }, { label: "Connect museum objects to construction archaeology", href: "/guides/when-metro-construction-meets-archaeology/", description: "Use provenance and project-stage evidence to distinguish a find, an engineering response and a later public display." }]},
{id:"consultation",type:"callout",title:"Need Xi'an museums and sites sequenced around real reservations?",body:"A Homeground travel consultant can compare your ticket windows, hotel location and historical priorities without turning every stop into a guided tour. Share your dates, passport type, group pace and any already-booked Terracotta Warriors visit.",tone:"neutral"},
{id:"sources",type:"sources",title:"Official and image sources reviewed",items:[{label:"Main Building visit and passport-reservation guide",url:"https://www.sxhm.com/guide.h",publisher:"Shaanxi History Museum",reviewedAt:"2026-08-12"},{label:"English Main Building visit page",url:"https://en.sxhm.com/en/new/visit.html",publisher:"Shaanxi History Museum",reviewedAt:"2026-08-12"},{label:"Current prohibited-items notice",url:"https://www.sxhm.com/guide/visit/detail/16043.html",publisher:"Shaanxi History Museum",reviewedAt:"2026-08-12"},{label:"Hero: Shaanxi History Museum architecture by Danielinblue, CC BY-SA 3.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:Shaanxi_History_Museum_architecture.JPG",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
