import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"시안을 처음 방문한다면 샤오자이동로 91호의 산시역사박물관 본관을 예약하고 예약에 사용한 원본 여권을 가져가세요. 기본 전시를 연대순으로 본 뒤 유료 또는 임시 전시를 더할지 정하면 됩니다. 별도로 떨어진 진한관으로 잘못 가지 마세요. 90분 집중 관람으로 병마용을 이해할 배경을 잡을 수 있고, 심화 관람은 모든 진열장을 보려 하기보다 2–3시간과 선택적 읽기가 필요합니다."},
{id:"venue-warning",type:"callout",title:"두 장소는 입장 방식도 다릅니다",body:"산시역사박물관 본관은 시안 도심 샤오자이역과 다옌타역 근처에 있고 진한관은 시셴신구에 있습니다. 박물관의 실시간 안내는 서로 다른 주소, 시간과 입장 규정을 제시합니다. 이 글은 본관만 다루며 한 곳의 예약·무료입장·입장권이 다른 곳에도 통한다고 가정하면 안 됩니다.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"실제로 가져갈 증명서로 본관을 예약하세요"},
{id:"booking",type:"list",items:["공식 ‘陕西历史博物馆’ 위챗 계정을 이용하세요. 현재 안내는 중국 본토 외 관람객이 본관 예약에 여권을 쓸 수 있다고 명시합니다.","2026년 8월 12일 기준 방문 5일 전 입장권이 매일 17:00에 열립니다. 관람객 정보를 미리 채운 것만으로는 성공이 아니므로 예약 완료 내역을 확인하세요.","여권 이름과 번호를 정확히 맞추고 원본을 가져가세요. 예약 완료 내역, 예약에 쓴 증명서 원본과 맞는 시간대가 모두 필요합니다.","계획이 바뀌면 공식 시스템에서 취소하세요. 현재 규정은 노쇼에 180일 예약 제한을 둡니다.","박물관은 본관 입장권을 판매하거나 묶어 파는 제3자 플랫폼, 여행사 또는 개인을 승인하지 않았다고 밝힙니다."]},
{id:"current-hours",type:"paragraph",text:"실시간 안내는 2026년 5월 6일–11월 14일 본관 시간을 08:30–19:00, 검표 마감 18:00으로 두며 법정 공휴일은 새 공지를 따릅니다. 영어 페이지는 하루 최대 12,000명과 무료 예약 입장도 표시합니다. 모두 날짜가 있는 운영 사실이므로 게시 전과 여행 전에 다시 확인하세요."},
{id:"route-heading",type:"heading",level:2,text:"입장 전에 소장품 관람 과제를 고르세요"},
{id:"route",type:"table",caption:"가능 시간별 소장품 관람 과제",columns:["가능 시간","핵심 과제","선택에서 뺄 것"],rows:[["약 90분","기본 전시의 큰 연대—선사 문화, 주나라 예제, 진·한 국가 형성, 수·당의 국제적 생활—를 따라가며 장마다 대표 유물이나 진열장 하나를 고릅니다.","임시 전시, 반복 관람과 별도 계획하지 않은 유료 당나라 벽화."],["약 2–3시간","같은 연대를 천천히 읽고 부장품, 금속, 도자와 문화 교류 자료를 비교한 뒤 현재 특별전 하나를 더합니다.","관람을 경주로 만드는 두 번째 유료 전시."],["역사 중심 반나절","상설 서사를 먼저 본 뒤 쉬고 미리 고른 유료 또는 임시 전시를 더합니다.","이동과 식사 여유까지 없애는 무관한 같은 날 명소."]]},
{id:"collection-method",type:"list",items:["선사: 이 지역의 정착 생활이 제국 수도 시안보다 훨씬 오래됐다는 시간축을 세웁니다.","주: 제기를 통해 물건이 신분, 의례와 정치 질서를 어떻게 표현하는지 봅니다.","진·한: 국가 체계와 장례 관념을 이후 황릉 유적 방문과 연결합니다.","수·당: 당을 ‘황금기’로만 줄이지 말고 교역, 종교, 복식과 외래 연결을 천천히 봅니다.","각 시대에서 적은 설명을 제대로 읽으세요. 목표는 유물 수를 채우는 것이 아니라 여행 중 활용할 수 있는 역사적 틀을 세우는 것입니다."]},
{id:"paid-exhibitions",type:"callout",title:"무료 기본 입장과 유료 전시는 별도 결정입니다",body:"현재 안내는 당나라 벽화 진품관과 이름이 명시된 특별전에 별도 표가 필요하고, 해당 유료 표를 온라인으로 미리 사면 본관 무료 예약을 다시 할 필요가 없다고 설명합니다. 상품과 입장 관계는 바뀔 수 있으므로 이 규정에 의존하기 전에 현재 구매 화면을 확인하세요.",tone:"neutral"},
{id:"arrival-heading",type:"heading",level:2,text:"시안 도심의 정확한 장소로 가세요"},
{id:"arrival",type:"list",items:["주소는 시안시 옌타구 샤오자이동로 91호입니다.","박물관은 2·3호선 샤오자이역에서 약 778m, 3·4호선 다옌타역에서 약 834m라고 안내합니다.","걷기, 줄, 보안 검색과 증명서 확인 시간을 두세요. 예약 시간대가 숙소를 나설 시간은 아닙니다.","큰 짐과 반입 제한 물품은 입장을 어렵게 합니다. 최신 금지 목록을 확인하고 숙소나 검증된 보관 장소를 이용하세요."]},
{id:"warriors-boundary",type:"paragraph",text:"본관과 병마용은 서로 다른 문제를 해결합니다. 본관은 긴 산시 역사 속에서 진 제국의 전후를 보여 주고, 진시황릉박물원은 도심 밖의 별도 방문으로 예약·교통·현장 순서가 따로 있습니다. 표는 서로 통하지 않으며 여유 없이 같은 오전에 욱여넣지 마세요."},
{id:"guide",type:"paragraph",text:"붐비는 진열장에서 일관된 핵심을 고르거나 유물을 이후 진·한·당 유적과 연결하려면 해설의 가치가 있습니다. 자유 관람객은 오디오 가이드나 선택적 설명 읽기로도 충분할 수 있습니다. 어떤 방법이든 입장 전 해석 목표를 정하고 밖에서 만난 첫 판매 권유를 따르지 마세요."},
{id:"final-check",type:"list",items:["예약 내역에 본관이 명시되고 원본 여권과 일치합니다.","미리 채운 정보가 아니라 예약 완료 내역이 보입니다.","예약 시간과 보안 검색 여유에 맞춰 도착합니다.","90분, 2–3시간 또는 반나절 관람안을 골랐습니다.","유료 전시 입장 조건은 별도로 확인했습니다."]},
{id:"internal-links",type:"internal-links",title:"시안의 역사 맥락을 연결하세요",items:[ { label: "시안 도시 허브", href: "/ko/destinations/xian/", description: "이 세부 사항을 정하기 전에 숙박 일수, 거점, 다음 도시를 먼저 정하세요." },{label:"병마용 자유여행 전체 절차",href:"/ko/guides/terracotta-warriors-without-tour/",description:"박물관에서 맥락을 세운 뒤 별도의 황릉 방문 과정을 실행하세요."},{label:"중국 고속철 첫 이용 안내",href:"/ko/guides/china-high-speed-train-first-time-guide/",description:"역과 여권 기록을 박물관 예약과 구분해 관리하세요."},{label:"부모님과 중국 여행",href:"/ko/guides/china-itinerary-with-older-parents/",description:"앉을 곳, 서 있는 시간과 선택적 소장품 동선을 계획하세요."},{label:"중국 여행에 가이드가 필요할까",href:"/ko/guides/do-you-need-a-tour-guide-in-china/",description:"해설이 충분한 가치를 더하는지 판단하세요."}, { label: "싼싱두이박물관 방문 계획하기", href: "/ko/guides/sanxingdui-museum-booking-and-gallery-order/", description: "공식 외국인 전용 예약 채널로 예약하고 청두에서 광한으로 이동한 뒤, 고고학적 맥락부터 청동 유물까지 순서대로 봅니다." }, { label: "박물관 유물을 건설 고고학과 연결하기", href: "/ko/guides/when-metro-construction-meets-archaeology/", description: "출처와 사업 단계의 증거로 발견, 공학적 대응과 이후 공개 전시를 구분합니다." }]},
{id:"consultation",type:"callout",title:"실제 예약에 맞춰 시안 박물관과 유적을 배열해야 하나요?",body:"Homeground 여행 상담가가 모든 방문지를 투어 상품으로 묶지 않고도 입장권 오픈 시점, 숙소 위치와 역사 관심을 비교할 수 있습니다. 날짜, 여권 종류, 일행 속도와 이미 예약한 병마용 시간을 알려 주세요.",tone:"neutral"},
{id:"sources",type:"sources",title:"확인한 공식·이미지 출처",items:[{label:"본관 안내, 여권 예약과 입장 규정",url:"https://www.sxhm.com/guide.h",publisher:"산시역사박물관",reviewedAt:"2026-08-12"},{label:"영문 본관 방문 페이지",url:"https://en.sxhm.com/en/new/visit.html",publisher:"산시역사박물관",reviewedAt:"2026-08-12"},{label:"현재 관람객 반입 금지 목록",url:"https://www.sxhm.com/guide/visit/detail/16043.html",publisher:"산시역사박물관",reviewedAt:"2026-08-12"},{label:"대표 이미지: Danielinblue, CC BY-SA 3.0; 자르기·변환",url:"https://commons.wikimedia.org/wiki/File:Shaanxi_History_Museum_architecture.JPG",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
