import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "第一次到深圳，不必默认为大鹏所城和较场尾留出整整一天。只有当你确实对深圳现代化以前的海防历史感兴趣，而且当天没有过关、航班或长途列车的截止时间时，才值得前往。以所城为主角；天气、体力和返程余量都允许时，再增加较场尾。如果海边或大鹏半岛另一项活动本身就是旅行目标，就考虑过夜。若室内空间无法参观，而历史又不是你的重点，则应跳过东部行程。" },
  { id: "answer", type: "callout", title: "直接结论", tone: "decision", body: "如果你既想认真读懂历史空间，也想从容地在海边停留，可以把两地合成一个完整日。若历史是前往大鹏的理由，但当天可用时间被压缩，就只保留所城。如果沙滩、水上活动或海边傍晚比当天返回深圳中心城区更重要，可以考虑过夜。若你在深圳仅有一两天，兴趣主要是当代城市，或当天还要去香港、机场或乘坐长途列车，则应跳过这段行程。以上是 Homeground 的行程判断，不是官方公布的游览时长或套票产品。" },

  { id: "worth-heading", type: "heading", level: 2, text: "深圳东部值得占用你一整天吗？" },
  { id: "worth-copy", type: "paragraph", text: "真正的问题是：这两个地方是否值得你从深圳中心城区移动到城市东端，同时还要保护返程时间。大鹏新区政府本来就把两地组合成一日线路；真正缺少的是，你最不愿失去什么。历史优先的旅客需要给所城足够的注意力；海边优先的旅客，可能比当天返回更看重傍晚和应对天气的弹性。如果两个主题对你的吸引力都只来自一张“深圳亮点”清单，就把这一天留给中心城区。" },
  { id: "worth-table", type: "table", caption: "先决定投入程度，再决定走法", columns: ["你真正的优先事项", "最合适的行程形态", "需要保护的内容", "不要勉强加入"], rows: [
    ["现代化以前的深圳与海防历史", "完整日，或只去所城的一天", "所城城门、街巷结构、官方解说，以及当天确认开放的室内空间", "若会削弱历史阅读或返程余量，就不要拉长海边停留"],
    ["一点历史，加一段简短海边散步", "完整日，先看所城", "先完整参观所城，再依据当天情况决定是否去较场尾", "游泳、水上活动、日落或固定返程时刻都不能预先保证"],
    ["沙滩、水上活动或悠闲的滨海夜晚", "考虑过夜，或改成以海岸为主的计划", "当天的天气、安全状况和运营方确认", "不要把所城当作海边行程必须附带的装饰"],
    ["深圳只有一两天，重点是设计、科技、美食或当代城区", "跳过东部一日", "保留当初让你选择深圳的中心城区重点", "不要因为“古城加海边”听起来像必选组合就前往"],
    ["当天还要去香港口岸、机场或搭乘长途列车", "跳过，或把大鹏移到没有硬性任务的一天", "为不可延误的出发保留宽裕缓冲", "不要把远距离出游和不可逆的截止时间叠在一起"],
  ]},
  { id: "pair-heading", type: "heading", level: 2, text: "你实际组合的是哪两个地方？" },
  { id: "pair-copy", type: "paragraph", text: "大鹏所城与较场尾彼此相邻，却不是同一个收取门票景区里的两个分区。大鹏所城是全国重点文物保护单位所在的历史聚落，拥有公共街巷、城门、城墙、具名宅第和由博物馆管理的室内空间；较场尾则是拥有住宿餐饮经营和海岸边缘的滨海村落与旅游区域。鹏城村保护规划把两地纳入较大的村庄规划范围，同时在该规划内划定较小、以所城为中心的核心保护范围。这一规划层级解释了官方为何把两地组合起来，却不能把较场尾划进全国重点文物保护单位的法定边界，也不能把它视作所城展览的一部分。" },
  { id: "relationship-figure", type: "figure", src: "/images/guides/dapeng-fortress-jiaochangwei-day-trip-decision/fortress-jiaochangwei-relationship.svg", alt: "不按比例绘制的编辑示意图，将大鹏所城与相邻的较场尾滨海村落分开标示", width: 1600, height: 1000, caption: "两地相邻，也经常被组合游览，但服务的是不同旅行目标。这不是路线地图，不承诺步行时间、入口位置或无障碍连通。" },
  { id: "pair-table", type: "table", caption: "相邻的两个地方，承担两种不同任务", columns: ["地点", "最突出的价值", "短时间参观能获得什么", "不能保证什么"], rows: [
    ["大鹏所城", "海防聚落、后期宅第和古城生活层次留下的空间与物质证据", "阅读城门、城墙构件、街巷尺度、具名建筑和当下解说", "不能说明眼前每个构件都始于1394年、每个室内空间都开放，也不能把街巷视作未经改变的明代古城"],
    ["较场尾", "紧邻历史区域的一段滨海村落体验", "条件合适时，增加一段在陆地上的海边散步、休息或对当代村落旅游业的观察", "不能保证水质、游泳条件、活动营业、低客流、日落或度假型沙滩品质"],
  ]},
  { id: "map-rule", type: "callout", title: "使用今天允许通行的连接方式", tone: "warning", body: "在两地之间以实时地图、围挡和现场标识为准。官方组合能够证明两地相邻，却不能证明永久共用一个入口、固定的步行时间或连续无台阶通道。" },

  { id: "traveller-heading", type: "heading", level: 2, text: "你属于历史优先、海边优先，还是截止时间优先？" },
  { id: "traveller-copy", type: "paragraph", text: "历史优先的旅客有一个清晰主角：大鹏所城。家庭或步速较慢的同行者可以保护这一条阅读线，同时让较场尾保持可删。海边优先的旅客则要问，一段受天气影响的短暂海岸停留是否足够；若不够，就选择过夜或另做海岸一日。从香港当天往返最不合适，因为两段有波动的移动包围着一个固定的过关截止时间。" },
  { id: "scenarios", type: "table", caption: "四种真实行程情境", columns: ["情境", "建议", "理由", "安全阀"], rows: [
    ["两位朋友在深圳有三天，而且会主动阅读军事史和城市史", "留出完整日，先看所城，海边可选", "历史主题值得这份时间投入，两地的反差也有价值", "参观完所城后再决定是否去较场尾，不要提前锁死"],
    ["父母步速较慢，也需要坐下休息", "只去所城，或只加一段很短的海边停留", "历史建筑门槛，加上尚未核实的连续无障碍连接，使强行完成两站风险更高", "让交通保持可用，逐处询问无障碍入口；提早结束不代表行程失败"],
    ["一对情侣真正想要的是日落、沙滩时间和放松的夜晚", "过夜，或选择更专注海岸的方案", "返回中心城区可能恰好拿走他们最珍惜的时间", "住宿另行确认天气、安全和物业条件；本页不代选酒店"],
    ["第一次到深圳，只停留36小时，夜里已预订去香港的安排", "跳过", "当代深圳与过关期限，会和一段距离远、依赖条件的行程正面竞争", "住宿区域和口岸枢纽请交给对应页面；不要因为已经做过功课就勉强前往"],
  ]},
  { id: "fortress-heading", type: "heading", level: 2, text: "大鹏所城凭什么值得专程前往？" },
  { id: "fortress-copy", type: "paragraph", text: "把所城当作一个有多重时间层次的聚落，而不是一排看起来古老的店铺，它才值得这段路程。官方资料把建城时间追溯至1394年，并将其说明为明清海防重地；同样的资料也记录了后来的宅第、庙宇、行政遗存、修缮过程和今天的博物馆用途。这个先后关系很重要：眼前的地方既不是某一年的完整原状，也不是一次性新建的主题园。参观时始终抓住四个观察问题——边界、街巷结构、具名室内空间和当下使用——就不容易把所城看成泛泛的“古风街”。" },
  { id: "fortress-observe", type: "list", ordered: true, items: [
    "到现存城门时，先辨认防御空间的门槛，再拍屋顶轮廓。如现场有当前正式解说，用它区分有明确年代、经过修缮和重建的城墙或城楼构件。例如，深圳场馆名录对南门不同的营建与修缮层次分别说明，并未把整座立面描述成未经改动的明代原物。",
    "进入所城后，借南门街、东门街、十字街和正街理解聚落紧凑的尺度和交叉结构。只有当前正式现场解说明确如此说明时，才能把某段路线称作保存下来的军事行进线。",
    "只有在确认当日开放后，才选择一处具名宅第或博物馆展室。赖恩爵振威将军第可以把一处家族宅院与19世纪海军史连接起来；但若大门关闭或展览暂停，不能只看外立面就猜测里面的内容。",
    "留意水井、门槛、石础或官方界标等较小构件。如现场有当前正式标签，先读标签再判断年代、功能或主人；没有解说时，“看起来很旧”不是断代证据。",
    "观察今天的商店、标识，以及有人使用或关闭的门口。它们说明保护、旅游和日常生活如今彼此重叠，既不能证明这里完全保持历史原貌，也不能证明一切都只是商业造假。",
  ]},
  { id: "nanmen-figure", type: "figure", src: "/images/guides/dapeng-fortress-jiaochangwei-day-trip-decision/nanmen-street-1600.webp", alt: "大鹏所城南门街36号的瓦顶与石门框，立面上可见当代小吃店招牌", width: 1600, height: 1000, caption: "瓦顶、石门框与今天的零售招牌出现在同一立面。图片记录的是当代商业层，不能据此判断建筑年代或原始用途。" },
  { id: "lai-figure", type: "figure", src: "/images/guides/dapeng-fortress-jiaochangwei-day-trip-decision/lai-residence-1600.webp", alt: "大鹏所城赖恩爵故居带装饰的入口与关闭的木门", width: 1600, height: 1000, caption: "2026年4月7日拍摄的照片里可见关闭的木门和一张小告示。它说明室内开放必须单独核实，但不能证明今天仍是同一状态。" },
  { id: "history-limit", type: "callout", title: "按不同层次读年代，不要只套一个始建年份", tone: "warning", body: "海防聚落始建于1394年，但宅第、不同城墙砌层、城楼、展陈、修缮、商铺立面和市政设施都有各自的历史。如当前正式解说提供了年代，就按解说阅读；否则只描述眼前可见的构件。" },

  { id: "coast-heading", type: "heading", level: 2, text: "较场尾能增加什么，又不能增加什么？" },
  { id: "coast-copy", type: "paragraph", text: "较场尾可以改变一整天的节奏。仔细看过城墙、街巷和标签后，一段开阔的滨海空间或坐下休息，可能形成有用的对照。今天的民宿、餐饮和休闲经营，也展示了不同于所城的村落适应方式。对部分旅客而言，这已足以支持一段短暂延伸；但还不足以承诺一次沙滩度假。政府长期展示的目的地页面提到沙滩和水上活动，可真正决定当天是否能用的，仍是即时天气、划定的安全区域、施工、潮汐、水质和运营方状态。" },
  { id: "coast-selector", type: "table", caption: "在所城现场决定，不要只按宣传册决定", columns: ["参观完所城后的情况", "是否增加较场尾？", "可以保留的期待", "应删掉的期待"], rows: [
    ["天气干燥、没有不利预警，体力和返程余量都充足", "可以，作为一段简短的陆上海岸与村落停留", "在当前通行条件下换一个环境、散步或休息", "保证游泳、人少、沙滩洁净或看到日落"],
    ["小雨或高温已经消耗体力", "只有在很短、能避雨或避晒的停留仍有价值时才加", "休息，或有限地看看公共空间", "完成一份沙滩打卡清单"],
    ["有雷暴、强风、台风或暴雨提示，或现场实施限制", "不去", "遵守官方安全要求并离开近水区域", "水上活动或“只下水一会儿”"],
    ["村内拥挤，或施工改变通行方式", "可选；缩短或跳过", "只使用开放的公共空间，并以现场标识为准", "固定步行环线，或旧照片里的氛围"],
    ["你需要的是完整的沙滩下午或滨海夜晚", "不要把它压缩成象征性的附加站", "改成过夜，或另行研究一整天的海岸方案", "默认较场尾能满足所有海滩目标"],
  ]},
  { id: "sequence-heading", type: "heading", level: 2, text: "当天往返应该怎样安排顺序？" },
  { id: "same-day-sequence", type: "list", ordered: true, items: [
    "以历史为主时，先看所城：公共街巷可以作为失败恢复，而室内空间开放窗口较窄，海边也更容易删除。离开深圳中心城区前，确认当天没有过关、机场或长途列车的截止时间；随后查看大鹏即时天气和通行通知。",
    "如果在2026年受管制的周末或法定节假日驾驶私家车或租赁车辆，出发前办妥大鹏半岛道路预约。它不是景点门票，也不等于停车位。",
    "到达所城后，确认一处当下允许进入的城门或入口。先读边界和街巷格局，再增加室内空间。",
    "根据自己的历史问题，选择一至两处确认开放的具名室内空间，而不是因为旧清单写着就假设所有房间都开门。若开放情况变化，仍要保持外部空间和街巷阅读的连贯性。",
    "在所城出口依据天气、预警、疲劳、施工和返程余量，重新决定较场尾去或不去。",
    "若海边条件仍合适，默认只做陆地活动。只有当天标识、工作人员和安全条件都支持时，才下水或购买水上项目。",
    "在返程余量仍然宽裕时离开。不要为了追回时间而无视围挡、天气警告或步速较慢的同行者。",
  ]},
  { id: "well-figure", type: "figure", src: "/images/guides/dapeng-fortress-jiaochangwei-day-trip-decision/fortress-well-1600.webp", alt: "大鹏所城内一口带金属安全围栏的石砌井", width: 1600, height: 1000, caption: "图片能证明所城内可见一口井，但仅凭照片无法判断它的年代或修复历史。" },
  { id: "overnight-heading", type: "heading", level: 2, text: "什么时候应该把一日游改成过夜？" },
  { id: "overnight-copy", type: "paragraph", text: "过夜应由第二个独立目标来证明，而不是仅因为路远。合理触发条件包括：想在海边度过傍晚；等待更安全或平稳的下水窗口；加入另一项已核实的大鹏半岛活动；或让步速较慢的同行者有足够恢复时间。“既然这么远，不如住一晚”则是较弱的理由。住宿会新增选房、取消条款和次日返程等任务，应该换来你真正看重的内容。" },
  { id: "access-heading", type: "heading", level: 2, text: "哪些通行规则会改变计划？" },
  { id: "access-copy", type: "paragraph", text: "三类不同限制很容易被混成一件事。第一，大鹏所城目的地长期页面把较宽泛的所城公共区域列为全天开放。第二，深圳市政府当前场馆名录为大鹏新区博物馆列出机构级服务时间：周一闭馆，周二至周日09:00—17:00，节假日及特殊情况另行通知。名录虽然列出所城内多栋建筑，却不能证明每栋建筑或每间展室同时开放；出发那一周仍需逐处确认。第三，2026年大鹏半岛规则管的是特定车辆进入受控道路，并非人员进入所城。把三层规则分开，就不会把道路预约误认为博物馆预约，也不会把开放的街巷误认为开放的宅第。" },
  { id: "access-table", type: "table", caption: "不能互相替代的三类管制", columns: ["管制", "管理对象", "当前证据", "失败恢复"], rows: [
    ["所城公共区域通行", "街巷与开放公共空间", "大鹏目的地长期页面显示全天开放", "服从当前围挡，用外部与街巷完成有限阅读"],
    ["大鹏新区博物馆这一机构", "机构级服务时段；具名建筑与展室仍需逐处确认", "深圳市政府当前场馆名录列出周一闭馆，周二至周日09:00—17:00；特殊通知优先，且名录不承诺所有空间同时开放", "保留聚落空间阅读，删去需要室内证据才能成立的结论"],
    ["2026年大鹏半岛车辆预约", "受影响日期内，指定车辆进入管制道路区域", "公安交警正式通告：2026年5月1日至10月7日的周末和法定节假日；列明车辆类别可豁免", "使用交警实时系统，或采用符合当日规则的交通方式；本页不提供交通执行方案"],
  ]},
  { id: "vehicle-warning", type: "callout", title: "2026年正式通告截至10月7日", tone: "warning", body: "深圳市政府一则新闻摘要写到10月8日，但深圳市公安局正式通告及交警后续说明均写10月7日。本文采用正式通告日期，并记录这一冲突。驾驶者仍应查询实时预约系统。道路预约成功不等于已有停车位或景点入场资格。" },
  { id: "threshold-figure", type: "figure", src: "/images/guides/dapeng-fortress-jiaochangwei-day-trip-decision/residential-threshold-1600.webp", alt: "大鹏所城十字街21号关闭的红色双门与旁边较窄的门口", width: 1600, height: 1000, caption: "公共街巷可以经过关闭的门槛。看得见门牌、街道开放，都不代表可以穿过门口或进入院落。" },
  { id: "etiquette-list", type: "list", items: [
    "留在公共街巷，只进入明确开放的参观空间；街道开放不等于可以跨过没有标识的门槛。",
    "拍摄可识别的居民、工作人员、礼拜者，或门内人物前先征得同意。作为公共空间背景偶然入镜，不等于近距离人物特写。",
    "不要为了改善拍摄角度而移动围挡、触摸历史表面，或探身越过水井护栏。",
    "今天的现场标识和工作人员要求，优先于本文和旧社交媒体帖子。",
    "如果无障碍连续通行很重要，请逐一询问各个管理场所当下的无障碍入口。本文不认证所城至海边存在连续无障碍路线。",
  ]},

  { id: "recovery-heading", type: "heading", level: 2, text: "当天出问题时，应该先删什么？" },
  { id: "recovery-table", type: "table", caption: "不假装行程没变的失败恢复", columns: ["问题", "立即怎样修改", "哪些内容仍然成立", "必须停止声称什么"], rows: [
    ["周一或某处博物馆室内空间关闭", "利用城门、公共街巷、街巷结构，以及现场任何可用的当前正式解说；只进入已经确认开放的空间", "对聚落形态和当代使用方式的有限阅读", "不能声称看过馆藏、宅第室内或全部具名场所"],
    ["下雨、高温或疲劳令体力下降", "保留一座城门、交叉街巷结构和一处确认开放的室内空间；先删较场尾", "历史主轴", "不能再称为从容的两地一日"],
    ["雷暴、强风、台风或暴雨提示，或近水区域受限", "离开海岸与近水区域并服从官方指令；结束行程，或只使用明确允许开放且能避险的所城空间", "仅限仍被明确允许、安全开放的部分", "不能声称可以游泳、参加水上活动或正常停留海边"],
    ["绕行、施工或拥挤改变两地连接", "沿允许通行的路线行动；如果较场尾已经没有额外价值，就跳过它", "仍可到达的所城阅读", "不能承诺固定路线、入口、步行时间或必须完成两地"],
    ["返程时间开始失控", "立刻离开，并删除所有可选停留", "可控的返程", "不能再把海边、用餐或下一处室内空间说成“顺路”"],
    ["同行者看不懂现场中文说明", "保存正式中文地名；仅在允许时拍摄公共标签，用离线翻译帮助同行者，并只描述标签能够支持的事实", "可见边界、街巷尺度和具名地点", "不能根据外观推断年代、军事功能或修复过程"],
    ["无法确认无障碍通行", "只询问下一个场所；缩短到能够安全抵达的公共空间，或结束行程", "安全、选择性的参观", "不能声称存在连续无障碍环线"],
  ]},

  { id: "verify-heading", type: "heading", level: 2, text: "离开深圳中心城区前，应核实什么？" },
  { id: "verify-copy", type: "paragraph", text: "稳定的行程判断现在就能做，运营细节则应留到出发那一周复核。先保存中文名称“大鹏所城”和“较场尾”，再检查可能令所选行程形态失效的条件。下面的清单刻意不提供固定公交线路、票价或驾车时间；这些属于交通执行页面，而且比目的地取舍更快过期。" },
  { id: "checklist", type: "list", items: [
    "在完整日、只去所城、过夜和跳过之间做出选择，并说清值得占用东部一天的唯一理由。",
    "移走同一天的过关、机场或长途列车截止时间；否则就移动大鹏。",
    "检查博物馆场馆名录，以及更新的闭馆、天气、水上安全和绕行通知。",
    "若在2026年受影响日期驾车，使用交警实时系统；5月1日至10月7日的规则管车辆，不是入场或停车。",
    "使用实时地图和现场标识；确认一至两处室内空间，同时保留城门与街巷替代方案。",
    "参观完所城后再评估较场尾。下水或购买活动，需要当天获得允许且安全条件成立。",
    "停留在公共街巷，尊重关闭的门槛；拍摄可识别人物前先询问，并在返程余量仍完整时离开。",
  ]},
  { id: "facts", type: "callout", title: "证据边界，复核于2026年9月4日", tone: "neutral", body: "政府、文物、博物馆、规划、交通和安全来源能够证明两地身份、所城历史与保护属性、具名博物馆场所、机构级场馆名录时间、2026年季节性车辆管制、有文件记录的2026年项目计划和安全限制。去或不去的分支、默认先看所城、过夜触发条件、时间保护原则和删减顺序，均为 Homeground 编辑判断；它们不是官方线路名称、行程耗时保证、无障碍认证，也不承诺入场、水质或活动运营。" },
  { id: "links", type: "internal-links", title: "相邻的深圳决策请查看对应指南", items: [
    { label: "选择深圳住宿基地：福田、罗湖还是南山", href: "/zh/guides/shenzhen-where-to-stay-futian-luohu-nanshan/", description: "主要城市住宿基地应另行选择；本页不推荐酒店，也不会把较场尾设为默认住宿地。" },
    { label: "选择深圳机场、火车站或口岸", href: "/zh/guides/shenzhen-airport-railway-station-border-port-selector/", description: "保护正确的固定出发任务，避免把距离较远的东部一日和错误的枢纽叠在一起。" },
    { label: "安排广州、深圳和香港的先后顺序", href: "/zh/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "跨城顺序交给对应页面；不要让这篇本地决策页承担三城总行程。" },
  ]},
  { id: "cta", type: "callout", title: "需要把大鹏取舍放进真实的深圳行程吗？", tone: "neutral", body: "告诉 Homeground 旅行规划师你的深圳住宿区域、可用日期、同行步速和固定出发任务。我们可以一起判断东部这一天是否属于你的行程，以及应该为返程留多少时间，而不会把大鹏硬塞进一个删掉它反而更好的计划。" },
  { id: "sources", type: "sources", title: "官方、规划、安全与图片来源", items: [
    { label: "大鹏所城概况与大鹏新区博物馆信息", url: "https://www.dpxq.gov.cn/zjdp/xqmxp/dpfg/content/post_12303112.html", publisher: "大鹏新区政府／大鹏新区博物馆", reviewedAt: "2026-09-04" },
    { label: "大鹏所城文物保护单位现行名录条目", url: "https://wtl.sz.gov.cn/ggfw/whl/shwhttylb/content/post_11653799.html", publisher: "深圳市文化广电旅游体育局", reviewedAt: "2026-09-04" },
    { label: "大鹏所城长期目的地页面", url: "https://www.dpxq.gov.cn/ztzl/pyxsj/wzdp/zjd/content/post_11551556.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "大鹏新区博物馆当前场馆名录", url: "https://www.sz.gov.cn/szzt2010/szwtt/wtcg/whcg/content/post_11171158.html", publisher: "深圳市人民政府", reviewedAt: "2026-09-04" },
    { label: "2023年关于大鹏所城场馆地址与开放时间的官方答复", url: "https://www.dpxq.gov.cn/hdjlpt/detail?pid=2759505&via=pc", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "较场尾长期目的地页面", url: "https://www.dpxq.gov.cn/ztzl/pyxsj/wzdp/zjd/content/post_11566977.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "官方大鹏所城—较场尾一日线路", url: "https://www.dpxq.gov.cn/ztzl/pyxsj/jplx/content/post_11552264.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "大鹏英文旅游线路，包括所城—较场尾组合", url: "https://www.dpxq.gov.cn/english/travel/travelroutes/content/post_3325303.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "大鹏所城—较场尾旅游区域组合", url: "https://wtl.sz.gov.cn/lyfw/qyly/content/post_11993018.html", publisher: "深圳市文化广电旅游体育局", reviewedAt: "2026-09-04" },
    { label: "鹏城村保护规划公告", url: "https://pnr.sz.gov.cn/xxgk/gggs/content/post_11576094.html", publisher: "深圳市规划和自然资源局", reviewedAt: "2026-09-04" },
    { label: "关于鹏城村规划与所城保护边界的官方访谈", url: "https://pnr.sz.gov.cn/hdjl/zxft/content/post_11687498.html", publisher: "深圳市规划和自然资源局", reviewedAt: "2026-09-04" },
    { label: "2026年大鹏半岛交通管理正式通告", url: "https://ga.sz.gov.cn/ZWGK/QT/GSGG/content/post_12754909.html", publisher: "深圳市公安局交通警察局", reviewedAt: "2026-09-04" },
    { label: "2026年4月30日交警问答，确认预约期截至10月7日", url: "https://szjj.sz.gov.cn/gkmlpt/content/12/12761/post_12761017.html", publisher: "深圳交警", reviewedAt: "2026-09-04" },
    { label: "大鹏半岛车辆预约实时入口", url: "https://yycx.szjj.sz.gov.cn/", publisher: "深圳交警", reviewedAt: "2026-09-04" },
    { label: "2026年车辆预约取消与延误官方问答", url: "https://szjj.sz.gov.cn/gkmlpt/content/12/12813/post_12813699.html", publisher: "深圳交警", reviewedAt: "2026-09-04" },
    { label: "大鹏办事处2026年工作计划", url: "https://www.dpxq.gov.cn/isz/ghjh/fzgh/content/post_12644702.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "2026年8月较场尾更新项目树木处置公众意见征询", url: "https://www.dpxq.gov.cn/xxgk/xxgk/tzgg/content/post_12956505.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "2026年大鹏水上安全提示", url: "https://www.dpxq.gov.cn/hdjl/ywzsk/aqsc/content/post_12880772.html", publisher: "大鹏新区应急管理部门", reviewedAt: "2026-09-04" },
    { label: "台风导致区域滨海绿道关闭的案例", url: "https://www.dpxq.gov.cn/english/news/notices/content/post_12928324.html", publisher: "大鹏新区政府", reviewedAt: "2026-09-04" },
    { label: "Dinkun Chen 拍摄的大鹏所城东门——经 Homeground 裁切、缩放并转换为 WebP", url: "https://commons.wikimedia.org/wiki/File:Dapeng_Fortress,_Shenzhen.jpg", publisher: "Wikimedia Commons，CC BY-SA 4.0", reviewedAt: "2026-09-04" },
    { label: "Yumeto 拍摄的南门街36号——经 Homeground 裁切、缩放并转换为 WebP", url: "https://commons.wikimedia.org/wiki/File:20260407_36_Nanmen_Jie.jpg", publisher: "Wikimedia Commons，CC BY-SA 4.0", reviewedAt: "2026-09-04" },
    { label: "Yumeto 拍摄的十字街21号——经 Homeground 裁切、缩放并转换为 WebP", url: "https://commons.wikimedia.org/wiki/File:20260407_21_Shizi_Jie.jpg", publisher: "Wikimedia Commons，CC BY-SA 4.0", reviewedAt: "2026-09-04" },
    { label: "Yumeto 拍摄的赖恩爵故居——经 Homeground 裁切、缩放并转换为 WebP", url: "https://commons.wikimedia.org/wiki/File:20260407_Former_residence_of_Lai_Enjue.jpg", publisher: "Wikimedia Commons，CC BY-SA 4.0", reviewedAt: "2026-09-04" },
    { label: "Dinkun Chen 拍摄的大鹏所城内水井——经 Homeground 裁切、缩放并转换为 WebP", url: "https://commons.wikimedia.org/wiki/File:A_Well_in_Dapeng_Fortress,_Shenzhen.jpg", publisher: "Wikimedia Commons，CC BY-SA 4.0", reviewedAt: "2026-09-04" },
    { label: "知识共享署名—相同方式共享4.0许可协议", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-09-04" },
  ]},
] } as const satisfies StructuredPageBody;

export default body;
