import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {schemaVersion:"1.0.0",blocks:[
  {id:"lead",type:"lead",text:"The Grand Canal is not one preserved ribbon and it is not only an imperial engineering story. Across its enormous system, protected locks and bridges, modern freight channels, rebuilt promenades, housing, shops and ordinary shortcuts sit beside one another. The useful travel task is to identify which layer you are looking at, then notice how water still shapes movement and neighbourhood life without pretending every lively waterfront is unchanged history."},
  {id:"answer",type:"callout",title:"Read three canals at once",body:"First identify the documented heritage element. Second ask whether the waterway still performs a transport, drainage or mobility job. Third step one street back and look for the daily city: apartment entrances, produce shopping, school runs, repairs, deliveries and evening exercise. A strong visit connects these layers; a weak one mistakes decorative paving for continuity.",tone:"decision"},
  {id:"layers-heading",type:"heading",level:2,text:"The name 'Grand Canal' covers three different kinds of evidence"},
  {id:"layers",type:"table",caption:"Keep the layers separate before connecting them",columns:["Layer","What counts as evidence","What it can tell you","What it cannot prove"],rows:[
    ["World Heritage property","A named canal section, hydraulic work or associated urban facility in the UNESCO serial property","Historic routes, engineering, administration and selected urban relationships","That every nearby old-looking lane is inscribed or ancient"],
    ["Working waterway","Freight traffic, locks, wharves, maintenance, water management or passenger movement documented by a current operator or authority","How a historic corridor has been adapted to present logistics and urban systems","That modern operation preserves the same cargo, labour or social order"],
    ["Everyday waterfront","Public paths, residential streets, shops, services and routines observed in a precisely located neighbourhood","How residents use water-adjacent space now","That one visit represents all residents, all seasons or the whole canal"]
  ]},
  {id:"system-heading",type:"heading",level:2,text:"The canal made cities by joining movement, storage and exchange"},
  {id:"system",type:"paragraph",text:"UNESCO describes the canal as the backbone of an inland communication system that moved grain and strategic materials and linked major river basins. Warehouses, tax and transport administration, wharves, bridges and market streets therefore belonged to one operating chain. Independent urban-history research also stresses that canal cities developed different forms rather than one standard 'water-town' layout. That distinction matters: a broad freight reach in northern Jiangsu, a dense bridge neighbourhood in Hangzhou and an urban recreation bank in Beijing can all belong to the canal story while showing different functions."},
  {id:"change-heading",type:"heading",level:2,text:"Continuity does not mean that nothing changed"},
  {id:"change",type:"comparison",title:"What survived, what shifted",columns:[
    {heading:"Historical operating logic",items:["Water made bulk movement possible","Warehousing and exchange gathered near access points","Bridges and gates concentrated crossings","Maintenance depended on organized labour and authority"]},
    {heading:"Present-day expression",items:["Some reaches still carry major freight","Former industrial edges may become museums, housing or promenades","Road, rail and digital logistics now intersect with the waterway","Public-space renewal can improve access while changing who uses the bank and how"]}
  ]},
  {id:"places-heading",type:"heading",level:2,text:"Choose a section by the relationship you want to see"},
  {id:"places",type:"table",caption:"Four useful lenses, not a ranked sightseeing list",columns:["Lens and possible base","Look for","Why it is useful","Boundary"],rows:[
    ["Working navigation — northern Jiangsu canal cities","Commercial vessels, locks, waiting areas and the separation between industrial and public banks","China's Ministry of Transport reports that the northern Jiangsu reach remains a major freight corridor","Observe only from lawful public space; an operating wharf is not an attraction"],
    ["Bridge neighbourhood — Gongchen Bridge and adjacent Hangzhou streets","Bridge crossings, lanes running toward the water, housing, community services and converted industrial buildings","The spatial relationship can be read on foot without claiming every façade is original","Museum and business hours change; residential alleys are not a stage"],
    ["Metropolitan waterfront — Beijing's Tongzhou canal area","Large-scale public banks, newer civic spaces, leisure use and the contrast with the canal's historic capital-supply role","Shows how a canal becomes metropolitan infrastructure and recreation","A restored urban bank is evidence of present planning, not automatic evidence of ancient fabric"],
    ["Town-scale exchange — a documented canal town or market street","Short links between landing place, bridge, street, shops and homes","Makes the movement-to-market chain easier to see","Verify that the waterway and street are actually connected to the Grand Canal property or system"]
  ]},
  {id:"walk-heading",type:"heading",level:2,text:"A two-hour field method: water, crossing, street, market"},
  {id:"walk",type:"list",ordered:true,items:["Start at a named canal, bridge, lock or wharf whose identity can be checked against an official heritage or transport source.","Spend ten minutes reading the water itself: flow, vessel type, bank treatment, gates, safety barriers and whether the edge is operational or recreational.","Follow one legal crossing. Notice whether it channels pedestrians, bikes, deliveries, buses or only sightseers.","Walk one or two streets perpendicular to the canal rather than staying on the scenic promenade.","Locate an ordinary exchange point such as a produce shop, repair business, convenience store or community service; do not photograph people intrusively.","Return by a parallel street and compare the commercial frontage, housing and access to the water.","Write one sentence for each layer: documented heritage, current system and present-day observation. Do not merge them into one claim."]},
  {id:"scenarios-heading",type:"heading",level:2,text:"Two travellers should choose different canal evidence"},
  {id:"scenarios",type:"comparison",title:"Use the question to choose the place",columns:[
    {heading:"The urban-history traveller",body:"Choose a walkable bridge neighbourhood with mapped heritage, side streets and public institutions. Spend less time collecting waterfront landmarks and more time tracing how crossings, warehouses and street grids relate."},
    {heading:"The contemporary-China traveller",body:"Choose a public viewpoint near an operating reach or a renewed metropolitan bank. Compare freight, maintenance, exercise and consumption, while stating clearly which observations are from that day."}
  ]},
  {id:"staged-heading",type:"heading",level:2,text:"How to avoid mistaking a heritage set for everyday life"},
  {id:"staged",type:"list",items:["A historic-style sign is branding until a conservation source identifies the building or street.","A busy snack lane proves current commerce, not continuity with an imperial market.","A museum explains selected evidence; it does not make the surrounding district unchanged.","Residents using a promenade show present public life, but one evening cannot establish a universal local habit.","A working barge is current transport evidence; identify the reach and source before generalizing its cargo or route.","Renovation can preserve, replace and reinterpret at the same time. Describe what is visible and cite what is documented."]},
  {id:"recovery-heading",type:"heading",level:2,text:"If the canal is closed, quiet or too polished"},
  {id:"recovery",type:"table",caption:"Recover the information task instead of forcing the scene",columns:["Problem","Switch to","What you can still learn"],rows:[
    ["Flood control, construction or event blocks the bank","Use the nearest legal crossing and a parallel street; consult the official map or museum","How the neighbourhood is connected even when the water edge is inaccessible"],
    ["No vessels appear","Read locks, mooring infrastructure and official traffic evidence; never promise a sighting","The corridor's operational design without inventing live activity"],
    ["The waterfront feels entirely commercialized","Step back into ordinary service streets, or move to a different documented section","How tourism and renewal have changed the relationship with the canal"],
    ["Rain or heat makes a long walk unwise","Choose one museum plus one short public-bank segment","Material evidence and urban form without treating endurance as insight"]
  ]},
  {id:"check-heading",type:"heading",level:2,text:"Final verification checklist"},
  {id:"check",type:"list",items:["Exact Chinese name and map pin for the canal section or heritage element","Whether the site is an inscribed component, a buffer/context area or simply nearby","Current public access, construction, flood-control and event notices","Museum, boat or venue hours checked on the operator's own channel","A lawful public viewpoint for any working port, lock or freight reach","One wet-weather or no-vessel alternative","Consent and privacy rules for any close photography of residents or workers"]},
  {id:"help",type:"callout",title:"Want a canal section that fits the rest of your trip?",body:"Tell Homeground which cities are already on your route and whether you care most about engineering, urban history, working transport or present-day neighbourhood life. A real planner can help select a lawful, useful section and recheck current access without turning the canal into a checklist of water towns.",tone:"neutral"},
  {id:"links",type:"internal-links",title:"Continue building context",items:[
    {label:"Build a Shanghai–Suzhou–Hangzhou–Nanjing route",href:"/guides/shanghai-suzhou-hangzhou-nanjing-route-order/",description:"Decide which lower-Yangtze cities earn a place before adding a canal theme."},
    {label:"Read Chinese timber buildings through dougong",href:"/guides/dougong-and-chinese-timber-frame-reading/",description:"Use construction evidence rather than old-looking atmosphere."},
    {label:"Compare woodblock and movable-type printing",href:"/guides/woodblock-and-movable-type-printing-decisions/",description:"See how material systems shaped urban production and exchange."},
    { label: "Follow rainwater through a Chinese sponge-city site", href: "/guides/how-to-read-a-chinese-sponge-city/", description: "Trace inlet, storage, overflow, maintenance and receiving water before calling one landscaped feature a working system." }
  ]},
  {id:"sources",type:"sources",title:"Official and independent sources",items:[
    {label:"Hero image — Gongchen Bridge, Grand Canal water and riverside public space, photographed 2023-11-22; not evidence of current event or access conditions",url:"https://commons.wikimedia.org/wiki/File:20231122_Gongchen_Bridge_01.jpg",publisher:"Windmemories — CC BY-SA 4.0; attribution only, no endorsement implied",reviewedAt:"2026-08-13"},
    {label:"Hero image licence — CC BY-SA 4.0",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-13"},
    {label:"The Grand Canal World Heritage property",url:"https://whc.unesco.org/en/list/1443/",publisher:"UNESCO World Heritage Centre",reviewedAt:"2026-08-13"},
    {label:"Northern Jiangsu canal as a modern freight corridor",url:"https://www.mot.gov.cn/xinwen/jiaotongyaowen/202601/t20260113_4197211.html",publisher:"Ministry of Transport of China",reviewedAt:"2026-08-13"},
    {label:"Hangzhou Grand Canal core-zone spatial controls",url:"https://www.hangzhou.gov.cn/art/2023/2/6/art_1229063387_1829308.html",publisher:"Hangzhou Municipal Government",reviewedAt:"2026-08-13"},
    {label:"Location, Urban Fabric and Transportation",url:"https://www.taylorfrancis.com/chapters/edit/10.4324/9780429244605-38/location-urban-fabric-transportation-fang-wang-bingyu-lin-qingyin-liu",publisher:"Routledge",reviewedAt:"2026-08-13"},
    {label:"Heritage Modernity: the Grand Canal and everyday life in Hangzhou",url:"https://escholarship.org/uc/item/7jj0h5hn",publisher:"University of California eScholarship",reviewedAt:"2026-08-13"}
  ]}
]} as const satisfies StructuredPageBody;

export default body;
