import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"Choose Tianluokeng for the iconic five-building composition and a route that can continue to Yuchanglou and Taxia. Choose Yunshuiyao for a gentler old-path-and-village day anchored by Heguilou and Huaiyuanlou. Choose Hongkeng for a dense Yongding cluster centred on Zhenchenglou; Gaobei for Chengqilou and a more compact stop; Chuxi for a more remote cluster whose value comes with a longer road commitment. One day should normally stay within one geographic group."},
{id:"whc",type:"callout",title:"‘Fujian Tulou’ is a serial World Heritage property",body:"UNESCO's property contains 46 tulou in six clusters and four individual buildings across Yongding, Nanjing and Hua'an. The famous aerial shape at Tianluokeng is one component, not the definition of every tulou or a single park containing all 46.",tone:"neutral"},
{id:"compare-heading",type:"heading",level:2,text:"Choose by the task you want the day to solve"},
{id:"compare",type:"table",caption:"Fujian tulou cluster comparison",columns:["Cluster or route","Best reason to choose","Planning cost"],rows:[
["Tianluokeng route, Nanjing","Upper and lower viewpoints of the five-building cluster, then Yuchanglou and Taxia on the official scenic route.","Mountain-road transfers and a scenic shuttle. The ticket is not the same as Yunshuiyao."],
["Yunshuiyao route, Nanjing","Heguilou, Huaiyuanlou and an old village path with a slower walking atmosphere.","It can feel more commercial and spread out; choose it for the combined village walk, not only one circular building."],
["Hongkeng, Yongding","Several building types in one village, including Zhenchenglou, with a strong first overview of Yongding Hakka tulou.","Do not append distant Nanjing clusters because they share the word tulou."],
["Gaobei, Yongding","Chengqilou and a compact named cluster.","A shorter visit than a broad village day; verify any internal access rules rather than assuming every upper floor is open."],
["Chuxi, Yongding","A more remote valley group with many named buildings and a stronger landscape commitment.","Longer road time and fewer easy public-transport assumptions; it needs a deliberate vehicle plan."],
]},
{id:"living",type:"callout",title:"These are living communities, not empty stage sets",body:"Some tulou remain homes or shared community spaces. A ticket does not grant access to every staircase, room or resident. Follow posted limits, ask before photographing people, keep drones out unless explicitly permitted and do not turn private life into an ‘authenticity’ test.",tone:"warning"},
{id:"transport-heading",type:"heading",level:2,text:"Transport is the decision, not an afterthought"},
{id:"transport",type:"list",items:["Identify whether your base is Xiamen, Nanjing County, Yongding or Longyan; similar cluster names hide long mountain-road gaps.","For rail, save the exact station name and the road transfer from that station. Nanjing County station is not Tianluokeng village.","For a driver or tour bus, put every included cluster, viewpoint, shuttle, meal and final drop-off in writing.","Do not accept ‘all major tulou’ without a map. Ask for drive times and the actual walking time at each village.","Protect daylight and the last return. Rural road or shuttle changes are more consequential than spending ten extra minutes in a courtyard."]},
{id:"tickets",type:"paragraph",text:"Nanjing's official price regulation lists Tianluokeng, Yunshuiyao and Hekeng as separate scenic products and says internal transport is voluntary and sold separately rather than bundled. Prices and scope can change, so use the current operator screen; the regulation is evidence of the product boundary, not a permanent 2026 price promise."},
{id:"final-check",type:"list",items:["The order names the exact county, cluster and buildings.","Drive time is separated from village time.","Scenic shuttle and entrance tickets are itemised.","Upper-floor and photography rules will be followed on site.","The return does not depend on an unverified last bus."]},
{id:"internal-links",type:"internal-links",title:"Connect the tulou day",items:[{label:"Xiamen hubs to Gulangyu ferry terminal",href:"/guides/xiamen-hubs-to-gulangyu-ferry-terminal/",description:"Keep the rural tulou day separate from Xiamen's ferry workflow."},{label:"China high-speed trains for first-time visitors",href:"/guides/china-high-speed-train-first-time-guide/",description:"Use exact station names and passport records before the road transfer."},{label:"Do you need a tour guide in China?",href:"/guides/do-you-need-a-tour-guide-in-china/",description:"Judge whether interpretation and rural transport justify support."}]},
{id:"consultation",type:"callout",title:"Need one cluster matched to your route?",body:"A Homeground travel consultant can compare the actual road chain, village priority and return for your dates. Share your base, available day length, group mobility and whether architecture, landscape or community context matters most.",tone:"neutral"},
{id:"sources",type:"sources",title:"Official, heritage and image sources reviewed",items:[{label:"Fujian Tulou World Heritage property",url:"https://whc.unesco.org/en/list/1113/",publisher:"UNESCO World Heritage Centre",reviewedAt:"2026-08-12"},{label:"Official Fujian heritage inventory of six clusters and four buildings",url:"https://fgw.fujian.gov.cn/ztzl/fjys/fjys/202311/t20231109_6293087.htm",publisher:"Fujian Provincial Development and Reform Commission",reviewedAt:"2026-08-12"},{label:"Nanjing scenic-product and shuttle price boundaries",url:"https://fgw.fujian.gov.cn/zfxxgkzl/zfxxgkml/yzdgkdqtxx/202009/t20200914_5385798.htm",publisher:"Fujian Provincial Development and Reform Commission",reviewedAt:"2026-08-12"},{label:"Hero: Tianluokeng by Windmemories, CC BY-SA 4.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:20121101_Tianluokeng_Tulou_01.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
