import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "最顺的走法通常是北京 → 西安 → 成都，或者完全反过来。先按国际航班的进出门户确定方向，再把住宿时间留给受保护的游览日。抵达、离境和跨城移动只有在完整的酒店到酒店链条通过下文检查后，才能得到 1 个有效半天。",
    },
    {
      id: "direction-comparison",
      type: "comparison",
      title: "两种强方向，以及一个通常较弱的起点",
      columns: [
        {
          heading: "北京 → 西安 → 成都",
          body: "适合从北京入境、从成都离境。西安位于中间，路线持续向前，不必折返。",
        },
        {
          heading: "成都 → 西安 → 北京",
          body: "如果反向国际航班更合适，这条线同样连贯，并在北京国际门户结束，不用再向南返回。",
        },
        {
          heading: "从西安开始，再去两端",
          body: "除非其中一个外端城市也是离境门户，否则通常会重复一段长距离。只有明显更好的航班或固定活动足以抵消折返时才选。",
        },
      ],
    },
    {
      id: "scope-boundary",
      type: "callout",
      tone: "neutral",
      title: "本页负责什么",
      body: "本页负责方向、进出门户和有效游览日的判断；不提供完整行程、实时班次、库存、票价或通用的城市夜数分配。",
    },
    {
      id: "gateway-heading",
      type: "heading",
      level: 2,
      text: "先看三种进出境情境",
    },
    {
      id: "gateway-scenarios",
      type: "table",
      caption: "路线方向应服从真实的国际机票",
      columns: ["进出门户情境", "对路线的影响", "对住宿分配的影响"],
      rows: [
        ["北京进、成都出", "除非按日期核验交通后不可行，否则采用北京 → 西安 → 成都。", "不用预留返回北京的一晚，重点保护成都离境。"],
        ["成都进、北京出", "把链条反过来，走成都 → 西安 → 北京。", "国际航班前的最后缓冲放在北京，不放在路线中段。"],
        ["同一城市往返", "三城走完后还要加入真实的返程段，或者删掉一个外端城市。", "返程和离境缓冲都会占用时间，不能藏在最后一城的游览配额里。"],
      ],
    },
    {
      id: "network-heading",
      type: "heading",
      level: 2,
      text: "铁路走廊已经成立，但车站字段会变化",
    },
    {
      id: "network-facts",
      type: "paragraph",
      text: "官方铁路资料确认了北京—西安连接，以及于 2017 年全线开通的西成高铁。这能支持线性路线，却不能让旧时刻表继续有效。西安东站已于 2026 年 6 月 30 日投入运营，北京和成都也都有多个客运枢纽。必须在 12306 查询准确日期，并把所选车次显示的车站原样写进路线。",
    },
    {
      id: "station-ledger",
      type: "table",
      caption: "城市名不等于枢纽名",
      columns: ["城市", "必须记录的字段", "要避免的错误"],
      rows: [
        ["北京", "机场、航站楼、火车站和酒店片区", "把北京西站、首都机场和大兴机场当成可互换节点"],
        ["西安", "西安北、西安东或其他车站；机场航站楼；酒店", "日期车次使用别站时仍照抄西安北站接送方案"],
        ["成都", "火车站；天府或双流机场；航站楼和酒店", "按错误机场设计离境日"],
      ],
    },
    {
      id: "half-day-heading",
      type: "heading",
      level: 2,
      text: "用有效半天给整段旅行记账",
    },
    {
      id: "half-day-rule",
      type: "callout",
      tone: "decision",
      title: "使用 0–1–2 账本",
      body: "一个受保护的完整游览日等于 2 个有效半天。抵达、离境和跨城日都从 0 开始；只有完整转场后仍留下稳定的上午或下午，才记 1。基线方案绝不把换酒店日记为 2。",
    },
    {
      id: "half-day-table",
      type: "table",
      caption: "安排任何必看预约前的保守计分",
      columns: ["日历区块", "基线分值", "何时可以得到 1 个有效半天"],
      rows: [
        ["国际抵达日", "0", "较早抵达，完成入境和取行李，已有确定的行李方案，并只安排酒店附近可替换活动"],
        ["北京—西安或西安—成都移动日", "0", "准确车次、两端进出站、退房、行李和抵达后仍留下一个连续本地区块"],
        ["国际离境日", "0", "较晚起飞，且在固定行李与去机场余量后仍留有受保护的本地区块"],
        ["同一住宿点的完整一天", "2", "没有换酒店、跨城截止点或长距离机场交通切开这一天"],
      ],
    },
    {
      id: "half-day-tests",
      type: "list",
      ordered: true,
      items: [
        "写下从酒店门口出发的时间，不要只抄火车或飞机时间。",
        "加入退房、处理行李、市内交通、车站或机场流程以及登乘。",
        "加入抵达枢纽、市内接驳、寄存或入住以及重新辨认方向的时间。",
        "确认候选活动当天开放、可以替换，而且从真实抵达点能够到达。",
        "如果延误会牺牲稀缺定时票或下一段已确认交通，就删掉这个半天。",
      ],
    },
    {
      id: "allocation-heading",
      type: "heading",
      level: 2,
      text: "按受保护的重点分配住宿，不要平均切三份",
    },
    {
      id: "city-role-matrix",
      type: "table",
      caption: "哪些情况能证明某城需要更多完整时间",
      columns: ["城市", "需要受保护游览日的信号", "压缩警告"],
      rows: [
        ["北京", "多个地理上分散的重点、长城一日，或稀缺的博物馆定时预约", "不要把北京的主要参观接在国际抵达或去西安的火车旁边"],
        ["西安", "兵马俑之外还有明确的市区重点，而不是只在车站停一下", "博物院不在市中心酒店区，进出本身要花时间；不要夹在两次铁路移动之间"],
        ["成都", "早间动物参观、饮食或街区重点，或者继续前往周边地区", "晚到之后不要默认仍能无恢复地承受第二天固定早起"],
      ],
    },
    {
      id: "allocation-workflow",
      type: "list",
      ordered: true,
      items: [
        "先固定国际机场，以及能保护出境航班的最后一晚住宿城市。",
        "标出每个景点的日期、闭馆日和分时预约依赖。",
        "给每个不可替代的重点一个完整游览日，或一个真正有效的半天。",
        "先把两次跨城移动按 0 个半天放进账本，等实时班次明确后再升级。",
        "儿童、慢行者、大件行李、时差或连续早起都要增加恢复空间。",
        "账本为负时，换门户、删掉最弱的一城或减少重点；不要从转场日借时间。",
      ],
    },
    {
      id: "scenario-heading",
      type: "heading",
      level: 2,
      text: "同一张地图，不同旅客会得出不同路线",
    },
    {
      id: "traveller-scenario-one",
      type: "callout",
      tone: "neutral",
      title: "情境 1：两人、9 晚、异地进出",
      body: "2 人从北京入境，住 9 晚后从成都离境。10 个日历日中，抵达、离境和 2 次移动都先记 0，保守计算只剩 6 个完整游览日当量。线性方向成立，但这 6 天必须按重点分配；写着 10 天，不等于有 10 个游览日。",
    },
    {
      id: "traveller-scenario-two",
      type: "callout",
      tone: "warning",
      title: "情境 2：8 晚、亲子、北京往返",
      body: "一家人带孩子从北京进出，共 8 晚。9 个日历日里包含抵达、离境、2 次向前移动和成都返回北京，保守基线只剩 4 个完整游览日当量。即使挣到 1 个半天，也无法消除脆弱性。改从成都离境、减少城市或增加夜数，结论才会变化。",
    },
    {
      id: "switch-heading",
      type: "heading",
      level: 2,
      text: "哪些条件会改变答案",
    },
    {
      id: "switch-conditions",
      type: "comparison",
      title: "保留、反转还是缩短链条",
      columns: [
        {
          heading: "保留线性三城",
          items: [
            "不同的入境和离境门户消除了折返。",
            "每座城市至少保留一个受保护且彼此不同的重点。",
            "不把定时参观放在移动日，半天账本仍不为负。",
          ],
        },
        {
          heading: "把方向反过来",
          items: [
            "可行的国际航班更适合成都进、北京出。",
            "按日期核验的闭馆或固定活动让反向顺序明显更安全。",
            "准确交通仍能让西安保持中间站。",
          ],
        },
        {
          heading: "缩短路线或增加时间",
          items: [
            "同城往返增加了第三次国内转场和最后缓冲。",
            "某城没有任何能通过删减测试的重点。",
            "行动能力、家庭节奏或连续早起所需恢复超出账本余量。",
          ],
        },
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "故障恢复：先保护路线链条，再保护愿望清单",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "路线假设失效时怎么办",
      columns: ["故障", "立即恢复", "后续修正"],
      rows: [
        ["抵达延误吃掉首个区块", "取消可替换活动，直接去酒店", "把第一次受保护参观留在后续完整日"],
        ["火车使用了另一个车站", "登车前重新计算酒店到车站的移动", "删除移动日活动，并更新所有已保存的接驳说明"],
        ["航班在城市的另一个机场", "先保护航班，按官方地面交通信息移动", "余量不足时更早回到离境城市或机场区域"],
        ["定时景点没有名额", "改用可替换的本地模块", "除非它是全程核心，否则不要为它反转整个路线"],
        ["体力比预计低", "保留当晚酒店，取消可选外出", "把一个半天还给下一站，或删除最弱停留"],
      ],
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "按依赖顺序预订",
    },
    {
      id: "booking-order",
      type: "list",
      ordered: true,
      items: [
        "确认入出境资格、国际机场和机票变更条件。",
        "核对决定旅行价值的北京、西安、成都参观项目的官方闭馆与预约规则。",
        "用准确日期和枢纽查询当前 12306 车次，以及可能采用的国内航班。",
        "等车站、机场和受保护日都清楚后再选酒店。",
        "在运营字段最终复核前，移动日活动一律保持可替换。",
      ],
    },
    {
      id: "final-check",
      type: "table",
      caption: "最终核验字段",
      columns: ["阶段", "核验内容", "官方位置"],
      rows: [
        ["购买国际机票前", "进出机场、出票结构和入境条件", "航空公司及相关移民管理机关"],
        ["铁路开放预订时", "日期、车次、准确车站对、乘车人信息和票务条件", "中国铁路 12306"],
        ["每次预订后", "机场或车站、航站楼、行李、酒店地址和取消条件", "承运人、12306、机场和酒店"],
        ["每次移动前不久", "运营通知、出发点、开放或预约规则、天气和本地接驳", "具名运营方、场馆和地方机关"],
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      tone: "warning",
      title: "不要从本文照抄运营细节",
      body: "车次结构、车站、航班、航站楼和景点规则都会变化。稳定的是线性链条与半天核算方法；所有日期字段都要在 12306、航空公司或机场以及场馆官网重新核验。",
    },
    {
      id: "editorial-judgment",
      type: "callout",
      tone: "neutral",
      title: "Homeground 编辑判断",
      body: "把转场从 0 开始是 Homeground 的保守规划规则，不是运营方承诺。它用来保护稀缺参观；真正挣到的半天仍可安排可替换街区、用餐或休息。",
    },
    {
      id: "help-cta",
      type: "callout",
      tone: "decision",
      title: "需要人工检查吗？",
      body: "留下日期、人数和大致预算，再附上真实的抵达与离境机场。Homeground 可以帮助找出最弱转场，以及会改变路线顺序的关键条件。",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "继续规划",
      items: [
        { label: "浏览中国旅行规划指南", href: "/zh/plan/", description: "回到规划集合页，选择下一项决策。" },
        { label: "判断是否选择异地进出（开口程）", href: "/zh/guides/china-open-jaw-flights-route-planning/", description: "比较异地进出与返回同一门户的完整成本。" },
        { label: "选择单一基地还是多基地串联", href: "/zh/guides/china-hub-and-spoke-or-multi-base-route/", description: "先确定路线结构，再安排这条三城顺序。" },
        { label: "第一次乘中国高铁", href: "/zh/guides/china-high-speed-train-first-time-guide/", description: "路线确定后，再处理乘车人信息和车站流程。" },
        { label: "检查行程是否太赶", href: "/zh/guides/is-your-china-itinerary-too-rushed/", description: "用酒店移动、固定预约和恢复时间测试整段旅行。" },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "已核验的官方来源",
      items: [
        { label: "中国铁路车票与车站查询", url: "https://www.12306.cn/en/index.html", publisher: "中国铁路 12306", reviewedAt: "2026-08-13" },
        { label: "西成高铁开通资料", url: "https://www.nra.gov.cn/tlfc/yxfc/202204/t20220405_293365.shtml", publisher: "国家铁路局", reviewedAt: "2026-08-13" },
        { label: "西安东站投入运营", url: "https://en.xa.gov.cn/MediaCenter/News/2072253459180654594.html", publisher: "西安市人民政府", reviewedAt: "2026-08-13" },
        { label: "公共航空运输旅客服务管理规定", url: "https://www.caac.gov.cn/XXGK/XXGK/MHGZ/202103/t20210315_206814.html", publisher: "中国民用航空局", reviewedAt: "2026-08-13" },
        { label: "北京八站两场交通格局", url: "https://www.beijing.gov.cn/ywdt/yaowen/202511/t20251121_4290581.html", publisher: "北京市人民政府", reviewedAt: "2026-08-13" },
        { label: "成都双机场航班调整公告", url: "https://www.cdairport.com/news_detail.aspx?cid=6393&page=1&t=60", publisher: "四川省机场集团", reviewedAt: "2026-08-13" },
        { label: "故宫博物院开放与参观信息", url: "https://www.dpm.org.cn/Visit.html", publisher: "故宫博物院", reviewedAt: "2026-08-13" },
        { label: "秦始皇帝陵博物院预约与参观指南", url: "https://www.bmy.com.cn/guide/", publisher: "秦始皇帝陵博物院", reviewedAt: "2026-08-13" },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
