import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Dujiangyan Irrigation System and Mount Qingcheng can share one day only if ‘Mount Qingcheng’ means a deliberately shortened Front Mountain visit and you accept that at least one site will be selective. A same-day tour product or their joint World Heritage name does not make them one continuous attraction, remove the transfer or erase the mountain's stairs. Split them when you want to understand all three water-control works, follow the temple landscape beyond a token stop, travel slowly, or protect the day against rain and queues. Back Mountain is a different nature-led outing and does not belong in this one-day pair." },
  { id: "answer", type: "callout", title: "The direct decision", tone: "decision", body: "Combine them if you can start early, hold separate valid entries, have no fixed evening departure and are willing to name your cut before setting out. Choose Dujiangyan alone for engineering or a more bounded day with less mountain ascent, but do not assume it is step-free. No continuous step-free route linking the three works was verified for this article; ask the operator about the current accessible entrances, links and any remaining steps. Choose Qingcheng Front Mountain alone for a real mountain-and-Daoist-temple day. Give them two days—or sleep in Dujiangyan—if both are priorities rather than two labels to collect. This is Homeground's time-allocation judgement, not an official duration or a promise that every lift, hall or path will operate." },

  { id: "decision-heading", type: "heading", level: 2, text: "Can the two sites honestly fit into one day?" },
  { id: "decision-copy", type: "paragraph", text: "Yes, but ‘fit’ has three meanings. It may mean entering both places, seeing one recognisable feature at each and returning on time. It may mean understanding why each half of the World Heritage property matters. Or it may mean completing the route that first drew you there. Only the first is easy to advertise as a package. The second requires a selective plan. The third normally needs separate days. The strongest one-day version protects a coherent core at one site and a deliberately limited core at the other; it does not pretend to be two complete visits." },
  { id: "decision-comparison", type: "comparison", title: "Choose the promise you are actually making", columns: [
    { heading: "Combine in one day", body: "Best for a fit, early-starting traveller who wants contrast more than completeness.", items: ["Front Mountain only", "One clear heritage priority", "A written cut order", "No same-evening flight or long-distance rail deadline"] },
    { heading: "Choose one", body: "Best when the day is bounded or one subject clearly matters more.", items: ["Dujiangyan for living engineering", "Front Mountain for wooded ascent and Daoist sites", "More attention, fewer transfers", "Easier recovery when conditions change"] },
    { heading: "Split or stay overnight", body: "Best when both sites are genuine priorities or the group needs a slower pace.", items: ["Room for the three water-control components", "Room for a meaningful temple path", "Less dependence on lift queues", "A safer choice in short daylight or unsettled weather"] },
  ] },

  { id: "property-heading", type: "heading", level: 2, text: "Why does one World Heritage name not mean one visitor site?" },
  { id: "property-copy", type: "paragraph", text: "UNESCO inscribed Mount Qingcheng and the Dujiangyan Irrigation System together in 2000, but for different attributes. Dujiangyan demonstrates water management that still works: the river is divided, excess flow and sediment are handled, and water is admitted towards the Chengdu Plain without a conventional blocking dam. Mount Qingcheng carries the religious and architectural association with the development of Daoism through its temple landscape. The shared inscription explains why the two belong in one cultural conversation. It does not create one gate, one ticket, one walking circuit or one operating schedule." },
  { id: "relationship-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/two-sites-one-heritage.svg", alt: "Editorial diagram showing Mount Qingcheng and the Dujiangyan Irrigation System under one World Heritage inscription, with Front Mountain marked only as this article's visitor task", width: 1600, height: 1000, caption: "UNESCO inscribed Mount Qingcheng with the Dujiangyan Irrigation System. This article uses Front Mountain only for the combined-day visitor task. The diagram does not map UNESCO boundaries, is not to scale and is not a transport map." },
  { id: "property-table", type: "table", caption: "Keep the two visitor jobs separate before joining the day", columns: ["Place or visitor task", "The question it answers", "Core evidence on site", "What a rushed visit loses"], rows: [
    ["Dujiangyan Irrigation System", "How can a river be divided, relieved of excess water and sediment, and channelled onto a plain without a conventional dam?", "Yuzui, Feishayan and Baopingkou read as one working system", "The three names become disconnected photo stops"],
    ["Mount Qingcheng — this page uses Front Mountain", "How is Daoist history expressed through a mountain path, temples and changing elevation?", "The relationship between wooded ascent, named religious buildings and the upper route", "A gate photograph or cableway ride replaces the temple landscape"],
  ] },

  { id: "mountain-meaning-heading", type: "heading", level: 2, text: "Which Mount Qingcheng do you mean: Front Mountain or Back Mountain?" },
  { id: "mountain-meaning-copy", type: "paragraph", text: "For this decision, Mount Qingcheng means the Front Mountain visitor task: a path-and-temple visit for which the current official ticket page lists admission, cableway and boat as separate operating layers. A 2026 Chengdu visitor-information item lists Front Mountain and Back Mountain separately; this page treats Back Mountain as a separate nature-and-walking task whose own access and conditions must be checked. That naming and planning distinction must not be read as a claim that modern visitor areas reproduce the technical UNESCO property boundary or as proof of current Back Mountain operation. Treating the two visitor tasks as interchangeable is still the fastest way to make an impossible schedule: a traveller who expects a substantial Back Mountain hike has already chosen a separate day, not a compact addition to Dujiangyan." },
  { id: "front-back-comparison", type: "comparison", title: "Do not solve the wrong mountain problem", columns: [
    { heading: "Front Mountain", body: "The only Qingcheng component considered in the combined-day plan.", items: ["Daoist heritage is the organising purpose", "Stairs, paths and optional lift layers still consume a substantial block", "A shortened visit must name which upper or lower section it will omit"] },
    { heading: "Back Mountain", body: "A separate nature-and-hiking decision not covered by this guide.", items: ["Do not substitute it silently for Front Mountain", "Do not add it to Dujiangyan as a third zone", "Check its own access, weather and trail notices before travel"] },
  ] },
  { id: "front-boundary", type: "callout", title: "A useful naming rule", tone: "warning", body: "If a tour or driver says only ‘Qingcheng Mountain’, ask for the Chinese entrance name and whether the plan is 前山 (Front Mountain) or 后山 (Back Mountain). This page does not certify a transfer product or a current route; it prevents two different mountain tasks from being sold as the same stop." },

  { id: "dujiangyan-heading", type: "heading", level: 2, text: "What must remain in a worthwhile Dujiangyan visit?" },
  { id: "dujiangyan-copy", type: "paragraph", text: "Protect the relationship among Yuzui, Feishayan and Baopingkou. UNESCO identifies them as the three key works of the weir system, not three unrelated monuments. Water first meets the fish-mouth-shaped dividing work at Yuzui; Feishayan provides a relief and sediment-handling layer; Baopingkou is the narrow diversion passage through which controlled flow enters the irrigation network. The exact water level and visual drama change. The intellectual task does not: stand where you can read direction, elevation and the next component before moving on." },
  { id: "dujiangyan-observe", type: "list", ordered: true, items: [
    "At Yuzui, locate the upstream river and trace the split towards the inner and outer channels. Do not look for a giant wall blocking the river; the absence of that wall is part of the engineering idea.",
    "Between Yuzui and Feishayan, keep asking where excess flow and sediment can leave the route towards Baopingkou. A low-water day may require more attention to labels and channel geometry than to spectacle.",
    "At Feishayan, read the overflow relationship rather than judging the place by height. Its job belongs to the system, not to a postcard silhouette.",
    "At Baopingkou, look for the constricted passage and the rock mass beside it. This is the admission point towards the plain, not simply a scenic gorge.",
    "Use one elevated or cross-river view only if it helps reconnect the three works. Bridges, temples and towers can add context, but they should not replace the hydraulic sequence when time is short.",
  ] },
  { id: "yuzui-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/yuzui-1600.webp", alt: "Yuzui dividing point and adjoining channels at the Dujiangyan Irrigation System", width: 1600, height: 1000, caption: "At Yuzui, follow the direction of the split rather than searching for a conventional dam wall. Current flow varies with season and management." },
  { id: "feishayan-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/feishayan-1600.webp", alt: "Wide view of the low Feishayan spillway within the Dujiangyan Irrigation System", width: 1600, height: 1000, caption: "Feishayan is low and broad in this location-verified view, so confirm its outline on the onsite panel instead of looking for a high dam wall. Read it through its overflow and sediment-handling relationship with the other works; the photograph does not establish the flow or access conditions on your date." },

  { id: "qingcheng-heading", type: "heading", level: 2, text: "What must remain in a worthwhile Front Mountain visit?" },
  { id: "qingcheng-copy", type: "paragraph", text: "Do not reduce Front Mountain to a summit claim. UNESCO's significance rests on the association between Mount Qingcheng and Daoism and on a series of temples in the mountain landscape. A meaningful shortened visit therefore needs at least one transition from entrance landscape to wooded ascent, one named religious building read in context, and an honest turning point. A lift can move you across part of the elevation; it cannot make the remaining stairs, queues, temple access or descent disappear. If the group cannot protect that minimum, choose Dujiangyan only and give Qingcheng another day." },
  { id: "qingcheng-observe", type: "list", ordered: true, items: [
    "At the lower approach, confirm that you are at Front Mountain and read the current map before committing to an upper target.",
    "Notice how buildings are reached through changing elevation and woodland rather than treating each hall as an isolated attraction.",
    "At a named temple such as Tianshi Cave or Shangqing Palace, distinguish the place's religious function and repaired architectural fabric from a generic ‘ancient mountain’ label.",
    "Choose the turnaround while everyone can still descend safely. Reaching the highest available point is optional; preserving a coherent ascent and descent is not.",
    "If using the cableway or boat, verify its live operation and last service onsite. Admission does not include these layers, and a queue can consume the time that made the combined day possible.",
  ] },
  { id: "qingcheng-steps-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/qingcheng-path-1600.webp", alt: "Wooden Jixian Bridge and adjoining uphill path in the forest on Mount Qingcheng Front Mountain", width: 1600, height: 1000, caption: "Jixian Bridge shows how the Front Mountain visit unfolds through a wooded route rather than a single monument. The photograph cannot certify today's surface condition, direction of travel or step-free access." },
  { id: "qingcheng-temple-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/qingcheng-temple-1600.webp", alt: "Tiled roofs and inscribed upper facade of Zhenwu Palace on Mount Qingcheng Front Mountain", width: 1600, height: 1000, caption: "Zhenwu Palace, also identified with Zushi Hall, anchors a named religious place in the mountain landscape. Confirm access and respect worship boundaries; visible architecture does not mean every interior permits entry or photography." },
  { id: "qingcheng-cableway-figure", type: "figure", src: "/images/guides/dujiangyan-qingcheng-mountain-same-day-or-separate/qingcheng-cableway-1600.webp", alt: "Cableway cabins above the wooded slopes of Mount Qingcheng Front Mountain", width: 1600, height: 1000, caption: "The cableway can change the elevation budget, but it is an optional operating layer rather than proof of a step-free route. Recheck service and queues on the day." },

  { id: "combined-heading", type: "heading", level: 2, text: "How should a combined day actually run?" },
  { id: "combined-copy", type: "paragraph", text: "Build the day around two protected blocks, not a list of hourly promises. Before leaving your base, confirm separate entry for both sites, the exact Front Mountain entrance, the weather alert level, current lift or boat status if you depend on them, and the final return task. For the second site, work backwards from the earlier of its last usable admission and the last service your route requires. Subtract the verified transfer and the exit-to-return buffer. Keep the transfer only if the remainder can still connect all three Dujiangyan works, or complete a lower-to-middle Front Mountain path, read one named religious place from an open public area and descend safely. Otherwise stop with the anchor. Engineering-first travellers should treat the mountain as the cuttable half; mountain-first travellers should set a firm turnaround and accept a reduced Dujiangyan circuit. The wrong order is the one that leaves the priority site until after its usable time has disappeared." },
  { id: "combined-sequence", type: "list", ordered: true, items: [
    "Name the anchor: Dujiangyan engineering or Front Mountain temple landscape. Write down the one site that must remain coherent.",
    "Confirm both admissions separately. A World Heritage label, one booking confirmation or one transport reservation is not proof of two valid entries.",
    "Confirm the exact transfer and a fallback endpoint from live maps or the provider you are actually using. This page deliberately does not freeze a bus number or driving time.",
    "Complete the anchor's minimum observation sequence before adding optional bridges, upper targets, commercial streets or a long meal.",
    "At the transfer decision, calculate the remaining usable block from the live last-admission or required-service cutoff, transfer, exit and return buffer. If the compact core no longer fits—or weather, knees or queues fail—switch to the single-site day.",
    "At the second site, follow the pre-agreed compact core. Do not recover lost time by rushing on wet steps, crossing a closure or skipping the return margin.",
  ] },
  { id: "combined-options", type: "table", caption: "Two honest combined-day versions", columns: ["Version", "Protect first", "Keep at the second site", "Cut before it cuts the day"], rows: [
    ["Engineering-led", "Yuzui → Feishayan → Baopingkou as one explanation", "Lower-to-middle Front Mountain path plus one named temple and a fixed turnaround", "Summit ambition, Back Mountain, long old-town detour and unverified lift dependence"],
    ["Mountain-led", "A coherent Front Mountain ascent, named temple and safe descent", "The three-part Dujiangyan core, using only currently open links", "Extra upper targets, unrelated city stops, evening show and a fixed intercity connection"],
  ] },
  { id: "cut-callout", type: "callout", title: "The cut order", tone: "warning", body: "Cut Back Mountain first because it is a separate task. Then cut optional upper targets or peripheral town time. If the remaining plan can no longer connect Yuzui, Feishayan and Baopingkou, or can no longer include a meaningful Front Mountain path and named temple, stop calling it a two-site heritage day and keep only the anchor." },

  { id: "split-heading", type: "heading", level: 2, text: "Who should split the sites or stay overnight?" },
  { id: "split-copy", type: "paragraph", text: "Two days are not an indulgence when the second site's value depends on attention. Split the visits for anyone who reads interpretation slowly, photographs architecture carefully, wants both upper and lower Front Mountain sections, or needs frequent rests. An overnight becomes useful when it protects an early mountain start, removes a return-to-Chengdu squeeze or lets weather move one component to the next morning. It is not automatically useful because the places are famous; accommodation creates its own check-in, luggage and cancellation decisions, which belong to a separate stay page." },
  { id: "scenarios", type: "table", caption: "Match the allocation to the traveller", columns: ["Traveller situation", "Best allocation", "Why", "Boundary"], rows: [
    ["Two fit adults with three Chengdu days, strong interest in engineering and only moderate interest in temples", "Combined day, Dujiangyan anchor", "The water system stays coherent while Front Mountain remains a selective contrast", "No Back Mountain and no fixed evening train"],
    ["Parents who walk slowly or protect their knees", "Dujiangyan only, or two days", "Transfers, mountain stairs and uncertain lift queues compound fatigue", "A lift is not a step-free-route guarantee"],
    ["Daoist history and mountain walking are the main reason for the excursion", "Front Mountain full day; Dujiangyan another day if desired", "The path-and-temple relationship needs time beyond a gate or summit photo", "Do not replace Front Mountain with Back Mountain without changing the purpose"],
    ["Family with a same-evening flight, border movement or long-distance rail booking", "Choose one or skip the outer day", "Two live operating systems plus a transfer leave too many failure points before a fixed departure", "Move the fixed departure to another day rather than erasing the buffer"],
    ["One night available in Dujiangyan and both sites matter", "Split across arrival afternoon and next morning according to live entry and weather", "The second date provides recovery capacity", "Select lodging separately; this page does not recommend a district or hotel"],
  ] },

  { id: "live-heading", type: "heading", level: 2, text: "Which live rules can overturn the plan?" },
  { id: "live-copy", type: "paragraph", text: "The current official tourism portal lists Dujiangyan and Front Mountain as separate ticket scopes. It says admission excludes optional transport and service layers, allows foreign visitors to select a passport or foreign residence permit and use a staffed channel, and tells visitors to follow capacity or closure controls. Recent 2026 notices also show that entry can be paused at high attendance. These facts close today's planning questions; they do not guarantee the same screen, slot, hours, refund flow, cableway operation or open path on your date. Recheck during the travel week and again on the morning of the mountain visit." },
  { id: "live-table", type: "table", caption: "Keep each control in its own layer", columns: ["Layer", "What to verify", "What it does not prove", "Recovery"], rows: [
    ["Separate admissions", "Correct date, time band, document and site name for Dujiangyan and Front Mountain", "One booking covers both places", "Keep the confirmed site and release the other if its entry cannot be secured"],
    ["Passport workflow", "The live official international or passport option and staffed-check procedure", "Every third-party app accepts the same document", "Use the current official portal or staffed window; do not invent an identity-number workaround"],
    ["Cableway, boat or sightseeing vehicle", "Live operation, queue and last service if the plan depends on it", "Admission includes the service or removes all climbing", "Shorten the mountain target or convert to the single-site day"],
    ["Path, hall and bridge access", "Current onsite signs and closure notices", "A standing map means every link or interior is open", "Use the nearest coherent loop; never cross a barrier to preserve an itinerary"],
    ["Weather and capacity", "Official warning, mountain status and admission availability", "A paid reservation overrides a safety closure or crowd pause", "Move the mountain, keep only Dujiangyan if open, or use a city day"],
  ] },

  { id: "recovery-heading", type: "heading", level: 2, text: "What if rain, queues or a closed service break the day?" },
  { id: "recovery-table", type: "table", caption: "Recover the purpose, not every stop", columns: ["Failure", "Immediate decision", "Keep", "Drop"], rows: [
    ["Rain or a geological/weather warning affects the mountain", "Do not begin or continue an exposed or closed path; follow the official notice", "Dujiangyan only if it remains officially open and safe, or a Chengdu city alternative", "The mountain, scenic detours and any attempt to ‘wait it out’ beyond official guidance"],
    ["Cableway or boat is unavailable", "Recalculate the walking route before entering the upper section", "A lower Front Mountain path and one named temple if safe and worthwhile", "The summit target and the assumption that paid admission requires completion"],
    ["The first site runs long", "Keep the anchor coherent and cancel the second before the return buffer disappears", "The three water works or the chosen mountain circuit", "A token gate photograph at the second site"],
    ["One site has no suitable admission", "Use the other as a full visit", "One complete subject and an unhurried return", "Buying through an unverified seller or entering details that do not match the passport"],
    ["Parents, children or knees tire early", "Turn at the next safe staffed or signed point", "One lower-elevation observation sequence and rest", "Upper targets, extra bridges and the idea that both names must appear in the photo album"],
    ["The return transfer becomes uncertain", "Leave the second site early and protect the verified return chain", "A calm exit and contingency margin", "Dinner/show add-ons and every optional last stop"],
  ] },
  { id: "recovery-copy", type: "paragraph", text: "A single-site day is the designed fallback, not a consolation prize. If Dujiangyan remains, use the recovered time to connect the three works and read one elevated view. If Front Mountain remains, choose a safe path-and-temple sequence rather than adding a commercial stop. If neither is safe or available, return to Chengdu and use a city guide. The loss to avoid is not a missing attraction; it is turning a recoverable change into a late, wet or document-risky return." },

  { id: "checklist-heading", type: "heading", level: 2, text: "What should you verify before committing the day?" },
  { id: "checklist", type: "list", items: [
    "Decide whether the mountain means Front Mountain. If it means Back Mountain, give it a separate plan.",
    "Choose one of four shapes: Dujiangyan only, Front Mountain only, selective combined day, or two days/overnight.",
    "Name the anchor and the minimum coherent sequence you refuse to cut.",
    "Secure separate, matching-date admissions with the correct passport or residence-document workflow.",
    "Reopen the official tourism portal for hours, time bands, capacity messages, refunds and optional-service status.",
    "Check the mountain weather warning and path notice, not only a general Chengdu forecast.",
    "Confirm the exact transfer and return chain from the station, hotel or vehicle you will actually use; keep a contingency margin.",
    "Agree on a turnaround for the mountain and a cancellation point for the second site before the day starts.",
    "Do not attach Panda Valley, Back Mountain, a fixed evening performance or a same-day long-distance departure to the combined plan.",
  ] },
  { id: "internal-links", type: "internal-links", title: "Use the right guide for each nearby decision", items: [
    { label: "Chengdu Panda Base or Dujiangyan Panda Valley", href: "/guides/chengdu-panda-base-or-dujiangyan-panda-valley/", description: "Use this only if pandas are a separate priority; do not add Panda Valley as a third stop to the combined heritage day." },
    { label: "Sanxingdui Museum booking and gallery order", href: "/guides/sanxingdui-museum-booking-and-gallery-order/", description: "Compare a museum-led outer day with the Dujiangyan–Qingcheng heritage decision instead of stacking them." },
    { label: "Leshan Giant Buddha: land or boat", href: "/guides/leshan-giant-buddha-land-or-boat-visit/", description: "Keep Leshan as its own Chengdu-area day decision; its access trade-offs are different." },
  ] },
  { id: "facts", type: "callout", title: "Evidence boundary — reviewed 4 September 2026", tone: "neutral", body: "UNESCO and official heritage sources establish the two components, the living irrigation function, the three principal water works and Mount Qingcheng's Daoist-temple significance. The live official tourism portal and dated 2025–2026 notices support separate entry scopes, current passport handling, optional-service exclusions and dated examples of capacity or weather controls. The combine/split test, anchor rule, cut order and recovery choices are Homeground planning judgements. They are not official durations, transport instructions, accessibility certification or operating guarantees." },
  { id: "cta", type: "paragraph", text: "If your Chengdu dates are fixed but walking capacity, passport booking or the choice between one long day and an overnight still feels unclear, share the actual travellers, dates and non-negotiable departure. A human planner can test the day against current entries and conditions without turning both sites into a rushed checklist." },

  { id: "sources", type: "sources", title: "Sources and verification", items: [
    { label: "Mount Qingcheng and the Dujiangyan Irrigation System", url: "https://whc.unesco.org/en/list/1001", publisher: "UNESCO World Heritage Centre", reviewedAt: "2026-09-04" },
    { label: "World Heritage property documents and technical boundary records", url: "https://whc.unesco.org/en/list/1001/documents/", publisher: "UNESCO World Heritage Centre", reviewedAt: "2026-09-04" },
    { label: "2023 periodic reporting record for the World Heritage property", url: "https://whc.unesco.org/document/217566", publisher: "UNESCO World Heritage Centre", reviewedAt: "2026-09-04" },
    { label: "Current official ticket, document, opening and refund guidance", url: "https://www.djy517.com/online.html?channelCode=mpyd", publisher: "Dujiangyan Tourism official portal", reviewedAt: "2026-09-04" },
    { label: "Official Dujiangyan tourism portal and notice entry", url: "https://www.djy517.com/", publisher: "Dujiangyan Tourism Business Co. / scenic-area platform", reviewedAt: "2026-09-04" },
    { label: "National scenic-area profile for Qingchengshan–Dujiangyan", url: "https://www.scfjyl.org.cn/web/info/23329", publisher: "Sichuan Scenic and Historic Areas Association", reviewedAt: "2026-09-04" },
    { label: "Official account of Yuzui, Feishayan and Baopingkou", url: "https://www.neac.gov.cn/seac/c103391/202308/1166522.shtml", publisher: "National Ethnic Affairs Commission", reviewedAt: "2026-09-04" },
    { label: "2025 provincial record of the international ticket-booking platform", url: "https://www.sc.gov.cn/10462/10464/10797/2025/6/16/d4ea87e678af4e888b7ff8158e13d462.shtml", publisher: "People's Government of Sichuan Province", reviewedAt: "2026-09-04" },
    { label: "3 May 2026 Front Mountain admission pause", url: "https://news.chengdu.cn/2026/0503/69f6a4998f007a160c63046d.shtml", publisher: "Red Star News quoting Qingchengshan–Dujiangyan Scenic Area Administration", reviewedAt: "2026-09-04" },
    { label: "9 June 2026 Chengdu visitor information listing Front Mountain and Back Mountain separately", url: "https://news.chengdu.cn/2026/0609/6a27c281cfd50212c36c5db5.shtml", publisher: "Red Star News republishing Chengdu Release visitor information", reviewedAt: "2026-09-04" },
    { label: "2025 detailed plan for Dujiangyan and Qingcheng Front/Back Mountain areas", url: "https://lcj.sc.gov.cn/scslyt/c1055/2025/2/10/4a85d44202364f12a8ba7eb391f0bf40/files/%E3%80%8A%E9%9D%92%E5%9F%8E%E5%B1%B1%E2%80%94%E9%83%BD%E6%B1%9F%E5%A0%B0%E9%A3%8E%E6%99%AF%E5%90%8D%E8%83%9C%E5%8C%BA%E9%83%BD%E6%B1%9F%E5%A0%B0%E6%99%AF%E5%8C%BA%E5%8F%8A%E9%9D%92%E5%9F%8E%E5%89%8D%E5%90%8E%E5%B1%B1%E7%89%87%E5%8C%BA%E8%AF%A6%E7%BB%86%E8%A7%84%E5%88%92%E3%80%8B.pdf", publisher: "Sichuan Forestry and Grassland Administration", reviewedAt: "2026-09-04" },
    { label: "2025 Front Mountain cableway maintenance notice", url: "https://news.chengdu.cn/2025/1119/691d0680869dfd455d6f321e.shtml", publisher: "Chengdu municipal news platform carrying scenic-area notice", reviewedAt: "2026-09-04" },
    { label: "2025 official extreme-weather closure example for Qingchengshan–Dujiangyan", url: "https://wlt.sc.gov.cn/scwlt/hydt/2025/8/29/932542f7ce2f47459f481435cef0a9ba.shtml", publisher: "Sichuan Provincial Department of Culture and Tourism", reviewedAt: "2026-09-04" },
    { label: "Google result set for Dujiangyan and Mount Qingcheng same-day decision", url: "https://www.google.com/search?q=Dujiangyan+Mount+Qingcheng+same+day", publisher: "Google demand/competition evidence only", reviewedAt: "2026-09-04" },
    { label: "Current traveller question on one day or separate visits", url: "https://www.reddit.com/r/travelchina/comments/1vjbqiv/first_time_in_china_itinerary_check/", publisher: "Reddit traveller-question evidence only", reviewedAt: "2026-09-04" },
    { label: "Current family itinerary discussion warning that the combination is a long busy day", url: "https://www.reddit.com/r/travelchina/comments/1tztxat/itinerary_advice_shanghai_xian_chengdu_chongqing/", publisher: "Reddit traveller-question evidence only", reviewedAt: "2026-09-04" },
    { label: "Yuzui photograph — Qiu Xingxiang; Homeground crop, resize and WebP conversion under CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E9%83%BD%E6%B1%9F%E5%A0%B0%E9%B1%BC%E5%98%B4.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
    { label: "Feishayan photograph — Shizhao; Homeground crop, resize and WebP conversion under CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:%E9%A3%9E%E6%B2%99%E5%A0%B0.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
    { label: "Jixian Bridge photograph — Kcx36; Homeground crop, resize and WebP conversion under CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E5%9F%8E%E5%B1%B1%E9%9B%86%E4%BB%99%E6%A1%A5.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
    { label: "Zhenwu Palace photograph — Kcx36; Homeground crop, resize and WebP conversion under CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E5%9F%8E%E5%B1%B1%E7%9C%9F%E6%AD%A6%E5%AE%AB_01.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
    { label: "Front Mountain cableway photograph — Kcx36; Homeground crop, resize and WebP conversion under CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E5%9F%8E%E5%B1%B1%E7%B4%A2%E9%81%93_02.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
    { label: "Creative Commons Attribution-ShareAlike 3.0 licence", url: "https://creativecommons.org/licenses/by-sa/3.0/", publisher: "Creative Commons", reviewedAt: "2026-09-04" },
    { label: "Creative Commons Attribution-ShareAlike 4.0 licence", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-09-04" },
  ] },
] } as const satisfies StructuredPageBody;

export default body;
