import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Keep your Xi’an hotel when you can reach the booked Mount Hua entrance on time and return to the hotel with margin. Sleep in Huayin before the visit if it protects that entrance; sleep there after if the descent makes the Xi’an return fragile. Move only to remove a real risk, not merely to shorten a map line.",
    },
    {
      id: "direct-answer",
      type: "callout",
      title: "The decision in one minute",
      tone: "decision",
      body: "Save the booked entrance in Chinese, the complete trip back to bed and written custody for every large bag. If both journeys work with margin, keep Xi’an. If morning travel threatens entry, move to Huayin before; if the evening stacks a ropeway, shuttle, local transfer and fixed train, sleep there after. Use two Huayin nights only when each side independently earns one. Before tickets or trains go on sale, hold only cancellable rooms, record the deadlines and rerun this decision when dated products appear.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This page begins after Mount Hua (Huashan) is in the itinerary. It places the adjoining night; it does not decide whether the mountain deserves another Xi’an day, choose a climbing route or ropeway, teach a night climb, assess fitness, sell tickets, rank hotels, or publish current prices, rooms and timetables. Summit lodging is a separate property decision.",
    },
    {
      id: "anchors-heading",
      type: "heading",
      level: 2,
      text: "Fix three anchors before searching for a room",
    },
    {
      id: "anchor-table",
      type: "table",
      caption: "A useful hotel pin protects a named task, not the words ‘near Mount Hua’",
      columns: ["Anchor", "Evidence to save", "What changes the base"],
      rows: [
        ["First entry", "Booked date and time, ticket type, exact Chinese check-in entrance and current opening notice", "A ropeway booking starts through the Mount Hua Visitor Centre; a walking entry starts through the Yuquanyuan–Huashan Gate chain. They are not interchangeable."],
        ["Last complete exit", "Planned descent, current ropeway/trail status, scenic shuttle, local transfer and a dated train or Huayin bed", "Leaving a peak is not the same as reaching Huashan North Station. Add every link and a disruption margin."],
        ["Large-bag custody", "Named custodian, accepted item, dates, hours, receipt and late-collection plan", "No current official source reviewed here confirms dependable large-bag storage at the visitor centre or station."],
      ],
    },
    {
      id: "patterns-heading",
      type: "heading",
      level: 2,
      text: "Choose one of four sleep patterns",
    },
    {
      id: "base-matrix",
      type: "table",
      caption: "The starting answer changes with the protected side of the mountain day",
      columns: ["Sleep pattern", "Best fit", "What it buys", "What it costs"],
      rows: [
        ["Xi’an before and after", "Both dated chains have margin", "One base; confirmed in-room bag custody", "Rail and local transfers frame a demanding day"],
        ["Huayin before, Xi’an after", "An early entry is fixed; return remains robust", "Removes cross-city morning risk", "Adds packing, luggage custody and another reception"],
        ["Xi’an before, Huayin after", "Entry works; descent or recovery makes return fragile", "Removes the fragile late connection", "Needs a verified late room and luggage handoff"],
        ["Huayin before and after", "Early entry independently needs the pre-night, and recovery or next-day eastbound travel independently needs the post-night", "Removes both cross-city edges and possible backtracking", "Two nights still do not guarantee mountain operations"],
      ],
    },
    {
      id: "luggage-matrix",
      type: "table",
      caption: "Name the custodian before choosing a split stay",
      columns: ["Pattern", "Large-bag proof"],
      rows: [
        ["Xi’an both sides", "Continuing room remains yours and the hotel confirms bags may stay inside"],
        ["Huayin before; Xi’an after", "Huayin hotel confirms post-checkout storage and the after-descent collection deadline"],
        ["Xi’an before; Huayin after", "Huayin hotel accepts the bag before entry, or a written transfer does; the detour still meets entry"],
        ["Huayin both sides", "The same room remains yours through the mountain day"],
      ],
    },
    {
      id: "entry-heading",
      type: "heading",
      level: 2,
      text: "A Huayin pre-night must match the booked entrance",
    },
    {
      id: "two-gates",
      type: "callout",
      title: "Huashan North Station, the visitor centre and Huashan Gate are three different nodes",
      tone: "warning",
      body: "Huashan North Railway Station (华山北站) is in Huayin (华阴), not at an entrance. Official guidance sends ropeway-ticket visitors to Mount Hua Visitor Centre (华山游客中心) and walkers to Yuquanyuan (玉泉院)–Huashan Gate (华山门). ‘Near the station’, ‘near the visitor centre’ and ‘near Huashan Gate’ therefore solve different trips. Match the hotel pin and transport to the booking.",
    },
    {
      id: "entry-checklist",
      type: "list",
      ordered: true,
      items: [
        "Copy the current ticket type, window and Chinese entrance. If it is not yet on sale, use a cancellable placeholder only.",
        "Build the morning in order: Xi’an hotel → ticketed departure station (not automatically Xi’an North / 西安北站) → train → Huashan North → verified local transfer → correct entrance, with station and queue margins.",
        "Get the property's Chinese name, coordinates, correct-entrance plan, staffed reception and foreign-guest check-in response in writing.",
        "For night or pre-dawn walking, recheck the route and ticket. A 2021 notice about 24-hour access is not a permanent guarantee.",
        "Keep a fallback for weather, fire control, capacity, trail, ropeway or shuttle changes. A Huayin bed does not guarantee entry.",
      ],
    },
    {
      id: "descent-heading",
      type: "heading",
      level: 2,
      text: "Build the last descent all the way to the bed",
    },
    {
      id: "exit-chain-table",
      type: "table",
      caption: "Do not stop the calculation when the ropeway or trail ends",
      columns: ["Link", "Verify for the date", "Accommodation consequence"],
      rows: [
        ["Route to lower station or trail exit", "Pace, queues, weather and operation", "A long, uncertain descent favours a Huayin post-night"],
        ["Lower station to public exit", "Applicable scenic shuttle and final workable service", "Ropeway descent is not yet the railway transfer"],
        ["Exit to Huashan North", "Legal vehicle, boarding point, luggage and delay response", "A confirmed Huayin room must remain reachable if rail fails"],
        ["Huashan North to the final bed", "Booked train and ticketed Xi’an arrival station, then hotel route/reception; or exact Huayin pin and staffed late arrival", "A search result is not a fallback until verified and bookable"],
      ],
    },
    {
      id: "move-heading",
      type: "heading",
      level: 2,
      text: "Make the hotel move prove its value",
    },
    {
      id: "one-move-test",
      type: "callout",
      title: "The one-move test",
      tone: "neutral",
      body: "Write one sentence: ‘Moving to Huayin protects ___ by removing ___, while adding ___.’ The move passes if it protects a booked first entry, removes an unsafe late chain, creates needed recovery time or fits an eastbound onward route. It fails if it only changes the map pin while adding checkout, luggage custody, another reception and the same unverified local vehicle.",
    },
    {
      id: "needs-heading",
      type: "heading",
      level: 2,
      text: "Let the most constrained traveller set the base",
    },
    {
      id: "needs-table",
      type: "table",
      caption: "‘Closer’ is useful only when the continuous route works",
      columns: ["Traveller or constraint", "Starting direction", "Required proof"],
      rows: [
        ["Family with children", "Use Huayin only if it removes an extreme start or fragile return", "Child seat or booster and whether the exact vehicle provides it; meals, reception, room and luggage"],
        ["Older or slower traveller", "Protect recovery; a post-night may matter more", "Real pace, queues, seating, transfers and hotel steps/lift"],
        ["Wheelchair or mobility device", "No area-wide default", "Verify both directions: hotel, vehicle loading, station/entry, chosen mountain facilities, exit and final room; 12306 help covers rail only"],
        ["Large bags or eastbound travel", "Use one proven custodian; avoid returning west only if onward rail works", "Capacity, storage acceptance, receipt and door-to-platform route"],
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Two complete examples",
    },
    {
      id: "scenario-day-return",
      type: "list",
      ordered: false,
      items: [
        "A couple already has a continuing Xi’an room, a dated train and a ropeway entry window that the full station-to-visitor-centre chain reaches with margin.",
        "They plan a conservative descent and have a later rail fallback. The hotel confirms the bags stay in the room.",
        "Decision: keep Xi’an before and after. A Huayin night would add a move without protecting a fixed task.",
      ],
    },
    {
      id: "scenario-post-night",
      type: "list",
      ordered: false,
      items: [
        "A multigenerational group can reach its booked entry from Xi’an, but its slower pace makes the final ropeway–shuttle–station–train chain unreliable.",
        "Before entry, a verified Huayin hotel accepts their bags; that detour still meets the window. It holds late arrival, and they continue east next morning.",
        "Decision: travel from Xi’an that morning and sleep in Huayin after descent, preserving recovery and avoiding a return west.",
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Recover without improvising a new mountain route",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Keep the recovery on the accommodation side of the decision",
      columns: ["Failure", "Immediate action", "Sleep recovery"],
      rows: [
        ["Weather, fire or safety control", "Read the official notice; do not assume a stopped ropeway makes walking open", "Use changeable room terms; proximity cannot override closure"],
        ["Missed entry window", "Contact the official ticket channel; do not expect gate discretion", "Move the visit only if access and room terms permit"],
        ["Descent misses the safe Xi’an chain", "Stop chasing an unverified final vehicle", "Use a prebooked room only after confirming late-arrival hold and cancellation deadline; otherwise call a prescreened same-night option before paying or contact the booking platform's accommodation support"],
        ["Booked Huayin room is refused/unavailable", "Show the booking and passport; request the reason, then contact booking-platform support", "Book a verified alternative; keep original evidence privately and redact copies sent outside the case channel"],
        ["Luggage custody fails", "Keep documents, medicine and valuables with you", "Return to the confirmed custodian or adjust the visit; do not default to carrying a large bag uphill"],
      ],
    },
    {
      id: "dynamic-callout",
      type: "callout",
      title: "Recheck on the date, not after checkout",
      tone: "warning",
      body: "Core official content was read on 1 September 2026; link availability was rechecked on 4 September, when several scenic-area pages were temporarily unreachable. A current official-account post still reiterated real-name timed booking and weather closure. Recheck the official notice/booking channel, entry, ropeway/trail, shuttle, 12306 train, local transfer and hotel before cancellation deadlines and on travel day. Old notices and sample searches are not guarantees.",
    },
    {
      id: "final-checklist",
      type: "list",
      ordered: true,
      items: [
        "Name the exact first entry in Chinese and match it to the booked ticket.",
        "Build the arrival chain from the bed—not merely from Xi’an North to Huashan North.",
        "Build the exit chain through descent, scenic shuttle, local transfer and the final bed.",
        "Place every large bag with a named custodian; never assume station or visitor-centre storage.",
        "Make one move state the fixed task it protects and the new handoffs it creates.",
        "Verify the property pin, staffed arrival, foreign-guest check-in, room and decisive access features in writing.",
        "Label the fallback as either a prebooked room with late-arrival/cancellation terms or a prescreened option that still needs a call and payment.",
        "Save evidence without putting passports, booking references, payment data or medical details into public messages.",
      ],
    },
    {
      id: "consultation-boundary",
      type: "callout",
      title: "Before using the general consultation form",
      tone: "neutral",
      body: "The next general form should receive only minimum non-sensitive context: dates, public city/base names, traveller and room counts, confirmed entry and onward direction, and a broad budget band. You may request a later family or accessibility discussion, but do not submit children's exact ages, mobility, medical or accessibility details, passport/ID, booking/payment records, or identifiable supplier-sharing information. Discuss those only in an appropriate human follow-up; nothing goes to a supplier without separate consent. This is not live inventory, booking or transport and does not guarantee price, availability, foreign-guest acceptance, room type, accessibility, entry, trail/ropeway, train/transfer, luggage, connection success or safety.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue with the owner of the next decision",
      items: [
        { label: "Xi’an travel planning", href: "/destinations/xian/", description: "Decide whether Mount Hua belongs in the Xi’an itinerary and how much city time to protect." },
        { label: "Where to stay within Xi’an", href: "/guides/xian-where-to-stay-city-wall-or-dayanta/", description: "After choosing a Xi’an base, compare the City Wall and Dayanta areas." },
        { label: "Recover from a hotel refusal", href: "/guides/foreigners-china-hotel/", description: "Separate national registration rules from a platform label or one property's front-desk execution." },
        { label: "Verify an accessible hotel room", href: "/guides/china-accessible-hotel-room-verification/", description: "Check the street-to-room chain and a named room instead of trusting an accessibility label." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official and primary sources reviewed",
      items: [
        { label: "Mount Hua reservation and opening FAQ — content captured 1 September; link availability rechecked 4 September", url: "https://www.chinahuashan.com/front/travelStrategy1.htm", publisher: "Mount Hua Scenic Area", reviewedAt: "2026-09-04" },
        { label: "Official Mount Hua route and arrival strategy — content captured 1 September; link availability rechecked 4 September", url: "https://www.chinahuashan.com/front/touristviewArticle.htm?id=262147", publisher: "Mount Hua Scenic Area", reviewedAt: "2026-09-04" },
        { label: "Historical Huashan Gate walking-access notice", url: "https://www.chinahuashan.com/front/notification.htm?id=983046", publisher: "Mount Hua Scenic Area", reviewedAt: "2026-09-04" },
        { label: "Mount Hua Visitor Centre — content captured 1 September; link availability rechecked 4 September", url: "https://www.chinahuashan.com/front/viewtouristattractions.htm?id=33", publisher: "Mount Hua Scenic Area", reviewedAt: "2026-09-04" },
        { label: "Official Mount Hua transport page — content captured 1 September; link availability rechecked 4 September", url: "https://www.chinahuashan.com/front/wzhs.htm", publisher: "Mount Hua Scenic Area", reviewedAt: "2026-09-04" },
        { label: "Current Mount Hua official-account walking activity and weather warning", url: "https://weibo.com/ttarticle/p/show?id=2309405338374721896472", publisher: "Mount Hua Scenic Area verified official account", reviewedAt: "2026-09-04" },
        { label: "Shaanxi Mount Hua Scenic and Historic Interest Area Regulation", url: "https://www.shaanxi.gov.cn/zfxxgk/zcwjk/dfxfg/202402/W020240226372070395729.pdf", publisher: "Shaanxi Provincial People's Government", reviewedAt: "2026-09-04" },
        { label: "Huashan North Railway Station address", url: "https://www.12306.cn/%2Fmormhweb/kyyyz/xian/201001/t20100124_1176.html", publisher: "China Railway 12306", reviewedAt: "2026-09-04" },
        { label: "Date-specific train query", url: "https://www.12306.cn/index/", publisher: "China Railway 12306", reviewedAt: "2026-09-04" },
        { label: "Railway carry-on luggage rules", url: "https://kyfw.12306.cn/otn/gonggao/luggage.html", publisher: "China Railway 12306", reviewedAt: "2026-09-04" },
        { label: "Priority traveller railway assistance", url: "https://kyfw.12306.cn/otn/view/icentre_qxyyInfo.html", publisher: "China Railway 12306", reviewedAt: "2026-09-04" },
        { label: "Hero: Mount Hua from Huashan North by A Chinese ID, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Mount_Hua,_shot_from_the_train_G1888_in_Huashanbei_Station.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
