import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "断桥、雷峰塔和金山寺都是真实地点，但没有一处能证明《白蛇传》曾作为历史事件发生。断桥是长期维护的西湖景观；今天雷峰塔内部保护着五代吴越时期佛塔的遗存，游客进入的建筑却是现代重建；金山寺仍是佛教活动空间，“水漫金山”则属于传说在文学和戏曲中的发展。对大多数读者，一段有重点的杭州半日已经足够。只有当你本来就在华东路线中，并且确实想比较两个城市怎样把同一则变化中的故事变成景观，镇江才值得增加。",
    },
    {
      id: "answer",
      type: "callout",
      title: "先给结论",
      body: "第一次接触这条故事线，选杭州：一座真实桥梁、一处考古遗址和一座现代重建塔，可以在同城形成最清楚的证据链。只有当镇江本来顺路、能单独留出半天，而且你想看“活态寺院如何承接另一层传说”，才增加金山寺。不要只为了收集第二个“白蛇传地点”而换城。",
      tone: "decision",
    },
    {
      id: "two-cities-heading",
      type: "heading",
      level: 2,
      text: "为什么同一则传说同时联系杭州和镇江？",
    },
    {
      id: "two-cities",
      type: "paragraph",
      text: "因为《白蛇传》并不是按一张固定路线图一次写成。国家级非遗记录分别登记了杭州与镇江的白蛇传说项目，并把两地都列为重要流传区域。杭州记录强调西湖、断桥与雷峰塔；金山与具体故事场景的关联，应由后来的景观叙事研究来说明，不能只凭非遗登记推出。合起来看，证据支持的是多地传播，不是“唯一发源地”竞赛。说书人、戏曲作者和影视创作者可以为各自版本选择、移动和重组地点。这种地理属于文学记忆：它能说明社群把故事安放在哪里，却不能证明白素贞、许仙或法海作为历史人物曾在这里生活。",
    },
    {
      id: "layers",
      type: "table",
      caption: "全文使用的四种证据层",
      columns: ["层次", "包括什么", "最多能证明什么"],
      rows: [
        ["历史与物质证据", "桥梁维修、塔基、佛教器物、有年代的营建、毁损与保护", "地点或物件真实存在并发生变化；不能证明传说事件"],
        ["民间传说", "白素贞、许仙、法海及其与地方的联系", "故事曾经流传并对社群有意义；不能当作人物传记"],
        ["文学与表演", "可指认的文本、戏曲版本及其增删情节", "某个版本具体怎样讲；不能代表永恒不变的总版本"],
        ["现代旅游呈现", "新塔、浮雕、展陈、节庆、景点命名和参观路线", "今天怎样解释故事；不能充当古代建筑或事件证据"],
      ],
    },
    {
      id: "versions-heading",
      type: "heading",
      level: 2,
      text: "我们熟悉的完整情节，是后来逐步组装出来的",
    },
    {
      id: "versions",
      type: "paragraph",
      text: "早期蛇女故事并没有今天观众熟悉的整套爱情叙事。国家非遗项目说明把冯梦龙十七世纪创作的白蛇故事视为较早的完整文本节点。此后戏曲继续改变人物动机、同情方向与地点组合。清代舞台进一步放大了后来被视为“核心”的桥段，包括水漫金山，以及冲突之后的断桥相会。现代电影、电视剧和景区又做了一轮取舍。稳妥的问题应是“这个场景属于哪个版本”，而不是“原事件究竟发生在哪里”。",
    },
    {
      id: "version-line",
      type: "table",
      caption: "一条简化的版本发展线，而不是完整故事史",
      columns: ["阶段", "可以得到的结论", "不要误以为"],
      rows: [
        ["早期蛇女故事", "熟悉的西湖爱情叙事之前，已经存在更早母题", "今天所有人物和地点当时都已固定"],
        ["冯梦龙文本", "一个重要书面版本形成更清楚的杭州—苏州—镇江—雷峰塔地理", "所有后来的名场面已经定型"],
        ["后来的戏曲舞台", "表演传统继续扩展冲突、水漫与断桥桥段", "某一出戏代表所有地区和时代"],
        ["影视与景区", "现代媒介让某些面孔、服装和情节格外熟悉", "最熟悉的影视版本就是最古老或唯一版本"],
      ],
    },
    {
      id: "broken-bridge-heading",
      type: "heading",
      level: 2,
      text: "在断桥：地点是真的，相遇属于故事记忆",
    },
    {
      id: "broken-bridge",
      type: "paragraph",
      text: "先把桥当作景观证据来读。国际古迹遗址理事会（ICOMOS）的评估文件把断桥定位在白堤东端，也记录了它在西湖这处长期营造的文化景观中反复维护和修缮的历史。现场先看桥与白堤的衔接、今天可见的石构和它与湖面的关系；然后望向南岸。雷峰塔并不在一条紧凑的“故事街”下一站，真实距离会打破影视形成的错觉。断桥可以成为传说锚点，却不是一次历史相遇留下的原状道具。",
    },
    {
      id: "bridge-boundary",
      type: "callout",
      title: "断桥到底证明什么",
      body: "它证明西湖文化景观中确有一座具名、经过维护的桥。相遇与再次相会属于民间传说和后来的文学层。列入世界遗产不等于认证传说人物，也不表示眼前每一块石材都来自古代。",
      tone: "neutral",
    },
    {
      id: "leifeng-heading",
      type: "heading",
      level: 2,
      text: "在雷峰塔：先分开旧塔遗址、倒塌的塔和现代建筑",
    },
    {
      id: "leifeng-modern",
      type: "paragraph",
      text: "雷峰塔最有力的古代证据首先是佛教考古，而不是人物传记。五代吴越时期的塔为宗教目的而建，2000—2001年的考古工作记录了塔基、地宫和佛教遗物。残损旧塔于1924年9月25日倒塌。今天游客进入的建筑，是二十一世纪初建在受保护遗址之上的新塔。先把它的轮廓读作现代仿古建筑，把内部动线读作遗址保护与解释设施，而不要把它说成吴越时期砖木塔原物保存至今。",
    },
    {
      id: "leifeng-modern-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-modern-1200.webp",
      alt: "现代雷峰塔从西湖南岸树林上方升起。",
      width: 1200,
      height: 800,
      caption: "今天的轮廓属于保护和展示遗址的现代建筑。仿古外观不能把吴越时期的年代转移给游客进入的新塔。",
    },
    {
      id: "leifeng-ruins",
      type: "paragraph",
      text: "如果相关室内楼层当天开放，重点寻找旧砖塔基，以及现代结构怎样围绕它形成保护边界。这种新旧并置，比在遗址里寻找“白素贞被镇压的位置”更有意义。考古能够证明营建、佛教使用、倒塌和遗物埋藏，不能识别白素贞。地宫是重要的考古背景，但本文不承诺游客可以看见或进入；博物馆藏品也可能轮换，因此要同时复核楼层开放和展品状态，不能围绕某件器物安排不可替换的参观。",
    },
    {
      id: "leifeng-ruins-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-ruins-1200.webp",
      alt: "现代参观建筑内受到保护的雷峰塔旧砖遗存。",
      width: 1200,
      height: 800,
      caption: "旧砖塔基是早期佛塔的物质证据；栏杆、玻璃和周围建筑属于现代保护与旅游呈现。",
    },
    {
      id: "leifeng-old",
      type: "paragraph",
      text: "一张完成版权核验的倒塌前照片可以补上中间层。把照片中残破厚重的砖塔与今天带屋檐的轮廓并排看，两者都不应冒充另一座。历史照片记录的是旧塔晚期残损状态，并非初建时原貌。如果当天展陈包含浮雕、壁画或白蛇故事标签，它们替游客选择了一个更容易记住的现代版本；即使位于真实塔基上方，也仍然属于解释层。",
    },
    {
      id: "leifeng-old-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-1918-1200.webp",
      alt: "1918年拍摄、在1924年倒塌前已残损的旧雷峰塔。",
      width: 1200,
      height: 850,
      caption: "关野贞于1918年拍下旧塔残损晚期状态；这不是吴越时期的初建原貌。图片版权与处理记录见 `image-plan.md`。",
    },
    {
      id: "jinshan-heading",
      type: "heading",
      level: 2,
      text: "金山增加的，是活态寺院和另一种“故事附着于地点”的方式",
    },
    {
      id: "jinshan",
      type: "paragraph",
      text: "金山寺正式名为江天禅寺，首先应作为仍在活动的佛教场所来理解。宗教活动、礼佛者和受限空间都优先于它的白蛇传旅游角色。沿山上行也带来真实的体力负担，这是平面故事地图看不到的。江苏消防救援2026年的报道转述当地消防教育馆沙盘，称1948年火灾烧损三百余间古建筑；由于研究包尚未找到更强的原始档案，正文必须保留这层归因，不能把数字写成独立核实的一手史实。它至少提醒我们：不能把今天整座寺院笼统说成未经变化的古代建筑。",
    },
    {
      id: "jinshan-entrance-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/jinshan-entrance-1200.webp",
      alt: "镇江金山寺入口题有正式寺名“江天禅寺”。",
      width: 1200,
      height: 800,
      caption: "入口把双重名称直接呈现出来：通常称金山寺，佛教机构正式名为江天禅寺。名称是真实证据，却不能把寺院变成故事布景。",
    },
    {
      id: "jinshan-geography",
      type: "paragraph",
      text: "寺院史研究与历史地理研究支持一种谨慎说法：十九世纪的河道变化与泥沙沉积逐步改变了金山的岛岸关系，今天山体已经与陆地相连。现有来源不适合把某一个精确“连陆年份”冻结成常青事实。更重要的是，真实地理变化不能证明文学里的水漫情节。今天的水岸与山体只适合帮助理解这个场景为什么容易被想象，不能把戏曲桥段倒推成水文史。",
    },
    {
      id: "cishou-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/cishou-pagoda-1200.webp",
      alt: "镇江金山寺建筑群内的慈寿塔。",
      width: 1200,
      height: 800,
      caption: "慈寿塔是镇江金山的地标，不是杭州雷峰塔被搬进另一幕故事。若要给出现存塔的具体年代，发布前仍须用寺院或文保资料复核。",
    },
    {
      id: "cave-warning",
      type: "callout",
      title: "不要承诺一定能进法海洞",
      body: "学术研究记录了裴公洞与法海洞在不同时期被不同命名和呈现的过程。这能证明景观叙事怎样形成，不能证明法海生平。2026年的开放、现行标识和摄影规则尚未得到直接确认，所以本文不承诺进入。若现场关闭或信息不清，改看公共寺院建筑、慈寿塔和合法水岸视角即可。",
      tone: "warning",
    },
    {
      id: "evidence-heading",
      type: "heading",
      level: 2,
      text: "四个地点分别允许你说到哪一步？",
    },
    {
      id: "evidence-table",
      type: "table",
      caption: "地点与证据边界",
      columns: ["地点", "最强证据", "故事层", "现代呈现"],
      rows: [
        ["断桥", "西湖文化景观中经过维护的桥梁", "相遇和再次相会", "解说牌、导览叙述和拍照构图"],
        ["旧雷峰塔遗址", "塔基、旧砖、地宫考古记录与佛教遗物", "镇压白素贞的情节", "遗址保护与考古解释"],
        ["现代雷峰塔", "建在遗址上方的现代建筑", "被挑选展示的白蛇故事场景", "建筑和游客动线；浮雕、壁画须以当天展出为准"],
        ["金山／江天禅寺", "经历重建维修、地理关系变化的活态佛教建筑群", "水漫金山和后来的法海关联", "洞名、景区活动与当代解释"],
      ],
    },
    {
      id: "choice-heading",
      type: "heading",
      level: 2,
      text: "只去杭州够不够？什么时候值得增加镇江？",
    },
    {
      id: "choice",
      type: "comparison",
      title: "按你想回答的问题来选",
      columns: [
        {
          heading: "只去杭州",
          items: [
            "最适合第一次理解白蛇传最清楚的断桥—雷峰塔地理",
            "同城看见真实景观、考古遗址与现代重建三个层次",
            "当镇江构成绕路或会把转场日压得过紧时，这是默认答案",
          ],
        },
        {
          heading: "增加镇江",
          items: [
            "江苏本来就在路线里，而且金山能够得到独立半天",
            "想增加活态寺院、山地动线和后世地名附会的观察",
            "适合比较文学怎样变成景观，不适合寻找唯一发源地",
          ],
        },
        {
          heading: "不把它当故事专题",
          items: [
            "主要兴趣只是普通西湖观光，而非版本与遗址辨析",
            "金山上行不适合同行者，且比较价值不足以抵消体力与时间",
            "不要因为影视里出现一个名称就额外增加城市",
          ],
        },
      ],
    },
    {
      id: "choice-rule",
      type: "paragraph",
      text: "判断镇江是否值得时，要算有效时间而不只看列车运行时间：退房、去车站、安检、候车、落地接驳、行李和误接下一段的后果都属于转场成本。用真实日期和车站在12306核验，本文不冻结车次与余票。扣除这些成本后，如果比较本身留不出独立半日，只去杭州就够了。",
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "每座城市用半天，让证据层依次显出来",
    },
    {
      id: "hangzhou-sequence",
      type: "list",
      ordered: true,
      items: [
        "从断桥开始。先找到它与白堤的连接，把桥标记为“经过维护的景观”，再讲相遇情节。",
        "只用一小段公共湖岸完成方位判断，确认断桥区与雷峰塔的真实距离。本文不扩写完整西湖步行或游船攻略。",
        "先在外部观察现代雷峰塔轮廓，明确眼前是新建筑，再决定是否进入。",
        "若当天相关楼层开放，再寻找旧砖塔基和保护边界；复核前不要承诺能见遗址、进入地宫或看到轮换藏品。",
        "若当天确有浮雕或故事标签展出，再以其中一处收尾：问它选择了哪个版本，又不能提供什么物质证据。",
      ],
    },
    {
      id: "zhenjiang-sequence",
      type: "list",
      ordered: true,
      items: [
        "在入口同时确认“金山寺”和“江天禅寺”两个名称，先承认这里是宗教场所，不是传说布景。",
        "上行前评估楼梯。同行者行动不便、炎热、下雨或人流管控时，保留下部公共空间方案。",
        "看今天的殿宇和维修痕迹，不要把整个建筑群都套上最早创建年代；礼佛与居民通行优先。",
        "把慈寿塔与杭州雷峰塔分开，再从公共视角观察山、水与今天的连陆状态。",
        "只有当现场标识与工作人员确认开放时，才接近法海洞／裴公洞区域；否则只理解地名演变。",
      ],
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "不要把“看起来完整的故事”误当成完整证据",
    },
    {
      id: "mistakes",
      type: "table",
      caption: "七个需要当场纠正的误解",
      columns: ["误解", "纠正"],
      rows: [
        ["真实断桥证明相遇", "真实地点可以承载传说，却不能记录事件"],
        ["世界遗产表示所有可见结构都是原物", "西湖是长期营造、内部构件不断变化的文化景观"],
        ["今天的雷峰塔就是吴越旧塔", "游客建筑是现代重建，受保护遗址才是旧物质证据"],
        ["历史照片展示初建原貌", "它只展示1924年倒塌前的晚期残损状态"],
        ["金山现有殿宇都来自最早创建年代", "火灾、重建、维修和持续使用需要逐栋证据"],
        ["法海洞证明历史人物住过", "地名变化说明后世附会与旅游呈现"],
        ["影视情节就是古老总版本", "可指认的文本和戏曲版本逐步发展了今天的地理"],
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "塔、洞窟或跨城连接失效时，比较仍然可以成立",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "不牺牲证据的替代方案",
      columns: ["失效情况", "保留", "删除"],
      rows: [
        ["雷峰塔内部关闭", "断桥、现代塔外观和有来源的新旧图像比较", "“可以看见遗址或地宫”的说法"],
        ["博物馆藏品未展", "有来源的考古出土事实", "在展厅一定能找到它的承诺"],
        ["法海洞／裴公洞开放或标识不清", "有文献支持的命名史和公共寺院路线", "进入、标识文字和拍摄承诺"],
        ["金山上部动线不适合", "下部公共建筑和确认开放的视角", "勉强爬升或“不到高处就不完整”"],
        ["铁路或后续衔接脆弱", "完整杭州证据链", "把镇江压成只收集标签的匆忙绕路"],
      ],
    },
    {
      id: "respect",
      type: "callout",
      title: "寺院不是影视片场",
      body: "遵守殿堂、洞窟、三脚架与室内拍摄的当前标识；拍出家人、礼佛者、仪式或可识别游客前先征得许可，不要堵住门槛复刻影视场景。本文不使用电影、电视剧或戏曲截图：熟悉不等于获得转载权，演出画面也不能代替物质历史。",
      tone: "warning",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "这条故事线适合谁？谁可以跳过？",
    },
    {
      id: "who",
      type: "paragraph",
      text: "如果你喜欢民间传说、改编、考古，或想理解城市怎样把文学变成可见景观，这条线值得安排。杭州单城适合大多数第一次来访者和需要保护节奏的人。双城版适合本来就在浙江、江苏之间移动，而且把两种证据的比较当作旅行目的的人。如果楼梯、转场风险或时间有限，不必增加镇江。真正有用的收获不是裁定“哪里才是真正发源地”，而是能说清哪些属于物质、哪些属于叙述、哪些是为了解释叙述而建。",
    },
    {
      id: "help",
      type: "callout",
      title: "需要人工核验当前状态？",
      body: "开放、预约、洞窟、列车与摄影规则截至2026年8月14日均按动态事实处理。你可以留下日期、人数和大致预算，请当地人工核验镇江是否能在不压缩转场日的前提下加入。在直接确认之前，不会承诺洞窟、车次或轮换展品。",
      tone: "decision",
    },
    {
      id: "links",
      type: "internal-links",
      title: "交通与节奏继续由原有页面负责",
      items: [
        {"label":"上海—杭州交通怎么选","href":"/zh/guides/shanghai-hangzhou-transport-route/","description":"处理跨城方式，不把这篇文化比较写成第二篇杭州交通攻略。"},
        {"label":"第一次乘坐中国高铁","href":"/zh/guides/china-high-speed-train-first-time-guide/","description":"确定镇江值得换城后，再核对车站、证件与乘车流程。"},
        {"label":"你的中国行程是不是太赶","href":"/zh/guides/is-your-china-itinerary-too-rushed/","description":"检查增加一个故事地点后，是否还剩真正可用的半天。"}
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "遗产、考古、寺院与研究来源",
      items: [
        {"label":"白蛇传传说——杭州项目","url":"https://www.ihchina.cn/project_details/12185/","publisher":"中国非物质文化遗产数字博物馆","reviewedAt":"2026-08-13"},
        {"label":"白蛇传传说——镇江项目","url":"https://www.ihchina.cn/project_details/12184.html","publisher":"中国非物质文化遗产数字博物馆","reviewedAt":"2026-08-13"},
        {"label":"杭州西湖文化景观","url":"https://whc.unesco.org/en/list/1334/","publisher":"UNESCO世界遗产中心","reviewedAt":"2026-08-13"},
        {"label":"杭州西湖文化景观ICOMOS评估文件","url":"https://whc.unesco.org/document/152404","publisher":"ICOMOS／UNESCO","reviewedAt":"2026-08-13"},
        {"label":"雷峰塔历史与遗址保护","url":"https://wgly.hangzhou.gov.cn/art/2022/12/1/art_1229696389_58943150.html","publisher":"杭州市文化广电旅游局","reviewedAt":"2026-08-13"},
        {"label":"雷峰塔遗址考古发掘报告目录记录","url":"https://buddhism.lib.ntu.edu.tw/DLMBS/en/search/search_detail.jsp?seq=554802","publisher":"台湾大学佛学数字图书馆／浙江省文物考古研究所报告","reviewedAt":"2026-08-13"},
        {"label":"《略论白蛇传故事的主题流变》","url":"https://dflt.qdu.edu.cn/__local/A/39/DD/795E68F17B2300A5D3639ABEFD9_97A4FDA1_173BA8.pdf","publisher":"《东方论坛》，崔云伟、孙绪波","reviewedAt":"2026-08-13"},
        {"label":"法海洞与雷峰塔的景观叙事研究","url":"https://xbzs.ecnu.edu.cn/CN/html/201402014.htm","publisher":"《华东师范大学学报》，余红艳","reviewedAt":"2026-08-13"},
        {"label":"镇江金山江天禅寺","url":"https://www.jsfj.net/syzs_zjjsjtcs","publisher":"江苏省佛教协会","reviewedAt":"2026-08-13"},
        {"label":"转述1948年金山火灾的镇江消防教育馆报道","url":"https://js.119.gov.cn/202606/jsxfww-menu-gzdt_c_30a20aac24664a56b642.html","publisher":"江苏消防救援","reviewedAt":"2026-08-13"},
        {"label":"金山寺史研究","url":"https://ccj.pku.edu.cn/article/info?id=286660025","publisher":"北京大学期刊平台（作者名见原文）","reviewedAt":"2026-08-13"},
        {"label":"镇江河段历史河道演变研究","url":"https://www.geog.com.cn/EN/abstract/article/0375-5444/47762","publisher":"《地理学报》（作者名见原文）","reviewedAt":"2026-08-13"},
        {"label":"铁路车次与售票核验","url":"https://www.12306.cn/en/index.html","publisher":"中国铁路12306","reviewedAt":"2026-08-13"},
        {"label":"首图：Suicasmo拍摄断桥，CC0 1.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Broken_Bridge_(Hangzhou)_20250505.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：Suicasmo拍摄现代雷峰塔，CC0 1.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Leifeng_Pagoda_20250505.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：HoweyYuan拍摄雷峰塔考古遗址，CC BY-SA 4.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Site_of_Leifeng_Pagoda_20240729.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"历史照片：关野贞1918年拍摄雷峰塔，公共领域；已按比例缩放、置于中性画布并转为WebP","url":"https://commons.wikimedia.org/wiki/File:Leifeng_Pagoda_in_Hangzhou,_1918.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"1918年雷峰塔照片的1939年来源卷册记录","url":"https://ndlsearch.ndl.go.jp/books/R100000039-I1902745","publisher":"日本国立国会图书馆","reviewedAt":"2026-08-14"},
        {"label":"正文图：Yumeto拍摄金山江天禅寺入口，CC BY-SA 4.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:20240806_Jinshan_Si.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"正文图：Yumeto拍摄慈寿塔，CC BY-SA 4.0；已裁切、缩放并转为WebP","url":"https://commons.wikimedia.org/wiki/File:20240806_Cishou_Ta.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"断桥与现代雷峰塔衍生图的CC0 1.0贡献声明","url":"https://creativecommons.org/publicdomain/zero/1.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"以上裁切衍生图适用的CC BY-SA 4.0许可","url":"https://creativecommons.org/licenses/by-sa/4.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"}
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
