import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Broken Bridge, Leifeng Pagoda and Jinshan Temple are real places, but none proves that the White Snake story happened as history. Broken Bridge is a maintained element of West Lake. Beneath the present Leifeng tower are remains of a Buddhist pagoda from the late Wuyue period; the visitor building is modern. Jinshan is a living Buddhist temple whose flood association belongs to the legend’s literary and theatrical growth. For most readers, Hangzhou supplies enough evidence in one focused half-day. Add Zhenjiang only if comparing how two cities made a changing story visible is worth an extra stop.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The short decision",
      body: "Choose Hangzhou for the clearest bridge–ruin–reconstruction sequence. Add Zhenjiang when Jinshan already fits your eastern China route, you can give it a separate half-day, and seeing a living temple and a different layer of the legend is worth the transfer. Do not add Zhenjiang merely to collect a second ‘White Snake location.’",
      tone: "decision",
    },
    {
      id: "two-cities-heading",
      type: "heading",
      level: 2,
      text: "Why does one legend belong to both Hangzhou and Zhenjiang?",
    },
    {
      id: "two-cities",
      type: "paragraph",
      text: "The legend did not emerge as a fixed itinerary. National ICH records separately register Hangzhou and Zhenjiang projects and name both important transmission areas. Hangzhou’s record emphasizes West Lake and Leifeng; later landscape-narrative research, not registration alone, documents Jinshan’s specific attachment. Together the evidence supports multi-place transmission, not an origin contest. Storytellers, playwrights and screenwriters reorganized places for their versions. This literary geography shows where communities located the story, not where evidence proves Bai Suzhen, Xu Xian or Fahai lived.",
    },
    {
      id: "layers",
      type: "table",
      caption: "Four evidence layers used throughout this guide",
      columns: ["Layer", "What belongs here", "What it can establish"],
      rows: [
        ["History and material evidence", "Bridge repair, pagoda foundations, Buddhist objects, dated construction, destruction and conservation", "A place or object existed and changed; not that a legendary episode occurred"],
        ["Folklore", "Bai Suzhen, Xu Xian, Fahai and local place associations", "A story circulated and mattered in a community; not verified biography"],
        ["Literature and performance", "Named written versions, drama and opera that add, remove or enlarge episodes", "What a particular version says; not one timeless master plot"],
        ["Tourism presentation", "A modern tower, relief, exhibition, festival or renamed feature", "How the story is presented now; not ancient fabric or event proof"],
      ],
    },
    {
      id: "versions-heading",
      type: "heading",
      level: 2,
      text: "The familiar plot was assembled over time",
    },
    {
      id: "versions",
      type: "paragraph",
      text: "Early snake-woman material does not yet supply the romance most viewers recognize. The national heritage overview identifies Feng Menglong’s seventeenth-century story, commonly translated as ‘Madam White Is Imprisoned Forever beneath Leifeng Pagoda,’ as an early relatively complete literary milestone. Later drama continued changing motivation, sympathy and place. Qing theatre enlarged scenes now treated as essential, including flooding Jinshan and the Broken Bridge encounter after the conflict. Modern screen works and attractions made another selection. Ask ‘Which version contains this scene?’ rather than ‘Where did the original event happen?’",
    },
    {
      id: "version-line",
      type: "table",
      caption: "A compact version line—not a complete history of the legend",
      columns: ["Stage", "Useful conclusion", "Do not assume"],
      rows: [
        ["Early snake-woman stories", "Older motifs existed before the familiar West Lake romance", "Every modern character and location was already fixed"],
        ["Feng Menglong’s story", "A major written version organizes a stronger Hangzhou–Suzhou–Zhenjiang–pagoda geography", "All later-famous scenes already had their final form"],
        ["Later theatre and opera", "Performance traditions expanded reconciliation, conflict, flooding and bridge scenes", "One stage script represents every region or period"],
        ["Film, television and attractions", "Modern media made selected faces, costumes and episodes widely recognizable", "The most familiar screen version is the oldest or only version"],
      ],
    },
    {
      id: "broken-bridge-heading",
      type: "heading",
      level: 2,
      text: "At Broken Bridge, the place is real but the meeting is story memory",
    },
    {
      id: "broken-bridge",
      type: "paragraph",
      text: "Start with the bridge as landscape evidence. ICOMOS places Broken Bridge at the eastern end of Bai Causeway and records a history of maintenance and repair within the deliberately shaped West Lake cultural landscape. Look at the bridge’s junction with the causeway, its current stone fabric and its relationship to the lake. Then turn toward the south shore: Leifeng is not the next object on a compact story street. The real separation helps correct a screen-shaped illusion in which every episode sits within a few steps. The bridge can anchor the legend without being an untouched prop from a historical meeting.",
    },
    {
      id: "bridge-boundary",
      type: "callout",
      title: "What Broken Bridge proves",
      body: "It proves that a named, repaired bridge belongs to West Lake’s long-developed landscape. The association with meeting or reunion belongs to folklore and later literature. UNESCO status does not authenticate the characters, and it does not mean every visible stone is ancient.",
      tone: "neutral",
    },
    {
      id: "leifeng-heading",
      type: "heading",
      level: 2,
      text: "At Leifeng, separate the old foundation, the lost tower and the new building",
    },
    {
      id: "leifeng-modern",
      type: "paragraph",
      text: "The strongest old evidence at Leifeng is Buddhist, not biographical. The late-Wuyue pagoda was built for religious purposes, and excavation in 2000–2001 documented its foundation, underground chamber and Buddhist deposits. The damaged historic tower collapsed on 25 September 1924. The present visitor building was then constructed over the protected site in the early twenty-first century. Read its silhouette as modern historicizing architecture and its circulation system as protection and interpretation—not as the Wuyue tower surviving intact.",
    },
    {
      id: "leifeng-modern-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-modern-1200.webp",
      alt: "The present Leifeng Pagoda rises above trees on the south side of West Lake.",
      width: 1200,
      height: 800,
      caption: "The present silhouette belongs to a modern protective and interpretive building. Its old-looking outline must not transfer a Wuyue date to the structure visitors enter.",
    },
    {
      id: "leifeng-ruins",
      type: "paragraph",
      text: "If that interior floor is accessible, look for the old brick base and its modern protection boundary. This contrast is more useful than searching for a legendary prison. Archaeology establishes construction, Buddhist use, collapse and deposits; it cannot identify Bai Suzhen. The underground chamber matters archaeologically, but this guide promises neither viewing nor entry. Objects may rotate, so confirm floor access and displays before planning around one relic.",
    },
    {
      id: "leifeng-ruins-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-ruins-1200.webp",
      alt: "Old brick remains of Leifeng Pagoda are protected inside the present visitor building.",
      width: 1200,
      height: 800,
      caption: "The protected brick base is material evidence for the earlier pagoda. Railings, glass and the surrounding building belong to modern conservation and visitor presentation.",
    },
    {
      id: "leifeng-old",
      type: "paragraph",
      text: "A rights-cleared pre-collapse photograph adds the missing middle layer. Compare its damaged masonry mass with the present roofed outline: neither should be mistaken for the other. The photograph documents the old tower’s late condition, not its appearance when first built. Where current displays include reliefs, murals or White Snake scenes, they make a modern editorial choice about which version visitors will remember. Treat any such display as interpretation even when it stands above authentic foundations.",
    },
    {
      id: "leifeng-old-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/leifeng-1918-1200.webp",
      alt: "The damaged old Leifeng Pagoda photographed in 1918 before its 1924 collapse.",
      width: 1200,
      height: 850,
      caption: "Sekino Tadashi photographed the damaged old tower in 1918. This historical image shows a late condition before the 1924 collapse, not the pagoda’s original Wuyue appearance. Rights review is recorded in the image plan.",
    },
    {
      id: "jinshan-heading",
      type: "heading",
      level: 2,
      text: "Jinshan adds a living temple and a different way of attaching story to place",
    },
    {
      id: "jinshan",
      type: "paragraph",
      text: "Jinshan, formally Jiangtian Chan Temple, should first be read as an active Buddhist institution. Temple use, worshippers and restricted areas take priority over its role in White Snake tourism. The uphill arrangement also creates a real mobility cost that a flat story map hides. A 2026 fire-service report, describing a local museum display, says a 1948 fire damaged more than 300 historic rooms or buildings; without a stronger archive in this source pack, that number remains attributed rather than stated as an independent primary fact. It is still enough to warn against calling the present complex wholly ancient fabric.",
    },
    {
      id: "jinshan-entrance-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/jinshan-entrance-1200.webp",
      alt: "The entrance to Jinshan Temple in Zhenjiang carries the formal name Jiangtian Chan Temple.",
      width: 1200,
      height: 800,
      caption: "The entrance makes the dual identity visible: commonly called Jinshan Temple, the active Buddhist institution is formally Jiangtian Chan Temple. The name is evidence; it does not turn the temple into a story set.",
    },
    {
      id: "jinshan-geography",
      type: "paragraph",
      text: "A scholarly temple history and historical-geography research support a cautious geographical statement: nineteenth-century channel change and sedimentation progressively altered Jinshan’s island–shore relationship, and the hill is now joined to land. Sources do not justify turning one precise joining year into an evergreen fact. More importantly, physical change cannot prove the literary flood. Use today’s water-and-hill view to understand why the scene became imaginable, not to reverse a theatrical episode into hydrological history.",
    },
    {
      id: "cishou-figure",
      type: "figure",
      src: "/images/guides/white-snake-legend-hangzhou-zhenjiang/cishou-pagoda-1200.webp",
      alt: "Cishou Pagoda stands within the Jinshan Temple complex in Zhenjiang.",
      width: 1200,
      height: 800,
      caption: "Cishou Pagoda is a Zhenjiang landmark, not Leifeng Pagoda transported into another scene. Verify any detailed construction date against a temple or heritage source before publication.",
    },
    {
      id: "cave-warning",
      type: "callout",
      title: "Do not promise Fahai Cave",
      body: "Scholarship traces a naming history in which Peigong Cave and Fahai Cave were presented differently over time. That is evidence of landscape storytelling, not Fahai’s biography. Access, wording and photography rules for 2026 have not been confirmed, so this guide does not promise entry. If closed or unclear, use public temple fabric, Cishou Pagoda and a lawful water–hill viewpoint instead.",
      tone: "warning",
    },
    {
      id: "evidence-heading",
      type: "heading",
      level: 2,
      text: "What does each site actually let you claim?",
    },
    {
      id: "evidence-table",
      type: "table",
      caption: "Site-by-site evidence boundary",
      columns: ["Place", "Strongest evidence", "Story layer", "Modern presentation"],
      rows: [
        ["Broken Bridge", "A maintained bridge in the West Lake cultural landscape", "Meeting and reunion associations", "Current signs, guided narratives and photo framing"],
        ["Old Leifeng site", "Foundation, brick base, underground chamber record and Buddhist finds", "Imprisonment beneath the pagoda", "Protected ruin and archaeological explanation"],
        ["Present Leifeng tower", "A modern building over a protected site", "White Snake scenes selected for display", "Architecture and visitor route; reliefs or murals only if currently displayed"],
        ["Jinshan / Jiangtian Temple", "A living Buddhist complex with documented rebuilding and changing geography", "Flooding Jinshan and later Fahai associations", "Cave naming, attraction events and contemporary interpretation"],
      ],
    },
    {
      id: "choice-heading",
      type: "heading",
      level: 2,
      text: "Is Hangzhou enough, or should you add Zhenjiang?",
    },
    {
      id: "choice",
      type: "comparison",
      title: "Choose by the question you want the trip to answer",
      columns: [
        {
          heading: "Hangzhou only",
          items: [
            "Best for a first encounter with the legend’s most legible bridge–pagoda geography",
            "Shows a real landscape feature, an excavated old site and a modern reconstruction in one city",
            "The sensible default when Zhenjiang would be a detour or create a rushed transfer day",
          ],
        },
        {
          heading: "Add Zhenjiang",
          items: [
            "Worthwhile when Jiangsu already fits the route and Jinshan can receive a separate half-day",
            "Adds a living temple, hillside movement and evidence of later place naming",
            "Best for readers comparing how literature becomes landscape, not for proving an origin",
          ],
        },
        {
          heading: "Skip both as a story project",
          items: [
            "Appropriate if the main interest is ordinary West Lake sightseeing rather than version history",
            "Better for travellers who cannot use the uphill Jinshan route and do not value the comparison",
            "Do not spend another city stop simply because a film scene used the name",
          ],
        },
      ],
    },
    {
      id: "choice-rule",
      type: "paragraph",
      text: "Before adding Zhenjiang, count usable time rather than train minutes: checkout, station access, security, waiting, local transfer, luggage and missed-connection consequences. Search 12306 for the actual date and stations; this article freezes no timetable or inventory. If the comparison cannot keep an independent half-day after those costs, Hangzhou is enough.",
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "Use one half-day in each city to reveal the layers",
    },
    {
      id: "hangzhou-sequence",
      type: "list",
      ordered: true,
      items: [
        "Begin at Broken Bridge. Locate the Bai Causeway junction and label the bridge as maintained landscape before discussing the meeting scene.",
        "Use one short public lakeshore orientation to establish the real separation between the bridge area and Leifeng. This is evidence work, not a full West Lake walk or cruise plan.",
        "Approach the present Leifeng tower from outside and identify its modern silhouette before entering.",
        "If current floor access allows, find the old brick base and conservation boundary. Do not promise the ruin, excavated underground chamber or a rotating museum object before rechecking.",
        "If a relief or story label is currently displayed, finish there. Ask which version it selects and what material evidence it does not provide.",
      ],
    },
    {
      id: "zhenjiang-sequence",
      type: "list",
      ordered: true,
      items: [
        "At the entrance, record both names—Jinshan Temple and Jiangtian Chan Temple—and remember that the religious institution is not a legend-themed set.",
        "Assess the stairs before committing to upper areas. Keep a lower public-space fallback for limited mobility, heat, rain or crowd control.",
        "Read current halls and repairs without assigning the whole complex an early founding date. Give worship and resident access priority.",
        "Keep Cishou Pagoda separate from Hangzhou’s Leifeng Pagoda, then use a public viewpoint to read hill, river and modern land connection.",
        "Only approach the Fahai/Peigong cave area if current signs and staff confirm access. If not, the naming history remains understandable without entry.",
      ],
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "Do not mistake a complete-looking story for complete evidence",
    },
    {
      id: "mistakes",
      type: "table",
      caption: "Seven shortcuts to reject",
      columns: ["Shortcut", "Correction"],
      rows: [
        ["The real bridge proves the meeting", "A real named place can carry folklore without documenting an event"],
        ["UNESCO means every visible structure is original", "The listing recognizes a developed cultural landscape with components that have changed"],
        ["Today’s Leifeng is the Wuyue tower", "The visitor building is modern; the protected old site is the material evidence"],
        ["The old photograph shows the first tower", "It shows a damaged late condition before the 1924 collapse"],
        ["Jinshan’s present halls all date from its founding", "Fire, rebuilding, repair and active use require building-by-building evidence"],
        ["Fahai Cave proves a historical resident", "Changing names show later association and tourism presentation"],
        ["The film plot is the ancient master version", "Named written and theatrical versions developed the familiar geography over time"],
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "If a tower, cave or connection fails, the comparison can still work",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Evidence-preserving fallbacks",
      columns: ["Failure", "Keep", "Remove"],
      rows: [
        ["Leifeng interior is closed", "Broken Bridge, exterior modern tower and a sourced old/modern comparison", "Claims that the ruin or underground chamber can be seen"],
        ["A museum object is off display", "Its excavated provenance as a sourced fact", "A promise to find it in a gallery"],
        ["Fahai/Peigong cave access or wording is unclear", "Documented naming history and public temple route", "Entry, sign text and photography promises"],
        ["Jinshan upper route is unsuitable", "Lower public fabric and a confirmed viewpoint", "A forced climb or claim that the visit is incomplete"],
        ["Rail or onward connection is fragile", "The complete Hangzhou evidence sequence", "Zhenjiang as a rushed label-collecting detour"],
      ],
    },
    {
      id: "respect",
      type: "callout",
      title: "A temple is not a film set",
      body: "Follow current signs for halls, caves, tripods and interior photography. Ask before photographing monks, worshippers, rituals or identifiable visitors, and never block a threshold for a recreation of a screen scene. Film, television and opera stills are not used here: familiarity is not republication permission, and a performance image cannot stand in for material history.",
      tone: "warning",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "Who gains most from this story line?",
    },
    {
      id: "who",
      type: "paragraph",
      text: "Choose it if you enjoy folklore, adaptation, archaeology or the way cities turn literature into visible landscape. Hangzhou alone suits most first-time visitors and anyone protecting pace. The two-city version suits a reader already moving through Zhejiang and Jiangsu who wants to compare two kinds of evidence. Skip the Zhenjiang addition if stairs, transfer risk or limited time outweigh that specific comparison. The useful souvenir is not a verdict on the ‘true birthplace’; it is the ability to name what is material, what is narrated and what was built to interpret the narration.",
    },
    {
      id: "help",
      type: "callout",
      title: "Need a current human check?",
      body: "Opening, reservations, cave access, rail service and photography rules were treated as dynamic on 14 August 2026. Send your dates, party size and approximate budget if you want a local human to check whether Zhenjiang fits without compressing a transfer day. No cave entry, train or rotating display will be promised before direct verification.",
      tone: "decision",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Keep the transport and pace questions with their existing owners",
      items: [
        {
          label: "Shanghai–Hangzhou transport choices",
          href: "/guides/shanghai-hangzhou-transport-route/",
          description: "Plan the city pair without turning this cultural comparison into another Hangzhou transport guide.",
        },
        {
          label: "First trip on China high-speed rail",
          href: "/guides/china-high-speed-train-first-time-guide/",
          description: "Verify stations, identity and boarding steps after deciding that Zhenjiang deserves the transfer.",
        },
        {
          label: "Is your China itinerary too rushed?",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Test whether an extra story stop leaves a usable half-day rather than another fragmented transfer.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Heritage, archaeology, temple and research sources",
      items: [
        {"label":"White Snake legend — Hangzhou record","url":"https://www.ihchina.cn/project_details/12185/","publisher":"China Intangible Cultural Heritage Digital Museum","reviewedAt":"2026-08-13"},
        {"label":"White Snake legend — Zhenjiang record","url":"https://www.ihchina.cn/project_details/12184.html","publisher":"China Intangible Cultural Heritage Digital Museum","reviewedAt":"2026-08-13"},
        {"label":"West Lake Cultural Landscape of Hangzhou","url":"https://whc.unesco.org/en/list/1334/","publisher":"UNESCO World Heritage Centre","reviewedAt":"2026-08-13"},
        {"label":"ICOMOS evaluation of the West Lake Cultural Landscape","url":"https://whc.unesco.org/document/152404","publisher":"ICOMOS / UNESCO","reviewedAt":"2026-08-13"},
        {"label":"Leifeng Pagoda history and protected ruins","url":"https://wgly.hangzhou.gov.cn/art/2022/12/1/art_1229696389_58943150.html","publisher":"Hangzhou Culture, Radio, Television and Tourism Bureau","reviewedAt":"2026-08-13"},
        {"label":"Leifeng Pagoda excavation report catalogue record","url":"https://buddhism.lib.ntu.edu.tw/DLMBS/en/search/search_detail.jsp?seq=554802","publisher":"National Taiwan University Buddhist Studies bibliography / Zhejiang archaeology report","reviewedAt":"2026-08-13"},
        {"label":"Thematic evolution of the White Snake story","url":"https://dflt.qdu.edu.cn/__local/A/39/DD/795E68F17B2300A5D3639ABEFD9_97A4FDA1_173BA8.pdf","publisher":"Dongfang Luntan, Cui Yunwei and Sun Xubo","reviewedAt":"2026-08-13"},
        {"label":"Landscape narrative at Fahai Cave and Leifeng Pagoda","url":"https://xbzs.ecnu.edu.cn/CN/html/201402014.htm","publisher":"Journal of East China Normal University, Yu Hongyan","reviewedAt":"2026-08-13"},
        {"label":"Jinshan Jiangtian Chan Temple","url":"https://www.jsfj.net/syzs_zjjsjtcs","publisher":"Buddhist Association of Jiangsu","reviewedAt":"2026-08-13"},
        {"label":"Zhenjiang fire-education museum report referencing the 1948 Jinshan fire","url":"https://js.119.gov.cn/202606/jsxfww-menu-gzdt_c_30a20aac24664a56b642.html","publisher":"Jiangsu Fire and Rescue","reviewedAt":"2026-08-13"},
        {"label":"Jinshan Temple history","url":"https://ccj.pku.edu.cn/article/info?id=286660025","publisher":"Peking University journal platform, Xu Shiyi","reviewedAt":"2026-08-13"},
        {"label":"Historical channel evolution of the Zhenjiang reach","url":"https://www.geog.com.cn/EN/abstract/article/0375-5444/47762","publisher":"Acta Geographica Sinica, Yang Xiao","reviewedAt":"2026-08-13"},
        {"label":"China Railway ticket and schedule verification","url":"https://www.12306.cn/en/index.html","publisher":"China Railway 12306","reviewedAt":"2026-08-13"},
        {"label":"Hero photograph: Broken Bridge by Suicasmo, CC0 1.0; cropped, resized and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:Broken_Bridge_(Hangzhou)_20250505.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"Body photograph: modern Leifeng Pagoda by Suicasmo, CC0 1.0; cropped, resized and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:Leifeng_Pagoda_20250505.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"Body photograph: Leifeng Pagoda archaeological site by HoweyYuan, CC BY-SA 4.0; cropped, resized and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:Site_of_Leifeng_Pagoda_20240729.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"Historical photograph: Leifeng Pagoda in 1918 by Sekino Tadashi, public domain; proportionally resized, placed on a neutral canvas and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:Leifeng_Pagoda_in_Hangzhou,_1918.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"1939 source-volume record for the 1918 Leifeng Pagoda photograph","url":"https://ndlsearch.ndl.go.jp/books/R100000039-I1902745","publisher":"National Diet Library of Japan","reviewedAt":"2026-08-14"},
        {"label":"Body photograph: Jinshan Jiangtian Chan Temple entrance by Yumeto, CC BY-SA 4.0; cropped, resized and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:20240806_Jinshan_Si.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"Body photograph: Cishou Pagoda by Yumeto, CC BY-SA 4.0; cropped, resized and converted to WebP","url":"https://commons.wikimedia.org/wiki/File:20240806_Cishou_Ta.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-14"},
        {"label":"CC0 1.0 dedication for the Broken Bridge and modern Leifeng derivatives","url":"https://creativecommons.org/publicdomain/zero/1.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"},
        {"label":"CC BY-SA 4.0 licence for the cropped image derivatives","url":"https://creativecommons.org/licenses/by-sa/4.0/","publisher":"Creative Commons","reviewedAt":"2026-08-14"}
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
