import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  "schemaVersion": "1.0.0",
  "blocks": [
    {"id":"lead","type":"lead","text":"Yingge (英歌) becomes easy to flatten into a short clip: painted faces, forceful stick strikes and a fast-moving crowd. A live performance is more legible when you verify the team and event first, then watch formation, rhythm and procession together. The records for Chaoyang, Puning and Jiazi describe related but distinct local practices; none supplies a single rule for every Yingge team."},
    {"id":"answer","type":"callout","title":"Verify one named team at one named event","body":"Use a dated notice from the organizer, local culture authority or team. Match the team name, locality, event, exact date, route or venue, and weather/crowd update. At the performance, watch three passes: how the formation is organized, how paired sticks and footwork answer percussion, and how the group moves through its route. Do not identify a style or Water Margin character from face paint alone.","tone":"decision"},
    {"id":"scope-heading","type":"heading","level":2,"text":"What the name Yingge establishes—and what it does not"},
    {"id":"scope","type":"paragraph","text":"Yingge is strongly associated with eastern Guangdong, especially Chaoshan and nearby communities, and combines group movement, rhythmic stick work, percussion, processional space and dramatic character presentation. National intangible-cultural-heritage records exist separately for Chaoyang Yingge, Puning Yingge and Jiazi Yingge. Those records confirm documented local lineages and characteristics. They do not make every troupe identical, prove that a current show follows an old description unchanged, or turn all painted warrior processions into Yingge. A named team’s own programme and local interpretation are needed for the performance in front of you."},
    {"id":"records-heading","type":"heading","level":2,"text":"Keep the three official records separate"},
    {"id":"records","type":"table","caption":"Differences supported by the cited heritage records","columns":["Recorded project","What its official record highlights","Safe conclusion","Do not generalize"],"rows":[["Chaoyang Yingge (潮阳英歌)","Slow, medium and fast local types; differences in stick length, rhythm and distribution; front and rear performance sections","Chaoyang contains documented internal variation","One speed, stick size or sequence for all Yingge"],["Puning Yingge (普宁英歌)","Locally recorded team-number traditions, changing formations and an association with heroes attacking Damingfu in Water Margin","That narrative and those numbers belong to the Puning record","Every team enacts the same episode or must field 24, 36, 72 or 108 people"],["Jiazi Yingge (甲子英歌)","A four-part processional structure with locally named components and small dramatic pieces","Jiazi has its own documented organization","That its four-part sequence is a national template"]]},
    {"id":"verify-heading","type":"heading","level":2,"text":"A current-event notice must answer six questions"},
    {"id":"verify","type":"table","caption":"Before travelling for a performance","columns":["Check","Evidence to seek","If it is missing"],"rows":[["Team","Full team name and home locality","Treat the clip or poster as a discovery lead only"],["Organizer","Government, temple/community body, venue or named producer","Ask who can confirm changes"],["Date and time","A notice for the exact year and day","Do not infer recurrence from last year"],["Place and route","Venue entrance, assembly point or street route","Keep a stationary cultural-site fallback"],["Conditions","Weather, road closure, capacity and crowd-control note","Recheck on the morning of the event"],["Programme identity","Yingge named explicitly, not just “folk parade”","Do not label an unknown act yourself"]]},
    {"id":"sources-order","type":"list","ordered":true,"items":["Start with the organizer, municipal culture authority or team’s verified channel.","Match the same event across a dated government notice and direct organizer information when possible.","Use the national ICH records to understand form-level distinctions, not to confirm today’s timetable.","Use news reports, blogs and viral clips to discover names; return to a direct source before committing travel time.","If current official sources conflict, contact the organizer or keep the event optional."]},
    {"id":"formation-heading","type":"heading","level":2,"text":"First pass: read the formation"},
    {"id":"formation","type":"paragraph","text":"Stand where you can see several rows rather than only the front performer. Notice leaders, paired bodies, spacing, diagonals, turns and how the line opens or compresses. A procession must also negotiate a real street: corners, spectators, barriers and pauses can reshape what appears in a staged video. Do not assume every pause is a ritual unit or every formation has one fixed symbolic translation. Describe the visible change first, then consult the team’s programme for its local name."},
    {"id":"rhythm-heading","type":"heading","level":2,"text":"Second pass: connect sticks, feet and percussion"},
    {"id":"rhythm","type":"paragraph","text":"Follow one pair of performers long enough to hear when their sticks meet, when feet land and when the percussion changes. Then widen your attention to see whether rows answer or mirror each other. Speed alone is a poor measure: weight transfer, synchronized recovery and the control needed to maintain distance are part of the work. Stick dimensions, striking patterns and tempo vary in the official local records, so a slow passage is not automatically less credible than a rapid one."},
    {"id":"route-heading","type":"heading","level":2,"text":"Third pass: watch the performance become a procession"},
    {"id":"route","type":"paragraph","text":"Yingge can occupy a stage, square or moving route. On a street, observe how the front section signals direction, how the main body preserves rhythm, what musicians do during a stop and whether a rear section or other acts follow. The boundary between performers, stewards and spectators is operational, not decorative. Never step backward into the route for a photograph, enter a gap in the formation or treat a temple/community stop as open staging space."},
    {"id":"scenarios-heading","type":"heading","level":2,"text":"Choose the encounter that matches your trip"},
    {"id":"scenarios","type":"comparison","title":"Two sensible first-viewing plans","columns":[{"heading":"Festival or street procession","items":["Best for seeing route, crowd relationship and formation adapt","Requires same-day weather, traffic and start-point verification","Accept that sightlines and timing may be uncertain"]},{"heading":"Curated stage or public-culture programme","items":["Best for a bounded time, clearer sightline and programme note","May shorten or rearrange a processional form","Confirm the named team and locality rather than judging the backdrop"]},{"heading":"Keep it optional","items":["Only an old clip or undated poster can be found","Your transfer depends on an exact finish time","Crowd, percussion or standing conditions do not suit the group"]}]},
    {"id":"recovery-heading","type":"heading","level":2,"text":"Common misreadings and how to recover"},
    {"id":"recovery","type":"table","caption":"When the clip, label or day does not match your expectation","columns":["Problem","Do now","Evidence boundary"],"rows":[["The shared video has no date or team name","Reverse-search names only as leads; find the current organizer notice","A popular clip cannot confirm a future appearance"],["The announced team is replaced","Record the actual team and locality before describing style","One team cannot stand in for the advertised one"],["You expected the Puning Water Margin account everywhere","Ask whether the local programme names a story or characters","The Puning record does not prove a universal narrative"],["The route is delayed or shortened","Follow steward instructions and protect onward-travel buffer","Operational change does not by itself prove loss of tradition"],["You cannot see the formation","Move only through public spectator space to a side or raised legal viewpoint","A face close-up cannot support claims about group structure"],["Photography is restricted","Put the phone away and use an authorized organizer image later","Attendance does not grant performer or image rights"]]},
    {"id":"respect","type":"callout","title":"A public procession is not an unowned film set","body":"Ask before making close portraits, especially of children or backstage preparation. Keep clear of performers, musicians, stewards, temple thresholds and resident access. Do not ask a team to repeat a strike or reveal private preparation for content. Painted faces and costume do not erase a performer’s likeness or the photographer’s copyright.","tone":"warning"},
    {"id":"checklist-heading","type":"heading","level":2,"text":"Save this field checklist"},
    {"id":"checklist","type":"list","items":["Named team and its home locality","Organizer’s dated notice and direct contact","Exact date, assembly point, route and expected duration","Morning-of weather, traffic and cancellation check","A lawful viewpoint showing formation and musicians","Hearing protection, water and an exit plan for dense crowds","Permission before close photography or publication"]},
    {"id":"judgment-heading","type":"heading","level":2,"text":"The evidence-led takeaway"},
    {"id":"judgment","type":"paragraph","text":"The official records support a family of locally documented practices, not a frozen master version. Homeground’s editorial test is simple: after the performance, can you name the team and place, describe one change in formation and one relationship between movement and sound, and say which interpretation remains unverified? That is a stronger first encounter than collecting a painted-face clip and calling it a complete explanation of Chaoshan culture."},
    {"id":"help","type":"callout","title":"Homeground","body":"Schedules, routes and troupe line-ups were last reviewed on 13 August 2026 and must be checked again for your date. Send your city, date and crowd or accessibility needs if you want a local human to verify a named event and a realistic fallback without promising an old viral clip will repeat.","tone":"decision"},
    {"id":"links","type":"internal-links","title":"Continue understanding Guangdong","items":[{"label":"Verify a Foshan lion-dance performance","href":"/guides/foshan-lion-dance-first-performance-workflow/","description":"Use a separate evidence trail for Guangdong awakening lion rather than merging the forms."},{"label":"Plan around China’s public-holiday calendar","href":"/guides/china-public-holidays-travel-calendar/","description":"Understand calendar and crowd pressure without assuming a performance recurs."},{"label":"How Guangzhou morning tea works","href":"/guides/how-guangzhou-morning-tea-works/","description":"Read another regional practice through its real service flow and local variation."}]},
    {"id":"sources","type":"sources","title":"Official and independent sources","items":[{"label":"Chaoyang Yingge","url":"https://www.ihchina.cn/project_details/12901.html","publisher":"China Intangible Cultural Heritage","reviewedAt":"2026-08-13"},{"label":"Puning Yingge","url":"https://www.ihchina.cn/project_details/12902.html","publisher":"China Intangible Cultural Heritage","reviewedAt":"2026-08-13"},{"label":"Jiazi Yingge","url":"https://www.ihchina.cn/project_details/12903.html","publisher":"China Intangible Cultural Heritage","reviewedAt":"2026-08-13"},{"label":"Yingge cultural highlight","url":"https://discoverguangdong.com/cultural-highlights/tu5abna3km5gbrswco1xdpge","publisher":"Discover Guangdong","reviewedAt":"2026-08-13"},{"label":"2026 Shantou event report","url":"https://stgsl.shantou.gov.cn/stgsl/tpxw/202602/a65ed783eae844c887242068a97c77e2.shtml","publisher":"Shantou Federation of Industry and Commerce","reviewedAt":"2026-08-13"},{"label":"Research on contemporary Yingge transmission","url":"https://tyxk.scnu.edu.cn/a/20240802/2929.html","publisher":"Journal of Physical Education, South China Normal University","reviewedAt":"2026-08-13"}]}
  ]
} as const satisfies StructuredPageBody;

export default body;
