import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "An ‘accessible room’ filter is a lead, not a verdict. A room may have grab bars but sit beyond a step, a narrow lift or a bathroom door your chair cannot pass. Before paying, verify one continuous route from the street or drop-off point to the exact room, then test the bed and bathroom against your own body, mobility device and transfer method." },
    { id: "answer", type: "callout", title: "The direct answer", tone: "decision", body: "Book only after the property supplies recent, room-type-specific evidence for every non-negotiable link: arrival, entrance, reception, lift, corridor, room door, bed transfer and bathroom. Ask for numbers and photographs rather than ‘yes, accessible.’ Keep a refundable backup room or second hotel until the assigned room is confirmed. A law, standard, brand promise or platform icon cannot certify that one room works for one traveller today." },
    { id: "three-layers", type: "paragraph", text: "Keep three layers separate. Chinese law and engineering standards set duties and technical baselines. A booking platform displays information supplied through its own listing process. The property controls the building, current maintenance and room assignment. Evidence at one layer does not prove the other two: even a correctly labelled room can be unusable if the route is blocked or the grab bars are on the wrong transfer side." },
    { id: "route-heading", type: "heading", level: 2, text: "Audit the street-to-room chain" },
    { id: "route-table", type: "table", caption: "A room is usable only when every required link works", columns: ["Link", "Ask the property to show", "What changes the decision"], rows: [["Street or vehicle stop", "Kerb, surface, slope, legal drop-off point and distance to the door", "Rain, a steep ramp, bollards or luggage can turn a short approach into a barrier"], ["Entrance and reception", "All steps, the usable door, threshold, clear opening and route to check-in", "A separate accessible entrance is useful only if it is open at your arrival time"], ["Lift and corridor", "Lift-door opening, cabin space, floor served and corridor obstacles", "One working lift with no outage fallback may be too fragile for the trip"], ["Assigned room", "Door opening, threshold, turning space and furniture layout for that room category", "A sample-room photograph cannot prove the room held for you"], ["Bed", "Clear transfer side, clear width and bed height with mattress", "Left/right transfer, hoist legs and mattress compression are personal fit questions"], ["Bathroom", "Door, toilet transfer side, bars, shower threshold, seat, controls and call device", "One misplaced fixed feature can make the whole room unusable"]] },
    { id: "request-heading", type: "heading", level: 2, text: "Send a measurement-and-photo request" },
    { id: "request-list", type: "list", items: ["State the mobility device's width and turning needs, the preferred transfer side and whether the traveller can manage any step. Do not send medical details the property does not need.", "Ask for the clear opening with each door fully open—not the width of the door leaf or frame—and photograph the threshold beside a ruler.", "Request a current image of the lift entrance and cabin, the assigned room layout, both sides of the toilet and the complete shower entrance.", "Ask whether furniture can be moved without narrowing the route, and who will do it before arrival. Never assume a heavy bed can move.", "Confirm whether the shower seat is fixed, folding or portable, its height, depth, width and rated load. A loose plastic stool is not equivalent to a properly installed seat.", "Have the property date the evidence and identify whether it shows your booked room, the same room type or only a representative room."] },
    { id: "standard-floor", type: "callout", title: "Use official dimensions as an evidence floor, not a personal prescription", tone: "neutral", body: "The mandatory GB 55019-2021 engineering code includes a continuous accessible route; accessible-room wheelchair turning space; a bed-side passage of at least 1.20 metres; an accessible bathroom; and specific requirements for doors, lifts, grab bars, shower seats and call devices. It applies to new, extended and renovated construction. China's accessibility law separately recognises that existing buildings may need planned alteration or necessary alternatives. Neither text proves a particular older hotel, current room assignment or individual fit." },
    { id: "bath-heading", type: "heading", level: 2, text: "Test the bathroom as a transfer sequence" },
    { id: "bath-table", type: "table", caption: "Photograph the usable space, not just the equipment", columns: ["Feature", "Useful evidence", "Common false positive"], rows: [["Bathroom door", "Clear opening, threshold and whether the door slides or opens outward", "A wide room door followed by a narrow bathroom door"], ["Toilet", "Seat height, free transfer side and fixed bar positions", "Bars exist but block the traveller's transfer side"], ["Shower", "No-step entry, clear approach, installed seat and reachable hand shower", "A shower photograph hides a lip or fixed glass panel"], ["Basin", "Knee/foot clearance, reachable tap and mirror", "A low basin with a cabinet underneath"], ["Help call", "Location reachable from the toilet and floor; how staff respond", "A cord tied up, unplugged or reachable only while standing"]] },
    { id: "scenarios-heading", type: "heading", level: 2, text: "Two rooms can carry the same label and fit different people" },
    { id: "wheelchair-scenario", type: "paragraph", text: "Scenario 1 — a manual wheelchair user transfers to the left. The entrance and lift work, but the toilet's free space is on the right and the bed has only a narrow left side. The hotel has not necessarily lied about having an accessible room; this room simply fails this traveller's transfer sequence. A mirrored room, furniture reset or different property changes the conclusion." },
    { id: "late-scenario", type: "paragraph", text: "Scenario 2 — a traveller using a walker arrives at 23:00. The step-free side entrance is locked after 22:00 and the only lift is under maintenance. Daytime photographs were accurate but the arrival chain is not. Confirm staffed hours, after-hours access and a ground-floor or second-lift fallback before the cancellation deadline." },
    { id: "sensory-scenario", type: "callout", title: "Physical access is not the whole room", tone: "warning", body: "A deaf solo traveller may need a visible or vibrating alert and a written emergency-contact method. A blind or low-vision traveller may need a staff-guided orientation, tactile or high-contrast controls and an unobstructed memorisable route. GB 55019 addresses multi-sensory information and accessible-room doorbells, but the actual equipment and staff procedure must still be confirmed for the assigned room." },
    { id: "book-heading", type: "heading", level: 2, text: "Convert the evidence into a protected booking" },
    { id: "book-steps", type: "list", ordered: true, items: ["Write two lists: conditions without which the room is unsafe or unusable, and preferences you can trade away.", "Shortlist properties that answer from the property itself. A call-centre promise about a brand is not unit-level evidence.", "Send the same numbered checklist to each property and keep replies inside a channel you can save.", "Match every photograph and measurement to the booked room type, arrival entrance and dates. Ask the name or role of the person confirming it.", "Choose a cancellation deadline that leaves time to obtain answers, and hold a workable backup rather than a cheaper but unverified substitute.", "Reconfirm the exact room, operating lift and arrival route shortly before travel; ask that the accessibility notes remain attached to the booking."] },
    { id: "arrival-heading", type: "heading", level: 2, text: "Inspect before unpacking" },
    { id: "arrival-list", type: "list", items: ["Follow the promised route from the real drop-off point; do not let staff carry a person or mobility device over an unsafe barrier as the default plan.", "Ask to see the assigned room before luggage is distributed. Check doorways, turning, transfer side, shower and call device in the order you will use them.", "Test only normal guest controls. Do not load-test grab bars, dismantle equipment or activate an emergency call without first coordinating with staff.", "Keep essential mobility equipment, medication and chargers with the traveller until the room is accepted."] },
    { id: "failure-heading", type: "heading", level: 2, text: "Recover when the promised chain breaks" },
    { id: "failure-table", type: "table", caption: "Fix the function first; document the dispute second", columns: ["Failure", "Immediate request", "Leave when"], rows: [["Wrong room assigned", "Show the written confirmation and ask for the verified room or a room inspected against the same checklist", "No room meets a non-negotiable transfer or access need"], ["Route blocked", "Ask for a safe, lawful step-free route and removal of movable obstruction", "The alternative requires lifting, tailgating or an unsafe surface"], ["Lift unavailable", "Request an accessible ground-floor room or another functioning route", "The traveller cannot independently or safely reach the room"], ["Bathroom differs", "Ask for a mirrored room or genuinely installed matching equipment", "The proposal is an unsecured stool, loose bar or staff promise that does not restore safe use"], ["Property cannot solve it", "Request cancellation and contact the booking channel while relocating", "Waiting risks being stranded late at night or without essential care"]] },
    { id: "records", type: "paragraph", text: "Preserve the booking, property name and address, dated messages, the exact unmet feature, staff role and outcome. Take narrow photographs that prove the mismatch while hiding faces, room numbers, keys, passports and other guests. Describe function—‘bathroom opening measured smaller than the confirmed value’—rather than alleging legal non-compliance. A platform can assess the booking evidence; only competent authorities determine compliance." },
    { id: "conditions", type: "table", caption: "Conditions that should change your default", columns: ["Condition", "More cautious choice"], rows: [["First night, late arrival or no local helper", "A staffed property with a fully evidenced route and a held backup"], ["Power wheelchair, hoist or one-sided transfer", "Exact-room dimensions and photos; generic room-type evidence is insufficient"], ["Several accessible rooms confirmed", "Ask which one is physically held and what happens after maintenance or overbooking"], ["Only a historic building can deliver the desired experience", "Accept it only if the actual route fits; otherwise stay accessibly and visit without luggage"], ["Property will not measure", "Treat the feature as unverified, not as probably adequate"]] },
    { id: "dynamic", type: "paragraph", text: "Official law and standard pages were reviewed on August 13, 2026. GB/T 47543-2026, the recommended national standard for accessible tourism service in tourism hotels, became effective on August 1, 2026; its existence does not mean every property claims or demonstrates conformance. Property equipment, maintenance, staff hours and room assignment are dynamic. Reconfirm close to arrival." },
    { id: "links", type: "internal-links", title: "Continue checking the stay", items: [{ label: "Where to stay in China", href: "/stay/", description: "Return to the accommodation decision collection." }, { label: "Test whether a China hotel is really near the metro", href: "/guides/china-hotel-near-metro/", description: "Audit the station exit, pavement and lobby rather than map distance." }, { label: "Choose a commercial aparthotel or residential rental", href: "/guides/commercial-aparthotel-or-residential-rental-china/", description: "Compare staffed recovery, building access and the exact operating model." }, { label: "Understand minsu, homestay and hotel labels", href: "/guides/minsu-homestay-or-hotel-china/", description: "Turn accommodation labels into room- and route-level questions." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Accessible Environment Development Law of the People's Republic of China", url: "https://www.cdpf.org.cn/ztzl/zxzt1/2024/cjrqybzflfggzxxgkxt/xfjfl/lfstl/dbcd52526ef14aa0ba649e7feb25a18d.htm", publisher: "China Disabled Persons' Federation", reviewedAt: "2026-08-13" }, { label: "GB 55019-2021 General Code for Accessibility of Buildings and Municipal Engineering Projects", url: "https://cl.huaian.gov.cn/col/8349_118464/art/w/17144928/1715582990210UdXHUSlL.html", publisher: "Huai'an Disabled Persons' Federation", reviewedAt: "2026-08-13" }, { label: "Announcement implementing mandatory GB 55019-2021", url: "https://www.beijing.gov.cn/zhengce/zhengcefagui/qtwj/202204/t20220412_2674451.html", publisher: "Beijing Municipal Government / Ministry of Housing and Urban-Rural Development", reviewedAt: "2026-08-13" }, { label: "GB/T 47543-2026 Specification on accessible tourism service — Tourism hotel", url: "https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=11FB862766387228085E1B8F974590D7", publisher: "National Public Service Platform for Standards Information", reviewedAt: "2026-08-13" }, { label: "Deployment to implement accessibility law and construction standards", url: "https://www.cdpf.org.cn/xwzx/clyw2/5536a8ea36af499c8c4196f18aa6815e.htm", publisher: "China Disabled Persons' Federation", reviewedAt: "2026-08-13" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
