import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "成都值得放进中国行程，有三个不同的理由，而它们并不是同一趟旅行：它是北京、西安、上海之后的慢节奏对照；是第一次看熊猫最省事的大城市基地；也是整段四川行程的规划门户。先想清楚你买的是哪一个，再决定订几晚。",
    },
    {
      id: "role-heading",
      type: "heading",
      level: 2,
      text: "成都在你的路线里到底做什么",
    },
    {
      id: "role-1",
      type: "paragraph",
      text: "成都常被形容为“安逸”，很多人听成了“小”。它既不小也不省事：这是一个非常大的省会，有两座在用的机场、好几个彼此独立的铁路枢纽，景点分散在不同方向。所谓的慢，来自这座城市允许你怎么用它，而不是它没什么可看。一段茶馆时间可以就是一段茶馆时间；一顿饭可以撑起一个下午，而不必被塞在两个景点之间。",
    },
    {
      id: "role-2",
      type: "paragraph",
      text: "最常见的路线错误，是把所有“从成都能去”的地方都算成成都景点。熊猫基地在城市边缘，仍然可以算成都的一个上午；都江堰是成都以西的另一座城市；三星堆在广汉；乐山是南面的另一座城市；九寨沟是需要自己的交通链和自己床位的山地目的地。成都是它们的门户，不是它们的街区。",
    },
    {
      id: "nights-heading",
      type: "heading",
      level: 2,
      text: "成都本身需要几个完整日？",
    },
    {
      id: "nights-1",
      type: "paragraph",
      text: "数的是游览日，不是行程表上的标签。晚上落地天府换来的是一顿晚饭，不是一个成都日；早上出发去九寨沟是转场日，哪怕铁路段看起来很短。",
    },
    {
      id: "nights-table",
      type: "table",
      caption: "成都与四川的几种停留形态",
      columns: ["停留形态", "成都段住宿晚数", "可用游览日", "能诚实装下什么", "应该舍弃什么"],
      rows: [
        [
          "最短城市初访",
          "2晚",
          "约1.5天",
          "一个以熊猫为主的上午，加一个城市中心时段",
          "三星堆、乐山，以及任何“看过四川了”的说法",
        ],
        [
          "推荐城市停留",
          "3晚",
          "约2–2.5天",
          "熊猫、中心城区文化与饮食，再加一个弹性半天",
          "超过一个的大型外出行程",
        ],
        [
          "城市加一条支线",
          "4晚",
          "约3天",
          "成都，加上三星堆、都江堰或乐山其中一条支线",
          "把九寨沟当日往返；两条远支线连着排",
        ],
        [
          "成都与更大的四川",
          "5–6晚以上",
          "约4–5天以上",
          "两个城市日，加一段过夜或多日的区域路线",
          "为了不搬酒店而把每一晚都留在市中心",
        ],
      ],
    },
    {
      id: "nights-2",
      type: "paragraph",
      text: "两晚在交通友好时成立：中午前抵达，第二天上午给熊猫，再让市中心拥有一个扎实时段，第三天较晚离开。三晚的容错高得多，因为熊猫那个上午不必再和川剧夜场或一段从容的中心城区散步挤在同一天。",
    },
    {
      id: "nights-3",
      type: "paragraph",
      text: "四晚不该等于三次一日游。更好的形态是两个城市日加一条支线。五到六晚才谈得上成都加乐山或都江堰过夜，或者一段独立的九寨沟行程。真正的衡量标准是行李在哪里过夜，而不是某个套餐把什么都叫作“成都”。",
    },
    {
      id: "stay-heading",
      type: "heading",
      level: 2,
      text: "住宿：让每个区域只承担一件事",
    },
    {
      id: "stay-1",
      type: "paragraph",
      text: "最好的基地是能保住这趟旅行大部分安排的那个，而不是离某一个景点最近的那个。地铁可达性、酒店真实入口、早餐，以及首末两天的交通任务，都比区域名气更重要。",
    },
    {
      id: "stay-table",
      type: "table",
      caption: "四个成都基地，按承担任务比较",
      columns: ["区域", "最适合承担的任务", "会变得更容易", "会变得更困难", "更适合谁"],
      rows: [
        [
          "春熙路／太古里",
          "第一次到成都的中心基地",
          "餐饮、夜间安排、大慈寺片区、多方向地铁",
          "人多；号称有地标景观的酒店也可能要穿过商场进门",
          "初访、情侣、以晚餐为重点的人",
        ],
        [
          "天府广场",
          "交通均衡的中心",
          "方位感、博物馆、人民公园一侧、换乘简单",
          "广场本身不是这座城市最有味道的夜晚",
          "家庭、短住、希望每天早上决策简单的人",
        ],
        [
          "宽窄巷子／人民公园一侧",
          "茶馆与老街节奏",
          "人民公园、街巷、慢早晨、西侧中心城区",
          "游客压力大；车辆进入和老建筑设施差异明显",
          "以文化为主的旅客与回访者",
        ],
        [
          "成都东站一带",
          "以转场为先的基地",
          "极早或极晚使用成都东站的车次",
          "体验城市很弱，多数景点仍要单独一趟车",
          "只适合一晚的铁路缓冲",
        ],
      ],
    },
    {
      id: "stay-2",
      type: "paragraph",
      text: "如果看重晚上，春熙路和太古里是实用默认项；但“太古里附近”可能意味着入口藏在商业体内部，请先确认从地铁走过去的路线和车辆上下客点。天府广场比它的照片更适合当基地：它位于几项中心任务之间，而不是独占某一种氛围。",
    },
    {
      id: "stay-3",
      type: "paragraph",
      text: "宽窄巷子与人民公园一侧最能表达这座城市的茶馆节奏，但具体是哪家物业，决定了巷子里的地址是有记忆点还是拖着大行李很难受。成都东站是个后勤方案，不是通用推荐：把它用在某趟固定车次前后的一晚，其余时间搬回市区更划算。",
    },
    {
      id: "teahouse-note",
      type: "callout",
      title: "茶馆本身就是行程，不是行程里的一站",
      body: "中心城区的茶馆值得坐到你能看出公共公园、社交习惯和商业服务是怎样叠在一起的。预算是一两个小时，不是一张照片。这是最容易体会到成都为什么要和北京、西安用不同方式规划的方法。",
      tone: "decision",
    },
    {
      id: "stay-network-links",
      type: "internal-links",
      title: "选定成都基地后，再核验具体物业",
      items: [
        {
          label: "酒店是真的靠近地铁吗？",
          href: "/zh/guides/china-hotel-near-metro/",
          description: "核对真正有用的出入口、商业体内部路线、过街与大堂，不只看地图半径。",
        },
        {
          label: "核验真正可用的无障碍客房",
          href: "/zh/guides/china-accessible-hotel-room-verification/",
          description: "为从街道到客房的完整路线索要对应房型的尺寸与证据。",
        },
        {
          label: "外宾预订、住宿登记与被拒恢复",
          href: "/zh/guides/foreigners-china-hotel/",
          description: "分清全国规则、平台页面与这家物业前台实际能够完成的流程。",
        },
        {
          label: "决定国际航班前最后一晚住哪里",
          href: "/zh/guides/china-last-night-before-international-flight/",
          description: "从准确航班与后备链比较成都市区最后一晚和天府或双流机场侧缓冲住宿。",
        },
      ],
    },
    {
      id: "stay-quote-handoff",
      type: "callout",
      title: "需要人工核对住宿区和房型吗？",
      tone: "decision",
      body: "请提供旅行日期、人数、房间数与床型要求、准确的抵离机场或火车站、重点行程、住宿预算及币种、行李情况，以及儿童、老人、行动不便或无障碍需求。Homeground 可以人工核验区域、物业事实并取得当次书面报价。书面报价不代表实时房态、最终价格或该物业一定能够为外宾办理登记；付款和抵达前仍须向具名物业再次确认。",
    },
    {
      id: "gateways-heading",
      type: "heading",
      level: 2,
      text: "天府、双流与几个火车站是分开的决定",
    },
    {
      id: "gateways-1",
      type: "paragraph",
      text: "成都天府国际机场（TFU）与成都双流国际机场（CTU）都是在用的客运机场，而且航班会在两场之间迁移。2026 年就有一批港澳台航班从天府转回双流，所以年初写下的行程可能会把你送错机场。可靠的做法只有一条：每一段都以当前行程单上的机场代码和航站楼为准，并在临行前向承运航司和机场公告再确认一次。",
    },
    {
      id: "gateways-table",
      type: "table",
      caption: "成都各门户及其影响",
      columns: ["枢纽", "实际角色", "对城市一侧的影响", "规划规则"],
      rows: [
        [
          "天府机场 TFU",
          "位于传统市区东南的大型新机场",
          "接驳距离长；地铁 18 号线有帮助，但仍要计算完整的酒店到登机口链条",
          "晚到不等于一个城市夜晚；按具体航班确认航站楼",
        ],
        [
          "双流机场 CTU",
          "位于市区西南、仍在运行的机场",
          "通常离成熟的中心与西南城区更近",
          "不要默认它只飞国内；部分地区与国际航线在此运行",
        ],
        [
          "成都东站",
          "多数高铁线路的主要门户",
          "地铁连接好，但不在中心步行范围",
          "以车票站名为准；预留排队与站内时间",
        ],
        [
          "成都南站",
          "城南的客运站",
          "与城南酒店和 18 号线机场方向天然搭配",
          "部分车次使用南站而非东站；不要凭印象替换",
        ],
        [
          "成都西站",
          "西侧铁路枢纽",
          "适用于部分向西和区域方向的车次",
          "订车前先核对车次号和中文站名",
        ],
        [
          "成都站（老“火车北站”）",
          "改扩建中，未办理客运",
          "无论旧地图标注如何，它现在都不能用",
          "2026 年中报道主体完成 70% 以上、目标 2027 年投用；不要按“即将重开”来规划",
        ],
      ],
    },
    {
      id: "gateways-2",
      type: "paragraph",
      text: "铁路和航空适用同一套纪律。成都东站常被默认，因为很多高铁走它；但南站和西站是真正独立的枢纽，不是同一栋楼的别名。路线摘要里写“成都”是不够的：把车票上的完整中文站名保存下来，再围绕那一栋楼安排酒店出发时间。",
    },
    {
      id: "city-heading",
      type: "heading",
      level: 2,
      text: "哪些内容真正属于城市日",
    },
    {
      id: "city-1",
      type: "paragraph",
      text: "好的成都城市日由彼此兼容的体验组成，而不是尽可能多的知名坐标。一种模式从人民公园或另一处中心茶馆开始，穿过西侧中心城区和一个博物馆或老街时段，以一顿不赶时间的饭结束。另一种用大慈寺和东侧中心城区，把更早的宗教空间与当代商业并置，然后直接进入街区餐饮，不再跨城。",
    },
    {
      id: "city-2",
      type: "paragraph",
      text: "第三种以武侯祠及其历史叙事为主，把旁边的商业街当作语境，而不是当作古城被完整保留的证据。更喜欢当代城市基础设施的旅客，可以把这一段换成城市绿道中连接良好的一段，而不是假装整条环线是一个景点。",
    },
    {
      id: "jinjiang-figure",
      type: "figure",
      src: "/images/destinations/chengdu/jinjiang-bridge-1200.webp",
      alt: "黄昏时成都中心城区锦江上的廊桥，水面倒映着现代写字楼。",
      width: 1200,
      height: 750,
      caption:
        "锦江给中心城区提供了一个不需要再跨城的夜晚。留一段靠水的时间，通常比再加第四个白天景点更值。",
    },
    {
      id: "city-3",
      type: "paragraph",
      text: "熊猫基地属于这座城市的游览系统，但它仍然会吃掉一个正经的上午加往返交通。请把它和同一侧城区的一个弹性下午搭配，而不是在“熊猫只要一小时”的假设下，同时排上远处的博物馆、固定城际车次和晚场演出。",
    },
    {
      id: "city-links",
      type: "internal-links",
      title: "把城市里的具体决定交给对应 owner",
      items: [
        {
          label: "成都熊猫基地还是都江堰熊猫谷？",
          href: "/zh/guides/chengdu-panda-base-or-dujiangyan-panda-valley/",
          description: "哪一个更适合你这次的看法，以及各自真正花掉多少时间和路程。",
        },
        {
          label: "成都环城绿道怎么用",
          href: "/zh/guides/chengdu-greenway-city-ring/",
          description: "为什么走连接良好的一段，比把整条环线当景点更有用。",
        },
        {
          label: "川剧与变脸：放回它的语境",
          href: "/zh/guides/sichuan-opera-face-changing-with-context/",
          description: "怎样挑节目和场地，以及变脸在整个表演传统里的位置。",
        },
      ],
    },
    {
      id: "branches-heading",
      type: "heading",
      level: 2,
      text: "哪些四川地点是支线，不是半天",
    },
    {
      id: "branches-1",
      type: "paragraph",
      text: "多数成都行程就是在这里崩的。下面每一个都从成都出发，但没有一个是市中心的附加项。",
    },
    {
      id: "branches-table",
      type: "table",
      caption: "成都的几条支线，以及各自真正需要的时间",
      columns: ["支线", "实际位置", "最低限度的诚实形态", "常见错误"],
      rows: [
        [
          "都江堰与熊猫谷",
          "都江堰，成都以西的另一座城市",
          "一整天；若加青城山则需过夜",
          "把熊猫谷说成不用付出交通成本的市区熊猫替代项",
        ],
        [
          "三星堆博物馆",
          "广汉，成都东北方向",
          "一整天，需分时预约和一条真实的展厅路线",
          "把一座重要考古博物馆当作下午顺路一停",
        ],
        [
          "乐山",
          "南面的另一座城市",
          "至少一个很长的整天；过夜会从容得多",
          "从成都出发一天连做乐山和峨眉",
        ],
        [
          "九寨沟",
          "更靠北的山地目的地",
          "自己的交通链和自己的住宿，通常要好几天",
          "任何形式的“九寨沟一日游”",
        ],
      ],
    },
    {
      id: "dujiangyan-figure",
      type: "figure",
      src: "/images/destinations/chengdu/dujiangyan-1200.webp",
      alt: "从高处俯瞰都江堰水利工程，江水在林木覆盖的山峦之间分流，远处是城区。",
      width: 1200,
      height: 750,
      caption: "都江堰是一整片河流尺度的工程景观，而且在它自己的城市里。这张视野就是它值得一整天、而不是一个下午的理由。",
    },
    {
      id: "branch-links",
      type: "internal-links",
      title: "订支线之前，先打开对应 owner",
      items: [
        {
          label: "三星堆博物馆：预约与展厅顺序",
          href: "/zh/guides/sanxingdui-museum-booking-and-gallery-order/",
          description: "预约方式、选哪个馆，以及能装进一天的看展路线。",
        },
        {
          label: "成都到九寨沟怎么走",
          href: "/zh/guides/chengdu-jiuzhaigou-transport-route/",
          description: "航空与公路方案，以及进沟之前这段路要花掉什么。",
        },
      ],
    },
    {
      id: "recheck-heading",
      type: "heading",
      level: 2,
      text: "临行前必须重新核对的几件事",
    },
    {
      id: "recheck-list",
      type: "list",
      items: [
        "每一段航班的机场代码、航站楼和承运航司——成都两场之间会互相调整航线。",
        "每张车票上的完整中文站名，因为东站、南站、西站是不同的建筑。",
        "熊猫基地与三星堆的分时预约，它们决定了那一天的形状。",
        "九寨沟的进出安排以及任何季节或天气导致的变化，它可能改动整段行程。",
        "公众假期周，四川的热门景区和它们的交通在这几周表现完全不同。",
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "两种典型翻车，以及怎么改",
    },
    {
      id: "scenario-1-heading",
      type: "heading",
      level: 3,
      text: "名义三晚，实际只有一天半",
    },
    {
      id: "scenario-1",
      type: "paragraph",
      text: "一对情侣晚上九点落地天府，计划第一个完整日去三星堆、第二天上午看熊猫、下午一点的车离开。实际结果是：抵达吃掉了第二天上午，三星堆占满第一整天，而熊猫的上午又撞上退房和跨城去车站。解决办法不是走快一点，而是把三星堆挪到后面的支线日或加一晚，并且让熊猫上午和离开日分开。",
    },
    {
      id: "scenario-2-heading",
      type: "heading",
      level: 3,
      text: "四晚全花在从市中心通勤",
    },
    {
      id: "scenario-2",
      type: "paragraph",
      text: "一家人守着一间市中心酒店，连着几天分别去都江堰、乐山和三星堆。每天都早出晚归，而他们本来想看的那座城市根本没发生。解决办法是两个受保护的成都日加一条支线，或者干脆在支线过夜，让返程不再吃掉第二天早上。",
    },
    {
      id: "next-heading",
      type: "heading",
      level: 2,
      text: "成都在整条路线中的位置",
    },
    {
      id: "next-1",
      type: "paragraph",
      text: "放在北京或西安之后，成都把节奏切换到日常生活、地方饮食和四川的山水；放在重庆之前，它又和更陡、更快的城市形成有意为之的对照。如果只是为了看熊猫而硬塞进紧凑的北京—西安—上海路线，它可能变成一次昂贵的绕路——先决定你买的是城市、熊猫，还是整个四川。",
    },
    {
      id: "next-links",
      type: "internal-links",
      title: "继续交给路线 owner",
      items: [
        {
          label: "北京、西安与成都：怎样排顺序",
          href: "/zh/guides/beijing-xian-chengdu-route-order/",
          description: "方向、门户，以及每种顺序真正能产生多少可用半天。",
        },
        {
          label: "十月去中国：黄金周还是往后错开？",
          href: "/zh/guides/china-in-october-golden-week-or-later/",
          description: "假期周怎样改变四川的人流、预订和交通。",
        },
        {
          label: "你的中国行程是不是太赶了？",
          href: "/zh/guides/is-your-china-itinerary-too-rushed/",
          description: "当问题是基地数量和连续转场，而不是成都本身时读这篇。",
        },
      ],
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "常见问题",
    },
    {
      id: "faq-1-heading",
      type: "heading",
      level: 3,
      text: "成都要住几晚？",
    },
    {
      id: "faq-1",
      type: "paragraph",
      text: "就城市本身而言，三晚是舒服的答案，大约产生两到两天半的可用时间。交通友好时两晚也能成立。超过三晚，买到的通常是一条四川支线，而不是更多的成都。",
    },
    {
      id: "faq-2-heading",
      type: "heading",
      level: 3,
      text: "应该飞天府还是双流？",
    },
    {
      id: "faq-2",
      type: "paragraph",
      text: "以订到的机票为准。两座机场都在用，2026 年还发生过航线在两场之间迁移，所以旧的接驳方案可能是错的。双流通常离成熟中心城区更近；天府需要预留更大的门到门时间。",
    },
    {
      id: "faq-3-heading",
      type: "heading",
      level: 3,
      text: "三星堆和熊猫基地能同一天吗？",
    },
    {
      id: "faq-3",
      type: "paragraph",
      text: "诚实地说不能。三星堆在另一座城市，需要分时预约，而且那座博物馆值得真实时间；熊猫基地会吃掉一个上午加交通。硬排在同一天，等于两边都没看好。",
    },
    {
      id: "faq-4-heading",
      type: "heading",
      level: 3,
      text: "九寨沟能从成都当日往返吗？",
    },
    {
      id: "faq-4",
      type: "paragraph",
      text: "不能。它是有自己交通链和自己住宿的山地目的地。请把它当作行程中独立的一段，而不是从成都酒店出发的一次外出。",
    },
    {
      id: "faq-5-heading",
      type: "heading",
      level: 3,
      text: "我会用到哪个成都火车站？",
    },
    {
      id: "faq-5",
      type: "paragraph",
      text: "看车票。成都东站承担很多高铁，但南站和西站是独立枢纽；老的成都站正在改扩建、目标 2027 年，现在不能进入任何实际计划。",
    },
    {
      id: "faq-6-heading",
      type: "heading",
      level: 3,
      text: "国际航班前一晚应该住天府还是双流机场附近？",
    },
    {
      id: "faq-6",
      type: "paragraph",
      text: "先从当前行程单读取准确机场和航站楼，再核对值机截止时间、市区酒店出发的完整链条与后备方案。若这条链很脆弱，尤其是早班机、带儿童老人或行李较多时，机场侧住宿更合理；若已核实出发当天的转场，且最后一个成都夜晚仍有价值，就可保留市区酒店。使用上方全国末晚指南的方法，天府与双流不能互相代替。",
    },
    {
      id: "cta-heading",
      type: "heading",
      level: 2,
      text: "把成都的选择放回整条中国路线",
    },
    {
      id: "cta-1",
      type: "paragraph",
      text: "如果现在还只是一串城市，先测试现有晚数到底装得下哪种顺序。如果航班和逐日安排都已经存在，更好的问题是：这份计划有没有保住真正的成都日，并且给每一条四川支线留出它自己的时间。",
    },
    {
      id: "cta-links",
      type: "internal-links",
      title: "两种继续方式",
      items: [
        {
          label: "免费人工规划初查",
          href: "/zh/#planner-contact",
          description: "提交路线与住宿限制，先由人工免费查看；不会预先选择任何付费服务。",
        },
        {
          label: "中国行程点评",
          href: "/zh/china-itinerary-review/",
          description: "把已有的逐日路线交上来，让人帮你找出薄弱环节。",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "官方来源与复核记录",
      items: [
        {
          label: "成都大熊猫繁育研究基地参观信息",
          url: "https://www.panda.org.cn/en/about/introduction/",
          publisher: "成都大熊猫繁育研究基地",
          reviewedAt: "2026-08-17",
        },
        {
          label: "九寨沟官方到达方式与交通",
          url: "https://www.jiuzhai.com/intelligent-service/arrival-mode",
          publisher: "九寨沟风景名胜区",
          reviewedAt: "2026-08-17",
        },
        {
          label: "成都站改扩建报道：主体完成 70% 以上，目标 2027 年投用",
          url: "http://sc.people.com.cn/n2/2026/0617/c379471-41612759.html",
          publisher: "人民网四川频道",
          reviewedAt: "2026-08-17",
        },
        {
          label: "中国铁路 12306：订票前核对确切车站",
          url: "https://www.12306.cn/en/index.html",
          publisher: "中国铁路 12306",
          reviewedAt: "2026-08-17",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
