import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "八达岭有多种公共交通，但它们从北京不同枢纽出发，到达点也不完全相同。先比较酒店到枢纽的首段与回程余量，不要只看最短车上时间。" },
  { id: "answer", type: "callout", title: "线路名称只回答了一半", tone: "decision", body: "酒店去清河或北京北站方便、当天有合适列车时先查高铁；S2市郊铁路目前从南口站始发；877路公交目前从北土城地铁站附近始发。机场线路只有机场确实是起点或终点时才相关，不能拿来当市区捷径。" },
  { id: "matrix-heading", type: "heading", level: 2, text: "四条路线，四种首段" },
  { id: "matrix", type: "table", caption: "按出发日期核对每个完整站名", columns: ["路线", "较好的出发条件", "实际不便", "不要假设"], rows: [
    ["高铁", "清河或北京北站顺路且有合适车次", "预约车次、安检、大站与较长出站系统", "所有车都从同一北京站出发"],
    ["S2市郊铁路", "南口站与当天时刻合适", "独立车站、有限班次与候车", "旧文所写黄土店今天仍是始发站"],
    ["877路公交", "北土城方便且能接受道路波动", "寻找官方站点、排队、拥堵与回程截止", "旧文所写德胜门今天仍是始发站"],
    ["机场直达巴士", "首都机场是真实起点或终点", "日期时刻、航站楼和景区运营日", "永久每日运行或服务大兴机场"],
  ]},
  { id: "names", type: "callout", title: "保存完整名称", tone: "warning", body: "八达岭长城站、S2八达岭站与公路巴士到达点不能当作同一名称。北京端按所选路线分别保存清河或北京北、南口、北土城的中文名，并在出发前核对当天运营。" },
  { id: "clock-heading", type: "heading", level: 2, text: "往返都要计算" },
  { id: "clock", type: "list", ordered: true, items: ["酒店或机场到正确枢纽。", "候车、安检或排队缓冲。", "计划车程与延误风险。", "到达点到所选入口及上坡移动。", "下山、集合与最后一条安全回程。"] },
  { id: "groups", type: "comparison", title: "哪一种实际不便最需要考虑？", columns: [
    { heading: "轻装、灵活", items: ["比较所有当前公共路线", "保留第二种回程", "携带中文名称"] },
    { heading: "家庭或父母", items: ["减少枢纽不确定性", "考虑陡坡与电梯", "不要等最后一班"] },
    { heading: "衔接机场或火车", items: ["只用日期明确的官方线路", "保护行李与值机时间", "避免同日脆弱接驳"] },
  ]},
  { id: "booking-heading", type: "heading", level: 2, text: "把路线变成按日期执行的订票流程" },
  { id: "booking-copy", type: "paragraph", text: "查询自己的出行日期，不要照抄旧博客路线。乘铁路时，付款前同时比较准确的北京出发站、八达岭长城站、去程时间、抵达时间和回程余票。乘S2或877路时，应使用当下运营公告，并把出发地点的中文名称保存好。然后按实际清晨时段计算酒店入口到出发点的路线。一条纸面上很简单的方案，加上首班地铁、安检排队或跨城出租车后，可能就不再占优。" },
  { id: "identity", type: "callout", title: "订票证件必须与旅客一致", tone: "warning", body: "铁路产品需要身份信息时，应按系统接受的方式准确录入护照，并携带同一本证件。若自动闸机无法读取，要给人工协助留时间。其他人的车票截图、翻译后的车站简称或付款收据，都不能替代有效订单与旅行证件。" },
  { id: "wall-heading", type: "heading", level: 2, text: "抵达八达岭只是下一段路线选择的开始" },
  { id: "wall-matrix", type: "table", caption: "确定回程前先设计景区段", columns: ["问题", "要做的决定", "为什么重要"], rows: [
    ["从哪个入口、走哪一段长城？", "确定步行方向和重新集合点", "不同交通抵达点和景区移动不会带来相同起点"],
    ["爬多少？", "按行动最受限的人选择路线，并核对当日提升设施", "交通日已经包含车站步行和排队"],
    ["全组怎么返回？", "保存从城墙到正确铁路站或巴士队列的路径", "去程顺利不代表回程入口一目了然"],
    ["游览后有什么固定安排？", "按最后安全回程设置离开城墙时间，而不是按闭园时间", "晚餐、火车或航班会放大延误后果"],
  ]},
  { id: "day-heading", type: "heading", level: 2, text: "给当天设置止损规则" },
  { id: "day-plan", type: "list", ordered: true, items: ["先确定等待首选去程到什么时间就应停止。", "从当下位置保存一个已核实的备选，而不是一串理论路线。", "设置景区折返时间，保护回程车次。", "若同行者分开，应在攀登前约好有名称的集合点和离开时限。", "除非按真实交通和进站时间仍有余量，不要再拼接另一个偏远北京景点。"] },
  { id: "recovery-heading", type: "heading", level: 2, text: "错枢纽或错过班次" },
  { id: "recovery", type: "table", caption: "继续移动前先确认备选方案", columns: ["问题", "动作"], rows: [
    ["到了错误北京火车站", "查官方退改与当前位置的路线，不凭猜测穿城赶站"],
    ["S2时刻不合适", "从当前位置比较877路与当天高铁余票"],
    ["公交站不清楚", "询问工作人员，并核对完整线路与中文终点"],
    ["回程即将失败", "离开景区，锁定下一班已确认服务并通知酒店或承运方"],
  ]},
  { id: "facts", type: "callout", title: "交通信息核验于2026年8月13日", tone: "neutral", body: "北京公交于2025年3月27日把877路始发站从德胜门迁至北土城；北京市交通委说明S2线自2025年10月25日起从南口站始发。高铁使用另一套铁路车站，首都机场至八达岭线路也按日期运营。出发前再次核对班次、票价与运营日。" },
  { id: "help", type: "callout", title: "需要按酒店核对路线？", tone: "decision", body: "提供日期、北京酒店或机场航站楼、人数、行动需求和晚间固定安排。Homeground可比较完整路线和实用备选方案，但不保证实时余票。" },
  { id: "links", type: "internal-links", title: "继续规划", items: [
    { label: "先选对长城段", href: "/zh/guides/great-wall-section-selector-from-beijing/", description: "在确定这条接驳前，先比较慕田峪、八达岭、金山岭和司马台。" },
    { label: "北京应该选哪个火车站", href: "/zh/guides/which-beijing-railway-station/", description: "识别清河、北京北和其他主要枢纽。" },
    { label: "第一次去北京住哪里", href: "/zh/guides/beijing-where-to-stay-first-trip/", description: "住宿区域会改变首段。" },
    { label: "北京到慕田峪", href: "/zh/guides/beijing-to-mutianyu-great-wall-transfer/", description: "确定去慕田峪后再使用。" },
    { label: "你的行程是否太赶", href: "/zh/guides/is-your-china-itinerary-too-rushed/", description: "保护长距离接驳的一天。" },
  ]},
  { id: "sources", type: "sources", title: "官方来源与图片署名", items: [
    { label: "八达岭公共交通路线", url: "https://english.beijing.gov.cn/latest/news/202406/t20240624_3725018.html", publisher: "北京市政府", reviewedAt: "2026-08-12" },
    { label: "877路始发站调整至北土城", url: "https://www.bjbus.com/home/fun_news_detail.php?uNewsCode=00010196&uNewsType=1", publisher: "北京公交集团", reviewedAt: "2026-08-13" },
    { label: "S2线始发站调整至南口", url: "https://jtw.beijing.gov.cn/sjtl/202111/t20211118_2540164.html", publisher: "北京市交通委员会", reviewedAt: "2026-08-13" },
    { label: "2026首都机场直达服务", url: "https://english.beijing.gov.cn/livinginbeijing/transportation/bus/202602/t20260211_4507827.html", publisher: "北京市政府", reviewedAt: "2026-08-12" },
    { label: "首图：N509FZ拍摄八达岭站，CC BY-SA 4.0，已裁切", url: "https://commons.wikimedia.org/wiki/File:Exterior_of_Badaling_Great_Wall_Railway_Station_(20220109161541).jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" },
    { label: "首图衍生文件许可证：CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-12" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
