import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "只说酒店“靠近地铁”并没有多少参考价值。你还需要知道具体走哪个出入口、步行路线是否好走，以及每天真正会乘坐哪条线路。酒店在地图上可能紧挨着车站，却要绕到不顺路的出口、搬行李走楼梯、横穿宽阔路口，或每天多换一次车。判断位置时，应看从酒店大堂到站台、再到每日目的地的完整动线，而不是预订页面上的一句标签。",
    },
    {
      id: "quick-answer",
      type: "heading",
      level: 2,
      text: "先说结论",
    },
    {
      id: "quick-answer-text",
      type: "paragraph",
      text: "对大多数第一次到一座中国城市的旅客，比较稳妥的标准是：从酒店大堂步行到实际可用的地铁出入口，经核实需要5至10分钟。如果同行有儿童、老人或大件行李，或一天要多次坐地铁，5分钟以内尤其有价值。若酒店对应的是更实用的直达线路、晚上更适合步行的街区，或房间明显更合适，10至15分钟也可以接受。再远一些，就不要继续把它当作“地铁旁酒店”，而应按一段普通的接驳行程来评估。",
    },
    {
      id: "decision-rule",
      type: "callout",
      title: "判断原则",
      body: "先量酒店大门到可用出入口的路，再计算换乘次数。多走几分钟平路去搭乘真正有用的线路，往往比住在不合适的线路旁更省事；地图距离虽短，但要爬楼梯、绕过障碍或走错方向的出入口，反而可能更差。",
      tone: "decision",
    },
    {
      id: "distance-bands",
      type: "heading",
      level: 2,
      text: "用步行时间分档，不要只看“近地铁”",
    },
    {
      id: "distance-table",
      type: "table",
      caption: "Homeground 对酒店大堂至正确地面出入口的规划分档",
      columns: ["核实后的步行时间", "如何看待", "哪些因素会改变结论"],
      rows: [
        ["0—5分钟", "适合每天反复乘坐地铁，确实算近", "大路口、台阶，或出入口位于马路对面，仍会明显影响体验"],
        ["5—10分钟", "通常是实用的城市住宿位置", "带着行李，并按同行中走得最慢者的速度再走一遍"],
        ["10—15分钟", "是一项需要主动接受的取舍，不必直接排除", "只有线路、街区、房间或价格更合适时才值得保留"],
        ["超过15分钟", "按一段接驳行程来评估", "比较短途网约车、公交接驳，或换一家酒店"],
      ],
    },
    {
      id: "distance-note",
      type: "paragraph",
      text: "以上是编辑部用于行程规划的分档，并非官方标准。计时应从酒店大堂开始，而不是从酒店用地边缘开始；终点是你打算使用的地面出入口，不是地图上的车站名称，也不是站台。比较完整行程时，还要加入过马路、安检、进站闸机以及站内步行所需的时间。",
    },
    {
      id: "station-pin",
      type: "heading",
      level: 2,
      text: "地图上的车站定位点，不等于出入口",
    },
    {
      id: "station-pin-table",
      type: "table",
      caption: "把预订页面的宣传语，转化为可以核实的路线",
      columns: ["住宿页面怎么写", "还需要查什么", "为什么重要"],
      rows: [
        ["“距某某站300米”", "从酒店大堂步行到某个明确出入口的当前路线", "距离终点可能是车站中心点，也可能在马路另一侧"],
        ["“地铁就在门口”", "显示具体出入口的街景照片或地图", "最近的出入口可能只有楼梯，也可能位于另一栋建筑内部"],
        ["“附近有两条地铁线”", "结合实际日程，查看会乘哪条线、如何换乘", "两条不顺路的线路，不如一条真正有用的直达线路"],
        ["“去机场方便”", "按抵达或离开的具体时段，规划从酒店门口到航站楼的完整路线", "地铁运营时间、行李以及到航站楼后的最后一段步行，都可能改变结论"],
      ],
    },
    {
      id: "entrance-access",
      type: "heading",
      level: 2,
      text: "先查出入口，再看酒店",
    },
    {
      id: "entrance-evidence",
      type: "paragraph",
      text: "运营方的官方信息说明了为什么必须查到具体出入口。北京京港地铁目前的西单站页面列出多组出入口，并明确标注地面电梯位于J1口。广州地铁的官方无障碍设施指引同样按具体出入口记录地面至站厅层的通行方式，而且不同车站所列出入口并不相同。因此，“这个站有电梯”并不能说明电梯是否靠近酒店，也不能说明它是否位于你真正需要走的路线上。",
    },
    {
      id: "accessible-exit",
      type: "callout",
      title: "无障碍必须覆盖全程",
      body: "使用轮椅、推婴儿车、膝盖不适或携带重行李时，需要把三段路线都核实清楚：地面到站厅层、站厅层到站台层，以及酒店与该地面出入口之间的步行路线。车站某处有一部电梯，并不代表整段路都能无障碍通行。",
      tone: "warning",
    },
    {
      id: "line-quality",
      type: "heading",
      level: 2,
      text: "线路是否有用，比哪条线最近更重要",
    },
    {
      id: "line-table",
      type: "table",
      caption: "根据旅途中会重复走的路线，比较酒店的地铁条件",
      columns: ["地铁条件", "适合什么情况", "容易忽略的代价"],
      rows: [
        ["一条线路可直达大部分计划地点", "停留时间短，而且行程相对集中", "从酒店到地铁可能多走几分钟，但每天都更简单"],
        ["酒店靠近两线换乘站", "每天前往的方向比较分散", "大型换乘站内部可能要走很远"],
        ["车站很近，但去主要景点都要换乘", "只有在换乘足够简单，且房间或街区明显更合适时才值得", "每天反复上下楼、换站台和应对拥挤，负担会累积"],
        ["步行范围内有多个车站", "每个车站都能承担一条真正有用的路线", "“附近车站很多”可能掩盖了没有一个真正靠近酒店大堂"],
      ],
    },
    {
      id: "transfer-rule",
      type: "callout",
      title: "步行和换乘要一起计算",
      body: "不要只按附近有几个车站来比较酒店。请分别计算三段关键行程从酒店大堂到目的地的时间：抵达当天、最满的一天，以及离开当天。",
      tone: "neutral",
    },
    {
      id: "daily-impact",
      type: "heading",
      level: 2,
      text: "把这段步行放到整个住宿期间计算",
    },
    {
      id: "daily-impact-text",
      type: "paragraph",
      text: "单程相差7分钟，一个普通的往返日就会多走14分钟；如果中途回酒店休息，差距还会扩大。住4天时，即使尚未计入站内通道，这些时间加起来也可能接近1小时。当然，为了更安静的房间、更适合夜间活动的街区或一条直达线路，多走这一段仍可能值得。关键是主动做出取舍，而不是把“近地铁”当成简单的是非筛选项。",
    },
    {
      id: "trip-fit",
      type: "heading",
      level: 2,
      text: "同行者和行程不同，判断标准也要调整",
    },
    {
      id: "trip-fit-table",
      type: "table",
      caption: "同一个酒店位置，对不同旅客的合适程度并不相同",
      columns: ["旅行情况", "优先考虑", "通常先放弃"],
      rows: [
        ["第一次来，停留两三晚", "直达线路或方便的换乘，加上晚上仍方便活动的周边", "为了更大的房间住到更远处"],
        ["带婴儿车的家庭或与长辈同行", "到已确认有电梯的出入口，路线短而且平坦", "需要爬楼梯或穿过大路口的热门地段"],
        ["抵达和离开时有大件行李", "出站动线简单、最后一段路宽敞，并有方便的出租车备选方案", "只为节省一点房费而多换一次车"],
        ["住宿时间较长，每天乘地铁次数较少", "街区生活、日常采购和房间舒适度", "只为两分钟的地铁步行距离支付溢价"],
        ["深夜抵达或清早离开", "明确的到店接待安排，以及在具体时段确实运营的交通", "误以为白天地铁方便，就能解决机场或火车站接驳"],
      ],
    },
    {
      id: "last-mile",
      type: "heading",
      level: 2,
      text: "仔细查看最后几百米",
    },
    {
      id: "last-mile-list",
      type: "list",
      items: [
        "过马路：不要只量直线距离，还要数清红绿灯、天桥和地下通道。",
        "垂直动线：确认楼梯、扶梯和具体地面电梯的位置，不要假设所有出入口都一样。",
        "路面和坡度：留意陡坡、破损路面、狭窄小巷，或是否需要从车辆出入口穿行。",
        "天气影响：结合出行季节，判断下雨、炎热或寒冷时这段路是否仍能接受。",
        "夜间便利：查看酒店大堂附近是否有吃饭的地方、便利店，以及安全等候车辆的位置。",
        "建筑开放时间：如果路线需要穿过商场或办公楼，确认你使用时室内通道仍然开放。",
      ],
    },
    {
      id: "luggage-warning",
      type: "callout",
      title: "行李特别大，需要再核实一次",
      body: "不要把一座城市的地铁行李规定直接套用到另一座城市。例如，上海在2026年7月3日更新的指引中公布了具体的尺寸和重量限制。如果携带超大行李箱、运动器材或多件行李，应查看该城市运营方的现行规定，并准备出租车或网约车等路面交通备选方案。",
      tone: "warning",
    },
    {
      id: "shortlist-method",
      type: "heading",
      level: 2,
      text: "按这套方法筛选酒店位置",
    },
    {
      id: "shortlist-steps",
      type: "list",
      ordered: true,
      items: [
        "先确定抵达的火车站或机场、每天最重要的三个目的地，以及离开时的出发点。",
        "保存酒店大堂的准确定位和中文地址；同一建筑群可能不止一个入口。",
        "查询前往某个具体地铁出入口的当前步行路线，不要只导航到车站定位点。",
        "通过运营方官网、官方应用或运营公告，核实线路、时刻、出入口和无障碍设施。",
        "分别规划抵达当天、行程最满的一天和离开当天的门到门路线，并计入换乘和站内步行。",
        "按同行中行动最不灵活者的速度和能力，并带入实际行李情况，重新评估酒店这段步行。",
        "在最后两家酒店之间，比较每天的总体折腾程度、夜间周边、房间是否合适以及价格，而不是只比距离。",
      ],
    },
    {
      id: "red-flags",
      type: "callout",
      title: "遇到这些情况，先别急着预订",
      body: "如果住宿页面只给出车站名称、使用直线距离、不说明酒店大堂入口、依赖室内捷径，或声称“可乘机场地铁”却不写清线路与运营时段，都需要重新核实。",
      tone: "warning",
    },
    {
      id: "before-booking",
      type: "heading",
      level: 2,
      text: "付款前，先回答这八个问题",
    },
    {
      id: "booking-list",
      type: "list",
      items: [
        "我们具体会使用哪个地铁出入口？",
        "从酒店大堂步行到该出入口，目前地图显示要多久？",
        "整段路线是否足够平坦，并能让所有同行者无障碍通行？",
        "我们抵达和返回时，这个出入口或与之相连的建筑是否开放？",
        "三段关键行程分别需要换乘几次？",
        "稍远一点的车站，是否反而有更实用的直达线路？",
        "遇到行李、下雨、炎热、疲惫的孩子或老人时，路线是否仍然可行？",
        "如果地铁方案临时不可用，附近是否有方便的出租车或网约车上车点？",
      ],
    },
    {
      id: "dynamic-check",
      type: "heading",
      level: 2,
      text: "哪些信息需要再次核实",
    },
    {
      id: "dynamic-text",
      type: "paragraph",
      text: "本文所用地铁运营方及市政府官方信息，核查日期为2026年8月11日。地铁线路、出入口、电梯可用情况、换乘关系、运营时段和临时调整公告都可能变化，因此本文不提供一个全国通用的线路数量，也不会把末班车时间写成长期固定事实。筛选酒店时应查询相应城市的运营方信息，并在抵达前不久再次确认。",
    },
    {
      id: "human-help",
      type: "heading",
      level: 2,
      text: "如果两个位置看起来还是差不多",
    },
    {
      id: "human-help-text",
      type: "paragraph",
      text: "可以提供旅行日期、人数、计划前往的城市和每晚的大致预算，由 Homeground 行程顾问协助比较住宿区域与交通是否匹配。尤其是带儿童、与长辈同行，或抵达当天时间很紧时，最后一段路会格外重要。",
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "继续规划",
      items: [
        {
          label: "了解中国酒店怎样才算物有所值",
          href: "/zh/guides/why-are-hotels-in-china-so-cheap/",
          description: "看到低价时，先比较位置、房型、抵达接待安排和最新可核实信息。",
        },
        {
          label: "规划与年长父母同行的中国之旅",
          href: "/zh/guides/china-itinerary-with-older-parents/",
          description: "减少更换酒店的次数，并以行动最不灵活的同行者为基准安排交通。",
        },
        {
          label: "检查你的中国行程是否太赶",
          href: "/zh/guides/is-your-china-itinerary-too-rushed/",
          description: "决定再加一站之前，把转场负担和恢复时间计算进去。",
        },
        { label: "规划适合孩子的路线", href: "/zh/guides/china-itinerary-with-young-children/", description: "从睡眠、饮食、如厕、照顾孩子的负担、酒店稳定性和儿童票规则设计中国亲子路线。" },
        { label: "核验上海24小时公园在夜间是否真的可用", href: "/zh/guides/shanghai-24-hour-parks-reality-check/", description: "要算开放入口、照明动线、设施和最后安全返程，不只看“24小时”标签或邻近地铁站。" },
        { label: "比较桂林到阳朔", href: "/zh/guides/guilin-yangshuo-transport-route/", description: "按车站、机场、酒店、行李、方向和回程，比较桂林与阳朔之间的火车、公路接驳和水路体验。" },
        { label: "选择上海住宿区", href: "/zh/guides/shanghai-where-to-stay-first-trip/", description: "从步行、轨道覆盖、夜间活动、行李和人流取舍比较外滩、人民广场与原法租界片区。" },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "已核查的官方来源",
      items: [
        {
          label: "西单站出入口、设施与时刻表",
          url: "https://www.mtr.bj.cn/en/service/line/station/5d5a18eeb1ea0278b8fffd6d",
          publisher: "北京京港地铁有限公司",
          reviewedAt: "2026-08-11",
        },
        {
          label: "广州地铁车站无障碍设施分布",
          url: "https://www.gz.gov.cn/attachment/7/7792/7792275/10198934.pdf",
          publisher: "广州市人民政府 / 广州地铁",
          reviewedAt: "2026-08-11",
        },
        {
          label: "上海地铁乘坐指南",
          url: "https://english.shanghai.gov.cn/en-Transportation/20231214/c727f5e15eff4b8c9340651dd95f3f7c.html",
          publisher: "上海市人民政府 / 上海地铁",
          reviewedAt: "2026-08-11",
        },
        {
          label: "上海地铁2026年首末班车时刻调整",
          url: "https://www.shanghai.gov.cn/nw17239/20260413/d8e14c16213246eba8fac7c23b2b04af.html",
          publisher: "上海市宝山区人民政府 / 上海申通地铁集团",
          reviewedAt: "2026-08-11",
        },
        {
          label: "上海地铁禁限带物品及超大行李指引，2026年7月3日更新",
          url: "https://english.shanghai.gov.cn/en-FAQs-TravelinShanghai/20240531/c328df3c38054bdcb66160007eb85b4f.html",
          publisher: "上海市人民政府 / 上海地铁",
          reviewedAt: "2026-08-11",
        },
        {
          label: "头图：Kmchang28 拍摄的上海地铁上海火车站站1号口（已裁切；CC BY-SA 4.0）",
          url: "https://commons.wikimedia.org/wiki/File:Exit_1_of_Metro_Shanghai_Railway_Station_in_Shanghai.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-11",
        },
        {
          label: "头图裁切版本适用的 CC BY-SA 4.0 许可",
          url: "https://creativecommons.org/licenses/by-sa/4.0/",
          publisher: "Creative Commons",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
