import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "“Near the metro” is not a useful answer until you know the entrance, the walking route and the line you will actually use. A hotel can sit beside a station marker yet require the wrong exit, stairs, a long road crossing or an inconvenient transfer every day. Judge the complete lobby-to-platform-to-itinerary sequence, not the label on the booking page.",
    },
    {
      id: "quick-answer",
      type: "heading",
      level: 2,
      text: "The short answer",
    },
    {
      id: "quick-answer-text",
      type: "paragraph",
      text: "For most first-time city stays, aim for a verified five-to-ten-minute walk from the hotel lobby to the entrance you can actually use. Under five minutes is especially valuable with children, older travellers, heavy luggage or several metro trips a day. Ten to fifteen minutes can still be sensible when the hotel gives you a better direct line, a more walkable evening area or a much better room. Beyond that, stop calling it a metro hotel and test the location as a normal last-mile commute.",
    },
    {
      id: "decision-rule",
      type: "callout",
      title: "Decision rule",
      body: "Measure door to usable entrance, then count transfers. A slightly longer flat walk to the right line often beats a hotel beside the wrong line; a short map distance with stairs, barriers or the wrong exit can be the worse choice.",
      tone: "decision",
    },
    {
      id: "distance-bands",
      type: "heading",
      level: 2,
      text: "Use walking-time bands, not the word “near”",
    },
    {
      id: "distance-table",
      type: "table",
      caption: "Homeground’s planning bands for the hotel lobby to the correct street entrance",
      columns: ["Verified walk", "How to treat it", "What can change the answer"],
      rows: [
        ["0–5 minutes", "Genuinely close for repeated daily use", "A large junction, steps or an entrance on the opposite side can still matter"],
        ["5–10 minutes", "Normally a practical city base", "Test the route with luggage and the slowest traveller"],
        ["10–15 minutes", "A deliberate trade-off, not an automatic rejection", "Keep it only for a better line, neighbourhood, room or price"],
        ["More than 15 minutes", "Treat it as a last-mile journey", "Compare a short ride-hail trip, bus connection or a different hotel"],
      ],
    },
    {
      id: "distance-note",
      type: "paragraph",
      text: "These are editorial planning bands, not official standards. Start the clock at the hotel lobby—not the edge of the property—and stop at the street entrance you plan to use—not the station name or the platform. Add time for crossings, security, ticket gates and the internal station walk when comparing the full journey.",
    },
    {
      id: "station-pin",
      type: "heading",
      level: 2,
      text: "A station pin is not an entrance",
    },
    {
      id: "station-pin-table",
      type: "table",
      caption: "Translate a booking-page claim into a route you can verify",
      columns: ["What the listing says", "What you still need", "Why it matters"],
      rows: [
        ["“300 m from X Station”", "A current walking route from the lobby to a named entrance", "The distance may point to the station centre or a different side of the road"],
        ["“Metro at the doorstep”", "A street-level photograph or map showing the exact entrance", "The nearest access may be stairs only or inside another building"],
        ["“Two metro lines nearby”", "The line and transfer sequence for your actual days", "Two unhelpful lines do not beat one direct useful line"],
        ["“Easy airport access”", "A door-to-terminal plan at your arrival or departure time", "Metro operating hours, luggage and the final terminal walk can change the result"],
      ],
    },
    {
      id: "entrance-access",
      type: "heading",
      level: 2,
      text: "Check the exit before you check the hotel",
    },
    {
      id: "entrance-evidence",
      type: "paragraph",
      text: "Official operator information shows why exit-level checking matters. Beijing MTR’s current Xidan station page lists several entrance groups but identifies the street elevator at Entrance J1. Guangzhou Metro’s official accessibility guide likewise records ground-to-concourse access by specific exit, and the listed exit varies by station. “The station has an elevator” therefore does not tell you whether the elevator is near your hotel or on the route you need.",
    },
    {
      id: "accessible-exit",
      type: "callout",
      title: "Step-free is an end-to-end route",
      body: "For a wheelchair, stroller, painful knees or heavy bags, verify all three links: street to concourse, concourse to platform, and the walk between the hotel and that street entrance. An elevator somewhere in the station is not enough.",
      tone: "warning",
    },
    {
      id: "line-quality",
      type: "heading",
      level: 2,
      text: "The useful line matters more than the nearest line",
    },
    {
      id: "line-table",
      type: "table",
      caption: "Compare hotel access against the journeys you will repeat",
      columns: ["Metro pattern", "When it works", "Hidden cost"],
      rows: [
        ["One direct line to most planned stops", "Short stays with a concentrated itinerary", "The hotel walk may be slightly longer, but each day is simpler"],
        ["A two-line interchange close to the hotel", "Mixed itineraries in different directions", "Large interchange stations can add a long internal walk"],
        ["Very close station with a transfer for every major sight", "Only when transfers are easy and the room or area clearly compensates", "Repeated stairs, platforms and crowding accumulate"],
        ["Several stations within walking distance", "When each serves a genuinely useful route", "A list of nearby stations can disguise that none is close to the lobby"],
      ],
    },
    {
      id: "transfer-rule",
      type: "callout",
      title: "Count walking plus transfers",
      body: "Do not compare hotels by station count alone. Compare lobby-to-destination time for the three journeys that anchor the stay: arrival, the busiest sightseeing day and departure.",
      tone: "neutral",
    },
    {
      id: "daily-impact",
      type: "heading",
      level: 2,
      text: "Price the walk across the whole stay",
    },
    {
      id: "daily-impact-text",
      type: "paragraph",
      text: "A seven-minute difference each way becomes fourteen minutes on a simple out-and-back day and more when you return for a rest. Over four days, that can approach an hour before counting station corridors. The extra walk may still be worth it for a quieter room, better evening streets or a direct line. Make that exchange consciously instead of treating “near metro” as a yes-or-no filter.",
    },
    {
      id: "trip-fit",
      type: "heading",
      level: 2,
      text: "Change the standard for the people and the trip",
    },
    {
      id: "trip-fit-table",
      type: "table",
      caption: "The same hotel location fits different travellers differently",
      columns: ["Trip pattern", "Prioritise", "Usually sacrifice first"],
      rows: [
        ["First visit, two or three nights", "A direct line or easy interchange plus a usable evening area", "A larger room farther out"],
        ["Family with a stroller or older relatives", "A short, flat route to a confirmed lift entrance", "A fashionable address with stairs or a long crossing"],
        ["Large luggage on arrival and departure", "A simple station exit, wide last mile and practical taxi fallback", "One extra transfer just to save a small room-rate difference"],
        ["Longer stay with fewer daily rides", "Neighbourhood life, groceries and room comfort", "Paying a premium for a two-minute metro walk"],
        ["Late arrival or early departure", "A staffed arrival plan and transport that operates at the exact hour", "Assuming daytime metro convenience solves the airport or railway transfer"],
      ],
    },
    {
      id: "last-mile",
      type: "heading",
      level: 2,
      text: "Inspect the last few hundred metres",
    },
    {
      id: "last-mile-list",
      type: "list",
      items: [
        "Road crossings: count signals, overpasses and underpasses rather than measuring a straight line.",
        "Vertical access: identify stairs, escalators and the exact street elevator; do not assume every exit is equivalent.",
        "Surface and slope: look for steep sections, broken paving, narrow lanes or a route through a vehicle entrance.",
        "Weather exposure: decide whether the walk is tolerable in the season you will visit with rain, heat or cold.",
        "Evening usefulness: check whether food, a convenience store and a safe place to wait for a ride are available near the lobby.",
        "Building access: confirm whether a route through a mall or office complex remains open at the times you will use it.",
      ],
    },
    {
      id: "luggage-warning",
      type: "callout",
      title: "Unusually large luggage needs a second check",
      body: "Do not copy one city’s metro baggage rule to another. Shanghai, for example, publishes specific size and weight limits in guidance updated on 3 July 2026. If you carry very large cases, sports equipment or several bags, check the current operator rule for that city and keep a road-transfer fallback.",
      tone: "warning",
    },
    {
      id: "shortlist-method",
      type: "heading",
      level: 2,
      text: "Run a clean hotel-location test",
    },
    {
      id: "shortlist-steps",
      type: "list",
      ordered: true,
      items: [
        "Fix the arrival station or airport, the three most important daily stops and the departure point.",
        "Save the hotel’s exact lobby pin and Chinese address; a complex can have more than one entrance.",
        "Find the current pedestrian route to a named metro entrance, not only to the station marker.",
        "Check the official operator page, app or service notice for the line, timetable, entrance and accessibility details.",
        "Route the arrival, busiest day and departure door to door, including transfers and internal station walking.",
        "Repeat the hotel walk using the pace and mobility of the least flexible traveller and the luggage you will carry.",
        "Compare the final two hotels on total daily friction, evening surroundings, room fit and price—not distance alone.",
      ],
    },
    {
      id: "red-flags",
      type: "callout",
      title: "Pause before booking",
      body: "Recheck any property that gives only a station name, quotes straight-line distance, hides the lobby entrance, relies on an indoor shortcut, or promises “airport metro access” without naming the line and operating window.",
      tone: "warning",
    },
    {
      id: "before-booking",
      type: "heading",
      level: 2,
      text: "Before paying, answer these eight questions",
    },
    {
      id: "booking-list",
      type: "list",
      items: [
        "Which exact metro entrance will we use?",
        "What is the current mapped walk from the lobby to that entrance?",
        "Is the route flat and step-free enough for everyone in the group?",
        "Does the entrance or connected building operate when we arrive and return?",
        "How many transfers do our three anchor journeys require?",
        "Would a slightly farther station provide a more useful direct line?",
        "What happens with luggage, rain, heat, tired children or an older traveller?",
        "Is there a taxi or ride-hail pickup point if the metro plan fails?",
      ],
    },
    {
      id: "dynamic-check",
      type: "heading",
      level: 2,
      text: "What must be checked again",
    },
    {
      id: "dynamic-text",
      type: "paragraph",
      text: "Official metro and municipal sources were reviewed on 11 August 2026. Lines, entrances, elevator availability, station connections, operating windows and disruption notices can change. This guide therefore does not freeze a nationwide line count or last-train time. Recheck the relevant city operator when shortlisting and again shortly before arrival.",
    },
    {
      id: "human-help",
      type: "heading",
      level: 2,
      text: "If two locations still look equal",
    },
    {
      id: "human-help-text",
      type: "paragraph",
      text: "Share your travel dates, number of travellers, planned cities and rough nightly budget. A Homeground planner can help compare the areas and transport fit, especially when children, older travellers or a tight arrival day make the last mile important.",
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Continue planning",
      items: [
        {
          label: "Understand what makes a China hotel good value",
          href: "/guides/why-are-hotels-in-china-so-cheap/",
          description: "Compare location, room type, arrival handling and current evidence before accepting a low rate.",
        },
        {
          label: "Plan China with older parents",
          href: "/guides/china-itinerary-with-older-parents/",
          description: "Reduce hotel changes and build transport around the least flexible traveller.",
        },
        {
          label: "Check whether your China itinerary is too rushed",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Count transfer friction and recovery time before adding another stop.",
        },
        { label: "Plan a child-compatible route", href: "/guides/china-itinerary-with-young-children/", description: "Design a China route for young children by sleep, food, toilets, carrying load, hotel stability and current child-ticket rules." },
        { label: "Check whether a 24-hour Shanghai park is usable after dark", href: "/guides/shanghai-24-hour-parks-reality-check/", description: "Count the open gate, lit route, facilities and last safe transport back—not just the park label or nearby station." },
        { label: "Compare Guilin to Yangshuo", href: "/guides/guilin-yangshuo-transport-route/", description: "Compare rail, road transfer and river travel between Guilin and Yangshuo by station, airport, hotel, luggage, direction and return plan." },
        { label: "Choose a Shanghai base", href: "/guides/shanghai-where-to-stay-first-trip/", description: "Compare the Bund, People’s Square and the former French Concession by walking, metro reach, evenings, luggage and crowd trade-offs." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        {
          label: "Xidan station entrances, facilities and timetable",
          url: "https://www.mtr.bj.cn/en/service/line/station/5d5a18eeb1ea0278b8fffd6d",
          publisher: "Beijing MTR Corporation",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Distribution of accessible facilities across Guangzhou Metro stations",
          url: "https://www.gz.gov.cn/attachment/7/7792/7792275/10198934.pdf",
          publisher: "Guangzhou Municipal Government / Guangzhou Metro",
          reviewedAt: "2026-08-11",
        },
        {
          label: "How to take the metro in Shanghai",
          url: "https://english.shanghai.gov.cn/en-Transportation/20231214/c727f5e15eff4b8c9340651dd95f3f7c.html",
          publisher: "Shanghai Municipal Government / Shanghai Metro",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Shanghai Metro first- and last-train timetable adjustment announced in April 2026",
          url: "https://www.shanghai.gov.cn/nw17239/20260413/d8e14c16213246eba8fac7c23b2b04af.html",
          publisher: "Baoshan District People’s Government / Shanghai Shentong Metro Group",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Shanghai Metro restricted-item and oversized-luggage guidance, updated 3 July 2026",
          url: "https://english.shanghai.gov.cn/en-FAQs-TravelinShanghai/20240531/c328df3c38054bdcb66160007eb85b4f.html",
          publisher: "Shanghai Municipal Government / Shanghai Metro",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Hero photograph: Shanghai Railway Station metro entrance 1 by Kmchang28 (cropped; CC BY-SA 4.0)",
          url: "https://commons.wikimedia.org/wiki/File:Exit_1_of_Metro_Shanghai_Railway_Station_in_Shanghai.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-11",
        },
        {
          label: "CC BY-SA 4.0 licence for the cropped hero photograph",
          url: "https://creativecommons.org/licenses/by-sa/4.0/",
          publisher: "Creative Commons",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
