import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "For almost every traveller, the answer between Xi'an and Chengdu is the high-speed train, in either direction, and the reason is not the headline journey time. It is that rail puts you inside a city on both ends, while the flight adds two long airport access legs, a check-in cutoff and a terminal you can get wrong. Fly only when the leg before or after the trip is itself a flight, when your dates are inside a rail crunch, or when your ticket already lands you at the airport side of either city." },

  { id: "answer", type: "callout", title: "Decide the doors first, then the mode", tone: "decision", body: "Write down four addresses: where you sleep in Xi'an, where you sleep in Chengdu, what happens immediately before this leg, and what happens immediately after it. Then search 12306 for your exact date across the Xi'an and Chengdu stations that actually appear for that date, and price the flight only as a complete door-to-door chain including the airport access leg at both ends. Rail wins on most of these chains. Air wins on a narrow set, and this guide names them rather than pretending the choice is symmetrical." },

  { id: "stations-heading", type: "heading", level: 2, text: "Two cities, eight ticketable stations, four airport doors" },
  { id: "stations-copy", type: "paragraph", text: "The first mistake is treating \"Xi'an\" and \"Chengdu\" as single points. China Railway's own station dictionary, the file 12306 uses to resolve what you type into the search box, lists four separately ticketable stations in each city. A ticket that says Chengdu is not the same object as a ticket that says Chengdu East, and a taxi driver reading a screenshot cannot repair the difference. The Xi'an–Chengdu high-speed railway opened on 6 December 2017 running between Xi'an North and Chengdu East, and that pairing is still the backbone of the corridor, but it is not the only pairing 12306 will sell you on a given date." },
  { id: "stations-table", type: "table", caption: "Read the full station name on the ticket, in Chinese, before you order a car (station list checked against China Railway's 12306 station dictionary, 22 August 2026)", columns: ["Ticket may say", "Chinese name", "12306 telegraph code", "What it means for you"], rows: [
    ["Xi'an North", "西安北", "EAY", "The main high-speed station and the usual Chengdu departure; also the Metro Line 14 interchange toward the airport"],
    ["Xi'an", "西安", "XAY", "The older central station near the city wall; a different building in a different district"],
    ["Xi'an East", "西安东", "XDY", "A newer station identity in the dictionary; confirm on 12306 whether it sells anything on your date"],
    ["Xi'an West", "西安西", "EGY", "A separate western station; easy to confuse with Xi'an on a rushed booking"],
    ["Chengdu East", "成都东", "ICW", "The main high-speed arrival for this corridor"],
    ["Chengdu South", "成都南", "CNW", "The station Metro Line 18 links directly to Tianfu airport"],
    ["Chengdu", "成都", "CDW", "The central station many travellers assume is \"the\" Chengdu station"],
    ["Chengdu West", "成都西", "CMW", "A separate western station with its own services"],
  ]},
  { id: "stations-warning", type: "callout", title: "The word Chengdu on a search result is not a station check", tone: "warning", body: "Search your date on 12306 before you fix a hotel or a car. A station that appears in the dictionary is not proof that it sells your train on your day; conversely, the train you want may only run from a station you were not considering. Save the train number, both full station names and the departure time from the confirmed order, not from a screenshot of a search." },

  { id: "doors-heading", type: "heading", level: 2, text: "Count the whole chain, not the middle of it" },
  { id: "doors-copy", type: "paragraph", text: "A rail-versus-air comparison that puts a train time next to a flight time is comparing the two shortest segments of two very different chains. The honest comparison counts every handoff, because every handoff is a place where the day can go wrong. Write the chain out for both options before you decide anything." },
  { id: "doors-list", type: "list", ordered: true, items: [
    "Leaving your accommodation, with luggage, at a real hour rather than an optimistic one.",
    "Getting to the correct station entrance or the correct airport terminal — not the airport, the terminal.",
    "Security screening, which China Railway states applies to all passengers and everything they carry, plus any queue at ID verification.",
    "For flights, the check-in and baggage cutoff, which is set by the airline and not by you.",
    "The booked train or flight itself.",
    "Arrival processing: walking a very large concourse, waiting for checked bags, finding the correct exit.",
    "The urban last mile to your exact address, including whether the metro is still running when you land.",
  ]},
  { id: "doors-para2", type: "paragraph", text: "Rail collapses steps two, three, four and six. You walk into a city-centre or near-centre station, you clear one security line, you board with the passport you booked with, and you walk out into the same city you were travelling to. Air keeps all seven and stretches two of them across the metropolitan area. That structural difference, not a stopwatch, is why the train is the default answer here in both directions." },

  { id: "matrix-heading", type: "heading", level: 2, text: "Let your bed and your next move choose the hub" },
  { id: "matrix-copy", type: "paragraph", text: "Once you accept that the chain decides the day, hub choice stops being a matter of preference. It follows from two things you already know: where you are sleeping, and what the leg after this one is. Use the table as a starting position, then confirm each cell on 12306 and on the operator pages for your date." },
  { id: "matrix-table", type: "table", caption: "Start from the accommodation and the onward leg, then test the pairing", columns: ["Your situation", "Check first", "Why", "What can undo it"], rows: [
    ["Staying inside or near the Xi'an city wall, going to central Chengdu", "Xi'an North to Chengdu East", "One metro ride to a purpose-built high-speed station, then a central Chengdu arrival", "A very early departure can precede the first metro; confirm the first train on your line"],
    ["Staying near Xi'an's airport, or arriving on a flight the same day", "Metro Line 14 from the airport to Xi'an North, then rail", "Line 14 was through-linked with the airport intercity railway in 2021 and connects the airport with Xi'an North directly", "A late flight can land after the last Line 14 service; check the last train before you plan it"],
    ["Chengdu leg is followed by an international flight", "Rail to Chengdu, then Metro Line 18 from Chengdu South to Tianfu", "International passenger flights were consolidated at Tianfu in March 2023; Shuangliu is a different airport in a different direction", "Booking a Chengdu hotel that is convenient for Shuangliu and then flying from Tianfu"],
    ["Chengdu leg is followed by a domestic flight", "Confirm which of the two Chengdu airports your flight actually uses", "Both airports are run by the same operator and both handle domestic traffic", "Assuming \"Chengdu airport\" is one place; the two are not adjacent"],
    ["Heavy or awkward luggage, or a group", "Rail, and the station with the shortest last mile at the busier end", "Rail luggage limits are generous and there is no checked-bag wait", "Oversized items still have a stated dimensional limit on EMU trains"],
    ["Onward from Chengdu to a mountain or valley destination the next morning", "Chengdu East or Chengdu South, whichever your next ticket uses", "A second early start from the wrong side of Chengdu costs more than the train saved", "Choosing the arrival station before you have booked the onward leg"],
  ]},

  { id: "flight-heading", type: "heading", level: 2, text: "The cases where flying is genuinely the better answer" },
  { id: "flight-copy", type: "paragraph", text: "Saying rail is the default is not the same as saying air is never right. There is a small set of situations where the flight protects the wider trip, and they share a common shape: you were already going to be at an airport, or the rail option cannot be made to fit the day at all." },
  { id: "flight-comparison", type: "comparison", title: "Three shapes where the flight can win", columns: [
    { heading: "You are already airside", items: ["An inbound international arrival at Xi'an or Chengdu the same day", "You would otherwise pay the airport access leg twice", "Still keep the connection loose and on separate, deliberate margins"] },
    { heading: "Rail cannot fit the date", items: ["Your dates fall in a national holiday crunch and rail inventory has gone", "The only remaining rail options force an overnight you did not plan", "Confirm on 12306 before you conclude this, not from a third-party screen"] },
    { heading: "The next leg is a flight anyway", items: ["A same-region onward flight from Tianfu or from Xi'an", "Arriving at the airport rather than the city can remove a whole crossing", "Only if the airports actually match — check the terminal, not the city"] },
  ]},
  { id: "flight-warning", type: "callout", title: "Do not build a tight self-transfer out of this", tone: "warning", body: "If you choose air because a flight sits on either side of this leg, prefer one through-ticket or another itinerary whose connections are protected by the carrier. Buy separate tickets only when that cannot reasonably be avoided, and then treat the connection as an unprotected self-transfer: leave a conservative margin, confirm whether checked bags must be collected and dropped again, and be prepared to fund the recovery yourself. On separate tickets, a missed onward flight after an earlier delay may be yours to solve, and it is a far more expensive failure than a missed train, which can often be re-ticketed on the same day." },

  { id: "airports-heading", type: "heading", level: 2, text: "What the two airport systems actually demand of you" },
  { id: "airports-copy1", type: "paragraph", text: "The Xi'an end is a single airport that has grown a new front door. Xi'an Xianyang International Airport's T5 terminal opened on 20 February 2025, with a main building and six piers over four levels: check-in and international departures on level three, mixed domestic arrivals and departures on level two, baggage handling and arrivals on level one. Two of the piers are convertible between domestic and international use and the rest were domestic at opening. The practical consequence for a visitor is simple and easy to get wrong: the airport now has terminals that are far enough apart to have separate metro stations. Metro Line 14 serves T1, T2 and T3 at the station named Airport West, and serves T5 at the station named Airport." },
  { id: "airports-copy2", type: "paragraph", text: "The Chengdu end is the opposite shape: one operator, two genuinely separate airports. Tianfu International Airport and Shuangliu International Airport are both run by the same group, and since 26 March 2023 international passenger flights that used to operate from Shuangliu have operated from Tianfu. If your Chengdu leg is followed by a long-haul departure, that single fact reorganises your entire Chengdu stay, because the two airports are connected to the city — and to each other — by different lines. The operator's own inter-airport guide points travellers to Metro Line 19 and to Airport Shuttle Line 5 between the two." },
  { id: "airports-callout", type: "callout", title: "If you arrive at the wrong terminal in Xi'an", tone: "neutral", body: "Xi'an Xianyang's published guidance sets out an explicit recovery path rather than leaving you to improvise. Information counters inside door 533 at T5, door 323 at T3 and door 222 at T2 operate assembly points for misdirected passengers with a free walk-up shuttle between terminals. Separately, within Line 14's daily operating hours, passengers transferring between the Airport West (T1, T2, T3) and Airport (T5) stations — including those who simply got off at the wrong one — can show their flight information at the station ticket service centre and travel between those two stations free of charge. Note the check-in cutoff that makes this urgent: the guidance states that domestic flights of China Eastern, Shanghai Airlines and China United stop check-in and baggage drop 40 minutes before scheduled departure." },

  { id: "luggage-heading", type: "heading", level: 2, text: "Luggage quietly decides more of this than fares do" },
  { id: "luggage-copy", type: "paragraph", text: "Travellers usually compare fares and journey times and then discover that the bags decided the day. The two systems treat luggage on fundamentally different terms, and the difference shows up as time, not money. On the train you carry your own bags through one security line and off at the other end; there is no drop-off deadline and no carousel. On the flight you meet an airline cutoff before you fly and a baggage hall after you land, and both sit inside the part of the chain you cannot compress." },
  { id: "luggage-table", type: "table", caption: "China Railway's stated free cabin-luggage limits, as published in 12306's English passenger FAQ (checked 22 August 2026)", columns: ["Rule", "What 12306 states"], rows: [
    ["Free weight, ordinary adult passenger", "20 kg"],
    ["Free weight, children including those travelling free", "10 kg"],
    ["Free weight, diplomats", "35 kg"],
    ["Maximum dimensions per item, conventional trains", "160 cm total, or 200 cm for rod-shaped items"],
    ["Maximum dimensions per item, EMU (high-speed) trains", "130 cm"],
    ["Maximum weight per individual item", "20 kg"],
    ["Folding wheelchairs used by disabled passengers", "Not counted within the above"],
  ]},
  { id: "luggage-copy2", type: "paragraph", text: "Read the EMU line carefully if you are carrying a large hard case, a tripod, a musical instrument or sports equipment: the dimensional limit on high-speed services is stated more tightly than on conventional trains. This is one of the rare places where the flight can genuinely be the simpler option for a specific object, and it is worth checking against the actual dimensions of what you are carrying rather than assuming." },

  { id: "example-heading", type: "heading", level: 2, text: "Example: the same trip, decided twice" },
  { id: "example-copy", type: "paragraph", text: "Example. Two travellers each have four nights in Xi'an and then five in Chengdu, and each has one large case. The first is staying near the Bell Tower and flies home from Chengdu on a long-haul departure. Reading the chain, she books rail from Xi'an North to a Chengdu station, then moves her final Chengdu night to somewhere with a clean run to Chengdu South, because Metro Line 18 links Chengdu South to Tianfu, and Tianfu is where her international flight departs. The train was never the interesting decision; the airport consolidation was." },
  { id: "example-copy2", type: "paragraph", text: "Example. The second traveller lands at Xi'an Xianyang on an inbound international flight in the early afternoon, and is going straight on to Chengdu without stopping in Xi'an at all. For him the airport access leg is already paid, so he compares a Xi'an flight against Metro Line 14 to Xi'an North plus a train. He checks the last Line 14 service and the rail options for that exact date, and finds the rail chain still works with margin — so he takes it, because it ends in the city rather than at a second airport with another access leg attached. Both travellers were right, and they were right for opposite reasons: the decision belongs to the chain, not to the mode." },

  { id: "recovery-heading", type: "heading", level: 2, text: "When the plan fails, stop and read the rule" },
  { id: "recovery-copy", type: "paragraph", text: "Most bad outcomes on this corridor come from improvising at speed. The rules that govern your recovery are published in advance, and two of them change what you should do at the moment things go wrong. First, ticket endorsement can change the date, the train number or the seat, but 12306 states that the departure and arrival stations cannot be changed except for stations in the same city — which is exactly the case here, since Xi'an's four stations share a city and so do Chengdu's. Second, changing your destination station is a separate service that must be requested at least 48 hours before the original departure, so it is not an option once you are already late." },
  { id: "recovery-table", type: "table", caption: "What to do first, and what the published rule allows", columns: ["What went wrong", "What to do", "The rule that governs it"], rows: [
    ["You are at the wrong Xi'an or Chengdu station", "Check endorsement to a later train before racing across the city", "Endorsement is available where seats exist; same-city station changes are the exception 12306 permits"],
    ["Your train has gone and you are still at the station", "Go to the station's designated counter rather than trying to fix it on a phone in a queue", "Refunds at the counter must be processed before departure; special-case handling after departure needs station approval"],
    ["You want to abandon the leg entirely", "Decide quickly, because the fee tiers step up sharply", "No fee at 8 days or more; 5% inside 8 days but over 48 hours; 10% between 24 and 48 hours; 20% inside 24 hours, minimum RMB 2"],
    ["You are at the wrong Xi'an terminal", "Go to the assembly point inside door 533, 323 or 222 and ask for the free inter-terminal shuttle", "Published in the airport's own T5 travel guidance"],
    ["You got off Line 14 at the wrong airport station", "Show your flight information at the ticket service centre and ride between Airport West and Airport free", "Published in the same guidance, within Line 14 operating hours"],
    ["You cannot book at all late at night", "Wait for the sales window rather than assuming inventory is gone", "12306 sells and endorses tickets from 05:00 to 01:00 the next day, and to 23:30 on Tuesdays; queries and refunds run 24 hours"],
    ["You lost the passport you booked with", "Do not go to the gate; go to the station and follow the replacement procedure", "12306 publishes a specific lost-document procedure including a replacement ticket and a later refund window"],
  ]},

  { id: "facts", type: "callout", title: "Operational facts checked 22 August 2026", tone: "neutral", body: "Station identities are taken from China Railway's live 12306 station dictionary on the date shown; station lists change when new lines open, so re-check before you travel. Xi'an Xianyang T5 opened 20 February 2025 and the Metro Line 14 Airport (T5) station opened 18 February 2025; first and last train times, bus routes and the free inter-terminal arrangement are as published in that guidance and are subject to change. The Shuangliu-to-Tianfu consolidation of international passenger flights dates from 26 March 2023; terminal and airport assignments for individual flights, including Hong Kong, Macao and Taiwan services, have been adjusted since and must be read from your own booking. No fare, seat availability or journey time in this guide should be treated as current — check 12306 and the airline for your date." },

  { id: "help", type: "callout", title: "Want the whole chain checked against both addresses?", tone: "decision", body: "Send your dates, the Xi'an address, the Chengdu address, what happens immediately before and after this leg, the number of people and the luggage. Homeground can walk the door-to-door chain with you and say where it breaks. Live rail inventory stays with 12306 and live flight status stays with the airline." },

  { id: "links", type: "internal-links", title: "Continue planning", items: [
    { label: "Beijing, Xi'an and Chengdu in what order?", href: "/guides/beijing-xian-chengdu-route-order/", description: "Settle the city order before you buy this leg." },
    { label: "Where to stay in Xi'an: city wall or Dayanta", href: "/guides/xian-where-to-stay-city-wall-or-dayanta/", description: "The Xi'an address that decides which station is easy." },
    { label: "China high-speed train first-time guide", href: "/guides/china-high-speed-train-first-time-guide/", description: "Booking, boarding and station procedure once the pairing is chosen." },
    { label: "Why China's high-speed stations are so far out", href: "/guides/why-china-high-speed-stations-are-far-away/", description: "Why the last mile is the part that surprises people." },
    { label: "Chengdu to Jiuzhaigou transport", href: "/guides/chengdu-jiuzhaigou-transport-route/", description: "If the leg after Chengdu is a mountain route, decide it before you pick an arrival station." },
    { label: "Separate flight tickets and self-transfer risk", href: "/guides/china-separate-flight-tickets-self-transfer-risk/", description: "Read this before building a same-day air chain around this leg." },
    { label: "Power bank rules on flights and trains", href: "/guides/china-power-bank-rules-flights-trains/", description: "One of the few rules that differs by mode and can stop you at security." },
  ]},

  { id: "sources", type: "sources", title: "Official sources and image credit", items: [
    { label: "12306 station dictionary used by the official booking site", url: "https://kyfw.12306.cn/otn/resources/js/framework/station_name.js", publisher: "China Railway 12306", reviewedAt: "2026-08-22" },
    { label: "Passenger FAQ: real-name ticketing, endorsement, refunds, luggage and security", url: "https://www.12306.cn/en/faq.html", publisher: "China Railway 12306", reviewedAt: "2026-08-22" },
    { label: "Official railway ticket channel", url: "https://www.12306.cn/en/index.html", publisher: "China Railway 12306", reviewedAt: "2026-08-22" },
    { label: "Detailed travel guidance for Xi'an Xianyang International Airport T5", url: "http://www.xixianxinqu.gov.cn/xwzx/tzgg/1892481399452139521.html", publisher: "Xixian New Area Development and Construction Administrative Committee", reviewedAt: "2026-08-22" },
    { label: "Xi'an Xianyang International Airport T5 enters service", url: "https://www.shaanxi.gov.cn/xw/tpxw/202502/t20250220_3445381_wap.html", publisher: "Shaanxi Provincial People's Government", reviewedAt: "2026-08-22" },
    { label: "Xi'an Metro Line 14 opens and is through-linked with the airport intercity railway", url: "http://www.shaanxi.gov.cn/xw/ldx/ds/202106/t20210629_2181120.html", publisher: "Shaanxi Provincial People's Government", reviewedAt: "2026-08-22" },
    { label: "Chengdu Tianfu International Airport becomes the international gateway", url: "http://xn.caac.gov.cn/XN_XXGK/XN_YSSC/202303/t20230328_217747.html", publisher: "CAAC Southwest Regional Administration", reviewedAt: "2026-08-22" },
    { label: "Shuangliu-Tianfu inter-airport connection guide", url: "https://www.cdairport.com/news_detail.aspx?t=60&cid=2507", publisher: "Chengdu Airport (Sichuan Province Airport Group)", reviewedAt: "2026-08-22" },
    { label: "Metro Line 18 direct services between Chengdu South Railway Station and Tianfu Airport", url: "https://www.sc.gov.cn/10462/10464/10465/10595/2023/5/30/58a406950eef4ab58e425282275b50ee.shtml", publisher: "Sichuan Provincial People's Government", reviewedAt: "2026-08-22" },
    { label: "Xi'an-Chengdu high-speed railway opening and route", url: "https://www.sc.gov.cn/10462/12771/2017/12/4/10439830.shtml", publisher: "Sichuan Provincial People's Government", reviewedAt: "2026-08-22" },
    { label: "Hero: Station Hall of Xi'an North Railway Station by YikyuenG, CC BY 4.0; cropped and converted to WebP", url: "https://commons.wikimedia.org/wiki/File:Station_Hall_of_Xi%27an_North_Railway_Station,_Xi%27an,_Shaanxi.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" },
    { label: "Hero derivative licence: CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-22" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
