import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Longji is not a single viewpoint outside Guilin. It is a mountain landscape spread across several terrace and village areas, with a road approach, an entrance process and a final uphill leg before the walking even begins. That is why the useful question is not simply whether Longji can be done in a day. It is whether your particular day still leaves enough time and energy to experience one part of it well." },
  { id: "answer", type: "callout", title: "The short answer", tone: "decision", body: "Choose a day trip when you are sleeping in Guilin, can leave early, will visit one terrace area, and have no fixed train or flight that evening. Stay one night when early or late light matters, cloud recovery would save the visit, you walk slowly, or Longji can sit naturally between two route segments. From Yangshuo, calculate the complete door-to-door day before calling it a day trip; the extra road dependency makes a rushed return much less forgiving." },
  { id: "decision-heading", type: "heading", level: 2, text: "Make the duration decision before choosing a village" },
  { id: "decision-matrix", type: "table", caption: "Longji trip-shape decision", columns: ["Your situation", "Better default", "Why", "What would change the answer"], rows: [
    ["Guilin hotel, one free day, light luggage", "Day trip", "One clearly chosen area can make a complete visit without another hotel move.", "Poor forecast, slow walking or a late start makes an overnight more useful."],
    ["Photography or landscape is a major reason for the trip", "One night", "You gain a second weather window and can see the landscape outside the middle-of-day rush.", "A poor mobility match or an awkward hotel last mile can outweigh the light advantage."],
    ["Starting and ending in Yangshuo", "Usually reconsider the route", "The scenic-area visit sits inside two longer road legs, so delays consume the walking time first.", "A verified through-route or an overnight that avoids returning to Yangshuo can make it coherent."],
    ["Older parents, young children or limited stair tolerance", "One night or a deliberately small day trip", "A slower pace and one accessible viewpoint matter more than collecting terrace names.", "A confirmed low-walking route may make a day trip comfortable."],
    ["Same-evening train, flight or non-refundable show", "Do not use Longji as the preceding day trip", "Mountain roads, weather and entry steps create several uncontrolled cutoffs.", "Move the fixed booking or place Longji on another date."],
    ["Arriving with several large suitcases", "One night only after last-mile verification, or store the bags in Guilin", "Some village stays require steps or a walk after the vehicle stops.", "A property that confirms vehicle access and named luggage help may solve it."],
  ]},
  { id: "not-one-stop", type: "callout", title: "Longji is a region, not one photo stop", tone: "neutral", body: "China's Ministry of Culture and Tourism identifies Dazhai Yao terraces, Ping'an Zhuang terraces, Longji Ancient Zhuang Village and Xiaozhai Red Yao terraces within the scenic area. Guangxi's official register gives the wider scenic area as 70.1 square kilometres. Do not buy a vague ‘Longji transfer’ and assume the entrance, village, viewpoint, vehicle stop and hotel are the same place." },
  { id: "area-heading", type: "heading", level: 2, text: "For one day, choose one coherent terrace area" },
  { id: "area-copy", type: "paragraph", text: "This page does not rank Ping'an, Dazhai/Jinkeng and every smaller village as if they were interchangeable products. The duration decision comes first. After that, ask the provider or accommodation to name the exact entrance, village, drop-off and walking route in Chinese. A day visitor should normally keep one area; an overnight visitor can use a second light or walking window without trying to cross the whole scenic region." },
  { id: "area-check", type: "table", caption: "What to verify after choosing the duration", columns: ["Decision", "Exact answer required", "Weak answer"], rows: [
    ["Terrace area", "Named area and village, not only ‘Longji’", "‘The driver knows the best place’"],
    ["Vehicle endpoint", "Named parking area or drop-off plus the remaining walk", "‘The hotel is inside the scenic area’"],
    ["Walking plan", "Surface, stairs, elevation change and turnaround point", "‘Easy for everyone’"],
    ["Entry", "Current entrance, passport method, ticket scope and any internal transport", "A screenshot with no date or official owner"],
    ["Return", "Named pickup place, responsible operator and a conservative departure cutoff", "‘Call us when you finish’"],
  ]},
  { id: "day-heading", type: "heading", level: 2, text: "What a good Longji day trip actually looks like" },
  { id: "day-shape", type: "list", ordered: true, items: [
    "Leave from a Guilin address with the exact destination area already agreed. Do not spend the first hour choosing between villages in the vehicle.",
    "Complete the current entrance or shuttle process, then go directly to the one walking loop or viewpoint sequence you selected.",
    "Pause for a meal or village rest without turning the visit into a race between named platforms.",
    "Use a pre-agreed turnaround time. The return begins at the viewpoint, not when the vehicle leaves the mountain.",
    "Keep the evening free of a flight, last train or other booking whose failure would damage the wider trip."
  ]},
  { id: "day-value", type: "paragraph", text: "A day trip succeeds when it produces one complete mountain experience: the layered fields, the relationship between forest, water, villages and cultivation, and enough walking time to notice how the land is worked. It fails when the road journey is treated as dead time and the traveller tries to recover it by rushing through two distant terrace areas." },
  { id: "day-breakers", type: "table", caption: "The warning signs that a day trip is becoming a bad deal", columns: ["Warning sign", "Why it matters", "Better response"], rows: [
    ["Departure slides later while the same route remains", "Walking and weather margin disappear first.", "Remove a viewpoint or move to an overnight; do not speed up the mountain road."],
    ["The booking names Longji but not the area", "You cannot calculate the final road and walking legs.", "Get the exact Chinese endpoint before paying."],
    ["Return is tied to the last possible connection", "A small delay becomes an expensive itinerary failure.", "Create a free evening or visit on another day."],
    ["Heavy luggage stays with the group", "Storage and steep last-mile handling may be unresolved.", "Store it in Guilin or obtain written property/vehicle handling details."],
    ["The plan promises sunrise and sunset in one day", "It is selling two different light windows without accounting for the night between them.", "Choose one night or remove the promise."],
  ]},
  { id: "overnight-heading", type: "heading", level: 2, text: "What one night buys — and what it does not" },
  { id: "overnight-comparison", type: "comparison", title: "The real overnight trade-off", columns: [
    { heading: "What you gain", items: ["A second weather window", "Quieter early or late hours", "A slower walking pace", "A route that can continue instead of returning to the same hotel"] },
    { heading: "What you add", items: ["Another check-in and check-out", "A mountain property last mile", "Luggage decisions", "More exposure to stairs, damp weather and limited late services"] },
    { heading: "What you do not buy", items: ["Guaranteed sunrise", "Guaranteed golden or mirror-like fields", "Automatic vehicle access to the door", "Permission to enter homes, fields or private paths"] },
  ]},
  { id: "overnight-shape", type: "list", ordered: true, items: [
    "Travel to the chosen terrace area early enough to enter and reach the accommodation in daylight.",
    "Confirm where the vehicle stops, who handles luggage and how many steps remain before arriving with full-size bags.",
    "Use the first afternoon for one village or viewpoint loop, not for crossing to every famous area.",
    "Choose the next morning's walk from the forecast, visibility and the actual path condition. Sunrise is an attempt, not a booked performance.",
    "Leave with a conservative road margin or continue to the next route segment only through a verified transfer."
  ]},
  { id: "overnight-callout", type: "callout", title: "Do not move hotels merely to wake before dawn", tone: "warning", body: "If darkness, steep wet steps or an uncertain property path would make the early walk unpleasant, the overnight may not add the value shown in photographs. A calm Guilin-based day trip can be better than carrying every bag uphill for a sunrise that cloud may hide. The overnight earns its place only when you will use the extra window." },
  { id: "origin-heading", type: "heading", level: 2, text: "Your starting point changes the answer" },
  { id: "origin-matrix", type: "table", caption: "Treat each origin as a different journey", columns: ["Origin or next stop", "Planning position", "Key check"], rows: [
    ["Guilin city hotel", "The cleanest base for a one-area day trip.", "True pickup address, exact terrace area and return buffer."],
    ["Guilin airport or railway station on arrival day", "Usually too fragile for a full visit unless the arrival is early and the plan can shrink safely.", "Flight/train delay, baggage collection, entry cutoff and night arrival at the property."],
    ["Yangshuo", "Not the same day-trip geometry as Guilin; two long road dependencies can leave little time on foot.", "Complete door-to-door route and whether an overnight or onward transfer avoids backtracking."],
    ["Continuing north or west after Longji", "An overnight may become efficient if a verified vehicle and luggage plan links the next leg.", "Do not assume a map line is a passenger service; name the operator and handoff."],
    ["Returning for an international departure", "Keep Longji away from the final hard deadline.", "Sleep near the departure gateway on the final night rather than gambling on a mountain-road return."],
  ]},
  { id: "season-heading", type: "heading", level: 2, text: "Plan for an agricultural landscape, not a colour calendar" },
  { id: "season-copy", type: "paragraph", text: "The National Agriculture Museum describes Longji as a living rice-terrace system across 11 administrative villages. Water, planting, growth and harvest follow farming decisions as well as weather. A photograph from another year cannot guarantee reflective water, bright green seedlings or gold fields on your date. Ask what is visibly happening now, then decide whether that landscape is still worth the journey." },
  { id: "season-table", type: "table", caption: "Use the landscape you actually find", columns: ["What you see", "A better way to read it", "Do not promise"], rows: [
    ["Water-filled plots", "Look for the relationship between channels, contour and mountain light.", "A perfect mirror or blue-sky reflection."],
    ["Growing green rice", "Notice how small fields connect to forest and village water systems.", "One universal ‘greenest week’."],
    ["Ripening or recently harvested fields", "Read cultivation patterns and active work; give farmers space.", "A fixed golden date or uncut fields."],
    ["Mist, cloud or muted colour", "Use the village, paths and living agricultural system as the story.", "That another viewpoint must be clear."],
  ]},
  { id: "weather", type: "callout", title: "Cloud is the best argument for one night, not a guarantee against disappointment", tone: "decision", body: "An overnight gives you another attempt, but both windows can still be cloudy. Set a visibility cutoff, keep one lower-risk village or cultural stop, and never ask a driver to race wet mountain roads between viewpoints. If an official weather or road closure is issued, the correct recovery is to change the day, not search for an unofficial entrance." },
  { id: "luggage-heading", type: "heading", level: 2, text: "Solve the last 500 metres before carrying a suitcase into the mountains" },
  { id: "luggage-table", type: "table", caption: "Property evidence that matters more than a scenic room photo", columns: ["Ask", "Useful answer", "Fallback"], rows: [
    ["Where exactly does the vehicle stop?", "A named parking/drop-off point and a map pin.", "Store large bags in Guilin and carry one-night luggage."],
    ["How far and how steep is the final path?", "Walking distance, surface, steps and recent route photos.", "Choose a vehicle-reachable property or make it a day trip."],
    ["Who carries the bags?", "Named property staff, availability window and any stated charge.", "Do not rely on someone being found after arrival."],
    ["What if arrival is late or raining?", "Written reception cutoff and a safe, lit meeting point.", "Stay in Guilin and enter the next morning."],
    ["Can this room fit the actual group?", "Exact booked room, beds, stairs and bathroom access.", "Use a more predictable room rather than a generic mountain-view category."],
  ]},
  { id: "access", type: "callout", title: "Terrace paths are not an accessibility promise", tone: "warning", body: "Even when a vehicle, shuttle or cableway removes part of the climb, the chosen viewpoint, village lane, hotel entrance and wet-weather route may still include uneven paving and stairs. Verify the complete path for the least mobile traveller. Do not translate ‘cableway available’ into ‘step-free visit’." },
  { id: "recovery-heading", type: "heading", level: 2, text: "Use a recovery plan before the mountain decides for you" },
  { id: "recovery", type: "table", caption: "Protect the trip, not the original checklist", columns: ["Problem", "First response", "When to stop"], rows: [
    ["Cloud hides the terraces", "Wait only within the chosen area, then use a village/rest stop or the second overnight window.", "When chasing another area creates a wet or dark road return."],
    ["Road control or closure", "Follow the official diversion or remain at a safe base.", "Never bypass a barrier on a village track."],
    ["Vehicle or pickup fails", "Contact the named operator and accommodation; agree on one legal replacement point.", "Do not accept an unmarked roadside vehicle simply because it says Guilin."],
    ["A traveller cannot manage the path", "Turn back to the last safe rest point and use the most accessible confirmed viewpoint.", "Do not split the group without a named meeting plan and communication."],
    ["The return is running late", "Drop the final viewpoint and leave on the agreed route.", "Do not protect a sunset at the expense of the next fixed booking."],
  ]},
  { id: "faq-heading", type: "heading", level: 2, text: "Questions travellers actually ask" },
  { id: "faq", type: "table", caption: "Short answers before you book", columns: ["Question", "Answer"], rows: [
    ["Can I visit Longji from Guilin in one day?", "Yes, if you leave early, choose one terrace area and keep the evening free. The plan must include entrance, internal movement, walking and the road return—not only the headline drive."],
    ["Can I do it from Yangshuo?", "It can be physically possible, but it is a different and more fragile door-to-door day. An overnight or a through-route that does not return to Yangshuo is often more coherent."],
    ["Is sunrise worth staying overnight?", "Only if you also value the slower visit and second weather window. Sunrise itself is never guaranteed, and the pre-dawn path must fit the group."],
    ["Should I choose Ping'an or Dazhai?", "Choose only after deciding duration, walking tolerance, vehicle endpoint and accommodation last mile. This page deliberately does not pretend that one area is universally best."],
    ["Can I bring a large suitcase?", "Not without checking the exact drop-off and final path. Store it in Guilin or obtain written luggage-help details before choosing a mountain stay."],
    ["Is Longji still worth it in rain or outside the famous colours?", "It can be, if you value a living cultivated landscape and villages rather than one guaranteed photograph. Active road or weather warnings still override the plan."],
  ]},
  { id: "facts", type: "callout", title: "Evidence boundary, reviewed 21 August 2026", tone: "neutral", body: "Official sources support Longji's location, multiple terrace/village areas, 4A status and living agricultural-heritage role. They do not establish a universal current transfer time, ticket, shuttle, opening hour, field colour or hotel last mile. The day-trip and overnight recommendations are Homeground planning judgments built around those verified geographic constraints. Recheck live operations before travel." },
  { id: "checklist", type: "list", items: [
    "One named terrace area, entrance and Chinese endpoint—not only ‘Longji’.",
    "A complete route from the real hotel, airport or station and back or onward.",
    "No same-evening hard connection after a day trip.",
    "A written vehicle, drop-off, walking and luggage plan.",
    "A weather alternative and a cutoff for abandoning extra viewpoints.",
    "Current official ticket, road, shuttle and opening checks.",
    "No promise of sunrise, clear sky or a particular field colour.",
    "Respect for working fields, irrigation paths, homes and village privacy."
  ]},
  { id: "links", type: "internal-links", title: "Connect Longji to the rest of the route", items: [
    { label: "Guilin to Yangshuo: train, road or river", href: "/guides/guilin-yangshuo-transport-route/", description: "Keep the separate Guilin–Yangshuo transport decision with its existing owner." },
    { label: "Is your China itinerary too rushed?", href: "/guides/is-your-china-itinerary-too-rushed/", description: "Test whether Longji creates a one-night hotel move or a fragile fixed connection." },
    { label: "China itinerary with older parents", href: "/guides/china-itinerary-with-older-parents/", description: "Design the walking, rest and vehicle plan around the least mobile traveller." },
    { label: "Yuanyang Rice Terraces viewpoint and village route", href: "/guides/yuanyang-rice-terraces-viewpoint-and-village-route/", description: "Compare another living terrace system without treating the two destinations as substitutes." },
    { label: "China public holidays travel calendar", href: "/guides/china-public-holidays-travel-calendar/", description: "Recheck holiday traffic controls before a mountain day." },
  ]},
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [
    { label: "Official Longji overview and named terrace areas", url: "https://www.mct.gov.cn/preview/special/9160/llxl/202009/t20200923_875345.htm", publisher: "Ministry of Culture and Tourism of China", reviewedAt: "2026-08-21" },
    { label: "Official Guangxi 4A scenic-area register", url: "https://wlt.gxzf.gov.cn/ztzl/rdjj/gxajlyjq/t19045600.shtml", publisher: "Guangxi Department of Culture and Tourism", reviewedAt: "2026-08-21" },
    { label: "Longji Rice Terraces agricultural heritage system", url: "https://jgs.agri.gov.cn/detail/zh/16211.html", publisher: "National Agriculture Museum", reviewedAt: "2026-08-21" },
    { label: "Longji living cultivation and conservation", url: "https://dnr.gxzf.gov.cn/xwzx/gnzx/t19768557.shtml", publisher: "Guangxi Department of Natural Resources", reviewedAt: "2026-08-21" },
    { label: "Hero: Longji rice terraces by Kaur Virunurm, CC0", url: "https://commons.wikimedia.org/wiki/File:Longji_rice_terraces_-_2023_10_11_Kaur_Virunurm.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-21" },
    { label: "Hero licence: CC0 1.0", url: "https://creativecommons.org/publicdomain/zero/1.0/", publisher: "Creative Commons", reviewedAt: "2026-08-21" },
  ]},
] } as const satisfies StructuredPageBody;

export default body;
