import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "‘성벽 안’은 너무 넓어 시안 호텔을 고를 수 없습니다. 종루는 구체적인 중심 노드이고 다른 성문 안팎은 전혀 다르게 움직이며, 다옌타는 별도의 문화·야간 묶음을 가진 남부 거점입니다. 평범한 밤이 어디서 끝나고 도시를 몇 번 가로지를지로 고르세요." },
  { id: "answer", type: "callout", title: "빠른 결론", tone: "decision", body: "짧은 첫 여행이 구시가지 핵심과 중앙 저녁 중심이면 종루를 고르세요. 특정 성문이 철도 도착·명소·차량 접근 가능한 조용한 골목과 실제로 맞을 때만 다른 성벽 안 위치를 택하세요. 대안탑·남부 박물관·공연／야간 지역·남부 일정이 반복되고 매일 구시가지로 돌아가는 것보다 중요하면 다옌타가 맞습니다." },
  { id: "boundary", type: "paragraph", text: "이 글은 세 위치 패턴을 고르며 호텔 순위를 만들거나 성벽 안 모든 주소를 하나로 보지 않습니다. 병마용 교통도 선택하지 않습니다. 교외 일정과 실제 출발점을 별도로 정하고 임시 투어 집결지가 모든 호텔 밤을 고르게 하지 마세요." },
  { id: "matrix", type: "table", caption: "세 명칭의 서로 다른 숙박 결정", columns: ["거점", "가장 잘 맞음", "주요 희생", "확인"], rows: [["종루／중러우", "첫 구시가지·중앙 음식·야간 산책", "인파·교통·일부 주소 차량 접근", "정확한 입구·중러우역 경로·조용한 객실"], ["다른 성문", "특정 성문·철도 연결·조용한 구시가지", "‘성 안’이어도 긴 도시 횡단", "성문 이름·횡단·역·하차"], ["다옌타／남부", "대안탑·남부 박물관·반복 남부 저녁", "구시가지 밤 뒤 긴 귀가", "정확한 역·행사 인파·마지막 도보"]] },
  { id: "trip-fit", type: "table", caption: "반복 일정이 고르게 하세요", columns: ["일정 패턴", "먼저 시험", "이유"], rows: [["2~3박 첫 방문, 구시가지 중심", "종루", "가장 많은 평범한 저녁을 중앙에 둠"], ["대안탑과 남부 문화가 여러 밤", "다옌타", "매일 중앙 아침 뒤 남쪽 귀환 방지"], ["한 성문 호텔이 훨씬 조용하거나 접근 쉬움", "그 정확한 성문", "숙소 접근이 유명 노드보다 중요"], ["다옌타 저녁 한 번, 나머지는 구시가지", "종루", "예외 한 번이 모든 밤을 정하지 않음"], ["부모님·유모차·여러 짐", "하차-엘리베이터-객실이 가장 쉬운 숙소", "역사 위치보다 접근 우선"]] },
  { id: "bell", type: "heading", level: 2, text: "종루: 유용한 중심이지 구시가지 전체는 아닙니다" },
  { id: "bell-copy", type: "paragraph", text: "시안시 방문 정보는 종루를 구시가지 네 대로의 교차점과 지하철 2호선 중러우역에 둡니다. 명확한 길 찾기와 야간 기준점입니다. 이름에 ‘종루’가 있어도 역 옆이나 차량 접근이 쉽다는 뜻은 아닙니다. 로비에서 거리를 재고 올바른 출구와 짐을 들고 주변 도로를 건너는 방법을 물으세요." },
  { id: "inside", type: "heading", level: 2, text: "성벽 안: 비교 전에 성문 이름을 말하세요" },
  { id: "inside-copy", type: "paragraph", text: "융닝먼, 철도역 쪽, 서쪽 성문, 작은 안쪽 골목은 다른 하루를 만듭니다. 가장 가까운 성문 이름과 성벽을 위·아래·문을 통해 건너는지 물으세요. 골목은 밤이 조용하지만 차량 하차까지 걸을 수 있고, 지도상 성벽 옆 주소가 제한된 통과점의 반대편일 수 있습니다." },
  { id: "dayanta", type: "heading", level: 2, text: "다옌타: 남부 야간 거점을 선택하세요" },
  { id: "dayanta-copy", type: "paragraph", text: "시안 공식 정보는 대안탑을 다옌타역에 두고 시 자료는 4호선이 주요 명소와 철도 접근을 잇는다고 설명합니다. 대안탑·남부 박물관·남부 저녁이 반복되면 맞습니다. 넓은 묶음 안의 정확한 호텔을 확인하세요. 행사 인파·큰 도로·역 이름에서 긴 도보가 겉보기 편의를 없앨 수 있습니다." },
  { id: "evening", type: "callout", title: "21시 30분에 지친 채 어디에 있을까요?", tone: "decision", body: "낮 명소 목록보다 이 답을 더 쓰세요. 여러 밤이 종루와 회민가 방향에서 끝나면 중앙, 여러 밤이 다옌타와 남부 문화 구역에서 끝나면 남부에 묵으세요. 예외 저녁 한 번의 택시는 매일 도시를 가로질러 귀가하는 것보다 대체로 쉽습니다." },
  { id: "arrival", type: "heading", level: 2, text: "표의 철도역 전체 이름과 호텔을 맞추세요" },
  { id: "arrival-copy", type: "paragraph", text: "시안의 철도역은 바꿔 쓸 수 없습니다. 표 전체 역 이름을 검색하고 일행 짐으로 실시간 문전 경로를 비교하세요. 직통 지하철도 보안·긴 통로·환승·어려운 횡단이 있을 수 있습니다. 늦은 열차 뒤에는 직원이 있고 도로 접근 가능한 체크인을 우선하고 남은 여러 밤에 이득일 때만 다음 날 이동하세요." },
  { id: "terracotta", type: "heading", level: 2, text: "병마용 집결지가 전체 숙박을 고르게 하지 마세요" },
  { id: "terracotta-copy", type: "paragraph", text: "병마용은 시안 중심 밖에 있고 대중·개인·투어 등 여러 방법이 있습니다. 방법과 실제 출발점을 먼저 정하세요. 현재 버스 집결지는 종루／다옌타 숙박의 영구적인 이유가 아닙니다. 집결지가 바뀌어도 호텔은 여행 나머지에 맞아야 합니다." },
  { id: "last-mile", type: "heading", level: 2, text: "역사 거리는 마지막 수백 미터를 결정적으로 만듭니다" },
  { id: "last-mile-list", type: "list", items: ["거리 주소뿐 아니라 중국어 호텔 입구와 차량 하차점을 받으세요.", "올바른 지하철 출구와 엘리베이터·횡단이 일행에게 맞는지 확인하세요.", "보행 골목·지하 통로·성문이 경로인지 보세요.", "야시장／공연 지역 객실은 확인된 조용한 쪽과 현재 공사를 물으세요.", "아이·부모님은 성벽·박물관·탑 일정을 마친 뒤 남은 도보를 계산하세요."] },
  { id: "room", type: "table", caption: "지역 약속을 숙소 증거로 바꾸세요", columns: ["주장", "질문", "막을 실패"], rows: [["‘성벽 안’", "성문 이름·거리·횡단 경로", "중앙 명칭이지만 매일 긴 도보"], ["‘종루 전망’", "배정 객실 방향·소음", "접근이 아닌 시끄러운 일부 전망에 지불"], ["‘다옌타 근처’", "정확한 출구·도로 횡단", "큰 지역 명칭의 긴 마지막 도보"], ["‘전통 스타일 호텔’", "엘리베이터·욕실·냉난방·여권", "분위기가 기본 객실 사실을 대체"], ["‘철도 접근’", "전체 역 이름·실제 시각", "잘못된 시안역 계획"]] },
  { id: "mobility", type: "callout", title: "분위기보다 입구를 먼저 고르세요", tone: "warning", body: "휠체어·유모차·무릎 통증·큰 짐은 하차·문·엘리베이터·샤워·사용할 역 출구를 확인하세요. 관광 위치가 좋아도 첫／마지막 200m가 실패할 수 있습니다. 숙소가 전체 경로를 설명 못 하면 도로 접근 가능한 일반 호텔을 고르고 짐 없이 골목을 방문하세요." },
  { id: "failure", type: "table", caption: "지역 선택이 기대보다 약할 때 복구", columns: ["문제", "즉시 대응", "계획 변화"], rows: [["택시가 골목에 못 감", "합의한 합법적 하차점과 숙소 도움", "반복되면 도로 접근 호텔"], ["심한 야간 소음", "확인된 조용한 쪽 객실", "지역보다 숙소를 먼저 변경"], ["철도역 오인", "표 전체 이름으로 재계산", "출발 밤을 가능한 교통 사슬로"], ["매일 남북 이동이 지배", "지역별 일정 묶기", "여러 날 남으면 낮에 한 번 이동"], ["행사 인파가 접근 변경", "공식 공지와 다른 직원 입구", "도로 이동 대안"]] },
  { id: "registration", type: "paragraph", text: "호텔은 외국인 투숙객을 등록합니다. 특히 골목 안 작은 전통형 숙소에는 제시한 도착 시각의 여권 체크인과 프런트를 확인하세요." },
  { id: "dynamic", type: "paragraph", text: "시안시 방문·지하철 자료는 2026년 8월 12일에 재확인했습니다. 명소 운영·행사·지하철 접근·숙소 입구는 변합니다. 날짜별 공식 채널과 호텔을 다시 확인하세요. 안정된 지리를 바탕으로 한 편집 판단이며 고정 이동 시간을 약속하지 않습니다." },
  { id: "links", type: "internal-links", title: "계속 계획하기", items: [ { label: "시안 도시 허브", href: "/ko/destinations/xian/", description: "이 세부 사항을 정하기 전에 숙박 일수, 거점, 다음 도시를 먼저 정하세요." },{ label: "투어 없이 병마용 방문", href: "/ko/guides/terracotta-warriors-without-tour/", description: "실제 교외 일정을 고르고 보호하세요." }, { label: "‘지하철 근처’ 판단법", href: "/ko/guides/china-hotel-near-metro/", description: "역 출구와 마지막 도보를 확인하세요." }, { label: "민수·홈스테이·호텔", href: "/ko/guides/minsu-homestay-or-hotel-china/", description: "전통형 숙소 운영을 확인하세요." }, { label: "중국 도시 성벽 읽기", href: "/ko/guides/chinese-city-walls-gates-and-urban-order/", description: "현존 재료, 보존 수리, 재건과 고고학 흔적을 구분하고 성문과 도로를 하나의 도시 체계로 이해합니다." }, { label: "산시역사박물관 계획", href: "/ko/guides/shaanxi-history-museum-booking-and-collection-plan/", description: "외국 여권으로 예약하고 샤오자이 본관과 진한관을 구분한 뒤 90분 또는 심화 관람 동선을 선택합니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 이미지 크레디트", items: [{ label: "시안 종루·고루 방문 정보", url: "https://en.xa.gov.cn/CultureTravel/Attractions/1691691501245550594.html", publisher: "시안시 인민정부", reviewedAt: "2026-08-12" }, { label: "대안탑 방문 정보", url: "https://en.xa.gov.cn/CultureTravel/Attractions/1691691504798126082.html", publisher: "시안시 인민정부", reviewedAt: "2026-08-12" }, { label: "지하철 4호선 도시 연결 공식 자료", url: "https://en.xa.gov.cn/MediaCenter/News/1691691435210428418.html", publisher: "시안시 인민정부", reviewedAt: "2026-08-12" }, { label: "대표 이미지: TarnishedPath의 종루, CC BY-SA 4.0, 크롭·변환", url: "https://commons.wikimedia.org/wiki/File:Bell_Tower_of_Xi%27an_at_night.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
