import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "‘Inside the City Wall’ is too broad to choose a Xi'an hotel. The Bell Tower is one specific central node; another gate inside or beside the wall can behave very differently; Dayanta is a south-side base with its own cultural and evening cluster. Choose where ordinary nights end and how often the itinerary crosses the city." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose near the Bell Tower for a short first trip built around the old-city core and central evenings. Choose another City Wall gate only when that exact gate matches a railway arrival, planned sights or a quieter lane with workable vehicle access. Choose Dayanta when Giant Wild Goose Pagoda, south-side museums, performance/evening areas or repeated south-side plans outweigh returning to the old city each night." },
  { id: "boundary", type: "paragraph", text: "This page chooses among three location patterns; it does not rank hotels or treat all addresses inside the wall as one base. It also does not choose a Terracotta Army transport method. Decide that excursion and its real departure point separately rather than letting a temporary tour pickup choose every hotel night." },
  { id: "matrix", type: "table", caption: "Three labels, three different lodging decisions", columns: ["Base", "Best fit", "Main sacrifice", "Verify"], rows: [["Bell Tower / Zhonglou", "First-trip old-city core, central food and evening walks", "Crowds, traffic and difficult curb access at some addresses", "Exact entrance, Zhonglou station route and quiet-side room"], ["Another City Wall gate", "A specific gate, railway connection or quieter old-city street", "‘Inside’ can still mean long cross-city walking", "Named gate, wall crossing, station and car drop-off"], ["Dayanta / south side", "Pagoda, south-side museums and repeated southern evenings", "Longer returns after old-city nights", "Exact station, event crowd plan and final walk"]] },
  { id: "trip-fit", type: "table", caption: "Let the repeated itinerary choose", columns: ["Trip pattern", "First base to test", "Why"], rows: [["Two or three nights, first visit, old city central", "Bell Tower", "It keeps the greatest number of ordinary evenings central"], ["Several nights around Giant Wild Goose Pagoda and south-side culture", "Dayanta", "Avoids returning south after every central morning"], ["A hotel near one wall gate is substantially quieter or easier to enter", "That exact gate", "Property access can beat a famous node"], ["One Dayanta evening, otherwise old city", "Bell Tower", "One exception should not choose every night"], ["Older parents, stroller or several bags", "Property with simplest curb-lift-room chain", "Historic location does not outrank access"]] },
  { id: "bell", type: "heading", level: 2, text: "Bell Tower: the useful centre, not the whole old city" },
  { id: "bell-copy", type: "paragraph", text: "Xi'an government visitor information places the Bell Tower at the intersection of the four old-city avenues and lists Zhonglou on Metro Line 2. That makes it a clear navigation and evening anchor. It does not mean every hotel using ‘Bell Tower’ in its name is beside the station or easy for a car. Measure from the lobby, identify the correct exit and ask how luggage crosses the surrounding roads." },
  { id: "inside", type: "heading", level: 2, text: "Inside the wall: name the gate before comparing" },
  { id: "inside-copy", type: "paragraph", text: "A property near Yongningmen, the railway-station side, a western gate or a small inner lane can create very different days. Ask which named gate is nearest and whether your route crosses over, under or through the wall. A lane may give a calmer night but add a walk to road pickup; an address close to the wall on a map may sit on the wrong side of a limited crossing." },
  { id: "dayanta", type: "heading", level: 2, text: "Dayanta: choose a south-side evening base" },
  { id: "dayanta-copy", type: "paragraph", text: "Official Xi'an information places Giant Wild Goose Pagoda at Dayanta station, and city reporting describes Line 4 connections among major sights and railway access. The area works when the pagoda, south-side museums or southern evenings repeat. Check the exact hotel within the broad cluster: event crowds, large roads and a long walk from the named station can erase the apparent convenience." },
  { id: "evening", type: "callout", title: "Where will you be tired at 21:30?", tone: "decision", body: "Use that answer more than a list of daytime attractions. If several nights finish around the Bell Tower and Muslim Quarter approaches, central wins. If several finish around Dayanta and the south-side cultural zone, stay south. A taxi for one exceptional evening is usually easier than a cross-city return every night." },
  { id: "arrival", type: "heading", level: 2, text: "Match the hotel to the full railway-station name" },
  { id: "arrival-copy", type: "paragraph", text: "Xi'an's railway stations are not interchangeable. Search the complete station name printed on the ticket and compare live door-to-door routes with the group's luggage. A direct metro line may still involve station security, long corridors, transfers or an awkward final crossing. After a late train, prioritise a staffed, road-accessible check-in; move the next day only if several remaining nights benefit." },
  { id: "terracotta", type: "heading", level: 2, text: "Do not let a Terracotta Army pickup choose the whole stay" },
  { id: "terracotta-copy", type: "paragraph", text: "The Terracotta Army lies outside central Xi'an and can be reached by different public, private or tour arrangements. Identify the method and actual departure point first. A current coach meeting point is not a permanent canonical reason to stay at the Bell Tower or Dayanta. If the pickup changes, the hotel should still work for the rest of the trip." },
  { id: "last-mile", type: "heading", level: 2, text: "Historic streets make the last few hundred metres decisive" },
  { id: "last-mile-list", type: "list", items: ["Ask for the Chinese hotel entrance and vehicle drop-off, not only the street address.", "Confirm the correct metro exit and whether lifts and crossings work for the whole group.", "Check whether a pedestrian lane, underground passage or wall gate is part of the route.", "For a room near a night market or performance area, request the quiet side and verify current construction.", "With children or older travellers, count the walk remaining after a full wall, museum or pagoda day."] },
  { id: "room", type: "table", caption: "Turn area promises into property evidence", columns: ["Claim", "Ask", "Failure to avoid"], rows: [["‘Inside the wall’", "Named gate, distance and crossing route", "Central label but long daily walk"], ["‘Bell Tower view’", "Assigned-room direction and sound exposure", "Paying for a noisy glimpse rather than access"], ["‘Near Dayanta’", "Exact station exit and road crossings", "Large district label with a long final walk"], ["‘Traditional-style hotel’", "Lift, bathroom, heating/cooling and passport process", "Atmosphere replacing basic room facts"], ["‘Easy railway access’", "Full station and actual travel hour", "Planning for the wrong Xi'an station"]] },
  { id: "mobility", type: "callout", title: "Choose an entrance before an atmosphere", tone: "warning", body: "For a wheelchair, stroller, painful knees or large luggage, verify curb, doorway, lift, shower and usable station exit. A hotel can be in an excellent sightseeing area yet fail the first and last 200 metres. If the property cannot describe the complete route, choose a conventional road-accessible hotel and visit the lanes without bags." },
  { id: "failure", type: "table", caption: "Recover when the area choice underperforms", columns: ["Problem", "Immediate response", "Plan change"], rows: [["Taxi cannot reach the lane", "Use only the agreed legal drop-off and request property help", "Move to a road-accessible hotel if this repeats"], ["Room faces severe evening noise", "Request a verified quiet-side room", "Change property, not necessarily district"], ["Wrong railway station assumption", "Recalculate with complete ticket name", "Protect the departure night near a workable chain"], ["Daily north-south crossing dominates", "Group days by area", "Move once in daylight if several days remain"], ["Event crowd changes access", "Use official notices and alternate staffed entrance", "Keep a road-transfer fallback"]] },
  { id: "registration", type: "paragraph", text: "Hotels register foreign guests. Ask the exact property to confirm passport check-in and reception at the stated arrival hour, especially for a small traditional-style property inside a lane." },
  { id: "dynamic", type: "paragraph", text: "Xi'an municipal visitor and metro references were reviewed on August 12, 2026. Attraction operations, events, metro access and property entrances can change. Recheck official channels and the hotel for the travel date; the recommendations are editorial judgements built on stable geography, not fixed journey times." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [ { label: "Xi'an destination hub", href: "/destinations/xian/", description: "Decide nights, base and the next city before fixing this detail." },{ label: "Terracotta Warriors without a tour", href: "/guides/terracotta-warriors-without-tour/", description: "Choose and protect the real out-of-city day." }, { label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Check the station exit and final walk." }, { label: "Minsu, homestay or hotel", href: "/guides/minsu-homestay-or-hotel-china/", description: "Verify a traditional-style property's operation." }, { label: "Read a Chinese city wall", href: "/guides/chinese-city-walls-gates-and-urban-order/", description: "Distinguish surviving fabric, conservation repair, reconstruction and archaeological traces, then read gates and streets as parts of an urban system." }, { label: "Plan Shaanxi History Museum", href: "/guides/shaanxi-history-museum-booking-and-collection-plan/", description: "Reserve with a foreign passport, avoid confusing the Main Building with the Qin-Han Gallery and choose a 90-minute or deeper collection route in Xi'an." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Xi'an Bell and Drum Towers visitor information", url: "https://en.xa.gov.cn/CultureTravel/Attractions/1691691501245550594.html", publisher: "Xi'an Municipal Government", reviewedAt: "2026-08-12" }, { label: "Giant Wild Goose Pagoda visitor information", url: "https://en.xa.gov.cn/CultureTravel/Attractions/1691691504798126082.html", publisher: "Xi'an Municipal Government", reviewedAt: "2026-08-12" }, { label: "Official Metro Line 4 city-connection reference", url: "https://en.xa.gov.cn/MediaCenter/News/1691691435210428418.html", publisher: "Xi'an Municipal Government", reviewedAt: "2026-08-12" }, { label: "Hero: Bell Tower by TarnishedPath, CC BY-SA 4.0; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:Bell_Tower_of_Xi%27an_at_night.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
