import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "A Beijing courtyard hotel can make the hutong part of the stay: a gate, a shared courtyard and a low-rise rhythm rather than a sealed tower. It can also mean narrow lanes, thresholds, room-to-room differences and less acoustic privacy. ‘Authentic’ describes an aspiration, not a room specification." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose a courtyard hotel when the setting is one of the trip's purposes and the exact room, entrance and luggage route have earned your confidence. Choose a modern hotel when lift access, predictable rooms, vehicle drop-off, sound control, connecting rooms or an efficient early departure matter more. A split stay works only when one deliberate move buys an experience you will actually use." },
  { id: "boundary", type: "paragraph", text: "This guide compares building and operating fit, not Beijing neighbourhoods. Decide Wangfujing, Qianmen, Sanlitun or a northern hutong base in the separate area guide first. A modern hotel can stand in a hutong, and a ‘courtyard-style’ property can be a recent reconstruction; neither label certifies heritage value or comfort." },
  { id: "matrix", type: "table", caption: "Test the property, not the romance", columns: ["Need", "Courtyard property can win", "Modern hotel can win"], rows: [["Sense of place", "Gate, courtyard and lane become part of the day", "Beijing experience happens outside a neutral room"], ["Arrival", "Rewarding when the lane and host handoff are clear", "Curb, lobby, lift and staffed desk are usually simpler"], ["Room", "Individual character", "More consistent layout, light and amenities"], ["Rest", "Small scale and quiet lane when the assigned room is protected", "More predictable sound separation and blackout"], ["Family or mobility", "Works only with a proven accessible room", "Lift, adjoining-room and bathroom options are easier to verify"], ["Early departure", "Possible with a confirmed car meeting point", "Road access and luggage handling are usually safer"]] },
  { id: "fit", type: "table", caption: "Let the least flexible traveller decide", columns: ["Situation", "Start with", "Exception"], rows: [["First night in China after a long flight", "Modern hotel", "Courtyard property has staffed late arrival and a simple car-to-room route"], ["Two light travellers who prioritise old-city mornings", "Courtyard hotel", "The room fails privacy, bathroom or climate-control checks"], ["Wheelchair, painful knees or stroller", "Modern hotel", "Courtyard confirms every threshold, doorway, lift/ramp and shower"], ["Family needing two adjacent rooms", "Modern hotel", "Courtyard names the exact rooms and their safe connection"], ["Very light sleeper", "Evidence from assigned room", "Never decide from building type alone"], ["One heritage night in a longer Beijing trip", "Split stay", "Moving costs more useful time than the night adds"]] },
  { id: "room", type: "heading", level: 2, text: "Ask about the assigned room" },
  { id: "room-list", type: "list", items: ["Is the room shown in the photos the booked category, and can that category be in several different wings or floors?", "Does it have an external window, private bathroom, seated toilet and reliable hot water?", "What heating or cooling operates during the travel dates, and can the guest control it?", "How many thresholds or steps lie between vehicle stop and bed, including the front gate?", "Does the room face the shared courtyard, breakfast tables, reception, lane, kitchen or mechanical equipment?", "For a loft or family room, are all advertised beds full sleeping surfaces with safe stairs and climate control?"] },
  { id: "photos", type: "callout", title: "The best photograph may not show a guest room", tone: "warning", body: "Courtyard listings naturally lead with the shared yard, carved gate or roofline. Ask for current photographs or a simple video of the booked room, bathroom, window and route from the entrance. Treat wide-angle room images and generic ‘room assigned at check-in’ language as reasons to ask more, not automatic rejection." },
  { id: "access", type: "heading", level: 2, text: "Map the last 300 metres with luggage" },
  { id: "access-copy", type: "paragraph", text: "A hutong address may be pleasant on foot but awkward for a car. Ask for the legal vehicle drop-off, the Chinese gate name, walking surface, night lighting and who can help with bags. Confirm whether a narrow lane, bollard or pedestrian control changes access at certain hours. Do not assume a taxi can stop at the door because the map route ends there." },
  { id: "access-table", type: "table", caption: "Turn the entrance into a usable arrival plan", columns: ["Check", "Good evidence", "Fallback"], rows: [["Vehicle stop", "Named road or landmark plus a map pin", "Meet staff at a staffed landmark"], ["Walking route", "Distance, surface, steps and gate photographs", "Use a smaller bag and store the main case"], ["Late entry", "Staffed hours and guest key/door process", "Modern hotel for the first night"], ["Rain or snow", "Covered waiting and a safe non-slip route", "Road-accessible property"], ["Luggage help", "Named property service and availability", "Do not rely on an informal street porter"]] },
  { id: "noise", type: "heading", level: 2, text: "A quiet hutong can contain a noisy room" },
  { id: "noise-copy", type: "paragraph", text: "Low-rise courtyards bring doors, windows, breakfast and conversation into a shared acoustic space. Ask where the assigned room sits, quiet hours, whether guests smoke or talk in the courtyard, and whether doors seal properly. A room facing an internal yard may avoid road noise but hear every late return. Light sleepers should request a room away from gate, reception and breakfast rather than asking only for ‘quiet’." },
  { id: "weather", type: "heading", level: 2, text: "Season changes what traditional geometry feels like" },
  { id: "weather-copy", type: "paragraph", text: "Beijing courtyard architecture is culturally meaningful, but a hotel conversion's insulation, heating, cooling and drainage are property-specific. In cold or hot periods, confirm operating dates and guest control of the system. In rain or snow, ask whether the bathroom or breakfast route crosses an uncovered courtyard. Do not infer modern performance from a renovated appearance." },
  { id: "registration", type: "heading", level: 2, text: "Architecture does not decide passport registration" },
  { id: "registration-copy", type: "paragraph", text: "A courtyard hotel operating as a hotel should register foreign guests. A private courtyard home or other non-hotel address follows the separate registration requirement within 24 hours. Ask which model applies, who handles it and which current local registration route is appropriate. ‘Traditional house’ and ‘boutique stay’ do not answer the legal or operational question." },
  { id: "arrival", type: "list", ordered: true, items: ["Send the real property-arrival window and passport count.", "Save the Chinese entrance and telephone number offline.", "Ask where the car stops and who meets you if it cannot enter the lane.", "Photograph any luggage left with a separate storage point and keep valuables with you.", "At the room, test the door, bathroom, hot water and temperature before unpacking."] },
  { id: "failure", type: "table", caption: "Recover without sacrificing the Beijing plan", columns: ["Problem", "First request", "Switch when"], rows: [["Assigned room differs", "The booked category or a clearly equivalent room", "Window, bathroom, beds or access cannot be delivered"], ["Car cannot reach entrance", "Staff meet the agreed stop and assist lawfully", "The route is unsafe for the group or luggage"], ["Noise prevents sleep", "Inspect a genuinely quieter room", "Only another courtyard-facing room is offered without evidence"], ["Heating/cooling or hot water fails", "Repair deadline and alternative room", "No habitable solution for the night"], ["Late check-in contact is absent", "Use written backup and platform support from a staffed place", "No responsible person can admit the group"]] },
  { id: "switch", type: "callout", title: "When a split stay is worth it", tone: "decision", body: "Put the courtyard night in the middle of the Beijing stay, not automatically on an international arrival or pre-flight departure. Leave the large case with the modern hotel only if storage is confirmed, carry an overnight bag and move after sightseeing check-out pressure has passed. If this choreography feels like work, visit a courtyard museum or neighbourhood and sleep in the modern hotel." },
  { id: "dynamic", type: "paragraph", text: "Beijing government cultural material and national accommodation-registration guidance were reviewed on August 13, 2026. They support the importance of hutong and siheyuan and the registration boundary; they do not certify any hotel's heritage, comfort or access. Verify the property itself." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Where to stay in Beijing on a first trip", href: "/guides/beijing-where-to-stay-first-trip/", description: "Choose the area before the building type." }, { label: "Minsu, homestay or hotel", href: "/guides/minsu-homestay-or-hotel-china/", description: "Read small-property labels more carefully." }, { label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Test the usable station entrance and final walk." }] },
  { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Official Beijing hutong visitor feature", url: "https://english.beijing.gov.cn/travellinginbeijing/citytours/202012/t20201214_2164217.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-13" }, { label: "Official cultural introduction to hutongs and siheyuan", url: "https://english.beijing.gov.cn/beijinginfo/culture/202005/t20200515_1898145.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-13" }, { label: "Online registration for foreigners staying outside hotels", url: "https://www.nia.gov.cn/n741440/n741577/c1771556/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
