import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "中国的公众假期安排每年都会变化，官方放假日期也只是旅行判断的第一层。先用下方日历找出容易受影响的跨城移动、限时预约景点和换酒店环节，再分别核对运营方的实时规则。2026年安排已经正式公布；2027年安排尚未发布。",
    },
    {
      id: "status-summary",
      type: "comparison",
      title: "日历状态（核对日期：2026年8月11日）",
      columns: [
        {
          heading: "2026年——已正式发布",
          body: "国务院办公厅通知列出七段假期和六个调休工作日，完整日期见下表。",
        },
        {
          heading: "2027年——尚未发布",
          body: "本页不会根据农历日期、往年安排或旅游平台预测补出日期；官方通知发布后再更新。",
        },
      ],
    },
    {
      id: "calendar-heading",
      type: "heading",
      level: 2,
      text: "2026年中国官方公众假期",
    },
    {
      id: "calendar-intro",
      type: "paragraph",
      text: "以下为《国务院办公厅关于2026年部分节假日安排的通知》（国办发明电〔2025〕7号）公布的全国安排。“调休工作日”是被安排为上班日的周六或周日，不是额外增加的假期。",
    },
    {
      id: "official-calendar",
      type: "table",
      caption: "2026年官方放假日期与调休工作日",
      columns: ["节日", "官方放假日期", "天数", "调休工作日"],
      rows: [
        ["元旦", "1月1日至3日", "3天", "1月4日（星期日）"],
        ["春节", "2月15日至23日", "9天", "2月14日（星期六）、2月28日（星期六）"],
        ["清明节", "4月4日至6日", "3天", "无"],
        ["劳动节", "5月1日至5日", "5天", "5月9日（星期六）"],
        ["端午节", "6月19日至21日", "3天", "无"],
        ["中秋节", "9月25日至27日", "3天", "无"],
        ["国庆节", "10月1日至7日", "7天", "9月20日（星期日）、10月10日（星期六）"],
      ],
    },
    {
      id: "official-not-operator",
      type: "callout",
      tone: "warning",
      title: "官方放假不等于全国统一营业时间",
      body: "国务院办公厅日历说明全国放假日期和调休工作日，但它不会保证某家博物馆开放、某家餐厅停业、某家酒店有房，或某趟列车有票。这些都属于不同运营方的单独决定。",
    },
    {
      id: "different-effects-heading",
      type: "heading",
      level: 2,
      text: "不同假期对旅行的影响并不相同",
    },
    {
      id: "holiday-effects",
      type: "table",
      caption: "每个假期为什么是不同的规划问题",
      columns: ["假期", "有证据支持的差异或结构特点", "行程里要检查什么"],
      rows: [
        ["元旦", "三天短假，之后的星期日调整为工作日。", "关注短途休闲出行和1月4日工作日，不要把它当成缩小版春节。"],
        ["春节", "九天公众假期位于另行公布的40天春运期内。", "探亲流向、长途票、商户停业安排和抵达后的恢复时间。"],
        ["清明节", "三天内同时有祭扫与休闲出行；官方交通信息特别关注墓区和景区周边道路。", "短途公路、当地交通，以及具体景区或祭扫区域通知。"],
        ["劳动节", "五天休闲出行集中，交通运输部会针对公路、铁路和民航综合准备。", "跨城备选、可取消住宿和限时入场容量。"],
        ["端午节", "2026年为三天假期，未列调休工作日。", "类似周末的区域短途出行、活动专属规则，以及那次紧凑换乘是否必要。"],
        ["中秋节", "三天家庭与休闲假期，2026年与国庆假期分开。", "核对九月对应周末和当地活动，不要直接套用十月判断。"],
        ["国庆节", "七天官方假期加两个调休工作日，适合形成全国性长线休闲出行。", "是否在一地停留、把跨城移动后移，以及如何保护依赖预约的日程。"],
      ],
    },
    {
      id: "no-ranking",
      type: "callout",
      tone: "neutral",
      title: "这不是“拥挤排行榜”",
      body: "一张全国日历无法负责任地给每座城市、每条线路和每个时段打同一个分数。实际判断取决于节日、出行方向、具体运营方、普通周末、当地活动，以及你的行程能否承受连接失败。",
    },
    {
      id: "spring-heading",
      type: "heading",
      level: 2,
      text: "春节：放假九天，但春运持续40天",
    },
    {
      id: "spring-detail",
      type: "paragraph",
      text: "交通运输部公布的2026年春运期为2月2日至3月13日。它远长于2月15日至23日的公众假期，因为探亲出行会分散在正式假期前后。这说明长途交通需要扩大核查日期范围，但不代表每条线路在40天里都同样繁忙。",
    },
    {
      id: "spring-checks",
      type: "list",
      items: [
        "逐段核对长途火车或航班的方向和日期，不要只看它是否落在2月15日至23日内。",
        "直接确认小型商户、餐厅和旅游服务的营业日期；家庭经营者可能自行安排春节休息。",
        "不要把不可退的景点预约紧接在不确定的长途抵达之后。",
        "长途夜航或大型探亲换乘后，要留出恢复时间。",
      ],
    },
    {
      id: "labour-national-heading",
      type: "heading",
      level: 2,
      text: "劳动节与国庆节：保护行程结构，不预测统一价格",
    },
    {
      id: "labour-national-detail",
      type: "paragraph",
      text: "劳动节五天、国庆节七天，让长线休闲出行更容易形成。多城市旅客应当预期热门日期下舒适备选会减少，但这不能推出全国统一的酒店涨幅，也不能承诺假期后第一天一定清静。位置、线路、房型、取消规则和当地活动仍会改变结果。",
    },
    {
      id: "october-owner",
      type: "callout",
      tone: "decision",
      title: "准备十月旅行？继续看十月决策文章",
      body: "本页负责全国年度假期日历。另一篇十月文章专门比较国庆假期与十月中下旬，包括路线结构和地区天气；它不会替代本页的年度官方日期来源。",
    },
    {
      id: "system-effects-heading",
      type: "heading",
      level: 2,
      text: "假期会怎样影响四类预订系统",
    },
    {
      id: "system-effects",
      type: "table",
      caption: "按预订系统拆分的旅行影响",
      columns: ["系统", "假期日历能告诉你什么", "它不能告诉你什么", "必须另行核对"],
      rows: [
        ["跨城交通", "哪些日期需要更早准备备选，并减少前后相互依赖的换乘。", "实时余票、价格、航班准点情况，或某个方向的具体压力。", "官方12306或航空公司库存，以及当期车站、机场指引。"],
        ["景区与场馆", "哪些日期更需要关注假期通知和限时预约。", "某个场馆究竟开放、闭馆、延长时间还是更换入口。", "该场馆官方预约渠道和当期假期公告。"],
        ["酒店", "哪些日期应在决策中更重视位置和可取消性。", "全国统一涨价幅度、实际房量，或某个房型是否适合。", "具体酒店、分店、房型配置和取消条款。"],
        ["商户与旅游服务", "哪些日期可能不再符合普通工作日习惯，春节前后尤其如此。", "适用于所有私营商户的全国统一营业安排。", "临近出行时向运营方直接确认。"],
      ],
    },
    {
      id: "rail-heading",
      type: "heading",
      level: 3,
      text: "铁路：当前预售期不等于有票保证",
    },
    {
      id: "rail-detail",
      type: "paragraph",
      text: "中国铁路现行规则以乘车日期计算，标准预售期为15天（含当天），并说明铁路可调整预售期并另行公告。应从实际乘车日倒推，在官方12306核对发售详情，同时准备可接受的替代车次。本页不读取实时库存。",
    },
    {
      id: "attraction-heading",
      type: "heading",
      level: 3,
      text: "景点：国家放假日期与场馆开放时间是两套数据",
    },
    {
      id: "attraction-detail",
      type: "paragraph",
      text: "故宫博物院可以说明这条边界。其2026年春节公告明确2月16日全天闭馆，并公布其余假期日期的开放安排；劳动节公告则明确5月1日至5日开放并列出时间。同一场馆在两个假期采用不同规则，不能把它复制到其他博物馆或其他年份。",
    },
    {
      id: "comp-workdays-heading",
      type: "heading",
      level: 2,
      text: "不要漏看调休工作日",
    },
    {
      id: "comp-workdays-detail",
      type: "paragraph",
      text: "中国每年的放假通知可以把普通周末调整为工作日。2026年共有1月4日、2月14日、2月28日、5月9日、9月20日和10月10日六天。星期日上班可能影响通勤、办公和当地生活节奏，但不代表所有景点或私营商户必须采用相同营业安排。",
    },
    {
      id: "route-method-heading",
      type: "heading",
      level: 2,
      text: "把日历变成路线判断",
    },
    {
      id: "route-method",
      type: "list",
      ordered: true,
      items: [
        "把入境、每次跨城移动和国际离境日逐一对照官方假期与调休工作日。",
        "如果春节出行，再把长途交通与另行公布的春运期对照。",
        "标出会破坏下一项预订的环节：指定车次、航班、一晚酒店和限时入场景点。",
        "没有可行备选时，删掉或后移一次换城市；一地住宿比连续一晚一城更容易恢复。",
        "进入真实预订窗口后，再核对官方交通库存、场馆公告和酒店条款。",
        "重新检查国际离境前的最后一晚，不要依赖当天长距离国内接驳。",
      ],
    },
    {
      id: "route-pattern",
      type: "comparison",
      title: "同一假期日期下的两种路线结构",
      columns: [
        {
          heading: "更有恢复空间",
          items: [
            "集中假期内保持同一家酒店作为基地。",
            "每天只有一个依赖预约的重点，附近另有替代。",
            "可取消房间，并接受两种跨城班次。",
            "国际航班前一晚已住在离境城市。",
          ],
        },
        {
          heading: "更容易连锁失效",
          items: [
            "每一两晚就换城市或酒店。",
            "长途移动后立刻安排固定入场景点。",
            "只接受一个座位、一个房型和一次连接，没有备选。",
            "国际航班当天才长距离抵达出发城市。",
          ],
        },
      ],
    },
    {
      id: "future-heading",
      type: "heading",
      level: 2,
      text: "旅行年份尚未公布怎么办？",
    },
    {
      id: "future-boundary",
      type: "callout",
      tone: "warning",
      title: "2027年：尚未发布",
      body: "截至2026年8月11日，2027年官方公众假期和调休工作日安排尚未发布。应把年度日历保留为一项未解决的规划依赖，不要把节日本身的日期或上一年的调休日期当成订票承诺。",
    },
    {
      id: "update-mechanism",
      type: "paragraph",
      text: "本页使用固定不变的常青URL。国务院办公厅发布新一年度通知后，结构化日历、三语正文和信息图必须同步更新。交通与景点信息只根据带日期的官方公告补充，并保留核对日期和适用范围。",
    },
    {
      id: "help-cta",
      type: "callout",
      tone: "decision",
      title: "固定日期需要人工检查？",
      body: "请留下出行日期、人数、大致预算，以及正在考虑的城市。规划师可以帮助找出受假期影响的关键换乘和缓冲，但不会把未来库存说成已保证。",
    },
    {
      id: "more-planning",
      type: "internal-links",
      title: "继续规划",
      items: [
        {
          label: "比较国庆假期与十月中下旬",
          href: "/zh/guides/china-in-october-golden-week-or-later/",
          description: "十月文章负责该月内的日期选择、路线结构和天气差异。",
        },
        {
          label: "第一次乘坐中国高铁",
          href: "/zh/guides/china-high-speed-train-first-time-guide/",
          description: "确认假期敏感的铁路段后，再了解护照、车票和车站流程。",
        },
        {
          label: "检查中国行程是否太赶",
          href: "/zh/guides/is-your-china-itinerary-too-rushed/",
          description: "减少相互依赖的换城环节，让假期变化更容易被吸收。",
        },
        {
          label: "国际航班前最后一晚住在哪里",
          href: "/zh/guides/china-last-night-before-international-flight/",
          description: "不要让当天的长途国内接驳威胁国际离境。",
        },
        { label: "分清节气、法定节假日与出行高峰", href: "/zh/guides/china-24-solar-terms-weather-food-daily-life/", description: "把节气当作文化与季节语境；法定休假、调休工作日和客流压力要查当年官方日历。" },
        { label: "了解中国旅行费用由什么决定", href: "/zh/guides/how-much-does-a-china-trip-cost/", description: "比较位置、灵活性和预订条款，而不是套用全国统一假期涨幅。" },
        { label: "沿绿道读懂成都", href: "/zh/guides/chengdu-greenway-city-ring/", description: "选择一段长度合适的成都环城绿道，连接公共交通与社区，并提前安排途中退出点。" },
        { label: "用四套时间表规划春节", href: "/zh/guides/lunar-new-year-customs-for-visitors/", description: "预订前分开农历日期、法定休假、交通需求以及每个家庭或场所自己的安排。" },
        { label: "自助参观莫高窟", href: "/zh/guides/mogao-caves-independent-visit-workflow/", description: "使用外籍护照官方入口，分清正常与应急参观，到对的起点报到，并为天气停开保留调整空间。" },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "已核对的官方来源",
      items: [
        { label: "2026年部分节假日安排", url: "https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm", publisher: "国务院办公厅", reviewedAt: "2026-08-11" },
        { label: "2026年春运安排", url: "https://www.mot.gov.cn/jiaotongyaowen/202601/t20260126_4198781.html", publisher: "交通运输部", reviewedAt: "2026-08-11" },
        { label: "2026年清明假期交通回顾", url: "https://www.mot.gov.cn/xinwen/jiaotongyaowen/202604/t20260407_4203180.html", publisher: "交通运输部", reviewedAt: "2026-08-11" },
        { label: "2026年劳动节交通新闻发布会", url: "https://www.mot.gov.cn/xinwen/xinwenfabuhui/202604/t20260424_4204258.html", publisher: "交通运输部", reviewedAt: "2026-08-11" },
        { label: "现行铁路售票规则", url: "https://kyfw.12306.cn/otn/gonggao/saleTicketMeans.html?linktypeid=means2", publisher: "中国铁路12306", reviewedAt: "2026-08-11" },
        { label: "故宫博物院2026年春节开放公告", url: "https://www.dpm.org.cn/announce_detail/378505.html", publisher: "故宫博物院", reviewedAt: "2026-08-11" },
        { label: "故宫博物院2026年劳动节开放公告", url: "https://www.dpm.org.cn/announce_detail/378865.html", publisher: "故宫博物院", reviewedAt: "2026-08-11" },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
