import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"You can visit Mogao Caves independently, but it is a controlled sequence rather than a walk-up monument: reserve through the official foreign-passport path, arrive at the Mogao Caves Digital Exhibition Center—not the protected cave zone—at least 30 minutes before your slot, complete the ticket procedure, then follow the official film, shuttle and guided-cave flow attached to your ticket type."},
{id:"official-2026",type:"callout",title:"2026 operating framework, verified 12 August",body:"The Dunhuang Academy's 2026 notice sets normal visits at a daily limit of 6,000 with digital film plus eight physical caves, and emergency visits at 12,000 with four physical caves. Emergency mode is activated when management requires it; it is not simply a cheaper version of the same experience. Capacity, accessible caves and special-cave arrangements remain controlled.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"Use the passport channel the operator actually names"},
{id:"booking",type:"list",items:["Follow the official WeChat service account 莫高窟参观预约网 and choose Ticket Booking under the reservation menu for foreign passports and Hong Kong, Macao or Taiwan travel documents.","Enter each traveller's real document details and carry the same original valid document. Ticket, document and person must match.","Choose the date, time and visit mode deliberately. Do not assume an emergency ticket will later convert into eight caves.","Avoid third-party ‘guaranteed tickets’. The 2026 official notice says no third party or individual is authorised to sell tickets on the operator's behalf.","Keep the official consultation number and order record offline, but note that the hotline answers questions and does not make reservations."]},
{id:"modes",type:"table",caption:"Mogao visit modes in the 2026 announcement",columns:["Mode in the 2026 notice","Included sequence","Planning consequence"],rows:[["Normal visit","Digital film hall plus eight physical caves; daily capacity 6,000.","Choose this when the fuller interpretation and cave allocation matter. Arrive at the Digital Exhibition Center for the complete workflow."],["Emergency visit","Four physical caves; daily capacity 12,000 when the mode is activated.","Expect a shorter, crowd-management product—not the same visit without films."],["Special caves","Limited opening governed by cave capacity and management.","Treat as an optional, day-specific procedure after a normal or emergency visit, never a guaranteed add-on."]]},
{id:"sequence-heading",type:"heading",level:2,text:"The first destination is on Yangguan East Road"},
{id:"sequence",type:"list",items:["Navigate to 莫高窟数字展示中心, 8899 Yangguan East Road, Dunhuang.","Arrive at least 30 minutes before the reserved time, as the official notice instructs.","Complete the applicable paper ticket-information slip procedure with the original document; follow staff instructions for your ticket type.","Proceed through the film and official transfer sequence included with the normal ticket, or the flow assigned to an emergency ticket.","At the cave zone, stay with the controlled group and guide. Which physical caves open is allocated and conservation-led, not a menu you can freely select."]},
{id:"wrong-gate",type:"callout",title:"Do not drive directly to the protected cave zone",body:"The official notice says the core cave area has neither a ticket office nor visitor parking. A map search that ends at the cliff can make you miss the real check-in. Save the Digital Exhibition Center in Chinese and show it to the driver.",tone:"warning"},
{id:"hours",type:"paragraph",text:"For 2026, the official notice lists 08:00–18:00 with last admission at 16:10 from 1 April to 30 November, and 09:00–17:00 with last admission at 15:10 from 1 December to 31 March. These are dated 2026 facts. Recheck the newest notice for your date, especially around weather, maintenance or a change of visit mode."},
{id:"weather-heading",type:"heading",level:2,text:"Protect the day against weather and conservation decisions"},
{id:"weather",type:"list",items:["Do not place a non-changeable flight or long-distance train immediately after the cave slot.","Check the Dunhuang Academy and official booking account on the morning of the visit.","Keep the booking account and payment method accessible in case an official change, refund or reschedule is offered.","A June 2026 rain closure shows why ‘desert’ does not mean weather-proof; the operator stopped ticket checks for safety and conservation reasons.","Never infer that one suspension policy applies to every future closure. Follow the specific dated notice."]},
{id:"guide",type:"paragraph",text:"Independent here does not mean unaccompanied inside every cave. The physical-cave section follows the site's controlled interpretation and conservation system. A private travel guide can help with wider Dunhuang context, language and transport, but cannot choose protected caves at will or bypass ticket allocation."},
{id:"final-check",type:"list",items:["Official Ticket Booking order matches every passport.","Normal or emergency mode is understood before payment.","Digital Exhibition Center—not the cliff—is saved as the first stop.","Arrival is at least 30 minutes early.","The day has weather and return-transport flexibility."]},
{id:"internal-links",type:"internal-links",title:"Connect the Dunhuang visit",items:[{label:"China high-speed trains for first-time visitors",href:"/guides/china-high-speed-train-first-time-guide/",description:"Use exact station names and leave a realistic post-visit buffer."},{label:"China public holidays",href:"/guides/china-public-holidays-travel-guide/",description:"Understand why limited-capacity tickets need earlier decisions."},{label:"Is your China itinerary too rushed?",href:"/guides/is-your-china-itinerary-too-rushed/",description:"Keep one conservation-controlled visit from destabilising the route."},{label:"Do you need a tour guide in China?",href:"/guides/do-you-need-a-tour-guide-in-china/",description:"Separate site-controlled interpretation from private trip support."}]},
{id:"consultation",type:"callout",title:"Need Mogao fitted into a wider Dunhuang stay?",body:"A Homeground travel consultant can check the live official workflow and protect transfers around your reserved slot. Share your passport type, visit date, ticket mode if already booked, hotel and fixed onward departure.",tone:"neutral"},
{id:"sources",type:"sources",title:"Official and image sources reviewed",items:[{label:"2026 Mogao Caves visitor-opening announcement",url:"https://www.dunhuangcaves.org/info/1020/7498.htm",publisher:"Dunhuang Academy",reviewedAt:"2026-08-12"},{label:"24 June 2026 rain suspension notice",url:"https://www.dunhuangcaves.org/info/1020/7731.htm",publisher:"Dunhuang Academy",reviewedAt:"2026-08-12"},{label:"Hero: Mogao Caves Exterior And Chambers by eviltomthai, CC BY 2.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:Mogao_Caves_Exterior_And_Chambers.jpeg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
