import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"막고굴은 자유여행으로 갈 수 있지만 현장에서 자유롭게 입장하는 유적이 아니라 통제된 절차입니다. 외국 여권 소지자용 공식 예약 경로로 예약하고, 보호구역의 석굴이 아닌 막고굴 디지털전시센터에 예약 시각보다 최소 30분 전 도착한 뒤, 입장권 종류에 포함된 영화·공식 셔틀·석굴 해설 순서를 따르세요."},
{id:"official-2026",type:"callout",title:"2026년 운영 체계—8월 12일 확인",body:"둔황연구원의 2026년 공지는 일반 관람을 하루 6,000명, 디지털 영화와 실제 석굴 8곳으로 정합니다. 응급 관람은 운영 측이 가동할 때 하루 12,000명, 실제 석굴 4곳입니다. 응급 관람은 같은 체험을 단순히 저렴하게 줄인 상품이 아니며, 수용량과 개방 석굴, 특별 석굴은 계속 보존 기준에 따라 관리됩니다.",tone:"warning"},
{id:"booking-heading",type:"heading",level:2,text:"운영기관이 지정한 여권 경로를 사용하세요"},
{id:"booking",type:"list",items:["공식 위챗 서비스 계정 ‘莫高窟参观预约网’을 팔로우하고 외국 여권 및 홍콩·마카오·대만 여행증명서는 예약 메뉴 아래 Ticket Booking을 선택하세요.","각 여행자의 실제 증명서 정보를 입력하고 같은 유효 원본을 가져가세요. 입장권 정보·신분증·방문자가 서로 일치해야 합니다.","날짜, 시간대와 관람 방식을 의도적으로 고르세요. 응급권이 현장에서 석굴 8곳을 보는 일반권으로 바뀐다고 기대하지 마세요.","‘입장권 확보 보장’을 내세운 대행은 피하세요. 2026년 공식 공지는 어떤 제3자나 개인에게도 판매 대행을 허가하지 않았다고 밝힙니다.","공식 상담 번호와 예약 내역을 오프라인으로 저장하되 전화는 상담만 하고 예약을 받지 않습니다."]},
{id:"modes",type:"table",caption:"2026년 막고굴 관람 방식",columns:["2026년 공지의 방식","포함 절차","계획 의미"],rows:[["일반 관람","디지털 영화관 + 실제 석굴 8곳, 하루 6,000명.","더 완전한 해석과 동굴 배정이 중요할 때 선택하고 디지털전시센터에서 전체 절차를 시작하세요."],["응급 관람","가동 시 실제 석굴 4곳, 하루 12,000명.","혼잡 관리를 위한 짧은 상품이며 영화만 빠진 같은 방문이 아닙니다."],["특별 동굴","동굴 수용량과 운영에 따라 제한 개방.","일반 또는 응급 관람 뒤 당일 가능한 선택 절차일 뿐, 보장된 추가 상품이 아닙니다."]]},
{id:"sequence-heading",type:"heading",level:2,text:"첫 목적지는 양관동로에 있습니다"},
{id:"sequence",type:"list",items:["둔황시 양관동로 8899호 ‘莫高窟数字展示中心’을 목적지로 저장하세요.","공식 안내대로 예약 시간 최소 30분 전에 도착하세요.","원본 증명서를 가져가 표 종류에 해당하는 종이 구매정보 확인서 절차를 마치고 직원 안내를 따르세요.","일반권는 영화와 공식 이동 순서를, 응급권는 그 표에 배정된 절차를 따릅니다.","동굴 구역에서는 통제된 그룹과 해설을 따르세요. 실제 개방 동굴은 보존 기준에 따라 배정되며 자유 선택 메뉴가 아닙니다."]},
{id:"wrong-gate",type:"callout",title:"보호구역 동굴로 직접 운전하지 마세요",body:"공식 공지는 핵심 동굴 구역에 매표소도 관람객 주차장도 없다고 명시합니다. 지도 검색이 절벽에서 끝나면 실제 체크인을 놓칠 수 있습니다. 중국어 ‘莫高窟数字展示中心’을 저장해 기사에게 보여 주세요.",tone:"warning"},
{id:"hours",type:"paragraph",text:"2026년 공식 시간은 4월 1일–11월 30일 08:00–18:00, 입장 마감 16:10이며 12월 1일–다음 해 3월 31일 09:00–17:00, 입장 마감 15:10입니다. 날짜가 명확한 2026년 사실이며 날씨, 정비나 관람 방식 변경이 있으면 최신 공지를 다시 확인해야 합니다."},
{id:"weather-heading",type:"heading",level:2,text:"날씨와 보존 결정에 대응할 여유를 두세요"},
{id:"weather",type:"list",items:["관람 시간 직후에 변경이 어려운 항공편이나 장거리 열차를 배치하지 마세요.","관람일 아침 둔황연구원과 공식 예약 계정을 확인하세요.","공식 변경·환불·시간 조정이 제시될 때를 위해 예약 계정과 결제 수단에 접근할 수 있어야 합니다.","2026년 6월 우천 폐쇄는 사막도 날씨에서 자유롭지 않음을 보여 줍니다. 7월 말의 별도 폐쇄 뒤에는 날짜가 명시된 재개방 공지가 나왔습니다. 폐쇄는 공지에 적힌 날짜와 조건에만 적용됩니다.","한 번의 중단 처리 방식을 미래 모든 상황에 적용하지 말고 해당 날짜의 공지를 따르세요."]},
{id:"guide",type:"paragraph",text:"자유여행이 실제 석굴마다 혼자 들어간다는 뜻은 아닙니다. 동굴 구간은 유적의 통제 해설과 보존 체계를 따릅니다. 개인 여행 가이드는 둔황의 넓은 맥락, 언어와 교통을 도울 수 있지만 보호 동굴을 마음대로 고르거나 배정을 우회할 수 없습니다."},
{id:"final-check",type:"list",items:["Ticket Booking 예약 내역이 모든 여권과 일치합니다.","결제 전에 일반 또는 응급 관람 방식을 이해했습니다.","절벽이 아닌 디지털전시센터를 첫 장소로 저장했습니다.","최소 30분 일찍 도착합니다.","날씨와 귀환 교통을 조정할 여유가 있습니다."]},
{id:"internal-links",type:"internal-links",title:"둔황 방문을 연결하세요",items:[{label:"중국 고속철 첫 이용 안내",href:"/ko/guides/china-high-speed-train-first-time-guide/",description:"정확한 역명을 쓰고 관람 뒤 현실적인 여유를 두세요."},{label:"중국 공휴일 여행",href:"/ko/guides/china-public-holidays-travel-calendar/",description:"수용량 제한 표를 왜 일찍 결정해야 하는지 이해하세요."},{label:"중국 일정이 너무 빠듯한가",href:"/ko/guides/is-your-china-itinerary-too-rushed/",description:"보존 통제 방문 하나가 전체 경로를 흔들지 않게 하세요."},{label:"중국 여행에 가이드가 필요할까",href:"/ko/guides/do-you-need-a-tour-guide-in-china/",description:"유적의 통제 해설과 개인 일정 지원을 구분하세요."}]},
{id:"consultation",type:"callout",title:"막고굴을 둔황 일정에 맞춰야 하나요?",body:"Homeground 여행 상담가가 날짜별 공식 절차를 확인하고 예약 전후 이동 여유를 확보할 수 있도록 도와드립니다. 여권 종류, 방문일, 이미 구입한 입장권 종류, 숙소와 고정 출발 시간을 알려 주세요.",tone:"neutral"},
{id:"sources",type:"sources",title:"확인한 공식·이미지 출처",items:[{label:"2026년 막고굴 관광 개방 공지",url:"https://www.dunhuangcaves.org/info/1020/7498.htm",publisher:"둔황연구원",reviewedAt:"2026-08-12"},{label:"2026년 6월 24일 우천 폐쇄 공지",url:"https://www.dunhuangcaves.org/info/1020/7731.htm",publisher:"둔황연구원",reviewedAt:"2026-08-12"},{label:"별도 기상 폐쇄 뒤 2026년 7월 30일 발표된 재개방 공지",url:"https://www.dunhuangcaves.org/info/1020/7811.htm",publisher:"둔황연구원",reviewedAt:"2026-08-12"},{label:"대표 이미지: eviltomthai, CC BY 2.0; 자르기·변환",url:"https://commons.wikimedia.org/wiki/File:Mogao_Caves_Exterior_And_Chambers.jpeg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}]}
]};export default body;
