import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body: StructuredPageBody = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "answer-first",
      type: "lead",
      text: "Treat the booking as three connected decisions: the exact Zhangjiajie National Forest Park product, the gate and time for first entry, and the in-park transport chain. For most travellers sleeping in Wulingyuan, East Gate is the sensible first hypothesis; South Gate fits a Golden Whip Stream or Huangshi Village start; West Gate fits a deliberate Yangjiajie start. North Gate and Zimugang can be useful, but only when the live ticket, road access and return transport are confirmed. Buy from the current official channel, enter the passport exactly, and never assume that the base admission includes every cableway, elevator or sightseeing train.",
    },
    {
      id: "canonical-boundary",
      type: "callout",
      title: "What this guide covers",
      body: "Use it to check ticket combinations, recover from a passport-booking failure, record the first-entry gate and time, read the displayed validity, distinguish the five gates, and connect scenic shuttles with Bailong Elevator and the Tianzi Mountain, Yangjiajie and Huangshi Village cableways. For a two-, three- or four-day itinerary, hotel-base choice, Tianmen Mountain A/B/C routes, or a Glass Bridge comparison, use the separate guides linked below.",
      tone: "neutral",
    },
    {
      id: "identity-heading",
      type: "heading",
      level: 2,
      text: "Make sure the ticket is for the right Zhangjiajie attraction",
    },
    {
      id: "identity-table",
      type: "table",
      caption: "Similar names do not share one ticket or entrance",
      columns: ["Place on the booking", "What it is", "Do not transfer from it"],
      rows: [
        ["张家界国家森林公园 / 武陵源核心景区", "The multi-gate sandstone-forest park covered by this guide", "Do not assume its ticket enters Tianmen Mountain or the Grand Canyon."],
        ["天门山国家森林公园", "A separate mountain attraction reached from Zhangjiajie city", "Its A/B/C route labels, cableway and entry appointment are separate owners."],
        ["张家界大峡谷 / 玻璃桥", "A separate Grand Canyon and Glass Bridge attraction", "Its ticket and time slot are not a Forest Park gate reservation."],
        ["黄龙洞 or 宝峰湖", "Separate Wulingyuan-area attractions", "Nearby location does not put them inside the Forest Park admission."],
      ],
    },
    {
      id: "ticket-heading",
      type: "heading",
      level: 2,
      text: "Read the ticket as a stack, not one all-inclusive pass",
    },
    {
      id: "ticket-table",
      type: "table",
      caption: "What to locate on the live product page before paying",
      columns: ["Layer", "What official material establishes", "What the current order must prove"],
      rows: [
        ["Core scenic-area admission", "The current official ticket page reviewed on 20 August 2026 lists a RMB 165 admission product, plus optional RMB 3 insurance, valid for four consecutive days and excluding eco-bus, cableways and elevators", "Exact attraction name, visit date, eligible traveller, first gate/time and displayed validity"],
        ["Eco/sightseeing shuttles", "The same current page lists a separate RMB 236 admission-plus-eco-bus product, plus optional RMB 3 insurance, also valid for four consecutive days; cableways and elevators remain excluded", "Which shuttle segments operate on the visit date and whether the selected product actually includes them"],
        ["Three cableways and one elevator", "The 2023 framework named Tianzi Mountain, Huangshi Village and Yangjiajie cableways plus Bailong Elevator as separately purchasable or combinable transport", "Direction, number of rides, validity and whether each desired segment is actually in the product"],
        ["Ten-Mile Gallery sightseeing train", "It is an in-park transport option but was not one of the ‘three cableways and one elevator’ named in that framework", "Whether it is sold separately, its operating status and the correct boarding point"],
        ["Discount or free-admission category", "Zhangjiajie applies documented preferential categories and requires valid proof", "Whether a foreign document is accepted for the exact category and whether transport charges remain payable"],
      ],
    },
    {
      id: "price-warning",
      type: "callout",
      title: "Use the current official product, not an old price screenshot",
      body: "As reviewed on 20 August 2026, the official page separates RMB 165 admission from RMB 236 admission plus eco-bus; optional RMB 3 insurance is listed for each, and neither product includes cableways or elevators. Prices, products and operating rules can change. Use the amount, inclusions, refund rule and validity shown in the live official order at payment, and save that product page with the order.",
      tone: "warning",
    },
    {
      id: "validity-heading",
      type: "heading",
      level: 2,
      text: "Gate, time and validity are separate fields",
    },
    {
      id: "validity-list",
      type: "list",
      ordered: true,
      items: [
        "Copy the visit date and the named first check-in. Official visitor guidance identifies timed reservations at different check-ins; a generic ‘Zhangjiajie ticket’ screenshot is not enough.",
        "Copy the first-entry period exactly and plan the hotel departure around the named gate, not around the city name.",
        "The current official admission-only and admission-plus-eco-bus products both display four consecutive days of validity. Copy the exact dates from your order, then confirm later-entry gates, time reservations and each separate transport product rather than treating multi-day validity as unrestricted access.",
        "Check whether later entries may use another gate and whether another time reservation is required. Do not infer unlimited gate changes from multi-day validity.",
        "Check the last usable date and the treatment of weather closure, unused rides, refunds and rescheduling before payment.",
      ],
    },
    {
      id: "record-heading",
      type: "heading",
      level: 2,
      text: "Keep the six booking records staff may need to check",
    },
    {
      id: "record-table",
      type: "table",
      caption: "The six records to keep together",
      columns: ["Record", "Why it matters", "Offline evidence"],
      rows: [
        ["Exact attraction and product name", "Separates the Forest Park from Tianmen Mountain and the Grand Canyon", "Full product page, not only a payment receipt"],
        ["Traveller name and document number", "Admission and concessions may be identity-bound", "Original passport plus order detail with most digits protected in ordinary sharing"],
        ["Visit date, first gate and time", "Controls the first physical check-in", "Chinese gate name, map pin and appointment screen"],
        ["Admission validity", "Determines whether a later park day is covered", "The live product rule saved at purchase"],
        ["Transport inclusions and ride count", "A base ticket, a single ride and a multi-ride bundle are not interchangeable", "Named cableway/elevator products with direction or count"],
        ["Refund, change and closure terms", "Weather or capacity can break the plan", "Current rule and official support contact"],
      ],
    },
    {
      id: "passport-heading",
      type: "heading",
      level: 2,
      text: "Passport booking: use a controlled fallback",
    },
    {
      id: "passport-steps",
      type: "list",
      ordered: true,
      items: [
        "Open the scenic-area administration's current ticket channel. The official 2023 visitor page named ‘张家界一机游’; confirm that it remains the instructed route before entering passport data, and avoid search advertisements that imitate a ticket desk.",
        "Select passport or the exact foreign-document option offered. Enter the name and number exactly as the platform labels require; do not invent a Chinese ID number.",
        "If verification fails, save the error, time, selected product and partially redacted document type. Do not keep creating accounts or changing the name format blindly.",
        "Contact the selected gate's official ticket-consultation number or the scenic-area service desk and ask which current official channel handles that passport. The gate numbers listed in the official Hunan visitor page are a verification route, not a promise of English service or ticket inventory.",
        "If staff direct you to in-person handling, ask whether inventory can be held and what original document is required. Do not assume a gate purchase will remain available on a capacity-controlled day.",
        "Bring the original passport used in the order, the complete order record and the payment proof. A photograph of the passport may not replace the original document at check-in.",
      ],
    },
    {
      id: "gate-heading",
      type: "heading",
      level: 2,
      text: "Choose the first entrance from your first planned area",
    },
    {
      id: "gate-table",
      type: "table",
      caption: "The five official check-ins and the decision each one serves",
      columns: ["Gate identity", "Useful starting case", "Main risk to verify"],
      rows: [
        ["East Gate · 武陵源标志门 / 吴家峪门票站", "A Wulingyuan hotel and a route beginning through the eastern shuttle network toward Bailong Elevator, Yuanjiajie or Ten-Mile Gallery", "Confirm the first shuttle/vertical transport sequence; ‘East’ is a base default, not proof that every desired node is direct."],
        ["South Gate · 森林公园门票站", "A deliberate start at Golden Whip Stream or Huangshi Village", "A route finishing on the high eastern side can leave a long return problem if the exit and luggage plan are not designed."],
        ["West Gate · 杨家界门票站", "A deliberate Yangjiajie start, often linked with the Yangjiajie cableway", "Verify road access, cableway operation and how the route returns to the selected hotel."],
        ["North Gate · 天子山门票站", "A confirmed high-side Tianzi Mountain start with suitable road transport", "Do not confuse it with Tianmen Mountain; confirm arrival and end-of-day transport before using this less forgiving gate."],
        ["Zimugang · 梓木岗门票站", "A route whose current official map and shuttle operation specifically use this check-in", "English sources differ between ‘Central’ and ‘southeast’; use the Chinese name and an exact pin, then confirm live connections."],
      ],
    },
    {
      id: "gate-default",
      type: "callout",
      title: "If the booking only says ‘main entrance’, stop and clarify",
      body: "There is no useful transport instruction in that phrase. Ask for the Chinese gate name, the appointment time, a map pin and the first shuttle or walking node. A Wulingyuan hotel normally makes East Gate the starting hypothesis; it does not convert every route into an East Gate route.",
      tone: "decision",
    },
    {
      id: "transport-heading",
      type: "heading",
      level: 2,
      text: "Understand what each in-park transport actually connects",
    },
    {
      id: "transport-table",
      type: "table",
      caption: "Horizontal transfer, vertical transfer and walking are different jobs",
      columns: ["Transport or path", "Job in the park", "What it does not solve"],
      rows: [
        ["Scenic eco/sightseeing shuttle", "Connects operating road nodes inside the scenic area", "It does not necessarily run directly between any two attractions or replace a closed vertical lift."],
        ["Bailong Elevator · 百龙天梯", "A major vertical link between the lower eastern network and the Yuanjiajie plateau area", "Its ticket does not choose the gate, guarantee queue time or carry you to every viewpoint."],
        ["Tianzi Mountain Cableway · 天子山索道", "A vertical connection for the Tianzi Mountain side", "It is not Tianmen Mountain's cableway and does not by itself solve the hotel transfer."],
        ["Yangjiajie Cableway · 杨家界索道", "A vertical link serving the Yangjiajie side", "It does not make West Gate practical without confirmed road access and a return plan."],
        ["Huangshi Village Cableway · 黄石寨索道", "A vertical option for Huangshi Village near the South Gate side", "It does not connect directly to Yuanjiajie or replace the Golden Whip Stream walking decision."],
        ["Ten-Mile Gallery train · 十里画廊观光电车", "An optional ride along the Ten-Mile Gallery corridor", "It is not included merely because a product mentions the three cableways and one elevator."],
        ["Walking trails", "Connect viewpoints and valleys that vehicles may not serve", "A map line does not prove current opening, surface, stair count or suitability for every traveller."],
      ],
    },
    {
      id: "chain-heading",
      type: "heading",
      level: 2,
      text: "Write the route as a chain before buying transport add-ons",
    },
    {
      id: "chain-examples",
      type: "comparison",
      title: "Four starting chains—not complete itineraries",
      columns: [
        { heading: "East Gate to a high plateau", items: ["East Gate appointment", "Operating scenic shuttle node", "Bailong Elevator or another confirmed vertical route", "Plateau shuttle/walk", "Named exit and return transport"] },
        { heading: "South Gate valley start", items: ["South Gate appointment", "Golden Whip Stream or Huangshi Village branch", "Walking or Huangshi cableway decision", "Confirmed cross-park or same-gate return", "Luggage and hotel handoff"] },
        { heading: "West Gate Yangjiajie start", items: ["West Gate appointment", "Operating shuttle", "Yangjiajie cableway or walking alternative", "High-area connection", "Confirmed hotel-side return"] },
        { heading: "North Gate high start", items: ["North Gate appointment", "Confirmed road arrival", "Tianzi Mountain shuttle/walk sequence", "Vertical descent or high-side exit", "End-of-day vehicle plan"] },
      ],
    },
    {
      id: "route-boundary",
      type: "callout",
      title: "A chain can begin at one gate and end near another—but do not improvise it",
      body: "Multi-gate geography makes one-way days possible, but shuttle suspensions, lift closures, weather, queues and last departures can break the return. Keep the named exit, luggage location and fallback vehicle in the plan. The separate Zhangjiajie itinerary owns how to distribute these chains across two, three or four days.",
      tone: "warning",
    },
    {
      id: "mobility-heading",
      type: "heading",
      level: 2,
      text: "Transport does not make the park step-free",
    },
    {
      id: "mobility-copy",
      type: "paragraph",
      text: "Cableways, the elevator, shuttles and the sightseeing train can remove particular climbs or distances, but transfers can still include stairs, steep paths, queue standing and gaps between stops and viewpoints. Ask the scenic-area service desk about the exact gate-to-attraction chain for a wheelchair, walking aid, young child or limited endurance. A generic ‘elevator included’ label is not an accessibility guarantee.",
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Recovery when the purchase or route breaks",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Protect admission first; simplify the route second",
      columns: ["Failure", "Immediate action", "Do not do"],
      rows: [
        ["Passport is not accepted online", "Save the official error and contact the selected gate/service desk for the current foreign-document route", "Do not use a false Chinese ID or pay an unverified person to ‘bind’ the passport."],
        ["Order has the wrong gate or time", "Use the official change/refund process before the deadline and recheck inventory", "Do not arrive at another gate expecting staff to rewrite the appointment."],
        ["A cableway or elevator is suspended", "Ask for the current official alternative, shorten the high-area plan and preserve a safe exit", "Do not follow an unofficial closed trail or assume another lift accepts the same ride product."],
        ["Heavy rain, wind, ice or capacity control changes operations", "Follow the scenic-area notice and staff instructions; keep the hotel day flexible", "Do not rely on an old opening-hours screenshot or pressure a driver to reach a closed gate."],
        ["You entered from the wrong side for stored luggage", "Stop adding attractions and confirm the last safe route to the bag and hotel", "Do not assume a late cross-park shuttle or cableway will wait."],
        ["Phone, QR or payment record fails at the gate", "Present the original passport and full official order record, then use the accountable service desk", "Do not expose the full passport or payment screen in a public chat."],
      ],
    },
    {
      id: "weather-warning",
      type: "callout",
      title: "Recheck after weather, not only before purchase",
      body: "The park has suspended and reopened after heavy rain, and official 2026 reporting still describes active optimization of reservations and transport capacity. Check the scenic-area notice the evening before and again before leaving the hotel. A valid admission order does not prove that every path, shuttle, cableway or elevator operates that day.",
      tone: "warning",
    },
    {
      id: "final-heading",
      type: "heading",
      level: 2,
      text: "Final booking checklist",
    },
    {
      id: "final-list",
      type: "list",
      items: [
        "The product says Zhangjiajie National Forest Park/Wulingyuan core scenic area, not Tianmen Mountain or the Grand Canyon.",
        "Every traveller's passport identity and any concession evidence match the order.",
        "The first gate is written in Chinese, has an exact pin and matches the appointment time and hotel departure.",
        "The live order shows admission validity, transport inclusions, ride count/direction and change/refund terms.",
        "The route chain distinguishes shuttle, vertical transport and walking, and names the planned exit.",
        "Original passports, full order evidence and official support contacts are available offline.",
        "Weather and live operations will be checked again before leaving the hotel.",
      ],
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue planning without mixing up separate decisions",
      items: [
        { label: "Compare the 4-day forest-first fixed private route", href: "/tours/zhangjiajie-forest-4-day-private-tour/", description: "Use the north gate for high peaks, the east gate for valley walks and one villa for all three nights, without cable cars or elevators." },
        { label: "Compare the classic 4-day private tour", href: "/tours/zhangjiajie-4-day-private-tour/", description: "Choose the broader route with Bailong Elevator, the Glass Bridge and Tianmen Mountain." },
        { label: "How many days in Zhangjiajie?", href: "/guides/zhangjiajie-itinerary/", description: "Use the itinerary owner to distribute park chains across the trip." },
        { label: "Stay in Zhangjiajie city or Wulingyuan?", href: "/guides/zhangjiajie-city-or-wulingyuan-hotel-base/", description: "Choose the hotel base separately from the park transaction." },
        { label: "Zhangjiajie Glass Bridge or mountain skywalk?", href: "/guides/zhangjiajie-glass-bridge-vs-skywalk/", description: "Keep the separate Grand Canyon and mountain attractions distinct." },
        { label: "Beijing to Zhangjiajie transport", href: "/guides/beijing-zhangjiajie-shanghai-transport/", description: "Plan the intercity arrival before the gate transfer." },
        { label: "Choose a Zhangjiajie night show", href: "/guides/best-zhangjiajie-night-show/", description: "Add an evening only after the park exit and hotel return are realistic." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources and image credit",
      items: [
        { label: "Zhangjiajie National Forest Park reservation, five check-ins and official service numbers", url: "https://www.enghunan.gov.cn/hneng/SP/sp2023/2023MayDay/202304/t20230426_29324679.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "Official Wulingyuan transport guide identifying five entrances and attraction connections", url: "https://whhlyt.hunan.gov.cn/whhlyt/wldh2022jt/202208/t20220823_27716245.html", publisher: "Hunan Provincial Department of Culture and Tourism", reviewedAt: "2026-08-20" },
        { label: "Current Wulingyuan admission, eco-bus products, validity and five entrance identities", url: "https://www.hnzjj.com/index.php/Ticket/show/2.html", publisher: "Wulingyuan Scenic Area official website", reviewedAt: "2026-08-20" },
        { label: "Hunan government-priced catalogue: Wulingyuan core admission and four-day validity", url: "https://fgw.hunan.gov.cn/fgw/xxgk_70899/gzdtf/gzdt/202507/t20250724_33748630.html", publisher: "Hunan Provincial Development and Reform Commission", reviewedAt: "2026-08-20" },
        { label: "Wulingyuan one-ticket framework for admission, eco-bus, three cableways and one elevator", url: "https://www.hunan.gov.cn/hnszf/hnyw/szdt/202312/t20231202_32455306.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "Advance reservation and weather-closure reminder after the park's 2025 reopening", url: "https://enghunan.gov.cn/hneng/News/Localnews/202506/t20250623_33717855.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "Inbound visitor services, staggered entry and self-service ticketing", url: "https://enghunan.gov.cn/hneng/News/Localnews/202508/t20250815_33773650.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "2026 reservation-system and in-park transport-capacity update", url: "https://www.enghunan.gov.cn/hneng/News/Localnews/202605/t20260523_33984056.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "Zhangjiajie scenic-area preferential ticket policy and document requirement", url: "https://enghunan.gov.cn/hneng/News/Localnews/202404/t20240425_33285051.html", publisher: "Hunan Provincial Government", reviewedAt: "2026-08-20" },
        { label: "Hero: Zhangjiajie National Forest Park — Kuruman (CC BY 2.0); resized and cropped by Homeground", url: "https://commons.wikimedia.org/wiki/File:Zhangjiajie_National_Forest_Park.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-20" },
        { label: "Hero photograph licence: CC BY 2.0", url: "https://creativecommons.org/licenses/by/2.0/", publisher: "Creative Commons", reviewedAt: "2026-08-20" },
      ],
    },
  ],
};

export default body;
