import type { HomegroundLocale } from "./homegroundI18n";

/** Words for the desktop contact card; loaded with the card, not on every page. */
export const contactCardCopy = {
  en: {
    title: "Talk to a China trip planner",
    close: "Close",
    chinaTime: "China time",
    tourLabel: "Your itinerary",
    guideLabel: "About this guide",
    scanTitle: "Scan to chat on your phone",
    scanSteps: [
      "Point your phone’s camera at the code.",
      "WhatsApp opens with the message ready to send.",
    ],
    qrLabel: "QR code that opens a WhatsApp chat with Homeground",
    numberLabel: "WhatsApp",
    copy: "Copy",
    copied: "Copied",
    copyNumber: "Copy the WhatsApp number",
    copyEmail: "Copy the email address",
    useHere: "Use WhatsApp on this computer",
    or: "or",
    replyFrom: "We reply from",
    openMailApp: "Open your email app",
    tabsLabel: "Ways to reach us",
    tabWhatsApp: "WhatsApp",
    tabEmail: "Email",
    tabMessenger: "Messenger",
    messengerScanTitle: "Scan to chat on Messenger",
    messengerSteps: ["Point your phone’s camera at the code.", "Messenger opens a chat with us."],
    messengerQrLabel: "QR code that opens Homeground on Messenger",
  },
  zh: {
    title: "联系中国旅行规划师",
    close: "关闭",
    chinaTime: "北京时间",
    tourLabel: "你选择的行程",
    guideLabel: "你正在看的攻略",
    scanTitle: "用手机扫码聊天",
    scanSteps: [
      "用手机相机对准二维码。",
      "WhatsApp 会打开对话，消息已经写好。",
    ],
    qrLabel: "扫码打开和 Homeground 的 WhatsApp 对话",
    numberLabel: "WhatsApp",
    copy: "复制",
    copied: "已复制",
    copyNumber: "复制 WhatsApp 号码",
    copyEmail: "复制邮箱地址",
    useHere: "在这台电脑上用 WhatsApp",
    or: "或",
    replyFrom: "回复邮箱",
    openMailApp: "用邮件应用发送",
    tabsLabel: "联系我们的方式",
    tabWhatsApp: "WhatsApp",
    tabEmail: "邮箱",
    tabMessenger: "Messenger",
    messengerScanTitle: "用手机扫码，在 Messenger 聊",
    messengerSteps: ["用手机相机对准二维码。", "Messenger 会打开和我们的对话。"],
    messengerQrLabel: "扫码在 Messenger 打开 Homeground",
  },
  ko: {
    title: "중국 여행 플래너와 상담하기",
    close: "닫기",
    chinaTime: "중국 시간",
    tourLabel: "선택하신 일정",
    guideLabel: "읽고 있는 가이드",
    scanTitle: "휴대폰으로 스캔해 대화하기",
    scanSteps: [
      "휴대폰 카메라로 코드를 비춰 주세요.",
      "보낼 메시지가 입력된 채로 WhatsApp이 열립니다.",
    ],
    qrLabel: "Homeground와의 WhatsApp 대화를 여는 QR 코드",
    numberLabel: "WhatsApp",
    copy: "복사",
    copied: "복사됨",
    copyNumber: "WhatsApp 번호 복사",
    copyEmail: "이메일 주소 복사",
    useHere: "이 컴퓨터에서 WhatsApp 사용하기",
    or: "또는",
    replyFrom: "답장 주소",
    openMailApp: "메일 앱으로 보내기",
    tabsLabel: "연락 방법",
    tabWhatsApp: "WhatsApp",
    tabEmail: "이메일",
    tabMessenger: "Messenger",
    messengerScanTitle: "휴대폰으로 스캔해 Messenger로 대화하기",
    messengerSteps: ["휴대폰 카메라로 코드를 비춰 주세요.", "Messenger에서 저희와의 대화가 열립니다."],
    messengerQrLabel: "Messenger에서 Homeground를 여는 QR 코드",
  },
} as const satisfies Record<HomegroundLocale, Record<string, string | readonly string[]>>;
