// Plain-<img> counterpart of lib/imageLoader.ts. Rasters under /images/ and
// /product-previews/ have .w640/.w1024/.w1280.webp siblings generated by
// tools/generate-image-variants.mjs (never wider than the original), so a card
// shown at ~400 CSS px no longer has to download a 1600px original.
const rasterPattern = /^\/(?:images|product-previews)\/.+\.(webp|jpe?g|png)$/i;
const variantPattern = /\.w(640|1024|1280)\.webp$/i;
const variantWidths = [640, 1024, 1280] as const;

/** srcset for a local raster of known intrinsic width, or undefined when no smaller variant exists. */
export function generatedImageSrcSet(src: string, width: number): string | undefined {
  if (!rasterPattern.test(src) || variantPattern.test(src)) return undefined;
  const variants = variantWidths
    .filter((variantWidth) => variantWidth < width)
    .map(
      (variantWidth) =>
        `${src.replace(/\.(webp|jpe?g|png)$/i, `.w${variantWidth}.webp`)} ${variantWidth}w`,
    );
  return variants.length > 0 ? [...variants, `${src} ${width}w`].join(", ") : undefined;
}
