// Generated by tools/slice-serif-sc-font.mjs from tools/fonts/homeground-serif-sc.woff2
// and tools/fonts/homeground-serif-sc-slices.json; do not edit.
export const homegroundSerifScPrimaryFontUrl = "/fonts/homeground-serif-sc-00.986cac7a.woff2";
export const homegroundSerifScSlicesStylesheetUrl = "/fonts/homeground-serif-sc-slices.20acd963.css";
