import type { PrivateTourPhotoCredit } from "./privateTourPhotoCredits";

const credit = (
  en: string,
  zh: string,
  ko: string,
  author: string,
  sourceUrl: string,
  licenseLabel: string,
  licenseUrl: string,
): PrivateTourPhotoCredit => ({
  subject: { en, zh, ko },
  author,
  sourceUrl,
  licenseLabel,
  licenseUrl,
});

const ccBy2 = "https://creativecommons.org/licenses/by/2.0/";
const ccBySa1 = "https://creativecommons.org/licenses/by-sa/1.0/";
const ccBySa25 = "https://creativecommons.org/licenses/by-sa/2.5/";
const ccBySa3 = "https://creativecommons.org/licenses/by-sa/3.0/";
const ccBySa3Igo = "https://creativecommons.org/licenses/by-sa/3.0/igo/";
const ccBySa4 = "https://creativecommons.org/licenses/by-sa/4.0/";
const cc0 = "https://creativecommons.org/publicdomain/zero/1.0/";
const publicDomain = "https://creativecommons.org/publicdomain/mark/1.0/";

export const privateTourExpansionPhotoCreditsBySlug: Readonly<
  Record<string, readonly PrivateTourPhotoCredit[]>
> = Object.freeze({
  "chengdu-jiuzhaigou-huanglong-6-day-private-tour": [
    credit(
      "Five Flower Lake, Jiuzhaigou",
      "九寨沟五花海",
      "주자이거우 오화해",
      "Chensiyuan",
      "https://commons.wikimedia.org/wiki/File:1_jiuzhaigou_valley_wu_hua_hai_2011b.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Chengdu Research Base of Giant Panda Breeding",
      "成都大熊猫繁育研究基地",
      "청두 자이언트판다 번식연구기지",
      "CEphoto, Uwe Aranas",
      "https://commons.wikimedia.org/wiki/File:Chengdu_Sichuan_China_Panda-breeding-and-research-center-02.jpg",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
    credit(
      "Multicolored ponds, Huanglong",
      "黄龙五彩池群",
      "황룽 오채지",
      "CEphoto, Uwe Aranas",
      "https://commons.wikimedia.org/wiki/File:Huanglong_Sichuan_China_Multicolored-ponds-02.jpg",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
  ],
  "kunming-dali-lijiang-8-day-private-tour": [
    credit(
      "Lijiang Old Town rooftops",
      "丽江古城屋顶",
      "리장고성 지붕 풍경",
      "CEphoto, Uwe Aranas",
      "https://commons.wikimedia.org/wiki/File:Lijiang_Yunnan_Old-town-03.jpg",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
    credit(
      "Erhai Lake, Dali",
      "大理洱海",
      "다리 얼하이 호수",
      "Mx. Granger",
      "https://commons.wikimedia.org/wiki/File:Tree_in_front_of_Erhai_Lake.jpg",
      "CC0 1.0",
      cc0,
    ),
    credit(
      "South Gate of Dali Old Town",
      "大理古城南门",
      "다리고성 남문",
      "Kcx36",
      "https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E7%90%86%E5%8F%A4%E5%9F%8E%E5%8D%97%E9%97%A8_01.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
  "guizhou-huangguoshu-libo-miao-7-day-private-tour": [
    credit(
      "Xijiang Miao Village",
      "西江千户苗寨",
      "시장 먀오족 마을",
      "SONG1907",
      "https://commons.wikimedia.org/wiki/File:Xijiang_Miao_Village.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Huangguoshu Waterfall",
      "黄果树瀑布",
      "황궈수 폭포",
      "Dounai",
      "https://commons.wikimedia.org/wiki/File:Huangguoshu_Waterfall_2.jpg",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
    credit(
      "Xiaoqikong ancient bridge, Libo",
      "荔波小七孔古桥",
      "리보 소칠공 고교",
      "Nyx Ning",
      "https://commons.wikimedia.org/wiki/File:%E8%8D%94%E6%B3%A2-%E5%B0%8F%E4%B8%83%E5%AD%94%E6%A1%A5_-_panoramio.jpg",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
  ],
  "xiamen-tulou-quanzhou-6-day-private-tour": [
    credit(
      "Gulangyu, Xiamen",
      "厦门鼓浪屿",
      "샤먼 구랑위",
      "Jakob Montrasio",
      "https://commons.wikimedia.org/wiki/File:Gulangyu.jpg",
      "CC BY 2.0",
      ccBy2,
    ),
    credit(
      "Tianluokeng Tulou Cluster",
      "南靖田螺坑土楼群",
      "난징 톈뤄컹 토루군",
      "rheins",
      "https://commons.wikimedia.org/wiki/File:%E7%94%B0%E8%9E%BA%E5%9D%91%E5%9C%9F%E6%A5%BC%E7%BE%A4_-_Tianluokeng_Tulou_Cluster_-_2010.07_-_panoramio.jpg",
      "CC BY 3.0",
      "https://creativecommons.org/licenses/by/3.0/",
    ),
    credit(
      "Twin pagodas of Kaiyuan Temple, Quanzhou",
      "泉州开元寺东西塔",
      "취안저우 카이위안사 동서탑",
      "Windmemories",
      "https://commons.wikimedia.org/wiki/File:20230129_Twin_pagodas_of_Kaiyuan_Temple.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
  "chaozhou-shantou-nanao-5-day-private-tour": [
    credit(
      "Guangji Bridge pontoon section, Chaozhou",
      "潮州广济桥浮桥段",
      "차오저우 광지교 부교 구간",
      "Akira CA",
      "https://commons.wikimedia.org/wiki/File:Chaozhou_Guangji_Bridge_20191211_2.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Changshanwei Lighthouse and Nan'ao Bridge",
      "南澳岛长山尾灯塔与南澳大桥",
      "난아오섬 창산웨이 등대와 난아오대교",
      "Windmemories",
      "https://commons.wikimedia.org/wiki/File:20230205_Changshanwei_Lighthouse_and_Nan%27ao_Bridge.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Xiaogongyuan historic district, Shantou",
      "汕头小公园开埠区",
      "산터우 샤오궁위안 개항지구",
      "Sgnpkd",
      "https://commons.wikimedia.org/wiki/File:Xiaogongyuan.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Paifang Street, Chaozhou",
      "潮州太平路牌坊街",
      "차오저우 파이팡제",
      "Windmemories",
      "https://commons.wikimedia.org/wiki/File:20230206_Taiping_Road,_Chaozhou.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
  "chengdu-chongqing-8-day-private-tour": [
    credit(
      "Hongya Cave at night, Chongqing",
      "重庆洪崖洞夜景",
      "충칭 훙야둥 야경",
      "Jonashtand",
      "https://commons.wikimedia.org/wiki/File:202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Giant panda at Chengdu Research Base",
      "成都大熊猫繁育研究基地的大熊猫",
      "청두 자이언트판다 번식연구기지의 자이언트판다",
      "Jimmyshjj",
      "https://commons.wikimedia.org/wiki/File:Chengdu_Research_Base_of_Giant_Panda_Breeding,_201907,_04.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Three Natural Bridges, Wulong",
      "武隆天生三桥景区",
      "우룽 천생삼교",
      "RoyalCathayan",
      "https://commons.wikimedia.org/wiki/File:Three_Natural_Bridges.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Leshan Giant Buddha",
      "乐山大佛全景",
      "러산대불 전경",
      "Ariel Steiner",
      "https://commons.wikimedia.org/wiki/File:Leshan_Buddha_Statue_View.JPG",
      "CC BY-SA 2.5",
      ccBySa25,
    ),
  ],
  "guangzhou-shunde-foshan-5-day-private-tour": [
    credit(
      "Canton Tower and Pearl River at night",
      "广州塔与珠江夜景",
      "광저우타워와 주장강 야경",
      "Daniel Lu（User:dllu）",
      "https://commons.wikimedia.org/wiki/File:Canton_Tower_at_night_Guangzhou_2024_dllu.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Chen Clan Ancestral Hall, Guangzhou",
      "广州陈家祠正立面",
      "광저우 천씨서원 정면",
      "Shujianyang",
      "https://commons.wikimedia.org/wiki/File:Chen_Clan_Ancestral_Hall_2025.06_02.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Foshan Ancestral Temple",
      "佛山祖庙",
      "포산 조묘",
      "钉钉",
      "https://commons.wikimedia.org/wiki/File:Foshan_Ancestral_Temple_2.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Bixi Cottage, Qinghui Garden",
      "顺德清晖园碧溪草堂",
      "순더 칭후이위안 비시초당",
      "古海岸遗址",
      "https://commons.wikimedia.org/wiki/File:Foshan_Shunde_Qinghui_Yuan_2024-05-11_16.12.39.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
  "huangshan-hongcun-huizhou-5-day-private-tour": [
    credit(
      "Mount Huangshan peaks",
      "黄山群峰",
      "황산 봉우리",
      "Francesco Bandarin",
      "https://commons.wikimedia.org/wiki/File:Mount_Huangshan-110978.jpg",
      "CC BY-SA 3.0 IGO",
      ccBySa3Igo,
    ),
    credit(
      "Hongcun entrance and waterscape",
      "宏村入口与水景",
      "홍춘 입구와 수경",
      "Ben Miller",
      "https://commons.wikimedia.org/wiki/File:Huangshan_11.jpg",
      "CC BY-SA 1.0",
      ccBySa1,
    ),
    credit(
      "Greeting Pine, Mount Huangshan",
      "黄山迎客松",
      "황산 영객송",
      "上传者 Immanuel Giel",
      "https://commons.wikimedia.org/wiki/File:Huangshan_Yingkesong.jpg",
      "Public domain",
      publicDomain,
    ),
  ],
  "jingdezhen-wuyuan-wangxian-6-day-private-tour": [
    credit(
      "Wangxian Valley at sunset",
      "望仙谷峡谷与灯笼步道",
      "왕셴구 협곡과 등롱 산책로",
      "茅野ふたば",
      "https://commons.wikimedia.org/wiki/File:Wangxiangu_Scenic_Area_-_25_(July_19,_2025).jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Jingdezhen Imperial Kiln Museum",
      "景德镇御窑博物馆",
      "징더전 어요박물관",
      "Zhu Pei",
      "https://commons.wikimedia.org/wiki/File:02-Jingdezhen_Imperial_Kiln_Museum.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Autumn sun drying at Huangling, Wuyuan",
      "婺源篁岭晒秋",
      "우위안 황링 쇄추",
      "Leungcwd",
      "https://commons.wikimedia.org/wiki/File:Autumn_sun_drying_at_Huangling.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
  "changbaishan-yanji-winter-6-day-private-tour": [
    credit(
      "Heaven Lake, Changbai Mountain",
      "长白山天池",
      "백두산 천지",
      "Wang65",
      "https://commons.wikimedia.org/wiki/File:Tianchi_Changbai.JPG",
      "CC BY-SA 3.0",
      ccBySa3,
    ),
    credit(
      "Yanji at night",
      "延吉夜景",
      "옌지 야경",
      "EditQ",
      "https://commons.wikimedia.org/wiki/File:Yanji_at_night.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
    credit(
      "Yanbian University popular wall, Yanji",
      "延边大学网红墙",
      "옌볜대학교 인기 벽거리",
      "Liuxingy",
      "https://commons.wikimedia.org/wiki/File:%E5%BB%B6%E5%90%89_%E5%BB%B6%E8%BE%B9%E5%A4%A7%E5%AD%A6%E7%BD%91%E7%BA%A2%E5%A2%99.jpg",
      "CC BY-SA 4.0",
      ccBySa4,
    ),
  ],
});
