// Generated by tools/generate-private-tour-inquiry-index.mjs from
// lib/privateTourProducts.ts (published, then preview products). Do not edit by hand: run
// `node --experimental-strip-types tools/generate-private-tour-inquiry-index.mjs`.
//
// Client code (tour contact panel, header) needs only these fields. Importing
// the full catalogue there would ship every tour's copy and FAQs to all pages.
import type { HomegroundLocale } from "./homegroundI18n";
// @ts-ignore Source-TypeScript tests require the explicit extension.
import type { PrivateTourPriceTier } from "./privateTourProducts.ts";

export interface PrivateTourInquiryIndexEntry {
  readonly slug: string;
  /** Unlisted, noindex preview product: en/zh/ko only, never Japanese. */
  readonly visibility?: "preview";
  readonly title: Readonly<Record<HomegroundLocale, string>> & { readonly ja?: string };
  readonly packages: readonly {
    readonly id: string;
    readonly prices: readonly { readonly travelers: PrivateTourPriceTier["travelers"] }[];
  }[];
}

export const privateTourInquiryIndex: readonly PrivateTourInquiryIndexEntry[] = [
  {
    slug: "shanghai-suzhou-hangzhou-6-day-private-tour",
    title: { en: "Shanghai, Suzhou & Hangzhou: 6-Day Private Tour", zh: "上海·苏州·杭州 6 天 5 晚私家团", ko: "상하이·쑤저우·항저우 6일 프라이빗 투어", ja: "上海・蘇州・杭州 6日間プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-pandas-sanxingdui-5-day-private-tour",
    title: { en: "Chengdu, Pandas & Sanxingdui: 5-Day Private Tour", zh: "成都·大熊猫·三星堆 5 天 4 晚私家团", ko: "청두·판다·싼싱두이 5일 프라이빗 투어", ja: "成都・パンダ・三星堆 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "xian-terracotta-warriors-5-day-private-tour",
    title: { en: "Xi'an & the Terracotta Warriors: 5-Day Private Tour", zh: "西安·兵马俑 5 天 4 晚私家团", ko: "시안·병마용 5일 프라이빗 투어", ja: "西安・兵馬俑 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chongqing-wulong-5-day-private-tour",
    title: { en: "Chongqing & Wulong: 5-Day Private Tour", zh: "重庆·武隆 5 天 4 晚私家团", ko: "충칭·우롱 5일 프라이빗 투어", ja: "重慶・武隆 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "guilin-yangshuo-5-day-private-tour",
    title: { en: "Guilin & Yangshuo: 5-Day Private Tour", zh: "桂林·阳朔 5 天 4 晚私家团", ko: "계림·양삭 5일 프라이빗 투어", ja: "桂林・陽朔 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "harbin-winter-5-day-private-tour",
    title: { en: "Harbin Ice & Snow: 5-Day Private Tour", zh: "哈尔滨冰雪 5 天 4 晚私家团", ko: "하얼빈 빙설 5일 프라이빗 투어", ja: "ハルビン氷雪 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided-winter", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "shanghai-suzhou-5-day-private-tour",
    title: { en: "Shanghai & Suzhou: 5-Day Private Tour", zh: "上海·苏州 5 天 4 晚私家团", ko: "상하이·쑤저우 5일 프라이빗 투어", ja: "上海・蘇州 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-highlights-5-day-private-tour",
    title: { en: "Beijing Highlights: 5-Day Private Tour", zh: "北京经典 5 天 4 晚私家团", ko: "베이징 핵심 5일 프라이빗 투어", ja: "北京の見どころ 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "english-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
      { id: "no-guide", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "zhangjiajie-forest-4-day-private-tour",
    title: { en: "Zhangjiajie Forest: 4-Day Fixed-Route Private Tour", zh: "张家界森林公园 4 天 3 晚固定路线私家团", ko: "장가계 국가삼림공원 4일 고정 코스 프라이빗 투어", ja: "張家界森林公園 4日間（3泊）固定ルートのプライベートツアー" },
    packages: [
      { id: "fixed-route-english-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "zhangjiajie-furong-fenghuang-7-day-private-tour",
    title: { en: "Zhangjiajie, Furong Town & Fenghuang: 7-Day Private Tour", zh: "张家界、芙蓉镇与凤凰 7 天 6 晚私家团", ko: "장가계, 부용진, 봉황 6박 7일 프라이빗 투어", ja: "張家界・芙蓉鎮・鳳凰 7日間（6泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-jiuzhaigou-huanglong-6-day-private-tour",
    title: { en: "Chengdu, Jiuzhaigou & Huanglong: 6-Day Private Tour", zh: "成都·九寨沟·黄龙 6 天 5 晚私家团", ko: "청두·구채구·황룡 6일 프라이빗 투어", ja: "成都・九寨溝・黄龍 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "kunming-dali-lijiang-8-day-private-tour",
    title: { en: "Yunnan 8-Day Private Tour: Kunming, Dali & Lijiang", zh: "昆明·大理·丽江 8 天 7 晚私家团", ko: "쿤밍·다리·리장 8일 프라이빗 투어", ja: "昆明・大理・麗江 8日間（7泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 6 }] },
    ],
  },
  {
    slug: "guizhou-huangguoshu-libo-miao-7-day-private-tour",
    title: { en: "Guiyang, Huangguoshu, Libo, Xijiang & Zhenyuan: 7-Day Private Tour", zh: "贵阳·黄果树·荔波·西江苗寨·镇远 7 天 6 晚私家团", ko: "구이양·황궈수·리보·시장·전위안 7일 프라이빗 투어", ja: "貴陽・黄果樹・荔波・西江・鎮遠 7日間（6泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "xiamen-tulou-quanzhou-6-day-private-tour",
    title: { en: "Xiamen, Fujian Tulou, Anxi & Quanzhou: 6-Day Private Tour", zh: "厦门·福建土楼·安溪·泉州 6 天 5 晚私家团", ko: "샤먼·푸젠 토루·안시·취안저우 6일 프라이빗 투어", ja: "厦門・福建土楼・安渓・泉州 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chaozhou-shantou-nanao-5-day-private-tour",
    title: { en: "Shantou, Nan'ao & Chaozhou: 5-Day Private Tour", zh: "汕头·南澳·潮州 5 天 4 晚私家团", ko: "산터우·난아오·차오저우 5일 프라이빗 투어", ja: "汕頭・南澳島・潮州 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-chongqing-8-day-private-tour",
    title: { en: "Chengdu, Leshan, Chongqing, Wulong & Dazu: 8-Day Private Tour", zh: "成都·乐山·重庆·武隆·大足 8 天 7 晚私家团", ko: "청두·낙산·충칭·우롱·대족 8일 프라이빗 투어", ja: "成都・楽山・重慶・武隆・大足 8日間（7泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "guangzhou-shunde-foshan-5-day-private-tour",
    title: { en: "Guangzhou, Shunde & Foshan: 5-Day Private Tour", zh: "广州·顺德·佛山 5 天 4 晚私家团", ko: "광저우·순더·포산 5일 프라이빗 투어", ja: "広州・順徳・仏山 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "huangshan-hongcun-huizhou-5-day-private-tour",
    title: { en: "Huangshan, Hongcun & Huizhou: 5-Day Private Tour", zh: "黄山·宏村·徽州 5 天 4 晚私家团", ko: "황산·홍춘·후이저우 5일 프라이빗 투어", ja: "黄山・宏村・徽州 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "jingdezhen-wuyuan-wangxian-6-day-private-tour",
    title: { en: "Jingdezhen, Wuyuan, Sanqingshan & Wangxian Valley: 6-Day Private Tour", zh: "景德镇·婺源·三清山·望仙谷 6 天 5 晚私家团", ko: "징더전·우위안·삼청산·왕셴구 6일 프라이빗 투어", ja: "景徳鎮・婺源・三清山・望仙谷 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "changbaishan-yanji-winter-6-day-private-tour",
    title: { en: "Changbaishan Resort, North Slope & Yanji: 6-Day Winter Private Tour", zh: "长白山度假区·北坡·延吉 6 天 5 晚冬季私家团", ko: "백두산(창바이산)·북파·연길 6일 겨울 프라이빗 투어", ja: "長白山リゾート・北坡・延吉 冬の6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided-winter", prices: [] },
    ],
  },
  {
    slug: "shanghai-disneyland-5-day-private-tour",
    title: { en: "Shanghai & Disneyland: 5-Day Private Tour", zh: "上海与迪士尼 5 天 4 晚私家团", ko: "상하이·디즈니랜드 5일 프라이빗 투어", ja: "上海・ディズニーランド 5日間（4泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "luoyang-dengfeng-kaifeng-6-day-private-tour",
    title: { en: "Luoyang, Dengfeng & Kaifeng: 6-Day Private Tour", zh: "洛阳·登封·开封 6 天 5 晚私家团", ko: "뤄양·덩펑·카이펑 6일 프라이빗 투어", ja: "洛陽・登封・開封 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "datong-pingyao-6-day-private-tour",
    title: { en: "Datong & Pingyao: 6-Day Private Tour", zh: "大同·平遥 6 天 5 晚私家团", ko: "다퉁·핑야오 6일 프라이빗 투어", ja: "大同・平遥 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "zhangye-jiayuguan-dunhuang-7-day-private-tour",
    title: { en: "Zhangye, Jiayuguan & Dunhuang: 7-Day Private Tour", zh: "张掖·嘉峪关·敦煌 7 天 6 晚私家团", ko: "장예·자위관·둔황 7일 프라이빗 투어", ja: "張掖・嘉峪関・敦煌 7日間（6泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chongqing-yangtze-cruise-6-day-private-tour",
    title: { en: "Chongqing & Yangtze Three Gorges: 6-Day Private Tour", zh: "重庆与长江三峡游轮 6 天 5 晚私家团", ko: "충칭·장강삼협 크루즈 6일 프라이빗 투어", ja: "重慶と長江三峡 6日間プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "xinjiang-ili-sayram-8-day-private-tour",
    title: { en: "Ili, Sayram Lake & Nalati: 8-Day Private Tour", zh: "伊犁·赛里木湖·那拉提 8 天 7 晚私家团", ko: "이리·싸이리무호·나라티 8일 프라이빗 투어", ja: "伊犁・賽里木湖・那拉提 8日間（7泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "hulunbuir-7-day-private-tour",
    title: { en: "Hulunbuir Grassland & Forest: 7-Day Private Tour", zh: "呼伦贝尔草原与森林 7 天 6 晚私家团", ko: "후룬베이얼 초원·숲 7일 프라이빗 투어", ja: "フルンボイル（呼倫貝爾）草原・森林 7日間（6泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "kunming-jianshui-yuanyang-6-day-private-tour",
    title: { en: "Kunming, Jianshui & Yuanyang: 6-Day Private Tour", zh: "昆明·建水·元阳 6 天 5 晚私家团", ko: "쿤밍·젠수이·위안양 6일 프라이빗 투어", ja: "昆明・建水・元陽 6日間（5泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "shenzhen-family-tech-4-day-private-tour",
    title: { en: "Shenzhen Family Science & Technology: 4-Day Private Tour", zh: "深圳亲子科技 4 天 3 晚私家团", ko: "선전 가족 과학·기술 4일 프라이빗 투어", ja: "深圳・親子で楽しむ科学とテクノロジー 4日間（3泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-shanghai-12-day-private-tour",
    title: { en: "Beijing, Xi'an & Shanghai: 12-Day Private Tour", zh: "北京·西安·上海 12 天 11 晚私家团", ko: "베이징·시안·상하이 12일 프라이빗 투어", ja: "北京・西安・上海 12日間（11泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-chengdu-guilin-shanghai-14-day-private-tour",
    title: { en: "Beijing, Xi'an, Chengdu, Guilin & Shanghai: 14-Day Private Tour", zh: "北京·西安·成都·桂林·上海 14 天 13 晚私家团", ko: "베이징·시안·청두·계림·상하이 14일 프라이빗 투어", ja: "北京・西安・成都・桂林・上海 14日間（13泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-chengdu-guilin-shanghai-14-day-small-group-tour",
    title: { en: "Beijing, Xi'an, Chengdu, Guilin & Shanghai: 14-Day Small-Group Tour", zh: "北京·西安·成都·桂林·上海 14 天 13 晚小团", ko: "베이징·시안·청두·계림·상하이 14일 소규모 그룹 투어", ja: "北京・西安・成都・桂林・上海 14日間 少人数ツアー" },
    packages: [
      { id: "small-group-departure", prices: [{ travelers: 2 }] },
    ],
  },
  {
    slug: "beijing-xian-zhangjiajie-guilin-shanghai-14-day-private-tour",
    title: { en: "Beijing, Xi'an, Zhangjiajie, Guilin & Shanghai: 14-Day Private Tour", zh: "北京·西安·张家界·桂林·上海 14 天 13 晚私家团", ko: "베이징·시안·장가계·계림·상하이 14일 프라이빗 투어", ja: "北京・西安・張家界・桂林・上海 14日間（13泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-zhangjiajie-guilin-shanghai-14-day-small-group-tour",
    title: { en: "Beijing, Xi'an, Zhangjiajie, Guilin & Shanghai: 14-Day Small-Group Tour", zh: "北京·西安·张家界·桂林·上海 14 天 13 晚小团", ko: "베이징·시안·장가계·계림·상하이 14일 소규모 그룹 투어", ja: "北京・西安・張家界・桂林・上海 14日間 少人数ツアー" },
    packages: [
      { id: "small-group-departure", prices: [{ travelers: 2 }] },
    ],
  },
  {
    slug: "beijing-xian-chengdu-yangtze-cruise-shanghai-17-day-private-tour",
    title: { en: "Beijing, Xi'an, Chengdu, Yangtze Cruise & Shanghai: 17-Day Private Tour", zh: "北京·西安·成都·长江游轮·上海 17 天 16 晚私家团", ko: "베이징·시안·청두·장강 크루즈·상하이 17일 프라이빗 투어", ja: "北京・西安・成都・長江クルーズ・上海 17日間プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-chengdu-yangtze-cruise-shanghai-17-day-small-group-tour",
    title: { en: "Beijing, Xi'an, Chengdu, Yangtze Cruise & Shanghai: 17-Day Small-Group Tour", zh: "北京·西安·成都·长江游轮·上海 17 天 16 晚小团", ko: "베이징·시안·청두·장강 크루즈·상하이 17일 소규모 그룹 투어", ja: "北京・西安・成都・長江クルーズ・上海 17日間 少人数ツアー" },
    packages: [
      { id: "small-group-departure", prices: [{ travelers: 2 }] },
    ],
  },
  {
    slug: "beijing-xian-silk-road-15-day-private-tour",
    title: { en: "Beijing, Xi'an & the Silk Road: 15-Day Private Tour", zh: "北京·西安·丝绸之路 15 天 14 晚私家团", ko: "베이징·시안·실크로드 15일 프라이빗 투어", ja: "北京・西安・シルクロード 15日間（14泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-silk-road-15-day-small-group-tour",
    title: { en: "Beijing, Xi'an & the Silk Road: 15-Day Small-Group Tour", zh: "北京·西安·丝绸之路 15 天 14 晚小团", ko: "베이징·시안·실크로드 15일 소규모 그룹 투어", ja: "北京・西安・シルクロード 15日間 少人数ツアー" },
    packages: [
      { id: "small-group-departure", prices: [{ travelers: 2 }] },
    ],
  },
  {
    slug: "beijing-xian-yunnan-14-day-private-tour",
    title: { en: "Beijing, Xi'an & Yunnan: 14-Day Private Tour", zh: "北京·西安·云南 14 天 13 晚私家团", ko: "베이징·시안·윈난 14일 프라이빗 투어", ja: "北京・西安・雲南 14日間（13泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-huangshan-hangzhou-shanghai-14-day-private-tour",
    title: { en: "Beijing, Xi'an, Yellow Mountain, Hangzhou & Shanghai: 14-Day Private Tour", zh: "北京·西安·黄山·杭州·上海 14 天 13 晚私家团", ko: "베이징·시안·황산·항저우·상하이 14일 프라이빗 투어", ja: "北京・西安・黄山・杭州・上海 14日間（13泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "china-grand-tour-21-day-private-tour",
    title: { en: "Grand China with Zhangjiajie & the Yangtze: 21-Day Private Tour", zh: "中国全景：含张家界与长江游轮 21 天 20 晚私家团", ko: "장가계·장강 크루즈를 포함한 중국 일주 21일 프라이빗 투어", ja: "北京・西安・桂林・張家界・長江三峡・上海 21日間プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-guilin-shanghai-10-day-private-tour",
    title: { en: "Beijing, Xi'an, Guilin & Shanghai: 10-Day Private Tour", zh: "北京·西安·桂林·上海 10 天 9 晚私家团", ko: "베이징·시안·계림·상하이 10일 프라이빗 투어", ja: "北京・西安・桂林・上海 10日間（9泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-hangzhou-suzhou-shanghai-11-day-private-tour",
    title: { en: "Beijing, Hangzhou, Suzhou & Shanghai: 11-Day Private Tour", zh: "北京·杭州·苏州·上海 11 天 10 晚私家团", ko: "베이징·항저우·쑤저우·상하이 11일 프라이빗 투어", ja: "北京・杭州・蘇州・上海 11日間（10泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "shanghai-zhangjiajie-fenghuang-guilin-13-day-private-tour",
    title: { en: "Shanghai, Zhangjiajie, Fenghuang & Guilin: 13-Day Private Tour", zh: "上海·张家界·凤凰·桂林 13 天 12 晚私家团", ko: "상하이·장가계·봉황·계림 13일 프라이빗 투어", ja: "上海・張家界・鳳凰・桂林 13日間（12泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-shanghai-8-day-private-tour",
    title: { en: "Beijing, Xi'an & Shanghai: 8-Day Private Tour", zh: "北京·西安·上海 8 天 7 晚私家团", ko: "베이징·시안·상하이 8일 프라이빗 투어", ja: "北京・西安・上海 8日間（7泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-guilin-hong-kong-10-day-private-tour",
    title: { en: "Beijing, Xi'an, Guilin & Hong Kong: 10-Day Private Tour", zh: "北京·西安·桂林·香港 10 天 9 晚私家团", ko: "베이징·시안·계림·홍콩 10일 프라이빗 투어", ja: "北京・西安・桂林・香港 10日間（9泊）プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-yangtze-cruise-shanghai-12-day-private-tour",
    title: { en: "Beijing, Xi'an, Yangtze Cruise & Shanghai: 12-Day Private Tour", zh: "北京·西安·长江游轮·上海 12 天 11 晚私家团", ko: "베이징·시안·장강 크루즈·상하이 12일 프라이빗 투어", ja: "北京・西安・長江クルーズ・上海 12日間プライベートツアー" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "harbin-yabuli-snow-town-6-day-private-tour",
    title: { en: "Harbin, Yabuli & Snow Town: 6-Day Winter Private Tour", zh: "哈尔滨·亚布力·雪乡 6 天 5 晚冬季私家团", ko: "하얼빈·야부리·설향 6일 겨울 프라이빗 투어", ja: "ハルビン・亜布力・雪郷 6日間（5泊）冬季プライベートツアー" },
    packages: [
      { id: "low-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
      { id: "peak-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
    ],
  },
  {
    slug: "harbin-snow-town-changbaishan-yanji-8-day-private-tour",
    title: { en: "Harbin, Yabuli, Snow Town, Changbai Mountain & Yanji: 8-Day Winter Private Tour", zh: "哈尔滨·亚布力·雪乡·长白山·延吉 8 天 7 晚冬季私家团", ko: "하얼빈·야부리·설향·백두산·연길 8일 겨울 프라이빗 투어", ja: "ハルビン・亜布力・雪郷・長白山・延吉 8日間（7泊）冬季プライベートツアー" },
    packages: [
      { id: "low-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
      { id: "peak-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
    ],
  },
  {
    slug: "harbin-mohe-arctic-village-7-day-private-tour",
    title: { en: "Harbin, Mohe, Beihong & Arctic Village: 7-Day Winter Private Tour", zh: "哈尔滨·漠河·北红村·北极村 7 天 6 晚冬季私家团", ko: "하얼빈·모허·베이훙촌·북극촌 7일 겨울 프라이빗 투어", ja: "ハルビン・漠河・北紅村・北極村 7日間（6泊）冬季プライベートツアー" },
    packages: [
      { id: "low-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
      { id: "peak-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
    ],
  },
  {
    slug: "harbin-snow-town-mohe-9-day-private-tour",
    title: { en: "Harbin, Yabuli, Snow Town & Mohe: 9-Day Winter Private Tour", zh: "哈尔滨·亚布力·雪乡·漠河 9 天 8 晚冬季私家团", ko: "하얼빈·야부리·설향·모허 9일 겨울 프라이빗 투어", ja: "ハルビン・亜布力・雪郷・漠河 9日間（8泊）冬季プライベートツアー" },
    packages: [
      { id: "low-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
      { id: "peak-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
    ],
  },
  {
    slug: "yanji-changbaishan-wanda-6-day-private-tour",
    title: { en: "Yanji, Changbai Mountain & Wanda Resort: 6-Day Winter Private Tour", zh: "延吉·长白山·万达度假区 6 天 5 晚冬季私家团", ko: "연길·백두산·완다 리조트 6일 겨울 프라이빗 투어", ja: "延吉・長白山・ワンダリゾート 6日間（5泊）冬季プライベートツアー" },
    packages: [
      { id: "low-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
      { id: "peak-season", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }, { travelers: 8 }] },
    ],
  },
];
