// Generated by tools/generate-private-tour-inquiry-index.mjs from
// lib/privateTourProducts.ts. Do not edit by hand: run
// `node --experimental-strip-types tools/generate-private-tour-inquiry-index.mjs`.
//
// Client code (tour contact panel, header) needs only these fields. Importing
// the full catalogue there would ship every tour's copy and FAQs to all pages.
import type { HomegroundLocale } from "./homegroundI18n";
// @ts-ignore Source-TypeScript tests require the explicit extension.
import type { PrivateTourPriceTier } from "./privateTourProducts.ts";

export interface PrivateTourInquiryIndexEntry {
  readonly slug: string;
  readonly title: Readonly<Record<HomegroundLocale, string>>;
  readonly packages: readonly {
    readonly id: string;
    readonly prices: readonly { readonly travelers: PrivateTourPriceTier["travelers"] }[];
  }[];
}

export const privateTourInquiryIndex: readonly PrivateTourInquiryIndexEntry[] = [
  {
    slug: "shanghai-suzhou-hangzhou-6-day-private-tour",
    title: { en: "Shanghai, Suzhou & Hangzhou: 6-Day Private Tour", zh: "上海·苏州·杭州 6 天 5 晚私家团", ko: "상하이·쑤저우·항저우 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-pandas-sanxingdui-5-day-private-tour",
    title: { en: "Chengdu, Pandas & Sanxingdui: 5-Day Private Tour", zh: "成都·大熊猫·三星堆 5 天 4 晚私家团", ko: "청두·판다·싼싱두이 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "xian-terracotta-warriors-5-day-private-tour",
    title: { en: "Xi'an & the Terracotta Warriors: 5-Day Private Tour", zh: "西安·兵马俑 5 天 4 晚私家团", ko: "시안·병마용 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chongqing-wulong-5-day-private-tour",
    title: { en: "Chongqing & Wulong: 5-Day Private Tour", zh: "重庆·武隆 5 天 4 晚私家团", ko: "충칭·우룽 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "guilin-yangshuo-5-day-private-tour",
    title: { en: "Guilin & Yangshuo: 5-Day Private Tour", zh: "桂林·阳朔 5 天 4 晚私家团", ko: "구이린·양숴 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "harbin-winter-5-day-private-tour",
    title: { en: "Harbin Ice & Snow: 5-Day Private Tour", zh: "哈尔滨冰雪 5 天 4 晚私家团", ko: "하얼빈 빙설 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided-winter", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "shanghai-suzhou-5-day-private-tour",
    title: { en: "Shanghai & Suzhou: 5-Day Private Tour", zh: "上海·苏州 5 天 4 晚私家团", ko: "상하이·쑤저우 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-highlights-5-day-private-tour",
    title: { en: "Beijing Highlights: 5-Day Private Tour", zh: "北京经典 5 天 4 晚私家团", ko: "베이징 핵심 5일 프라이빗 투어" },
    packages: [
      { id: "english-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
      { id: "no-guide", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "zhangjiajie-forest-4-day-private-tour",
    title: { en: "Zhangjiajie Forest: 4-Day Fixed-Route Private Tour", zh: "张家界森林公园 4 天 3 晚固定路线私家团", ko: "장가계 국립삼림공원 4일 고정 코스 프라이빗 투어" },
    packages: [
      { id: "fixed-route-english-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "zhangjiajie-furong-fenghuang-7-day-private-tour",
    title: { en: "Zhangjiajie, Furong Town & Fenghuang: 7-Day Private Tour", zh: "张家界、芙蓉镇与凤凰 7 天 6 晚私家团", ko: "장가계, 부용진, 봉황 6박 7일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-jiuzhaigou-huanglong-6-day-private-tour",
    title: { en: "Chengdu, Jiuzhaigou & Huanglong: 6-Day Private Tour", zh: "成都·九寨沟·黄龙 6 天 5 晚私家团", ko: "청두·주자이거우·황룽 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "kunming-dali-lijiang-8-day-private-tour",
    title: { en: "Kunming, Dali & Lijiang: 8-Day Private Tour", zh: "昆明·大理·丽江 8 天 7 晚私家团", ko: "쿤밍·다리·리장 8일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 6 }] },
    ],
  },
  {
    slug: "guizhou-huangguoshu-libo-miao-7-day-private-tour",
    title: { en: "Guiyang, Huangguoshu, Libo, Xijiang & Zhenyuan: 7-Day Private Tour", zh: "贵阳·黄果树·荔波·西江苗寨·镇远 7 天 6 晚私家团", ko: "구이양·황궈수·리보·시장·전위안 7일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "xiamen-tulou-quanzhou-6-day-private-tour",
    title: { en: "Xiamen, Fujian Tulou, Anxi & Quanzhou: 6-Day Private Tour", zh: "厦门·福建土楼·安溪·泉州 6 天 5 晚私家团", ko: "샤먼·푸젠 토루·안시·취안저우 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chaozhou-shantou-nanao-5-day-private-tour",
    title: { en: "Shantou, Nan'ao & Chaozhou: 5-Day Private Tour", zh: "汕头·南澳·潮州 5 天 4 晚私家团", ko: "산터우·난아오·차오저우 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chengdu-chongqing-8-day-private-tour",
    title: { en: "Chengdu, Leshan, Chongqing, Wulong & Dazu: 8-Day Private Tour", zh: "成都·乐山·重庆·武隆·大足 8 天 7 晚私家团", ko: "청두·러산·충칭·우룽·대족 8일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "guangzhou-shunde-foshan-5-day-private-tour",
    title: { en: "Guangzhou, Shunde & Foshan: 5-Day Private Tour", zh: "广州·顺德·佛山 5 天 4 晚私家团", ko: "광저우·순더·포산 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "huangshan-hongcun-huizhou-5-day-private-tour",
    title: { en: "Huangshan, Hongcun & Huizhou: 5-Day Private Tour", zh: "黄山·宏村·徽州 5 天 4 晚私家团", ko: "황산·홍춘·후이저우 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "jingdezhen-wuyuan-wangxian-6-day-private-tour",
    title: { en: "Jingdezhen, Wuyuan, Sanqingshan & Wangxian Valley: 6-Day Private Tour", zh: "景德镇·婺源·三清山·望仙谷 6 天 5 晚私家团", ko: "징더전·우위안·삼청산·왕셴구 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "changbaishan-yanji-winter-6-day-private-tour",
    title: { en: "Changbaishan Resort, North Slope & Yanji: 6-Day Winter Private Tour", zh: "长白山度假区·北坡·延吉 6 天 5 晚冬季私家团", ko: "창바이산·북파·옌지 6일 겨울 프라이빗 투어" },
    packages: [
      { id: "standard-guided-winter", prices: [] },
    ],
  },
  {
    slug: "shanghai-disneyland-5-day-private-tour",
    title: { en: "Shanghai & Disneyland: 5-Day Private Tour", zh: "上海与迪士尼 5 天 4 晚私家团", ko: "상하이·디즈니랜드 5일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "luoyang-dengfeng-kaifeng-6-day-private-tour",
    title: { en: "Luoyang, Dengfeng & Kaifeng: 6-Day Private Tour", zh: "洛阳·登封·开封 6 天 5 晚私家团", ko: "뤄양·덩펑·카이펑 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "datong-pingyao-6-day-private-tour",
    title: { en: "Datong & Pingyao: 6-Day Private Tour", zh: "大同·平遥 6 天 5 晚私家团", ko: "다퉁·핑야오 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "zhangye-jiayuguan-dunhuang-7-day-private-tour",
    title: { en: "Zhangye, Jiayuguan & Dunhuang: 7-Day Private Tour", zh: "张掖·嘉峪关·敦煌 7 天 6 晚私家团", ko: "장예·자위관·둔황 7일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "chongqing-yangtze-cruise-6-day-private-tour",
    title: { en: "Chongqing & Yangtze Three Gorges: 6-Day Private Tour", zh: "重庆与长江三峡游轮 6 天 5 晚私家团", ko: "충칭·창장삼협 크루즈 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "xinjiang-ili-sayram-8-day-private-tour",
    title: { en: "Ili, Sayram Lake & Nalati: 8-Day Private Tour", zh: "伊犁·赛里木湖·那拉提 8 天 7 晚私家团", ko: "이리·싸이리무호·나라티 8일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "hulunbuir-7-day-private-tour",
    title: { en: "Hulunbuir Grassland & Forest: 7-Day Private Tour", zh: "呼伦贝尔草原与森林 7 天 6 晚私家团", ko: "후룬베이얼 초원·숲 7일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [] },
    ],
  },
  {
    slug: "kunming-jianshui-yuanyang-6-day-private-tour",
    title: { en: "Kunming, Jianshui & Yuanyang: 6-Day Private Tour", zh: "昆明·建水·元阳 6 天 5 晚私家团", ko: "쿤밍·젠수이·위안양 6일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "shenzhen-family-tech-4-day-private-tour",
    title: { en: "Shenzhen Family Science & Technology: 4-Day Private Tour", zh: "深圳亲子科技 4 天 3 晚私家团", ko: "선전 가족 과학·기술 4일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
  {
    slug: "beijing-xian-shanghai-12-day-private-tour",
    title: { en: "Beijing, Xi'an & Shanghai: 12-Day Private Tour", zh: "北京·西安·上海 12 天 11 晚私家团", ko: "베이징·시안·상하이 12일 프라이빗 투어" },
    packages: [
      { id: "standard-guided", prices: [{ travelers: 2 }, { travelers: 4 }, { travelers: 6 }] },
    ],
  },
];
