import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "For a first Yangshuo trip, the safest default is the Yangshuo town and West Street living circle—not necessarily a room on West Street itself. Choose the Yulong River countryside deliberately when quiet mornings, karst-and-field views and a slower stay matter more than spontaneous dinners, simple luggage handling and an easy rainy-day fallback.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The short answer",
      tone: "decision",
      body: "Stay on the quieter edge of Yangshuo town for a short first visit, a late arrival, large bags, several evening meals out, children, older relatives or a group that wants options when it rains. Stay in the Yulong River countryside when the property itself is part of the holiday and you have verified the exact village, vehicle drop-off, meals, stairs, reception and route back after dark. Do not decide from the words “near West Street” or “Yulong River”; decide from the door.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This guide chooses a base within Yangshuo. It does not compare sleeping in Guilin with sleeping in Yangshuo, rank hotels, quote current rooms or availability, or plan transport between Guilin and Yangshuo. Once the base is chosen, use the separate Guilin–Yangshuo transport guide for the railway station, airport, road transfer or Li River arrival chain.",
    },
    {
      id: "labels-heading",
      type: "heading",
      level: 2,
      text: "Define the two choices before comparing them",
    },
    {
      id: "labels",
      type: "comparison",
      title: "Neither label is one hotel block",
      columns: [
        {
          heading: "Yangshuo town / West Street living circle",
          body: "The compact town base around the county centre, West Street and surrounding streets. It does not require a room inside the pedestrian and nightlife core. A quieter road-edge property can keep the evening convenience while reducing noise and suitcase friction.",
        },
        {
          heading: "Yulong River countryside",
          body: "A broad rural corridor of riverside and village stays rather than one centre. Jiuxian, Chaoyang, Jima, the Yulong Bridge area and the lower river near Gongnong Bridge behave differently. The exact address can matter more than the marketing label.",
        },
      ],
    },
    {
      id: "matrix-heading",
      type: "heading",
      level: 2,
      text: "Decision matrix: choose by what repeats",
    },
    {
      id: "decision-matrix",
      type: "table",
      caption: "Start with the recurring part of the stay, then verify the property",
      columns: ["What matters most", "Town / West Street circle", "Yulong River countryside", "Deciding check"],
      rows: [
        ["Evenings", "More freedom to choose dinner, shops or a walk without planning another road leg", "Best when an early, quiet night is the point and dinner is already solved", "Where will the group be after dinner on at least two nights?"],
        ["Early mornings", "Easier breakfast choices and pickup coordination; scenery usually requires going out", "Landscape, village lanes and river air can begin at the property", "Will the group actually use a slow countryside morning?"],
        ["Luggage and arrival", "Lower risk if the property has a confirmed road set-down and staffed reception", "Can add a village road, narrow lane or property pickup after the main drive", "Can the booked vehicle reach the door with every bag?"],
        ["Rain", "More indoor food and practical fallback choices within a compact area", "Rewarding if the stay has covered space, meals and a usable wet-weather road", "What remains enjoyable if outdoor activity changes?"],
        ["Children, older travellers or limited mobility", "Usually the first area to test, especially at a road edge", "Works only after the full vehicle-to-room route is verified", "Steps, lift, surface, lighting, bathroom and emergency fallback"],
        ["Quiet", "Possible on a side street, but verify room orientation and evening noise", "Stronger default away from busy roads and activity nodes, but not guaranteed", "Ask what the room faces and what happens nearby at night or dawn"],
        ["Relationship to sights", "Balanced for mixed Yangshuo days and one-off trips in different directions", "Strongest when Yulong River walks, cycling or slow time repeat", "Which place appears on two mornings, not just once on a wish list?"],
        ["Two or three nights", "Usually the resilient first choice", "Choose only when countryside time is a main reason for coming", "Would a remote base improve two parts of the stay or only one photo stop?"],
      ],
    },
    {
      id: "town-heading",
      type: "heading",
      level: 2,
      text: "When Yangshuo town is the better base",
    },
    {
      id: "town-evening",
      type: "paragraph",
      text: "Town earns the stay after the sightseeing day ends. A group can change dinner time, separate for a short walk, buy something forgotten or return early without every choice becoming a vehicle arrangement. Official Guangxi planning identifies the Yangshuo West Street area as a night-time culture and tourism consumption cluster. That supports the evening contrast; it does not mean every traveller should sleep on the busiest lane.",
    },
    {
      id: "town-morning",
      type: "paragraph",
      text: "Town also absorbs imperfect logistics. It is easier to protect a late check-in, leave bags with a staffed desk, change a wet-weather morning or gather several travellers for one confirmed pickup. You can still spend a full day in the Yulong River countryside. The trade-off is that the quiet field-and-river morning does not begin outside the room, and a poorly located town property can still create a pedestrian last mile.",
    },
    {
      id: "town-trap",
      type: "callout",
      title: "Do not translate “town” into “sleep on West Street”",
      tone: "warning",
      body: "A room inside or immediately above a busy pedestrian lane may exchange convenience for late noise and difficult vehicle access. First look for the useful living circle; then inspect the exact entrance, room orientation and road set-down. A quieter street a short walk away can be the stronger town choice.",
    },
    {
      id: "river-heading",
      type: "heading",
      level: 2,
      text: "When the Yulong River countryside is worth the extra planning",
    },
    {
      id: "river-geography",
      type: "paragraph",
      text: "“Yulong River” is much larger than one hotel zone. A Ministry of Culture and Tourism profile describes the national tourism resort as 86 square kilometres, with a 30-square-kilometre core spanning four townships and many natural villages. The scenic operator describes an 18.8-kilometre river reach from Yulong Bridge to Gongnong Bridge. These are useful scale facts: a listing near one village, bridge or wharf is not automatically convenient for another.",
    },
    {
      id: "river-rhythm",
      type: "paragraph",
      text: "The countryside earns its friction when the stay itself supplies the missing experience: an unhurried first light, breakfast facing the karst, a walk before day visitors arrive, an afternoon rest and an early evening with no need to return to town. It works especially well for travellers who want to repeat that rhythm, not merely take one bamboo-raft trip. The room, terrace or view shown on a booking page still does not prove a simple road, reliable dinner or step-free route.",
    },
    {
      id: "river-trap",
      type: "callout",
      title: "A riverside label does not identify the last mile",
      tone: "warning",
      body: "Ask for the full Chinese address, named village, map pin, nearest vehicle point and a current entrance photo. Confirm whether an ordinary booked vehicle reaches that point at the real arrival time and who carries the bags from there. Ride-hailing supply, local traffic controls and property pickups can change; this page does not promise any of them.",
    },
    {
      id: "schedule-heading",
      type: "heading",
      level: 2,
      text: "Two typical days show what you are buying",
    },
    {
      id: "schedule-town-heading",
      type: "heading",
      level: 3,
      text: "Typical town-base day",
    },
    {
      id: "schedule-town",
      type: "list",
      ordered: true,
      items: [
        "Breakfast and group assembly happen near the room, with bags or rain gear easy to retrieve.",
        "Use one confirmed outward trip for the Yulong River, a rural cycle or another chosen sight; keep the exact pickup point offline.",
        "Return, rest and change plans without committing to the same driver or restaurant for the evening.",
        "Walk to dinner or a town evening, then sleep on a checked quieter street rather than assuming the busiest lane is best.",
      ],
    },
    {
      id: "schedule-river-heading",
      type: "heading",
      level: 3,
      text: "Typical Yulong River countryside day",
    },
    {
      id: "schedule-river",
      type: "list",
      ordered: true,
      items: [
        "Use the early morning locally: a verified path, river view or quiet breakfast is the first activity rather than a transfer.",
        "Choose the day's walking, cycling or authorised river activity from the exact village and operating notice, not from a generic map pin.",
        "Return to the property for a slow afternoon instead of treating the room only as a place to sleep.",
        "Eat on site or follow a pre-checked dinner and return plan; do not discover the dark, wet or unlit last mile after the meal.",
      ],
    },
    {
      id: "weather-heading",
      type: "heading",
      level: 2,
      text: "Rain changes the value of the base, not only the view",
    },
    {
      id: "weather-table",
      type: "table",
      caption: "Build a rainy-day plan before paying for the countryside atmosphere",
      columns: ["Condition", "Town response", "Countryside response", "What to verify"],
      rows: [
        ["Light rain", "Short food and shopping walks remain flexible", "Mist and karst views may still make a slow property day rewarding", "Covered entrance, umbrellas, non-slip route and a dry place for wet clothes"],
        ["Steady rain", "More compact indoor choices and easier plan changes", "The stay works if meals and covered common space are genuinely available", "Road surface, vehicle reach, drainage and meal hours"],
        ["Outdoor or river activity changes", "Replace the activity without also solving a remote return", "Keep the countryside only if the property itself still justifies the day", "Official notice, cancellation terms and a pre-decided switch time"],
        ["Severe-weather warning", "Follow authorities and protect the next fixed journey", "Do not use scenery as a reason to remain on an unsafe route", "Current official weather, road and scenic-area instructions"],
      ],
    },
    {
      id: "mobility-heading",
      type: "heading",
      level: 2,
      text: "For families and mobility needs, test the chain rather than the scenery",
    },
    {
      id: "mobility-copy",
      type: "paragraph",
      text: "A road-edge town property is usually the lower-risk starting point for a pushchair, older parent, wheelchair user, heavy cases or a child who may need an early return. That is an area-level starting hypothesis, not an accessibility guarantee. A well-verified countryside property can be easier than a stepped town guesthouse; a beautiful rural room can also become unusable if the vehicle stops far away or there is no lift.",
    },
    {
      id: "mobility-check",
      type: "list",
      items: [
        "Vehicle set-down to entrance: distance, surface, gradient, lighting and cover from rain",
        "Entrance to assigned room: thresholds, stairs, lift dimensions and corridor turns",
        "Room and bathroom: bed arrangement, door clearance, shower or tub and night lighting",
        "Meals and return: breakfast, early dinner, child seating and a reliable way back before fatigue",
        "Recovery: a confirmed town-side alternative if the actual route is not usable",
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Real-world failure patterns and recovery",
    },
    {
      id: "failure-intro",
      type: "paragraph",
      text: "The failures below come from address and operating mismatches, not from choosing the “wrong” atmosphere. None requires a hotel ranking to solve; each requires one exact point, a cutoff and a fallback.",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Recover the stay without turning a small mismatch into a lost day",
      columns: ["Failure", "What went wrong", "Immediate recovery", "Next decision"],
      rows: [
        ["“Near West Street” ends inside a pedestrian lane", "The taxi pin is not the hotel door and the cases still need to cross paving or steps", "Call the property, use the agreed set-down and ask for its stated luggage help", "If the chain is not usable, move to a road-edge town property rather than changing the whole trip"],
        ["“Yulong River” is beside the wrong village or river section", "The activity, dinner or pickup was planned from a different pin", "Read the full Chinese address and contact the booked property and authorised operator", "Keep the stay if its own rhythm still works; otherwise move once at a sensible daylight cutoff"],
        ["A late, wet arrival ends at a rural roadside", "Reception, vehicle reach and the final bag handoff were never confirmed", "Stay with the named vehicle, call the property and do not walk an unknown dark lane with luggage", "Use a staffed town room for the first night if the property cannot provide a safe confirmed chain"],
        ["The river activity changes after a countryside booking", "The room was chosen only for one operating product", "Check the official notice and the booking's cancellation terms", "Keep the rural base only if the view, walks, meals and rest still make the stay worthwhile"],
      ],
    },
    {
      id: "address-heading",
      type: "heading",
      level: 2,
      text: "Verify the address before booking",
    },
    {
      id: "address-intro",
      type: "paragraph",
      text: "Open a Chinese map and save evidence for the exact property, not the platform's area badge. Measure the route from the entrance pin you will actually use. An old review, a straight-line distance or an English neighbourhood label cannot replace a current written answer from the property.",
    },
    {
      id: "address-list",
      type: "list",
      ordered: true,
      items: [
        "Save the full Chinese property name, address, phone number and map pin.",
        "Ask which named village, road, bridge or wharf the entrance is actually near.",
        "Request a current entrance photo and the normal vehicle set-down point.",
        "Confirm the final walking distance, surface, steps and who handles large bags.",
        "Check reception coverage for the realistic arrival window and what happens after a delay.",
        "Verify breakfast and dinner rather than assuming a rural listing has all-day food.",
        "For a quiet room, ask what it faces and whether there is road, bar, construction or common-area noise.",
        "For children or mobility needs, verify the assigned-room route and bathroom, not only the building description.",
        "Ask how the property arranges a legal vehicle and return after dark; do not rely on permanent ride-hailing supply.",
        "Keep the cancellation terms and one town-side fallback offline for rain, delay or an unusable last mile.",
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      title: "What was current when this guide was reviewed",
      tone: "neutral",
      body: "Reviewed August 21, 2026: the official Yulong River site was listing multiple named wharves and routes across the corridor, while official planning and scenic materials continued to show a distributed village, path and transport-node geography. This guide intentionally gives no permanent price, departure time, shuttle, ride-hailing promise, traffic-control rule or room feature. Recheck the official scenic notice, Chinese map and booked property's written instructions for the travel date.",
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "FAQ",
    },
    {
      id: "faq-short-heading",
      type: "heading",
      level: 3,
      text: "I have only two nights. Where should I stay?",
    },
    {
      id: "faq-short",
      type: "paragraph",
      text: "Start with a quiet, vehicle-accessible property in the town and West Street living circle. It protects arrival, dinner and a mixed sightseeing day. Override that default only if waking in the Yulong River countryside is one of the trip's main purposes and the exact last mile is already solved.",
    },
    {
      id: "faq-west-street-heading",
      type: "heading",
      level: 3,
      text: "Do I need to stay on West Street itself?",
    },
    {
      id: "faq-west-street",
      type: "paragraph",
      text: "No. “West Street living circle” is the useful comparison, not a command to sleep above the busiest section. A checked side street or road edge can preserve walkable evenings while improving sleep, vehicle access and luggage handling.",
    },
    {
      id: "faq-split-heading",
      type: "heading",
      level: 3,
      text: "Should I split the stay between town and the river?",
    },
    {
      id: "faq-split",
      type: "paragraph",
      text: "Usually not for a two- or three-night visit. Consider one move when there are enough nights to use at least one real countryside morning and at least one town evening, or when a late arrival or early departure makes the edge nights different. Count packing, storage, vehicle access and two check-ins before deciding that a split is more varied.",
    },
    {
      id: "faq-raft-heading",
      type: "heading",
      level: 3,
      text: "Does a Yulong River stay mean I can walk to any bamboo-raft trip?",
    },
    {
      id: "faq-raft",
      type: "paragraph",
      text: "No. The corridor has multiple named wharves and routes. Match the authorised product and its current operating notice to the exact property address. This page chooses a sleeping base; it does not choose or book a raft route.",
    },
    {
      id: "faq-xingping-heading",
      type: "heading",
      level: 3,
      text: "Which base is better for Xingping, the Li River or Yangshuo Railway Station?",
    },
    {
      id: "faq-xingping",
      type: "paragraph",
      text: "Neither area label solves those endpoints automatically. Xingping and Yangshuo Railway Station are separate from most town and Yulong River stays, and a Li River arrival has its own pier and luggage chain. Compare the exact two endpoints in the Guilin–Yangshuo transport guide rather than moving this accommodation decision into a transport timetable.",
    },
    {
      id: "faq-quiet-heading",
      type: "heading",
      level: 3,
      text: "Is the Yulong River always quiet?",
    },
    {
      id: "faq-quiet",
      type: "paragraph",
      text: "No area can guarantee a quiet assigned room. The countryside reduces urban evening activity, but a room can still face a road, common terrace, animals, maintenance or early departures. Town can also be quiet when the entrance and room face away from the pedestrian nightlife core. Ask about the room, not only the district.",
    },
    {
      id: "faq-family-heading",
      type: "heading",
      level: 3,
      text: "Which base is better with children or older parents?",
    },
    {
      id: "faq-family",
      type: "paragraph",
      text: "Test a road-edge town property first because meals, early returns and backup options are usually easier. Choose the countryside when a specific property has confirmed the vehicle-to-room chain, suitable room and bathroom, meal plan and safe return. Separately recheck the current age, height, health and safety rules for any river activity; a suitable base does not make every activity suitable.",
    },
    {
      id: "questions-heading",
      type: "heading",
      level: 2,
      text: "Questions to answer before you book",
    },
    {
      id: "questions-list",
      type: "list",
      items: [
        "After dinner on most nights, do we want to walk home or arrange a vehicle?",
        "Will we genuinely use an early countryside morning, or only leave immediately for another sight?",
        "What is the exact entrance pin, and can our vehicle reach it with all luggage?",
        "What remains a good day if rain or a river operation changes the outdoor plan?",
        "Who needs the simplest surface, fewest steps, earliest return or most reliable meal access?",
        "Does the property solve breakfast, dinner and the return after dark in writing?",
        "Is one hotel move removing repeated transfers, or merely adding packing to a short stay?",
        "Which current facts must be rechecked: property instructions, road access, scenic notice or onward transport?",
      ],
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue planning",
      items: [
        {
          label: "Where to stay in China",
          href: "/stay/",
          description: "Return to Homeground's neutral accommodation decision collection.",
        },
        {
          label: "Guilin to Yangshuo: train, road or river",
          href: "/guides/guilin-yangshuo-transport-route/",
          description: "After choosing the base, match the exact station, airport, pier and hotel endpoints.",
        },
        {
          label: "Minsu, homestay or hotel in China?",
          href: "/guides/minsu-homestay-or-hotel-china/",
          description: "Separate a countryside setting from the property type and service model.",
        },
        {
          label: "Verify an accessible hotel room",
          href: "/guides/china-accessible-hotel-room-verification/",
          description: "Check the full street-to-room-to-bathroom chain for a specific booking.",
        },
        {
          label: "Can foreign travellers stay at any hotel in China?",
          href: "/guides/foreigners-china-hotel/",
          description: "Keep national accommodation-registration and failed-check-in recovery in its dedicated guide.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official, first-party and map sources",
      items: [
        {
          label: "Yulong River National Tourism Resort profile and area scale",
          url: "https://www.mct.gov.cn/preview/special/9160/llxl/202009/t20200923_875345.htm",
          publisher: "Ministry of Culture and Tourism of the People's Republic of China",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Yulong River scenic-area overview and river reach",
          url: "https://www.ysylh.cn/about/",
          publisher: "Yangshuo County Yulong River Scenic Area Tourism Development Co.",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Official Jima route, village and riverside-path orientation",
          url: "https://www.ysylh.cn/matou/2023/jimamatouView.shtml",
          publisher: "Yangshuo County Yulong River Scenic Area Tourism Development Co.",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Official Yulong River detailed scenic-area plan",
          url: "https://lyj.gxzf.gov.cn/zfxxgkzl/fdzdgknr/gggs/P020230823401747754653.pdf",
          publisher: "Guangxi Zhuang Autonomous Region Forestry Administration",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Yangshuo West Street map record",
          url: "https://www.amap.com/place/B0IAHC7KWH",
          publisher: "Amap",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Guangxi plan identifying Yangshuo West Street's night-time role",
          url: "https://wlt.gxzf.gov.cn/zfxxgk/fdzdgknr/ghjh/zcqgh/P020230727672416456348.pdf",
          publisher: "Guangxi Zhuang Autonomous Region Department of Culture and Tourism",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Current official Yulong River wharf and route index",
          url: "https://www.ysylh.cn/matou/",
          publisher: "Yangshuo County Yulong River Scenic Area Tourism Development Co.",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Hero photograph: Yulong River by Liuxingy, CC BY-SA 4.0",
          url: "https://commons.wikimedia.org/wiki/File:%E6%A1%82%E6%9E%97%E9%98%B3%E6%9C%94%E5%8D%81%E9%87%8C%E7%94%BB%E5%BB%8A%E9%81%87%E9%BE%99%E6%B2%B3%E9%A3%8E%E6%99%AF_01.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Hero derivative licence: CC BY-SA 4.0",
          url: "https://creativecommons.org/licenses/by-sa/4.0/",
          publisher: "Creative Commons",
          reviewedAt: "2026-08-21",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
