import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "유니버설 베이징 리조트는 일곱 테마 구역을 아무 순서로 완주하는 목록이 아닙니다. 외국인은 먼저 여권과 일치하는 깨끗한 티켓 기록을 만들어야 합니다. 파크 안에서는 날씨, 어트랙션 상태, 공연, 키 제한과 대기가 실시간 사실이 됩니다. 우선순위와 지리로 계획하고 회복 여유를 남기세요." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "리조트나 베이징 정부가 안내한 경로에서 구매하고 여권 정보를 정확히 입력해 원본 여권을 지참하세요. 공식 앱을 미리 설치합니다. 반드시 보고 싶은 랜드 하나, 주요 어트랙션 하나, 공연이나 그룹 경험 하나를 정하세요. 실시간 지도로 시작하고 인접 구역을 끝낸 뒤 이동하며, 각 구역에 대안을 둡니다. 오래된 대기시간 예측에 하루를 걸지 마세요." },
  { id: "identity-heading", type: "heading", level: 2, text: "여권, 주문과 앱을 일치시키세요" },
  { id: "identity", type: "table", caption: "입장 전 연결", columns: ["항목", "확인", "실패 경계"], rows: [["티켓 주문", "방문일, 상품, 인원, 공식/공인 판매자", "마켓 스크린샷은 입장 기록이 아님"], ["여권", "이름과 번호가 주문과 일치", "중국 신분증을 지어내거나 타인 실명표를 넘겨받지 않음"], ["공식 앱/미니프로그램", "버전, 로그인과 실시간 지도", "버튼과 연결 흐름은 바뀔 수 있음"], ["원본 문서", "호텔이 아니라 방문자가 소지", "여권 사진은 여행 백업일 뿐 확실한 대체가 아님"]] },
  { id: "official-buy", type: "paragraph", text: "베이징시 공식 영문 서비스는 외국인이 리조트 앱, 공식 Fliggy 스토어 또는 연락센터에서 구매할 수 있고 여권 정보가 필요하다고 설명합니다. 리조트 자체 사이트에서 현재 티켓·앱·연락 경로를 확인하세요. 해외 결제나 계정이 실패하면 비슷한 사이트에 신원을 반복 제출하지 말고 공식 센터를 이용합니다." },
  { id: "privacy", type: "callout", title: "사진 검증은 현행 고지를 읽고 선택하세요", tone: "neutral", body: "리조트는 입장 등에 쓰는 사진 검증을 설명하면서 직원이나 게스트 서비스를 통해 거부·문의할 수 있다고 안내합니다. 얼굴 사진을 미리 올리기 전 현재 개인정보 고지를 읽으세요. 이 글은 검증 우회나 특정 방식의 이용을 보장하지 않습니다." },
  { id: "app-heading", type: "heading", level: 2, text: "공식 앱을 하루의 제어판으로" },
  { id: "app-list", type: "list", items: ["방문일 운영 달력, 상태, 공연과 지도를 확인합니다.", "여행자별 이용 제한을 읽습니다.", "게스트 서비스, 의료, 보관함과 수하물 보관 위치를 미리 찾습니다.", "충전된 두 번째 기기나 주문 정보를 준비합니다.", "익스프레스는 현행 약관이 있는 선택 상품이며 보장이 아닙니다."] },
  { id: "route-heading", type: "heading", level: 2, text: "앵커 랜드 하나를 중심으로 동선을 만드세요" },
  { id: "route", type: "comparison", title: "정직한 하루 세 가지", columns: [{ heading: "첫 방문 샘플", body: "앵커 랜드 하나, 다른 구역 주요 기구 하나, 공연 하나를 고르고 나머지는 인접한 낮은 부담 경험으로 채웁니다." }, { heading: "스릴 중심", body: "몸에 맞는 강한 기구 2~3개와 안전 제한을 지키고 랜드 탐색, 쇼핑과 캐릭터 시간을 줄입니다." }, { heading: "가족·혼합 그룹", body: "공동 기구, 공연, 식사와 휴식 중심. 성인·문서·폰·집합점이 독립적일 때만 잠깐 나뉩니다." }] },
  { id: "geography", type: "paragraph", text: "대기 숫자가 몇 분 줄었다고 지그재그로 걷지 마세요. 이동하는 동안 수치는 바뀝니다. 앵커 랜드의 필수 항목과 근처 대안을 마친 뒤 한 번 이동합니다. 시티워크의 쇼핑과 식사는 파크의 좋은 운영 시간을 소모하지 않도록 뒤로 둘 수 있습니다." },
  { id: "day", type: "table", caption: "회복 가능한 하루 리듬", columns: ["구간", "결정", "피할 것"], rows: [["입장 전", "문서, 실시간 정보와 첫 앵커 확인", "게이트에서 하루 재설계"], ["첫 운영 구간", "앵커 또는 근처 대안 완료", "중단 기구를 따라 파크 횡단"], ["점심", "먹고 수분 보충, 가장 지친 사람 확인", "피로를 낭비로 취급"], ["오후", "두 번째 구역과 공연/공동 목표", "놓친 모든 인기 항목 다시 추가"], ["마지막", "남은 우선순위 또는 분위기", "마지막 재개에 의존"]] },
  { id: "weather", type: "callout", title: "날씨는 편안함 이상을 바꿉니다", tone: "warning", body: "더위, 번개, 바람, 비, 결빙과 대기 상태는 야외 기구와 공연을 바꿀 수 있습니다. 합법적인 실내·휴식 대안을 두고 직원 지시를 따르세요. 티켓이나 익스프레스도 안전하지 않은 운영을 요구할 수 없습니다." },
  { id: "failure-heading", type: "heading", level: 2, text: "문제를 키우지 말고 회복하세요" },
  { id: "failure", type: "table", caption: "문제와 대응", columns: ["문제", "대응"], rows: [["여권 정보 오류", "여행 전에 공식 판매자나 리조트에 연락; 두 번째 신원 생성 금지"], ["앱/미니프로그램 실패", "원본 여권과 주문을 보관하고 공식 웹·센터·게스트 서비스 이용"], ["앵커 기구 중단", "근처 대안 후 나중에 확인하고 그룹 경험 보호"], ["그룹 분리", "정해 둔 물리적 장소와 시간에 만남"], ["수하물이 큼", "현행 공식 보관만 쓰고 크기·요금·종료 조건 확인"]] },
  { id: "return", type: "paragraph", text: "베이징 도심 귀환 여유를 지키세요. 중국어 대중교통/픽업 지점을 저장하고 최종 출발 시각을 정합니다. 파크 뒤에 놓칠 수 없는 항공이나 열차를 붙이지 마세요. 폐장 시각은 막차, 짧은 택시 줄이나 원활한 도로를 보장하지 않습니다." },
  { id: "check", type: "list", items: ["전원의 주문과 원본 여권이 일치합니다.", "공식 앱·지도·연락 경로가 충전된 기기에서 작동합니다.", "시간, 날씨, 제한과 공연을 다시 확인했습니다.", "앵커 랜드, 주요 기구, 공동 목표와 근처 대안이 있습니다.", "귀환 경로와 최종 출발 결정을 저장했습니다."] },
  { id: "links", type: "internal-links", title: "베이징 계획 이어가기", items: [{ label: "베이징 도시 허브", href: "/ko/destinations/beijing/", description: "숙박일과 첫 여행에서 파크 역할을 정합니다." }, { label: "베이징 숙소 지역", href: "/ko/guides/beijing-where-to-stay-first-trip/", description: "다른 베이징 일정에도 맞는 기반을 고릅니다." }, { label: "베이징 어느 기차역?", href: "/ko/guides/which-beijing-railway-station/", description: "발권된 역과 귀환을 일치시킵니다." }, { label: "중국 공휴일", href: "/ko/guides/china-public-holidays-travel-calendar/", description: "날짜표 구매 전 혼잡일을 확인합니다." }, { label: "중국 보조배터리 규정", href: "/ko/guides/china-power-bank-rules-flights-trains/", description: "규정에 맞게 앱 전원을 지킵니다." }, { label: "일정이 너무 바쁜가요?", href: "/ko/guides/is-your-china-itinerary-too-rushed/", description: "파크를 취약한 도시 간 환승에 붙이지 않습니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "외국인 티켓과 여권 요건", url: "https://english.beijing.gov.cn/consuminginbeijing/faq/202306/t20230630_3151223.html", publisher: "베이징시 인민정부", reviewedAt: "2026-08-22" }, { label: "게스트 서비스·앱·보관", url: "https://www.universalbeijingresort.com/en/ubrbasepage/youkefuwu", publisher: "Universal Beijing Resort", reviewedAt: "2026-08-22" }, { label: "공식 연락센터", url: "https://www.universalbeijingresort.com/en/contact/contactus", publisher: "Universal Beijing Resort", reviewedAt: "2026-08-22" }, { label: "사진 검증과 거부 안내", url: "https://www.universalbeijingresort.com/en/photo-validation-system-introduction", publisher: "Universal Beijing Resort", reviewedAt: "2026-08-22" }, { label: "대표 사진: Hhhh2, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Universal_Beijing_Resort.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
