import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body: StructuredPageBody = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "answer-first",
      type: "lead",
      text: "Almost every foreign visitor must fill in China's free arrival card, including Malaysians and Singaporeans entering visa-free. Since 20 November 2025 you can do it online before you fly: on the National Immigration Administration's website at s.nia.gov.cn/ArrivalCardFillingPC/, in its NIA 12367 app, or in its mini-program inside WeChat or Alipay. Fill it in once your flight and first hotel are booked; China sets no 24- or 72-hour deadline. If you cannot, use the QR code, a self-service device or a paper card at the Chinese airport or port. The card records your trip; it is not a visa. Checked on 24 September 2026.",
    },
    {
      id: "official-free",
      type: "callout",
      title: "The official form costs nothing",
      body: "Start from s.nia.gov.cn/ArrivalCardFillingPC/, the NIA 12367 app or its WeChat or Alipay mini-program. A website that charges an arrival-card fee, sells urgent approval or asks for card payment is not the free government service described by the NIA. Stop before paying and reopen the official address yourself.",
      tone: "warning",
      link: { href: "https://s.nia.gov.cn/ArrivalCardFillingPC/", label: "Open the official free arrival card" },
    },
    {
      id: "malaysia-singapore-heading",
      type: "heading",
      level: 2,
      text: "From Malaysia or Singapore: visa-free, but still fill in the card",
    },
    {
      id: "malaysia-singapore-table",
      type: "table",
      caption: "Malaysian and Singapore passports on a holiday of up to 30 days (checked 24 September 2026)",
      columns: ["Rule", "Malaysian passport", "Singapore passport"],
      rows: [
        ["Visa", "Not needed for up to 30 days per entry (since 17 July 2025)", "Not needed for up to 30 days (since 9 February 2024)"],
        ["ETA or pre-approval", "None mentioned by the Chinese Embassy in Malaysia", "None mentioned by ICA or the Chinese side"],
        ["Arrival card", "Yes, free", "Yes, free"],
        ["Passport validity", "At least six months (Chinese Embassy in Malaysia)", "No official minimum found; six months is the safe choice"],
        ["Time limit", "No more than 90 days in any 180", "No official limit found beyond 30 days per stay"],
        ["Work, study, journalism or over 30 days", "Visa needed", "Visa needed"],
      ],
    },
    {
      id: "malaysia-singapore-list",
      type: "list",
      ordered: false,
      items: [
        "Malaysia: the 30 days run from 0:00 on the day after you arrive, and the 90 days are counted back 180 days from each entry day; stays before 17 July 2025 do not count. The agreement is valid for five years from 17 July 2025, with automatic renewal, so it does not end in 2026.",
        "Singapore permanent residents follow the rule for their own passport: a Malaysian with Singapore PR uses the Malaysian arrangement, and a Chinese citizen entering on a Chinese passport does not fill in this foreigners' card.",
        "A package or private tour does not, on its own, make you exempt from the card. The \"visa-free tourist group\" exemption refers to formal schemes run by a registered travel agency, where the group enters and leaves together: cruise groups, ASEAN groups to Xishuangbanna or Guilin, and foreign groups entering Guangdong or Hainan from Hong Kong or Macao. If you enter on your own passport under the visa exemption, even as part of a tour, fill in the card.",
        "Flying straight to Hainan: Hainan has its own 30-day visa-free policy for both passports. Singapore's consulate in Guangzhou said in February 2025, before the online card, that travellers staying only in Hainan under that policy need not fill in the card. The NIA's current form does not list this exemption, so fill in the card anyway: it is free, and it covers you if you travel beyond Hainan.",
      ],
    },
    {
      id: "timing-heading",
      type: "heading",
      level: 2,
      text: "When to fill it: China sets no 24- or 72-hour deadline",
    },
    {
      id: "timing-copy",
      type: "paragraph",
      text: "Fill it in once your flight and first night's hotel are booked and your arrival is less than three months away. Neither the NIA's announcement nor the Chinese Embassy in Malaysia's notice sets a deadline, and the entry-date picker in the live web form, checked on 24 September 2026, offers dates up to three months ahead. We suggest the week before you fly: it leaves time to fix a mistake but little time for plans to change. The 72-hour and 24-hour rules in some guides and search summaries do not come from the NIA. Do not invent a flight number or hotel to submit sooner; if the form shows its own window, follow it.",
    },
    {
      id: "where-heading",
      type: "heading",
      level: 2,
      text: "Where to fill it in: website, app, WeChat, Alipay or at the port",
    },
    {
      id: "channel-comparison",
      type: "comparison",
      columns: [
        {
          heading: "Before travel online",
          items: [
            "Website: s.nia.gov.cn/ArrivalCardFillingPC/ on a computer, or s.nia.gov.cn/ArrivalCardFillingPhone/ on a phone",
            "13 languages, including English and Chinese; no Malay",
            "The NIA 12367 app (移民局12367 in Chinese), or its mini-program inside WeChat or Alipay",
            "Save the receipt offline; a copy is also emailed to you",
          ],
        },
        {
          heading: "At the port electronically",
          items: [
            "Scan the official QR code or use a self-service device at the port",
            "Keep the passport and flight details ready",
            "Ask border staff when the steps or language are unclear",
            "Filling it in early does not remove the inspection queue",
          ],
        },
        {
          heading: "Paper at the port",
          items: [
            "The NIA says paper cards remain available",
            "Copy passport and flight details exactly",
            "Correct an error visibly or ask for a new card",
            "Your fallback if the phone, network or website fails",
          ],
        },
      ],
    },
    {
      id: "other-apps",
      type: "paragraph",
      text: "You may also see an arrival-card feature in Touch 'n Go or other travel apps. We have not confirmed that these submit your card to the NIA, and the NIA and the Chinese Embassy in Malaysia name only the NIA's own channels, so use one of those.",
    },
    {
      id: "prepare-heading",
      type: "heading",
      level: 2,
      text: "What to have ready",
    },
    {
      id: "prepare-list",
      type: "list",
      ordered: false,
      items: [
        "Each traveller's passport: the form reads the photo page.",
        "Your flight number, arrival airport and the local arrival date.",
        "The full address of your first hotel, as on the booking confirmation.",
        "Your phone number and email, and your return or onward flight if booked.",
        "The countries or regions you have visited in the past two years.",
      ],
    },
    {
      id: "steps-heading",
      type: "heading",
      level: 2,
      text: "Fill it in, screen by screen (checked 24 September 2026)",
    },
    {
      id: "steps-list",
      type: "list",
      ordered: true,
      items: [
        "Open s.nia.gov.cn/ArrivalCardFillingPC/ (or /ArrivalCardFillingPhone/ on a phone) from a saved link, or use the NIA 12367 app or mini-program. Pick English or Chinese from the Language menu, select Entry Declaration and read the list of exemptions.",
        "Photograph your passport data page. The form reads your details from it; check every letter, number and date it fills in against the passport.",
        "Basic information: document type, name, sex, date of birth, citizenship and passport number; how you arrive (plane, train, ship or road), the flight, train or vessel number, and the city and port of entry; your phone number and email.",
        "Entry category: the form asks whether you hold a valid visa or other entry permit. If you are entering visa-free from Malaysia or Singapore, answer No and choose the visa-exemption policy the form offers for your passport. If it says you do not qualify for visa-free entry, stop and check your passport and trip against the rules above.",
        "Personal information: other names, any other citizenship, country and city of birth, and whether this passport has ever been lost or stolen.",
        "Travel information: purpose (sightseeing or leisure for a holiday), date of entry, the cities you will visit and any you transit through, countries or regions visited in the past two years, your confirmed departure (date, city, port, transport and flight number, if booked) and the full address of your first accommodation. The form also asks whether you have an inviting company or person in China; on a holiday, answer No.",
        "Accompanying people: you can add companions (the form's list holds up to ten), so one adult can complete the card for a family. Enter each person's own passport details; do not copy one person's passport number or address into another's record.",
        "Sign in the box on screen and submit. You get an Entry Declaration Receipt on screen and by email. Save it offline, and carry your passport and your flight and hotel bookings: officers still inspect everyone.",
      ],
    },
    {
      id: "steps-note",
      type: "paragraph",
      text: "If the live form differs from these steps, follow its wording and answer only what it asks. The NIA's own video walkthrough is listed under Sources. Do not send Homeground or an unofficial agent a passport scan to have the card typed for you.",
    },
    {
      id: "change-heading",
      type: "heading",
      level: 2,
      text: "What to do when details change or the form fails",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "If your plans change or something goes wrong",
      columns: ["Problem", "What to do first", "If that does not work"],
      rows: [
        ["Your flight or arrival date changes", "Open the official service again and correct the card, or submit a new one if it lets you.", "Carry the new booking and your old receipt, and tell the officer at the counter."],
        ["Your first hotel changes", "Update the address the same way, using the new booking confirmation.", "Show the new booking at the counter; fill in a paper card if the officer asks."],
        ["A typo in your name, passport number or passport expiry date", "Do not travel with a known mistake: correct it or submit a new card through the official service.", "Call the 12367 immigration hotline, or ask the officers at the port."],
        ["The website will not load, or your phone has no data", "Try another connection, and type the address yourself instead of tapping a search ad.", "At the port, scan the official QR code, use a self-service device or ask for a paper card."],
        ["You did not save the receipt", "Look for the copy emailed to you, or reopen the official service. Never pay a website to retrieve it.", "If the officer cannot find your card, fill it in again at the port."],
        ["You may have submitted twice", "Keep the most recent correct receipt.", "Show the officer both and follow their instruction."],
      ],
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "Who does not need a China arrival card",
    },
    {
      id: "who-table",
      type: "table",
      caption: "Eight exemptions on the live form (checked 24 September 2026). None covers an ordinary holiday, even on a private tour.",
      columns: ["Exempt traveller or journey", "What to know"],
      rows: [
        ["Holder of a PRC Foreign Permanent Resident ID Card", "Carry and use the qualifying document; exemption from the card is not exemption from inspection."],
        ["Holder of a Mainland Travel Permit for Hong Kong and Macao Residents (Non-Chinese Citizens)", "Confirm that the traveller is entering on that document."],
        ["Member of a formal visa-free tourist group, or holder of a group visa", "Covers schemes such as cruise groups, ASEAN groups to Xishuangbanna or Guilin, and foreign groups entering Guangdong or Hainan from Hong Kong or Macao, organised by a registered agency. An ordinary package or private tour entering on individual visa-free terms is not one of them."],
        ["Direct transit within 24 hours without leaving the port's restricted area", "If the journey requires entry, baggage collection landside or an unprotected transfer, do not assume this category applies."],
        ["Traveller entering and leaving on the same cruise ship", "Confirm the cruise and port procedure for the exact call."],
        ["Traveller entering through the E-channel (fast lane)", "Unlikely to cover you: the NIA's published rules open these lanes to people such as mainland, Hong Kong, Macao and Taiwan residents and non-Chinese holders of the Hong Kong and Macao residents' permit, and we found no rule opening them to ordinary Malaysian or Singaporean visitors."],
        ["Foreign employee of an exit-entry transport vehicle", "This is an occupational category, not a general airline-passenger exemption."],
        ["Traveller formally eligible for the courtesy arrangement for centralized presentation of entry-exit documents", "This is a managed courtesy process. Do not infer eligibility from passport type or group travel; confirm it with the responsible organiser or immigration authority."],
      ],
    },
    {
      id: "fraud-heading",
      type: "heading",
      level: 2,
      text: "Recover from a fake or paid arrival-card website",
    },
    {
      id: "fraud-list",
      type: "list",
      ordered: true,
      items: [
        "Stop the session. Do not send more passport images, payment details, verification codes or selfies.",
        "Screenshot the website address, the amount, the time and any receipt or messages; you will need them for a refund claim.",
        "If you entered card details, call your bank on the number on your card and ask it to block the card and dispute the charge.",
        "Change any password reused on that website and protect the associated email account with a unique password and multi-factor authentication.",
        "Open the NIA service by typing or using the official government link and submit the accurate arrival information there. A paid receipt from another site is not official proof.",
        "Report the site. In Malaysia, call the National Scam Response Centre on 997 as soon as money has left your account; in Singapore, call the ScamShield Helpline on 1799 (+65 6869 1799 from overseas). For questions about the arrival card itself, call China's immigration hotline, 12367.",
      ],
    },
    {
      id: "privacy-warning",
      type: "callout",
      title: "Treat passport data as a sensitive identity record",
      body: "Do not post the completed card, QR code, passport page, visa, boarding pass or hotel booking publicly. When asking for help, redact document numbers, dates of birth, barcodes, booking references, addresses and contact details. Homeground can explain the workflow without collecting those records.",
      tone: "warning",
    },
    {
      id: "boundary-heading",
      type: "heading",
      level: 2,
      text: "What the arrival card does not cover",
    },
    {
      id: "boundary-list",
      type: "list",
      ordered: false,
      items: [
        "Permission to enter: the visa or visa-free rule, your passport and the border officer's decision. A submitted card does not guarantee entry or a faster queue.",
        "Customs is separate: declare food, medicine, cash over the limits or dutiable goods at the red channel; otherwise walk through the green channel.",
        "Where you stay: hotels register you with the police at check-in. If you stay with family or in a private home, you or your host must register the stay within 24 hours (Exit and Entry Administration Law, Article 39). Since 21 September 2026, the NIA has offered online registration for stays outside hotels nationwide, while in-person registration at the local police office remains available.",
      ],
    },
    {
      id: "final-checklist-heading",
      type: "heading",
      level: 2,
      text: "Five-minute check before departure",
    },
    {
      id: "final-checklist",
      type: "list",
      ordered: false,
      items: [
        "Everyone travelling has a card, or clearly fits one of the eight exemptions.",
        "You used s.nia.gov.cn, the NIA 12367 app or its WeChat or Alipay mini-program, and paid nothing.",
        "Names, passport numbers, flight, arrival airport, date and first hotel match your bookings.",
        "The receipts are saved offline, and you know the port has QR, self-service and paper backups.",
      ],
    },
    {
      id: "faq",
      type: "faq",
      title: "Arrival card questions answered",
      items: [
        {
          question: "Is there an online arrival card for China?",
          answer: "Yes. Since 20 November 2025, China's National Immigration Administration has run a free online arrival card at s.nia.gov.cn/ArrivalCardFillingPC/, in the NIA 12367 app and in the NIA 12367 mini-programs inside WeChat and Alipay. Fill it in before you fly once your flight and first hotel are booked; otherwise use the QR code, a self-service device or a paper card at the port.",
        },
        {
          question: "Do Malaysians need to fill in an arrival card for China?",
          answer: "Yes. Malaysians entering visa-free fill in the free arrival card, and joining a package or private tour does not on its own change that: the group exemption refers to formal group visa-free schemes. Fill it in online before the flight, or at the port if the site will not load.",
        },
        {
          question: "Do Malaysians need a visa or an ETA for China in 2026?",
          answer: "No, for stays of up to 30 days for tourism, visiting family or friends, business, exchanges, medical treatment or transit. The mutual visa exemption took effect on 17 July 2025 for five years, with automatic renewal, and the Chinese Embassy in Malaysia mentions no ETA or pre-approval. You need a passport valid for six months and the arrival card, and you may spend no more than 90 days in China in any 180.",
        },
        {
          question: "Do Singaporeans need to fill in a China arrival card?",
          answer: "Yes. Singaporeans enter visa-free for up to 30 days (since 9 February 2024) but still fill in the free arrival card, online before the flight or at the port. A Singapore permanent resident follows the rule for their own passport: a foreign passport holder fills in the card; a Chinese citizen entering on a Chinese passport does not.",
        },
        {
          question: "When should I fill out the China arrival card?",
          answer: "Once your flight and first hotel are booked. China sets no 24- or 72-hour deadline, and the live web form offers entry dates up to three months ahead. We suggest the week before you fly, which leaves time to correct mistakes; if you cannot do it in advance, complete it at the port.",
        },
        {
          question: "How do I fill in China's e-arrival card?",
          answer: "Open s.nia.gov.cn/ArrivalCardFillingPC/, the NIA 12367 app or its WeChat or Alipay mini-program, photograph your passport data page and check the details it reads. Enter your flight, port and date, answer the visa question (No, if you are entering visa-free, then choose the visa-free policy the form offers), and add your purpose, cities and first address. Sign, submit and save the Entry Declaration Receipt, which is also emailed to you.",
        },
        {
          question: "Can I fill in the China arrival card for my family?",
          answer: "Yes. The official form lets you add accompanying people (its list holds up to ten), so one adult can add family members or companions. Enter each person's own passport details; everyone still goes through border inspection.",
        },
        {
          question: "Do I need a new arrival card every time I enter China?",
          answer: "Yes. The card records one entry: its date, port and flight or train. After a side trip to Hong Kong or Macao, for example, fill in a new card for the next entry into mainland China.",
        },
        {
          question: "Is China's online arrival card free?",
          answer: "Yes. The National Immigration Administration's official service costs nothing. A website that charges an arrival-card fee, sells urgent approval or asks for card payment is not the official service: stop before paying and reopen s.nia.gov.cn/ArrivalCardFillingPC/ yourself.",
        },
        {
          question: "Who does not need to fill in a China arrival card?",
          answer: "Only eight narrow groups: holders of a Chinese permanent residence ID card, or non-Chinese holders of a Mainland Travel Permit for Hong Kong and Macao residents; airside transit under 24 hours; formal visa-free tourist groups or group-visa holders; transport crew; cruise passengers leaving on the same ship; the document-presentation courtesy; and E-channel users. An ordinary package tour entering on individual visa-free terms is not one of these.",
        },
        {
          question: "Is China's digital arrival card mandatory?",
          answer: "The arrival card is mandatory for almost every foreign visitor, including Malaysians and Singaporeans entering visa-free. Filling it in online is not: you can still do it at the port by QR code, self-service device or paper card. Doing it before you fly just means one less task in the arrival hall. The official service is free.",
        },
        {
          question: "What other forms do I need to enter China?",
          answer: "For a holiday of up to 30 days on a Malaysian or Singapore passport: no visa and no ETA, just the arrival card. At Customs, use the red channel only if you carry goods to declare or cash above the limits, such as more than RMB 20,000. Hotels register your stay for you; if you stay in a private home, register with the local police within 24 hours.",
        },
      ],
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Read next: entry, payments and arrival day",
      items: [
        { label: "How to pay in China from Malaysia or Singapore", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Set up Touch 'n Go, OCBC, Alipay or WeChat Pay before the same flight." },
        { label: "China entry requirements", href: "/guides/china-entry-requirements/", description: "Check visa, visa-free and transit rules for other passports." },
        { label: "China eSIM or local SIM", href: "/guides/china-esim-vs-local-sim/", description: "You need data to open the form or its receipt on arrival." },
        { label: "Hong Kong or Macao side trip: how re-entry is counted", href: "/guides/hong-kong-macau-mainland-reentry-count/", description: "Plan the extra arrival card and the visa-free days for a side trip." },
        { label: "Passport validity and blank pages", href: "/guides/china-passport-validity-and-blank-pages/", description: "Audit the physical passport and separate airline, visa and border rules." },
        { label: "China Customs red or green channel", href: "/guides/china-customs-red-green-channels/", description: "Decide whether baggage needs a Customs declaration after immigration." },
        { label: "Food, plants and animal products at China Customs", href: "/guides/food-plants-and-animal-products-into-china/", description: "Check what must be declared, surrendered or left at home before packing." },
        { label: "Can a China arrival day support a timed booking?", href: "/guides/china-arrival-day-booked-anchor-or-flexible-block/", description: "Protect the first day without assuming the online card removes border-processing uncertainty." },
        { label: "Hotel check-in for foreign travellers", href: "/guides/foreigners-china-hotel/", description: "Keep hotel acceptance and accommodation registration as the next task." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources and image credit",
      items: [
        { label: "FAQs on the China-Malaysia Mutual Visa Exemption Agreement (1 August 2025)", url: "https://my.china-embassy.gov.cn/eng/fwzc/lsyw/qz/202508/t20250801_11681401.htm", publisher: "Embassy of the People's Republic of China in Malaysia", reviewedAt: "2026-09-24" },
        { label: "Mutual 30-day visa-exemption arrangement between Singapore and the People's Republic of China", url: "https://www.ica.gov.sg/news-and-publications/newsroom/media-release/mutual-30-day-visa-exemption-arrangement-between-singapore-and-the-people-s-republic-of-china", publisher: "Immigration & Checkpoints Authority of Singapore", reviewedAt: "2026-09-24" },
        { label: "Notice on the online arrival card: channels, port options and exemptions (3 December 2025)", url: "https://my.china-embassy.gov.cn/eng/fwzc/zytz/202512/t20251203_11765712.htm", publisher: "Embassy of the People's Republic of China in Malaysia", reviewedAt: "2026-09-24" },
        { label: "Visa-free group and regional entry schemes, including ASEAN groups to Xishuangbanna and Guilin (updated 20 August 2026)", url: "https://en.nia.gov.cn/n147418/n147463/c180637/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "E-channels for non-Chinese holders of the Mainland Travel Permit after fingerprint collection (2 July 2024)", url: "https://en.nia.gov.cn/n147418/n147463/c156118/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "Visa-exemption policies for Singapore passport holders entering Hainan (13 February 2025)", url: "https://guangzhou.mfa.gov.sg/mission-updates/visa-exemption-policies-for-singapore-ordinary-passport-holders-entering-hainan/", publisher: "Consulate-General of the Republic of Singapore in Guangzhou", reviewedAt: "2026-09-24" },
        { label: "China travel page: visa exemption and Hainan arrangements", url: "https://www.mfa.gov.sg/travelling-overseas/travel-advisories-notices-and-visa-information/china/", publisher: "Ministry of Foreign Affairs, Singapore", reviewedAt: "2026-09-24" },
        { label: "China–Singapore mutual visa exemption: purposes and activities that need a visa (25 January 2024, in Chinese)", url: "https://wb.beijing.gov.cn/home/wswm/crjxx/qzxx/qztz/202402/t20240205_3557072.html", publisher: "Foreign Affairs Office of the Beijing Municipal Government", reviewedAt: "2026-09-24" },
        { label: "Exit and Entry Administration Law, Article 39: accommodation registration within 24 hours", url: "https://en.nia.gov.cn/n147418/n147458/c155978/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "Policy interpretation: online accommodation registration for stays outside hotels (20 March 2026)", url: "https://en.nia.gov.cn/n147418/n147463/c197328/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "Nationwide online registration for stays outside hotels from 21 September 2026", url: "https://www.nia.gov.cn/n897453/c1806111/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-25" },
        { label: "State Council — Guide to Working and Living in China: RMB 20,000 cash allowance per trip", url: "https://english.www.gov.cn/2025special/bizexpatsinchina2025", publisher: "The State Council of the People's Republic of China", reviewedAt: "2026-09-24" },
        { label: "NSRC 997 hotline for online financial scams", url: "https://www.malaysia.gov.my/en/categories/safety-and-community/cybersecurity/nsrc-997-hotline", publisher: "Government of Malaysia", reviewedAt: "2026-09-24" },
        { label: "ScamShield Helpline 1799", url: "https://www.scamshield.gov.sg/scamshield-helpline/", publisher: "ScamShield, Government of Singapore", reviewedAt: "2026-09-24" },
        { label: "Beware of fraudulent arrival-card websites", url: "https://en.nia.gov.cn/n147418/n147463/c191530/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "Official online arrival-card service: instructions, eight exemptions and form (checked 24 September 2026)", url: "https://s.nia.gov.cn/ArrivalCardFillingPC/", publisher: "National Immigration Administration Government Service Platform", reviewedAt: "2026-09-24" },
        { label: "2025 announcement implementing online arrival-card filling and its original seven exemptions", url: "https://en.nia.gov.cn/n147413/c187308/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "How to submit the arrival card online (NIA video walkthrough)", url: "https://en.nia.gov.cn/n147418/n147463/c195170/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-24" },
        { label: "Hero: Beijing Capital International Airport T1 arrival hall — Tyg728 (CC BY-SA 4.0); resized by Homeground", url: "https://commons.wikimedia.org/wiki/File:Beijing_Capital_International_Airport_T1_Arrival_hall_20161124.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-20" },
        { label: "Hero photograph licence: CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-20" },
      ],
    },
  ],
};

export default body;
