import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body: StructuredPageBody = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "answer-first",
      type: "lead",
      text: "Use the National Immigration Administration's official online arrival-card service before travelling if you are required to complete a card and your trip details are settled. The service is free. If the official form will not load or you cannot complete it in advance, the NIA says you may fill in the information at the Chinese port using the official QR code or a port device, or use a paper arrival card. If details change after submission, use any correction route shown by the live official service; if none is clear, carry the correct records and ask 12367 or immigration staff at the port. The card records entry information; it is not a visa, visa-free approval or permission to bypass border inspection.",
    },
    {
      id: "official-free",
      type: "callout",
      title: "The official form costs nothing",
      body: "Start from https://s.nia.gov.cn/ArrivalCardFillingPC/ or a channel named by the NIA. A website that charges an arrival-card fee, sells urgent approval or asks for card payment is not the free government service described by the NIA. Stop before paying and reopen the official address yourself.",
      tone: "warning",
    },
    {
      id: "who-heading",
      type: "heading",
      level: 2,
      text: "First decide whether this traveller needs an arrival card",
    },
    {
      id: "who-table",
      type: "table",
      caption: "The 2025 NIA announcement listed seven exemptions; the live official form reviewed on 20 August 2026 lists an eighth document-presentation courtesy category",
      columns: ["Traveller or journey", "Arrival-card position", "What still needs checking"],
      rows: [
        ["Holder of a PRC Foreign Permanent Resident ID Card", "Listed as exempt", "Carry and use the qualifying document; exemption from the card is not exemption from inspection."],
        ["Holder of a Mainland Travel Permit for Hong Kong and Macao Residents (Non-Chinese Citizens)", "Listed as exempt", "Confirm that the traveller is entering on that document."],
        ["Group-visa holder or traveller eligible for group visa-free entry", "Listed as exempt", "The organising operator and border authority still control the group process."],
        ["Direct transit within 24 hours without leaving the port's restricted area", "Listed as exempt", "If the journey requires entry, baggage collection landside or an unprotected transfer, do not assume this category applies."],
        ["Traveller entering and leaving on the same cruise ship", "Listed as exempt", "Confirm the cruise and port procedure for the exact call."],
        ["Traveller using a fast lane", "Listed as exempt", "Do not assume ordinary eligibility for a fast lane from passport type alone."],
        ["Foreign employee of an exit-entry transport vehicle", "Listed as exempt", "This is an occupational category, not a general airline-passenger exemption."],
        ["Traveller formally eligible for the courtesy arrangement for centralized presentation of entry-exit documents", "Listed as exempt in the live official form reviewed on 20 August 2026", "This is a managed courtesy process. Do not infer eligibility from passport type or group travel; confirm it with the responsible organiser or immigration authority."],
      ],
    },
    {
      id: "eligibility-boundary",
      type: "callout",
      title: "The form does not answer whether you may enter",
      body: "Visa, visa-free entry, visa-free transit, passport validity, carrier boarding and the border officer's admission decision are separate questions. Complete the arrival card only after checking the entry basis for the exact passport and route. A successful submission screen is not approval of that basis.",
      tone: "warning",
    },
    {
      id: "where-heading",
      type: "heading",
      level: 2,
      text: "Choose the channel by reliability, not by marketing",
    },
    {
      id: "channel-comparison",
      type: "comparison",
      title: "Three official completion routes",
      columns: [
        {
          heading: "Before travel online",
          items: ["Use the NIA web service or another channel named in the current NIA notice", "Enter details from the final passport and confirmed journey record", "Save the submission evidence offline", "Recheck changed details before departure"],
        },
        {
          heading: "At the port electronically",
          items: ["Use the designated official QR code or port smart device", "Keep the passport and transport details ready", "Ask border-inspection staff when the workflow or language is unclear", "Allow time rather than assuming pre-filling removes the inspection queue"],
        },
        {
          heading: "Paper at the port",
          items: ["The NIA says paper cards remain available", "Copy document and journey details exactly", "Correct an error visibly or request a replacement card", "Keep this fallback when the phone, network or website fails"],
        },
      ],
    },
    {
      id: "timing-heading",
      type: "heading",
      level: 2,
      text: "Fill it when the entry record is stable",
    },
    {
      id: "timing-copy",
      type: "paragraph",
      text: "The NIA permits online filling before coming to China, but the notices reviewed for this guide do not state one universal filing deadline. The useful moment is after the passport, inbound service, entry port and first China address are sufficiently settled, yet early enough to fix a mismatch. Do not invent a flight number or hotel merely to submit sooner. If the live form displays a validity window or submission instruction, that current on-screen rule controls.",
    },
    {
      id: "prepare-heading",
      type: "heading",
      level: 2,
      text: "Prepare records before opening the form",
    },
    {
      id: "prepare-table",
      type: "table",
      caption: "A preparation pack that survives field and interface changes",
      columns: ["Record", "Copy from", "Common mismatch to prevent"],
      rows: [
        ["Name, sex, birth details and nationality", "The passport data page", "Typing a nickname, reversing names without following the form labels, or using a different nationality record"],
        ["Passport number, document type and validity", "The exact passport used for boarding and entry", "Confusing a letter with a number or using an expired/replaced passport"],
        ["Inbound transport and entry port", "The operating carrier's final itinerary", "Using the booking website's city name when the flight, train, ship or road port is different"],
        ["Arrival date", "The local date at the actual Chinese port", "Copying the departure date from the origin country or ignoring an overnight flight"],
        ["Purpose and entry basis when requested", "Visa, residence document or the checked visa-free route", "Treating the arrival card as the place to choose an unverified immigration status"],
        ["First address and contact in China", "Confirmed accommodation record or host details", "Entering a platform nickname instead of the property's official name and usable address"],
        ["Previous or onward journey information when requested", "Final tickets and route record", "Leaving an inconsistency between the form and the journey presented at inspection"],
      ],
    },
    {
      id: "fields-boundary",
      type: "callout",
      title: "Use the live official form as the field list",
      body: "Interfaces and conditional questions can change. This preparation table describes source records, not a frozen screenshot of every field. Answer only what the official form asks, use its help text, and do not send Homeground or an unofficial agent a passport scan merely to have the card typed for you.",
      tone: "neutral",
    },
    {
      id: "steps-heading",
      type: "heading",
      level: 2,
      text: "Complete the official workflow without losing the evidence",
    },
    {
      id: "steps-list",
      type: "list",
      ordered: true,
      items: [
        "Open the official NIA page from a saved government link. Check that the host is nia.gov.cn before entering passport data.",
        "Select the language you can read accurately. Keep the passport, inbound itinerary and first-stay record beside you.",
        "Copy identity and document data from the passport, not from memory or an old booking profile.",
        "Match the arrival service, Chinese port and local arrival date to the final operating itinerary.",
        "Enter the China stay information requested by the live form. If the first accommodation is not settled, settle it or plan to complete the card later rather than inventing an address.",
        "Review every summary screen against the three original records: passport, transport and accommodation. Pay special attention to document number, date and port.",
        "Submit only on the official service. Save the resulting confirmation, reference or QR display if one is presented, plus a screenshot of the official host and submission time.",
        "Keep the evidence offline and carry the passport and journey record. Follow the instructions at the actual border port; pre-filling does not replace inspection.",
      ],
    },
    {
      id: "group-warning",
      type: "callout",
      title: "One booking does not make one arrival card for everyone",
      body: "Check each traveller separately. Names, documents, exemptions and entry bases can differ within a family or tour. Do not copy one adult's passport number, exemption or China address into another person's record without checking it.",
      tone: "neutral",
    },
    {
      id: "change-heading",
      type: "heading",
      level: 2,
      text: "What to do when details change or the form fails",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "Recover the record instead of forcing a wrong submission",
      columns: ["Problem", "Immediate action", "Safe fallback"],
      rows: [
        ["Flight, ship, train, road port or arrival date changes", "Use the current official service to review whether the submission can be corrected or replaced", "Carry both the changed itinerary and the latest form evidence; ask at the port if the online record cannot be updated"],
        ["First hotel or host changes", "Replace the address if the live service permits, using the final confirmed record", "Explain the change truthfully at inspection and complete the current official or paper process as directed"],
        ["Typo in name, passport number or validity", "Do not leave a known identity mismatch; use the official correction/resubmission route shown", "Ask NIA through 12367 or border staff when the interface gives no clear correction path"],
        ["Official website will not load or the phone has no data", "Try the official channel on a secure connection without moving to a search advertisement", "Use the port's designated QR code or smart device, or request a paper card"],
        ["No confirmation was saved", "Return through the official channel and check the live service rather than paying a third party to retrieve it", "Bring all source records and complete the port process if the submission cannot be confirmed"],
        ["Duplicate submissions may exist", "Do not guess which one is active; keep the latest accurate evidence", "Show staff the records and follow the port's instruction"],
      ],
    },
    {
      id: "fraud-heading",
      type: "heading",
      level: 2,
      text: "Recover from a fake or paid arrival-card website",
    },
    {
      id: "fraud-list",
      type: "list",
      ordered: true,
      items: [
        "Stop the session. Do not send more passport images, payment details, verification codes or selfies.",
        "Record the website address, amount, time, receipt and messages without continuing to interact. This supports a bank, card-provider or platform dispute.",
        "If payment details were entered, contact the card issuer or payment provider through its official channel and follow its security instructions.",
        "Change any password reused on that website and protect the associated email account with a unique password and multi-factor authentication.",
        "Open the NIA service by typing or using the official government link and submit the accurate arrival information there. A paid receipt from another site is not official proof.",
        "For immigration-process questions, contact the China Immigration Service Hotline 12367. For suspected identity or payment crime, use the appropriate police, bank and platform reporting channels in the relevant country.",
      ],
    },
    {
      id: "privacy-warning",
      type: "callout",
      title: "Treat passport data as a sensitive identity record",
      body: "Do not post the completed card, QR code, passport page, visa, boarding pass or hotel booking publicly. When asking for help, redact document numbers, dates of birth, barcodes, booking references, addresses and contact details. Homeground can explain the workflow without collecting those records.",
      tone: "warning",
    },
    {
      id: "boundary-heading",
      type: "heading",
      level: 2,
      text: "Keep five different arrival tasks separate",
    },
    {
      id: "boundary-table",
      type: "table",
      caption: "The arrival card covers one task, not the whole border journey",
      columns: ["Task", "Responsible authority", "What this guide covers"],
      rows: [
        ["Visa, visa-free or transit eligibility", "NIA, the competent Chinese mission and the operating carrier for its boarding check", "No passport-specific eligibility is copied into the arrival-card workflow"],
        ["Online arrival-card information", "National Immigration Administration", "This page explains the free channels, preparation, exemptions and recovery"],
        ["Border inspection and admission", "Immigration inspection at the port", "A submitted card does not guarantee admission or a processing time"],
        ["Customs and quarantine declaration", "General Administration of Customs and relevant quarantine rules", "Food, cash, medicine and baggage declarations are not answered by the immigration card"],
        ["Hotel or non-hotel accommodation registration after entry", "Hotel or the traveller/host under the current accommodation-registration process", "It is a later stay-registration task, not the arrival card"],
      ],
    },
    {
      id: "final-checklist-heading",
      type: "heading",
      level: 2,
      text: "Five-minute check before departure",
    },
    {
      id: "final-checklist",
      type: "list",
      items: [
        "The entry basis has been checked separately for the exact passport and route.",
        "The traveller either needs a card or fits a named NIA exemption with the qualifying document.",
        "The submission used an official nia.gov.cn channel and no fee was paid.",
        "Passport, operating itinerary, entry port/date and first China address match the latest records.",
        "Submission evidence and the source records are available offline, while a port QR/device or paper card remains the fallback.",
      ],
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue the arrival plan without duplicating the rules",
      items: [
        { label: "China entry requirements", href: "/guides/china-entry-requirements/", description: "Check visa, visa-free and transit rules in the separate entry guide." },
        { label: "Passport validity and blank pages", href: "/guides/china-passport-validity-and-blank-pages/", description: "Audit the physical passport and separate airline, visa and border rules." },
        { label: "China Customs red or green channel", href: "/guides/china-customs-red-green-channels/", description: "Decide whether baggage needs a Customs declaration after immigration." },
        { label: "Can a China arrival day support a timed booking?", href: "/guides/china-arrival-day-booked-anchor-or-flexible-block/", description: "Protect the first day without assuming the online card removes border-processing uncertainty." },
        { label: "Hotel check-in for foreign travellers", href: "/guides/foreigners-china-hotel/", description: "Keep hotel acceptance and accommodation registration as the next task." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources and image credit",
      items: [
        { label: "Beware of fraudulent arrival-card websites", url: "https://en.nia.gov.cn/n147418/n147463/c191530/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-20" },
        { label: "Official online arrival-card service", url: "https://s.nia.gov.cn/ArrivalCardFillingPC/", publisher: "National Immigration Administration Government Service Platform", reviewedAt: "2026-08-20" },
        { label: "2025 announcement implementing online arrival-card filling and its original seven exemptions", url: "https://en.nia.gov.cn/n147413/c187308/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-20" },
        { label: "How to submit the arrival card online", url: "https://en.nia.gov.cn/n147418/n147463/c195170/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-08-20" },
        { label: "Hero: Beijing Capital International Airport T1 arrival hall — Tyg728 (CC BY-SA 4.0); resized by Homeground", url: "https://commons.wikimedia.org/wiki/File:Beijing_Capital_International_Airport_T1_Arrival_hall_20161124.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-20" },
        { label: "Hero photograph licence: CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-20" },
      ],
    },
  ],
};

export default body;
