import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Downtown Dunhuang is the safer default when fixed Mogao, city-evening, luggage and onward-transport tasks interact. Choose the Mingsha entrance area when desert evenings are the priority and the exact property's gate, road, reception and room claims are verified. Neither ‘near Mogao’ nor ‘desert view’ is proof.",
    },
    {
      id: "direct-answer",
      type: "callout",
      title: "Use the least movable appointment as the anchor",
      tone: "decision",
      body: "Write the confirmed Mogao reporting time and location first. As reviewed on 4 September 2026, the official reserved-visit chain begins at the Mogao Caves Digital Exhibition Center (莫高窟数字展示中心), not the protected cave area's map pin; follow the latest official instruction for your date, product and booking record. Then place the Mingsha evening, arrival, departure and bags around it. Keep one base unless two nights protect two fixed tasks.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This page starts after Dunhuang and total nights are chosen. It does not choose trip length, book Mogao, publish Mingsha access, plan a Silk Road route, rank hotels, quote prices or promise transport.",
    },
    {
      id: "anchors-heading",
      type: "heading",
      level: 2,
      text: "Write four anchors before opening a hotel map",
    },
    {
      id: "anchor-ledger",
      type: "table",
      caption: "A base must protect the least flexible link",
      columns: ["Anchor", "Record", "Why it changes the base"],
      rows: [
        ["Mogao appointment", "Date, report time, official first checkpoint, required original travel document and booking record", "The timed first stop outranks a hotel's claimed cave distance"],
        ["Mingsha evening", "Date, official gate, last admission/verification window from that day's notice and weather fallback", "Nearby helps only if the intended entrance and return route operate"],
        ["Arrival and departure", "Airport or station, service number, direction, handoff and backup contact", "A transport-facing night may beat a scenic-facing night"],
        ["Luggage", "Count, largest size, custodian, storage point and collection deadline", "Mogao restricts large luggage in the protected cave area, so bags need their own chain"],
      ],
    },
    {
      id: "map-correction",
      type: "callout",
      title: "‘Near Mogao Caves’ can point to the wrong first stop",
      tone: "warning",
      body: "As reviewed on 4 September 2026, Dunhuang Academy directs reserved visitors to the Digital Exhibition Center at 8899 Yangguan East Road, not the protected cave area, which lacks visitor ticketing and parking. Search sites may rank stays by cave-site distance. Confirm the current first checkpoint in your official booking, then check the route from the real reception to it.",
    },
    {
      id: "bases-heading",
      type: "heading",
      level: 2,
      text: "Choose the base that removes a fragile handoff",
    },
    {
      id: "base-matrix",
      type: "table",
      caption: "The useful label is the complete route, not the neighbourhood name",
      columns: ["Base", "Best fit", "What it buys", "What you trade"],
      rows: [
        ["Downtown Dunhuang", "Mixed Mogao, city-evening and onward plan", "City dining and a neutral base for different directions", "A separate verified Mingsha return trip"],
        ["Mingsha entrance area", "A desert evening or following visit decides", "A shorter property-to-gate chain when verified", "Less certainty for city errands, late returns and onward handoffs"],
        ["Remote or ‘desert’ property", "The stay matters and the seller, actual lodging operator, sleeping address and access are proven", "A setting unlike an urban room", "Misleading images, vague pins, weather, road, late reception and unclear lodging status"],
        ["Split stay", "Two nights protect two different fixed anchors and bag transfer is solved", "One transport-facing and one desert-facing night", "Two registrations, two cancellation states, a bag move and lost usable time"],
      ],
    },
    {
      id: "night-plan-heading",
      type: "heading",
      level: 2,
      text: "Test the decision night by night",
    },
    {
      id: "night-plan",
      type: "list",
      ordered: true,
      items: [
        "Mark every fixed item: the Mogao slot, booked train or flight, and confirmed same-day scenic-area requirement.",
        "Mark flexible preferences separately: night market, desert sunset, early walk or room view. Important does not mean guaranteed.",
        "Draw the hardest day from room to first checkpoint and final checkpoint back to reception, using the correct Mingsha gate.",
        "Place every bag during Mogao, after checkout and before departure. Do not assume an attraction, driver or camp will hold it.",
        "Choose the single base with the fewest unsupported links. Split only when moving removes more risk than it creates.",
      ],
    },
    {
      id: "proof-heading",
      type: "heading",
      level: 2,
      text: "Make a ‘desert stay’ prove what it is",
    },
    {
      id: "property-proof",
      type: "list",
      ordered: true,
      items: [
        "Separate booking seller from lodging operator. Match its Chinese name, accommodation type, sleeping address, pin, staffed reception/telephone and registration entity to the order and reply.",
        "Request a dated sequence from public road to reception and offered room. Exclude guests, documents, room numbers and keycards.",
        "Separate area, building and room. ‘Near Mingsha’, ‘in the desert’ and dune photos prove none of the reception, assigned building, view or gate route.",
        "Ask which gate, whether road and reception work at arrival, and who answers if the vehicle fails.",
        "Confirm tagged luggage custody, delivery and collection; carry passport, medicine, devices and one-night essentials.",
        "Confirm room, occupancy, beds, bathroom, deadline and weather/maintenance fallback.",
        "Obtain the actual lodging operator's written confirmation of original-passport check-in and who completes accommodation registration. A seller or experience operator, platform label and camp name are neither lodging proof nor law.",
        "Use a traceable payment channel; save the order and promises. Never chat passport, card or verification-code data.",
      ],
    },
    {
      id: "property-warning",
      type: "callout",
      title: "A view photo is not a location certificate",
      tone: "warning",
      body: "A current exterior, reception route and exact-room evidence answer different questions. Old reviews or an OTA map may prompt checks but cannot settle identity. If name, address, reception, room type, late contact and passport check-in remain unconfirmed by the cancellation/change deadline—or before non-cancellable payment—use a verified alternative.",
    },
    {
      id: "luggage-heading",
      type: "heading",
      level: 2,
      text: "Plan luggage as a separate itinerary",
    },
    {
      id: "luggage-ledger",
      type: "table",
      caption: "A base is convenient only when every bag has a custodian",
      columns: ["Situation", "Verify", "Base consequence"],
      rows: [
        ["Mogao before check-in", "Pre-room hotel storage, tag, collection window and Center route", "Downtown wins if it removes an unsupported handoff"],
        ["Mogao after checkout", "Post-checkout custody and pre-departure collection", "Rely on Center storage only if current official instructions for your date confirm size, acceptance time, collection point and a return chain; otherwise keep hotel or other verified custody"],
        ["Split stay", "Custodian, named vehicle/contact and failed-delivery response", "Keep one base if transfer consumes the benefit"],
        ["Remote property", "Road-to-reception access, vehicle capacity, staff custody and departure retrieval", "A scenic location loses if luggage depends on an informal promise"],
      ],
    },
    {
      id: "needs-heading",
      type: "heading",
      level: 2,
      text: "Let the traveller with the hardest route decide",
    },
    {
      id: "needs-table",
      type: "table",
      caption: "Distance alone cannot answer for a family or mobility need",
      columns: ["Need", "Starting direction", "Evidence that can reverse it"],
      rows: [
        ["Family with children", "Prefer one base and a simple meal–reception–bathroom chain", "Written occupancy, beds, child document/admission process, vehicle restraint and room route; discuss details privately later"],
        ["Older or slower traveller", "Minimise queues, vehicle changes and uncertain walks", "Drop-off surface, staffed reception, lift/stairs, rest points, bathroom and confirmed return"],
        ["Wheelchair or mobility device", "No area-wide default", "Measured road–reception–lift–door–bathroom route and usable backup; change property if unconfirmed"],
        ["Large or several bags", "Prefer the base with written storage and one accountable handoff", "Tagged custody and a vehicle that fits travellers and bags may justify a Mingsha-side or remote stay"],
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Two reasonable trips can reach opposite answers",
    },
    {
      id: "scenario-downtown",
      type: "list",
      ordered: false,
      items: [
        "A first-timer has one fixed Mogao slot, a flexible Mingsha evening, a night-market meal and next-day rail departure.",
        "Mingsha's gate still needs a same-day check; a downtown property confirms storage, passport check-in, a planned departure and vehicle/public-transport chain to the Digital Exhibition Center, a failed-ride contact and the next-day handoff.",
        "Decision: stay downtown. It protects the appointment, bags and departure; Mingsha stays a conditional excursion.",
      ],
    },
    {
      id: "scenario-mingsha",
      type: "list",
      ordered: false,
      items: [
        "A traveller reserves two evenings for Mingsha, has no early departure and visits Mogao on another day.",
        "An entrance-area property confirms identity, gate, reception route, room, late desk, bags, passport registration, plus the separate-day departure and verified transport chain to the Digital Exhibition Center with a failed-ride fallback.",
        "Decision: Mingsha can win because it protects the repeated desert anchor without relying on ‘desert view’.",
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Recover the plan when one link changes",
    },
    {
      id: "failure-ledger",
      type: "table",
      caption: "Protect the fixed task first; settle the disputed promise second",
      columns: ["Failure", "Immediate action", "Accommodation recovery"],
      rows: [
        ["Mogao instruction changes", "Use the current official booking/notice to reconfirm the first checkpoint, time and address", "Keep a base reaching that checkpoint; use the Center only while the booking still specifies it"],
        ["Mingsha access changes", "Check the same-day official notice and usable route", "Change the visit under actual terms; proximity guarantees nothing"],
        ["Identity or view mismatch", "Stop payment/documents; save listing, messages, images and location", "Use the fallback; request a written selling-channel remedy"],
        ["Late reception or vehicle fails", "Call the staffed number and platform; stay at a safe public point", "Use the option with confirmed late check-in, registration and cancellation state"],
        ["Passport check-in is refused", "Identify the lodging/registration operator; request a written reason, show policy and retain the passport", "Use a passport-confirmed hotel, keep receipts and follow the refusal guide; 12367 or 12345 may help"],
        ["Bag, route or room fails", "Record the handoff, barrier or maintenance; request a workable room or bags", "Accept replacement only if decisive needs work; otherwise change under documented terms"],
      ],
    },
    {
      id: "dynamic-callout",
      type: "callout",
      title: "Recheck gates, hours and the reporting chain",
      tone: "warning",
      body: "Official pages were reviewed on 4 September 2026. No current official notice establishing September Mingsha gate and closing arrangements was retrieved, so none are published here. Mogao instructions, Mingsha access, events, weather, ground transport and property operations can change. Recheck before the cancellation/change deadline and on the day.",
    },
    {
      id: "final-checklist",
      type: "list",
      ordered: true,
      items: [
        "Reconfirm the current booking's first checkpoint, time and address; as reviewed, it is the Digital Exhibition Center, not the cave pin.",
        "Confirm Mingsha gate, verification window, same-day notice and weather fallback; assume no event.",
        "Write arrival, departure and each bag handoff.",
        "Compare complete routes, not straight-line distance.",
        "Verify identity, address, reception, room, route, late contact and passport check-in in writing.",
        "Verify family or accessibility route and exact room privately; filters prove nothing.",
        "Keep one base unless moving protects a fixed anchor after counting bags and cancellation risk.",
        "Save a verified candidate or held fallback; record cancellation cost and release trigger.",
      ],
    },
    {
      id: "consultation-boundary",
      type: "callout",
      title: "If you want a human to compare the route",
      tone: "neutral",
      body: "The initial form should contain only minimum non-sensitive context: dates, public base or property names, traveller and room counts, confirmed Mogao slot or travel direction, and broad budget. Ask to discuss family or accessibility later, but do not submit children's exact ages, mobility, medical or accessibility details, passport/ID, booking/payment records, or identifiable supplier-sharing information. Use an appropriate human follow-up, with separate consent before supplier sharing. This is not live inventory, booking or transport and does not guarantee price, availability, foreign-guest acceptance, room type, accessibility, property identity or view, late reception/check-in, Mogao or Mingsha admission/opening, luggage, transfer, connection success or safety.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue with the guide for your next decision",
      items: [
        { label: "Mogao Caves independent visit workflow", href: "/guides/mogao-caves-independent-visit-workflow/", description: "Handle official booking, foreign-passport verification, the Digital Exhibition Center sequence and visit-day recovery." },
        { label: "Xi'an–Lanzhou–Dunhuang Silk Road route", href: "/guides/xian-lanzhou-dunhuang-silk-road-route/", description: "Choose city order, total nights and gateway logic before selecting the within-Dunhuang base." },
        { label: "Private transfer or public transport", href: "/guides/china-private-transfer-or-public-transport/", description: "Choose transport only after the exact hotel reception, station, airport and attraction checkpoints are known." },
        { label: "Foreign-guest hotel registration and refusal recovery", href: "/guides/foreigners-china-hotel/", description: "Separate the national registration rule from platform display and recover if a front desk refuses check-in." },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official and primary sources reviewed",
      items: [
        { label: "2026 Mogao Caves opening and reservation notice", url: "https://www.dha.ac.cn/info/1020/7498.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-09-04" },
        { label: "Mogao Caves visitor sequence, luggage and weather information", url: "https://www.dha.ac.cn/skxl/mgk.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-09-04" },
        { label: "Statement on unauthorized Mogao ticket sales", url: "https://www.dha.ac.cn/info/1018/7786.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-09-04" },
        { label: "Dated 2026 Mingsha access adjustment", url: "https://www.gswbj.gov.cn/a/2026/04/16/28007.html", publisher: "Gansu Provincial Department of Culture and Tourism", reviewedAt: "2026-09-04" },
        { label: "2026 Mingsha starlight performance notice", url: "https://www.gswbj.gov.cn/a/2026/04/13/27966.html", publisher: "Gansu Provincial Department of Culture and Tourism", reviewedAt: "2026-09-04" },
        { label: "Dunhuang attractions and broad geographic relationships", url: "https://www.gswbj.gov.cn/a/2024/09/10/22009.html", publisher: "Gansu Provincial Department of Culture and Tourism", reviewedAt: "2026-09-04" },
        { label: "Dunhuang Mogao International Airport profile", url: "https://www.caac.gov.cn/GYMH/MHGK/GJKAYSJC/XBDQ/GS/202404/t20240417_223898.html", publisher: "Civil Aviation Administration of China", reviewedAt: "2026-09-04" },
        { label: "Dunhuang Night Market current city-evening context", url: "https://www.gswbj.gov.cn/a/2026/07/29/29045.html", publisher: "Gansu Provincial Department of Culture and Tourism", reviewedAt: "2026-09-04" },
        { label: "Exit and Entry Administration Law, Article 39", url: "https://www.nia.gov.cn/n794014/n1050181/n1050479/c1013311/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-04" },
        { label: "Government response on hotels receiving overseas visitors", url: "https://www.gov.cn/hudong/202405/content_6952770.htm", publisher: "The State Council of the People's Republic of China", reviewedAt: "2026-09-04" },
        { label: "Notice on facilitating accommodation for overseas visitors", url: "https://www.mofcom.gov.cn/zcfb/zc/art/2024/art_2389dfd945704c8f8247149f918bcaef.html", publisher: "Ministry of Commerce of the People's Republic of China", reviewedAt: "2026-09-04" },
        { label: "Hero: Mingsha Mountain by Yanxutong1215, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:鸣沙山.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
