import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "For most first nights, late arrivals, one-day visits and uncertain high-altitude tolerance, start in Shangri-La Town (Riwa), Daocheng County, Sichuan. Choose Yading Village only when you have already adjusted reasonably well, will tour on two consecutive mornings, and the exact property has confirmed its current stop or pickup, luggage handoff and reception plan. The village sits farther inside the scenic-area transport chain, but it is not the trailhead and does not remove onward park transport. If a flight or road connection fails before you reach the gateway town, stop chasing an unconfirmed night transfer and use the nearest verified legal accommodation at the safe hub where you actually are.",
    },
    {
      id: "short-answer",
      type: "callout",
      title: "The decision in one minute",
      tone: "decision",
      body: "Town is the resilient default: it is on the relatively lower gateway side, makes a late arrival easier to recover and avoids committing to an inner-area stay before you know how your body and the day's operations are behaving. Village is a conditional convenience choice: it can remove one repeated gateway-to-village segment across two touring days, but only after you confirm that the current park chain, property access and your health make that gain real. If there is one touring day, one uncertain arrival or one uncertain traveller, do not add a hotel move merely to sleep ‘inside’.",
    },
    {
      id: "name-warning",
      type: "callout",
      title: "Do not book the wrong Shangri-La",
      tone: "warning",
      body: "This comparison uses Shangri-La Town (Riwa) in Daocheng County, Sichuan—the gateway settlement for the Daocheng Yading Scenic Area. It is not Shangri-La City in Yunnan. Save the Chinese name 稻城县香格里拉镇, the full property address and its map pin before paying; an English result that says only ‘Shangri-La’ is not enough.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This page begins after Daocheng Yading is already in the itinerary. It does not decide whether to visit, build a hiking route, give medical advice, rank hotels, quote prices or promise current tickets, roads, buses, rooms or foreign-guest acceptance. Its job is narrower: choose the sleeping base that best supports a confirmed arrival and sight order, then keep a workable recovery if conditions change.",
    },
    {
      id: "route-heading",
      type: "heading",
      level: 2,
      text: "Understand the chain before choosing the bed",
    },
    {
      id: "route-table",
      type: "table",
      caption: "A village booking shortens one part of the chain; it does not erase the rest",
      columns: ["Place or handoff", "What it means for the stay", "What remains after it", "What to verify now"],
      rows: [
        ["Shangri-La Town (Riwa)", "The relatively lower gateway/support base and the practical town-side fallback", "The scenic-area visitor-centre, controlled entry and park-transport chain", "Exact property-to-visitor-centre route, reception, licensed transport and morning operating notice"],
        ["Daocheng Yading Visitor Centre", "The town-side public gateway, not a hotel district label", "Checks, transfers and the current scenic transport toward inner nodes", "Reservation/passport workflow, opening, boarding point, luggage rule and last workable connection"],
        ["Yading Village", "An inhabited inner settlement where guest accommodation exists", "Onward park transport and walking links toward Zhaguanbeng (扎灌崩), Chonggu Temple and the chosen route", "Whether current services stop for the named property, exact walking/vehicle handoff, steps and late-arrival limit"],
        ["Zhaguanbeng and Chonggu area", "The official route framework places an inner touring handoff here; it is not proof that a village room is beside the trail", "The selected short, middle or long route and its current restrictions", "Which route is open, the current stop, the latest return chain and what to do if the harder route closes"],
      ],
    },
    {
      id: "altitude-heading",
      type: "heading",
      level: 2,
      text: "Let altitude veto convenience",
    },
    {
      id: "altitude-veto",
      type: "callout",
      title: "Relatively lower does not mean safe",
      tone: "warning",
      body: "A 2026 Daocheng County notice describes the core touring area as roughly 3,700–4,700 metres. Shangri-La Town is relatively lower than Yading Village and the inner touring area, so it is usually the more conservative first-night base—but neither place can prevent altitude illness. Do not move higher merely to save a transport segment. If symptoms appear or worsen, stop further ascent and strenuous activity, seek professional or local emergency advice and move lower if instructed. This page does not diagnose symptoms or recommend medication.",
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "Choose from the confirmed sight order",
    },
    {
      id: "decision-matrix",
      type: "table",
      caption: "Base decision by trip pattern",
      columns: ["Confirmed pattern", "Town base", "Village base", "Best starting decision"],
      rows: [
        ["Arrive late or after an uncertain road/flight connection", "Keeps the first check-in on the gateway side and leaves more recovery options", "Adds a controlled-entry and park-transport dependency before the room", "Town; do not promise an inner transfer until the property and current service confirm it"],
        ["One touring day", "One outward and return chain, with no hotel move", "The saved segment is used only once and onward transport still remains", "Town unless a verified village stay solves another fixed need without raising health or access risk"],
        ["Two consecutive touring days after acclimatization", "Repeats the gateway-to-inner chain", "May remove one repeated town-to-village segment", "Village becomes reasonable only when both mornings, re-entry, luggage and the current stop are confirmed"],
        ["Family, older traveller, mobility constraint or heavy luggage", "Avoids entering the scenic transport chain before sleep; every backup room still needs property-by-property verification", "Extra handoffs, steps or room limitations may cancel the location gain", "Default to the property with the fully verified door-to-room and emergency chain, usually town"],
        ["Weather, route opening or physical condition uncertain", "Easier to keep or change the plan without an inner-area checkout", "A closure may erase the expected convenience", "Town; decide again only after the latest official notice and a stable first day"],
      ],
    },
    {
      id: "split-heading",
      type: "heading",
      level: 2,
      text: "Does one hotel move earn its place?",
    },
    {
      id: "split-table",
      type: "table",
      caption: "A split stay is an operating choice, not a sightseeing badge",
      columns: ["Plan", "Keep one town base", "Move once to the village", "Cost that can overturn the move"],
      rows: [
        ["One park day", "Almost always simpler", "Rarely useful", "Packing, two receptions and a handoff that saves no repeated journey"],
        ["Two park days, uncertain adaptation", "Protects the lower first night and one luggage base", "Consider only after a stable first day", "A same-day room, transfer or re-entry assumption may fail"],
        ["Two park days, already acclimatized", "Still works if the early chain is reliable", "Can be efficient when the exact property confirms the whole chain", "Checkout time, luggage custody and onward-transport cutoff"],
        ["Early departure after the final tour", "Best when the departure vehicle starts town-side", "Useful only when the current, legal return chain is confirmed end to end", "Verify the operator, pickup point, luggage, latest connection and road permission; a property promise alone is not transport proof"],
      ],
    },
    {
      id: "property-heading",
      type: "heading",
      level: 2,
      text: "Verify the exact property, not the words ‘inside Yading’",
    },
    {
      id: "property-checklist",
      type: "list",
      ordered: true,
      items: [
        "Request the full Chinese property name, Chinese street or village address, map pin and a staffed contact. Confirm that it is in Yading Village or Daocheng's Shangri-La Town—not Daocheng county seat and not Yunnan.",
        "Ask for the current public transport stop or legal pickup point and a step-by-step description from that point to reception. ‘Near the entrance’ is not a route.",
        "Confirm the latest arrival the property can actually receive, who meets the guest if needed and what happens when the park bus, road or flight is delayed.",
        "Ask how large luggage moves across every handoff, whether stairs or rough lanes intervene, where bags stay during a touring day and who accepts custody.",
        "Confirm foreign-guest check-in for the named travellers and dates in writing, while treating the reply as property evidence rather than a national rule.",
        "Confirm the booked room configuration and the features that matter: real heating/hot water arrangements, power, bathroom, bed setup, lift or steps and an accessible route if required. Do not infer them from an area label.",
        "Request current, dated photographs or measurements when a room or access feature is decisive. Reconfirm if the assigned room changes.",
        "Keep ticket and scenic-transport charges, eligibility and booking as separate questions; never assume an admission promotion includes the bus component or a second entry.",
        "Save cancellation and change terms, the official operations channel and one acceptable town-side fallback before the free-cancellation window closes.",
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Three realistic decisions",
    },
    {
      id: "scenario-one-heading",
      type: "heading",
      level: 3,
      text: "Scenario 1: first high-altitude stop, one touring day",
    },
    {
      id: "scenario-one",
      type: "list",
      ordered: true,
      items: [
        "Choose a verified Shangri-La Town property with a workable visitor-centre connection.",
        "Use the arrival evening for a quiet check-in rather than adding an inner-area transfer.",
        "Recheck the official opening and route notice before departure and keep the less demanding open route as a fallback.",
        "Return to the same room; the convenience of avoiding a second check-in usually exceeds the one-time village segment saved.",
      ],
    },
    {
      id: "scenario-two-heading",
      type: "heading",
      level: 3,
      text: "Scenario 2: two touring days, already acclimatized",
    },
    {
      id: "scenario-two",
      type: "list",
      ordered: true,
      items: [
        "Confirm that the current operation permits the intended two-day sequence; do not use an old second-entry post as permission.",
        "Choose Yading Village only after the property documents the stop, reception, luggage and return chain.",
        "Treat the first morning's gain as removal of one transport segment, not as direct trail access or a guaranteed empty queue.",
        "Keep a town-side fallback and be willing to abandon the move if symptoms, weather or a route suspension changes the value of day two.",
      ],
    },
    {
      id: "scenario-three-heading",
      type: "heading",
      level: 3,
      text: "Scenario 3: family with large bags and an early onward departure",
    },
    {
      id: "scenario-three",
      type: "list",
      ordered: true,
      items: [
        "Keep one town-side property whose set-down, reception, assigned room and onward pickup are verified.",
        "Carry only a day bag through the park chain and agree luggage custody with the hotel.",
        "Match the route to the slowest traveller and the current official opening; do not make a village move the price of seeing a second route.",
        "Protect the departure connection by sleeping where the licensed vehicle actually begins, not where a map looks closest to the mountains.",
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Failure recovery",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Recover the trip without defending a base that no longer works",
      columns: ["Failure", "Immediate action", "Record to keep", "Accommodation response"],
      rows: [
        ["A connection breaks before town, or you reach town after the inner transfer", "Before the gateway, stop chasing unconfirmed night transport and use the nearest verified legal accommodation at your current safe hub; if already in town, contact the property and use only the confirmed local chain", "Delay notice, written property reply, time and safe pickup details", "Daocheng county seat/Jinzhu Town may be a disruption-only fallback when that is where you are; otherwise use the verified town fallback and move only after the next day's operation is confirmed"],
        ["Weather or safety notice closes a route or the whole area", "Follow the current official notice and change the ticket through the channel it specifies", "Notice, original booking, change/refund communication", "Stay town-side if the village convenience has disappeared; do not cite a historic refund case as today's promise"],
        ["Bus stop, pickup or luggage handoff differs from the listing", "Pause at the official staffed point and call the property/platform rather than following an unknown driver", "Listing, pin, message and actual handoff without exposing private documents", "Request a workable alternative or relocate through the booking channel"],
        ["Front desk cannot check in or the room differs materially", "Use the separate foreign-guest refusal-recovery process; preserve the reservation and exact replies", "Booking, property confirmation and front-desk outcome; never post passport data publicly", "Choose the nearest verified fallback that protects health and the next official connection"],
        ["Symptoms appear or worsen", "Stop further ascent and hard activity; seek professional/local emergency advice and descend if instructed", "Only the minimum medical record needed for care or insurance, kept private", "Do not remain in or move to the village to defend a reservation; convenience is no longer the decision"],
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      title: "Recheck the operating day",
      tone: "neutral",
      body: "Reviewed 1 September 2026: current county material supports real-name capacity management, high-altitude route categories and a visitor-service/transport chain, while older official records establish the broad town–village–inner-node geography. Exact opening, reservation method, foreign-passport handling, bus stops and runs, re-entry, ticket and transport treatment, controlled-road access, weather restrictions and property operations can change. Check the current Daocheng County or scenic-area notice and the named property immediately before travel. No fixed timetable, journey time, price, availability or access promise is made here.",
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "Final booking check",
    },
    {
      id: "booking-checklist",
      type: "list",
      items: [
        "The full name Shangri-La Town (Riwa), Daocheng County, Sichuan—not Yunnan",
        "Arrival time plus a legal, confirmed route to the actual reception",
        "Current opening, reservation/passport process and park-transport chain",
        "One- or two-day sight order and whether a repeated segment is genuinely removed",
        "A health-first decision that never treats the lower base as a safety guarantee",
        "Current stop/pickup, steps, luggage handoff and last workable connection",
        "Foreign-guest check-in, assigned room and any access feature confirmed by the property",
        "Separate ticket, transport and re-entry evidence rather than an old combined claim",
        "Cancellation terms and one verified town-side fallback",
      ],
    },
    {
      id: "consultation-boundary",
      type: "callout",
      title: "If you want a human base check",
      tone: "neutral",
      body: "In the initial planner, send only minimum non-sensitive context: travel dates, Daocheng Yading touring days, the public bases you are comparing, traveller and room counts, arrival/departure direction and an optional broad budget. You may say that you want to discuss family or accessibility arrangements later, but do not submit children's exact ages; mobility, medical or accessibility details; passport or identity documents; booking or payment records; or identifiable information intended for a hotel, driver, DMC or other supplier. Those details require a separate human follow-up, an appropriate purpose and consent; nothing is shared with a supplier without separate consent. This is not a live inventory or transport service and does not guarantee price, availability, foreign-guest acceptance, room type, accessibility suitability, park entry, road or bus operation, luggage transfer or high-altitude suitability.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue the accommodation decision",
      items: [
        {
          label: "Browse China accommodation decisions",
          href: "/stay/",
          description: "Compare other stay areas, property types and recovery workflows.",
        },
        {
          label: "Prepare for foreign-guest check-in or refusal",
          href: "/guides/foreigners-china-hotel/",
          description: "Separate the registration rule from a platform label and recover if the front desk cannot check you in.",
        },
        {
          label: "Choose between a minsu and a hotel",
          href: "/guides/minsu-homestay-or-hotel-china/",
          description: "Verify reception, privacy, room and recovery differences before relying on a village property type.",
        },
        {
          label: "Verify an actually usable accessible room",
          href: "/guides/china-accessible-hotel-room-verification/",
          description: "Check the street-to-room chain with measurements and a backup room or property.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Government, scenic-area, safety and image sources",
      items: [
        {
          label: "2026 Daocheng Yading operations and visitor-service notice",
          url: "https://www.daocheng.gov.cn/dcyw/article/727365",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Daocheng County administrative divisions",
          url: "https://www.daocheng.gov.cn/xzqh/article/713650",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Scenic road environmental assessment and route sequence",
          url: "https://www.daocheng.gov.cn/dcxrmzf/c102435/201412/bc43497d98f44a7c83133bf951ea09cf.shtml",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Daocheng tourism development planning",
          url: "https://www.daocheng.gov.cn/dcxrmzf/c102548/201611/535e102ad1fc4747bbd84564b4b2978a.shtml",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Yading Village homestay development report",
          url: "https://www.daocheng.gov.cn/lydt/article/697371",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Official Daocheng Yading booking and notice page",
          url: "https://www.yadingtour.com/book/providerIndex.action?iscenicid=1",
          publisher: "Daocheng Yading Scenic Area",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Official historic Daocheng Yading touring guide",
          url: "https://www.yadingtour.com/home/showArticle.action?article.amid=82",
          publisher: "Daocheng Yading Scenic Area",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Daocheng enforcement against unlicensed passenger transport",
          url: "https://www.daocheng.gov.cn/bmdt/article/709007",
          publisher: "Daocheng County People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Official high-altitude travel safety notice",
          url: "https://www.shannan.gov.cn/zjsn/snly/jzcs/202608/t20260821_175356.html",
          publisher: "Shannan Municipal People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Historic severe-weather closure notice",
          url: "https://cn.yadingtour.com/e-news/notice/838-2023-12-08-4",
          publisher: "Daocheng Yading Scenic Area",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Hero: Yading Village by fsyzh, CC BY 3.0",
          url: "https://commons.wikimedia.org/wiki/File:%E4%BA%9A%E4%B8%81%E6%9D%91_-_panoramio.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-09-01",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
