import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body: StructuredPageBody = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "For most travellers the Beijing–Xi'an decision is not “4 hours on rails versus 2 in the air” — it is which mode loses fewer hours at the edges. The fastest Beijing West → Xi'an North services cover the roughly 1,200 km corridor in about 4h10m–4h30m with a metro ride waiting at each end (example timings reviewed August 2026). Flying cuts the airborne leg to around two hours but adds two airports, earlier check-in and a 60-plus-minute airport-to-city transfer in Xi'an, so door-to-door totals usually converge — and the tie-breaker is almost always where your hotels sit and what your luggage is doing.",
    },
    {
      id: "first-steps",
      type: "list",
      ordered: true,
      items: [
        "Locate both hotels first: central Beijing near a rail link favours the train; a hotel already beside Capital or Daxing airport favours flying.",
        "Check the train pairing Beijing West (北京西站) → Xi'an North (西安北站) for your date — those exact stations carry the fast G-services; a few departures leave from Fengtai (北京丰台站).",
        "If flying, identify which Beijing airport your fare uses before pricing anything: Capital (PEK) and Daxing (PKX) sit on opposite sides of the city.",
        "Build one door-to-door ledger per mode using the seven-stage table below; do not compare onboard minutes alone.",
        "Decide with your heaviest constraint: checked luggage, an early next-morning departure, or a same-day connection to another city usually picks the winner.",
        "Buy flexible-where-affordable: on a 4.5-hour corridor a missed fixed ticket costs far more than the saving.",
        "Save both Xi'an station names in Chinese — 西安北站 and 西安站 are different stations about 10 km apart serving different networks.",
      ],
    },
    {
      id: "ledger-heading",
      type: "heading",
      level: 2,
      text: "One ledger, two modes",
    },
    {
      id: "ledger-table",
      type: "table",
      caption: "Door-to-door stages compared (example timings, reviewed August 2026)",
      columns: ["Stage", "High-speed rail", "Flight"],
      rows: [
        ["City edge to gateway", "15–40 min to Beijing West by metro/taxi from central districts", "60–90 min to Capital or Daxing depending on side of city"],
        ["Security + documents", "Station security plus gate entry; passport works end to end", "Airport security plus airline check-in cut-offs (often 45+ min domestic)"],
        ["Buffer recommended", "30–40 min", "90 min or more"],
        ["Line-haul", "≈4h10m fastest; 4h20m–5h50m typical band", "≈2h airborne"],
        ["Arrival gateway", "Xi'an North — Metro Line 2/4 into the centre, ≈30 min example to the Bell Tower area", "Xianyang XIY — ≈60–75 min road or airport intercity rail into central Xi'an"],
        ["Weather exposure", "Corridor delays possible but rare total stoppage", "Thunderstorm/visibility cancellations happen seasonally"],
        ["Typical door-to-door total", "≈6–7 h city centre to city centre", "≈6.5–8 h when transfers counted honestly"],
      ],
    },
    {
      id: "gateway-heading",
      type: "heading",
      level: 2,
      text: "Your Beijing base decides half the answer",
    },
    {
      id: "gateway-table",
      type: "table",
      caption: "Match the Beijing gateway to where you sleep",
      columns: ["Beijing base", "Leans toward", "Reason"],
      rows: [
        ["West-side districts, Beijing West vicinity, Fengtai", "Train", "Gateway is already at your doorstep; no airport crossing needed"],
        ["Central (Wangfujing, Qianmen, Chaoyang core)", "Either — compute", "Rail needs only a metro ride; flying adds a full cross-city leg"],
        ["Near Capital Airport (Shunyi)", "Flight", "You wake up beside the departure hall"],
        ["Near Daxing Airport", "Flight from PKX only if fares fit; otherwise train from West", "Daxing is far south — convenient for flights, awkward for rail"],
        ["Hotel near a Fengtai departure time that suits you", "Train (check operator note)", "A minority of Xi'an services use 北京丰台站 instead of 北京西站"],
      ],
    },
    {
      id: "xian-heading",
      type: "heading",
      level: 2,
      text: "Xi'an's last mile: North station versus Xianyang airport",
    },
    {
      id: "xian-list",
      type: "list",
      items: [
        "Arriving by rail puts you at 西安北站, a metro-served hub in the city's northern suburbs — Line 2 runs toward the Bell Tower / City Wall core and Line 4 crosses southward; the ride into the centre is on the order of half an hour (example, reviewed August 2026).",
        "The old 西安站 near the City Wall mainly handles conventional services; do not confuse the two when booking or when telling a driver your destination.",
        "Arriving by air lands at Xianyang (XIY), which is not in Xi'an's districts at all: budget 60–75 minutes by taxi or airport rail link before you reach the wall-side hotels.",
        "With checked luggage the difference compounds: two escalator changes from a platform beat an entire baggage-claim cycle.",
        "Late arrivals flip the math: metro closes around midnight while taxis remain; but a 23:30 rail arrival still beats a 00:40 airport touchdown for total sleep time.",
      ],
    },
    {
      id: "friction-heading",
      type: "heading",
      level: 2,
      text: "Luggage, security, waiting and disruption recovery",
    },
    {
      id: "friction-table",
      type: "table",
      caption: "Where the two modes actually differ",
      columns: ["Factor", "High-speed rail", "Flight"],
      rows: [
        ["Checked luggage", "Carry-on style works for most trips; no baggage carousel", "Checked bags add drop-off and reclaim cycles at both ends"],
        ["Security", "One station screening + gate check", "Airport screening + airline gate procedures; liquids rules apply"],
        ["Waiting quality", "Station halls with food streets; board anytime", "Gate-bound after security; delays trap you airside"],
        ["Disruption recovery", "Rebooking onto frequent later services same corridor", "Fewer alternates; weather waves cancel whole banks of flights"],
        ["Failure cost", "Missed train → change per railway fare rules", "Missed flight → fare-class dependent, often expensive"],
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Three composite scenarios",
    },
    {
      id: "scenario-a-heading",
      type: "heading",
      level: 3,
      text: "City centre to city centre",
    },
    {
      id: "scenario-a",
      type: "paragraph",
      text: "A couple sleeping near Wangfujing wants the Bell Tower area in Xi'an. The train wins the arithmetic: one metro ride to Beijing West, a 4h20m example service, then Line 2 straight to the wall. Flying would add two cross-city legs plus airports to reach roughly the same total. This is the classic case where onboard time misleads — the rail door-to-door is shorter even though its line-haul is twice as long.",
    },
    {
      id: "scenario-b-heading",
      type: "heading",
      level: 3,
      text: "Starting beside an airport",
    },
    {
      id: "scenario-b",
      type: "paragraph",
      text: "A traveller whose last Beijing night is at a Capital Airport hotel faces the mirror image. The flight departs ten minutes away; the train means crossing the whole city westward first. Unless the Xi'an arrival side punishes them with a late-night airport transfer, flying converts their position advantage directly into sleep. The lesson generalises: price the mode from wherever you will wake up, not from a map's centre point.",
    },
    {
      id: "scenario-c-heading",
      type: "heading",
      level: 3,
      text: "Xi'an onward to Chengdu",
    },
    {
      id: "scenario-c",
      type: "paragraph",
      text: "A planner continuing to Chengdu the next morning should optimise the junction, not the inbound leg. Arriving Xi'an North by rail keeps tomorrow's Chengdu high-speed departure inside the same complex — an elevator change instead of an airport-to-station transfer. Flying in would strand them across town from the morning train they actually need. When a second leg exists, choose the mode that parks you nearest it.",
    },
    {
      id: "mistakes-heading",
      type: "heading",
      level: 2,
      text: "Four mistakes that distort this decision",
    },
    {
      id: "mistakes",
      type: "list",
      ordered: true,
      items: [
        "Comparing 4h10m against 2h05m and stopping there — the edges own this route.",
        "Booking 北京西 out of habit when your ticket actually says 北京丰台, or assuming every fast train uses the West station.",
        "Treating 西安北 and 西安站 as interchangeable; they serve different networks about 10 km apart.",
        "Forgetting which Beijing airport the flight uses until the night before — Capital and Daxing are opposite ends of the city.",
      ],
    },
    {
      id: "framework-heading",
      type: "heading",
      level: 2,
      text: "The tie-breaker framework",
    },
    {
      id: "framework-table",
      type: "table",
      caption: "Read your own trip through these rows before choosing",
      columns: ["Question", "Points to rail", "Points to flight"],
      rows: [
        ["Where do you wake up?", "Central or west Beijing", "Beside either airport"],
        ["Where does tomorrow start?", "Inside Xi'an city, or continuing by train from the North hub", "Early XIY departure onward"],
        ["What are you carrying?", "One roller plus daypack per person", "Nothing — or everything checked through an airline you trust"],
        ["Which date?", "Shoulder dates with wide seat maps", "Peak days when rail seats vanish but flights remain priced"],
        ["How bad is a failure?", "Rebookable on the same corridor within hours", "Weather banks can erase a whole evening"],
        ["Travelling party?", "Solo/couple — metro-friendly", "Family of four — one taxi beats four metro fares only if the airport is close"],
      ],
    },
    {
      id: "framework-note",
      type: "paragraph",
      text: "Three of six rows pointing the same way is a decision; a split verdict means price and personal tolerance decide. What the framework deliberately excludes is any claim that one mode is universally faster — on this corridor the honest answer changes from traveller to traveller.",
    },
    {
      id: "gateways-heading",
      type: "heading",
      level: 2,
      text: "Know the gateways before you book",
    },
    {
      id: "gateways-list",
      type: "list",
      items: [
        "北京西站 Beijing West sits on Metro Line 7 and Line 9 in the city's west — most Xi'an G-services depart here, and its size means twenty minutes inside the building is realistic even without security chaos.",
        "北京丰台站 Beijing Fengtai, south-west and newer, appears on a minority of Xi'an departures; its name is one character away from West in pinyin confusion — check the ticket characters, not memory.",
        "首都机场 Capital (PEK) serves the north-east; 大兴机场 Daxing (PKX) serves the far south. They are roughly 60–90 minutes apart from each other by road at good hours, so a fare that switches airports silently can wreck a plan.",
        "咸阳国际机场 Xianyang (XIY) is Xi'an's airport in name location only — budget a full hour to the wall-side hotels even before baggage reclaim.",
        "西安北站 Xi'an North is the arrival point for essentially all fast services: Line 2 southbound is the tourist spine toward the Bell Tower, Line 4 crosses toward the Big Wild Goose Pagoda side.",
        "西安站 Xi'an (old) station by the wall handles slower conventional trains; occasionally useful for overnight options, never interchangeable with the North hub.",
      ],
    },
    {
      id: "checklist-heading",
      type: "heading",
      level: 2,
      text: "Day-before checklist",
    },
    {
      id: "checklist",
      type: "list",
      ordered: true,
      items: [
        "Confirm the exact Chinese station names printed on each ticket or e-ticket screen.",
        "Screenshot the platform-level map of your Beijing gateway with your hotel pinned, so morning-you decides metro versus taxi in seconds.",
        "Check weather along both ends — summer thunderstorms hit flights harder; winter fog hits both.",
        "If flying, re-check terminal assignment: some airlines moved between terminals at Capital in recent years.",
        "Charge devices and download offline maps for both cities' metro systems.",
        "Set two alarms if the departure is before 08:00 — this corridor punishes late starts twice over.",
      ],
    },
    {
      id: "prices-heading",
      type: "heading",
      level: 2,
      text: "Prices move too: what shifts each side",
    },
    {
      id: "prices-para",
      type: "paragraph",
      text: "Rail fares on this corridor sit in a narrow band — an example second-class Beijing West to Xi'an North range of roughly 515-580 yuan was reviewed August 2026 — and vary mainly by service speed rather than by when you look. Flights behave differently: the same route can swing several-fold between a quiet Tuesday and the start of a holiday week, and advertised fares rarely include a checked bag or the seat you would actually choose. Two practical rules follow. First, treat price as the final tie-breaker, never the opening argument - a saving that looks large can evaporate once the airside edges cost three hours. Second, compare like with like: rail's quoted fare includes your bag on the rack beside you, while a flight's quoted fare may not include anything you will really carry.",
    },
    {
      id: "timetable-heading",
      type: "heading",
      level: 2,
      text: "How to read the timetable for your date",
    },
    {
      id: "timetable-list",
      type: "list",
      ordered: true,
      items: [
        "Search station-to-station (北京西 → 西安北), never city-to-city, so every result is actually usable.",
        "Scan departure-station characters across results: a few fast services leave 北京丰台站 instead of 北京西站 - filter them consciously.",
        "Sort by duration first for the realistic fastest band, then re-sort by departure time to find services matching your morning.",
        "Confirm arrival reads 西安北 before comparing anything onward; an arrival at 西安站 changes your whole last mile.",
        "Repeat the same search reversed for your return date - evening frequency is thinner than morning frequency on this corridor.",
        "Screenshot both searches with dates visible; when plans shift mid-trip you will compare against what you saw, not against memory.",
      ],
    },
    {
      id: "recovery-heading",
      type: "heading",
      level: 2,
      text: "When plans break",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "Recovery paths by failure",
      columns: ["Failure", "First move", "Then"],
      rows: [
        [
          "Chosen train sold out on your date",
          "Check Fengtai departures and split routings (via Zhengzhou) in ticketing apps",
          "Consider flying if the airside total still fits; or shift Xi'an nights rather than losing the day",
        ],
        [
          "Flight cancelled seasonally (weather bank)",
          "Ask the airline's rebooking options first",
          "Same-day rail seats exist most days — the corridor's frequency is your insurance policy",
        ],
        [
          "Wrong Xi'an station realised on arrival",
          "Metro between 西安北 and the centre is straightforward; 西安站 needs a transfer or taxi",
          "Do not re-cross the city twice for one booking error — re-sequence tomorrow instead",
        ],
        [
          "Late-night arrival, metro closed",
          "Official taxi queue at either gateway",
          "Keep hotel Chinese address ready; North-station taxis are plentiful but confirm the meter",
        ],
      ],
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      tone: "warning",
      title: "Examples are dated, not frozen",
      body: "Journey-time bands, frequencies and transfer estimates here were reviewed August 2026 from timetable services and change with schedules and seasons. Gateway locations and metro lines are stable facts. Always price your exact date and stations.",
    },
    {
      id: "scope",
      type: "callout",
      tone: "neutral",
      title: "What this guide covers",
      body: "One task: choosing rail versus air for Beijing–Xi'an door to door in both directions. It does not sequence Beijing–Xi'an–Chengdu itineraries beyond one junction example, does not teach general rail or flight mechanics, does not compare airlines or fares, and does not pick Beijing hotels.",
    },
    {
      id: "more-planning",
      type: "internal-links",
      title: "Related planning guides",
      items: [
        {
          label: "Ordering Beijing, Xi'an and Chengdu",
          href: "/guides/beijing-xian-chengdu-route-order/",
          description: "Where this leg sits when all three cities join one trip.",
        },
        {
          label: "Riding China high-speed rail for the first time",
          href: "/guides/china-high-speed-train-first-time-guide/",
          description: "Passport booking, gates and onboard basics this route assumes.",
        },
        {
          label: "Reading fare bundles before you pay",
          href: "/guides/china-domestic-flight-fare-bundle-baggage/",
          description: "If you fly, the fare rules decide how gentle a disruption is.",
        },
        {
          label: "Passport as ticket, booking to gate",
          href: "/guides/china-passport-as-ticket-booking-to-gate/",
          description: "Foreign-passport e-tickets end to end.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources reviewed",
      items: [
        {
          label: "China Railway 12306 — official ticketing platform (station names, live timetables)",
          url: "https://www.12306.cn/index/",
          publisher: "China State Railway Group",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Beijing to Xi'an route guide — fastest 4h10m, West/North pairing, frequency band (dated example source)",
          url: "https://chinahighspeedrail.com/route-guides/beijing-to-xian/",
          publisher: "ChinaHighSpeedRail.com",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Beijing West → Xi'an North schedule listing (dated example cross-check)",
          url: "https://hk.trip.com/trains/china/route/beijing-west-to-xian-north/",
          publisher: "Trip.com trains",
          reviewedAt: "2026-08-22",
        },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
