export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "You can visit the Terracotta Warriors without joining a tour, but treat it as one linked day rather than four separate questions. Reserve the Emperor Qinshihuang's Mausoleum Site Museum in the passport name of every visitor, carry those original passports, reach the museum's North Gate from Xi'an, choose a permitted order through Pits 1, 2 and 3, take the included shuttle to Lishan Garden, return to the museum transport area, and only then travel back to Xi'an. A guide is optional for entry and transport; the strongest reason to hire one is interpretation.",
    },
    {
      id: "execution-summary",
      type: "callout",
      title: "The independent visit in eight actions",
      body: "1. Confirm the live official calendar. 2. Book every visitor through a channel linked by the museum. 3. Match each name and passport number to the original document. 4. Choose the public-transport or car plan from Xi'an. 5. Enter at the museum's North Gate. 6. Visit all three pits in an order that fits your priorities and current crowd controls. 7. Use the included shuttle for Lishan Garden. 8. Return to the museum-side transport zone and follow the return plan already saved on your phone.",
      tone: "decision",
    },
    {
      id: "day-scope",
      type: "paragraph",
      text: "This is normally a full-day task from central Xi'an. The museum itself says the Terracotta Warriors area and Lishan Garden each need about 1.5 hours. That three-hour visit estimate excludes the journey from Xi'an, passport inspection, walking to and from the gates, shuttle queues, meals and the return. Homeground would protect most of a day rather than attach the site to a tightly timed arrival or departure day.",
    },
    {
      id: "official-facts-heading",
      type: "heading",
      level: 2,
      text: "What the official sources confirm this week",
    },
    {
      id: "official-facts-table",
      type: "table",
      caption: "Standing museum facts reviewed on 11 August 2026",
      columns: ["Decision", "Official position", "Traveller action"],
      rows: [
        ["Foreign passport", "Foreign visitors are included in the real-name advance-reservation system; a passport can be used", "Enter the document exactly and carry the same original passport"],
        ["Ticket scope", "One admission covers the Terracotta Warriors Museum and Lishan Garden, with free shuttle travel between them", "Do not buy a second admission just because the two areas appear as separate map pins"],
        ["Adult price", "The current official English ticket page lists the standard adult admission at 120 yuan", "Recheck the live checkout before paying because price and concession rules can change"],
        ["Opening season", "Ticket inspection is normally 08:30–17:00 from 16 March to 15 November and 08:30–16:30 from 16 November to 15 March", "Use the live notice for the actual date, especially around holidays"],
        ["Entry", "The current English visitor instructions identify the museum North Gate as the visitor entrance", "Navigate to the museum entrance, not the mausoleum mound or a generic Terracotta Warriors pin"],
        ["Capacity", "The standing visitor guide lists a normal maximum of 65,000; dated holiday notices can temporarily change hours and capacity", "Treat every expansion as date-specific, not as permanent extra inventory"],
      ],
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "Step 1: secure a museum reservation with the passport you will carry",
    },
    {
      id: "booking-channels",
      type: "table",
      caption: "Booking paths currently identified by the museum",
      columns: ["Path", "What makes it official or authorised", "Boundary"],
      rows: [
        ["Museum visitor guide and online-reservation link", "The official bmy.com.cn guide links directly to its reservation system", "Start at the museum site rather than a search advertisement or similarly named website"],
        ["Official WeChat accounts", "The museum names ‘秦始皇帝陵博物院’ and ‘兵马俑票务在线’ as reservation channels", "Check the exact account identity before entering passport data or paying"],
        ["Overseas booking path", "The museum's English ticket link currently routes to Trip.com, and the museum documented a cross-border ticketing partnership with Ctrip in 2024", "This is a dated integrated service path; recheck where the official English site sends you and read any separate service terms"],
      ],
    },
    {
      id: "passport-process",
      type: "paragraph",
      text: "Use the full name and passport number shown in the machine-readable identity page. Before payment, check every digit, the visit date, entry period and visitor count. The museum requires the original valid document at inspection and says the visitor, ticket and document must match. A screenshot or photocopy is useful as travel backup, but it is not the original passport required for entry.",
    },
    {
      id: "booking-confirmation",
      type: "list",
      items: [
        "Open ‘My Orders’ in the channel used and confirm that the order exists rather than relying only on a payment notification.",
        "Save the order number, date, time period and the official ticket hotline, but do not publish or share a readable passport page.",
        "Check whether the confirmation covers every named traveller, including anyone who may qualify for a concession.",
        "Keep the original passport accessible on the day; do not pack it in luggage left with a driver.",
      ],
    },
    {
      id: "booking-recovery",
      type: "callout",
      title: "If the passport or payment flow fails, recover before travelling to Lintong",
      body: "Do not invent a Chinese ID number, borrow another person's account identity or assume staff will create a walk-up exception. First open ‘My Orders’ and follow the channel's current lookup prompts. If there is no confirmed record, retry through a channel linked from bmy.com.cn or call the official ticket line, 029-81399127. The museum explicitly asks visitors to complete online purchase before arrival, so an unresolved booking is a reason to pause the journey, not a reason to gamble on the gate.",
      tone: "warning",
    },
    {
      id: "one-ticket",
      type: "callout",
      title: "The pits and Lishan Garden are two visitor areas under one admission",
      body: "The Terracotta Warriors Museum contains Pits 1, 2 and 3. Lishan Garden is the archaeological site park around the imperial mausoleum and contains the Bronze Chariots Museum and other excavated sites. They are not a single walkable exhibition hall. The included shuttle connects them, and the transfer time must sit inside the same day's plan.",
      tone: "neutral",
    },
    {
      id: "hours-heading",
      type: "heading",
      level: 2,
      text: "Step 2: read the regular hours and the dated notice together",
    },
    {
      id: "hours-table",
      type: "table",
      caption: "Regular ticket-inspection hours shown by the museum on 11 August 2026",
      columns: ["Season", "Start checking tickets", "Stop checking tickets", "Published closing time"],
      rows: [
        ["16 March–15 November", "08:30", "17:00", "18:30"],
        ["16 November–15 March", "08:30", "16:30", "18:00"],
      ],
    },
    {
      id: "holiday-expansion",
      type: "callout",
      title: "Holiday expansion is real, but it is never a standing promise",
      body: "For the 2026 Qingming holiday, the museum temporarily opened earlier, inspected tickets later and added 5,000 places per day. For 1–5 May 2026, it temporarily operated 07:30–20:00, stopped inspection at 18:00 and raised the maximum from 65,000 to 75,000. Those measures applied to those dates only. Do not reuse them for another weekend, Golden Week or next year without a new official notice.",
      tone: "warning",
    },
    {
      id: "transport-heading",
      type: "heading",
      level: 2,
      text: "Step 3: travel from Xi'an to the museum, not just to Lintong",
    },
    {
      id: "public-transport-route",
      type: "paragraph",
      text: "The museum's current transport page directs travellers from Xi'an North Railway Station or Xi'an Railway Station onto the metro network, then Line 1 to Fangzhicheng, Line 9 to Huaqingchi, and a final transfer to Lintong Tourist Bus 613 or Bus 602 for the Terracotta Warriors area. From a central Xi'an hotel, join the same Line 1–Line 9 sequence at the most practical station. Check the live exit and bus stop before leaving the metro because road works and stop positions are operational facts.",
    },
    {
      id: "transport-options",
      type: "comparison",
      title: "Choose the transport by failure risk, not by the shortest advertised time",
      columns: [
        {
          heading: "Metro plus local bus",
          body: "Best for travellers who want a public, independently recoverable route. Save Fangzhicheng, Huaqingchi and the exact final bus name in Chinese. It involves transfers and standing time.",
        },
        {
          heading: "Confirmed direct sightseeing bus",
          body: "Useful only when the operator, departure point, departure time, return point and last return are confirmed for the actual date. Many old city-centre listings remain online after operations change.",
        },
        {
          heading: "Taxi, ride-hail or prearranged car",
          body: "Simplest for a small group, parents or a strict return time. Agree on the official visitor drop-off and the later pickup point; a driver is not automatically a guide or a ticket provider.",
        },
      ],
    },
    {
      id: "transport-schedule-boundary",
      type: "callout",
      title: "This guide does not freeze an unofficial bus timetable",
      body: "At the 11 August 2026 review, the museum's official transport page listed routes 602 and Tourist 613 but did not publish a dependable departure interval or last-return time. Homeground therefore does not copy a schedule from blogs or map aggregators. Check the museum route page, the current operator or a live official transport service on the travel date; if the last return cannot be confirmed, use a different return plan.",
      tone: "warning",
    },
    {
      id: "arrival-check",
      type: "callout",
      title: "Before entering, identify both the museum gate and your later return zone",
      body: "The museum's current English instructions say visitors enter through the North Gate. When you arrive, save the signed public-transport or legal pickup area you will use after returning from Lishan Garden. Do not assume that ‘Terracotta Warriors car park,’ ‘North Gate’ and a bus stop with a similar name are interchangeable pins.",
      tone: "decision",
    },
    {
      id: "pits-heading",
      type: "heading",
      level: 2,
      text: "Step 4: give each of the three pits a different job",
    },
    {
      id: "pits-table",
      type: "table",
      caption: "What each pit contributes to a first independent visit",
      columns: ["Pit", "What the official site establishes", "How to use your time"],
      rows: [
        ["Pit 1", "The largest pit: 230 by 62 metres, with an estimated 6,000 terracotta figures and horses", "Use it for scale, formation and the conservation workspace; protect a full circuit rather than stopping only at the famous front view"],
        ["Pit 2", "A roughly 6,000-square-metre L-shaped pit with more varied troop types, including archers, chariots and cavalry", "Slow down for military structure and the closer display objects; the excavated area can look less immediately dramatic than Pit 1"],
        ["Pit 3", "A much smaller 520-square-metre pit that scholars have interpreted as a command post", "Use the smaller space to understand command organisation and then move on before crowding erases the benefit"],
      ],
    },
    {
      id: "pit-order-heading",
      type: "heading",
      level: 3,
      text: "There is no single correct pit order for every visitor",
    },
    {
      id: "pit-order-options",
      type: "comparison",
      columns: [
        {
          heading: "Pit 1 first",
          body: "Choose this when the immediate scale of the army is the main reason for coming. Continue to Pit 3 and Pit 2 if current signs and crowd controls permit; this matches the museum's published two-hour pit sequence, but it is a suggested route rather than a rule for everyone.",
        },
        {
          heading: "Pit 2 first",
          body: "Choose this when troop types, weapons and close detail matter most, or when you prefer to save the largest view for later. Confirm that the current visitor flow allows the sequence without inefficient backtracking.",
        },
        {
          heading: "Crowd-adaptive order",
          body: "Use the current map and staff directions, take the clearer permitted pit first and protect Pit 1 for a less compressed window. Never push against a one-way control simply to follow an internet itinerary.",
        },
      ],
    },
    {
      id: "pits-time-plan",
      type: "table",
      caption: "Homeground time allocation inside the Terracotta Warriors area",
      columns: ["Task", "Planning allowance", "Cut rule"],
      rows: [
        ["Entry, orientation and current map", "15–20 minutes", "Do not begin a paid sales presentation before knowing the museum route"],
        ["Pit 1", "45–60 minutes", "Keep the scale view and conservation end; reduce repeated photo stops"],
        ["Pits 2 and 3", "35–50 minutes combined", "Keep one focused interpretation point in each rather than treating them as smaller copies"],
        ["Facilities and walk to shuttle", "15–25 minutes", "Leave the area before the Lishan plan becomes impossible"],
      ],
    },
    {
      id: "order-boundary",
      type: "callout",
      title: "A preferred sequence never overrides the route operating that day",
      body: "Temporary maintenance, one-way crowd management and gallery closures can change the usable order. Check the map and signs after entry. The purpose of choosing an order is to protect your priority, not to promise that every doorway and viewing rail will be available in the same direction forever.",
      tone: "neutral",
    },
    {
      id: "lishan-heading",
      type: "heading",
      level: 2,
      text: "Step 5: use the included shuttle for Lishan Garden",
    },
    {
      id: "shuttle-process",
      type: "paragraph",
      text: "The museum's one-ticket notice places the shuttle point west of the Terracotta Warriors Museum North Gate and the corresponding stop at Lishan Garden's East Gate. Keep the booking record and passport available, follow the current queue and confirm that the vehicle is the museum shuttle. The transfer is included; electric sightseeing vehicles inside either visitor area are separate paid services.",
    },
    {
      id: "lishan-contents",
      type: "table",
      caption: "What Lishan Garden adds after the three pits",
      columns: ["Stop", "Why it changes the visit", "Time decision"],
      rows: [
        ["Bronze Chariots Museum", "The bronze chariots were moved to their dedicated museum in Lishan Garden", "Protect this if objects and technology matter more than covering every outdoor point"],
        ["K9901 exhibition", "Presents acrobat or entertainment figures unlike the armoured warriors", "Pairs well with the pits because it broadens the purpose of the mausoleum complex"],
        ["K0006 exhibition", "Includes figures commonly interpreted as civil officials", "Useful when administration and court organisation are a priority"],
        ["Mausoleum mound and site landscape", "Shows the scale and spatial logic of the burial complex rather than another hall of warriors", "Keep it only if weather, mobility and closing time allow"],
      ],
    },
    {
      id: "lishan-time",
      type: "callout",
      title: "Do not board the Lishan shuttle with only a few spare minutes",
      body: "The museum estimates about 1.5 hours for Lishan Garden and an earlier official notice estimates roughly one hour of walking to cover the Bronze Chariots Museum, K9901 and K0006. Shuttle waiting, internal transport and the walk back to the East Gate are additional. If the day has slipped, choose a smaller Lishan priority set instead of assuming the last inspection time is the time you can start the entire park.",
      tone: "warning",
    },
    {
      id: "return-heading",
      type: "heading",
      level: 2,
      text: "Step 6: return to the museum side before returning to Xi'an",
    },
    {
      id: "return-sequence",
      type: "paragraph",
      text: "The lowest-ambiguity independent sequence is Terracotta Warriors Museum → Lishan Garden → museum-side transport zone → Xi'an. From Lishan Garden's East Gate, use the included shuttle back to the Terracotta Warriors Museum unless a different official exit arrangement has been confirmed for that day. This returns you to the area where you saved the public bus stop or arranged car pickup.",
    },
    {
      id: "return-options",
      type: "table",
      caption: "Build the return before leaving Xi'an in the morning",
      columns: ["Return method", "Confirm in advance", "Failure plan"],
      rows: [
        ["Bus 602 or Tourist 613 plus Metro Line 9", "Exact museum-side stop, direction to Huaqingchi, current service window and metro connection", "If the last bus cannot be verified, switch to a car rather than waiting beside an ambiguous stop"],
        ["Round-trip direct sightseeing bus", "The exact return boarding point and last departure, not only the outbound ticket", "Know whether a missed departure makes the ticket void and keep a ride-hail option"],
        ["Ride-hail, taxi or private car", "A legal pickup pin, driver contact, vehicle plate and whether the driver waits during Lishan Garden", "Use the museum's staffed transport area to resolve the pin; do not meet on an unsafe roadside"],
      ],
    },
    {
      id: "return-checkpoint",
      type: "callout",
      title: "A return promise without a named boarding point is not a plan",
      body: "Save the stop or pickup pin in Chinese and a screenshot before entering. Reconfirm it after the shuttle returns from Lishan Garden. ‘Outside the Terracotta Warriors’ is too vague for a site with multiple gates, parking areas and two visitor zones.",
      tone: "decision",
    },
    {
      id: "guide-heading",
      type: "heading",
      level: 2,
      text: "When a guide genuinely adds value",
    },
    {
      id: "guide-decision",
      type: "comparison",
      columns: [
        {
          heading: "A guide is probably worth considering",
          items: [
            "You want the formations, ranks, weapons, excavation and conservation work connected into one explanation.",
            "Your group has focused historical questions that an audio guide or labels will not answer.",
            "Parents, children or different walking speeds make real-time route cuts valuable.",
            "You have limited site time and want someone to protect the interpretation rather than only navigate.",
          ],
        },
        {
          heading: "Independent visiting is usually enough",
          items: [
            "You can complete the passport booking and transport checks yourself.",
            "Your priority is visual scale and a self-paced walk rather than detailed historical interpretation.",
            "You are comfortable reading the official map, following staff directions and cutting stops when time slips.",
            "You have already separated transport, ticket and explanation instead of expecting one person to solve all three invisibly.",
          ],
        },
      ],
    },
    {
      id: "guide-boundary",
      type: "paragraph",
      text: "A guide is not required to make the passport valid, unlock a special pit order or operate the museum shuttle. A driver provides transport; a guide provides interpretation and visitor support; a ticket channel issues the reservation. If you hire help, ask which roles are actually included, which language is confirmed, whether Lishan Garden is covered and where the return vehicle waits. The museum currently publishes separate ticket and explanation hotlines, but language availability and service times remain dynamic.",
    },
    {
      id: "parents-boundary",
      type: "callout",
      title: "With older parents, Lishan Garden is a same-day decision, not a compulsory endurance test",
      body: "Protect the three pits first, include seated pauses and reassess after the museum area. The same ticket includes Lishan Garden, but that does not make every outdoor stop mandatory. The broader older-parent route page owns hotel changes, recovery days and the pace of the whole China trip; this page only decides how to execute the Terracotta Warriors day.",
      tone: "neutral",
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "Questions that can break an independent visit",
    },
    {
      id: "faq-passport",
      type: "callout",
      title: "Can a foreign visitor book with a passport?",
      body: "Yes. The museum includes foreign visitors in its real-name reservation system and lists passports as accepted documents. Use the same original valid passport for entry.",
      tone: "neutral",
    },
    {
      id: "faq-lishan",
      type: "callout",
      title: "Is Lishan Garden included in the Terracotta Warriors ticket?",
      body: "Yes under the current one-ticket arrangement, and the shuttle between the two visitor areas is included. Paid electric sightseeing vehicles inside the areas are separate.",
      tone: "neutral",
    },
    {
      id: "faq-order",
      type: "callout",
      title: "Must everyone visit Pit 1, then Pit 3, then Pit 2?",
      body: "No. The museum publishes that sequence as a suggested two-hour route, but your priority and the day's crowd controls matter. Follow current one-way directions and choose the permitted sequence that protects what you came to understand.",
      tone: "neutral",
    },
    {
      id: "faq-time",
      type: "callout",
      title: "How long should the whole day take?",
      body: "The museum's own planning figure is about 1.5 hours in each of its two areas. Once travel from Xi'an, inspection, shuttle waits and the return are added, protect a full day. Do not convert that judgment into a guaranteed door-to-door duration.",
      tone: "neutral",
    },
    {
      id: "fact-boundary",
      type: "callout",
      title: "Official fact versus Homeground planning judgment",
      body: "Passport eligibility, official channels, original-document inspection, seasonal hours, one-ticket coverage, the two visitor areas, shuttle points, pit descriptions, official transport routes and dated holiday expansion come from the sources below. The full-day recommendation, time allocations, alternative pit orders, default return via the museum side and guide-value test are Homeground planning judgments built on those facts.",
      tone: "neutral",
    },
    {
      id: "final-check-heading",
      type: "heading",
      level: 2,
      text: "Final checks before the visit",
    },
    {
      id: "final-check-list",
      type: "list",
      items: [
        "The official order record contains every visitor's correct passport details and visit period.",
        "The original passports are packed where the travellers, not a driver or hotel, control them.",
        "The latest notice confirms the visit-day hours, capacity and any temporary pit or Lishan closure.",
        "The museum's official transport page still lists the chosen route, and the actual departure or return service has been checked for that date.",
        "The group knows the current North Gate entry and has saved the later museum-side return point.",
        "The Lishan shuttle and walking allowance fit before the current last inspection and closing times.",
        "Any guide, driver or direct bus has a written language, meeting point, service scope and return arrangement.",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Connect this day to the rest of the China trip",
      items: [
        {
          label: "China high-speed trains for first-time visitors",
          href: "/guides/china-high-speed-train-first-time-guide/",
          description: "Use the correct passport record and station process when Xi'an is reached by rail.",
        },
        {
          label: "Do you need a tour guide in China?",
          href: "/guides/do-you-need-a-tour-guide-in-china/",
          description: "Keep the country-wide support decision separate from the interpretation choice at this one archaeological site.",
        },
        {
          label: "China with older parents",
          href: "/guides/china-itinerary-with-older-parents/",
          description: "Place the walking, transfers and recovery from this day inside a realistic multi-city route.",
        },
        {
          label: "How much does a China trip cost?",
          href: "/guides/how-much-does-a-china-trip-cost/",
          description: "Compare the cost roles of public transport, a car, a guide and broader trip support.",
        },
      ],
    },
    {
      id: "consultation-cta",
      type: "callout",
      title: "Need this day fitted into a real China itinerary?",
      body: "If your dates, passports, family pace or transport connections make the Xi'an day unusually tight, you can ask a Homeground travel consultant to review the actual route. The useful starting details are the visit date, hotel area, group size, walking limits and the train or flight that constrains the day.",
      tone: "neutral",
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        {
          label: "Museum visitor guide, booking, hours, passport and shuttle information",
          url: "https://www.bmy.com.cn/guide/",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Official English ticket, inspection and visitor-route information",
          url: "https://www.bmy.com.cn/jingtai/bmyweb/ticketing.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Official museum transport routes from Xi'an",
          url: "https://www.bmy.com.cn/guide/368.html?_isa=1",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "One-ticket system, Lishan Garden exhibits and shuttle boarding points",
          url: "https://www.bmy.com.cn/news/news/980.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Official Pit 1 description",
          url: "https://www.bmy.com.cn/pitone.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Official Pit 2 description",
          url: "https://www.bmy.com.cn/pittwo.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Official Pit 3 description",
          url: "https://www.bmy.com.cn/pitthree.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Museum announcement on its cross-border ticketing platform",
          url: "https://www.bmy.com.cn/news/news/2897.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026 Qingming temporary hours and capacity expansion",
          url: "https://www.bmy.com.cn/news/news/3259.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "2026 May Day temporary hours and capacity expansion",
          url: "https://www.bmy.com.cn/news/news/3278.html",
          publisher: "Emperor Qinshihuang's Mausoleum Site Museum",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const;
