import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "先确定主要景点的顺序，再在张家界市区和武陵源之间选择住宿基地。连续游览张家界国家森林公园及周边景点时，武陵源通常更省折返；天门山、进出张家界以及离开前一晚，市区通常更顺。没有景点顺序，就没有固定胜者。" },
  { id: "answer", type: "callout", title: "直接结论", tone: "decision", body: "先把每一晚放到第二天最早的固定任务旁边，再看前一天在哪里结束。如果换店只少坐一段车，通常保留一个基地；如果武陵源一侧和市区一侧的连续景点会造成两次或更多跨区往返，可以考虑只换一次酒店。儿童、行动不便、大件行李、晚到和早离都会提高换店成本。" },
  { id: "boundary", type: "paragraph", text: "本页假定你已经知道要去哪些景点。它不替你编排张家界二日、三日或四日路线，不排名酒店，不写实时房价，也不承诺某班车时间。先用张家界行程指南确定景点顺序，再用本页安排每一晚。" },
  { id: "inputs", type: "heading", level: 2, text: "打开订房 App 前，先写下固定顺序" },
  { id: "sequence", type: "list", ordered: true, items: ["逐日写下景点及准确入口或运营节点，不要只写“张家界森林公园”。东门和南门不是同一抵达点。", "从车票复制准确到站和离站名称。张家界站与张家界西站不能混用。", "加入真实抵达窗口，包括入境、取行李或列车晚点，并问清前台最晚保留房间的时间。", "标出每天早上第一项有时间要求的任务，以及前一天大概率在哪里结束。", "列出每次行李交接：退房、寄存、领取、装车和下一家入住。", "最后才比较全住市区、全住武陵源，还是只换一次基地。"] },
  { id: "matrix", type: "table", caption: "先按景点顺序初选，再根据同行者调整", columns: ["已确定顺序", "先测试的住宿方案", "什么会改变结论"], rows: [["连续两天森林公园", "武陵源", "具体入口离酒店很远、最后一段路不可用，或很早从市区侧离开"], ["天门山后乘火车或飞机离开", "张家界市区", "天门山线路变化、离开站点不同，或离开时间很晚"], ["森林公园、森林公园、天门山", "先武陵源，再换一次到市区", "住宿晚数太少、行李多，或没有可靠的行李转移"], ["天门山后连续两天森林公园", "先市区，再换一次到武陵源", "入园较晚、入口变化，或已确认更合适的直达交通"], ["短停中只有一个森林公园日", "按抵离节点保留一个基地", "固定早入园值得多换一次酒店"]] },
  { id: "gate", type: "callout", title: "“武陵源”不是一个入口", tone: "warning", body: "核心景区有多个门票站。向物业索取中文全名、地图定位、车辆落客点，以及到你票面入口的走法。房源位于武陵源区，不代表能步行到你需要的门。2025 年官方东门—南门环景巴士信息有助于理解区域，但不能当作长期不变的班次承诺。" },
  { id: "arrival", type: "heading", level: 2, text: "先安排好抵达夜和离开前一晚" },
  { id: "arrival-table", type: "table", caption: "第一晚和最后一晚经常决定整套答案", columns: ["首尾条件", "低风险起点", "付款前核验"], rows: [["很晚抵达，后续车辆未确认", "有前台值守的市区住宿", "准确车站、前台时间、外籍住客登记和次晨安全转场"], ["从张家界西站乘早班车", "最后一晚住市区侧", "有日期的车票、上车点和充足的出发余量"], ["第一个公园日有固定早入园", "前一晚住武陵源", "正确门票站、门票有效性、早餐和首段交通"], ["公园傍晚结束，第二天在市区侧", "行李可衔接时，游览后只换一次", "寄存、领取截止时间、司机、新前台和取消条件"]] },
  { id: "scenarios", type: "heading", level: 2, text: "两个顺序，会得到两种答案" },
  { id: "scenario-one", type: "comparison", title: "情境 A：森林公园两天，随后天门山和傍晚航班", columns: [{ heading: "全住市区", body: "不用换酒店，但两次市区—公园往返会占用早晨或傍晚，也不利于公园早出发。" }, { heading: "全住武陵源", body: "森林公园两天更轻松，但天门山和离开日会承担跨区转场风险。" }, { heading: "只换一次", body: "武陵源住两晚，再到市区住一晚；如果寄存和转移已经确认，它可能替代反复折返。" }] },
  { id: "scenario-two", type: "callout", title: "情境 B：晚到、带两名儿童、只有一个公园日", tone: "neutral", body: "假设一家人很晚抵达，先游天门山，之后只有一天森林公园，次日早上从张家界西站离开。全程住市区可能更能保证休息，也少一次打包、转移和重新办理入住。如果公园票必须很早入园，而且转场已可靠确认，武陵源住一晚才可能值得。同样的景点，因为首尾两晚和行李不同，答案也会改变。" },
  { id: "move-cost", type: "heading", level: 2, text: "计算完整换店成本，不只看车程" },
  { id: "move-list", type: "list", items: ["在第一项游览前打包，并把药品、护照和雨具留在手边。", "退房时核对每件行李的标记，并书面确认寄存截止时间。", "游览后前往新基地，或先绕回原酒店领取行李。", "在可能并非酒店门口的车辆点装卸行李。", "到新酒店再次出示护照，由前台办理住宿登记。", "如果房间未准备好，或司机找不到英文房源名，要承担等待时间。", "为儿童、老人、轮椅或大箱子重新核验整段通行路径。"] },
  { id: "move-rule", type: "callout", title: "一个实用的换店门槛", tone: "decision", body: "换店应当换来一个更完整的早晨、减少至少两次可能的跨区往返，或保护关键离开节点。如果它只缩短一程车，单一基地通常更稳。这是 Homeground 的编辑判断，不是官方交通保证。" },
  { id: "failure", type: "heading", level: 2, text: "行程顺序变化时怎么调整" },
  { id: "failure-table", type: "table", caption: "不要让一次变化引发不必要的连环换店", columns: ["变化", "立即行动", "重新计算"], rows: [["列车晚到，无法安全转去武陵源", "通知原酒店，不再依赖未确认的夜间交通，先确认一间有前台值守的市区客房", "从仍可执行的第一个景点重新选基地"], ["道路、索道或入口安排变化", "查看景区当前官方公告，并确认原票是否仍有效", "同时看未来两段；若换店不再减少反复交通，就保留现有房间"], ["物业不能按承诺寄存或转运行李", "先把行李留在有人值守的地方，并要求书面替代方案", "比较增加一次车程与继续换店的时间和风险"], ["司机找不到酒店", "发送物业中文全名、完整地址、电话和地图定位", "不要假定英文品牌或区域名能定位到正确分店"]] },
  { id: "dynamic", type: "paragraph", text: "官方游线示例、城景交通资料、天门山交通参考和 12306 已于 2026 年 8 月 13 日复核。它们可以说明地理关系和官方曾公布这些交通连接，但不能证明目前仍在运营，也不能保证你出行日期的班次。临行前请再次核对景区公告、票面入口、准确火车站和物业说明。" },
  { id: "check", type: "heading", level: 2, text: "最终预订核验" },
  { id: "check-list", type: "list", items: ["有日期的景点顺序与准确门票站", "12306 或已出票车票显示的准确抵离站", "物业中文全名、地址、电话和地图定位", "真实抵达时仍有前台值守", "门店已确认每位外籍住客的入住登记", "计划换店时，两端的行李寄存都已确认", "所需时段的当前交通，而不只是“有这条线路”", "取消条件，以及晚到中断时的市区备用住宿"] },
  { id: "links", type: "internal-links", title: "继续规划", items: [{ label: "中国住宿决策", href: "/zh/stay/", description: "返回 Homeground 住宿决策集合页。" }, { label: "先确定张家界景点顺序", href: "/zh/guides/zhangjiajie-itinerary/", description: "在安排住宿晚数前，先排好森林公园、天门山与周边景点。" }, { label: "如何判断靠近地铁", href: "/zh/guides/china-hotel-near-metro/", description: "把最后步行检验用于后续城市酒店；在张家界应核对实际道路、景区入口和车辆衔接。" }, { label: "核验真正可用的无障碍酒店房", href: "/zh/guides/china-accessible-hotel-room-verification/", description: "决定换基地前，核对从车辆停点到房间和浴室的每一段。" }, { label: "外国旅客能住中国任何酒店吗？", href: "/zh/guides/foreigners-china-hotel/", description: "规划双基地前，分别核验两家物业的护照登记。" }, { label: "国际航班前中国最后一晚", href: "/zh/guides/china-last-night-before-international-flight/", description: "从实际国际出境机场倒推；张家界市区末晚只保护本地衔接段。" }, { label: "衔接北京、张家界与上海", href: "/zh/guides/beijing-zhangjiajie-shanghai-transport/", description: "核对城际段与准确的张家界抵达点。" }, { label: "年长旅客的张家界安排", href: "/zh/guides/zhangjiajie-older-travellers/", description: "按步行量、休息与行动能力调整换基地计划。" }, { label: "为《边城》选凤凰、茶峒或两地", href: "/zh/guides/border-town-fenghuang-chadong-shen-congwen/", description: "若湘西行程从张家界继续延伸，先分清沈从文故乡与小说的文学地理。" }] },
  { id: "consult", type: "callout", title: "先请求人工沟通基地适配", tone: "neutral", body: "现有通用规划入口只用于初次联系。初始表单仅填写旅行日期、准备比较的城市或区域、旅客与房间数量，以及必要时的大致住宿预算。可以说明希望稍后讨论家庭或无障碍安排，但不要提交儿童具体年龄、行动、医疗或无障碍细节、护照或其他证件资料、订单或付款记录，或任何准备转交酒店、地接等供应商的可识别资料。规划师会另行安排人工跟进；这些细节只在确有需要并取得适当同意后讨论。未经另行、针对明确目的的同意，Homeground 不会把资料分享给供应商；这里也不是实时库存系统，不保证价格、房态、外宾接待、房型或无障碍适用性。" },
  { id: "sources", type: "sources", title: "官方与一手来源", items: [{ label: "张家界世界地质公园二日游路线", url: "https://zhangjiajieuggp.org.cn/html/2026/2026032620135033852.html", publisher: "张家界世界地质公园", reviewedAt: "2026-08-13" }, { label: "张家界世界地质公园三日游路线", url: "https://zhangjiajieuggp.org.cn/html/2026/2026032620161311924.html", publisher: "张家界世界地质公园", reviewedAt: "2026-08-13" }, { label: "天门山景区游玩交通指南", url: "https://whhlyt.hunan.gov.cn/whhlyt/wldh2022jt/202208/t20220823_27716284.html", publisher: "湖南省文化和旅游厅", reviewedAt: "2026-08-13" }, { label: "张家界城景旅游客运专线", url: "https://jtt.hunan.gov.cn/xxgk/gzdt/szdt1/202506/t20250610_33706126.html", publisher: "湖南省交通运输厅", reviewedAt: "2026-08-13" }, { label: "武陵源东门—南门环景巴士", url: "https://jtt.hunan.gov.cn/jtt/xxgk/gzdt/szdt1/202506/t20250610_33706127.html", publisher: "湖南省交通运输厅", reviewedAt: "2026-08-13" }, { label: "铁路车票与车站官方查询", url: "https://www.12306.cn/", publisher: "中国铁路 12306", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
