import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Choose between Zhangjiajie city and Wulingyuan only after fixing the order of your major sights. Wulingyuan is usually the lower-friction base for consecutive days in Zhangjiajie National Forest Park and nearby scenic sites. The city is usually stronger for Tianmen Mountain, city-side arrivals and the final night before a train or flight. Neither base wins without the sequence." },
  { id: "answer", type: "callout", title: "The direct answer", tone: "decision", body: "Put each night beside the first fixed task of the following morning, then check where the previous day ends. Keep one base when a move would save only one transfer. Consider one move when a Wulingyuan cluster and a city-side cluster would otherwise create two or more cross-area journeys. Children, limited mobility, heavy luggage, late arrivals and early departures raise the cost of moving." },
  { id: "boundary", type: "paragraph", text: "This page assumes you already know which sights you intend to visit. It does not build a two-, three- or four-day itinerary, rank hotels, quote live room prices or promise a bus time. Use the Zhangjiajie itinerary guide to choose the sightseeing order; use this page to place the nights." },
  { id: "inputs", type: "heading", level: 2, text: "Write the fixed sequence before opening a hotel app" },
  { id: "sequence", type: "list", ordered: true, items: ["List each dated sight and its exact entrance or operating node, not just ‘Zhangjiajie park’. The East Gate and South Gate are different arrival points.", "Copy the exact arrival and departure station from the ticket. Zhangjiajie Railway Station and Zhangjiajie West Railway Station are not interchangeable.", "Add the real arrival window, including immigration, baggage or rail delays, and ask when the reception will stop holding the room.", "Mark the first timed task each morning and the place where the previous day is likely to finish.", "Add every bag handoff: checkout, storage, collection, vehicle loading and the next check-in.", "Only then compare one city base, one Wulingyuan base or one move between them."] },
  { id: "matrix", type: "table", caption: "Start with the sight order, then adjust for the travellers", columns: ["Confirmed sequence", "Base to test first", "What could change it"], rows: [["Two consecutive forest-park days", "Wulingyuan", "A specific gate far from the property, an unusable last mile or an early city-side departure"], ["Tianmen Mountain, then rail or flight departure", "Zhangjiajie city", "A changed Tianmen route, a different station or a very late departure"], ["Forest park, forest park, then Tianmen Mountain", "Wulingyuan, then one move to the city", "Too few nights, heavy luggage or no reliable bag transfer"], ["Tianmen Mountain, then two park days", "City, then one move to Wulingyuan", "Late park entry, an entrance change or a better confirmed direct transfer"], ["Only one park day in a short stay", "One base, chosen from arrival and departure", "A timed early park entrance that is worth one hotel move"]] },
  { id: "gate", type: "callout", title: "‘Wulingyuan’ is not a door", tone: "warning", body: "The core scenic area has multiple ticket stations. Ask the property for its full Chinese name, pin, vehicle drop-off point and the route to the entrance on your ticket. A listing can be in Wulingyuan District without being walkable to the gate you need. The official 2025 East Gate–South Gate ring-bus announcement helps orientation, but it is not a permanent timetable promise." },
  { id: "arrival", type: "heading", level: 2, text: "Protect the arrival and departure nights" },
  { id: "arrival-table", type: "table", caption: "The first and final nights often decide the best base", columns: ["Arrival or departure condition", "Lower-risk starting point", "Verify before paying"], rows: [["Late arrival with no confirmed onward vehicle", "Staffed city-side room", "Exact station, latest reception, passport check-in and safe transfer the next morning"], ["Early train from Zhangjiajie West", "City side for the final night", "Dated ticket, pickup point and conservative departure buffer"], ["First park day has a fixed early entry", "Wulingyuan the night before", "Correct gate, ticket validity, breakfast and first transport"], ["Evening park finish before a city-side next day", "Move once after the park if bags can follow", "Storage, collection deadline, driver, new reception and cancellation terms"]] },
  { id: "scenarios", type: "heading", level: 2, text: "Two sequences, two different answers" },
  { id: "scenario-one", type: "comparison", title: "Scenario A: two park days, then Tianmen Mountain and an evening flight", columns: [{ heading: "All city", body: "One hotel, but repeated city–park travel consumes two mornings or evenings and makes an early park start harder." }, { heading: "All Wulingyuan", body: "The park days are simpler, but Tianmen Mountain and the departure day inherit the cross-area transfer risk." }, { heading: "One move", body: "Two Wulingyuan nights, then one city night can replace repeated backtracking if luggage storage and transfer are confirmed." }] },
  { id: "scenario-two", type: "callout", title: "Scenario B: late arrival, two children and only one park day", tone: "neutral", body: "Suppose the family arrives late, visits Tianmen Mountain first, has one forest-park day and leaves from Zhangjiajie West the next morning. Staying in the city throughout may protect sleep and remove a pack–move–check-in cycle. If the park ticket requires an early entrance and a reliable transfer is confirmed, one Wulingyuan night may become worthwhile. The same sights produce a different answer because the first and final nights and the luggage changed." },
  { id: "move-cost", type: "heading", level: 2, text: "Count the whole hotel move, not only the drive" },
  { id: "move-list", type: "list", items: ["Pack before the first attraction and keep medicines, passports and weather gear accessible.", "Check out, confirm every bag is tagged and obtain the storage deadline in writing.", "Reach the next base or return to collect luggage after the sightseeing route.", "Load and unload bags at a vehicle point that may not be the hotel door.", "Present each passport again so the new property can complete hotel registration.", "Absorb waiting time if a room is not ready or a driver cannot locate an English listing name.", "Repeat the access check for children, older travellers, wheelchairs or large cases."] },
  { id: "move-rule", type: "callout", title: "A practical move threshold", tone: "decision", body: "A move should buy a meaningful morning, remove at least two likely cross-area journeys, or protect a critical departure. If it only shortens one ride, one base is normally the more resilient plan. This is an editorial rule, not an official transport guarantee." },
  { id: "failure", type: "heading", level: 2, text: "Recover when the order changes" },
  { id: "failure-table", type: "table", caption: "Do not let one disruption trigger an unnecessary hotel chain", columns: ["Disruption", "Immediate action", "Recalculate"], rows: [["Train arrives too late for the Wulingyuan transfer", "Tell the booked property, stop relying on unconfirmed night transport and secure a staffed city room", "Choose the next base from the first sight that remains executable"], ["Road, cableway or entrance arrangement changes", "Check the current official scenic notice and whether the ticket remains valid", "Look at the next two travel legs; keep the room if moving no longer removes repeated travel"], ["Property cannot store or transfer bags as promised", "Keep the bags with a staffed property and ask for a written alternative", "Compare one extra transfer with the time and risk of moving"], ["Driver cannot find the hotel", "Send the Chinese property name, full address, phone and map pin", "Do not assume an English brand or neighbourhood label identifies the correct branch"]] },
  { id: "dynamic", type: "paragraph", text: "Official route examples, city–scenic transport reports, the Tianmen Mountain access reference and 12306 were reviewed on August 13, 2026. They establish geography and documented transport links, not current operation or a guaranteed schedule for your date. Recheck scenic notices, ticket entrance, exact railway station and property instructions shortly before travel." },
  { id: "check", type: "heading", level: 2, text: "Final booking check" },
  { id: "check-list", type: "list", items: ["Dated sight order and the exact ticket entrance", "Exact arrival and departure station shown on 12306 or the issued ticket", "Property's full Chinese name, address, phone and map pin", "Reception coverage for the real arrival window", "Passport check-in confirmed for every foreign guest", "Bag storage at both ends of a planned move", "Current transport for the required time, not a route that merely exists", "Cancellation terms and a city-side fallback for a disrupted late arrival"] },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Where to Stay in China", href: "/stay/", description: "Return to Homeground's lodging decision collection." }, { label: "Build your Zhangjiajie sightseeing order", href: "/guides/zhangjiajie-itinerary/", description: "Choose the park, Tianmen Mountain and surrounding-sight sequence before placing the nights." }, { label: "Connect Beijing, Zhangjiajie and Shanghai", href: "/guides/beijing-zhangjiajie-shanghai-transport/", description: "Check the intercity leg and the exact Zhangjiajie arrival point." }, { label: "Plan Zhangjiajie for older travellers", href: "/guides/zhangjiajie-older-travellers/", description: "Adjust the base move for walking load, rest and mobility." }] },
  { id: "consult", type: "callout", title: "Need a human base check?", tone: "neutral", body: "Send your travel dates, traveller count, confirmed Zhangjiajie sights, arrival and departure details, and approximate accommodation budget. A planner can help judge the area and whether one move is worth it; this is not a hotel availability promise." },
  { id: "sources", type: "sources", title: "Official and first-party sources", items: [{ label: "Two-day Zhangjiajie Global Geopark route", url: "https://zhangjiajieuggp.org.cn/html/2026/2026032620135033852.html", publisher: "Zhangjiajie UNESCO Global Geopark", reviewedAt: "2026-08-13" }, { label: "Three-day Zhangjiajie Global Geopark route", url: "https://zhangjiajieuggp.org.cn/html/2026/2026032620161311924.html", publisher: "Zhangjiajie UNESCO Global Geopark", reviewedAt: "2026-08-13" }, { label: "Tianmen Mountain visitor-transport reference", url: "https://whhlyt.hunan.gov.cn/whhlyt/wldh2022jt/202208/t20220823_27716284.html", publisher: "Hunan Provincial Department of Culture and Tourism", reviewedAt: "2026-08-13" }, { label: "Zhangjiajie city–scenic passenger routes", url: "https://jtt.hunan.gov.cn/xxgk/gzdt/szdt1/202506/t20250610_33706126.html", publisher: "Hunan Provincial Department of Transport", reviewedAt: "2026-08-13" }, { label: "Wulingyuan East Gate–South Gate ring bus", url: "https://jtt.hunan.gov.cn/jtt/xxgk/gzdt/szdt1/202506/t20250610_33706127.html", publisher: "Hunan Provincial Department of Transport", reviewedAt: "2026-08-13" }, { label: "Official rail ticket and station query", url: "https://www.12306.cn/", publisher: "China Railway 12306", reviewedAt: "2026-08-13" }] }
] } as const satisfies StructuredPageBody;
export default body;
