import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "decision-lead",
      type: "lead",
      text: "If a flight or train is already issued, the portal printed on it is fixed: SZX means Shenzhen Bao'an International Airport, 深圳北 means Shenzhen North, 福田 means Futian Railway Station and 深圳 means Shenzhen Railway Station in Luohu. If nothing is booked, compare the live service and the complete journey between your real doors. Do not choose by the word ‘Shenzhen’ or ‘Futian’ alone—Futian Railway Station is not Futian Checkpoint, and Shenzhen Railway Station is one specific station rather than a general name for every railway hub in the city.",
    },
    {
      id: "quick-answer",
      type: "callout",
      title: "The short answer",
      tone: "decision",
      body: "Use SZX only for an actual flight. Start a mainland-rail search with Shenzhen North when you want the broadest principal-hub shortlist, then compare any live Futian or Shenzhen Station option with the hotel transfer. Treat Futian and Luohu checkpoints as border anchors only after you have chosen a complete Shenzhen–Hong Kong route. Once a ticket is issued, its exact airport or station wins over every shortcut in this page.",
    },
    {
      id: "scope-boundary",
      type: "callout",
      title: "What this guide owns",
      tone: "neutral",
      body: "This page chooses a Shenzhen arrival or departure hub and helps recover from the wrong one. It does not reproduce the national high-speed-train process, publish fares or a timetable, decide Hong Kong entry eligibility, rank every border crossing, or choose between Futian, Luohu and Nanshan as hotel bases. Use the linked owners for those jobs. Other Shenzhen stations remain valid when they are printed on a live ticket; this is a decision guide for the principal international-visitor anchors, not an exhaustive station directory.",
    },
    {
      id: "five-name-check",
      type: "list",
      ordered: true,
      items: [
        "Identify the transport type first: flight, mainland/cross-boundary high-speed train, another mainland train, or pedestrian/road border crossing.",
        "Read the complete Chinese name on the issued record, not a translated map label: 深圳宝安国际机场, 深圳北, 福田, 深圳, 福田口岸 or 罗湖口岸.",
        "Save the real destination door: hotel lobby, office entrance, airport terminal, railway station or Hong Kong neighbourhood—not merely ‘downtown’.",
        "Build the chain at the actual hour with luggage, every interchange, the station or border walk and a legal road fallback.",
        "If the issued name and this guide disagree, follow the issued name and verify the current operator information.",
      ],
    },
    {
      id: "common-confusions",
      type: "heading",
      level: 2,
      text: "Six names that look closer than they are",
    },
    {
      id: "identity-table",
      type: "table",
      caption: "Save the Chinese name and the facility type together",
      columns: ["Name", "What it is", "What it is not"],
      rows: [
        ["Shenzhen North / 深圳北", "A major mainland and cross-boundary high-speed railway hub in Longhua", "A border checkpoint, Shenzhen Railway Station, or the airport"],
        ["Futian Railway Station / 福田站", "An underground railway station in the Futian CBD, connected to Metro Lines 2, 3 and 11", "Futian Checkpoint; the two require a separate city transfer"],
        ["Futian Checkpoint / 福田口岸", "A land-border inspection complex connected across the boundary to Hong Kong's Lok Ma Chau and East Rail", "Futian Railway Station or a high-speed-train platform"],
        ["Shenzhen Railway Station / 深圳站", "One exact railway station at 1003 Jianshe Road in Luohu", "A generic label for Shenzhen North, Futian, East or every other city station"],
        ["Luohu Checkpoint / 罗湖口岸", "A land-border inspection complex continuing to Hong Kong's Lo Wu and East Rail", "Shenzhen Railway Station, even though both anchors sit in the wider Luohu hub area"],
        ["Shenzhen Airport / 深圳宝安国际机场 (SZX)", "The flight gateway in Bao'an; its ground-transport system includes Airport Station", "Shenzhen North, or a promise that a pin called Airport North is your passenger terminal"],
      ],
    },
    {
      id: "matrix-heading",
      type: "heading",
      level: 2,
      text: "Choose the portal by the whole trip",
    },
    {
      id: "hub-matrix",
      type: "table",
      caption: "Principal Shenzhen arrival and departure anchors; live inventory and the issued record always control",
      columns: ["Portal", "When it enters the shortlist", "City-side test", "Mistake to prevent"],
      rows: [
        ["SZX airport / 深圳宝安国际机场", "Your booked flight uses SZX, or an unbooked air option wins after comparing the complete origin-to-hotel or hotel-to-destination journey", "Western Bao'an. Test the current Airport Station/Line 11 or Ground Transportation Center chain to the exact hotel at the flight's realistic exit or check-in time", "Do not navigate to Shenzhen North or Airport North merely because both names contain an airport or railway clue"],
        ["Shenzhen North / 深圳北", "A suitable train appears for the exact date; it is usually the first principal hub to test for the broadest railway choice", "Longhua, with municipal information listing Metro Lines 4, 5 and 6. Compare the full hotel-to-platform chain", "It is not Shenzhen Railway Station or a land checkpoint; a Hong Kong high-speed train leads to West Kowloon, not Lo Wu or Lok Ma Chau"],
        ["Futian Railway Station / 福田站", "A suitable live train serves it and the central Futian location reduces the complete transfer", "Futian CBD at Yitian Road and Shennan Boulevard, connected to Metro Lines 2, 3 and 11", "It is not 福田口岸. A cross-boundary high-speed-rail ticket and a pedestrian land-border route are different journeys"],
        ["Shenzhen Railway Station / 深圳站", "The live ticket says 深圳 and Luohu, Dongmen or the offered train pattern makes the total journey useful", "Luohu at 1003 Jianshe Road; municipal information lists Metro Lines 1 and 9 plus road connections", "‘Shenzhen Station’ is not a collective name. Do not substitute North, Futian or East, and do not treat the nearby Luohu Checkpoint as the same facility"],
        ["Futian or Luohu checkpoint / 福田口岸 or 罗湖口岸", "A complete Shenzhen–Hong Kong route has already selected the matching Hong Kong endpoint and the checkpoint is currently operating for your trip", "Futian connects to Lok Ma Chau; Luohu connects to Lo Wu. Include border processing, the Hong Kong-side rail chain, luggage and current hours", "A checkpoint is not a mainland railway departure station. This page identifies the anchor; the cross-border guide decides the route"],
      ],
    },
    {
      id: "issued-ticket-warning",
      type: "callout",
      title: "A closer hub cannot take a different ticket",
      tone: "warning",
      body: "Shenzhen's July 2026 railway adjustment recorded active services at Shenzhen North, Shenzhen, Futian and Shenzhen East, but the allocations were specific to that operating diagram. Direction, old habits and hotel distance are only search clues. After purchase, the exact origin and destination on the issued ticket control; a ticket for 深圳北 cannot be used at 深圳, and a ticket for 福田 cannot be used at a checkpoint.",
    },
    {
      id: "airport-heading",
      type: "heading",
      level: 2,
      text: "SZX: the flight fixes the airport; you still choose the ground chain",
    },
    {
      id: "airport-copy",
      type: "paragraph",
      text: "Shenzhen Airport's current transport information connects Airport Station with Metro Line 11 and points travellers to the Ground Transportation Center for airport-road services. That makes SZX workable for western Shenzhen and many central journeys, but a direct line on a map is not the same as a short terminal-to-lobby trip. Include aircraft arrival, immigration when applicable, baggage, the walk to ground transport, the last hotel segment and reception hours. For departure, reverse the chain and follow the airline's current terminal and check-in information.",
    },
    {
      id: "airport-rail-warning",
      type: "callout",
      title: "Airport Station and Airport North are transport nodes, not flight instructions",
      tone: "warning",
      body: "The municipal railway roster describes Shenzhen Airport Station as the intercity station connected with T3 and Metro Line 11. It describes Airport North as a different underground intercity/metro node associated with the airport's northern development. Neither name overrules the terminal shown by the airline. Do not infer a passenger terminal from a construction plan, an old map pin or the word ‘airport’; verify the flight and current airport wayfinding.",
    },
    {
      id: "rail-heading",
      type: "heading",
      level: 2,
      text: "For rail, search the date first—then compare the two city transfers",
    },
    {
      id: "rail-copy",
      type: "paragraph",
      text: "Before booking, search the exact route and date in the official railway channel. Put every workable train into a door-to-door comparison: hotel to the Shenzhen platform, scheduled rail time, and destination platform to the next door. North often supplies the widest principal-hub shortlist; Futian can remove a cross-city transfer for a central stay; Shenzhen Station can fit Luohu and some live services. None is a permanent direction rule. If the live ticket instead says 深圳东, 深圳坪山, 光明城, 平湖 or another exact station, follow it and verify that separate access rather than renaming it ‘Shenzhen Station’. The national first-time rail guide owns passport, ticket purchase, station entry and boarding.",
    },
    {
      id: "border-heading",
      type: "heading",
      level: 2,
      text: "Railway station, checkpoint and Hong Kong endpoint form different chains",
    },
    {
      id: "border-handoff",
      type: "table",
      caption: "Use these identity anchors, then hand the complete cross-border route to the Shenzhen–Hong Kong guide",
      columns: ["If your plan says", "Shenzhen-side anchor", "Hong Kong-side relationship", "What this page does not decide"],
      rows: [
        ["High-speed rail to or from Hong Kong West Kowloon", "The exact railway station on the ticket—often Futian or Shenzhen North in this comparison", "A reserved cross-boundary train reaches or leaves Hong Kong West Kowloon", "Train availability, immigration sequence, eligibility, fares, cutoffs or the West Kowloon last mile"],
        ["East Rail through Lok Ma Chau", "Futian Checkpoint / 福田口岸", "The pedestrian boundary bridge connects to Lok Ma Chau station and Hong Kong East Rail", "Whether this crossing best fits the Hong Kong door or its current operating window"],
        ["East Rail through Lo Wu", "Luohu Checkpoint / 罗湖口岸", "After border processing, the Hong Kong rail anchor is Lo Wu on East Rail", "Whether Luohu beats another port, the current queue or the onward Hong Kong route"],
        ["Shenzhen Bay or another road/sea port", "The exact named port—not any railway station in this matrix", "A separate road or sea arrival chain on the Hong Kong side", "The full port comparison, documents, current hours, operator or fallback"],
      ],
    },
    {
      id: "border-boundary",
      type: "callout",
      title: "Futian Station ≠ Futian Checkpoint; Shenzhen Station ≠ Luohu Checkpoint",
      tone: "warning",
      body: "Futian Railway Station lies in the CBD and uses the rail/metro complex at 福田站; Futian Checkpoint lies at the boundary and is signed 福田口岸. Shenzhen Railway Station and Luohu Checkpoint occupy the same wider transport district, but they remain separate facilities with separate passenger flows. Adjacency does not remove ticket, border, baggage or wayfinding steps.",
    },
    {
      id: "scenarios",
      type: "comparison",
      title: "Three real decisions",
      columns: [
        {
          heading: "Late flight, Futian hotel",
          items: [
            "SZX is fixed by the flight",
            "Estimate the realistic terminal exit, not the scheduled touchdown",
            "Use the airport's current Ground Transportation Center information if Line 11 no longer fits",
            "Do not race to a separate railway station or checkpoint simply to avoid an airport-side night",
          ],
        },
        {
          heading: "Several rail options, central stay",
          items: [
            "Search the exact date before choosing North, Futian or Shenzhen Station",
            "Compare hotel door to platform and destination platform to the next door",
            "Futian may win on the city transfer only when a suitable train is actually offered",
            "Once issued, the ticketed station is fixed",
          ],
        },
        {
          heading: "Hong Kong day from Luohu",
          items: [
            "Choose the Hong Kong endpoint and full route first",
            "Luohu Checkpoint may fit an East Rail journey through Lo Wu; a high-speed train uses West Kowloon instead",
            "A hotel near Shenzhen Railway Station does not turn its platform into a border crossing",
            "Check current checkpoint and Hong Kong service information before leaving",
          ],
        },
      ],
    },
    {
      id: "luggage-late-heading",
      type: "heading",
      level: 2,
      text: "Luggage, late arrivals and tight connections change the winner",
    },
    {
      id: "fragile-trips",
      type: "table",
      caption: "Choose for the weakest link, not the fastest advertised segment",
      columns: ["Condition", "Better decision test", "Fallback to prepare"],
      rows: [
        ["Two large cases, children, older parents or slower walking", "Prefer fewer handoffs, clear lifts, one meeting point and a shorter uncontrolled walk—even when the scheduled ride is longer", "A legal vehicle route sized for the group; never assume one step-free station makes the whole chain step-free"],
        ["Very early rail or flight departure", "Verify the complete first-service or road chain to the exact entrance, then work backwards from a conservative arrival target", "A better-aligned final-night base, chosen through the stay guide rather than by this hub page"],
        ["Late flight arrival", "Use realistic deplaning, immigration, baggage and terminal-exit time before testing metro or airport-road services", "The current airport night-transport channel or an airport-side night; do not promise a connection from touchdown time"],
        ["Flight followed by a separately ticketed train", "Treat it as unprotected: include delay, airport exit, cross-city transfer and station entry", "A changeable later train or an overnight break; separate sellers do not protect the connection"],
        ["Border crossing near closing time", "Include Shenzhen approach, both inspections, the Hong Kong onward service and luggage walking", "Use the cross-border guide to select a currently operating alternative; this page does not rank ports"],
      ],
    },
    {
      id: "wrong-hub-heading",
      type: "heading",
      level: 2,
      text: "At the wrong hub? Recover in this order",
    },
    {
      id: "wrong-hub-recovery",
      type: "list",
      ordered: true,
      items: [
        "Stop and read the complete Chinese name, facility type, date and time. A map pin is not an issued ticket or flight record.",
        "Decide whether you are at the correct facility but the wrong entrance, square or level, or at a genuinely different airport, railway station or checkpoint. Ask uniformed staff when the signs are unclear.",
        "For a flight, confirm the airport and current terminal with the airline before moving. For rail, confirm the exact origin on the issued ticket. For a border journey, confirm the selected Shenzhen checkpoint and Hong Kong endpoint together.",
        "Calculate arrival at the correct passenger entrance with a normal check-in, station-entry or border margin. Do not count arrival at a road curb as arrival at the platform or gate.",
        "If the original booking remains clearly usable, take a verified metro or legal road route. Keep passports, luggage and the group together and share one meeting point.",
        "If the margin is unsafe, solve the booking before crossing the city: use the official airline/railway channel or staff for current change, refund or rebooking choices. A different Shenzhen station cannot simply accept the old ticket.",
        "If the error involves a checkpoint, move to the Shenzhen–Hong Kong route owner and current port/MTR sources. Crossing hours and the Hong Kong last mile—not name similarity—decide the recovery.",
      ],
    },
    {
      id: "recovery-cases",
      type: "table",
      caption: "Common wrong-name recoveries",
      columns: ["You are here", "But you need", "Immediate action"],
      rows: [
        ["Futian Railway Station / 福田站", "Futian Checkpoint / 福田口岸", "Treat it as a separate city transfer. Recheck checkpoint status and the Hong Kong onward chain before leaving the station"],
        ["Futian Checkpoint / 福田口岸", "A train from Futian Railway Station", "Read the rail ticket, estimate arrival at the railway entrance and contact the official railway channel or staff if the margin is unsafe"],
        ["Shenzhen North / 深圳北", "Shenzhen Railway Station / 深圳站", "They are different stations. Do not attempt to board; transfer only if the full margin is safe, otherwise change the ticket through the current official path"],
        ["Shenzhen Railway Station / 深圳站", "Hong Kong East Rail through Lo Wu", "Use Luohu Checkpoint only if the complete cross-border plan selects it and it is operating; the mainland railway platform is not the Hong Kong entrance"],
        ["Airport North / 机场北", "A departing flight", "Verify the airline's current terminal and follow airport wayfinding. The rail/metro node name is not a boarding instruction"],
        ["A driver searched ‘Shenzhen station’", "Any exact hub", "Send the Chinese name, address and verified pin. Do not rely on an English city-name search"],
      ],
    },
    {
      id: "checklist-heading",
      type: "heading",
      level: 2,
      text: "First-time traveller checklist",
    },
    {
      id: "checklist",
      type: "list",
      ordered: false,
      items: [
        "Transport type: flight, railway or border crossing",
        "Exact code/name: SZX plus terminal, or the complete Chinese station/checkpoint name",
        "Issued record: flight/train number, date, time, origin, destination and valid booking status",
        "Real door at both ends: hotel branch and lobby, office entrance, airport terminal or Hong Kong neighbourhood",
        "Current chain: metro/rail/road route, each interchange, internal walk, border steps when applicable and live operating window",
        "Human factors: luggage count, children, slower walker, lift dependence, rain and one group meeting point",
        "Connection status: protected through-ticket or separate, unprotected bookings",
        "Recovery threshold: the time at which you stop crossing the city and ask the current operator for a booking solution",
      ],
    },
    {
      id: "dynamic-boundary",
      type: "table",
      caption: "What stays useful and what must be checked again",
      columns: ["Status", "Information", "Action"],
      rows: [
        ["Durable logic", "Airport, railway stations and checkpoints are different facility types; an issued name controls; both city transfers matter", "Use these rules on every Shenzhen arrival and departure"],
        ["Rechecked 21 August 2026", "Municipal sources listed the named station identities and connections; the July railway diagram showed current activity at North, Shenzhen, Futian and East; port and airport sources provided live verification paths", "Treat this as a dated baseline, not an eternal route or operating guarantee"],
        ["Check for every trip", "Actual flight terminal, train and station, ticket inventory, entrance, metro first/last service, Ground Transportation Center services, checkpoint status/hours, Hong Kong onward service, disruption and road conditions", "Use the airline, 12306, Shenzhen Airport, Shenzhen transport/port authorities and MTR shortly before travel"],
      ],
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "Frequently asked questions",
    },
    {
      id: "faq",
      type: "table",
      caption: "Fast answers to the questions that cause wrong-hub trips",
      columns: ["Question", "Answer"],
      rows: [
        ["Which Shenzhen railway station is the default?", "There is no universal default. Shenzhen North is a sensible first principal hub to search, but a live Futian or Shenzhen Station train may produce the better complete journey. The issued ticket decides."],
        ["Is Futian Station the same as Futian Checkpoint?", "No. 福田站 is a CBD railway/metro complex; 福田口岸 is a separate land-border complex connecting to Hong Kong's Lok Ma Chau and East Rail."],
        ["Are Shenzhen Station and Shenzhen North the same?", "No. 深圳站 is the specific Luohu station; 深圳北 is the major Longhua hub. Tickets and map pins are not interchangeable."],
        ["Is Shenzhen Railway Station next to Luohu Checkpoint?", "They sit in the same wider Luohu transport area, but remain separate facilities. Add the signed walk, border processing and Hong Kong onward route rather than treating them as one platform."],
        ["Can I take a train from Futian to Hong Kong?", "Only when a live cross-boundary high-speed-rail ticket names Futian and Hong Kong West Kowloon. That is different from using Futian Checkpoint to Lok Ma Chau/East Rail."],
        ["Is Airport Station the same as the SZX terminal?", "Airport Station serves the airport transport complex, but the airline's current terminal and airport signs control the flight. Airport North is another transport node, not a substitute flight terminal."],
        ["Can I land at SZX and catch a train the same day?", "Sometimes, but a separate ticket is unprotected. Budget for flight delay, immigration when applicable, baggage, terminal exit, the complete city transfer and station entry; use a later train or overnight when the chain is fragile."],
        ["Why are there no fixed travel times, fares or last trains here?", "They change with the travel date, operating diagram, traffic, disruption and checkpoint status. Publishing one number would create false confidence; use the current official channels listed below."],
      ],
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue planning",
      items: [
        {
          label: "Shenzhen to Hong Kong transport route",
          href: "/guides/shenzhen-hong-kong-transport-route/",
          description: "Choose the complete cross-border route, checkpoint, Hong Kong endpoint and recovery path after the Shenzhen anchor is clear.",
        },
        {
          label: "Where to stay in Shenzhen: Futian, Luohu or Nanshan",
          href: "/guides/shenzhen-where-to-stay-futian-luohu-nanshan/",
          description: "Choose the overnight base by repeated addresses and the exact arrival hub, not by a district name alone.",
        },
        {
          label: "China high-speed train first-time guide",
          href: "/guides/china-high-speed-train-first-time-guide/",
          description: "Use this after the exact station pair is settled for booking, documents, station entry and boarding.",
        },
        {
          label: "Private transfer or public transport in China",
          href: "/guides/china-private-transfer-or-public-transport/",
          description: "Choose the last mile by luggage, handoffs, walking and recovery rather than map distance alone.",
        },
        {
          label: "Guangzhou, Shenzhen and Hong Kong route order",
          href: "/guides/guangzhou-shenzhen-hong-kong-route-order/",
          description: "Decide whether Shenzhen is a real stay or only a transfer before fixing the regional sequence.",
        },
        {
          label: "Last night before an international flight",
          href: "/guides/china-last-night-before-international-flight/",
          description: "Protect an early SZX departure or fragile separate connection with a better final-night decision.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources and image credit",
      items: [
        {
          label: "Shenzhen Transport Bureau railway-station roster",
          url: "https://jtys.sz.gov.cn/jtzx/wycx/hccx/hczfb/",
          publisher: "Transport Bureau of Shenzhen Municipality",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Official Shenzhen North Railway Station profile",
          url: "https://jtys.sz.gov.cn/jtzx/wycx/hccx/hczfb/content/post_12904228.html",
          publisher: "Transport Bureau of Shenzhen Municipality",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Official Futian Railway Station profile",
          url: "https://jtys.sz.gov.cn/jtzx/wycx/hccx/hczfb/content/post_11457302.html",
          publisher: "Transport Bureau of Shenzhen Municipality",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Official Shenzhen Railway Station profile",
          url: "https://jtys.sz.gov.cn/jtzx/wycx/hccx/hczfb/content/post_9979916.html",
          publisher: "Transport Bureau of Shenzhen Municipality",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Shenzhen Airport official metro connections",
          url: "https://www.szairport.com/szairporten/ditie/zlm_tt.shtml",
          publisher: "Shenzhen Bao'an International Airport",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Shenzhen railway operating-diagram update effective 1 July 2026",
          url: "https://www.sz.gov.cn/cn/xxgk/bmtx/content/post_12863893.html",
          publisher: "Shenzhen Municipal Government",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Current Shenzhen checkpoint status and official detail pages",
          url: "https://ka.sz.gov.cn/",
          publisher: "Office of Port of Entry and Exit of Shenzhen Municipal People's Government",
          reviewedAt: "2026-08-21",
        },
        {
          label: "MTR High Speed Rail destinations and live search entry point",
          url: "https://www.highspeed.mtr.com.hk/en/ticket/destination.html",
          publisher: "MTR Corporation",
          reviewedAt: "2026-08-21",
        },
        {
          label: "MTR East Rail cross-boundary relationship for Lo Wu and Lok Ma Chau",
          url: "https://www.mtr.com.hk/en/customer/main/eal-brand-service-campaign.html",
          publisher: "MTR Corporation",
          reviewedAt: "2026-08-21",
        },
        {
          label: "Hero: Shenzhen North Railway Station by Wpcpey, CC BY-SA 4.0",
          url: "https://commons.wikimedia.org/wiki/File:Shenzhen_North_Railway_Station_Outside_view_201809.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-21",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
