import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "샤먼 본섬과 구랑위는 마주 보지만 하나로 이어진 구시가지 산책이 아닙니다. 샤먼은 음식 골목, 사찰과 긴 해안이 있는 작동하는 도시입니다. 구랑위는 보행 섬으로 거리 조직, 정원, 음악사와 혼합 건축이 핵심입니다. 페리는 두 경험 사이의 시간 제한이 있는 경계입니다." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "첫 방문 하루라면 공식 관광객 페리가 이미 확인되었을 때 오전과 이른 오후를 구랑위에 줍니다. 여유 있게 본섬으로 돌아온 뒤 중산로·옛 항구 또는 해안 한 곳만 저녁에 고릅니다. 페리가 확정되지 않았다면 하루 종일 표를 쫓지 말고 좋은 샤먼 도시 일정을 만들며 구랑위를 다른 날로 옮기세요." },
  { id: "two-places-heading", type: "heading", level: 2, text: "두 장소에 각각 한 가지 일을 맡기세요" },
  { id: "two-places", type: "table", caption: "한 체크리스트가 아닌 두 방문", columns: ["장소", "지킬 것", "강요하지 않을 것"], rows: [["구랑위", "느린 거리 순서, 건축/정원 앵커 하나, 혼합 도시조직을 볼 시간", "모든 유료 장소·정상·해변·간식길 한 바퀴"], ["샤먼 본섬", "동네 또는 해안 이야기 하나, 저녁과 안정적 호텔 귀환", "난푸퉈·대학·중산로·해변·해안 마을을 한 저녁에"], ["페리 연결", "정확한 양쪽 터미널, 여권 주문, 체크인 여유와 날씨 대안", "이 글의 고정 시간표나 귀환 부두 보장"]] },
  { id: "ferry-boundary", type: "callout", title: "운영 절차는 전용 페리 가이드로", tone: "warning", body: "이 글은 판매 창, 터미널, 체크인 마감과 여권 처리를 반복하지 않습니다. 변동하며 이미 한 canonical owner가 있습니다. 샤먼 페리 공식 채널과 Homeground 터미널 글을 먼저 열어 왕복 구조를 이해한 뒤 경험을 배치하세요." },
  { id: "gulangyu-heading", type: "heading", level: 2, text: "구랑위에서는 길보다 테마를 먼저" },
  { id: "gulangyu", type: "comparison", title: "정직한 섬 방문 세 가지", columns: [{ heading: "건축과 골목", body: "연결된 역사 거리에서 남부 푸젠, 서양 고전주의, 베란다 식민 양식과 아모이 데코를 읽습니다. 세계유산 가치와 가장 가깝습니다." }, { heading: "정원과 전망", body: "정원·고지대·해안 전망 하나를 고르고 주변 골목을 더합니다. 현행 표, 줄과 날씨로 결정하세요." }, { heading: "느린 섬 분위기", body: "가장 붐비는 상가 골목을 벗어나 음악이나 안뜰에 머물고 명소 수를 줄입니다. 숙박이나 재방문에 좋습니다." }] },
  { id: "heritage", type: "paragraph", text: "유네스코는 구랑위를 중국과 외국의 교류가 도시 조직에 남은 역사적 국제 정착지로 설명하며 남부 푸젠, 서양 고전주의, 베란다 식민 양식과 아모이 데코를 언급합니다. 이 가치는 분산되어 있으므로 인기 핀만 달리면 섬을 성립시키는 거리망을 놓칩니다." },
  { id: "xiamen-heading", type: "heading", level: 2, text: "페리 뒤에는 샤먼 마무리 하나만" },
  { id: "xiamen", type: "table", caption: "저녁 마무리", columns: ["선택", "이유", "경계"], rows: [["옛 항구/중산로", "섬을 마주 보는 도시 쪽에 가깝고 음식과 거리 생활 추가", "가게·노점의 고정 시간을 보장하지 않음"], ["해안 한 구간", "빽빽한 보행 섬 뒤 열린 바다 대비", "합법 접근 하나만; 해안선은 매우 김"], ["호텔 근처 식사와 휴식", "더위, 지연, 짐이나 긴 보행 뒤 가장 좋음", "휴식은 성공적인 삭제"]] },
  { id: "day-heading", type: "heading", level: 2, text: "현실적인 하루 순서" },
  { id: "day", type: "list", ordered: true, items: ["구체적 출발 페리, 양쪽 터미널, 여권 주문과 귀환 틀을 확인합니다.", "현행 체크인 여유로 도착하고 촉박한 항공·열차에 붙이지 않습니다.", "구랑위에서 테마 하나와 유연한 두 번째 층을 완료합니다.", "점심에 두 번째 섬 앵커가 귀환을 지키는지 판단합니다.", "날씨와 이후 교통 여유로 본섬에 돌아옵니다.", "도시 한 구역, 저녁과 간단한 호텔 귀환으로 끝냅니다."] },
  { id: "cut", type: "callout", title: "페리 여유보다 두 번째 도시 구역을 먼저 빼세요", tone: "decision", body: "섬이 늦어지면 해변, 사찰, 대학이나 두 번째 시장을 뺍니다. 확인 안 된 부두, 짐을 끌고 달리기, 마지막 귀환을 열차·항공에 붙이지 마세요. 페리는 되돌리기 어려운 연결이고 샤먼 저녁이 유연한 층입니다." },
  { id: "who", type: "table", caption: "여행자별 조정", columns: ["여행자", "나은 계획"], rows: [["큰 짐", "검증된 보관 또는 본섬 기반; 섬의 걷기와 계단 고려"], ["노약자/보행 제한", "짧은 섬 구역, 앉는 휴식과 이른 귀환, 각 장소 계단 확인"], ["어린이", "식사·화장실·그늘을 지키고 날씨가 좋으면 정원/해변 대비"], ["늦은 도착", "본섬에 머물고 구랑위를 완전한 오전으로 이동"]] },
  { id: "failure", type: "table", caption: "회복 계획", columns: ["문제", "대응"], rows: [["확정 관광객 페리 없음", "구랑위를 오늘의 과제에서 빼고 샤먼 도시 일정"], ["잘못된 터미널 핀", "하차 전 공식 주문의 전체 중국어 이름 대조"], ["날씨 중단", "샤먼 페리 공지에 따르고 필요하면 본섬에 머묾"], ["섬 보행 지연", "두 번째 유료 장소를 빼고 여유 있게 귀환"], ["귀환 변경", "운영사 현행 지시를 따르고 영구 부두를 추정하지 않음"]] },
  { id: "overnight", type: "paragraph", text: "숙박은 결정을 바꿉니다. 이른·늦은 거리의 가치가 있지만 짐, 보행 마지막 구간과 페리 의존이 늘어납니다. 반복되는 섬 가치 때문에 고르고 호텔 수를 늘리기 위해 선택하지 마세요. 숙소 지역 글이 본섬과 섬 기반을 담당합니다." },
  { id: "links", type: "internal-links", title: "샤먼 계획 이어가기", items: [{ label: "샤먼 허브–구랑위 페리", href: "/ko/guides/xiamen-hubs-to-gulangyu-ferry-terminal/", description: "여권, 터미널과 페리 연결을 실행합니다." }, { label: "샤먼 숙소 지역", href: "/ko/guides/xiamen-where-to-stay-zhongshan-gulangyu-zengcuoan/", description: "중산로, 구랑위와 쩡춰안을 비교합니다." }, { label: "허브 왕복과 다중 거점", href: "/ko/guides/china-hub-and-spoke-or-multi-base-route/", description: "샤먼을 실제 거점으로 둘지 압축 경유지로 둘지 정합니다." }, { label: "중국 공휴일", href: "/ko/guides/china-public-holidays-travel-calendar/", description: "섬 방문 전 혼잡 압력을 확인합니다." }, { label: "일정이 너무 바쁜가요?", href: "/ko/guides/is-your-china-itinerary-too-rushed/", description: "페리와 보행 마찰을 계산합니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "구랑위 세계유산 설명", url: "https://whc.unesco.org/en/list/1541/", publisher: "유네스코 세계유산센터", reviewedAt: "2026-08-22" }, { label: "현재 관광객 구매와 여권 FAQ", url: "https://xmferry.com/wybm/wshlk/wlgpp/index.htm", publisher: "샤먼 페리", reviewedAt: "2026-08-22" }, { label: "현재 체크인과 귀환 FAQ", url: "https://xmferry.com/wybm/wshlk/chch/index.htm", publisher: "샤먼 페리", reviewedAt: "2026-08-22" }, { label: "대표 사진: Slyronit의 구랑위, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Gulangyu_Island_from_Zhongshan_Road,_Xiamen.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
