import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "厦门到鼓浪屿的交接要让四个名称一致：内地抵达枢纽、票面厦门码头、票面岛上码头与住宿。只解决“机场到轮渡”，仍可能坐错船。" },
  { id: "answer", type: "callout", title: "先买日期明确的船票，再连接枢纽", tone: "decision", body: "先使用厦门轮渡当前指引的官方渠道：FAQ目前引导游客通过微信公众号 `xmferry` 或支付宝生活号“屿见厦门轮渡”购票。选到有余位的航线并读取两端完整码头名后，再计算厦门机场、厦门站或厦门北站的接驳。不要因为旧地图上某个市区码头更近就自行替换。" },
  { id: "matrix-heading", type: "heading", level: 2, text: "不同起点改变内地接驳" },
  { id: "matrix", type: "table", caption: "船票决定码头", columns: ["起点", "主要风险", "需要预留"], rows: [
    ["厦门机场", "航班晚点、取行李、道路和停止办理时间", "稍晚船班或厦门本岛住宿备选"],
    ["厦门站", "出口、道路上车点与市区交通", "准确码头定位和足够办理时间"],
    ["厦门北站", "较长市内接驳与大型铁路枢纽", "铁路晚点缓冲和已确认直接接车"],
    ["厦门酒店", "地图距离短也可能遇到绕行与拥挤", "看票面码头，不搜“最近轮渡”"],
  ]},
  { id: "warning", type: "callout", title: "码头名称是运营事实", tone: "warning", body: "游客航线、市民航线、日间安排和临时调整不能互换。从当前订单复制厦门端与鼓浪屿端完整中文码头名，并把两者都给司机看。" },
  { id: "chain-heading", type: "heading", level: 2, text: "把整段路线安排到岛上酒店" },
  { id: "chain", type: "list", ordered: true, items: ["抵达枢纽到订单所列码头的准确入口。", "证件或登船凭证核验，以及停止检票前的充足时间。", "指定船班到指定岛上码头。", "码头到住宿的实际步行与行李安排。", "返程资格、内地后续交通与天气备选。"] },
  { id: "groups", type: "comparison", title: "行李会改变岛上到达", columns: [
    { heading: "一日游、轻装", items: ["可以接受更多步行", "随时留意回程余位", "携带订单名称"] },
    { heading: "住岛上酒店", items: ["询问酒店建议哪个码头", "单独确认行李协助", "不要假设有车辆接船"] },
    { heading: "家庭或大箱子", items: ["避开最紧衔接", "每位旅客保管自己的证件", "晚到可先住厦门本岛"] },
  ]},
  { id: "order-heading", type: "heading", level: 2, text: "计算公路接驳前先审订单" },
  { id: "order-copy", type: "paragraph", text: "打开已经完成的订单，逐项读取航行日期、出发时间、大陆一侧完整码头、岛上抵达码头和旅客证件。不要根据搜索结果截图或未付款购物车做计划。如果护照无法在线核验或系统要求人工处理，应按官方FAQ携带护照原件到人工售票处现场核验并取票。值船时携带同一本护照和订单记录，并把每位同行者的证件状态放进同一张清单。" },
  { id: "arrival-heading", type: "heading", level: 2, text: "按真实抵达时间选择船班" },
  { id: "arrival-matrix", type: "table", caption: "衔接缓冲从到达码头之前开始", columns: ["抵达模式", "更稳妥的选择", "原因"], rows: [
    ["上午航班或火车", "选择更晚的船，并明确留出延误余量", "取行李、出站和道路拥堵都不在船期内"],
    ["傍晚抵达", "保留厦门本岛住宿", "错过船班后可能已没有合理的当日上岛方案"],
    ["岛上住宿为独立订单", "确认酒店晚到流程和建议抵达码头", "轮渡运营方不负责住宿交接"],
    ["当天还有下一张订单", "不要把离岛回程压在火车或航班之前", "返程资格不是预留班次，天气也可能改变运营"],
  ]},
  { id: "island", type: "callout", title: "轮渡码头不是岛上酒店大堂", tone: "neutral", body: "鼓浪屿最后一段主要是步行与行李问题。把准确抵达码头发给酒店，询问建议步行路线，并确认是否真的提供行李协助。把中文地址和电话离线保存。石板巷、台阶、雨水和人流会让很短的距离变得困难；除非酒店按日期确认，否则不要承诺车辆或搬运行李服务。" },
  { id: "return-heading", type: "heading", level: 2, text: "把返程当成一次新的运营核查" },
  { id: "return-plan", type: "list", ordered: true, items: ["确认当前船票和航线符合计划返程条件，不只依赖通用有效期表述。", "核对所选日期的实时返程码头、排队或班次规则。", "从大陆的火车或航班倒推，加入岛上步行、值船、航行、出码头和公路接驳。", "设置最晚可接受的离岛时间和更早的恶劣天气备选。", "返程已经无法保护后续订单时，应提前一晚回厦门本岛，而不是继续压缩每一段。"] },
  { id: "recovery-heading", type: "heading", level: 2, text: "错码头或错过船" },
  { id: "recovery", type: "table", caption: "用运营方记录，不听街边建议", columns: ["问题", "应对"], rows: [
    ["司机到了另一个码头", "完整票面码头未匹配前不要取下行李"],
    ["航班或火车晚点", "使用轮渡官方改签渠道，并保护本岛过夜"],
    ["船票与证件不符", "找官方服务人员，不买绑定他人身份的转售票"],
    ["天气中断", "看厦门轮渡通知，改线前先通知岛上住宿"],
  ]},
  { id: "facts", type: "callout", title: "护照人工核验流程复核于8月23日；其余交通信息复核于2026年8月13日", tone: "neutral", body: "当前FAQ引导线上购票者使用官方微信或支付宝渠道；外国游客可用已实名认证的支付宝账号录入护照信息。护照无法在线核验或需要人工处理时，应携带护照原件到人工售票处现场核验并取票。预售期为15天（含乘船当日），每天9:00开放第15日船票。开航前20分钟开始检票、前10分钟停止检票。去程票通常包含20天内一次符合当期游客航线规则的免费返程，但不等于预订了固定返程船班或永久固定码头。官网同页仍有较旧说法，因此付款前应再次核对当前渠道与航线。" },
  { id: "help", type: "callout", title: "需要匹配枢纽和船票？", tone: "decision", body: "提供日期、航班或火车、票面两端码头、岛上酒店、人数和行李。Homeground可核对交接与时间缓冲，船票余位仍以官方运营方为准。" },
  { id: "links", type: "internal-links", title: "继续规划", items: [
    { label: "第一次坐中国高铁", href: "/zh/guides/china-high-speed-train-first-time-guide/", description: "在轮渡交接前准备铁路抵达。" },
    { label: "国际航班前最后一晚", href: "/zh/guides/china-last-night-before-international-flight/", description: "保护从岛上返回的接驳。" },
    { label: "你的行程是否太赶", href: "/zh/guides/is-your-china-itinerary-too-rushed/", description: "不要压缩铁路、道路和船班截止。" },
    { label: "外国游客如何在中国付款", href: "/zh/guides/how-to-pay-in-china-as-a-tourist/", description: "为内地交通保留付款备选。" },
    { label: "选择厦门住宿基地", href: "/zh/guides/xiamen-where-to-stay-zhongshan-gulangyu-zengcuoan/", description: "从轮渡、行李、清晨与夜晚、海边活动和后续交通比较中山路、鼓浪屿过夜与曾厝垵。" },
  ]},
  { id: "sources", type: "sources", title: "官方来源与图片署名", items: [
    { label: "官方网络购票FAQ：当前渠道、人工售票处护照核验取票与返程有效期", url: "https://xmferry.com/wybm/wshlk/wlgpp/index.htm", publisher: "厦门轮渡有限公司", reviewedAt: "2026-08-23" },
    { label: "2026年官方通知：预售期调整为15天", url: "https://www.xmferry.com/xwzx/zxgg/32338.htm", publisher: "厦门轮渡有限公司", reviewedAt: "2026-08-13" },
    { label: "官方检票与返程FAQ", url: "https://xmferry.com/wybm/wshlk/chch/index.htm", publisher: "厦门轮渡有限公司", reviewedAt: "2026-08-13" },
    { label: "首图：HualinXMN拍摄邮轮中心公交区域，CC BY 4.0，已裁切并转为WebP", url: "https://commons.wikimedia.org/wiki/File:Cruise_Center_Bus_Station(Xiamen)._20190203.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" },
    { label: "首图衍生文件许可证：CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-12" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
