import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "If your dates and candidate cities are chosen but the exact domestic trains are not yet bookable, do not freeze the whole trip and do not stop planning. Keep the route provisional. Commit only to items that remain workable if a rail assumption changes, use genuinely cancellable placeholders for dependent stays, and write down the official evidence that will turn each unknown into a confirmation. A railway reservation request, waitlist or third-party pre-order is not an issued ticket, so none of them should support a non-refundable chain downstream.",
    },
    {
      id: "scope-callout",
      type: "callout",
      title: "This guide starts in the middle of planning",
      body: "Use it only when you already have travel dates, a candidate city skeleton and a reason for each stop, but dated domestic rail inventory is unavailable. If you are still choosing cities, gateways or trip length, start with the First Trip Planner. When tickets go on sale, use the high-speed rail guide to execute the purchase, then return to this ledger to close the downstream dependencies.",
      tone: "neutral",
    },
    {
      id: "starting-state-heading",
      type: "heading",
      level: 2,
      text: "Decide the route skeleton without inventing a train",
    },
    {
      id: "starting-state-text",
      type: "paragraph",
      text: "A useful provisional route can name the city roles, broad date bands, direction and transfer edges without pretending that a future service exists. Write “City A → City B, rail to be verified,” not a copied train number from a different date. The edge remains a planning assumption until the official dated result shows the exact departure and arrival stations, time and status. That distinction lets you plan months ahead while keeping unsupported transport claims out of the itinerary.",
    },
    {
      id: "known-unknown-table",
      type: "table",
      caption: "What a route skeleton can settle before dated rail inventory exists",
      columns: ["May be decided now", "Must remain unknown", "Evidence that closes the gap"],
      rows: [
        ["Which city has a distinct job in the trip", "Whether one future train makes that stop convenient", "A dated official result plus the door-to-door station chain"],
        ["The broad direction between confirmed gateways", "The exact train, time, station pair, fare and seat", "Official order status explicitly shows an issued or fulfilled ticket matching the traveller, date and stations"],
        ["Which transfer days begin with no promised sightseeing", "Whether a usable morning or afternoon will actually remain", "Exact transport plus checkout, luggage, station and hotel-arrival facts"],
        ["Which visit or event could define the trip", "Whether its future inventory and entry terms will fit", "The named operator's current booking result and notice page"],
      ],
    },
    {
      id: "rail-boundary",
      type: "callout",
      title: "Do not turn one railway window into a national calendar",
      body: "As reviewed on 1 September 2026, ordinary sale timing and a limited advance-request pilot for eligible Beijing–Shanghai trains coexist. China Railway controls the exact state for each segment. This page records only whether your edge is unknown, requested, waitlisted or issued; use the rail guide for current windows, identity verification, purchase, change and refund procedures.",
      tone: "warning",
    },
    {
      id: "states-heading",
      type: "heading",
      level: 2,
      text: "Use four planning states instead of one word: booked",
    },
    {
      id: "states-table",
      type: "table",
      caption: "Homeground's route-readiness vocabulary",
      columns: ["State", "What it means", "What it does not permit"],
      rows: [
        ["Provisional route", "Dates and city order are a working hypothesis; at least one essential transfer or fixed visit is still unsupported", "Presenting exact timings, full sightseeing days or non-refundable dependent purchases as safe"],
        ["Conditionally committed", "One or more real purchases or cancellable holds exist, but the route still has a named open dependency", "Calling the whole route confirmed or removing its fallback"],
        ["Operator-confirmed item", "The responsible airline, railway, hotel or venue has provided final fulfilment confirmation for the exact product; a pending request, pre-order, waitlist or payment alone is excluded", "Assuming every linked item is also confirmed"],
        ["Executable route", "Every essential edge and trip-defining visit has evidence, exact nodes reconcile with the stays, and protected recovery remains", "A guarantee against delay, closure, fatigue or later operational change"],
      ],
    },
    {
      id: "weakest-link-rule",
      type: "callout",
      title: "The weakest essential dependency sets the route state",
      body: "Three confirmed hotels do not make an unissued rail edge real. An international flight does not confirm the domestic chain. A paid attraction does not create transport that reaches its entry window. Promote the route only when every essential dependency meets its own evidence test.",
      tone: "decision",
    },
    {
      id: "ledger-heading",
      type: "heading",
      level: 2,
      text: "Build one provisional-route ledger",
    },
    {
      id: "ledger-intro",
      type: "paragraph",
      text: "A calendar hides uncertainty because a coloured block looks equally solid whether it is an idea, a cancellable room or an issued ticket. Use a ledger beside the calendar. One row should describe one dependency and name the person or official channel responsible for checking it. If the row has no trigger, fallback or reversal consequence, it is not ready to control another purchase.",
    },
    {
      id: "ledger-fields",
      type: "table",
      caption: "Minimum fields for each route dependency",
      columns: ["Field", "Question to answer", "Example without inventing inventory"],
      rows: [
        ["Role", "Why does this item exist?", "Rail edge connects the second and third bases"],
        ["Current evidence", "What do you actually hold?", "No dated official result yet; only a planning assumption"],
        ["State", "Provisional, conditionally committed or operator-confirmed?", "Provisional"],
        ["Dependents", "What becomes unsafe if it fails?", "Third-city hotel, timed visit and onward airport transfer"],
        ["Reversal consequence", "Money, time or scarce inventory lost if changed?", "Hotel remains cancellable until its recorded deadline"],
        ["Trigger and responsible source or person", "When and where will it be checked?", "Search the exact date and station pair in Railway 12306 when available"],
        ["Fallback", "What changes first if it fails?", "Move the flexible visit, change the base date or remove the weakest stop"],
      ],
    },
    {
      id: "identity-prep",
      type: "paragraph",
      text: "Some preparation removes friction without committing money. Create one passport-based identity record and complete the current railway identity process before the relevant window. China Railway currently supports eligible foreign-passport verification online or at a station, but it does not promise how quickly an individual case will clear. “Account created” and “passenger verified for purchase” therefore belong in separate ledger rows. Use the passport-name guide for field-by-field correction and document-change recovery.",
    },
    {
      id: "commit-heading",
      type: "heading",
      level: 2,
      text: "Commit early only when the item survives the missing rail edge",
    },
    {
      id: "commit-rule",
      type: "paragraph",
      text: "The useful question is not “Do flights come before hotels?” It is “If the assumed rail edge changes, can this purchase still perform its job at an acceptable cost?” An international ticket can sensibly fix the first and last gateways when the route has more than one workable domestic connection and its fare conditions are acceptable. The same ticket is premature when a family event, entry condition or only workable route direction remains unresolved. Read the contracting carrier, actual carrier, connection structure, baggage and the exact fare's change and refund terms; airline categories alone do not reveal flexibility.",
    },
    {
      id: "placeholder-table",
      type: "table",
      caption: "How to treat possible early commitments",
      columns: ["Item", "May be placed early when", "Keep it provisional when"],
      rows: [
        ["International flight", "The gateways and dates remain useful under every credible domestic fallback, and the issued fare conditions are acceptable", "One unverified domestic edge is the only way to reach the departure gateway"],
        ["Accommodation placeholder", "The terms attached to that exact room and rate plan state a workable cancellation deadline, payment method and no-show consequence", "“Free cancellation” lacks a usable deadline, the room is non-refundable or the station/base may change"],
        ["Trip-defining venue or event", "Its official result is available and the day still works if the rail edge moves within the allowed range", "Admission is not released, the venue day depends on an assumed arrival, or a request has not been accepted"],
        ["Local flexible activity", "It can move or disappear without harming the trip", "It is being used to make a transfer day look complete"],
      ],
    },
    {
      id: "hotel-terms",
      type: "callout",
      title: "A hotel is not automatically the flexible layer",
      body: "The 2025 online-platform accommodation booking industry standard specifies that cancellation labels disclose their conditions, channel, deadline and refund path. That does not make every room cancellable. Read the terms attached to that exact room and rate plan. An unclear, prepaid or non-refundable room is a hard commitment even if another rate at the same property is flexible.",
      tone: "warning",
    },
    {
      id: "triggers-heading",
      type: "heading",
      level: 2,
      text: "Give every unknown its own official trigger",
    },
    {
      id: "triggers-text",
      type: "paragraph",
      text: "A single reminder labelled “book China” is too vague. Different operators release and change information on different schedules. Even two Beijing museums currently using seven-day reservation windows publish different release times, entry periods and missed-reservation consequences. That coincidence does not create a seven-day rule for China. Record the exact responsible source or person and trigger for each trip-defining item, and re-read the live terms when the trigger arrives.",
    },
    {
      id: "trigger-table",
      type: "table",
      caption: "A trigger register closes assumptions one by one",
      columns: ["Dependency", "Trigger", "Status after the trigger"],
      rows: [
        ["Domestic rail edge", "The exact date and station pair become searchable or eligible for the current official request path", "Still pending until official status explicitly shows the ticket was issued or fulfilled; payment alone is not proof"],
        ["Waitlisted rail option", "The official order changes to fulfilled or expires", "Confirmed only when the official result shows fulfilment and the traveller, date, train and stations match; otherwise activate the fallback"],
        ["Trip-defining venue", "Its own official window opens and temporary notices are checked", "Confirmed only when the correct person, date, period and document are accepted"],
        ["Cancellable accommodation", "Its recorded free-cancellation deadline approaches", "Keep, move or cancel after checking all upstream edges"],
        ["Public-holiday pressure", "The State Council publishes the relevant annual calendar or the dates overlap a confirmed holiday", "Increase checking and fallback strength without predicting a sell-out or inventing a crowd score"],
      ],
    },
    {
      id: "request-not-ticket",
      type: "callout",
      title: "Request, waitlist, payment and ticket are different states",
      body: "China Railway's current systems include flows where a traveller submits a request or prepays a waitlist. Neither is proof that the journey has been issued. Read the official order result. A third-party “pre-order” may be only an instruction to try later; its own terms cannot turn unavailable railway inventory into a ticket.",
      tone: "warning",
    },
    {
      id: "dependency-heading",
      type: "heading",
      level: 2,
      text: "Run a dependency test before every non-refundable purchase",
    },
    {
      id: "dependency-questions",
      type: "list",
      ordered: true,
      items: [
        "Name the upstream fact. Which exact transport, gateway, station, venue or legal constraint must be true for this purchase to work?",
        "Name the current evidence. Is it an official issued result, a cancellable hold, a request, a waitlist or only an assumption copied from another date?",
        "Name the recovery. If the upstream fact fails, can you move or cancel this item before losing money or a protected day?",
        "Name the deadline. Does the downstream cancellation deadline arrive before or after the upstream trigger can realistically produce evidence?",
        "Make the decision. Commit only if the item is independent, the reversal consequence is acceptable, or a documented fallback keeps the route viable.",
      ],
    },
    {
      id: "dependency-matrix",
      type: "table",
      caption: "The evidence and deadline decide—not the product category",
      columns: ["Upstream state", "Downstream terms", "Action"],
      rows: [
        ["Officially confirmed", "Consequences understood and acceptable", "Commit, then attach the confirmation to the ledger"],
        ["Provisional", "Cancellable after the expected verification trigger", "A placeholder may be rational; record the exact deadline"],
        ["Provisional", "Cancellation expires before verification", "Wait, change the downstream terms or redesign the dependency"],
        ["Requested or waitlisted", "Non-refundable", "Do not treat the request as permission to commit"],
        ["Officially confirmed but exact station breaks the base", "Hotel still cancellable", "Move the base before tightening the room terms"],
      ],
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Three travellers can share the same skeleton and need different commitments",
    },
    {
      id: "scenario-linear",
      type: "callout",
      title: "Traveller A: open-jaw gateways, two unissued rail edges",
      body: "The international ticket arrives in the first city and leaves from the last, and both domestic edges have candidate rail or air recovery paths. Those alternatives remain provisional until the responsible operators confirm them for the dates. The traveller may accept the flight's fare conditions and hold rooms whose cancellation deadlines fall after the rail checks. The route remains conditionally committed, not executable. A later station mismatch should change the affected base or flexible activity before it changes the gateways.",
      tone: "neutral",
    },
    {
      id: "scenario-event",
      type: "callout",
      title: "Traveller B: one immovable event inside the route",
      body: "A family event or officially confirmed performance fixes one city and date. That fact becomes an upstream constraint. The surrounding cities may remain a skeleton until both sides of the event have verified transport. If the only assumed rail connection would arrive too late, delete or move the weaker neighbouring stop; do not solve the conflict by counting the event day as a transfer and sightseeing day at once.",
      tone: "decision",
    },
    {
      id: "scenario-constrained",
      type: "callout",
      title: "Traveller C: holiday dates, mobility limits and larger luggage",
      body: "The official holiday calendar creates a pressure trigger but proves neither a sell-out nor a price rise. This traveller needs stronger evidence before the rooms become non-refundable: exact stations, a manageable hotel transfer, lift or assistance checks, and a recovery option that does not require a rushed same-day flight. The same city skeleton therefore stays provisional longer than Traveller A's, even if both see the same trains in an old timetable.",
      tone: "warning",
    },
    {
      id: "recovery-heading",
      type: "heading",
      level: 2,
      text: "Repair the cheapest dependency before rebuilding the trip",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "Failure-state recovery after the official rail check",
      columns: ["What changed", "First repair", "Escalate only if"],
      rows: [
        ["The useful service uses a different station", "Recalculate both hotel–station chains and move a cancellable base if needed", "The station change destroys a trip-defining visit or protected departure"],
        ["No workable direct option appears", "Compare a verified transfer or air edge and remove transfer-day sightseeing", "Every alternative consumes the only complete day that justified the stop"],
        ["A request or waitlist remains unfulfilled", "Keep the fallback active and cancel dependent placeholders before their deadlines", "The stop has enough value and time to justify a different confirmed mode"],
        ["A venue window conflicts with the issued transport", "Move the replaceable activity or use another official period", "The venue is the reason for the city and no safe period remains"],
        ["A hotel deadline arrives before the rail result", "Replace it with later-cancellation terms or release the room", "The property itself is trip-defining and the loss is knowingly acceptable"],
        ["The international flight changes a gateway or time", "Protect entry or departure first and reopen all dependent edges", "No domestic recovery preserves the route's essential roles"],
      ],
    },
    {
      id: "recovery-order",
      type: "paragraph",
      text: "Recover from the outside in. Remove a flexible meal or neighbourhood block before a trip-defining visit; move a cancellable room before an issued international flight; remove the weakest city before compressing several complete days into transfer fragments. This ordering is Homeground editorial judgment. It limits cascading losses but does not predict what inventory an operator will provide.",
    },
    {
      id: "executable-heading",
      type: "heading",
      level: 2,
      text: "Promote the route only when the evidence makes it executable",
    },
    {
      id: "executable-checklist",
      type: "table",
      caption: "Final state-transition check",
      columns: ["Check", "Required evidence", "If missing"],
      rows: [
        ["International edges", "Issued itinerary, exact airports and terminals, operating and contracting carriers, baggage and fare conditions", "Keep the affected gateway dependency open"],
        ["Domestic edges", "Official status explicitly shows an issued or fulfilled ticket matching the traveller, date, service and exact stations or airports", "Keep the route provisional and protect fallback deadlines"],
        ["Complete transfer chain", "Hotel checkout, luggage, terminal access, arrival transfer and next-door opening all fit", "Count no promised sightseeing and change the base or edge"],
        ["Trip-defining visits", "Correct date, period, document, admission result and current temporary notices", "Use the named replacement or reconsider the stop"],
        ["Stays", "Exact address, check-in/luggage response, payment, cancellation and no-show terms fit the confirmed nodes", "Keep or replace only with reversible terms"],
        ["Recovery", "Name the most fragile essential dependency, test one specific failure and show that the international departure or essential event remains protected", "Add buffer, remove the weakest dependency or redesign"],
      ],
    },
    {
      id: "final-verification",
      type: "paragraph",
      text: "Run the ledger again before each cancellation deadline and shortly before travel. Use the operating airline, Railway 12306 order, named venue notice and exact hotel order—not a saved search result—as the final authority. “Executable” means the planned chain is supported now. It is not a promise that operators, weather or the traveller's energy cannot change later.",
    },
    {
      id: "editorial-boundary",
      type: "callout",
      title: "Assumptions must stay visible",
      body: "The four route states, dependency test and outside-in recovery order are Homeground editorial tools. Official sources establish ticket states, contract fields, venue rules and holiday dates. They do not certify this framework, calculate a route score or guarantee that a particular itinerary will work.",
      tone: "neutral",
    },
    {
      id: "help-cta",
      type: "callout",
      title: "Need a human to test the provisional chain?",
      body: "Leave your dates, traveller count, approximate budget, candidate cities and any commitments already paid. Homeground can identify which assumptions still control the route and which official facts must be rechecked, without presenting unavailable trains or venue inventory as confirmed.",
      tone: "decision",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue planning",
      items: [
        { "label": "Use the First Trip Planner", "href": "/plan/", "description": "Choose constraints, cities, route shape, transport, stays and buffers before entering this narrower provisional stage." },
        { "label": "Prepare for a first high-speed train", "href": "/guides/china-high-speed-train-first-time-guide/", "description": "Check current sale states, passport verification, purchase, station and boarding execution." },
        { "label": "Compare open-jaw and same-city flights", "href": "/guides/china-open-jaw-flights-route-planning/", "description": "Decide whether different international gateways remove a return journey." },
        { "label": "Check China's official holiday calendar", "href": "/guides/china-public-holidays-travel-calendar/", "description": "Verify the published holiday and adjusted-workday dates without relying on a crowd score." },
        { "label": "Verify official and reseller attraction tickets", "href": "/guides/official-or-reseller-china-tickets/", "description": "Identify the responsible ticket issuer and distinguish a seller order from admission confirmed by the attraction or operator." },
        { "label": "Protect a flexible arrival day", "href": "/guides/china-arrival-day-booked-anchor-or-flexible-block/", "description": "Decide whether the arrival chain can support a timed reservation." },
        { "label": "Keep passport names consistent", "href": "/guides/passport-name-across-china-bookings/", "description": "Prepare one identity record for flights, rail, hotels and real-name bookings." }
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        { "label": "Railway 12306 ticket and identity rules", "url": "https://kyfw.12306.cn/otn/gonggao/saleTicketMeans.html", "publisher": "China Railway 12306", "reviewedAt": "2026-09-01" },
        { "label": "Railway 12306 waitlist rules", "url": "https://kyfw.12306.cn/otn/gonggao/alternate.html", "publisher": "China Railway 12306", "reviewedAt": "2026-09-01" },
        { "label": "Ordinary advance-sale notice", "url": "https://www.12306.cn/mormhweb/zxdt/202205/t20220531_37508.html", "publisher": "China Railway 12306", "reviewedAt": "2026-09-01" },
        { "label": "Beijing–Shanghai advance-request pilot update", "url": "https://jnjtj.jinan.gov.cn/col/col15131/art/2026/art_3c25b7293e224f439f9a3053a9b104e2.html", "publisher": "Jinan Municipal Transportation Bureau", "reviewedAt": "2026-09-01" },
        { "label": "Public Air Transport Passenger Service Rules", "url": "https://www.caac.gov.cn/XXGK/XXGK/MHGZ/202103/t20210315_206814.html", "publisher": "Civil Aviation Administration of China", "reviewedAt": "2026-09-01" },
        { "label": "Online tourism platform accommodation booking standard LB/T 094—2025", "url": "https://zwgk.mct.gov.cn/zfxxgkml/hybz/202505/W020250520321654696062.pdf", "publisher": "Ministry of Culture and Tourism", "reviewedAt": "2026-09-01" },
        { "label": "Palace Museum booking instructions", "url": "https://www.dpm.org.cn/subject_booking/", "publisher": "Palace Museum", "reviewedAt": "2026-09-01" },
        { "label": "National Museum of China reservation instructions", "url": "https://www.chnmuseum.cn/cg/", "publisher": "National Museum of China", "reviewedAt": "2026-09-01" },
        { "label": "2026 public-holiday and adjusted-workday calendar", "url": "https://www.gov.cn/gongbao/2025/issue_12406/material/gwygb202532.pdf", "publisher": "State Council of the People's Republic of China", "reviewedAt": "2026-09-01" }
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
