import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "For accompanied medicine entering mainland China, start with active ingredients—not brand. Ordinary medicine still needs small/reasonable personal-use quantity under Customs supervision. A controlled-list match, uncertain ingredient/quantity or conflicting answer means ask before flying. There is no universal day supply. Documents, declaration and prior advice never guarantee clearance; arrival Customs decides." },
    { id: "answer", type: "callout", title: "Carry, ask or no-go", tone: "decision", body: "Carry is only a candidate after ingredient, purpose, quantity and evidence support personal use. Ask 12360/arrival Customs about uncertainty. No-go means do not board with the unresolved medicine: ask the prescriber for a safe not-carry/alternative plan. Never stop, substitute or change dose yourself." },
    { id: "scope", type: "callout", title: "Mainland passenger baggage only", tone: "warning", body: "Excluded: Hong Kong/Macao, commercial import, post, blood/biological products, needles/airlines, refrigeration and pharmacy supply. The NMPA organisational import permit and medical-personnel provincial certificate are not tourist applications." },
    { id: "triage-heading", type: "heading", level: 2, text: "Make the first decision before packing" },
    { id: "triage-table", type: "table", caption: "Planning triage—not clearance", columns: ["Path", "Use when", "Action"], rows: [["Carry candidate", "Ordinary classification; small/reasonable personal use; evidence ready", "Inventory; Customs decides"], ["Ask", "Match/possible match; ingredient/form/threshold/quantity unclear; conflict", "Send exact facts to 12360/port"], ["No-go", "Ingredient/path/evidence unconfirmed", "Ask prescriber for safe not-carry/alternative plan"]] },
    { id: "days", type: "callout", title: "Trip length is no allowance", tone: "warning", body: "Never turn personal use, reasonable quantity or itinerary into a 30-, 90- or trip-length rule. Official sources give ordinary medicine no universal days. Ask about the exact ingredient, form and amount." },
    { id: "ingredient-heading", type: "heading", level: 2, text: "Audit ingredients before reading traveller lists" },
    { id: "ingredient-list", type: "list", ordered: true, items: ["Copy each active ingredient and every related form named by the applicable catalogue note: salt, stereoisomer, ester or ether where relevant.", "Record strength, form and total units—not only boxes.", "List every compound ingredient and applicable threshold/footnote.", "Use brand/manufacturer/country only to identify.", "Search the 2025 catalogues by ingredient and every extension, form or compound condition named in the exact note.", "Record match/category/URL/date; an asterisk is no tourist-admission mark.", "No match is not automatically ordinary/allowed; unresolved means ask."] },
    { id: "ingredient-table", type: "table", caption: "One line per medicine", columns: ["Field", "Record", "Why"], rows: [["Ingredient", "Active name plus any named salt, stereoisomer, ester or ether", "Apply the exact catalogue note"], ["Form/strength", "Form, strength, compound ingredients", "Notes/thresholds"], ["Amount", "Containers/total units", "Quantity review"], ["Purpose", "Personal prescribed treatment", "Personal use"], ["Result", "Match, possible, none, unresolved", "No-match is not clearance"]] },
    { id: "documents-heading", type: "heading", level: 2, text: "Build an evidence packet; never call it a permit" },
    { id: "documents-table", type: "table", caption: "Evidence for review", columns: ["Item", "Include", "Boundary"], rows: [["Prescription", "Patient, ingredient, strength/form, quantity", "No clearance guarantee"], ["Record/diagnosis", "Institution, treatment need, date", "Article 44 requires diagnosis evidence"], ["Identity", "Entry passport/other proof", "Must match evidence"], ["Inventory", "Ingredient, form, strength, amount, containers", "Not authorisation"], ["Translation", "Original if available plus an accurate translation aid", "Ask the port about format; no replacement/guarantee"], ["Official reply", "Question, port, date, channel, reference", "On-site review remains"]] },
    { id: "article44", type: "callout", title: "Article 44 is narrow", tone: "warning", body: "For treatment, narcotic/Category I medicine is limited to one prescription's maximum with a medical-institution diagnosis certificate and identity proof; Customs reviews. The 2026 FAQ says Category II may be ‘appropriately extended’ but states no days. The reviewed official sources do not state one national rule for foreign-document language, translation/notarisation, issue age, electronic copies or mapping to China's prescription maximum. Ask the port." },
    { id: "confirm-heading", type: "heading", level: 2, text: "Ask Customs a question it can answer" },
    { id: "confirm-list", type: "list", ordered: true, items: ["Name arrival port/date.", "Give ingredient plus any relevant salt, stereoisomer, ester or ether, compounds, form, strength and amount.", "State personal treatment/itinerary without invented days.", "Ask category and which exact catalogue footnote, extension or threshold applies.", "For Article 44 ask diagnosis, identity, prescription maximum, language/translation/notarisation, date and electronic/original format.", "Ask declaration channel/process.", "Save page/reference/language/date; consultation is no permit. If contact, language or a formal answer fails, no answer is not permission: keep the medicine unresolved and use the prescriber-led no-carry plan."] },
    { id: "reply-table", type: "table", caption: "Preserve confirmation", columns: ["Field", "Save", "Missing"], rows: [["Authority", "12360/arrival Customs", "Use GACC's current guide to find the direct Customs site; no official answer stays unresolved"], ["Question", "Ingredient/form/amount/port", "‘My medicine’ is unusable"], ["Response", "Words, date, language, reference", "Clarify; do not infer"], ["Conflict", "Both versions/jurisdictions", "Narrow and escalate"]] },
    { id: "packing-heading", type: "heading", level: 2, text: "Prepare a Customs handoff, not a concealment strategy" },
    { id: "packing-list", type: "list", items: ["Match one inventory line per medicine to evidence.", "Keep medicine and originals/copies inspectable.", "Carry only reviewed personal-use amount; none for others/resale.", "Never hide, misdescribe or disperse unresolved quantity.", "Keep 12360/port reply and catalogue result offline.", "Check airline, needle, refrigeration and biological rules separately."] },
    { id: "scenario-one-heading", type: "heading", level: 2, text: "Scenario: ordinary medicine for a long itinerary" },
    { id: "scenario-one", type: "paragraph", text: "No catalogue match appears and a long trip needs several containers. That proves neither ordinary/allowed status nor an allowance. Complete ingredient/amount evidence and ask 12360/arrival Customs. The 2026 FAQ advises documents/declaration but creates no days or guarantee. If no official answer arrives, keep the medicine unresolved; silence is not permission." },
    { id: "scenario-two-heading", type: "heading", level: 2, text: "Scenario: a brand contains a controlled ingredient" },
    { id: "scenario-two", type: "paragraph", text: "Brand and prescription are insufficient. Record controlled ingredient/category. For narcotic/Category I, ask about Article 44's prescription maximum and diagnosis/identity evidence; never turn Category II's ‘appropriately extended’ into days. If unresolved, do not fly with it; ask the prescriber for a safe plan." },
    { id: "port-heading", type: "heading", level: 2, text: "At the mainland arrival Customs point" },
    { id: "port-steps", type: "list", ordered: true, items: ["Disclose uncertainty before choosing; if unsure, use things-to-declare/red and ask.", "Truthfully present medicine, inventory, medical evidence, identity and reply.", "Answer with ingredient, form, strength, amount and personal purpose.", "Accept inspection/instructions; prior advice is not clearance.", "Ask for available declaration/decision/reference record.", "Save result; it does not decide a changed future trip."] },
    { id: "declaration", type: "callout", title: "Declaration advice is not a universal red-channel law", tone: "decision", body: "The 2026 Chongqing FAQ advises medical evidence and proactive declaration; GACC separately defines channels. Declare/ask controls risk for controlled or uncertain medicine. It does not make red channel legally mandatory for every ordinary medicine." },
    { id: "refusal-heading", type: "heading", level: 2, text: "If Customs does not release the medicine" },
    { id: "failure-table", type: "table", caption: "Recover without escalation", columns: ["Failure", "Action", "Never"], rows: [["Ingredient unclear", "Give labels/evidence; ask what's missing", "Guess category"], ["Evidence insufficient", "Follow instructions; ask available record/option", "Claim guaranteed entry"], ["Quantity rejected", "Ask authorised return/storage/process/deadline", "Hide, disperse or abandon it on your own"], ["Advice conflicts", "Show reference; request reconciliation; save both", "Claim phone advice binds"], ["Cannot enter", "Ask the prescriber or insurer's medical-assistance channel for a safe clinical plan", "Stop, substitute or change the dose yourself"], ["Non-release directed", "Comply; preserve available record", "Discard, conceal or post it without Customs authorisation"]] },
    { id: "change-table", type: "table", caption: "Facts changing the answer", columns: ["Change", "Decision"], rows: [["Ingredient/category", "Restart catalogue/Customs check"], ["Amount/form", "Recheck quantity/Article 44"], ["Arrival port", "Ask actual port; do not transfer advice"], ["Catalogue/regulation", "Use new; archive old"], ["FAQ/national conflict", "Preserve both; national text/GACC process control; ask"], ["No documents", "Move to unresolved/no-go; consult prescriber"]] },
    { id: "freshness", type: "paragraph", text: "ReviewedAt: 2026-09-04. FreshnessClass: critical-on-customs-or-controlled-drug-change. Recheck GACC rules, Customs Law, controlled-drug regulation/catalogues, 12360 and port practice. The Chongqing English FAQ is operational guidance, not national law. For language/date/jurisdiction conflict, preserve versions and ask 12360/arrival Customs; infer no allowance." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final pre-flight check" },
    { id: "verify-list", type: "list", items: ["Every active ingredient identified.", "Every salt, stereoisomer, ester, ether, compound condition, form, strength, amount and container named by the relevant catalogue note was recorded.", "2025 catalogues dated; asterisk not treated as admission.", "No-match not called ordinary/allowed.", "No universal days invented.", "Article 44/Category II boundaries exact.", "Medical evidence, identity and inventory match.", "Exact uncertainties sent to 12360/port; failed contact or silence remains unresolved.", "Declaration advice not made universal law.", "Non-release has prescriber-led/Customs-compliant fallback.", "Nothing hidden, abandoned, posted or medically changed without instruction.", "SAR/excluded issues sent to their authorities."] },
    { id: "links", type: "internal-links", title: "Complete the arrival checks", items: [{ label: "Choose the correct China Customs channel", href: "/guides/china-customs-red-green-channels/", description: "Use the red/green decision without turning uncertainty into a clearance promise." }, { label: "Check food, plants and animal products", href: "/guides/food-plants-and-animal-products-into-china/", description: "Keep other biosecurity items in their separate official workflow." }, { label: "Complete the China online arrival card", href: "/guides/china-online-arrival-card/", description: "The arrival card does not replace a Customs medicine declaration." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Customs clearance of passenger baggage", url: "https://english.customs.gov.cn/statics/3a12c746-51e1-4d94-8fc1-44a573fad090.html", publisher: "General Administration of Customs", reviewedAt: "2026-09-04" }, { label: "Current passenger-baggage supervision service guide", url: "https://online.customs.gov.cn/static/pages/guides/000629014002/000629014002.html", publisher: "General Administration of Customs", reviewedAt: "2026-09-04" }, { label: "Requirements for carrying medicines for personal use", url: "https://english.cq.gov.cn/services/entryandexit/FAQs/202606/t20260629_15782389.html", publisher: "Chongqing Municipal Government / Chongqing Customs", reviewedAt: "2026-09-04" }, { label: "2025 medicinal narcotic and psychotropic drug catalogues, Announcement No. 55", url: "https://yjj.sh.gov.cn/qtgzwj/20250728/80ad6017cd9d41daa4181ddb4a044c9c.html", publisher: "NMPA, Ministry of Public Security and National Health Commission", reviewedAt: "2026-09-04" }, { label: "Regulation on Narcotic Drugs and Psychotropic Substances — current third revision", url: "https://xzfg.moj.gov.cn/front/law/detail?LawID=1744", publisher: "Ministry of Justice national administrative-regulations database", reviewedAt: "2026-09-04" }, { label: "Customs Law of the People's Republic of China", url: "https://english.customs.gov.cn/statics/644dcaee-ca91-483a-86f4-bdc23695e3c3.html", publisher: "General Administration of Customs", reviewedAt: "2026-09-04" }, { label: "NMPA organisational import permit for controlled medicines", url: "https://zwfw.nmpa.gov.cn/web/taskview/11100000MB0341032Y100017212800101", publisher: "National Medical Products Administration", reviewedAt: "2026-09-04" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
