import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "If your dates are flexible, mid-to-late October is usually the lower-friction choice for a first multi-city trip. If your international flight lands during Golden Week, the trip can still work: keep one city as your base through the holiday, secure the few reservations that truly matter, and postpone most intercity moves until the official break has ended.",
    },
    {
      id: "decision-summary",
      type: "comparison",
      title: "The short answer",
      columns: [
        {
          heading: "Choose Golden Week if",
          items: [
            "Your international dates cannot move.",
            "You can stay in one base rather than changing cities repeatedly.",
            "You are comfortable booking trains and headline sights at their official release times.",
            "You can accept queues, tighter availability and a backup plan for each day.",
          ],
        },
        {
          heading: "Choose mid-to-late October if",
          items: [
            "You want a multi-city first trip with several rail or flight legs.",
            "You value easier changes more than holiday atmosphere.",
            "Your group includes older travellers, young children or anyone with low queue tolerance.",
            "You are willing to trade warmer evenings and longer days for lower planning pressure.",
          ],
        },
      ],
    },
    {
      id: "dates-2026",
      type: "heading",
      level: 2,
      text: "The official 2026 dates are not the same as 2025",
    },
    {
      id: "dates-intro",
      type: "paragraph",
      text: "The State Council schedule makes Mid-Autumn Festival and National Day two separate breaks in 2026. There are three ordinary working days between them. The notice encourages people to combine public holidays with annual leave, so some travellers may bridge the gap, but September 28–30 are not an extended national public holiday.",
    },
    {
      id: "official-calendar",
      type: "table",
      caption: "Official 2026 holiday calendar and what it means for trip planning",
      columns: ["Date", "Official status", "Planning meaning"],
      rows: [
        ["Sunday, September 20", "Working day", "A make-up working day under the official schedule."],
        ["September 25–27", "Mid-Autumn Festival holiday", "A separate three-day break; late September is not a completely ordinary travel period."],
        ["September 28–30", "Ordinary working days", "Not part of an official eight- or ten-day Golden Week."],
        ["October 1–7", "National Day holiday", "This is the official seven-day National Day holiday, commonly called Golden Week."],
        ["Thursday, October 8 onward", "Holiday ended", "The official holiday has ended, but return journeys and spillover demand may continue; October 8 is not guaranteed to be quiet."],
        ["Saturday, October 10", "Working day", "The second make-up working day in the official schedule."],
      ],
    },
    {
      id: "claim-layers",
      type: "callout",
      tone: "neutral",
      title: "How to read this guide",
      body: "The holiday dates above are 2026 facts. The rail and attraction details below are current operator rules checked on August 10, 2026, and may still be updated. Recommendations such as reducing city changes are Homeground planning judgements, not government rules or promises about crowds, prices or weather.",
    },
    {
      id: "what-changes",
      type: "heading",
      level: 2,
      text: "What actually changes during Golden Week",
    },
    {
      id: "what-changes-intro",
      type: "paragraph",
      text: "The holiday does not switch China from normal to impossible. It changes the margin for error. A preferred train, well-located family room or timed-entry slot matters more when many domestic trips are concentrated into the same seven days. Later in the month, the main benefit is usually more choice and easier recovery when a plan changes—not an empty country.",
    },
    {
      id: "operational-comparison",
      type: "table",
      caption: "Golden Week and mid-to-late October: the practical differences",
      columns: ["Trip element", "October 1–7", "Mid-to-late October"],
      rows: [
        ["Intercity trains", "The fixed sales window becomes a hard planning deadline. Preferred direct trains or departure times may be unavailable.", "The same rules apply, but there is usually more room to compare times and recover from a missed first choice."],
        ["Domestic flights", "Convenient departure times and lower fare classes may narrow. There is no single national Golden Week release time.", "Choice can improve, but a later date does not automatically mean a cheaper fare; route, weekday and local events still matter."],
        ["Hotels", "Popular locations, connected rooms and family room types become less forgiving. Cancellation terms matter as much as the nightly rate.", "Choice and flexibility are often better, but weekends, conventions and local events can still tighten one city."],
        ["Headline attractions", "A dated or timed reservation may decide the day. Each venue has its own window, ID rules and holiday notices.", "Required reservations do not disappear; they are simply less likely to collide with a nationwide holiday peak."],
        ["On-the-ground movement", "Queues and traffic around transport hubs and famous sights can consume more of the day.", "National holiday pressure is lower, though normal weekend, school-group and event crowds remain possible."],
        ["Itinerary changes", "A chain of one-night stays, same-day transfers and fixed entries is fragile.", "Rebooking a train, room or sightseeing day is generally easier, so a multi-city route has more resilience."],
      ],
    },
    {
      id: "not-all-full",
      type: "callout",
      tone: "warning",
      title: "Avoid the blanket claims",
      body: "This guide does not assume that every train, flight, hotel or attraction will sell out, or that every price will rise by the same amount. Availability is route-, property-, venue- and date-specific. The reliable conclusion is that Golden Week gives you fewer easy substitutes when the first choice is gone.",
    },
    {
      id: "booking-order",
      type: "heading",
      level: 2,
      text: "Book the high-pressure pieces in the right order",
    },
    {
      id: "rail-tickets",
      type: "heading",
      level: 3,
      text: "Train tickets: prepare before the 15-day window opens",
    },
    {
      id: "rail-rule",
      type: "paragraph",
      text: "At the time of writing, China Railway's advance-sale window is 15 days including the travel date. Tickets do not all appear at midnight: the on-sale time is tied to the departure station and can be adjusted. Foreign-passport users can buy through 12306, but identity verification and passenger details should be completed before the sales window opens. Travel with the same original document used for booking.",
    },
    {
      id: "rail-sale-dates",
      type: "table",
      caption: "Calculated 2026 rail sale dates under the current 15-day rule; confirm the station-specific release time in 12306",
      columns: ["Travel date", "Enters the current sales window", "What to do"],
      rows: [
        ["Thursday, October 1", "Thursday, September 17", "Have passenger verification, preferred train and alternatives ready before the station's release time."],
        ["Wednesday, October 7", "Wednesday, September 23", "Treat the return-side journey as a separate booking deadline."],
        ["Thursday, October 8", "Thursday, September 24", "Do not assume the first post-holiday day will have unlimited choice."],
      ],
    },
    {
      id: "rail-fallback",
      type: "list",
      items: [
        "Prepare two or three acceptable departures, not one perfect train.",
        "Check nearby departure stations only when the transfer to them is genuinely workable.",
        "Use the official waitlist when appropriate, but do not treat a waitlist request as a confirmed ticket.",
        "Keep a refundable extra hotel night until the critical intercity leg is secure.",
        "Do not build a non-refundable attraction booking immediately after an uncertain rail connection.",
      ],
    },
    {
      id: "air-hotels",
      type: "heading",
      level: 3,
      text: "Flights and hotels: protect flexibility, not a predicted price",
    },
    {
      id: "air-hotels-text",
      type: "paragraph",
      text: "Domestic airfares and hotel inventory do not follow one nationwide booking window. They change by route, property, room type and cancellation condition. It is responsible to expect tighter choice on popular holiday dates; it is not responsible to publish a universal percentage increase or promise that October 8 will be cheaper.",
    },
    {
      id: "hotel-flight-checks",
      type: "list",
      items: [
        "Book a well-located, cancellable holiday base before committing to a chain of domestic tickets.",
        "Compare the fare rules and baggage allowance, not only the flight price.",
        "Avoid airport arrival, intercity transfer and a fixed-entry attraction on the same day.",
        "For families, confirm the exact room configuration; an available room is not automatically a workable room.",
        "Recheck local events and weekends before assuming later October will have normal rates."],
    },
    {
      id: "attraction-rules",
      type: "heading",
      level: 3,
      text: "Attractions: there is no national reservation rule",
    },
    {
      id: "attraction-intro",
      type: "paragraph",
      text: "Reservation systems differ not only by city, but also by venue, exhibition and date. Use the attraction's own official channel and read the current holiday notice. A rule from one museum, one Great Wall section or one previous year is not a rule for every sight in China.",
    },
    {
      id: "attraction-examples",
      type: "table",
      caption: "Examples of current official attraction rules, checked August 10, 2026",
      columns: ["Attraction", "Current official rule", "Planning consequence"],
      rows: [
        ["Palace Museum, Beijing", "No same-day tickets. Tickets normally open at 20:00 seven days before the visit; passport booking is supported.", "Under the standing rule, an October 1 visit would normally open on September 24 at 20:00. That is a calculation, not a special 2026 holiday notice."],
        ["Badaling Great Wall, Beijing", "The official site lists real-name advance booking and on-site ticket sales.", "Do not copy the Palace Museum's no-same-day rule to Badaling—or Badaling's rule to another Great Wall section."],
        ["Emperor Qinshihuang's Mausoleum Site Museum, Xi'an", "All visitors, including foreign visitors and free-entry visitors, are directed to make a real-name reservation through official channels.", "Use the passport details that will be carried on the day, and check the latest holiday opening notice."],
        ["Shanghai Museum", "The East Building currently trials reservation-free general admission, while specified spaces still require booking. The People's Square Building requires a ticket for all visitors during the July 9, 2026–November 14, 2027 exhibition.", "Even one institution can have more than one rule. Check the exact building and exhibition rather than relying on a generic museum tip."],
      ],
    },
    {
      id: "attraction-recheck",
      type: "callout",
      tone: "decision",
      title: "The 2026 holiday notices may still change the detail",
      body: "As of August 10, several venues had not yet published their specific National Day operating notice. Recheck official opening hours, entry gates, release times and temporary limits when the relevant reservation window approaches.",
    },
    {
      id: "who-can-go",
      type: "heading",
      level: 2,
      text: "Who can still travel well during Golden Week?",
    },
    {
      id: "traveller-fit",
      type: "comparison",
      columns: [
        {
          heading: "Golden Week can work",
          items: [
            "A repeat visitor who does not need every famous sight.",
            "A traveller visiting friends or family and staying in one place.",
            "A couple or small group with a confirmed hotel, transport plan and a flexible daily list.",
            "Someone who values the public-holiday atmosphere and accepts that it changes the pace."],
        },
        {
          heading: "Golden Week is a poor fit",
          items: [
            "A first-time checklist route with Beijing, Xi'an and Shanghai compressed into a few nights.",
            "A last-minute traveller who wants spontaneous high-speed rail and headline attractions.",
            "A group that needs low walking, short queues or easy same-day changes.",
            "A budget built around one exact train, one exact room type and no fallback."],
        },
      ],
    },
    {
      id: "who-can-go-detail",
      type: "paragraph",
      text: "The key distinction is not brave versus cautious. It is whether the route can absorb a missing ticket, a longer queue or a slower transfer without losing the next two bookings. A one-base holiday can absorb that. A tightly linked series of one-night stays often cannot.",
    },
    {
      id: "later-tradeoffs",
      type: "heading",
      level: 2,
      text: "What mid-to-late October buys—and what it may cost",
    },
    {
      id: "later-intro",
      type: "paragraph",
      text: "Moving the trip later is mostly an exchange of operational pressure for seasonal uncertainty. You normally gain flexibility, but you do not buy a weather guarantee, a national low-price period or a fixed autumn-colour calendar.",
    },
    {
      id: "later-table",
      type: "table",
      caption: "The trade-offs of moving a China trip later in October",
      columns: ["You are more likely to gain", "You may give up or still face"],
      rows: [
        ["More alternatives for intercity travel and hotel changes", "International fares or a city event can still make a later date expensive"],
        ["Less nationwide holiday pressure at famous sights", "Normal weekends, school groups and local festivals still exist"],
        ["A route that can support more than one city", "Shorter daylight and cooler mornings, especially in the north and mountains"],
        ["A better chance to adjust a day around rain", "No promise of clear skies, autumn colour or mountain visibility"],
        ["A calmer decision environment", "Less of the National Day public-holiday atmosphere"],
      ],
    },
    {
      id: "foliage-warning",
      type: "callout",
      tone: "warning",
      title: "Autumn colour is not a reservation",
      body: "Leaf timing varies by latitude, altitude and that year's weather. Later October may improve the chance of colour in some northern places while being too late, too early or simply green elsewhere. Agricultural landscapes such as rice terraces follow the year's harvest notices, not a permanent Golden Week calendar.",
    },
    {
      id: "weather-is-local",
      type: "heading",
      level: 2,
      text: "October weather is a route question, not a China-wide answer",
    },
    {
      id: "weather-intro",
      type: "paragraph",
      text: "The table below describes long-term climate patterns, not the exact weather in October 2026. A north–south trip can cross several seasonal stages in one week, and a mountain viewpoint can feel very different from the city below.",
    },
    {
      id: "weather-table",
      type: "table",
      caption: "How October planning differs across six common destinations",
      columns: ["Destination", "Long-term October pattern", "Planning implication"],
      rows: [
        ["Beijing", "Autumn is short and often clear, with a stronger turn toward cold conditions by the end of the month.", "Later October needs warmer morning and evening layers. It may bring autumn colour, but the peak cannot be promised."],
        ["Shanghai", "Early October often sits near the seasonal change into autumn. It is generally milder than Beijing, and humid or rainy spells remain possible.", "Later October may feel more autumnal, but do not translate that into guaranteed dry or blue-sky weather."],
        ["Xi'an", "Autumn cooling is noticeable, and the wider region can experience persistent autumn rain.", "Do not reuse a dry-Beijing packing assumption. Carry a light waterproof layer and keep an indoor alternative."],
        ["Chengdu", "The Sichuan Basin is humid, often cloudy and relatively low in sunshine; autumn rain varies substantially by year.", "Later means cooler, not necessarily brighter. Damp conditions can feel cooler than the temperature suggests."],
        ["Guilin", "October moves into the region's drier season, while northern Guangxi also becomes more exposed to cool-air changes.", "Mid-to-late month may be cooler and seasonally drier, but rain, warmth and river conditions still require a live check."],
        ["Zhangjiajie", "The mountain environment is humid and higher viewpoints are cooler than Zhangjiajie city; autumn is generally less rainy than summer.", "Allow for layers and a shorter mountain day later in the month. Mist, views and foliage are possibilities, not guarantees."],
      ],
    },
    {
      id: "forecast-boundary",
      type: "callout",
      tone: "neutral",
      title: "For October 2026, check twice",
      body: "Several months ahead, a seasonal outlook cannot tell you the weather on one sightseeing day. Homeground's planning rule is to check the official city and scenic-area forecast about 7–10 days before travel, then check mountain and long-transport days again 48–72 hours beforehand.",
    },
    {
      id: "fixed-flights",
      type: "heading",
      level: 2,
      text: "If your international flight lands during Golden Week, redesign the route",
    },
    {
      id: "fixed-flights-intro",
      type: "paragraph",
      text: "A fixed international fare is not a reason to cancel China. It is a reason to stop treating the first week as a normal multi-city sequence. Protect the arrival, keep one base, and make the holiday portion of the trip deliberately simple.",
    },
    {
      id: "fixed-route-steps",
      type: "list",
      ordered: true,
      items: [
        "Choose one arrival-city hotel and keep it through the official holiday rather than changing hotels every one or two nights.",
        "Secure a cancellable room before the rail and attraction windows open; location can save more time than a distant bargain.",
        "Give each day one reservation-dependent anchor, not three. Pair it with nearby public spaces, neighbourhoods or an indoor alternative.",
        "Book strict venues through their official channels at the correct release time. If the anchor is not secured, use the backup rather than forcing an unofficial ticket route.",
        "Place the first major intercity move after October 7. If the trip length allows, add a buffer day instead of assuming October 8 will be empty.",
        "Keep the final night before an international departure in the departure city; do not rely on a same-day long-distance connection.",
        "Recheck official attraction notices and weather shortly before travel, because neither August research nor a climate average is an October operating guarantee."],
    },
    {
      id: "route-patterns",
      type: "table",
      caption: "Low-friction route patterns when the international arrival falls on October 1–7",
      columns: ["Arrival gateway", "Holiday portion", "After the holiday"],
      rows: [
        ["Beijing", "Use Beijing as the fixed base. Hold the Palace Museum only if the official reservation is secured; plan other days in geographic clusters.", "Continue to Xi'an and then Shanghai, rather than inserting an overnight city change inside the holiday."],
        ["Shanghai", "Stay in Shanghai, where the plan can mix booked exhibitions with neighbourhoods and public waterfront areas.", "Begin the long intercity sequence after the holiday, with rail or air chosen from live availability."],
        ["Chengdu", "Keep a Chengdu base and reserve only the time-sensitive visits that matter to you.", "Connect onward after the holiday instead of using Chengdu as a one-night transfer stop."],
      ],
    },
    {
      id: "fixed-route-note",
      type: "paragraph",
      text: "These are route shapes, not promises that one city will be quiet. Their advantage is structural: one hotel and fewer long transfers create more ways to recover when a timed ticket or preferred departure is unavailable.",
    },
    {
      id: "decision-rule",
      type: "heading",
      level: 2,
      text: "The decision rule",
    },
    {
      id: "decision-rule-list",
      type: "list",
      items: [
        "If you can move the whole trip and want a first-time multi-city route, choose mid-to-late October.",
        "If your international flights are fixed but the domestic sequence is flexible, keep the trip and simplify October 1–7 to one base.",
        "If both dates and a fast checklist route are fixed, identify the rail and attraction failure points before paying for the remaining non-refundable pieces.",
        "If your main goal depends on one specific autumn landscape, check that destination's current-year notice rather than choosing by a national rule."],
    },
    {
      id: "decision-close",
      type: "paragraph",
      text: "Golden Week is not a universal cancellation notice, and later October is not a universal promise of empty sights and perfect weather. The better choice is the one whose transport, reservations, climate and fallback options fit your actual route.",
    },
    {
      id: "more-planning",
      type: "internal-links",
      title: "Continue planning the route",
      items: [
        {
          label: "Check whether your China itinerary is too rushed",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Test the city changes, full transfer days and fixed bookings before adding more stops.",
        },
        {
          label: "Compare trains, flights and complete transfer time",
          href: "/transport/",
          description: "Use door-to-door time rather than comparing only the train journey and flight duration.",
        },
        {
          label: "Choose a hotel for location and flexibility",
          href: "/guides/why-are-hotels-in-china-so-cheap/",
          description: "Look beyond the rate to the exact branch, room type, recent feedback and cancellation terms.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        { label: "2026 public holiday schedule", url: "https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm", publisher: "General Office of the State Council", reviewedAt: "2026-08-10" },
        { label: "Rail ticket 15-day advance-sale notice", url: "https://www.12306.cn/mormhweb/zxdt/202205/t20220531_37508.html", publisher: "China Railway 12306", reviewedAt: "2026-08-10" },
        { label: "Station-specific ticket release times", url: "https://www.12306.cn/index/view/infos/sale_time.html", publisher: "China Railway 12306", reviewedAt: "2026-08-10" },
        { label: "Official waitlist rules", url: "https://kyfw.12306.cn/otn/gonggao/alternate.html", publisher: "China Railway 12306", reviewedAt: "2026-08-10" },
        { label: "Rail passenger rules and identity documents", url: "https://kyfw.12306.cn/otn/gonggao/saleTicketMeans.html", publisher: "China Railway 12306", reviewedAt: "2026-08-10" },
        { label: "Palace Museum visitor and ticket rules", url: "https://www.dpm.org.cn/singles_detail/259831.html", publisher: "Palace Museum", reviewedAt: "2026-08-10" },
        { label: "Badaling Great Wall official ticket entry points", url: "https://www.badaling.cn/website/pc/index.html", publisher: "Badaling Great Wall Scenic Area", reviewedAt: "2026-08-10" },
        { label: "Emperor Qinshihuang's Mausoleum Site Museum visitor guide", url: "https://www.bmy.com.cn/guide/", publisher: "Emperor Qinshihuang's Mausoleum Site Museum", reviewedAt: "2026-08-10" },
        { label: "Shanghai Museum current visitor notice", url: "https://reservation.shanghaimuseum.net/", publisher: "Shanghai Museum", reviewedAt: "2026-08-10" },
        { label: "Beijing climate characteristics", url: "https://www.cma.gov.cn/kppd/kppdqxsj/kppdtqqh/202111/t20211103_4159387.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
        { label: "Shanghai's long-term autumn transition date", url: "https://www.shanghai.gov.cn/nw4411/20241007/54ec10bccbcd4775aeb1b3f53c5881fa.html", publisher: "Shanghai Municipal People's Government", reviewedAt: "2026-08-10" },
        { label: "Xi'an climate background", url: "https://www.weather.com.cn/cityintro/101110101.shtml", publisher: "China Weather Network", reviewedAt: "2026-08-10" },
        { label: "Chengdu geography and climate", url: "https://scdfz.sc.gov.cn/scdqs/sxdq/cds/content_12030", publisher: "Sichuan Provincial Local Records Office", reviewedAt: "2026-08-10" },
        { label: "Year-to-year variation in West China autumn rain", url: "https://www.cma.gov.cn/2011xzt/20160518/202503/t20250312_6911976.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
        { label: "Guangxi seasonal climate characteristics", url: "https://www.cma.gov.cn/2011xzt/2018zt/20181128/2018091804/201811/t20181128_484420.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
        { label: "Zhangjiajie tourism climate background", url: "https://www.cma.gov.cn/kppd/kppdqxwq/kppdfycq/201212/t20121202_193792.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
        { label: "Weather and climate prediction boundaries", url: "https://www.cma.gov.cn/2011xzt/2016zt/20160720/202111/t20211104_4169841.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
        { label: "Daylight shortens after the autumn equinox", url: "https://www.cma.gov.cn/ztbd/2025zt/24jq/qiufen/index.html", publisher: "China Meteorological Administration", reviewedAt: "2026-08-10" },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
