import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "If tomorrow is your confirmed full day in Jiuzhaigou, stay outside the scenic area near its visitor centre in Zhangzha Town—not at Huanglongjiuzhai Railway Station. Move the long station-to-entrance road handoff into the arrival day so the park morning starts at the gate side. A night around the rail gateway in Chuanzhusi Town earns its place when a late train, a missing safe onward transfer, a very early fixed departure, an already-confirmed Huanglong/Songpan sequence, or a verified chain that is still unsafe or impractical for the slowest or most constrained traveller makes continuing that night the weaker choice.",
    },
    {
      id: "direct-answer",
      type: "callout",
      title: "The answer in one minute",
      tone: "decision",
      body: "Use the entrance-side lodging belt as the sightseeing base. Use the rail gateway as a transition or recovery night, not as a Jiuzhaigou park base. Official material places Huanglongjiuzhai Station in Chuanzhusi Town, Songpan County, roughly 90 kilometres from the scenic area; actual journey time remains dynamic and must be confirmed in the dated transport plan. An extra hotel move is justified when it protects a fixed train, safely recovers a failed handoff or avoids a verified arrival chain that still does not work for the most constrained traveller. Otherwise, keep one entrance-side property and book the rooms the group needs.",
    },
    {
      id: "inside-rule",
      type: "callout",
      title: "“Near Jiuzhaigou” is not “inside Jiuzhaigou”",
      tone: "warning",
      body: "Current official management says visitors tour inside and stay outside, and the scenic-area regulation prohibits visitors from remaining or camping inside the valley. A property marketed as “Jiuzhaigou entrance”, “goukou” or “Zhangzha” should therefore be outside the controlled scenic area. Do not treat an old “stay inside” post, an English map label or a platform category as legal permission or geographic proof.",
    },
    {
      id: "scope-boundary",
      type: "paragraph",
      text: "This page begins after Jiuzhaigou is already in the itinerary. It chooses the sleep location around a confirmed park day and a dated rail/road plan. It does not choose the Chengdu transport mode, book the station coach, design the three-valley sightseeing route, decide whether Huanglong comes first, rank hotels, quote prices or promise tickets, rooms, foreign-guest acceptance or accessibility. Use the current transport or sightseeing guidance for those journeys, and confirm hotel-specific facts with the named property.",
    },
    {
      id: "map-heading",
      type: "heading",
      level: 2,
      text: "Keep four names on four separate pins",
    },
    {
      id: "location-table",
      type: "table",
      caption: "The booking label is useful only after the exact pin and next transfer are known",
      columns: ["Name you may see", "What it actually is", "Useful sleep role", "Do not assume"],
      rows: [
        ["Jiuzhaigou Scenic Area visitor centre / goukou (九寨沟景区游客中心 / 沟口)", "The controlled attraction and its public entrance/service node in Zhangzha Town", "The next fixed task for a full park day", "A hotel room exists inside the valley, or a nearby listing is walkable to the correct entry"],
        ["Zhangzha Town / Pengfeng", "The outside-the-scenic-area settlement and accommodation area serving the entrance", "Default base before and after a Jiuzhaigou park day", "Every Zhangzha property is equally close, flat, accessible or served by the same drop-off"],
        ["Huanglongjiuzhai Railway Station / Chuanzhusi Town (黄龙九寨站 / 川主寺镇)", "A rail gateway in Songpan County, separated from Jiuzhaigou by a substantial road handoff", "Late-arrival, early-departure or disruption transition night", "The word “Jiuzhaigou” in the station name means the platform is at the park gate"],
        ["Jiuzhaigou county seat / Nanping Town (九寨沟县城 / 南坪镇)", "The county administrative centre, not the scenic entrance and not Huanglongjiuzhai Station", "A disruption-only fallback when that is where a verified vehicle actually leaves you", "A county-wide hotel search proves a useful gate location"],
      ],
    },
    {
      id: "sequence-heading",
      type: "heading",
      level: 2,
      text: "Choose the bed from the next fixed task",
    },
    {
      id: "stay-matrix",
      type: "table",
      caption: "Place the road transfer on the side of the day that can absorb it",
      columns: ["Confirmed situation", "Entrance-side base", "Rail-gateway night", "Starting decision"],
      rows: [
        ["Ticket confirmed; tomorrow is the full Jiuzhaigou day", "Protects the park morning from the long station handoff", "Makes the transfer compete with entry and sightseeing", "Go to the verified entrance-side property on arrival day"],
        ["Train arrives late; no safe, dated onward transfer is confirmed", "Useful only if reception and legal transport still work end to end", "Stops the night chase and moves the road leg to daylight", "Stay at a verified Chuanzhusi/rail-gateway property, then accept a later park start or move the park date"],
        ["A very early fixed train follows the park day", "Avoids a hotel move but needs a conservative road buffer", "Protects the rail departure if the exact transfer and station-side room are verified", "Move once only when the saved departure risk exceeds the packing and check-in cost"],
        ["Huanglong or Songpan is already the next fixed stop", "May create backtracking", "Can fit a proven sight order or a protected departure", "Let the existing route order decide; this page only places the room after that order is fixed"],
        ["Park ticket or current opening is not confirmed", "A non-refundable gate booking can lock the wrong night", "A station booking does not solve park access", "Hold a changeable plan until the official reservation and operations are confirmed"],
      ],
    },
    {
      id: "arrival-heading",
      type: "heading",
      level: 2,
      text: "For the arrival night, verify the whole handoff",
    },
    {
      id: "arrival-checklist",
      type: "list",
      ordered: true,
      items: [
        "Bring a dated transport plan from the current rail/transfer guidance. For the accommodation decision, copy only the exact station name and final public drop-off; a generic ‘Jiuzhaigou station’ label is not enough. Save 黄龙九寨站 and the Chinese property address.",
        "Let the live operator confirm the timetable, boarding point, train matching, luggage rule and delay response. This page only asks what that confirmed final drop-off means for the night: continue to the entrance-side property or stop at the rail gateway.",
        "Ask the entrance-side property whether that exact drop-off reaches reception, whether an identifiable compliant pickup is required and the last arrival it can actually receive. A coach reaching ‘goukou’ is not automatically a hotel transfer.",
        "Use the margin calculated in the dated transport plan. If it cannot place the group at staffed reception without relying on a punctual train, an informal driver or an unconfirmed late check-in, choose the gateway transition night.",
        "For children, older travellers, wheelchairs or large bags, verify platform-to-exit, vehicle boarding, luggage loading, drop-off, street surface, hotel entrance, lift/steps and assigned room as separate links.",
        "For a high-risk late arrival, identify a gateway property whose exact location, staffed late reception, foreign-guest check-in, room availability, booking cutoff, bookable path and cancellation terms are confirmed. A contactable listing is not a backup reservation.",
      ],
    },
    {
      id: "departure-heading",
      type: "heading",
      level: 2,
      text: "For the final night, count risk—not kilometres",
    },
    {
      id: "last-night-table",
      type: "table",
      caption: "A station-side night is insurance only when it covers a real fixed departure",
      columns: ["Departure pattern", "Stay entrance-side", "Move toward the station", "Evidence needed before deciding"],
      rows: [
        ["Flexible midday or later train", "Usually preserves one property and one checkout sequence", "Often adds work without protecting a tight deadline", "Current road estimate, official transfer, railway check-in margin and a later fallback"],
        ["Early train with no conservative same-morning chain", "Risks the independent rail ticket", "Can remove the mountain-road leg from departure morning", "Exact property pin, station access, staffed reception, legal vehicle and the booked train's station"],
        ["International flight or irreplaceable onward ticket after rail", "A same-day mountain road plus rail plus flight stacks independent failures", "Station-side may still be too late in the risk chain", "Protect the larger connection using the separate last-night/transfer-risk guidance, possibly moving farther toward the airport earlier"],
        ["A second property booked only to claim a ‘closer’ last night", "One base avoids packing and another check-in", "The move has no value if the listing is not actually close or the departure vehicle starts elsewhere", "Door-to-platform route, luggage, walking surface and operation on the exact date"],
      ],
    },
    {
      id: "move-heading",
      type: "heading",
      level: 2,
      text: "Make one hotel move prove its value",
    },
    {
      id: "one-move-rule",
      type: "callout",
      title: "The one-move test",
      tone: "neutral",
      body: "Write the fixed task that the move protects, the failure it removes and the new handoffs it creates. A gate-to-station move passes when it removes a road leg from an inflexible early departure or safely recovers a missed evening transfer. It fails when it merely changes a map pin, repeats check-in, exposes luggage and still needs an unverified vehicle. For a normal full park day followed by a flexible departure, keep one entrance-side base.",
    },
    {
      id: "travellers-heading",
      type: "heading",
      level: 2,
      text: "The area label matters less when the group has constraints",
    },
    {
      id: "needs-table",
      type: "table",
      caption: "Choose the property whose complete chain works for the slowest or least flexible traveller",
      columns: ["Traveller or constraint", "Default direction", "Condition that changes it", "Must verify"],
      rows: [
        ["Family with young children", "One entrance-side property before the full park day, with the rooms needed and a day bag", "A late arrival or verified chain that still does not work for the children makes a gateway rest safer", "Child restraint if required, food/late reception, luggage plan, room setup and next-day entrance transfer"],
        ["Older traveller or slower walking pace", "Protect the park morning but avoid a property that adds steep streets or stairs", "A verified station-side rest is safer than continuing after a very late train", "Every walking section, seating/rest option, pickup point, lift and the realistic park-day start"],
        ["Wheelchair or mobility device", "No area-wide default: choose only from the verified continuous route", "Any broken link can overturn the apparent location advantage", "Platform, lift operation, vehicle boarding and restraint, luggage/device handling, kerbs, hotel room and visitor-centre path"],
        ["Large or multiple bags", "Use one entrance-side property; leave bags in the continuing room, or confirm receipted front-desk storage after checkout", "A station-side final night may protect an early train if bags can move reliably", "Vehicle capacity, stairs, storage receipt, staffed pickup and door-to-platform route"],
        ["One traveller with a fixed next-day commitment", "Let that deadline control the last night", "A later replaceable train or flexible park date reduces the need to move", "Change terms and backup transport, not an optimistic minimum travel time"],
      ],
    },
    {
      id: "property-heading",
      type: "heading",
      level: 2,
      text: "Verify the property, not the search category",
    },
    {
      id: "property-checklist",
      type: "list",
      ordered: true,
      items: [
        "Get the full Chinese property name, street address, coordinates and a current exterior/location image. Confirm whether it is in Zhangzha/Pengfeng, Jiuzhaigou county seat, Chuanzhusi or another place.",
        "Ask for a door-to-visitor-centre or door-to-station route, not ‘five minutes from Jiuzhaigou’. Request the actual distance, surface, slope, crossings, stairs and the entrance or station access point used.",
        "Confirm the staffed reception window and what happens after a delayed train or coach. A phone number is useful only if someone will answer on the travel date.",
        "Confirm foreign-guest check-in for the named travellers and date in writing. Treat that reply as property evidence only; use the separate national guide if the front desk refuses after booking.",
        "Confirm the booked room configuration and every decisive feature: lift, threshold, bathroom, heating, beds and space for luggage or a mobility device. An ‘accessible’ or ‘family’ platform label is not a measurement.",
        "Confirm who operates any pickup, the legal boarding point, vehicle type, luggage/device handling, cost treatment and failure plan. A hotel's shuttle claim is not proof of every-day operation.",
        "Save cancellation, no-show, late-arrival and room-change terms before paying. Prefer adjustability while tickets, weather or the final transport chain remain unresolved.",
        "Keep the booking platform's help route and one alternative property whose exact pin and reception have also been checked. Do not rely on a generic list shown after midnight.",
      ],
    },
    {
      id: "scenario-heading",
      type: "heading",
      level: 2,
      text: "Four decisions in practice",
    },
    {
      id: "scenario-full-heading",
      type: "heading",
      level: 3,
      text: "Scenario 1: confirmed ticket and one full park day",
    },
    {
      id: "scenario-full",
      type: "list",
      ordered: true,
      items: [
        "Book a changeable entrance-side room with a verified route to the current visitor-centre entry.",
        "Choose a train and official onward transfer that complete the station-to-property chain on the arrival day.",
        "Recheck the official entry and operating notice; start from the same room with only the day's luggage.",
        "Return to the same property. Do not add a station night unless the next departure is genuinely inflexible and cannot be protected from the entrance side.",
      ],
    },
    {
      id: "scenario-late-heading",
      type: "heading",
      level: 3,
      text: "Scenario 2: the train is late and the last confirmed transfer is gone",
    },
    {
      id: "scenario-late",
      type: "list",
      ordered: true,
      items: [
        "Use the transport guide and live official channel to determine whether any safe, identifiable onward option remains; do not rebuild that route from an unsolicited promise.",
        "If the dated transport recovery no longer provides a workable evening handoff, stop at the rail gateway in a property verified and booked for that night.",
        "Notify the entrance-side property and booking platform in writing; save delay evidence and ask about change or no-show handling without assuming a refund.",
        "Move the road handoff to daylight and accept a later park start or a changed park date. Do not defend the original ticket by taking an unverified night ride.",
      ],
    },
    {
      id: "scenario-early-heading",
      type: "heading",
      level: 3,
      text: "Scenario 3: an early rail departure after Jiuzhaigou",
    },
    {
      id: "scenario-early",
      type: "list",
      ordered: true,
      items: [
        "Work backward from the booked train's check-in/boarding requirement and add a conservative road-disruption margin.",
        "If no verified entrance-to-station chain can meet that margin, use the afternoon or evening before to move to a verified rail-gateway room.",
        "Confirm that the room is near the exact station in practice, reception is staffed and the door-to-platform route works with the bags and travellers.",
        "If the train connects to an irreplaceable flight, examine the entire independent-ticket risk; a station night may not be enough protection.",
      ],
    },
    {
      id: "scenario-family-heading",
      type: "heading",
      level: 3,
      text: "Scenario 4: family, older traveller and large luggage",
    },
    {
      id: "scenario-family",
      type: "list",
      ordered: true,
      items: [
        "Choose one entrance-side property, with the rooms the group needs, if the arrival handoff can be completed safely.",
        "Verify the slowest traveller's platform-to-room and room-to-visitor-centre chain; a station lift proves only one link.",
        "Leave luggage in a continuing room, or obtain written confirmation and a receipt for front-desk storage after checkout; carry only a day bag through the park day.",
        "Keep the gateway room as a disruption fallback, not a scheduled second check-in, unless it protects a fixed early departure.",
      ],
    },
    {
      id: "failure-heading",
      type: "heading",
      level: 2,
      text: "Recover when the plan stops matching reality",
    },
    {
      id: "failure-table",
      type: "table",
      caption: "Change the bed when the fixed task or safe transfer changes",
      columns: ["Failure", "Immediate action", "Accommodation response", "Record to keep"],
      rows: [
        ["Train delay or missed station transfer", "Use the separate dated transport-recovery guidance and live operator; do not follow an unknown driver", "If that recovery shows no workable evening handoff, use the gateway property already verified for location, reception, foreign-guest check-in and booking", "Rail delay, transfer order/status, property messages and time"],
        ["Park ticket sold out or entry/open sections change", "Use the current official reservation, standby, change or refund channel; do not arrive without a valid reservation", "Keep, shift or cancel the entrance-side room under its actual terms", "Official notice, booking status and hotel/platform reply"],
        ["Road, weather or geological-hazard interruption", "Stop forcing the connection; check scenic-area, road and traffic authorities and notify every independent booking", "Stay at the safe verified hub you have reached, then rebuild in daylight", "Time-stamped notice, vehicle message, rail status, payments and receipts"],
        ["Listing pin, drop-off or pickup is wrong", "Pause at an official staffed place and contact the property and platform", "Request a workable pickup, relocation or platform-supported alternative", "Listing, map pin, written promise, actual location and response"],
        ["Front desk cannot check in the foreign guest", "Use the separate refusal-recovery chain; keep communication factual and do not post passport data publicly", "Ask platform/property for a verified alternative rather than treating the platform label as law", "Reservation, prior acceptance, front-desk outcome and escalation reference"],
        ["A lift, vehicle, room or walking link is unusable", "Do not improvise around an unsafe access gap; seek staffed help and a suitable verified link", "Change vehicle, assigned room or property based on the exact requirement", "Dated photos/measurements without private documents, written confirmations and change outcome"],
      ],
    },
    {
      id: "records-heading",
      type: "heading",
      level: 2,
      text: "Keep a small evidence pack",
    },
    {
      id: "records-list",
      type: "list",
      items: [
        "The rail booking showing the exact station and train",
        "The current official transfer booking or query result and pickup/drop-off wording",
        "The property's Chinese name, pin, address, reception and pickup reply",
        "Park reservation status and the current official operating notice",
        "Cancellation, late-arrival and no-show terms captured before the deadline",
        "Delay or closure notices, call/message times, payments and receipts when recovery is needed",
        "Only redacted copies for platform disputes; never publish passport numbers, QR codes, booking codes, room numbers, keycards or payment data",
      ],
    },
    {
      id: "dynamic-heading",
      type: "heading",
      level: 2,
      text: "Dynamic facts checked 1 September 2026",
    },
    {
      id: "dynamic-callout",
      type: "callout",
      title: "Recheck before paying and again before travel",
      tone: "neutral",
      body: "Official 2026 pages changed both the scenic-area entry start and the wording of station coaches—from a stronger train-matching statement in July to dynamic dispatch in late August. Current reservation capacity, open sections, 12306 trains, official transfer, pickup/drop-off, G544 road status, transfer duration and property operation therefore belong to the travel date. The official roughly 90-kilometre geographic relationship explains the decision; this page does not publish a timetable or arrival guarantee.",
    },
    {
      id: "final-heading",
      type: "heading",
      level: 2,
      text: "Final booking check",
    },
    {
      id: "final-checklist",
      type: "list",
      items: [
        "A confirmed Jiuzhaigou park date and current official entry status",
        "Four distinct pins: scenic entrance, Zhangzha property, Huanglongjiuzhai Station and any county-seat fallback",
        "The next fixed task that the chosen bed protects",
        "A dated official station transfer with exact pickup and drop-off—or an intentional gateway night",
        "Property reception, foreign-guest check-in, room, luggage and door route confirmed in writing",
        "The full accessibility chain verified where required, without inferring from a station or platform label",
        "A one-move reason stronger than packing, second reception and transfer risk",
        "Change terms, one verified fallback plan and the small evidence pack saved",
      ],
    },
    {
      id: "consultation-boundary",
      type: "callout",
      title: "If you want a human base check",
      tone: "neutral",
      body: "In the initial planner, send only minimum non-sensitive context: travel dates, the public bases being compared, traveller and room counts, the confirmed park day, arrival/departure direction and an optional broad budget. You may say that you want to discuss family or accessibility arrangements later, but do not submit children's exact ages; mobility, medical or accessibility details; passport or identity documents; booking or payment records; or identifiable information intended for a hotel, driver, DMC or other supplier. Those details require a separate human follow-up, an appropriate purpose and consent; nothing is shared with a supplier without separate consent. This is not a live inventory or transport service and does not guarantee price, availability, foreign-guest acceptance, room type, accessibility suitability, park entry, train/coach operation, road conditions, luggage handling or connection success.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue the decision",
      items: [
        {
          label: "Choose the Chengdu–Jiuzhaigou transport chain",
          href: "/guides/chengdu-jiuzhaigou-transport-route/",
          description: "Verify the exact rail station, named onward transfer, drop-off and return without treating the station as the valley gate.",
        },
        {
          label: "Decide whether a multi-base route is worth it",
          href: "/guides/china-hub-and-spoke-or-multi-base-route/",
          description: "Test whether any hotel move removes real transport risk or merely adds another handoff.",
        },
        {
          label: "Prepare for foreign-guest check-in or refusal",
          href: "/guides/foreigners-china-hotel/",
          description: "Separate the legal registration rule from a platform label and recover if the front desk cannot check you in.",
        },
        {
          label: "Verify an actually usable accessible hotel room",
          href: "/guides/china-accessible-hotel-room-verification/",
          description: "Check the street-to-room chain with measurements and a backup room or property.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Government, scenic-area and image sources",
      items: [
        { label: "Huanglongjiuzhai Station upgrade and dynamic scenic coaches", url: "https://abazhou.gov.cn/abazhou/c101955/202608/61f879f6a24746718025c78e2c42777e.shtml", publisher: "Aba Tibetan and Qiang Autonomous Prefecture Government", reviewedAt: "2026-09-01" },
        { label: "Huanglongjiuzhai Station location and planning relationship", url: "https://abazhou.gov.cn/abazhou/c101955/202407/e13092b093f24b009f989bd418ffa142.shtml", publisher: "Aba Tibetan and Qiang Autonomous Prefecture Government", reviewedAt: "2026-09-01" },
        { label: "Songpan railway stations and last-mile role", url: "https://www.songpan.gov.cn/spxrmzf/c100050/202607/90c2369b5699446f8ff99065a3645082.shtml", publisher: "Songpan County People's Government", reviewedAt: "2026-09-01" },
        { label: "Jiuzhaigou 2026 summer travel and rail-transfer notice", url: "https://www.jiuzhai.com/news/notice/11241-2026-07-08-03-30-49", publisher: "Jiuzhaigou Valley Scenic and Historic Interest Area", reviewedAt: "2026-09-01" },
        { label: "Jiuzhaigou capacity and standby notice", url: "https://www.jiuzhai.com/news/notice/11325-2026-08-11-16-26-09", publisher: "Jiuzhaigou Valley Scenic and Historic Interest Area", reviewedAt: "2026-09-01" },
        { label: "Jiuzhaigou 2026 outside-stay visitor arrangements", url: "https://www.jzg.gov.cn/jzgrmzf/jgsf/202603/ccfa4789012d490596552a1680ffaaec.shtml", publisher: "Jiuzhaigou County People's Government", reviewedAt: "2026-09-01" },
        { label: "Jiuzhaigou Scenic Area regulation", url: "https://abazhou.gov.cn/abazhou/c109784/202308/6b5847dfac864e6ab7220430510232ad.shtml", publisher: "Aba Tibetan and Qiang Autonomous Prefecture Government", reviewedAt: "2026-09-01" },
        { label: "Official Jiuzhaigou location overview", url: "https://www.jiuzhai.com/about/jiuzhai-valley", publisher: "Jiuzhaigou Valley Scenic and Historic Interest Area", reviewedAt: "2026-09-01" },
        { label: "2021 administrative-division notice locating the county government in Nanping Town", url: "https://www.jzg.gov.cn/jzgrmzf/c100053/202112/a162bf6d283a483e9ca612cb4de9d1d1.shtml", publisher: "Jiuzhaigou County People's Government", reviewedAt: "2026-09-01" },
        { label: "Full reopening after the July 2026 disruption", url: "https://www.jiuzhai.com/news/notice/11290-2026-07-29-02-04-43", publisher: "Jiuzhaigou Valley Scenic and Historic Interest Area", reviewedAt: "2026-09-01" },
        { label: "G544 snow and ice road controls", url: "https://abazhou.gov.cn/abazhou/c109692/202603/9bd4dacbc0464f199500321fb1ff94dd.shtml", publisher: "Aba Tibetan and Qiang Autonomous Prefecture road authority", reviewedAt: "2026-09-01" },
        { label: "Inbound visitor and passport booking service report", url: "https://www.sc.gov.cn/10462/10464/10797/2025/6/16/d4ea87e678af4e888b7ff8158e13d462.shtml", publisher: "Sichuan Provincial People's Government", reviewedAt: "2026-09-01" },
        { label: "Station accessibility-facility upgrade report", url: "https://www.songpan.gov.cn/spxrmzf/c100050/202608/119293cc2ee84196a1a30bebcdcb90d4.shtml", publisher: "Songpan County People's Government", reviewedAt: "2026-09-01" },
        { label: "Hero: Huanglongjiuzhai Railway Station by Underbar dk, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Huanglongjiuzhai_Railway_Station,_December_2024,_10.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-01" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
