import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  "schemaVersion": "1.0.0",
  "blocks": [
    {"id":"lead","type":"lead","text":"A Quanzhou string puppet does not move because one string is pulled at a time. A performer coordinates a control, many lines, gravity, the puppet’s articulated body, voice, music and stage partners so that intention appears below. For a useful first visit, verify a named programme on the heritage centre’s current channel, then shift your attention between hand, string, puppet and scene instead of trying to count lines."},
    {"id":"answer","type":"callout","title":"Choose a named work, then watch four relationships","body":"Prefer the Quanzhou Marionette Heritage and Protection Center or another identifiable producer that gives a current date, venue, work or excerpt and booking conditions. Reconfirm on the official show list or with the venue; do not rely on a copied calendar. During the performance, watch control-to-string, string-to-body, body-to-character and character-to-music. The number of strings alone does not authenticate or rank a puppet.","tone":"decision"},
    {"id":"identity-heading","type":"heading","level":2,"text":"Make sure the programme is Quanzhou string puppetry"},
    {"id":"identity","type":"paragraph","text":"The national intangible-cultural-heritage project is 木偶戏（泉州提线木偶戏）, literally puppetry—Quanzhou suspended-string puppetry. In English, “Quanzhou string puppetry” and “Quanzhou marionette theatre” are both useful. It is not interchangeable with Fujian glove/hand puppetry, shadow theatre, a souvenir marionette demonstration or every puppet show staged in Quanzhou. Look for the Chinese name, producing institution and named work. UNESCO’s recognized safeguarding project concerns training future generations of Fujian puppetry practitioners; it is recognition of a safeguarding strategy, not a quality seal attached to every ticket."},
    {"id":"choose-heading","type":"heading","level":2,"text":"Select the programme without building a stale timetable"},
    {"id":"choose","type":"table","caption":"Evidence to check for your performance date","columns":["Question","Best current evidence","Why it matters","Fallback"],"rows":[["Who performs?","Heritage centre or named troupe/producer","Separates the form from a generic puppet attraction","Keep the centre visit but do not promise a show"],["What is performed?","Named work, excerpt or clearly labelled demonstration","Lets you read a synopsis and identify format","Ask for the Chinese title at the desk"],["When and where?","Dated first-party show entry plus exact theatre/entrance","Archives and reposts can remain visible after an event","Confirm by official contact on the day"],["How is admission handled?","Direct booking, collection, capacity and late-entry terms","Building access may not equal a seat","Arrive only with a verified admission plan"],["What support exists?","Synopsis, programme, subtitles or introduction","A first audience needs orientation, not a full translation","Save a short Chinese synopsis for translation"],["What may change?","Cast, work, duration, photography and cancellation notice","Live programmes are dynamic","Keep another Quanzhou heritage stop nearby"]]},
    {"id":"arrival-heading","type":"heading","level":2,"text":"Before the curtain: establish a small evidence file"},
    {"id":"arrival","type":"list","ordered":true,"items":["Save the current official listing with its publication or performance date.","Record the Chinese work title, producer, venue and announced format.","Read a short synopsis: identify the central characters and immediate conflict, not every plot detail.","Check whether the event is a staged work, selected excerpts, public demonstration or workshop.","Ask about photography, late entry, age/access needs and whether the announced programme has changed.","Sit where the puppet’s full body and stage partners are visible; a close side seat may hide the vertical control relationship."]},
    {"id":"hands-heading","type":"heading","level":2,"text":"First attention shift: from hands to intention"},
    {"id":"hands","type":"paragraph","text":"When the manipulator or upper control is visible, watch for small changes rather than large arm sweeps. One hand may stabilize while another redirects or releases tension; the visible action can be much smaller than the puppet’s response below. If performers are concealed by the staging, do not treat that as missing authenticity. Use the puppet’s balance, timing and repeatable gestures to infer coordination, but do not claim a precise technique unless a practitioner or programme explains it."},
    {"id":"strings-heading","type":"heading","level":2,"text":"Second attention shift: strings are a system, not a score"},
    {"id":"strings","type":"paragraph","text":"The China ICH overview describes Quanzhou puppets using variable numbers—from more than ten to more than thirty—while another institutional programme has published a different range for its own presentation. This is exactly why a fixed number is misleading. A puppet’s lines may distribute control across head, hands, torso, feet, costume or props according to role and production. Lighting and distance may also make lines disappear. Count only if the troupe invites that exercise; otherwise watch how tension changes travel through the body."},
    {"id":"body-heading","type":"heading","level":2,"text":"Third attention shift: find weight inside the puppet body"},
    {"id":"body","type":"paragraph","text":"Look at beginnings and endings of motion. Does a foot appear to receive weight before the body advances? Does the head arrive after a turn rather than swivel independently? Do sleeves, costume and a carried object settle at different speeds? These details make carved, jointed and dressed material read as a character. They also show why a still photograph cannot prove performance quality. Do not identify wood, age, maker, role or restoration history from appearance; use the troupe’s object record when such facts matter."},
    {"id":"sound-heading","type":"heading","level":2,"text":"Fourth attention shift: reconnect voice, music and scene"},
    {"id":"sound","type":"paragraph","text":"Quanzhou string puppetry carries repertoire and musical inheritance as well as manipulation. Follow who voices a character, when singing or speech begins, and how percussion or melodic cues change the puppet’s pace. A convincing pause may depend on sound stopping at the same instant as the body. Watch exchanges between puppets: gaze direction, spacing and delayed reactions create relationships. Even if you do not understand the language, the synopsis plus entrances, repeated sound cues and responses will reveal a dramatic arc."},
    {"id":"scenarios-heading","type":"heading","level":2,"text":"Two first-audience routes"},
    {"id":"scenarios","type":"comparison","title":"Choose depth or access","columns":[{"heading":"You have one short Quanzhou evening","items":["Choose a current, named centre programme with a bounded duration","Read one-paragraph plot context before arrival","Focus on one puppet’s walk, one interaction and one sound cue"]},{"heading":"You want to understand the craft","items":["Pair a staged work with an officially announced public demonstration or interpretation session","Ask what is production-specific rather than demanding secrets","Record the named practitioner, puppet/work and date"]},{"heading":"Do not anchor the day","items":["Only a ticket reseller or old announcement lists the show","The exact venue or admission method is unclear","Your connection cannot absorb a cast, time or programme change"]}]},
    {"id":"recovery-heading","type":"heading","level":2,"text":"When the performance differs from expectation"},
    {"id":"recovery","type":"table","caption":"Failure recovery without inventing a claim","columns":["Problem","Useful response","Do not conclude"],"rows":[["The show list changed","Ask the centre what work and format replaced it; apply refund terms if relevant","The replacement is inferior or a deception"],["There are no English subtitles","Translate the short synopsis before the start; follow character entrances and sound cues","The visual action has one obvious universal meaning"],["The manipulator is not visible","Watch balance, tension, timing and interaction; ask after the show if interpretation is offered","Hidden performers mean a lesser form"],["You cannot count the strings","Stop counting and follow one body relationship","More visible lines automatically mean older or better work"],["A demonstration is shorter than expected","Name exactly which movement or control relationship was shown","A short demonstration is complete training in the tradition"],["Photography is prohibited","Use an authorized programme or licensed institutional image later","A ticket includes reproduction rights"]]},
    {"id":"craft-boundary","type":"callout","title":"Observation is not apprenticeship","body":"A public explanation can identify a control relationship, repertoire feature or making stage, but it does not transfer the embodied knowledge developed through training. Do not ask a practitioner to disclose restricted methods, handle a puppet, cross the stage boundary or let a child pull lines unless the session explicitly invites it. A visitor workshop should be labelled by its actual scope.","tone":"warning"},
    {"id":"after-heading","type":"heading","level":2,"text":"After the show: leave with traceable evidence"},
    {"id":"after","type":"list","items":["Write down the exact work or excerpt and the producing institution.","Name one controlled movement and the sound or partner action connected to it.","Separate what the programme stated from what you personally observed.","If photographing an approved display, include its label rather than guessing the puppet’s identity.","Use the heritage centre’s repertoire or contact channel for follow-up, not an unattributed clip.","Ask permission before publishing performers, programme scans or workshop participants."]},
    {"id":"judgment-heading","type":"heading","level":2,"text":"What the evidence supports"},
    {"id":"judgment","type":"paragraph","text":"The official heritage record supports the identity, institutional protection and documented craft characteristics of Quanzhou string puppetry. UNESCO supports the significance of a particular training strategy. A first-party show entry supports an announced programme on a stated date. None proves that a future schedule is fixed, one puppet represents the whole repertoire, or a high line count makes a performance more authentic. Homeground’s editorial test is whether you can connect one visible manipulation choice to bodily and dramatic effect while naming the evidence you used."},
    {"id":"help","type":"callout","title":"Homeground","body":"Programmes, venues and admission conditions were last reviewed on 13 August 2026 and must be reconfirmed on the official show list or with the centre. Send your Quanzhou date, language and accessibility needs if you want a local human to check a current performance and nearby fallback without turning this guide into a stale calendar.","tone":"decision"},
    {"id":"links","type":"internal-links","title":"Continue reading craft and Quanzhou","items":[{"label":"Read Qiaopi letters and remittance routes","href":"/guides/qiaopi-letters-remittances-and-migration/","description":"Use another evidence-led route into Quanzhou’s overseas connections."},{"label":"Choose a printing-craft visit","href":"/guides/woodblock-and-movable-type-printing-decisions/","description":"Compare a workshop, demonstration and museum without calling a short activity the complete craft."},{"label":"Read dougong and timber frames","href":"/guides/dougong-and-chinese-timber-frame-reading/","description":"Practise separating visible structure from claims that require records."}]},
    {"id":"sources","type":"sources","title":"Official, institutional and independent sources","items":[{"label":"Fujian puppetry practitioner training strategy","url":"https://ich.unesco.org/en/BSP/strategy-for-training-coming-generations-of-fujian-puppetry-practitioners-00624","publisher":"UNESCO Intangible Cultural Heritage","reviewedAt":"2026-08-13"},{"label":"Puppetry (Quanzhou string puppetry)","url":"https://www.ihchina.cn/project_details/13429.html","publisher":"China Intangible Cultural Heritage","reviewedAt":"2026-08-13"},{"label":"Quanzhou Marionette Heritage and Protection Center","url":"https://www.cnqzmt.com/","publisher":"Quanzhou Marionette Heritage and Protection Center","reviewedAt":"2026-08-13"},{"label":"Current official performance list","url":"https://www.cnqzmt.com/shows_list.html","publisher":"Quanzhou Marionette Heritage and Protection Center","reviewedAt":"2026-08-13"},{"label":"2026 Fujian performance recognition","url":"https://wlt.fujian.gov.cn/wldt/btdt/202601/t20260120_7082303.htm","publisher":"Fujian Department of Culture and Tourism","reviewedAt":"2026-08-13"},{"label":"Quanzhou Marionette Troupe reference","url":"https://wepa.unima.org/en/quanzhou-marionette-troupe/","publisher":"World Encyclopedia of Puppetry Arts / UNIMA","reviewedAt":"2026-08-13"}]}
  ]
} as const satisfies StructuredPageBody;

export default body;
