import type { StructuredPageBody } from "../../../lib/content-system/page-body";
import type { HomegroundLocale } from "../../../lib/homegroundI18n";

const copies = {
  en: {
    lead: "Zhangjiajie is not one park with one gate. The destination name covers a city gateway, Wulingyuan and the National Forest Park, Tianmen Mountain beside the city, and the Grand Canyon in another direction. Most first trips work best with three complete sightseeing days; the real planning decision is which systems deserve those days and which hotel base protects the first departure.",
    answerTitle: "Start with complete days, not nights on a booking screen",
    answerBody: "Two complete days force a major omission. Three complete days usually support two National Forest Park days plus Tianmen Mountain, or a deliberate alternative. Four complete days add weather recovery, slower mobility or one separate attraction. Arrival and departure fragments do not count as mountain days.",
    fitHeading: "Who Zhangjiajie suits",
    fitColumns: ["Traveller", "Why it fits", "Design requirement"],
    fitRows: [
      ["First-time landscape traveller", "The sandstone pillar landscape is genuinely distinct", "Protect at least two park-side blocks rather than collecting disconnected highlights"],
      ["Family or older traveller", "Buses, cableways and lifts can replace much climbing", "Riding does not remove queues, standing, platform walks or weather exposure"],
      ["Photographer or slow traveller", "Mist, light and viewpoints reward time flexibility", "A fourth day is more useful than another fixed attraction promise"],
      ["Very short China itinerary", "Possible only when Zhangjiajie is a true priority", "Do not hide flight, train, hotel move and mountain transfer time inside sightseeing days"],
    ],
    daysHeading: "What two, three and four complete days mean",
    daysColumns: ["Complete days", "Realistic shape", "What must stay outside"],
    daysRows: [
      ["2", "One substantial National Forest Park day plus Tianmen Mountain, or two selective park days", "Grand Canyon, Fenghuang and a promise to cover every plateau"],
      ["3", "Two park days plus Tianmen Mountain; the strongest first-trip default", "A casual Grand Canyon add-on and unprotected onward departure"],
      ["4", "Weather recovery, slower pace or one separately chosen Grand Canyon / culture day", "Turning the extra day into a fourth crowded checklist"],
    ],
    baseHeading: "Choose the hotel base by the first job each morning",
    baseColumns: ["Base", "Best for", "Trade-off"],
    baseRows: [
      ["Wulingyuan", "Early National Forest Park starts and two consecutive park days", "Farther from DYG airport, Zhangjiajie West and Tianmen's city-side system"],
      ["Zhangjiajie city", "Tianmen Mountain, late arrival, early departure and gateway access", "Consumes a road transfer before a Wulingyuan park start"],
      ["Two-base split", "A route with enough nights to protect both park and city tasks", "Checkout, luggage and another handoff; do it only when the saved transfer is larger"],
    ],
    gatewayHeading: "Enter and leave through the exact gateway",
    gatewayIntro: "DYG airport and Zhangjiajie West Railway Station both sit on the city side, not at the Wulingyuan park entrance. Match every arrival to the actual hotel reception, time of day, luggage and legal transfer. A late arrival may justify a city night even when the next two days belong in Wulingyuan.",
    gatewayColumns: ["Gateway", "Planning role", "Common failure"],
    gatewayRows: [
      ["DYG Hehua Airport", "Flights that remove a long cross-country surface journey", "Reading Zhangjiajie as if the airport were beside the forest-park gate"],
      ["Zhangjiajie West", "High-speed rail and regional access on the city side", "Counting train arrival as arrival at a Wulingyuan hotel"],
      ["Road transfer", "The last mile between gateway, city and Wulingyuan", "Accepting an unlicensed pickup or a vague hotel name without a Chinese address"],
    ],
    systemsHeading: "Four names that must not collapse into one attraction",
    systemsColumns: ["System", "What it owns", "Do not confuse it with"],
    systemsRows: [
      ["Zhangjiajie National Forest Park / Wulingyuan core", "Multiple gates, lower valleys, upper plateaus, park shuttles, lifts and cableways", "Tianmen Mountain or the Grand Canyon"],
      ["Tianmen Mountain", "A city-side ticket and transport system normally consuming its own substantial block", "Tianzi Mountain inside the Wulingyuan landscape"],
      ["Zhangjiajie Grand Canyon", "The Glass Bridge and canyon system in a separate direction", "Glass skywalks on Tianmen Mountain"],
      ["Fenghuang", "A separate historic-town destination and onward-route decision", "An evening neighbourhood inside Zhangjiajie"],
    ],
    parkTitle: "The National Forest Park still needs a gate-and-transport decision",
    parkBody: "The Hub explains where the park sits in the trip. The dedicated ticket, entrance and in-park transport owner decides which gate to use first, what the booked product includes, how shuttles connect to lifts or cableways, and how to recover when the passport, time slot or entrance plan fails. Do not copy that volatile workflow into this broad page.",
    readingTitle: "Continue with the canonical owner for the next decision",
    links: [
      ["See what fits in 2, 3 or 4 days", "zhangjiajie-itinerary", "The exact day allocation and what to omit."],
      ["Choose Zhangjiajie city or Wulingyuan", "zhangjiajie-city-or-wulingyuan-hotel-base", "Compare the two hotel bases and when a split is worth the luggage move."],
      ["Choose National Forest Park tickets, entrances and transport", "zhangjiajie-national-forest-park-tickets-and-entrances", "Gate, passport, booking and in-park failure recovery."],
      ["Separate the Glass Bridge from glass skywalks", "zhangjiajie-glass-bridge-vs-skywalk", "Three different locations, ticket systems and physical experiences."],
      ["Plan Zhangjiajie with older travellers", "zhangjiajie-older-travellers", "Rides, walking load, queues and recovery choices."],
      ["Compare Zhangjiajie night shows", "best-zhangjiajie-night-show", "Choose by hotel base, finish time and what the day can still absorb."],
    ],
    stayReadingTitle: "Finish the lodging decision with the nationwide owners",
    stayLinks: [
      ["Test what ‘near transport’ really means", "china-hotel-near-metro", "Use the same exit-to-lobby and final-walk audit when a listing claims nearby transit; a map pin does not prove a practical Zhangjiajie transfer."],
      ["Verify an actually usable accessible room", "china-accessible-hotel-room-verification", "Check the complete street or vehicle-drop-off to room and bathroom chain at the exact property."],
      ["Can foreigners stay at any hotel in China?", "foreigners-china-hotel", "Keep the legal rule, platform display and the named property's current passport-registration operation separate."],
      ["Choose the last night before an international flight", "china-last-night-before-international-flight", "Protect the local DYG or rail positioning leg, then work backwards from the actual international airport and terminal."],
    ],
    quoteTitle: "Need a human Zhangjiajie property-fit check?",
    quoteBody: "Use the general planner only for a first contact. In the initial form, share travel dates, the city or areas being compared, traveller and room counts, and an approximate accommodation budget if useful. You may say that you want to discuss family or accessibility arrangements later, but do not submit children's ages, mobility, medical or accessibility details, passport or other document information, booking or payment records, or identifiable material intended for a hotel, DMC or other supplier. A planner can arrange a separate human follow-up; those details are discussed only when appropriate and with suitable consent. Nothing is shared with a supplier without separate, purpose-specific consent, and this is not live inventory or a guarantee of price, availability, guest acceptance, room type or accessibility.",
    onwardHeading: "Choose the next city by the journey it creates",
    onwardColumns: ["Next place", "Works when", "Boundary"],
    onwardRows: [
      ["Fenghuang", "A historic-town evening and next morning are a real priority", "It needs transport and usually a night; it is not a park extension"],
      ["Changsha", "A major rail/air gateway or Hunan city stay helps the route", "Do not add it only because every map line passes through Hunan"],
      ["Chongqing", "The exact dated rail or flight pattern and a real Chongqing stay work", "Search the actual station pair; direction alone does not establish a train"],
      ["Beijing or Shanghai", "The long jump preserves enough complete days on both sides", "Compare door-to-door flight and rail, not headline duration"],
    ],
    recheckHeading: "Recheck before every Zhangjiajie trip",
    recheckItems: [
      "The exact product, passport requirements, first entrance, time slot and inclusion list for every attraction.",
      "Park shuttle, lift and cableway operation on the travel day; no diagram proves live service.",
      "Weather, visibility, lightning, maintenance and temporary closures before leaving the hotel.",
      "The exact DYG terminal or Zhangjiajie West train, plus the final transfer to the correct hotel branch.",
      "Night-show venue, programme, finish time and transport back to the chosen base.",
      "The current onward ticket before committing to Fenghuang, Changsha or another long transfer.",
    ],
    faqHeading: "Common questions",
    faqs: [
      ["How many days for a first trip?", "Three complete sightseeing days are the strongest default. Two force a major omission; four buy weather recovery, slower mobility or one separate attraction."],
      ["Should I stay in the city or Wulingyuan?", "Use Wulingyuan to protect early park starts and the city for Tianmen, gateways or late arrivals. Split only when the saved transfer is worth another luggage move."],
      ["Are Tianmen Mountain and Tianzi Mountain the same?", "No. Tianmen is a separate city-side attraction system. Tianzi Mountain is one upper scenic area within the Wulingyuan landscape."],
      ["Is the Glass Bridge inside the National Forest Park?", "No. It belongs to the Grand Canyon system in another direction. Tianmen's glass skywalks are different again."],
      ["Can Fenghuang be a quick evening add-on?", "Usually not honestly. It needs a separate transfer and becomes worthwhile when the old town receives an evening and preferably the next morning."],
      ["Does a city-side last night protect an international departure?", "Only partly. A city night can protect an early DYG flight or Zhangjiajie West rail leg, but DYG is not a generic international-departure solution. For an international flight elsewhere, work backwards from the actual airport, terminal and check-in deadline, then decide whether another airport-side buffer is necessary. Reconfirm the dated positioning ticket, hotel handoff and fallback."],
    ],
    planningTitle: "Test the complete route, not only the mountain days",
    planningLinks: [
      ["Compare Beijing–Zhangjiajie–Shanghai transport", "beijing-zhangjiajie-shanghai-transport", "Count airports, stations, late arrivals and protected hotel handoffs."],
      ["Review an existing China itinerary", "../china-itinerary-review", "Check whether the chosen nights really contain the promised complete days."],
    ],
    sourcesTitle: "Official and primary sources",
    sourceLabels: ["Wulingyuan Scenic and Historic Interest Area", "Zhangjiajie municipal government", "China Railway 12306 date-specific search", "Zhangjiajie Hehua Airport identity", "Owner-supplied real Zhangjiajie hero photograph and rights record"],
  },
  zh: {
    lead: "张家界不是一座只有一个门的公园。这个目的地名同时包含城市门户、武陵源与国家森林公园、市区旁的天门山，以及另一个方向的大峡谷。多数第一次旅行以三个完整游览日最稳；真正的规划问题是哪些系统值得占用这些天，以及哪个住宿基地能保护每天第一次出发。",
    answerTitle: "先数完整游览日，不要只数订房晚数",
    answerBody: "两个完整日必须舍弃一个大项；三个完整日通常可以安排森林公园两日加天门山，或一个明确的替代；四个完整日增加天气恢复、慢速行动或一个独立景区。抵达与离开碎片不能冒充山岳游览日。",
    fitHeading: "张家界适合谁",
    fitColumns: ["旅客", "为什么适合", "设计要求"],
    fitRows: [
      ["第一次看峰林的旅客", "石英砂岩峰林确实独特", "保护至少两个公园时段，不要只收集互不相连的亮点"],
      ["家庭或年长旅客", "巴士、索道和电梯可以替代大量爬升", "乘坐工具并不会消除排队、站立、平台步行与天气暴露"],
      ["摄影或慢旅行者", "云雾、光线和观景台值得留出弹性", "第四日比再承诺一个固定景点更有用"],
      ["中国总行程很短", "只有张家界是真正优先级时才成立", "不要把航班、列车、换酒店和上山接驳藏进游览日"],
    ],
    daysHeading: "两个、三个和四个完整日分别意味着什么",
    daysColumns: ["完整日", "现实形态", "必须留在外面"],
    daysRows: [
      ["2", "一个扎实的森林公园日加天门山，或两个精选公园日", "大峡谷、凤凰，以及走完所有山顶分区的承诺"],
      ["3", "森林公园两日加天门山；第一次旅行最强默认", "顺手加大峡谷，以及没有保护的离开日"],
      ["4", "天气恢复、慢节奏，或独立选择一个大峡谷/文化日", "把多出一天变成第四套拥挤清单"],
    ],
    baseHeading: "按每天早晨的第一项任务选择住宿基地",
    baseColumns: ["基地", "最适合", "代价"],
    baseRows: [
      ["武陵源", "森林公园早出发与连续两个公园日", "离荷花机场、张家界西站和天门山市区系统更远"],
      ["张家界市区", "天门山、晚到、早走与门户接驳", "去武陵源公园门前先消耗一段道路接驳"],
      ["双基地", "晚数足够、需要同时保护公园和市区任务", "退房、行李和额外交接；只有省下的接驳更大才值得"],
    ],
    gatewayHeading: "按准确门户进入和离开",
    gatewayIntro: "荷花机场与张家界西站都在市区一侧，不在武陵源公园入口。把每次抵达与真实酒店前台、时段、行李和合规接驳对应。很晚到达时，即使后两日住武陵源，第一晚也可能更适合市区。",
    gatewayColumns: ["门户", "规划作用", "常见失败"],
    gatewayRows: [
      ["DYG荷花机场", "用航班消除长距离地面移动", "把机场当作森林公园门口"],
      ["张家界西站", "市区一侧的高铁与区域铁路门户", "把列车到站时间当成抵达武陵源酒店"],
      ["道路接驳", "连接门户、市区与武陵源的最后一程", "接受无资质接客，或只给模糊酒店名而没有中文地址"],
    ],
    systemsHeading: "四个绝不能折叠成一个景点的名称",
    systemsColumns: ["系统", "它负责什么", "不要混淆"],
    systemsRows: [
      ["张家界国家森林公园 / 武陵源核心", "多个门、谷底、山顶台地、环保车、电梯与索道", "天门山或大峡谷"],
      ["天门山", "市区侧独立票务与交通系统，通常占用一个大时段", "武陵源景观中的天子山"],
      ["张家界大峡谷", "另一个方向的大峡谷与玻璃桥系统", "天门山的玻璃栈道"],
      ["凤凰", "独立古城目的地与下一段路线决策", "张家界里面的夜间街区"],
    ],
    parkTitle: "国家森林公园仍需单独决定门票、入口与园内交通",
    parkBody: "本 Hub 只解释森林公园在整趟旅程里的位置。专门的门票—入口—园内交通 owner 负责首入门、所购产品包含什么、环保车怎样接电梯或索道，以及护照、时段或入口计划失败后的补救。不要把这套高动态流程复制到泛目的地页。",
    readingTitle: "下一步交给对应 canonical owner",
    links: [
      ["查看2、3、4天到底能安排什么", "zhangjiajie-itinerary", "逐日分配与主动舍弃。"],
      ["选择张家界市区还是武陵源", "zhangjiajie-city-or-wulingyuan-hotel-base", "比较两个住宿基地，以及什么时候值得搬行李。"],
      ["选择森林公园门票、入口与园内交通", "zhangjiajie-national-forest-park-tickets-and-entrances", "入口、护照、预订与园内失败补救。"],
      ["分清玻璃桥与玻璃栈道", "zhangjiajie-glass-bridge-vs-skywalk", "三个不同地点、票务系统与身体体验。"],
      ["带年长旅客规划张家界", "zhangjiajie-older-travellers", "乘坐工具、步行负荷、排队与补救选择。"],
      ["比较张家界夜间演出", "best-zhangjiajie-night-show", "按住宿基地、结束时间和白天剩余体力选择。"],
    ],
    stayReadingTitle: "用全国住宿 owner 完成最后核验",
    stayLinks: [
      ["判断所谓‘靠近交通’是否真方便", "china-hotel-near-metro", "遇到靠近车站或交通的标签，也要核对出口、道路、接驳点和大堂；地图坐标不能证明张家界最后一程好走。"],
      ["核验真正可用的无障碍酒店房", "china-accessible-hotel-room-verification", "按具体物业核对从街道或车辆下客点到客房及浴室的完整通路。"],
      ["外国旅客能住中国任何酒店吗？", "foreigners-china-hotel", "把法律规则、平台显示和该物业当前能否完成护照登记分开记录。"],
      ["选择国际航班前最后一晚", "china-last-night-before-international-flight", "先保护 DYG 或铁路定位段，再从真正的国际出境机场和航站楼倒推。"],
    ],
    quoteTitle: "需要人工核对张家界候选住宿？",
    quoteBody: "现有通用规划入口只用于初次联系。初始表单仅填写旅行日期、准备比较的城市或区域、旅客与房间数量，以及必要时的大致住宿预算。可以说明希望稍后讨论家庭或无障碍安排，但不要提交儿童具体年龄、行动、医疗或无障碍细节、护照或其他证件资料、订单或付款记录，或任何准备转交酒店、地接等供应商的可识别资料。规划师会另行安排人工跟进；这些细节只在确有需要并取得适当同意后讨论。未经另行、针对明确目的的同意，Homeground 不会把资料分享给供应商；这里也不是实时库存系统，不保证价格、房态、外宾接待、房型或无障碍适用性。",
    onwardHeading: "按它创造的旅程选择下一座城市",
    onwardColumns: ["下一站", "何时成立", "边界"],
    onwardRows: [
      ["凤凰", "古城夜晚与次日清晨是真正优先级", "需要独立交通且通常住一晚，不是公园延伸"],
      ["长沙", "作为铁路/航空门户或湖南城市停留确有作用", "不要只因地图线路经过湖南就自动加入"],
      ["重庆", "具体日期的铁路或航班与重庆停留都合适", "搜索准确车站组合，方向不能证明车次"],
      ["北京或上海", "长距离跳转仍能保护两端完整游览日", "比较门到门飞行和铁路，不只看标称时间"],
    ],
    recheckHeading: "每次张家界旅行前重新核对",
    recheckItems: ["每个景区产品的准确名称、护照要求、首入门、时段与包含项目。", "出行日的环保车、电梯与索道运营；示意图不能证明实时开放。", "离开酒店前查天气、能见度、雷电、检修与临时关闭。", "准确航站楼或张家界西站车次，以及到正确酒店分店的最后一程。", "夜间演出的场地、节目、结束时间与返回基地交通。", "承诺凤凰、长沙或其他长接驳前，先确认真实下一程车票。"],
    faqHeading: "常见问题",
    faqs: [
      ["第一次去需要几天？", "三个完整游览日是最强默认。两日必须大舍弃；四日提供天气恢复、慢速行动或一个独立景区。"],
      ["住市区还是武陵源？", "武陵源保护公园早出发，市区适合天门山、门户和晚到。只有省下的接驳大于搬行李成本时才双基地。"],
      ["天门山和天子山是一个地方吗？", "不是。天门山是市区侧独立景区系统；天子山是武陵源景观中的一个山顶分区。"],
      ["玻璃桥在森林公园里面吗？", "不在。它属于另一个方向的大峡谷系统；天门山的玻璃栈道又是第三件事。"],
      ["凤凰能顺便去看一个晚上吗？", "通常不能诚实地称为顺便。它需要独立接驳，至少获得一个夜晚，最好还保留次日清晨才更值得。"],
      ["市区最后一晚能保护国际航班吗？", "只能保护其中一段。市区住宿可以降低清早乘 DYG 航班或从张家界西站离开的风险，但 DYG 不是通用的国际离境解决方案。若国际航班从别处起飞，应从真实机场、航站楼和截止时间倒推，再判断是否还需机场侧缓冲。请重查定位票、酒店交接和备用方案。"],
    ],
    planningTitle: "检验完整路线，不只看山上几天",
    planningLinks: [
      ["比较北京—张家界—上海交通", "beijing-zhangjiajie-shanghai-transport", "计算机场、车站、晚到与酒店交接。"],
      ["审阅已有中国行程", "../china-itinerary-review", "检查订下的晚数是否真的包含承诺的完整游览日。"],
    ],
    sourcesTitle: "官方与一手来源",
    sourceLabels: ["武陵源风景名胜区", "张家界市人民政府", "中国铁路12306按日期查询", "张家界荷花机场身份", "业主提供的真实张家界题图与权利记录"],
  },
  ko: {
    lead: "장자제는 입구 하나인 공원 하나가 아닙니다. 목적지 이름에는 도시 관문, 우링위안과 국가삼림공원, 시내 옆 톈먼산, 다른 방향의 대협곡이 함께 들어갑니다. 첫 여행은 온전한 관광일 3일이 가장 잘 맞으며, 어떤 체계에 그날을 주고 어느 숙소 거점이 첫 출발을 지킬지가 핵심입니다.",
    answerTitle: "예약 화면의 숙박일이 아니라 온전한 관광일을 세세요",
    answerBody: "온전한 2일은 큰 하나를 빼야 합니다. 3일은 보통 국가삼림공원 2일과 톈먼산 또는 명확한 대안을 담습니다. 4일은 날씨 회복, 느린 이동 또는 독립된 장소 하나를 더합니다. 도착·출발 조각은 산악 관광일이 아닙니다.",
    fitHeading: "장자제가 맞는 여행자",
    fitColumns: ["여행자", "맞는 이유", "설계 조건"],
    fitRows: [
      ["첫 산수 여행자", "사암 봉우리 경관이 실제로 독특함", "분리된 하이라이트 수집 대신 공원 쪽 블록 2개 보호"],
      ["가족·고령 여행자", "버스·케이블카·엘리베이터가 많은 오르막을 대체", "탑승도 대기·서기·플랫폼 보행·날씨 노출을 없애지 않음"],
      ["사진·느린 여행자", "안개·빛·전망대가 시간 탄력성을 보상", "고정 명소 하나보다 4일째가 유용"],
      ["매우 짧은 중국 일정", "장자제가 진짜 우선순위일 때만 가능", "항공·철도·호텔 이동·산악 접속을 관광일에 숨기지 않기"],
    ],
    daysHeading: "온전한 2·3·4일의 의미",
    daysColumns: ["온전한 날", "현실적인 형태", "밖에 둘 것"],
    daysRows: [
      ["2", "국가삼림공원 큰 하루와 톈먼산, 또는 선택적 공원 2일", "대협곡·펑황·모든 상부 구역 완성 약속"],
      ["3", "공원 2일과 톈먼산; 첫 여행의 가장 강한 기본값", "대협곡 덧붙이기와 보호되지 않은 출발"],
      ["4", "날씨 회복, 느린 속도 또는 별도로 고른 대협곡/문화 하루", "추가 하루를 네 번째 혼잡 목록으로 만들기"],
    ],
    baseHeading: "매일 아침 첫 과제로 숙소 거점을 고르세요",
    baseColumns: ["거점", "가장 좋은 경우", "대가"],
    baseRows: [
      ["우링위안", "이른 국가삼림공원 출발과 연속 2일", "DYG·장자제서역·톈먼산 시내 체계에서 멂"],
      ["장자제 시내", "톈먼산, 늦은 도착, 이른 출발과 관문", "우링위안 공원 시작 전 도로 이동 소모"],
      ["두 거점", "숙박이 충분해 공원과 시내 과제를 모두 보호", "체크아웃·짐·인계; 절약 이동이 더 클 때만"],
    ],
    gatewayHeading: "정확한 관문으로 들어오고 나가세요",
    gatewayIntro: "DYG 공항과 장자제서역은 모두 시내 쪽이며 우링위안 공원 입구가 아닙니다. 실제 호텔 프런트, 시각, 짐과 합법적인 이동에 도착을 연결하세요. 늦은 도착은 다음 2일이 우링위안이어도 시내 1박을 정당화할 수 있습니다.",
    gatewayColumns: ["관문", "역할", "흔한 실패"],
    gatewayRows: [
      ["DYG 허화공항", "긴 육상 이동을 없애는 항공편", "공항을 삼림공원 입구로 생각"],
      ["장자제서역", "시내 쪽 고속철·지역 철도 관문", "열차 도착을 우링위안 호텔 도착으로 계산"],
      ["도로 이동", "관문·시내·우링위안 마지막 연결", "무허가 픽업 또는 중국어 주소 없는 모호한 호텔 이름"],
    ],
    systemsHeading: "하나의 명소로 합치면 안 되는 네 이름",
    systemsColumns: ["체계", "맡는 것", "혼동 금지"],
    systemsRows: [
      ["장자제 국가삼림공원 / 우링위안 핵심", "여러 게이트, 계곡, 상부 고원, 셔틀·엘리베이터·케이블카", "톈먼산 또는 대협곡"],
      ["톈먼산", "시내 쪽 독립 티켓·교통 체계와 큰 시간 블록", "우링위안의 톈쯔산"],
      ["장자제 대협곡", "다른 방향의 유리다리와 협곡 체계", "톈먼산 유리잔도"],
      ["펑황", "별도 고성 목적지와 다음 동선 결정", "장자제 안의 저녁 동네"],
    ],
    parkTitle: "국가삼림공원은 티켓·입구·공원 내 교통 결정을 따로 해야 합니다",
    parkBody: "허브는 공원이 전체 여행에서 어디에 놓이는지만 설명합니다. 전용 티켓–입구–공원 교통 owner가 첫 게이트, 구매 상품 포함, 셔틀과 엘리베이터·케이블카 관계, 여권·시간대·입구 계획 실패 대처를 맡습니다. 이 변동성 높은 절차를 넓은 목적지 페이지에 복사하지 않습니다.",
    readingTitle: "다음 결정은 해당 canonical owner로 이어가세요",
    links: [
      ["2·3·4일에 가능한 것 보기", "zhangjiajie-itinerary", "정확한 날짜 배분과 뺄 것."],
      ["장자제 시내 또는 우링위안 고르기", "zhangjiajie-city-or-wulingyuan-hotel-base", "두 숙소 거점과 짐 이동 가치 비교."],
      ["국가삼림공원 티켓·입구·교통 고르기", "zhangjiajie-national-forest-park-tickets-and-entrances", "게이트·여권·예약과 공원 안 실패 대처."],
      ["유리다리와 유리잔도 나누기", "zhangjiajie-glass-bridge-vs-skywalk", "서로 다른 세 장소·티켓·신체 경험."],
      ["고령 여행자와 장자제 계획", "zhangjiajie-older-travellers", "탑승·보행·대기와 회복 선택."],
      ["장자제 야간 공연 비교", "best-zhangjiajie-night-show", "숙소 거점·종료 시각·낮 체력으로 선택."],
    ],
    stayReadingTitle: "전국 숙박 owner로 마지막 확인을 마치세요",
    stayLinks: [
      ["‘교통과 가까움’이 실제로 편리한지 확인", "china-hotel-near-metro", "역이나 교통 근처라는 표시도 출구·도로·승하차 지점·로비까지 확인하세요. 지도 핀은 장자제 마지막 이동을 증명하지 않습니다."],
      ["실제로 쓸 수 있는 접근성 객실 확인", "china-accessible-hotel-room-verification", "해당 숙소의 도로나 차량 하차 지점부터 객실과 욕실까지 전체 경로를 확인하세요."],
      ["외국인은 중국의 모든 호텔에 묵을 수 있을까?", "foreigners-china-hotel", "법적 규칙, 플랫폼 표시, 해당 숙소의 현재 여권 등록 운영을 따로 기록하세요."],
      ["국제선 전 마지막 밤 선택", "china-last-night-before-international-flight", "DYG 또는 철도 포지셔닝 구간을 먼저 보호하고 실제 국제선 출발 공항과 터미널에서 거꾸로 계산하세요."],
    ],
    quoteTitle: "장자제 후보 숙소를 사람과 함께 확인하고 싶다면",
    quoteBody: "현재 일반 플래너 창구는 첫 연락에만 이용하세요. 초기 양식에는 여행 날짜, 비교할 도시나 지역, 여행자 수와 객실 수, 필요하다면 대략적인 숙박 예산만 적으세요. 가족 또는 접근성 준비를 나중에 상의하고 싶다고 표시할 수는 있지만, 어린이의 구체적인 나이, 이동·의료·접근성 세부 정보, 여권이나 기타 신분증 정보, 예약·결제 기록, 호텔·DMC 등 공급업체에 전달하려는 식별 가능한 자료는 제출하지 마세요. 플래너가 별도의 후속 상담을 안내하며, 이런 세부 정보는 필요한 경우 적절한 동의를 받은 뒤에만 논의합니다. 별도의 목적별 동의 없이는 공급업체와 자료를 공유하지 않으며, 이 창구는 실시간 재고가 아니므로 가격·객실 가능 여부·외국인 투숙·객실 유형·접근성을 보장하지 않습니다.",
    onwardHeading: "만들어지는 여정으로 다음 도시를 고르세요",
    onwardColumns: ["다음 장소", "성립할 때", "경계"],
    onwardRows: [
      ["펑황", "고성의 저녁과 다음 아침이 실제 우선순위", "별도 교통과 보통 1박 필요; 공원 연장이 아님"],
      ["창사", "철도·항공 관문 또는 후난 도시 체류가 동선에 도움", "후난을 지난다는 이유만으로 자동 추가 금지"],
      ["충칭", "날짜별 철도·항공과 충칭 체류가 모두 맞음", "실제 역 조합 검색; 방향은 열차를 증명하지 않음"],
      ["베이징·상하이", "장거리 이동 뒤 양쪽 온전한 날이 보호됨", "표면 시간 말고 문에서 문까지 항공·철도 비교"],
    ],
    recheckHeading: "모든 장자제 여행 전에 재확인하세요",
    recheckItems: ["각 관광 상품의 정확한 이름, 여권 조건, 첫 입구, 시간대와 포함 항목.", "여행일의 셔틀·엘리베이터·케이블카 운행; 도식은 실시간 개방 증거가 아님.", "호텔 출발 전 날씨·가시거리·낙뢰·정비·임시 폐쇄.", "정확한 DYG 터미널 또는 장자제서역 열차와 올바른 호텔 지점까지 마지막 이동.", "야간 공연 장소·프로그램·종료 시각과 거점 귀환 교통.", "펑황·창사 또는 긴 다음 이동을 약속하기 전 실제 표."],
    faqHeading: "자주 묻는 질문",
    faqs: [
      ["첫 여행은 며칠인가?", "온전한 관광일 3일이 가장 강한 기본값입니다. 2일은 큰 제외가 필요하고 4일은 날씨 회복·느린 이동·별도 명소를 삽니다."],
      ["시내 또는 우링위안?", "우링위안은 공원 이른 출발, 시내는 톈먼산·관문·늦은 도착에 맞습니다. 절약 이동이 짐 이동보다 클 때만 두 거점입니다."],
      ["톈먼산과 톈쯔산은 같은가?", "아닙니다. 톈먼산은 시내 쪽 별도 체계이고 톈쯔산은 우링위안 상부 구역입니다."],
      ["유리다리는 국가삼림공원 안인가?", "아닙니다. 다른 방향의 대협곡 체계이며 톈먼산 유리잔도는 또 다릅니다."],
      ["펑황을 저녁에 잠깐 더할 수 있나?", "대개 솔직한 ‘잠깐’이 아닙니다. 별도 이동과 저녁, 가능하면 다음 아침을 줘야 가치가 생깁니다."],
      ["시내 마지막 밤이 국제선 출발을 지켜 주나?", "일부 구간만 보호합니다. 시내 숙박은 이른 DYG 항공편이나 장자제서역 출발 위험을 줄일 수 있지만 DYG가 모든 국제선 출발의 해답은 아닙니다. 국제선이 다른 공항에서 출발한다면 실제 공항·터미널·체크인 마감에서 거꾸로 계산해 공항 쪽 추가 완충 숙박이 필요한지 판단하세요. 날짜가 정해진 포지셔닝 표, 호텔 인계와 대안을 다시 확인하세요."],
    ],
    planningTitle: "산에서 보낸 날만 아니라 전체 동선을 시험하세요",
    planningLinks: [
      ["베이징–장자제–상하이 교통 비교", "beijing-zhangjiajie-shanghai-transport", "공항·역·늦은 도착과 호텔 인계를 셉니다."],
      ["기존 중국 일정 검토", "../china-itinerary-review", "예약한 박수가 약속한 온전한 날을 실제로 담는지 확인합니다."],
    ],
    sourcesTitle: "공식·1차 출처",
    sourceLabels: ["우링위안 경관·역사 지구", "장자제시 인민정부", "중국철도 12306 날짜별 검색", "장자제 허화공항 식별", "소유자가 제공한 실제 장자제 대표 사진과 권리 기록"],
  },
} as const;

const sourceUrls = [
  ["https://whc.unesco.org/en/list/640/", "UNESCO World Heritage Centre"],
  ["https://www.zjj.gov.cn/", "People's Government of Zhangjiajie Municipality"],
  ["https://www.12306.cn/en/index.html", "China Railway 12306"],
  ["https://www.caac.gov.cn/GYMH/MHGK/JCJSDT/201511/t20151130_11065.html", "Civil Aviation Administration of China"],
  ["https://homegroundchina.com/guides/zhangjiajie-itinerary/", "Homeground field editorial record"],
] as const;

function guidePath(locale: HomegroundLocale, slug: string) {
  return locale === "en" ? `/guides/${slug}/` : `/${locale}/guides/${slug}/`;
}

export function buildZhangjiajieBody(locale: HomegroundLocale): StructuredPageBody {
  const c = copies[locale];
  return {
    schemaVersion: "1.0.0",
    blocks: [
      { id: "lead", type: "lead", text: c.lead },
      { id: "answer", type: "callout", title: c.answerTitle, body: c.answerBody, tone: "decision" },
      { id: "fit-heading", type: "heading", level: 2, text: c.fitHeading },
      { id: "fit", type: "table", caption: c.fitHeading, columns: c.fitColumns, rows: c.fitRows },
      { id: "days-heading", type: "heading", level: 2, text: c.daysHeading },
      { id: "days", type: "table", caption: c.daysHeading, columns: c.daysColumns, rows: c.daysRows },
      { id: "base-heading", type: "heading", level: 2, text: c.baseHeading },
      { id: "bases", type: "table", caption: c.baseHeading, columns: c.baseColumns, rows: c.baseRows },
      { id: "gateway-heading", type: "heading", level: 2, text: c.gatewayHeading },
      { id: "gateway-intro", type: "paragraph", text: c.gatewayIntro },
      { id: "gateways", type: "table", caption: c.gatewayHeading, columns: c.gatewayColumns, rows: c.gatewayRows },
      { id: "systems-heading", type: "heading", level: 2, text: c.systemsHeading },
      { id: "systems", type: "table", caption: c.systemsHeading, columns: c.systemsColumns, rows: c.systemsRows },
      { id: "park-boundary", type: "callout", title: c.parkTitle, body: c.parkBody, tone: "warning" },
      { id: "reading", type: "internal-links", title: c.readingTitle, items: c.links.map(([label, slug, description]) => ({ label, href: guidePath(locale, slug), description })) },
      { id: "stay-owners", type: "internal-links", title: c.stayReadingTitle, items: c.stayLinks.map(([label, slug, description]) => ({ label, href: guidePath(locale, slug), description })) },
      { id: "stay-quote-handoff", type: "callout", title: c.quoteTitle, body: c.quoteBody, tone: "neutral" },
      { id: "onward-heading", type: "heading", level: 2, text: c.onwardHeading },
      { id: "onward", type: "table", caption: c.onwardHeading, columns: c.onwardColumns, rows: c.onwardRows },
      { id: "recheck-heading", type: "heading", level: 2, text: c.recheckHeading },
      { id: "recheck", type: "list", items: c.recheckItems },
      { id: "faq-heading", type: "heading", level: 2, text: c.faqHeading },
      ...c.faqs.flatMap(([question, answer], index) => [
        { id: `faq-${index + 1}-heading`, type: "heading" as const, level: 3 as const, text: question },
        { id: `faq-${index + 1}`, type: "paragraph" as const, text: answer },
      ]),
      { id: "planning", type: "internal-links", title: c.planningTitle, items: c.planningLinks.map(([label, target, description]) => ({
        label,
        href: target.startsWith("..")
          ? locale === "en" ? "/china-itinerary-review/" : `/${locale}/china-itinerary-review/`
          : guidePath(locale, target),
        description,
      })) },
      { id: "sources", type: "sources", title: c.sourcesTitle, items: sourceUrls.map(([url, publisher], index) => ({ label: c.sourceLabels[index], url, publisher, reviewedAt: "2026-08-20" })) },
    ],
  };
}
