import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "Chengdu Wuhou Shrine is worth visiting if you read it as a layered memorial, not as a preserved Three Kingdoms palace or a walk-through version of Romance of the Three Kingdoms. Start under the gate marked 漢昭烈廟 (simplified: 汉昭烈庙)—Han Zhaolie Temple, named for Liu Bei—then use a dated Tang stele, the Qing-period hall hierarchy, a relocated Sanyi Temple, Huiling and modern Jinli to ask a different question at every stop. The historical people are real; the visible architecture, statues, literary scenes and visitor street belong to different centuries and kinds of evidence. With that key, even a traveller who has never read the novel can make sense of the site.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The route in one decision",
      tone: "decision",
      body: "If your priority is evidence, keep the museum’s forward spine: entrance plaque → 809 Tang stele → Liu Bei Hall and official corridors → passage and Zhuge Liang Hall → Sanyi Temple → Huiling. Add the permanent exhibition when open for historical context, and treat Jinli as a separate modern tourism layer. Readers of the novel should do the same route rather than chase every familiar character. Homeground’s judgment is that this order gives the site more meaning than beginning with Jinli or treating every statue as an illustration of the book.",
    },
    {
      id: "layer-key",
      type: "table",
      caption: "Use one of four evidence labels at every stop",
      columns: ["Label", "What it means here", "What it cannot prove"],
      rows: [
        ["History", "A recorded person, office, event or burial statement, usually reached through an identified historical text", "That a later hall, image or popular anecdote is contemporary evidence"],
        ["Memorial history", "A later community, ruler, official or museum decided how people should be remembered in architecture, text or ritual", "That the arrangement reproduces a Shu-Han court or that a statue is a portrait"],
        ["Literature", "A historical novel and its long performance tradition selected, combined and dramatized people and episodes", "That every scene happened as narrated—or that every character in the novel is invented"],
        ["Tourism presentation", "Modern visitor facilities, themed streets, interpretation and commercial display make the past accessible", "That an antique-looking setting is ancient material evidence"],
      ],
    },
    {
      id: "gate-heading",
      type: "heading",
      level: 2,
      text: "Why does the Wuhou Shrine gate name Liu Bei?",
    },
    {
      id: "gate-p1",
      type: "paragraph",
      text: "Look up before entering. The plaque uses the traditional characters 漢昭烈廟 (simplified: 汉昭烈庙), Han Zhaolie Temple: Zhaolie is Liu Bei’s posthumous imperial title. Yet residents and visitors commonly call the whole complex Wuhou Shrine, using Zhuge Liang’s title, Marquis Wu. That mismatch is not a sign that you found the wrong entrance. It is the first physical clue that several memorial identities were combined and that popular memory did not follow the official hierarchy neatly.",
    },
    {
      id: "gate-p2",
      type: "paragraph",
      text: "The museum’s historical account begins with Huiling, the burial place named for Liu Bei in the historical record. Separate memorials for Liu Bei and Zhuge Liang existed near one another later. In 1390–1391, the Ming prince Zhu Chun consolidated the minister’s image into Liu Bei’s temple; after war damage, a 1671–1672 Qing rebuilding established the basic front-and-back arrangement visible today. The gate therefore introduces a long history of remembrance. It is not a surviving entrance to Liu Bei’s third-century court.",
    },
    {
      id: "gate-check",
      type: "callout",
      title: "First observation: record two names",
      tone: "neutral",
      body: "Photograph or note the visible 漢昭烈廟 plaque only if the current sign permits it, then find 武侯祠 over the passage farther inside. The two labels mark a useful conceptual movement: from the emperor’s memorial zone to the narrower shrine for his minister. Do not turn the plaques into construction dates; names and fabric have their own histories.",
    },
    {
      id: "stele-heading",
      type: "heading",
      level: 2,
      text: "What can the Tang ‘Three-Success Stele’ actually tell you?",
    },
    {
      id: "stele-p1",
      type: "paragraph",
      text: "Inside the first courtyard, look for the stele titled 蜀丞相诸葛武侯祠堂碑—the Stele of the Ancestral Hall of Zhuge, Marquis Wu. It was erected in 809, almost six centuries after Liu Bei’s death. The museum identifies Pei Du as the author, Liu Gongchuo as the calligrapher and Lu Jian as the carver. Later admirers called it the 三绝碑, often rendered ‘Three-Success’ or ‘Three-Excellence Stele,’ because text, calligraphy and carving were each esteemed.",
    },
    {
      id: "stele-p2",
      type: "paragraph",
      text: "Its value comes precisely from being dated and later. It shows that Zhuge Liang already had a powerful memorial reputation in Tang Chengdu and records what an elite visitor wanted people to admire. It does not record a speech made by Zhuge Liang, show his face or prove that the current courtyard existed in 809. Read the heading, date and makers before trying to decipher the long praise text. The object becomes evidence for the history of reputation, not a shortcut to biography.",
    },
    {
      id: "stele-table",
      type: "table",
      caption: "Three questions to ask of any inscription",
      columns: ["Question", "At this stele", "Why it matters"],
      rows: [
        ["When?", "Tang Yuanhe year four, 809", "It separates the inscription from the third-century life it remembers"],
        ["Who made it?", "Pei Du wrote, Liu Gongchuo calligraphed and Lu Jian carved it", "Authorship turns ‘an old stone’ into an attributable act of commemoration"],
        ["What kind of claim?", "Praise and political-moral judgment about Zhuge Liang", "Evaluation is evidence of reception, not neutral eyewitness reporting"],
      ],
    },
    {
      id: "liubei-heading",
      type: "heading",
      level: 2,
      text: "Read Liu Bei Hall and the corridors as a later memorial court",
    },
    {
      id: "liubei-p1",
      type: "paragraph",
      text: "After the second gate, the larger and higher Liu Bei Hall controls the front court. The emperor occupies the principal hall; associated figures appear in side halls, and civil and military officials line the two corridors. This order expresses the Qing builders’ solution to a political and ritual problem: honour the ruler first while giving the widely admired Zhuge Liang a distinct hall behind him. It is a designed hierarchy of remembrance, not a map of where those people worked in Shu-Han Chengdu.",
    },
    {
      id: "liubei-p2",
      type: "paragraph",
      text: "Now slow down at the corridors. The museum dates the coloured clay figures between the 1672 rebuilding and later Qing adjustments, with a major reshaping in 1849. It also says their clothing drew mainly on Qing opera. That is an unusually useful label: a named official may be historical while the face, costume and position are later visual interpretation. Read the individual name tablet for identity, the date label for the statue, and the costume as evidence of how later audiences imagined the past.",
    },
    {
      id: "corridor-table",
      type: "table",
      caption: "Do not ask one object to answer four different questions",
      columns: ["What you see", "Safe conclusion", "Common overreach"],
      rows: [
        ["A named official’s statue", "That person was selected for later commemoration here", "‘This is what the person looked like’"],
        ["Qing-opera-influenced clothing", "Later theatre helped shape a recognisable visual language", "‘This is documented third-century dress’"],
        ["A position near Liu Bei", "The memorial designers assigned a relationship and rank", "‘The real court stood in this order’"],
        ["An omitted person", "The current memorial program did not include that figure", "‘The person was historically unimportant’"],
      ],
    },
    {
      id: "zhuge-heading",
      type: "heading",
      level: 2,
      text: "What changes when you cross into Zhuge Liang Hall?",
    },
    {
      id: "zhuge-p1",
      type: "paragraph",
      text: "The passage after Liu Bei Hall carries the 武侯祠 plaque and functions as the threshold into the narrower shrine. Beyond it, Zhuge Liang Hall sits lower and is smaller than the emperor’s hall. The museum explains this as a Qing compromise: front hall ‘court’ etiquette preserved ruler–minister hierarchy, while the rear hall gave Zhuge Liang and descendants a more self-contained memorial space. You can read that spatial contrast without deciding which man was ‘more important.’ Architecture is showing a later answer to competing duties and affections.",
    },
    {
      id: "zhuge-p2",
      type: "paragraph",
      text: "This is also where novel knowledge can distort looking. If you arrive expecting an all-knowing strategist from Romance of the Three Kingdoms, every fan, robe or inscription may seem to confirm the character. Reverse the method: identify what the museum dates; separate a historical office or documented action from moral praise; then ask whether a familiar trait comes from the historical record, later worship, opera, the novel or screen adaptation. The shrine preserves the career of Zhuge Liang’s reputation as much as it explains the man.",
    },
    {
      id: "zhuge-warning",
      type: "callout",
      title: "Do not use popularity as a dating tool",
      tone: "warning",
      body: "The fact that the entire complex is commonly called Wuhou Shrine shows the strength of Zhuge Liang’s later memory. It does not make the rear hall older than the Liu Bei memorial, turn its statue into a contemporary portrait or prove a novel episode. Popular names are cultural evidence—but evidence of reception.",
    },
    {
      id: "sanyi-heading",
      type: "heading",
      level: 2,
      text: "Is Sanyi Temple proof of the Peach Garden Oath?",
    },
    {
      id: "sanyi-p1",
      type: "paragraph",
      text: "No. Liu Bei, Guan Yu and Zhang Fei were historical people, but the hall’s architecture and images are later memorial evidence. The museum itself says the figures here were shaped from Romance of the Three Kingdoms. That means the completed peach-garden setting, vows and familiar symbolism should be read as literary and performance tradition, not as something this hall independently proves happened. The novel is a major cultural work, not a disguised excavation report.",
    },
    {
      id: "sanyi-p2",
      type: "paragraph",
      text: "The building adds another layer. The museum says Sanyi Temple began as a Qing memorial elsewhere in Chengdu and was moved into this complex in 1998. Its presence therefore tells you how strongly the brotherhood narrative shaped later commemoration and how a modern museum assembled a more complete Three Kingdoms visitor story. Look for the relocation record if accessible. A moved historic memorial can be genuine evidence of Qing and modern memory without becoming the actual site of a third-century oath.",
    },
    {
      id: "sanyi-table",
      type: "table",
      caption: "The Sanyi stop in four layers",
      columns: ["Layer", "What belongs here"],
      rows: [
        ["History", "Liu Bei, Guan Yu and Zhang Fei as historical people"],
        ["Literature", "The fully staged Peach Garden Oath and much of its familiar dialogue and symbolism"],
        ["Memorial history", "A Qing temple dedicated to the trio and the images chosen for it"],
        ["Tourism presentation", "Its 1998 relocation into a museum route that gathers several kinds of Three Kingdoms memory"],
      ],
    },
    {
      id: "huiling-heading",
      type: "heading",
      level: 2,
      text: "How should you read Huiling without claiming too much?",
    },
    {
      id: "huiling-p1",
      type: "paragraph",
      text: "Huiling is the point where the route comes closest to a third-century event. The museum quotes the Records of the Three Kingdoms: Liu Bei died at Yong’an in 223, his coffin returned to Chengdu, and he was buried at Huiling in the eighth month. The official site identifies the mound here as Huiling and describes later gates, a spirit way and a resting hall around it. That gives you a historical burial statement joined to a long-maintained place identity.",
    },
    {
      id: "huiling-p2",
      type: "paragraph",
      text: "Keep the conclusion at that level. The reviewed museum sources do not say that tourists are looking into an excavated chamber, that grave goods have confirmed every tradition or that each brick, wall and gate survives from 223. A burial place can retain powerful continuity while its approach, enclosure, inscription and repaired fabric belong to later protection. Look for the mound form, the 惠陵 or imperial-tomb labels and the relationship to the shrine axis; do not search for an exposed tomb interior.",
    },
    {
      id: "huiling-test",
      type: "callout",
      title: "Use a three-part sentence",
      tone: "neutral",
      body: "‘A historical text says Liu Bei was buried at Huiling; the institution identifies this maintained mound as that place; the visible surrounding fabric has its own later history.’ That sentence respects the record, the site tradition and the material limit at once.",
    },
    {
      id: "jinli-heading",
      type: "heading",
      level: 2,
      text: "Where does Jinli fit—and where does it not?",
    },
    {
      id: "jinli-p1",
      type: "paragraph",
      text: "Jinli belongs after the evidence route, not before it. The museum describes it as a modern folk-culture zone built in an antique style informed by late Qing and early Republican Sichuan vernacular architecture. It was developed as the complex expanded in the late twentieth and early twenty-first centuries. Food, shops, lighting and performance can show how Chengdu packages regional identity for present visitors. They do not reconstruct a documented Shu-Han market street.",
    },
    {
      id: "jinli-p2",
      type: "paragraph",
      text: "That distinction is not a reason to skip Jinli. It is a reason to use it honestly. Visit if your group wants an accessible social finish, snacks or evening atmosphere; skip it if crowds and commercial display are not your purpose. Do not use an antique-looking doorway, costume or menu as evidence for Liu Bei’s Chengdu. If you have only one concentrated hour, spend it in the heritage zone and treat Jinli as optional rather than letting it consume the time needed for the stele and Huiling.",
    },
    {
      id: "route-heading",
      type: "heading",
      level: 2,
      text: "Which Wuhou Shrine route fits your actual attention?",
    },
    {
      id: "route-table",
      type: "table",
      caption: "Choose by question, not by a promised number of minutes",
      columns: ["Traveller", "Keep", "Cut first"],
      rows: [
        ["No Three Kingdoms background", "Gate-name clue, Tang stele, one corridor label, Liu Bei/Zhuge hall contrast, Huiling and the permanent exhibition when open", "Detailed character-by-character statue study and Jinli"],
        ["Novel or game fan", "The same six-stop spine, with extra notes at Sanyi Temple on which memories come from literature", "Trying to ‘confirm’ every favourite episode in a statue or souvenir"],
        ["History-focused visitor", "Stele makers/date, Ming consolidation, Qing hall hierarchy, statue dates, Huiling evidence boundary and relocation record", "Unlabelled themed displays and temporary entertainment"],
        ["Family or mixed-interest group", "Give each person one task: find the two gate names, one dated object, one later costume clue and one modern element", "A long lecture before anyone has found the physical clues"],
        ["Visitor with limited mobility", "Travel with the companion required by the current rules; contact the museum before booking for a feasible entrance, name two essential stops and accept a partial axis", "Assuming the published route is continuously step-free"],
      ],
    },
    {
      id: "route-p1",
      type: "paragraph",
      text: "This guide follows the museum’s published forward order through the core: Han Zhaolie Temple → Tang stele → Liu Bei Hall and corridors → Zhuge Liang Hall → Sanyi Temple → Huiling, with the exhibition room after the red-wall path when open. The official reverse route approaches Huiling first, then Sanyi Temple, Zhuge Liang Hall and Liu Bei Hall before returning toward the Tang stele. Use only a direction shown on the current map and permitted by staff; do not splice the two into a route that backtracks. Before entering, save the official map and write down two non-negotiable stops. If a closure breaks the route, keep the conceptual order in your notes: name → dated memorial → spatial hierarchy → literary memory → burial claim → modern presentation.",
    },
    {
      id: "operations-heading",
      type: "heading",
      level: 2,
      text: "What should you verify on the day—and how do you recover?",
    },
    {
      id: "operations-p1",
      type: "paragraph",
      text: "Check the museum’s official homepage, ticket page and same-day notices rather than copying a blog’s timetable. On 4 September 2026, the homepage and ticket page displayed different opening and last-entry times, and both warned that seasonal or special-event hours can change. If a same-day notice does not settle the conflict, contact the ticket office through the current official ticket page; do not plan around the later cutoff, and reschedule or skip the stop if you cannot confirm enough time. The ticket page explicitly says foreign visitors may make a real-name reservation with a passport. Carry the original passport and follow the verification instructions on the completed order. This guide did not test every passport format or payment completion. If the official system fails, save the error and ask the staffed service window. Use only the museum website, official account or service window for admission and interpretation services.",
    },
    {
      id: "operations-table",
      type: "table",
      caption: "Five failures that do not have to ruin the visit",
      columns: ["Failure", "Immediate recovery", "Evidence boundary"],
      rows: [
        ["Online booking rejects a passport", "Keep the error screen, bring the original passport and ask the museum service window about current full-price admission", "The official policy accepts passports; this recovery covers a system or payment failure and cannot promise a walk-up ticket"],
        ["Tang stele or a hall is closed", "Use the museum label/map to record its date and role, then continue to the next layer rather than substituting an unlabelled stone", "A photo online is a study aid, not proof of what was on display that day"],
        ["Labels are only partly understood", "Use the object’s Chinese name and date; verify an official audio device or live interpretation at the service point", "Automatic translation can assist navigation but should not invent a historical claim"],
        ["Crowds block the main axis", "If staff permit, use the official reverse route from Huiling through Sanyi Temple, Zhuge Liang Hall and Liu Bei Hall rather than improvising a cross-cut", "Do not cross barriers or treat a distant glimpse as a material inspection"],
        ["Steps interrupt a mobility plan", "Travel with a companion as the rules require, contact visitor service before booking and substitute official interpretation for inaccessible interiors", "The rules acknowledge steps and slopes; this review found no verified continuous step-free route"],
      ],
    },
    {
      id: "photo-callout",
      type: "callout",
      title: "Personal photos are not a site-wide promise",
      tone: "warning",
      body: "The current rules explicitly ban unapproved commercial shooting and livestream selling and forbid touching or climbing on heritage. They do not amount to blanket permission for personal photography in every room. Read the sign at each doorway, follow staff instructions, keep away from barriers and never use a photograph of a statue as a verified likeness. Ask: ‘这里可以拍照吗？不用闪光灯。’—‘May I take a photo here? I will not use flash.’",
    },
    {
      id: "phrase-table",
      type: "table",
      caption: "A compact Chinese field card",
      columns: ["Need", "Show or say", "Meaning"],
      rows: [
        ["Find the Tang stele", "请问唐碑（三绝碑）在哪里？", "Where is the Tang stele (the Three-Success Stele)?"],
        ["Check Huiling access", "今天惠陵可以参观吗？", "Can Huiling be visited today?"],
        ["Ask about an object date", "这是哪个年代的建筑／塑像？", "What period is this building/statue from?"],
        ["Passport help", "我用外国护照，应该在哪里购票和验票？", "I use a foreign passport. Where should I buy and validate admission?"],
        ["Accessibility", "请问轮椅可以走哪条路线？", "Which route can a wheelchair use?"],
        ["Photography", "这里可以拍照吗？不用闪光灯。", "May I take a photo here? I will not use flash."],
      ],
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "Who should visit Wuhou Shrine—and who can skip it?",
    },
    {
      id: "decision-table",
      type: "table",
      caption: "A final visit, shorten or skip decision",
      columns: ["You want", "Decision", "Reason"],
      rows: [
        ["To understand how Chengdu remembered Liu Bei and Zhuge Liang across centuries", "Visit and use the full evidence route", "The site’s strongest object is not one ancient building but the relationship among burial memory, inscriptions and later halls"],
        ["A first bridge between history and a beloved novel/game", "Visit, but label every stop before matching characters", "The site rewards prior enthusiasm when literary scenes are not used as proof"],
        ["Only an excavated Three Kingdoms city or untouched third-century architecture", "Skip or change expectations", "The complex is a long-lived memorial and museum, not that archaeological product"],
        ["A relaxed group finish after the heritage route", "Add Jinli as a separate modern layer", "It solves a social/food task without being mislabelled as Shu-Han street evidence"],
        ["Very limited time and no interest in inscriptions, memory or Three Kingdoms reception", "Skip without guilt", "A generic garden walk will not justify the stop for every traveller"],
      ],
    },
    {
      id: "decision-p1",
      type: "paragraph",
      text: "The most useful souvenir is a six-line record: what the object is called, when its current form or inscription dates from, who made or moved it, which person or story it remembers, what layer the claim belongs to, and what it cannot prove. That method turns Wuhou Shrine from a row of names into a readable argument about political hierarchy, affection and cultural memory. For a broader material-evidence method, use Homeground’s archaeological-site museum guide; for living stage interpretation, keep the separate Sichuan opera guide. Neither should be folded into this one shrine visit.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue the Chengdu and evidence route",
      items: [
        {
          label: "Visit an archaeological site museum without confusing reconstruction and evidence",
          href: "/guides/how-to-visit-an-archaeological-site-museum/",
          description: "Use a broader object–context–inference method at excavated sites; Wuhou Shrine remains a different memorial task.",
        },
        {
          label: "Choose a first Sichuan opera performance beyond face-changing",
          href: "/guides/sichuan-opera-face-changing-with-context/",
          description: "Separate theatrical form, programme context and tourist packaging in a living performance setting.",
        },
        {
          label: "Choose the order of Beijing, Xi’an and Chengdu",
          href: "/guides/beijing-xian-chengdu-route-order/",
          description: "Place Chengdu in the wider trip after deciding what this single cultural stop can deliver.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources",
      items: [
        {
          label: "About Wuhou Shrine and its historical changes",
          url: "https://wuhouci.net.cn/about",
          publisher: "Chengdu Wuhou Shrine Museum",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Official Wuhou Shrine survey and heritage database record",
          url: "https://www.wuhouci.net.cn/ycdc_list_Detail?id=665250334087581696",
          publisher: "Chengdu Wuhou Shrine Museum",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Official visitor map and route",
          url: "https://en.wuhouci.net.cn/map",
          publisher: "Chengdu Wuhou Shrine Museum",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Official ticket information",
          url: "https://wuhouci.net.cn/pwxx",
          publisher: "Chengdu Wuhou Shrine Museum",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Official visitor and photography-related rules",
          url: "https://wuhouci.net.cn/cgxz",
          publisher: "Chengdu Wuhou Shrine Museum",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Academic overview of Romance of the Three Kingdoms as historical fiction",
          url: "https://rkyfz.pku.edu.cn/article/info?aid=271016275",
          publisher: "Peking University journal archive",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Guan Yu worship and later popular-literary tradition",
          url: "https://crlhd.xmu.edu.cn/info/1037/4807.htm",
          publisher: "Xiamen University Centre for Research on Local Historical Documents",
          reviewedAt: "2026-09-04",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
