import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const en = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "At Guangzhou's Chen Clan Academy, the first exhibition is above the entrance. Roof ridges carry ceramic figures; gables and walls hold lime and brick work; beams, doors, stone bases, metal components and painted surfaces continue the argument inside. The building began as a shared Chen-lineage institution in the early 1890s and became the Guangdong Folk Arts Museum in 1959. Read those two functions separately, then use seven crafts to move from façade to gallery." },
    { id: "answer", type: "callout", title: "The direct answer", body: "Look up before entering. Identify ceramic sculpture, lime sculpture, woodcarving, brick carving, stone carving, metal casting and painting by material and location—not by guessing the story. The architecture is the stable core; rotating folk-arts exhibitions are a later museum layer. Current scaffolding or a closed gallery should change your route, not your identification standards.", tone: "decision" },
    { id: "institution-h", type: "heading", level: 2, text: "What was the Chen Clan Academy before it was a museum?" },
    { id: "institution-p1", type: "paragraph", text: "The complex, also called the Chen Clan Ancestral Hall or Chen Clan Academy (陈家祠 / 陈氏书院), was built as a collective institution for Chen lineages in Guangdong. It combined ancestral, educational, lodging and organisational functions rather than serving as one nuclear family's house. Guangzhou institutions phrase completion as 1893 or 1894, so this page uses “completed in the early 1890s” and records the source difference." },
    { id: "institution-p2", type: "paragraph", text: "Since 1959 it has housed the Guangdong Folk Arts Museum. That museum role preserves and interprets the building while adding collections, labels and temporary exhibitions that were not part of its original programme. A display case of contemporary craft can be excellent, but it does not prove that the same object stood in the academy in the nineteenth century." },
    { id: "seven-h", type: "heading", level: 2, text: "Use material first: seven crafts at a glance" },
    { id: "seven-table", type: "table", caption: "Material, likely location and verification", columns: ["Craft", "Where to look", "How not to confuse it"], rows: [["Woodcarving 木雕", "Doors, screens, beams and brackets", "Check grain/joinery and label; dark paint alone is not wood"], ["Brick carving 砖雕", "Wall panels and gable surfaces", "Relief is cut into/assembled from brick, not grey-painted plaster"], ["Stone carving 石雕", "Column bases, railings, steps and structural ornaments", "Weight and structural position help, but label decides"], ["Ceramic sculpture 陶塑", "Roof ridges and high figural groups", "Fired ceramic pieces often retain glazed colour; do not call all roof art lime"], ["Lime sculpture 灰塑", "Gables, ridges and wall-top relief", "Built in lime/plaster technique and painted; not a fired ceramic object"], ["Metal casting 铜铁铸", "Railings, panels and functional/decorative fittings", "Do not infer alloy or date from colour/rust"], ["Painting 彩绘", "Beams, panels and architectural surfaces", "Distinguish painted decoration from a removable museum painting"]] },
    { id: "roof-h", type: "heading", level: 2, text: "Start across the courtyard, where the roof becomes readable" },
    { id: "roof-p1", type: "paragraph", text: "Stand far enough back to separate the roof planes, ridge figures, gable edges and wall relief. Use a telephoto lens only where photography rules permit; never step into planted areas or block a doorway for a straight-on shot. Match one figure group to a museum label before naming its material or story." },
    { id: "roof-p2", type: "paragraph", text: "Ridge scenes may draw on historical tales, opera, literature, auspicious imagery or craft convention. A depicted general did not therefore visit this academy, and a scene is not evidence that one version of a legend is historical fact. Caption “ceramic ridge group depicting…” or “museum identifies the motif as…” rather than narrating an unverified story." },
    { id: "lime-h", type: "heading", level: 2, text: "Ceramic and lime sculpture are the test most visitors fail" },
    { id: "lime-p1", type: "paragraph", text: "Ceramic sculpture is fired material assembled into architectural decoration, often with glazed colour and distinct pieces. Lime sculpture is modelled in a lime-based material on the building, then detailed and painted. Both can occupy high, colourful positions and both receive repair, so colour alone is unreliable." },
    { id: "lime-p2", type: "paragraph", text: "Choose one labelled example of each. Record exact location, support and conservation note. When a repaired area is visible, do not call brighter colour “new fake work” or darker colour “original.” Conservators may clean, consolidate, replace lost support or reintegrate colour; the project record is the evidence." },
    { id: "low-h", type: "heading", level: 2, text: "At eye level, compare how materials solve different jobs" },
    { id: "low-list", type: "list", ordered: true, items: ["Wood: follow the carved scene into joints, doors or structural brackets; ask whether it is load-bearing, screen or applied panel.", "Brick: look at how relief emerges from a wall and how seams or modules are handled.", "Stone: find a base, railing or step where durability and structure matter, not only imagery.", "Metal: identify function—barrier, fitting, panel or ornament—before naming technique or alloy.", "Painting: locate colour on the architecture and distinguish historic layer, restored scheme and current retouching through labels."] },
    { id: "stories-h", type: "heading", level: 2, text: "How to read stories without turning decoration into a history book" },
    { id: "stories-p1", type: "paragraph", text: "Architectural images communicated recognition, values, humour and virtuosity to viewers familiar with their conventions. Today, identification often depends on attributes, inscriptions, sequence and museum research. If you recognise only a character, leave the narrative open. A wrong confident caption is worse than “unidentified narrative figure group on the east ridge.”" },
    { id: "stories-p2", type: "paragraph", text: "Separate four layers in your notes: the older story or historical person represented; the nineteenth-century choice to depict it; the surviving/repaired material now visible; and the museum's current explanation. A scene can be literature or folklore while the craft object carrying it is historical fabric." },
    { id: "museum-h", type: "heading", level: 2, text: "Enter the galleries only after the building has given you a vocabulary" },
    { id: "museum-p1", type: "paragraph", text: "The Guangdong Folk Arts Museum can place portable objects beside the building crafts: carving, embroidery, ceramics or other regional arts depending on the current programme. Use comparison carefully. A small carved object may demonstrate a technique, but scale, tool access and structural purpose differ from architectural carving." },
    { id: "museum-p2", type: "paragraph", text: "Check whether an exhibition is permanent, temporary or borrowed. Photography permission and reproduction rights can vary by object. If a gallery is closed, the architecture still delivers the core article; do not substitute an unlabelled souvenir shop item as evidence." },
    { id: "route-h", type: "heading", level: 2, text: "A seven-craft route that survives scaffolding" },
    { id: "route-table", type: "table", caption: "Work from high and public to close and labelled", columns: ["Stage", "Target", "Recovery"], rows: [["Forecourt", "Overall roof and ceramic/lime locations", "Use another courtyard if one elevation is scaffolded"], ["Main entrance", "Stone base + wood/metal threshold", "Read from the side without blocking flow"], ["First courtyard", "One labelled ceramic and one lime example", "Use museum diagram if too high or covered"], ["Covered hall", "Wood, brick and painted surface", "Select an adjacent bay with a label"], ["Interior threshold", "Metal casting and structural stone", "Do not infer alloy/date"], ["Gallery", "One portable craft comparison", "Skip if closed; architecture remains primary"], ["Exit review", "Seven materials, seven exact locations", "Leave unidentified categories blank"]] },
    { id: "misread-h", type: "heading", level: 2, text: "Five things the façade cannot prove" },
    { id: "misread-list", type: "list", ordered: false, items: ["That every component has remained unchanged since the early 1890s.", "That every roof figure is ceramic rather than lime sculpture.", "That a depicted literary or legendary event occurred at the academy.", "That current museum objects belonged to the original institution.", "That one decorative style represents all Guangdong buildings or all Chen families."] },
    { id: "who-h", type: "heading", level: 2, text: "Who should prioritise Chen Clan Academy?" },
    { id: "who-p", type: "paragraph", text: "Prioritise it if architectural detail, craft process or the transformation of a clan institution into a museum interests you. It works even on a shorter visit if you identify three crafts accurately rather than photograph twenty unidentified scenes. Travelers wanting a complete Guangzhou itinerary or a single “old house” may need another guide. Recheck the museum for booking, access, scaffolding, exhibition and photography rules." },
    { id: "links", type: "internal-links", title: "Continue understanding Guangzhou and heritage", items: [{ label: "Understand how Guangzhou morning tea works", href: "/guides/how-guangzhou-morning-tea-works/", description: "Move from building craft to another place-specific cultural system." }, { label: "Read heritage interventions in China", href: "/guides/how-to-read-heritage-sites-in-china/", description: "Judge conserved and replaced architectural components precisely." }, { label: "Read dougong and Chinese timber frames", href: "/guides/dougong-and-chinese-timber-frame-reading/", description: "Carry material-first looking from decoration into structural joinery." }, { label: "See Foshan lion dance as a first audience", href: "/guides/foshan-lion-dance-first-performance-workflow/", description: "Continue into a nearby Guangdong craft-and-performance tradition." }, { label: "Order Guangzhou, Shenzhen and Hong Kong", href: "/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "Place the museum inside a practical Pearl River Delta route." }] },
    { id: "sources", type: "sources", title: "Core museum and government sources reviewed", items: [{ label: "Guangdong Folk Arts Museum", url: "https://www.gzcjc.com.cn/", publisher: "Guangdong Folk Arts Museum", reviewedAt: "2026-08-20" }, { label: "Guangzhou museum introduction", url: "https://www.gz.gov.cn/zlgz/gzly/wzgz/wbcg/content/mpost_9587900.html", publisher: "Guangzhou Municipal Government", reviewedAt: "2026-08-20" }, { label: "Guangdong museum entry", url: "https://whly.gd.gov.cn/service_newwwbwg/content/post_2843831.html", publisher: "Department of Culture and Tourism of Guangdong", reviewedAt: "2026-08-20" }, { label: "Museum story on seven building crafts", url: "https://www.gzcjc.com.cn/MYwebsite/rc/sjguanzhigushi.htm", publisher: "Guangdong Folk Arts Museum", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

const zh = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "在广州陈家祠，第一场展览其实在入口上方。屋脊有陶塑人物，山墙和墙面有灰塑、砖雕，进入后木构、门窗、石础、金属构件和彩绘继续展开。建筑在1890年代初作为陈氏共享机构建成，1959年成为广东民间工艺博物馆。先分开这两层功能，再用七种工艺从立面走到展厅。" },
    { id: "answer", type: "callout", title: "直接答案", body: "进门前先抬头。按材料和位置辨认陶塑、灰塑、木雕、砖雕、石雕、铜铁铸和彩绘，不凭故事猜工艺。建筑是稳定核心，轮换民间工艺展是后来的博物馆层。脚手架或闭室只应改变路线，不能降低辨认标准。", tone: "decision" },
    { id: "institution-h", type: "heading", level: 2, text: "成为博物馆前，陈氏书院是什么？" },
    { id: "institution-p1", type: "paragraph", text: "陈家祠又称陈氏书院，是广东陈氏宗族共同建设的机构，兼有祭祖、教育、寄寓和组织等功能，不是一户小家庭的住宅。广州不同官方摘要分别使用1893和1894年竣工口径，因此本文写“1890年代初建成”，把年份差异留在来源日志。" },
    { id: "institution-p2", type: "paragraph", text: "1959年后，这里成为广东民间工艺博物馆。博物馆保护、解释建筑，也加入原功能没有的收藏、标签和临展。当代工艺展品可以非常重要，却不能证明同一件物品在十九世纪就摆在书院里。" },
    { id: "seven-h", type: "heading", level: 2, text: "材料优先：七种工艺速查" },
    { id: "seven-table", type: "table", caption: "材料、位置和辨认边界", columns: ["工艺", "到哪里找", "怎样不混淆"], rows: [["木雕", "门、屏、梁架与斗拱", "看木纹、接榫和标签；深色不自动等于木"], ["砖雕", "墙面、山墙浮雕", "从砖材雕成或拼装，不是涂灰的塑层"], ["石雕", "柱础、栏杆、台阶与结构装饰", "重量和位置可提示，仍由标签确认"], ["陶塑", "屋脊和高处人物群", "烧成陶件常有釉彩；不能把全部屋顶装饰叫灰塑"], ["灰塑", "山墙、屋脊和墙顶浮雕", "以灰泥类材料塑成、施彩，不是烧成陶器"], ["铜铁铸", "栏杆、板件和功能/装饰配件", "不能凭锈色判断合金与年代"], ["彩绘", "梁枋、板面和建筑表面", "分开建筑彩绘与可移动绘画展品"]] },
    { id: "roof-h", type: "heading", level: 2, text: "从院落对面开始，让屋顶变得可读" },
    { id: "roof-p1", type: "paragraph", text: "退到能分清屋面、脊饰、山墙边缘和墙面浮雕的位置。摄影规则允许时再用长焦，不踩绿地，也不为正面构图堵门。命名材料和故事前，至少把一组人物与馆方标签对应。" },
    { id: "roof-p2", type: "paragraph", text: "屋脊场景可能来自历史故事、戏曲、文学、吉祥图像或工艺惯例。画了某位将军，不等于他到过陈氏书院；场景也不能证明某个传说版本为历史事实。图片说明写“陶塑屋脊人物群”或“馆方识别为……题材”，不补无来源剧情。" },
    { id: "lime-h", type: "heading", level: 2, text: "陶塑与灰塑，是最容易答错的一题" },
    { id: "lime-p1", type: "paragraph", text: "陶塑是烧制后组合进建筑的陶质装饰，常保留釉彩和分件；灰塑以石灰类材料在建筑上塑造，再细修施彩。两者都可能位置高、颜色丰富，也都会维修，所以只看颜色不可靠。" },
    { id: "lime-p2", type: "paragraph", text: "各选一处有标签实例，记录准确位置、承托方式和保护说明。修过区域较亮，不能直接说“新做假货”；颜色较暗，也不自动是原物。保护可能包括清洁、加固、补支撑或协调色彩，工程记录才是依据。" },
    { id: "low-h", type: "heading", level: 2, text: "到视线高度，比较材料怎样解决不同工作" },
    { id: "low-list", type: "list", ordered: true, items: ["木：从雕刻图像追到榫接、门扇或斗拱，问它承重、隔断还是贴附。", "砖：看浮雕怎样从墙面形成，接缝和模块怎样处理。", "石：找柱础、栏杆或台阶，观察耐久与结构，而不只看图像。", "金属：先确定栏杆、配件、板件或装饰功能，再谈技法与合金。", "彩绘：找到建筑表面的颜色，依标签分清历史层、恢复方案和当前补绘。"] },
    { id: "stories-h", type: "heading", level: 2, text: "怎样读故事，又不把装饰当历史书？" },
    { id: "stories-p1", type: "paragraph", text: "建筑图像会向熟悉典故的观众传递身份、价值、幽默和技艺。今天辨认往往依靠人物属性、题字、连续场景和馆方研究。只认出一个角色时，应保留故事未知。自信写错，不如“东侧屋脊未确认题材人物群”。" },
    { id: "stories-p2", type: "paragraph", text: "笔记分四层：被表现的旧故事或历史人物；十九世纪为何选择它；今天可见的原存/维修材料；博物馆当前解释。场景可以属于文学或传说，承载它的工艺构件却是历史物质。" },
    { id: "museum-h", type: "heading", level: 2, text: "建筑先给你词汇，再进入展厅" },
    { id: "museum-p1", type: "paragraph", text: "广东民间工艺博物馆会依当期安排，把雕刻、刺绣、陶瓷等可移动工艺品与建筑工艺并置。比较时要注意尺度、工具接近方式和结构用途不同；一件小木雕只能示范部分技法。" },
    { id: "museum-p2", type: "paragraph", text: "确认展览是常设、临时还是借展，摄影和公开使用权也可能逐件不同。展厅关闭时，建筑仍能完成本文核心；不要用无标签纪念品补证据。" },
    { id: "route-h", type: "heading", level: 2, text: "遇到脚手架也能完成的七工艺路线" },
    { id: "route-table", type: "table", caption: "从高处公共视野走向近处标签", columns: ["阶段", "目标", "恢复"], rows: [["前院", "整体屋顶与陶/灰塑位置", "一侧有架就换另一院落"], ["正门", "石础+木/金属门槛", "侧读，不堵人流"], ["第一院", "一处有标签陶塑和灰塑", "过高或遮挡时用馆方图"], ["厅廊", "木、砖与彩绘", "换相邻有标签开间"], ["室内门槛", "金属铸件与结构石", "不猜合金/年代"], ["展厅", "一件可移动工艺比较", "关闭就跳过，建筑为主"], ["出口", "七种材料、七处位置", "未确认类别留空"]] },
    { id: "misread-h", type: "heading", level: 2, text: "一张立面不能证明五件事" },
    { id: "misread-list", type: "list", ordered: false, items: ["所有构件从1890年代初至今未变。", "屋顶人物全是陶塑而非灰塑。", "表现的文学、传说事件发生在书院。", "今天展品原属书院。", "一种装饰代表所有广东建筑或所有陈氏家庭。"] },
    { id: "who-h", type: "heading", level: 2, text: "谁应该优先看陈家祠？" },
    { id: "who-p", type: "paragraph", text: "喜欢建筑细节、工艺过程，或宗族机构怎样变成博物馆的人应优先。短时间也可以，只要准确辨认三种工艺，不求拍二十组不知名故事。若需要完整广州行程或单一“老宅”，应看其他指南。预约、开放、脚手架、展览和摄影以馆方为准。" },
    { id: "links", type: "internal-links", title: "继续理解广州与遗产", items: [{ label: "广州早茶是怎样运作的", href: "/zh/guides/how-guangzhou-morning-tea-works/", description: "从建筑工艺转向另一套地点专属文化系统。" }, { label: "看懂中国遗产干预", href: "/zh/guides/how-to-read-heritage-sites-in-china/", description: "精确判断保护与替换的建筑构件。" }, { label: "读懂斗拱与中国木构", href: "/zh/guides/dougong-and-chinese-timber-frame-reading/", description: "把材料优先的观察法从装饰延伸到结构连接。" }, { label: "第一次怎么看佛山醒狮", href: "/zh/guides/foshan-lion-dance-first-performance-workflow/", description: "继续理解珠三角另一项工艺与表演传统。" }, { label: "安排广州、深圳与香港顺序", href: "/zh/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "把这座博物馆放进可执行的珠三角路线。" }] },
    { id: "sources", type: "sources", title: "已核对的博物馆与政府来源", items: [{ label: "广东民间工艺博物馆", url: "https://www.gzcjc.com.cn/", publisher: "广东民间工艺博物馆", reviewedAt: "2026-08-20" }, { label: "广州市陈家祠介绍", url: "https://www.gz.gov.cn/zlgz/gzly/wzgz/wbcg/content/mpost_9587900.html", publisher: "广州市人民政府", reviewedAt: "2026-08-20" }, { label: "广东省博物馆名录条目", url: "https://whly.gd.gov.cn/service_newwwbwg/content/post_2843831.html", publisher: "广东省文化和旅游厅", reviewedAt: "2026-08-20" }, { label: "馆方七种建筑工艺资料", url: "https://www.gzcjc.com.cn/MYwebsite/rc/sjguanzhigushi.htm", publisher: "广东民间工艺博物馆", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

const ko = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "광저우 천자츠의 첫 전시는 입구 위에 있습니다. 용마루에는 도소 인물이 있고 박공·벽에는 회소·전조가 있으며 안쪽 목구조·문·석초·금속·채색이 이어집니다. 건물은 1890년대 초 천씨 공동 기관으로 시작해 1959년 광둥민간공예박물관이 됐습니다. 두 기능을 나누고 일곱 공예로 정면에서 전시실까지 걸으세요." },
    { id: "answer", type: "callout", title: "바로 답하면", body: "들어가기 전에 위를 보세요. 도소·회소·목조·전조·석조·금속 주조·채색을 이야기 추측이 아니라 재료와 위치로 확인합니다. 건축이 안정된 핵심이고 교체 전시는 후대 박물관 층입니다. 비계·폐실은 동선을 바꿀 뿐 식별 기준을 낮추지 않습니다.", tone: "decision" },
    { id: "institution-h", type: "heading", level: 2, text: "박물관 이전 천씨서원은 무엇이었을까요?" },
    { id: "institution-p1", type: "paragraph", text: "천자츠/천씨서원(陈家祠·陈氏书院)은 광둥 천씨 계통의 공동 기관으로 제향·교육·숙박·조직 기능을 결합했으며 한 핵가족 집이 아니었습니다. 광저우 기관 요약에 1893·1894가 달라 본문은 ‘1890년대 초 완공’으로 쓰고 차이는 출처 로그에 남깁니다." },
    { id: "institution-p2", type: "paragraph", text: "1959년부터 광둥민간공예박물관입니다. 건물을 보존·해석하며 원래 프로그램에 없던 수장품·라벨·특별전을 더했습니다. 현대 공예품은 훌륭해도 19세기 서원에 놓였다는 증거는 아닙니다." },
    { id: "seven-h", type: "heading", level: 2, text: "재료 먼저: 일곱 공예" },
    { id: "seven-table", type: "table", caption: "재료·위치·구분", columns: ["공예", "볼 곳", "혼동 방지"], rows: [["목조", "문·병풍·들보·공포", "나뭇결·이음·라벨; 어둡다고 목재는 아님"], ["전조", "벽·박공 부조", "벽돌을 새기거나 조립; 회색 칠 회반죽과 다름"], ["석조", "주초·난간·계단·구조 장식", "무게·위치는 단서, 라벨이 결정"], ["도소", "용마루·높은 인물군", "구운 도편·유약색; 지붕 전체를 회소라 하지 않기"], ["회소", "박공·용마루·벽상부 부조", "석회계 재료를 빚어 채색, 구운 도기가 아님"], ["동철 주조", "난간·패널·기능/장식 철물", "색·녹으로 합금·연대 추정 금지"], ["채색", "들보·판·건축 표면", "이동 가능한 회화 전시와 분리"]] },
    { id: "roof-h", type: "heading", level: 2, text: "중정 맞은편에서 지붕을 읽으세요" },
    { id: "roof-p1", type: "paragraph", text: "지붕면·용마루 인물·박공 가장자리·벽 부조가 갈라져 보이게 물러납니다. 허용될 때만 망원을 쓰고 화단에 들어가거나 문을 막지 않습니다. 재료·이야기 이름 전에 한 인물군을 박물관 라벨과 맞춥니다." },
    { id: "roof-p2", type: "paragraph", text: "용마루 장면은 역사 이야기·희곡·문학·길상·공예 관습에서 올 수 있습니다. 장군이 그려졌다고 서원에 왔다는 뜻이 아니며 전설의 역사성을 증명하지 않습니다. ‘도소 용마루 인물군’ 또는 ‘박물관이 ○○ 모티프로 식별’이라고 쓰세요." },
    { id: "lime-h", type: "heading", level: 2, text: "도소와 회소가 가장 어려운 시험입니다" },
    { id: "lime-p1", type: "paragraph", text: "도소는 구워 건축에 조립한 도질 장식으로 유약색과 분리 부재가 흔합니다. 회소는 석회계 재료를 건물 위에서 빚고 세부·채색합니다. 둘 다 높고 화려하며 보수되므로 색만으로 판단하지 않습니다." },
    { id: "lime-p2", type: "paragraph", text: "라벨 있는 예를 하나씩 골라 정확한 위치·지지·보존 설명을 기록하세요. 밝은 보수부를 ‘새 가짜’, 어두운 부분을 ‘원형’이라 부르지 않습니다. 세척·강화·지지 보충·색 조정은 기록이 판단합니다." },
    { id: "low-h", type: "heading", level: 2, text: "눈높이에서는 재료가 다른 일을 푸는 방식을 비교하세요" },
    { id: "low-list", type: "list", ordered: true, items: ["목재: 조각 장면에서 이음·문·공포로 따라가며 구조·칸막이·부착 패널인지 묻습니다.", "벽돌: 부조가 벽에서 나오고 이음·모듈을 처리한 방식을 봅니다.", "돌: 주초·난간·계단에서 이미지뿐 아니라 내구·구조를 봅니다.", "금속: 기법·합금 전에 난간·철물·패널·장식 기능을 확인합니다.", "채색: 건축 표면의 색을 찾아 역사층·복원안·현재 보채를 라벨로 나눕니다."] },
    { id: "stories-h", type: "heading", level: 2, text: "장식을 역사책으로 만들지 않고 이야기 읽기" },
    { id: "stories-p1", type: "paragraph", text: "건축 이미지는 관습을 아는 관객에게 정체성·가치·유머·기량을 전했습니다. 오늘 식별은 지물·글자·연속 장면·박물관 연구에 의존합니다. 인물 하나만 알면 서사를 열어 두세요. 틀린 자신감보다 ‘동쪽 용마루 미확인 서사 인물군’이 낫습니다." },
    { id: "stories-p2", type: "paragraph", text: "메모를 네 층으로 나눕니다. 표현된 옛 이야기/인물, 19세기 선택, 오늘 보이는 잔존/보수 재료, 현재 박물관 설명입니다. 장면은 문학·전설이어도 이를 담은 공예 부재는 역사 물질일 수 있습니다." },
    { id: "museum-h", type: "heading", level: 2, text: "건물이 어휘를 준 뒤 전시실로 가세요" },
    { id: "museum-p1", type: "paragraph", text: "현재 프로그램에 따라 조각·자수·도자 등 이동 공예를 건축과 비교합니다. 작은 조각은 기법을 보여도 규모·도구 접근·구조 목적이 건축 조각과 다릅니다." },
    { id: "museum-p2", type: "paragraph", text: "상설·특별·대여를 확인하고 촬영·공개 권리는 물건마다 다릅니다. 전시실이 닫혀도 건축으로 핵심을 끝냅니다. 라벨 없는 기념품을 증거로 쓰지 마세요." },
    { id: "route-h", type: "heading", level: 2, text: "비계가 있어도 되는 일곱 공예 동선" },
    { id: "route-table", type: "table", caption: "높고 공개된 곳에서 가까운 라벨로", columns: ["단계", "대상", "대안"], rows: [["앞뜰", "전체 지붕·도소/회소 위치", "한쪽 비계면 다른 중정"], ["정문", "석초+목/금속 문턱", "사람 흐름 막지 않고 옆에서"], ["첫 중정", "라벨 있는 도소·회소 하나씩", "너무 높거나 가려지면 기관 도면"], ["회랑", "목·벽돌·채색", "인접 라벨 개간"], ["내부 문턱", "금속 주조·구조석", "합금·연대 추측 금지"], ["전시실", "이동 공예 하나 비교", "폐쇄면 생략, 건축 우선"], ["출구", "일곱 재료·일곱 정확한 위치", "미확인 칸 비우기"]] },
    { id: "misread-h", type: "heading", level: 2, text: "정면이 증명하지 못하는 다섯 가지" },
    { id: "misread-list", type: "list", ordered: false, items: ["모든 부재가 1890년대 초부터 그대로라는 것.", "모든 지붕 인물이 회소가 아닌 도소라는 것.", "문학·전설 장면이 서원에서 일어났다는 것.", "현재 전시품이 원래 기관 소유였다는 것.", "한 장식이 광둥 모든 건물·천씨 가문을 대표한다는 것."] },
    { id: "who-h", type: "heading", level: 2, text: "누가 천자츠를 우선해야 할까요?" },
    { id: "who-p", type: "paragraph", text: "건축 세부·공예 과정·문중 기관의 박물관 변화를 좋아하면 우선하세요. 짧아도 세 공예를 정확히 식별하면 됩니다. 광저우 전체 일정·한 채의 ‘옛집’을 원하면 다른 가이드가 필요합니다. 예약·개방·비계·전시·촬영은 박물관을 확인하세요." },
    { id: "links", type: "internal-links", title: "광저우·유산 계속 이해하기", items: [{ label: "광저우 모닝티가 어떻게 운영되는지 이해하기", href: "/ko/guides/how-guangzhou-morning-tea-works/", description: "건축 공예에서 또 다른 장소 고유 문화 체계로 갑니다." }, { label: "중국 유산 개입 읽기", href: "/ko/guides/how-to-read-heritage-sites-in-china/", description: "보존·교체 건축 부재를 정확히 판단합니다." }, { label: "두공과 중국 목구조 읽기", href: "/ko/guides/dougong-and-chinese-timber-frame-reading/", description: "재료 중심 관찰을 장식에서 구조 결구로 넓힙니다." }, { label: "포산 사자춤을 처음 관람하는 법", href: "/ko/guides/foshan-lion-dance-first-performance-workflow/", description: "주장삼각주의 또 다른 공예·공연 전통으로 이어 갑니다." }, { label: "광저우·선전·홍콩 순서 짜기", href: "/ko/guides/guangzhou-shenzhen-hong-kong-route-order/", description: "박물관을 실행 가능한 주장삼각주 일정에 넣습니다." }] },
    { id: "sources", type: "sources", title: "검토한 박물관·정부 자료", items: [{ label: "광둥민간공예박물관", url: "https://www.gzcjc.com.cn/", publisher: "광둥민간공예박물관", reviewedAt: "2026-08-20" }, { label: "광저우시 천자츠 소개", url: "https://www.gz.gov.cn/zlgz/gzly/wzgz/wbcg/content/mpost_9587900.html", publisher: "광저우시 인민정부", reviewedAt: "2026-08-20" }, { label: "광둥성 박물관 항목", url: "https://whly.gd.gov.cn/service_newwwbwg/content/post_2843831.html", publisher: "광둥성 문화여유청", reviewedAt: "2026-08-20" }, { label: "박물관 일곱 건축 공예 자료", url: "https://www.gzcjc.com.cn/MYwebsite/rc/sjguanzhigushi.htm", publisher: "광둥민간공예박물관", reviewedAt: "2026-08-20" }] }
  ]
} satisfies StructuredPageBody;

export const bodies = { en, zh, ko };
