import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "People's Square, the Bund/East Nanjing Road and the area commonly called the Former French Concession all work for a first Shanghai stay, but they optimise different days. The choice is not ‘central or charming’. It is whether the hotel should simplify transport, put one landmark outside the door, or make ordinary mornings and evenings the point of the stay." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose People's Square for the most balanced first-trip transport base and mixed sightseeing. Choose the Bund or East Nanjing Road when skyline walks and central visitor energy are a repeated priority and you accept crowds plus a potentially awkward pedestrian last mile. Choose a precise address in the Former French Concession area when tree-lined streets, cafés and neighbourhood evenings matter more than being beside the Bund—and only after checking the actual station and arrival route." },
  { id: "boundary", type: "paragraph", text: "This page compares three broad bases; it does not rank hotels or claim that all of the Former French Concession is one district. That travel label covers a wide set of streets and several metro stations. A property near Changshu Road behaves differently from one near Xintiandi or Jiaotong University. Always reduce the label to the exact lobby." },
  { id: "matrix", type: "table", caption: "Three good bases, three different gains", columns: ["Base", "What it improves", "What you trade", "Verify"], rows: [["People's Square", "Balanced Lines 1, 2 and 8 access and central flexibility", "Less distinctive doorstep than the river or lane areas", "Correct station exit, road crossing and lobby walk"], ["Bund / East Nanjing Road", "Repeated skyline, pedestrian-street and central visitor evenings", "Crowds, noise and road/pedestrian controls at busy times", "Car drop-off, luggage route and quiet-side room"], ["Former French Concession area", "Neighbourhood walks, cafés and slower mornings/evenings", "The broad label may hide extra transfers", "Exact useful station, night route and airport/rail transfer"]] },
  { id: "trip-fit", type: "table", caption: "Give the hotel to the pattern that repeats", columns: ["Trip pattern", "First base to test", "Deciding check"], rows: [["Three or four nights, first time, mixed classic sights", "People's Square", "Hotel is genuinely close to a usable Line 1/2/8 entrance"], ["Bund sunrise/sunset and East Nanjing Road appear on several days", "Bund / East Nanjing Road", "Room and entrance survive crowd and noise checks"], ["Food, design, cafés and neighbourhood walks are central to the trip", "Precise Former French Concession address", "The exact street and station fit the other fixed days"], ["Older parents, stroller or several cases", "Property with simplest curb-to-room route", "Do not let an area label override step-free access"], ["Late arrival or early departure", "Hotel that protects that transfer", "Actual operating-hour route and staffed arrival"]] },
  { id: "peoples-square", type: "heading", level: 2, text: "People's Square: the balanced transport answer" },
  { id: "peoples-square-copy", type: "paragraph", text: "Shanghai government visitor information identifies People's Square station with Lines 1, 2 and 8, and official metro reporting records it as one of the network's busiest stations. That combination is useful for a first trip, but a large station can add internal walking and the district label extends beyond one entrance. Ask which exit serves the hotel, whether that exit is accessible for the group and how many road crossings remain." },
  { id: "bund", type: "heading", level: 2, text: "Bund and East Nanjing Road: choose the experience, then manage the crowd" },
  { id: "bund-copy", type: "paragraph", text: "This base earns its price when you will use the riverfront and East Nanjing Road early, late or more than once. Official Shanghai reporting shows East Nanjing Road can receive very high weekend passenger flow, and holiday notices sometimes change station operations. That does not make the area a bad base; it means the lobby entrance, road pickup and return route deserve the same attention as the view." },
  { id: "bund-warning", type: "callout", title: "‘Bund view’ and ‘walk to the Bund’ are different products", tone: "warning", body: "A room may face the skyline but sit behind a major road or several blocks inland. Another hotel may have no view but a direct pedestrian route. Decide whether the room view or repeated street access is the goal, then verify it from the exact entrance. Do not pay for both in your imagination." },
  { id: "ffc", type: "heading", level: 2, text: "Former French Concession: make the broad label precise" },
  { id: "ffc-copy", type: "paragraph", text: "The appeal is a different Shanghai rhythm: residential streets, cafés, small shops and evenings that do not depend on reaching the riverfront. But booking platforms use the label broadly. Pin the three places you expect to use there, then select a hotel near a useful station rather than the geometric centre of the label. Check nighttime lighting, footpaths, road pickup and whether the desired street life is still close after returning from sightseeing." },
  { id: "arrival", type: "heading", level: 2, text: "Let the named airport or railway station influence the first and last night" },
  { id: "arrival-copy", type: "paragraph", text: "Use the full terminal or railway-station name and the real hour you will leave it. People's Square may offer a direct line for some journeys, but luggage, long station corridors and operating windows can make a road transfer simpler. Bund hotels may add a pedestrian final approach; a lane-area hotel may add another transfer. Compare the complete terminal-to-lobby journey, not the district's reputation." },
  { id: "last-mile", type: "list", items: ["Get the lobby pin and Chinese road entrance, not only the hotel name.", "Confirm the usable metro exit and whether the whole route is step-free.", "Ask if a pedestrian street, crowd barrier or hotel tower changes the taxi stop.", "Check whether a mall or indoor route closes before your return.", "With large luggage, preserve a road-transfer fallback even when the metro route is direct."] },
  { id: "evenings", type: "heading", level: 2, text: "Choose where a normal evening ends" },
  { id: "evenings-copy", type: "paragraph", text: "One Bund night does not require four nights beside the Bund, and one café morning does not require moving the stay west. Write down the likely end point of every evening. If most nights finish after central sightseeing, People's Square or the Bund cluster may reduce friction. If the evening itself is neighbourhood dining and walking, the lane-area base earns its role. Use repeated behaviour, not the most photogenic hour." },
  { id: "room", type: "table", caption: "Property checks by base", columns: ["Base", "Ask", "Hidden failure"], rows: [["People's Square", "Exact exit, lift route and room exposure", "‘Near station’ but a long underground/road crossing"], ["Bund / East Nanjing Road", "Quiet side, crowd-time entrance and vehicle stop", "View room with severe traffic or nightlife noise"], ["Former French Concession", "Exact station, lift, lane access and current construction", "Charming address with poor luggage and daily transport"], ["Any base", "Staffed passport check-in at actual arrival", "Good location but nobody authorised to admit the group"]] },
  { id: "failure", type: "table", caption: "Recover when Shanghai is busier than expected", columns: ["Problem", "Immediate action", "Better plan"], rows: [["Station exit/operation changes", "Use the official operator notice and another staffed exit", "Road transfer to the lobby"], ["Crowd blocks normal pickup", "Move only to the property's agreed legal meeting point", "Pre-book a clear pickup away from pedestrian controls"], ["Room is too noisy", "Request a verified quiet-side room", "Move after one night if repeated sleep is at risk"], ["Lane route is difficult with bags", "Use the road entrance or luggage support", "Keep first/last night at an accessible base"], ["Area creates daily extra transfers", "Regroup sightseeing by side", "One daytime hotel move if several days remain"]] },
  { id: "registration", type: "paragraph", text: "Hotels register foreign guests. Ask the exact property to confirm staff and passport handling at the actual arrival hour; a famous area does not guarantee an effortless late check-in." },
  { id: "dynamic", type: "paragraph", text: "Shanghai municipal metro and visitor information was reviewed on August 12, 2026. Passenger controls, station operations and property access can change for holidays or events. Recheck the Shanghai Metro channel and the hotel shortly before arrival; no fixed closure or crowd level is assumed here." },
  { id: "stay-quote-handoff", type: "callout", title: "Ask for a human property-fit check", tone: "neutral", body: "For a human comparison of a shortlist, send the travel dates, traveller count, room and bed configuration, exact arrival and departure terminal or railway station, accommodation budget and currency, luggage, children's ages, older-traveller or accessibility needs, and flexibility on area, room type or a fallback hotel. A planner can compare those requirements with current written property answers and organise a supplier-neutral enquiry. Every property, room, passport-registration process and complete accessible route still needs human reconfirmation; this does not guarantee a live price, availability, guest acceptance, room type or accessibility." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [ { label: "Shanghai destination hub", href: "/destinations/shanghai/", description: "Decide complete days, which bank to stay on and the gateway before fixing this detail." },{ label: "What ‘near the metro’ should mean", href: "/guides/china-hotel-near-metro/", description: "Check the exact station exit and lobby walk." }, { label: "Verify an accessible hotel room", href: "/guides/china-accessible-hotel-room-verification/", description: "Check the full curb-to-room route instead of relying on an accessibility label." }, { label: "Can foreigners stay at any hotel in China?", href: "/guides/foreigners-china-hotel/", description: "Separate the legal rule, platform display and the property's current check-in operation." }, { label: "Shanghai airport choice", href: "/guides/shanghai-pudong-or-hongqiao-airport/", description: "Match the hotel to the correct airport transfer." }, { label: "China's last night before an international flight", href: "/guides/china-last-night-before-international-flight/", description: "Protect the departure night without wasting a full day." }, { label: "Verify a Shanghai 24-hour park", href: "/guides/shanghai-24-hour-parks-reality-check/", description: "Add a late public-space option only after checking the exact zone, entrance, facilities and return." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Shanghai Metro passenger-flow report", url: "https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240910/db6a0546907e44409a328e389d2ef969.html", publisher: "Shanghai Municipal Government", reviewedAt: "2026-08-12" }, { label: "Official reference to People's Square Lines 1, 2 and 8", url: "https://english.shanghai.gov.cn/en-MuseumsGalleries/20240527/3937ac13043a44f39c2a27506a3d7539.html", publisher: "Shanghai Municipal Government", reviewedAt: "2026-08-12" }, { label: "Official example of event-period station changes", url: "https://english.shanghai.gov.cn/en-LatestNews/20251231/1b54690a4747486caee0b9d845156187.html", publisher: "Shanghai Municipal Government", reviewedAt: "2026-08-12" }, { label: "Hero: East Nanjing Road at night by EditQ, CC BY-SA 4.0; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:East_Nanjing_Road_at_night,_Shanghai.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
