import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body={schemaVersion:"1.0.0",blocks:[
{id:"lead",type:"lead",text:"Shanghai's famous names describe large areas, not hotel entrances. For a first visit, choose the place that keeps your evening and two most important sightseeing days simple."},
{id:"answer",type:"callout",title:"The short decision",tone:"decision",body:"Choose People’s Square for the broadest all-round transport logic. Choose the Bund or east Nanjing Road when riverfront evenings are central and you accept crowds plus a possible walk to useful metro exits. Choose the former French Concession when leafy streets, cafés and neighbourhood walking matter more than being beside the classic skyline."},
{id:"matrix",type:"table",caption:"Three first-trip bases",columns:["Area","Best fit","Trade-off","Property check"],rows:[["People’s Square","Mixed sightseeing and rail connections","Busy, less intimate immediately outside","Exact side of the square and station exit"],["Bund / east Nanjing Road","Skyline, riverfront and late central walks","Weekend crowds; some riverfront pins are not close to a convenient exit","Walking route from station and vehicle access"],["Former French Concession","Street life, cafés, slower mornings","Longer trip to some classic sights and transport hubs","Nearest practical station, not the district label"]]},
{id:"split",type:"callout",title:"Do not treat the former French Concession as one point",tone:"warning",body:"It spans multiple neighbourhoods and station catchments. A hotel near one edge can create a very different day from a property near another. Compare the exact address with your first and last stop."},
{id:"fit",type:"comparison",title:"Match the base to the trip",columns:[{heading:"48-hour highlights",items:["People’s Square or east Nanjing Road","Keep one riverfront evening walkable","Accept a busier base"]},{heading:"Food and neighbourhood pace",items:["Former French Concession","Plan a separate Bund outing","Check late return options"]},{heading:"Family or heavy luggage",items:["Prioritise lift and vehicle entrance","Avoid unnecessary station complexes","Confirm room and entrance details"]}]},
{id:"facts",type:"callout",title:"Dynamic facts checked August 12, 2026",tone:"neutral",body:"Shanghai government information identifies People’s Square as a major transport location served by Metro lines 1, 2 and 8, and reports crowd controls around east Nanjing Road and the Bund on busy weekends. These verified facts support the trade-offs; the area recommendation is Homeground editorial judgement. Check current metro, closures and road access for your dates."},
{id:"check",type:"list",ordered:true,items:["Pin the hotel entrance, not the neighbourhood name.","Map one daytime and one late-evening return.","Check the correct station exit and lift path.","Compare arrival-day luggage handoffs.","Confirm the property details before free cancellation ends."]},
{id:"help",type:"callout",title:"Need two addresses compared?",tone:"decision",body:"Send dates, party size, arrival station or airport, priority sights and approximate budget. Homeground can compare the actual pins and the trade-offs to verify."},
{id:"links",type:"internal-links",title:"Continue planning",items:[{label:"Serviced apartment or hotel?",href:"/guides/serviced-apartment-or-hotel-china/",description:"Choose an operating model for a longer stay."},{label:"Chongqing stay areas",href:"/guides/chongqing-where-to-stay-jiefangbei-guanyinqiao-shapingba/",description:"See how terrain changes the same decision."},{label:"What ‘near the metro’ should mean",href:"/guides/china-hotel-near-metro/",description:"Test the final walking route."}]},
{id:"sources",type:"sources",title:"Official sources and image credit",items:[{label:"People’s Square and central weekend traffic information",url:"https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240910/db6a0546907e44409a328e389d2ef969.html",publisher:"Shanghai Municipal Government",reviewedAt:"2026-08-12"},{label:"Official central-area and Metro lines 1, 2 and 8 reference",url:"https://english.shanghai.gov.cn/en-TaxRefundandDutyFree/20251111/07617954a5814e939172eba7136936ae.html",publisher:"Shanghai Municipal Government",reviewedAt:"2026-08-12"},{label:"Hero: East Nanjing Road by EditQ, CC BY-SA 4.0; cropped and converted",url:"https://commons.wikimedia.org/wiki/File:East_Nanjing_Road_at_night,_Shanghai.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"},{label:"CC BY-SA 4.0 licence",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-12"}]}
]} as const satisfies StructuredPageBody; export default body;
