import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body={schemaVersion:"1.0.0",blocks:[
{id:"lead",type:"lead",text:"상하이의 유명 지명은 넓은 지역을 뜻하며 호텔 입구가 아닙니다. 첫 여행에는 저녁과 가장 중요한 이틀의 동선을 단순하게 만드는 곳을 고르세요."},
{id:"answer",type:"callout",title:"빠른 선택",tone:"decision",body:"여러 명소와 철도 연결을 고르게 챙기려면 인민광장, 강변 야경과 난징둥루의 밤이 핵심이고 인파를 감수할 수 있다면 와이탄·난징둥루, 가로수길·카페·동네 산책이 더 중요하면 옛 프랑스 조계지 일대를 비교하세요."},
{id:"matrix",type:"table",caption:"첫 여행의 세 거점",columns:["지역","잘 맞는 여행","감수할 점","숙소 확인"],rows:[["인민광장","혼합 관광과 지하철 연결","붐비고 문밖 분위기가 덜 아늑함","광장 어느 쪽인지와 정확한 출구"],["와이탄·난징둥루 동쪽","스카이라인과 강변의 밤","주말 인파, 일부 강변 숙소의 긴 역 도보","역에서 걷는 길과 차량 접근"],["옛 프랑스 조계지 일대","거리 생활과 느린 아침","일부 명소·교통 허브까지 더 멂","지역명이 아닌 실제 역"]]},
{id:"split",type:"callout",title:"옛 프랑스 조계지를 한 점으로 보지 마세요",tone:"warning",body:"여러 동네와 역세권에 걸쳐 있습니다. 어느 가장자리에 있느냐에 따라 하루가 달라지므로 정확한 주소를 첫 일정과 마지막 일정에 대조하세요."},
{id:"fit",type:"comparison",title:"여행에 맞추기",columns:[{heading:"48시간 하이라이트",items:["인민광장 또는 난징둥루","강변의 밤 한 번을 도보권에","붐비는 거점 감수"]},{heading:"음식과 동네 속도",items:["옛 프랑스 조계지","와이탄은 별도 일정","늦은 귀가 확인"]},{heading:"가족·큰 짐",items:["엘리베이터와 차량 입구 우선","복잡한 역 통과 최소화","방과 입구 조건 확인"]}]},
{id:"facts",type:"callout",title:"변동 정보 확인일: 2026년 8월 12일",tone:"neutral",body:"상하이시 공식 자료는 인민광장을 1·2·8호선이 지나는 주요 교통 지점으로 안내하고, 혼잡한 주말 난징둥루 동쪽과 와이탄 주변의 인파 관리 사례를 알립니다. 이는 확인된 사실이며 지역 추천은 Homeground의 편집 판단입니다. 날짜별 운행·통제·차량 접근은 다시 확인하세요."},
{id:"check",type:"list",ordered:true,items:["지역명이 아니라 입구를 찍습니다.","낮과 늦은 밤 귀가를 한 번씩 그립니다.","정확한 출구와 엘리베이터 길을 봅니다.","도착일 짐 인계를 비교합니다.","무료 취소 전 숙소 세부사항을 확인합니다."]},
{id:"help",type:"callout",title:"두 주소를 비교할까요?",tone:"decision",body:"날짜, 인원, 도착 공항·역, 우선 명소와 대략적 예산을 보내면 Homeground가 실제 위치와 재확인할 조건을 비교할 수 있습니다."},
{id:"links",type:"internal-links",title:"계속 계획하기",items:[{label:"서비스드 아파트와 호텔",href:"/ko/guides/serviced-apartment-or-hotel-china/",description:"장기 체류 운영 형태를 고릅니다."},{label:"충칭 숙소 지역",href:"/ko/guides/chongqing-where-to-stay-jiefangbei-guanyinqiao-shapingba/",description:"지형이 같은 결정을 어떻게 바꾸는지 봅니다."},{label:"‘지하철 근처’ 판단법",href:"/ko/guides/china-hotel-near-metro/",description:"마지막 도보를 검증합니다."}]},
{id:"sources",type:"sources",title:"공식 출처와 이미지 크레디트",items:[{label:"인민광장과 중심부 주말 교통 정보",url:"https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240910/db6a0546907e44409a328e389d2ef969.html",publisher:"상하이시 인민정부",reviewedAt:"2026-08-12"},{label:"중심 지역과 1·2·8호선 공식 자료",url:"https://english.shanghai.gov.cn/en-TaxRefundandDutyFree/20251111/07617954a5814e939172eba7136936ae.html",publisher:"상하이시 인민정부",reviewedAt:"2026-08-12"},{label:"대표 이미지: EditQ의 난징둥루 야경, CC BY-SA 4.0, 크롭·변환",url:"https://commons.wikimedia.org/wiki/File:East_Nanjing_Road_at_night,_Shanghai.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"},{label:"CC BY-SA 4.0 라이선스",url:"https://creativecommons.org/licenses/by-sa/4.0/",publisher:"Creative Commons",reviewedAt:"2026-08-12"}]}
]} as const satisfies StructuredPageBody; export default body;
