import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "A green exit sign in a booking photograph does not show how to leave the room you receive. After check-in, spend five minutes reading the room-door evacuation diagram and walking toward the stairs or exit. You are not certifying the hotel; you are learning a route before darkness, smoke or stress removes easy choices." },
    { id: "scope", type: "callout", title: "The traveller-level decision", tone: "decision", body: "From the assigned room, identify a primary and alternative direction, recognise the stair or exit route, and check for an obvious obstruction, locked door or contradictory instruction. If staff cannot demonstrate a route that works for everyone in the room, request another room and walk again. Change property when no usable plan exists. Do not test alarms, force doors, enter restricted areas or judge legal compliance." },
    { id: "five-heading", type: "heading", level: 2, text: "The five-minute check" },
    { id: "clock-table", type: "table", caption: "Run this after the room is assigned, before unpacking", columns: ["Time", "Action", "Result to keep"], rows: [["0:00–1:00", "Read the diagram on or beside the room door; find ‘you are here,’ the nearest exit direction and another direction if shown", "A simple mental route rather than a photograph you must unlock your phone to see"], ["1:00–3:00", "Walk the primary direction to the stair or clearly designated exit point that a guest may use", "Turns, door count and a landmark you can recognise in low visibility"], ["3:00–4:00", "Observe whether the corridor is clear, signs continue and doors on the route appear normally usable", "A specific problem to report, not a general feeling"], ["4:00–4:30", "Locate the alternative direction and learn how the hotel tells guests about an alarm", "A fallback that does not rely on the same blocked segment"], ["4:30–5:00", "Save the property's Chinese name and address; place key items together for night", "Information for 119 and essentials you can reach without searching"]] },
    { id: "route-list", type: "list", items: ["Start at your door. The obvious lobby exit may be irrelevant from another tower or floor.", "Read every arrow. If the door diagram and corridor signs cannot be reconciled, ask staff to walk the route.", "Notice storage, renovation barriers, carts or furniture narrowing the path; do not move heavy or safety equipment yourself.", "Do not wedge a fire door open or assume a closed door is locked. Use normal guest access and ask about anything unclear.", "Recognise a manual alarm point, fire telephone or extinguisher without activating or handling it as a test.", "If a respirator, torch or other device is supplied, read its instructions; equipment differs between hotels."] },
    { id: "do-not-test", type: "callout", title: "A visual check is not a fire inspection", tone: "warning", body: "Chinese law and standards place design, maintenance and emergency-planning duties on responsible units and authorities. A traveller cannot verify hidden systems or declare compliance. Never cover a detector, hang items from a sprinkler, cut a seal, sound an alarm for practice or publish a complete floor plan. Report the functional concern and choose a usable route or room." },
    { id: "night-heading", type: "heading", level: 2, text: "Set up the room for a night-time alarm" },
    { id: "night-table", type: "table", caption: "Reduce tasks you would otherwise do half awake", columns: ["Prepare", "Why", "Boundary"], rows: [["Shoes, key card and glasses together", "Avoid searching or stepping into debris barefoot", "Do not delay evacuation to collect other belongings"], ["Phone charged with the hotel address saved", "Helps report the location and receive instructions", "A phone is not a reason to ignore an alarm or wait for a perfect signal"], ["Mobility aid beside its user", "Keeps the person's normal movement method available", "Do not block the doorway or corridor"], ["Essential medication in one small reachable pouch", "Protects time-sensitive needs if relocation is prolonged", "Life safety comes before packing a full medicine case"], ["Family roles agreed", "One adult can assist each child or older traveller", "Do not split up to retrieve bags"], ["An outside meeting point chosen", "Reduces re-entry and confusion after evacuation", "Follow staff or fire-rescue direction if they designate another safe place"]] },
    { id: "smoke-heading", type: "heading", level: 2, text: "Scenario: an alarm at night and smoke outside" },
    { id: "smoke-scenario", type: "paragraph", text: "You wake to an alarm and smell smoke outside. Stop treating this as a booking dispute or filming opportunity. Assess conditions, alert 119 or staff and follow official or on-site instructions. Do not use an ordinary lift, return for luggage, enter dense smoke blindly or jump. Smoke, heat and official direction—not the check-in diagram alone—now control the decision." },
    { id: "smoke-actions", type: "list", ordered: true, items: ["If the indicated route is clear enough to use and staff or emergency direction calls for evacuation, leave promptly by the designated stairs or exit.", "Stay low where smoke conditions require it and keep the group together; do not race against or push through other evacuees.", "If the door is hot, smoke or fire prevents exit, or officials direct you to remain, keep the door closed, reduce smoke entering around gaps if possible and call for rescue.", "Tell 119 the hotel's Chinese name and address, your precise location, number of people and any mobility, hearing, vision or medical limitation.", "Signal from a safe visible position if instructed or necessary, but do not improvise a rope descent or reopen a dangerous route."] },
    { id: "mobility-heading", type: "heading", level: 2, text: "Change the room decision when mobility changes the route" },
    { id: "mobility-table", type: "table", caption: "The normal lift is not an evacuation plan", columns: ["Traveller need", "Ask at check-in", "Reject as a complete answer"], rows: [["Wheelchair or powered mobility", "Which room location and staff emergency procedure apply when ordinary lifts are not used?", "‘Take the lift down’ without an emergency-specific plan"], ["Walker, painful knees or limited stamina", "How many turns, doors and stair flights are on the usable route; is a more suitable room available?", "‘The exit is nearby’ without walking it"], ["Personal assistance", "Who is notified, on which shift, and what should the traveller do if help does not arrive?", "An unnamed promise that someone will carry the guest"], ["Medical equipment", "What must remain with the user and what can be left during immediate evacuation?", "A plan that requires repacking equipment under alarm conditions"]] },
    { id: "sensory", type: "paragraph", text: "A deaf traveller should confirm how the actual room delivers or supplements an audible alarm—such as a visible or vibrating device or a documented staff alert—and how to contact staff in writing. A blind or low-vision traveller can ask staff to walk both directions, describe doors and count turns. These are property-specific arrangements; a platform accessibility icon or brand-wide answer does not confirm the assigned room." },
    { id: "family", type: "callout", title: "For children or older relatives, assign people—not possessions", tone: "neutral", body: "Decide which adult assists each person and where the group meets outside. Keep children from playing with alarms, extinguishers and door hardware. During an evacuation, no adult should go back for passports, suitcases or a separated phone. Tell staff or firefighters immediately if a person is missing rather than re-entering." },
    { id: "fault-heading", type: "heading", level: 2, text: "When the route fails at check-in" },
    { id: "fault-steps", type: "list", ordered: true, items: ["Stay in a staffed public area and describe the exact segment: blocked corridor, sign conflict, inaccessible stair approach or door that does not work through normal guest operation.", "Ask the front desk or duty manager to inspect it now. Do not accept ‘maintenance will look tomorrow’ when it affects the only route you can use tonight.", "If it can be cleared safely, walk the route again. Do not rely only on a verbal message that the obstacle has gone.", "If not, request a room with a different, demonstrated route and repeat the five-minute check from that door.", "If no route works for everyone in the room, relocate while transport and alternative reception are still available; pursue the booking remedy after safety is restored."] },
    { id: "fault-table", type: "table", caption: "Proportionate recovery before an emergency", columns: ["Observed issue", "Reasonable first response", "Escalate to room/property change when"], rows: [["Movable cart or stored goods", "Ask staff to clear the route immediately", "It returns or staff refuses"], ["Exit indication is dark, missing or contradictory", "Ask staff to demonstrate the current guest route", "The route remains ambiguous"], ["Door appears locked or restricted", "Do not force it; ask duty staff to verify normal operation", "No alternative guest route can be shown"], ["Route does not work for a mobility or sensory need", "Ask for a more suitable room and documented assistance procedure", "The answer still depends on an ordinary lift or an unnamed carrier"], ["Renovation has changed the floor", "Request the current diagram and a walked route", "The displayed plan no longer matches what exists"]] },
    { id: "active-fire", type: "callout", title: "During smoke or fire, stop negotiating", tone: "warning", body: "Call 119 and act on immediate conditions and emergency instructions. Do not wait for a platform agent, debate a refund, collect proof or return to the room. Booking recovery and complaints belong after every traveller is safe." },
    { id: "evidence", type: "paragraph", text: "For a non-emergency problem, save the booking, property name, address, time, staff role, requested fix and outcome. Photograph only the local obstruction or sign problem; hide room numbers, guests, credentials and camera views. Use the record for a room change, cancellation or platform review. Do not publish a complete map or allege illegality; competent authorities determine compliance." },
    { id: "conditions", type: "table", caption: "Conditions that change the safest default", columns: ["Condition", "Decision adjustment"], rows: [["Solo stay with hearing or vision limits", "Require an actual-room alert and orientation plan, not a general accessibility answer"], ["Wheelchair user above ground level", "Ask for the emergency procedure before accepting the room; ordinary lift access is insufficient"], ["Late arrival during renovation", "Walk the current route before unpacking because signs and barriers may have changed"], ["Only one route appears usable", "Ask staff to identify the alternative and change room if the same blockage defeats both"], ["Active alarm, smoke or heat", "Immediate life-safety action overrides the check-in plan and booking process"]] },
    { id: "privacy", type: "paragraph", text: "Keep the check private: you need a mental route and emergency-ready address, not a floor-plan archive. Never publish a room number, key-card image, full floor geometry, door-control detail, CCTV position or another guest. Give 119 your precise room and floor directly; privacy must not withhold rescue information." },
    { id: "dynamic", type: "paragraph", text: "Official sources were reviewed on August 13, 2026. Mandatory standard GB 13495.3-2026 on installing fire-safety signs took effect on August 1, 2026 and replaced GB 15630-1995. Routes, renovation barriers, equipment and staff procedures remain property- and time-specific; repeat the check after any room move." },
    { id: "links", type: "internal-links", title: "Continue checking the property", items: [{ label: "Where to stay in China", href: "/stay/", description: "Return to the accommodation decision collection." }, { label: "Compare commercial aparthotels and residential rentals", href: "/guides/commercial-aparthotel-or-residential-rental-china/", description: "Choose the operating model with a workable late-night recovery chain." }, { label: "Understand minsu, homestay and hotel labels", href: "/guides/minsu-homestay-or-hotel-china/", description: "Verify the operator and actual property instead of relying on a label." }, { label: "Choose a Beijing courtyard or modern hotel", href: "/guides/beijing-courtyard-hotel-or-modern-hotel/", description: "Compare character with entrance, stairs, staff support and room function." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "2025 holiday travel safety press conference", url: "https://www.mem.gov.cn/xw/xwfbh/2025n09y29xwfbh/", publisher: "Ministry of Emergency Management", reviewedAt: "2026-08-13" }, { label: "How to stay safely in a hotel", url: "https://www.119.gov.cn/kp/hzyf/bgfd/2022/18836.shtml", publisher: "National Fire and Rescue Administration / Beijing Fire and Rescue", reviewedAt: "2026-08-13" }, { label: "National Fire and Rescue Administration holiday safety notice", url: "https://www.119.gov.cn/qmxfgk/tzgg/2023/39693.shtml", publisher: "National Fire and Rescue Administration", reviewedAt: "2026-08-13" }, { label: "Public-place fire self-rescue guidance", url: "https://www.mem.gov.cn/kp/shaq/201904/t20190401_366015.shtml", publisher: "Ministry of Emergency Management", reviewedAt: "2026-08-13" }, { label: "GB 13495.3-2026 Fire safety signs — Requirements for installation", url: "https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=E430E8F3B52A6CD5AB7E2DEC00F5C1EE", publisher: "National Public Service Platform for Standards Information", reviewedAt: "2026-08-13" }, { label: "Fire Protection Law of the People's Republic of China", url: "https://flk.npc.gov.cn/detail?fileId=&id=ff8081817ab22e0c017abd909312060a&title=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E6%B6%88%E9%98%B2%E6%B3%95&type=", publisher: "National Database of Laws and Regulations", reviewedAt: "2026-08-13" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
