import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "The China National Silk Museum is most useful when you do not begin with the oldest-looking robe. Start with the living chain that makes silk possible, move to the looms that turn thread into structures, read historical textiles through their labels, and finish where conservators decide how much evidence can safely survive. Homeground’s recommended sequence is Sericulture Hall → Weaving Hall → Silk Road Hall → Textile Conservation Gallery, subject to the museum’s current route and closures. It turns a large multi-building museum into four questions: What was made? How was it structured? Where did this object and its information come from? What has conservation changed—or deliberately left unchanged?",
    },
    {
      id: "answer",
      type: "callout",
      title: "The direct answer: follow a process, not a gallery checklist",
      tone: "decision",
      body: "Choose this museum if you want to understand how a cocoon becomes evidence, not merely see beautiful clothes. Keep one process display, one loom or model, one historical object label and one conservation decision. A first visit does not need every gallery. A UNESCO-listed practice is not proof that every display is ancient; a reconstruction can explain mechanism without becoming an original; and a “long-term” exhibition still needs a same-day access check.",
    },
    {
      id: "layer-key",
      type: "table",
      caption: "Give each display one evidence label before interpreting it",
      columns: ["Layer", "What it can do", "What it cannot do by itself"],
      rows: [
        ["Living practice", "Explain coordinated knowledge such as mulberry care, silkworm raising, reeling, dyeing, weaving and embroidery", "Show that a short museum demonstration reproduces a whole community practice"],
        ["Model or reconstruction", "Make a hidden mechanism, loom movement or missing step visible", "Prove that the model is an excavated ancient machine or that every detail is historically fixed"],
        ["Historical object", "Carry material, structure, date, findspot, use and custody evidence when the label supports them", "Reveal an unnamed maker, wearer, merchant or complete journey"],
        ["Conservation presentation", "Show how documentation, analysis, support and display conditions protect information", "Return an object to a perfect original state or make every repair invisible"],
      ],
    },
    {
      id: "route-heading",
      type: "heading",
      level: 2,
      text: "Which museum route gives a first visit a clear argument?",
    },
    {
      id: "route-p1",
      type: "paragraph",
      text: "Use four anchors rather than trying to finish the campus. In the Sericulture Hall, find the transition from cocoon to usable filament or thread. In the Weaving Hall, choose one named loom, model or preparation tool and ask what movement it explains. In the Silk Road Hall, stop at one object whose label gives more than a dynasty. End at the Textile Conservation Gallery, where the problem changes from making cloth to preserving a fragile record. This order is Homeground’s editorial recommendation, not an official one-way route; follow current signs and staff instructions between buildings.",
    },
    {
      id: "route-p2",
      type: "paragraph",
      text: "Before walking, save the current exhibition list and write four headings in your notes: process, structure, context, condition. Put one observation beneath each. If a temporary show occupies part of a core hall, do not rush through it merely because it is current; ask whether it answers one of those four questions. The Fashion Hall can be a worthwhile optional finish for design-focused visitors, but it should not replace the production and conservation anchors if the purpose is to understand how textile evidence works.",
    },
    {
      id: "route-list",
      type: "list",
      ordered: true,
      items: [
        "Sericulture Hall: identify the material chain before looking for a masterpiece.",
        "Weaving Hall: connect one mechanism to warp, weft or another named structure.",
        "Silk Road Hall: read one label from object name through provenance and collection route.",
        "Textile Conservation Gallery: identify the risk, investigation and treatment boundary.",
        "Optional Fashion Hall or temporary exhibition: add it only after the four core questions are answered.",
      ],
    },
    {
      id: "raw-heading",
      type: "heading",
      level: 2,
      text: "What is silk before it becomes fabric?",
    },
    {
      id: "raw-p1",
      type: "paragraph",
      text: "Silk begins as a biological and agricultural relationship, not as a bolt of shiny cloth. UNESCO’s intangible-heritage record describes a chain that includes growing mulberry, raising silkworms, unreeling cocoons, preparing thread, designing and weaving. The museum’s current Sericulture and Weaving exhibition adds reeling, floss preparation, printing and resist-dyeing displays, embroidery and regional customs. At the first process case, point to the input and output: cocoon to filament, filaments to a usable thread, or prepared thread to colour. If neither side is labelled, treat the display as orientation rather than a technical conclusion.",
    },
    {
      id: "raw-p2",
      type: "paragraph",
      text: "The distinction between reeling and weaving prevents an easy mistake. Reeling draws long filaments from cocoons and combines or prepares them; weaving interlaces prepared warp and weft into cloth. Spun silk made from shorter fibres is another path, so do not call every bundle of fibre “reeled silk.” Dyeing may happen at different points depending on the textile. A five-minute video or static tableau can clarify one transition, but it cannot represent the labour, seasonal knowledge, breeding, agriculture and local social practice covered by the living tradition.",
    },
    {
      id: "process-table",
      type: "table",
      caption: "Read the chain as changes in material state",
      columns: ["Stop", "Look for", "Useful question"],
      rows: [
        ["Mulberry and silkworm", "Leaves, life-cycle material, tools or community customs", "Which living and seasonal conditions are being explained?"],
        ["Cocoon and reeling", "Filament emerging, combining or winding", "Is this reeling, floss preparation or a model of the action?"],
        ["Thread and colour", "Twist, skein, a mordant treatment that helps dye bind to fibre, printing or resist-dyeing evidence", "Was fibre, yarn or finished cloth treated?"],
        ["Loom and cloth", "Warp preparation, heddles, shuttle or pattern control", "Which thread relationship creates the structure?"],
        ["Embroidery", "A needle-added surface technique", "What was woven first, and what was added afterward?"],
      ],
    },
    {
      id: "loom-heading",
      type: "heading",
      level: 2,
      text: "What should one loom teach you?",
    },
    {
      id: "loom-p1",
      type: "paragraph",
      text: "Do not count looms; choose one whose label you can read. Find the warp—the lengthwise set held under tension—and the weft that passes across it. Then identify what controls the crossing: heddles lifting selected warps, a shuttle carrying weft, pattern cords, cards or another mechanism named by the museum. A reconstructed Han-pattern loom or a scaled model can make that control visible even when no ancient wooden machine survives. Its value is explanatory. Record “model,” “reconstruction” or “traditional loom” exactly rather than upgrading it to an original.",
    },
    {
      id: "loom-p2",
      type: "paragraph",
      text: "Next separate structure from decoration. Plain, twill and satin describe basic ways warp and weft relate; luo (罗), often rendered gauze or leno, involves crossed warp relationships that produce an open but stable structure. Brocade, embroidery and a flower or animal motif answer different questions. The museum’s own explainers are useful precisely because “silk” is not one surface: it can be open, ribbed, dense, matte or lustrous. You are not expected to authenticate a fragment by eye. Use the label to test your observation, not your observation to overrule the label.",
    },
    {
      id: "song-twill-figure",
      type: "figure",
      src: "/images/guides/china-national-silk-museum-cocoon-to-conservation-route/song-twill-1600.webp",
      alt: "Close view of a 1274 floral-patterned twill in the China National Silk Museum collection.",
      width: 1600,
      height: 1065,
      caption: "A motif is easy to see; “twill” is a structural identification supported by the object record, not by colour or shine alone. Photo: 三猎, CC BY-SA 4.0; resized.",
    },
    {
      id: "structure-table",
      type: "table",
      caption: "Five terms that should not collapse into “silk”",
      columns: ["Term", "Field meaning", "Do not mistake it for"],
      rows: [
        ["Fibre/material", "What the thread is made from", "The way threads cross"],
        ["Weave structure", "How warp and weft interlace", "A flower, dragon or geometric motif"],
        ["Technique", "A making or decorating action such as reeling, resist dyeing or embroidery", "A dynasty or provenance"],
        ["Motif", "The visible designed form", "Proof of one culture, route or owner"],
        ["Object type", "Garment, fragment, cover, ribbon or another use form", "A guarantee that every component shares one date"],
      ],
    },
    {
      id: "label-heading",
      type: "heading",
      level: 2,
      text: "How do you read a historical textile label without over-reading it?",
    },
    {
      id: "label-p1",
      type: "paragraph",
      text: "Begin with the noun. Is it a complete garment, a panel, an excavated fragment, a reproduction, a loom sample or a modern practitioner’s work? Then record material and structure, the proposed date, dimensions, findspot, donor or holding institution, and any treatment or reconstruction note. These fields answer different questions. “Excavated at Astana Cemetery” is a findspot; “donated by the Xinjiang Uyghur Autonomous Region Museum” is part of custody; “China National Silk Museum collection” is the present holding statement. None means the object was found in Hangzhou.",
    },
    {
      id: "plain-luo-figure",
      type: "figure",
      src: "/images/guides/china-national-silk-museum-cocoon-to-conservation-route/plain-luo-garment-1600.webp",
      alt: "A dark-brown plain-luo single garment dated 1274 displayed behind glass at the China National Silk Museum.",
      width: 1600,
      height: 1067,
      caption: "The 1274 素罗单衣 links a named object, weave term and De’an tomb context; this 2017 photograph is not a current-display promise. Photo: Siyuwj, CC BY-SA 4.0; resized.",
    },
    {
      id: "label-p2",
      type: "paragraph",
      text: "The museum’s published record for this 素罗单衣 gives an unusually useful bundle: object no. 1761, a date of 1274, a De’an tomb in Jiangxi, dimensions, garment construction and the term luo. The photograph lets you see a surviving garment and display context; the record supplies the date and excavation claim. It still does not tell you that the item will be in the same case today, that every stitch is untouched, or that the quoted historical explanation of the garment name has only one accepted interpretation. Copy the institution’s certainty words—“dated,” “approximately,” “excavated,” “donated,” “restored”—instead of silently strengthening them.",
    },
    {
      id: "label-list",
      type: "list",
      items: [
        "Object: what survives, and is it complete or a fragment?",
        "Material and structure: what is identified scientifically or technically?",
        "Date: exact dated context, period range, stylistic attribution or modern reproduction?",
        "Place: findspot, production hypothesis and present museum are three different locations.",
        "Custody: who excavated, donated, lent or now holds it?",
        "Intervention: what is restored, supported, reconstructed or replaced?",
      ],
    },
    {
      id: "silk-road-heading",
      type: "heading",
      level: 2,
      text: "What can a Silk Road gallery actually prove?",
    },
    {
      id: "silk-road-p1",
      type: "paragraph",
      text: "The Silk Road Hall moves from prehistoric and early imperial textiles through medieval exchange to modern production. Its strongest evidence is specific: a textile found at a named site, a weave that can be compared with other pieces, a motif with parallels, a dye identified through analysis, or a documented industrial sample. Put those fields together and an exchange hypothesis becomes stronger. Keep the plural idea of routes and relationships in mind. “Silk Road” is an interpretive frame across long periods, not a railway line on which every object travelled end to end.",
    },
    {
      id: "brocade-figure",
      type: "figure",
      src: "/images/guides/china-national-silk-museum-cocoon-to-conservation-route/northern-dynasties-brocade-1600.webp",
      alt: "Fragment of Northern Dynasties brocade with lions, elephants and camel-leading figures in the museum collection.",
      width: 1600,
      height: 1065,
      caption: "The motif invites an exchange question; without a complete label and analysis it cannot reveal one trader, direction or journey. Photo: 三猎, CC BY-SA 4.0; resized.",
    },
    {
      id: "silk-road-p2",
      type: "paragraph",
      text: "A foreign-looking animal or medallion is a starting clue, not a passport. Ask whether the label cites a findspot, comparison, weave analysis, inscription or dye test. The museum’s research exhibition on natural dyes explains that laboratory chemical analysis can identify dye compounds and, combined with structure and pattern, contribute to proposals about technique, production and exchange. That is stronger than colour matching by eye but still bounded. It cannot name an undocumented dyer, wearer or merchant. If a label says “influenced by,” “possibly” or “suggests,” keep that degree of confidence in your note.",
    },
    {
      id: "exchange-table",
      type: "table",
      caption: "Build an exchange claim one rung at a time",
      columns: ["Evidence", "Supports", "Does not establish alone"],
      rows: [
        ["Named findspot", "Where the object was recovered", "Where it was made or every route before burial"],
        ["Weave or fibre analysis", "Technical relationships and possible production traditions", "An individual artisan or ethnic identity"],
        ["Motif comparison", "A visual relationship worth testing", "Direction, date or direct contact without other evidence"],
        ["Dye analysis", "Probable colourant sources and technical choices", "The photograph’s apparent colour or one exact trade path"],
        ["Inscription/document", "A named language, phrase, owner or transaction when legible and contextualised", "The full biography of an unrecorded user"],
      ],
    },
    {
      id: "conservation-heading",
      type: "heading",
      level: 2,
      text: "Why should conservation be the final gallery, not an afterthought?",
    },
    {
      id: "conservation-p1",
      type: "paragraph",
      text: "Textiles survive unevenly. Light, humidity, handling, folds, soil, old repairs and the chemistry of fibres and dyes all affect what can be displayed. The Conservation Gallery’s published scope begins with information extraction and research before treatment. Museum reports separate photography and documentation, condition assessment, fibre or dye analysis, cleaning where justified, stitching or support, mounting and storage/display controls. The sequence matters: conservators need to know what an object is doing before deciding what to do to it.",
    },
    {
      id: "sui-blue-figure",
      type: "figure",
      src: "/images/guides/china-national-silk-museum-cocoon-to-conservation-route/sui-blue-silk-1600.webp",
      alt: "Close view of a blue plain-silk fragment dated to the Sui period, from Astana Cemetery and held by the China National Silk Museum.",
      width: 1600,
      height: 1065,
      caption: "Findspot and collection route are separate evidence fields; the photograph alone cannot identify the dye or current treatment. Photo: 三猎, CC BY-SA 4.0; resized.",
    },
    {
      id: "conservation-p2",
      type: "paragraph",
      text: "At a case or viewing window, identify three things: the risk, the evidence preserved and the intervention disclosed. A support fabric may prevent further tearing without pretending to be the lost original. A darkened stain may remain because removal would destroy fibre or historical information. Low light may make a display frustrating because light damage is cumulative. Conversely, a clean and complete object is not automatically fake. Conservation can stabilise, join or mount surviving material while keeping additions distinguishable in records. Do not tap glass, lean over barriers or use a camera setting that staff have prohibited in pursuit of a brighter image.",
    },
    {
      id: "conservation-table",
      type: "table",
      caption: "Read treatment as a decision with limits",
      columns: ["Stage", "Visitor-visible clue", "Safe interpretation"],
      rows: [
        ["Documentation", "Overall and detail images, diagrams, measurements", "A baseline records condition and construction"],
        ["Analysis", "Fibre, dye or contaminant result", "A test can narrow material or process questions"],
        ["Stabilisation", "Support, aligned tears or restrained loose threads", "The aim can be safe survival, not visual perfection"],
        ["Mounting/display", "Low light, angled support, limited exposure", "The display environment is part of preservation"],
        ["Reconstruction", "A diagram, sample or replacement area clearly identified", "It helps explanation but is not surviving original material"],
      ],
    },
    {
      id: "ich-heading",
      type: "heading",
      level: 2,
      text: "Does UNESCO recognition make a display ‘authentic’?",
    },
    {
      id: "ich-p1",
      type: "paragraph",
      text: "UNESCO inscribed sericulture and silk craftsmanship of China on the Representative List of the Intangible Cultural Heritage of Humanity in 2009. The subject is living knowledge and coordinated practice in communities—not a certificate attached to every cocoon, loom, textile or visitor activity. In the museum, the inscription helps you ask who carries knowledge, which steps depend on season and cooperation, and how skills are taught. It does not turn an old tool into a third-century original or a modern practitioner’s work into an archaeological object.",
    },
    {
      id: "ich-p2",
      type: "paragraph",
      text: "This distinction also protects the people behind the process. A static model can explain mechanics; a recorded demonstration can preserve an action; a scheduled encounter with a practitioner may show living skill. They are not interchangeable. If the museum advertises a dated workshop or demonstration, read who leads it, which step participants perform, what material is pre-prepared and whether photography is permitted. A short hands-on activity can be valuable without being described as “making silk from start to finish.”",
    },
    {
      id: "ich-warning",
      type: "callout",
      title: "Do not turn one badge into four claims",
      tone: "warning",
      body: "UNESCO recognition supports the significance of a living practice. It does not prove the age of a museum machine, the provenance of a textile, the completeness of a visitor workshop or the current availability of a practitioner. Read the practice record, object label, reconstruction label and event notice separately.",
    },
    {
      id: "closure-heading",
      type: "heading",
      level: 2,
      text: "What if a core hall is closed or occupied by a temporary show?",
    },
    {
      id: "closure-p1",
      type: "paragraph",
      text: "Treat the route as four questions, not four guaranteed doors. The museum’s current 2026 homepage lists the Sericulture/Weaving, Silk Road and Conservation exhibitions as long-term, while a 2025 notice shows that these same areas have closed during upgrades. On 4 September 2026, temporary exhibitions also occupied parts of the Sericulture and Conservation spaces. Check the homepage and newest notice on the day, then ask staff which levels are open. A dated exhibition end date still does not guarantee that every case or corridor is accessible.",
    },
    {
      id: "closure-table",
      type: "table",
      caption: "Keep the learning task when the ideal route breaks",
      columns: ["Unavailable node", "Best recovery", "Do not substitute"],
      rows: [
        ["Sericulture Hall", "Use an open process introduction or official display text, then begin with a labelled loom input/output", "A shop’s cocoon product as proof of the production chain"],
        ["Weaving Hall", "Use a labelled historical textile to identify warp/weft structure, then consult the museum’s official weave explainer", "Calling any old wooden machine an ancient loom"],
        ["Silk Road Hall", "Choose a documented object in another open gallery and apply the same date–place–custody test", "A decorative route map with no object evidence"],
        ["Conservation Gallery", "Record condition and display controls on one open textile; use the museum’s official conservation material later", "Claiming that you watched a treatment that was not visible"],
        ["Object named in this guide", "Use another label with the same fields", "Assuming a 2016 or 2017 photograph proves current display"],
      ],
    },
    {
      id: "closure-p2",
      type: "paragraph",
      text: "If two or more anchors are closed, shorten the visit rather than padding it with retail or unrelated temporary material. Photograph the current map only when signs allow, note the closed nodes, and preserve the question for a future visit. The page remains useful because no single object is mandatory. Its method can be completed with whichever labelled process, structure, historical context and condition evidence is genuinely accessible.",
    },
    {
      id: "traveler-heading",
      type: "heading",
      level: 2,
      text: "Which version of the route fits your group?",
    },
    {
      id: "traveler-table",
      type: "table",
      caption: "Choose attention before choosing duration",
      columns: ["Traveler", "Keep", "Cut first"],
      rows: [
        ["First-time visitor", "One cocoon-to-thread step, one loom, one complete label and conservation", "Dense dynasty-by-dynasty coverage"],
        ["Textile or design specialist", "Two contrasting structures, construction details, analysis and mounting decisions", "Generic introductory panels already known"],
        ["Family with children", "Give each person one role: material detective, loom-movement finder, label recorder, condition observer", "Long technical reading before finding a physical clue"],
        ["Fashion-focused visitor", "Core process and label anchors, then Fashion Hall if open", "Assuming fashion alone explains fibre production or object history"],
        ["Visitor with limited mobility or energy", "Contact the museum, identify one feasible hall plus one backup and accept a partial route", "Assuming a continuous step-free connection without current confirmation"],
      ],
    },
    {
      id: "traveler-p1",
      type: "paragraph",
      text: "Do not promise your group a universal two-hour circuit. Separate buildings, temporary installations, queues, reading depth and lift status change the effort. Agree on four pieces of evidence and stop when you have them. A specialist may spend longer with two labels than a family spends in a whole room. Both can complete the route if they can explain one material transition, one structure, one contextual claim and one conservation limit.",
    },
    {
      id: "day-heading",
      type: "heading",
      level: 2,
      text: "What should you verify today—and is the museum worth your time?",
    },
    {
      id: "day-p1",
      type: "paragraph",
      text: "The museum’s standing notice reviewed on 4 September 2026 lists Tuesday–Sunday opening from 09:00 to 17:00, last entry at 16:30, and Monday closure except statutory holidays. It says individual visitors do not need advance reservation and foreign visitors may enter with a passport. Bring the original passport and check for a newer dated notice before leaving. The review found no current museum-wide public rule that guarantees ordinary photography in every room, no verified continuous step-free route and no guaranteed schedule for English interpretation or live demonstrations.",
    },
    {
      id: "day-table",
      type: "table",
      caption: "Five day-of checks with honest fallbacks",
      columns: ["Need", "Check", "Fallback"],
      rows: [
        ["Entry", "Newest official notice and original passport", "Ask visitor service; do not rely on a search snippet"],
        ["Core halls", "Current exhibition list, onsite map and closure signs", "Keep the four questions and use equivalent open displays"],
        ["Photography", "Door, case and temporary-exhibition signs; ask staff", "Write object number, title, date and one observation"],
        ["Language", "Ask whether an official English guide, device or service is available", "Use Chinese object names and numbers; translate only after preserving the label"],
        ["Mobility", "Contact the museum about the actual route, lifts and companion needs", "Choose one confirmed hall and an official digital/reading fallback"],
      ],
    },
    {
      id: "phrase-table",
      type: "table",
      caption: "A compact Chinese field card",
      columns: ["Need", "Show or say", "Meaning"],
      rows: [
        ["Find a hall", "请问蚕桑馆／织造馆／丝路馆／修复展示馆怎么走？", "How do I get to the Sericulture / Weaving / Silk Road / Conservation Hall?"],
        ["Check status", "这个展厅今天开放吗？", "Is this gallery open today?"],
        ["Ask about a model", "这是原件、复原件，还是模型？", "Is this an original, a reconstruction or a model?"],
        ["Ask about a label", "请问出土地和收藏单位分别是什么？", "What are the findspot and holding institution?"],
        ["Photography", "这里可以拍照吗？不用闪光灯。", "May I take a photo here? I will not use flash."],
        ["Accessibility", "请问无障碍路线和电梯在哪里？", "Where are the accessible route and lifts?"],
      ],
    },
    {
      id: "decision",
      type: "callout",
      title: "Worth it—or skip it?",
      tone: "decision",
      body: "Visit if you want to understand making, material evidence or conservation and can give the museum focused attention. It is especially strong for travelers tired of seeing ‘silk’ used as a single luxury label. Shorten to two open anchors if energy is limited. Skip without guilt if your only aim is shopping, a guaranteed live workshop or a quick Hangzhou landmark photograph; this page does not turn the museum into those products.",
    },
    {
      id: "day-p2",
      type: "paragraph",
      text: "Leave with four sentences, not a bag of unexplained names: “This display shows one change in material state. This loom or model explains one structural relationship. This object’s date and journey are supported by these label fields. This conservation choice protects this evidence while leaving this uncertainty.” That is enough to make the museum coherent—and to keep a beautiful textile from carrying claims it cannot support.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue the craft, evidence and Hangzhou route",
      items: [
        {
          label: "Choose a Xuan-paper museum, production visit or workshop",
          href: "/guides/jingxian-xuan-paper-museum-workshop-choice/",
          description: "Apply the same process and authenticity boundaries to a living paper craft without confusing a short activity with full production.",
        },
        {
          label: "Visit an archaeological site museum without over-reading one object",
          href: "/guides/how-to-visit-an-archaeological-site-museum/",
          description: "Extend the date–findspot–context–inference method to excavated sites and displays.",
        },
        {
          label: "Choose the right Shanghai–Hangzhou station pair",
          href: "/guides/shanghai-hangzhou-transport-route/",
          description: "Solve the separate intercity transport task after deciding that the museum belongs in the Hangzhou plan.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources and image credits reviewed 4 September 2026",
      items: [
        { label: "Current opening, reservation and passport notice", url: "https://www.chinasilkmuseum.com/cgjyy/info_6.aspx?itemid=31249", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Current exhibitions and long-term gallery status", url: "https://www.chinasilkmuseum.com/zz/list_17.aspx", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Sericulture and Weaving permanent exhibition", url: "https://www.chinasilkmuseum.com/zz/info_17.aspx?itemid=31423", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Sericulture and silk craftsmanship of China", url: "https://ich.unesco.org/en/RL/sericulture-and-silk-craftsmanship-of-china-00197?RL=00197", publisher: "UNESCO Intangible Cultural Heritage", reviewedAt: "2026-09-04" },
        { label: "Silk Road Hall permanent exhibition", url: "https://www.chinasilkmuseum.com/zz/info_17.aspx?itemid=26320", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Textile Conservation Gallery", url: "https://www.chinasilkmuseum.com/zz/info_17.aspx?itemid=26331", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Museum explainers on ling, luo, chou and duan", url: "https://www.chinasilkmuseum.com/gskt/info_319.aspx?itemid=30898", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Natural-dye analysis and evidence", url: "https://www.chinasilkmuseum.com/zz/info_96_itemid_31240.html", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Official textile-conservation method report", url: "https://www.chinasilkmuseum.com/uploadfiles/2021/01/20210119142011140.pdf", publisher: "China National Silk Museum", reviewedAt: "2026-09-04" },
        { label: "Hero: museum entrance by Siyuwj; cropped, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:China_Silk_Museum,_2017-11-12_01.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
        { label: "1274 plain-luo garment by Siyuwj; resized, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E7%B4%A0%E8%90%9D%E5%8D%95%E8%A1%A3,_2017-11-12.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
        { label: "1274 floral twill by 三猎; resized, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E5%8D%97%E5%AE%8B%E8%8A%B1%E5%8D%89%E7%BA%B9%E7%BB%AB.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
        { label: "Northern Dynasties brocade by 三猎; resized, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E5%8C%97%E6%9C%9D%E5%AF%B9%E7%8B%AE%E5%AF%B9%E8%B1%A1%E7%89%B5%E9%A9%BC%E4%BA%BA%E7%89%A9%E7%BA%B9%E9%94%A61.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
        { label: "Sui blue plain-silk fragment by 三猎; resized, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:%E9%9A%8B%E4%BB%A3%E8%93%9D%E7%BB%A2%E7%89%87.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-09-04" },
        { label: "CC BY-SA 4.0 licence", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-09-04" },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
