import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "From Beijing South Railway Station to Daxing Airport (PKX), compare the subway connection to the Daxing Airport Express at Caoqiao with a taxi. For Capital Airport (PEK), compare the airport bus, subway/Airport Express and a taxi. Your arrival time, luggage and flight terminal determine the useful option. Check current services and allow for leaving the railway station, airport walking and airline check-in as well as the ride itself." },
  { id: "answer", type: "callout", title: "PEK and PKX are not substitute terminals", tone: "decision", body: "For PKX, compare a subway connection to the Daxing Airport Express at Caoqiao with a road vehicle. For PEK, compare the current Beijing South airport-bus route, subway/Airport Express and a road vehicle. The best answer changes with the exact hour, luggage, group and disruption margin." },
  { id: "matrix-heading", type: "heading", level: 2, text: "Choose the airport first, then the mode" },
  { id: "matrix", type: "table", caption: "Every option starts after the train is actually exited", columns: ["Route", "Good fit", "Practical drawback", "Verify"], rows: [
    ["Beijing South → subway → Daxing Airport Express → PKX", "Daytime, manageable luggage and live rail service", "Station corridors, transfers, separate airport express and terminal walk", "Current subway route, last train and flight terminal"],
    ["Beijing South → current airport bus → PEK", "A dated departure fits and its station stop is clear", "Waiting, road traffic, intermediate stops and terminal order", "Official platform, boarding point, departure and served terminal"],
    ["Beijing South → subway/Airport Express → PEK", "Rail is running and transfers suit the group", "Cross-city interchange and luggage through stations", "Live route, operating window and terminal"],
    ["Authorised taxi/ride-hail → either airport", "Several people, large bags or rail is closed", "Road variability, pickup-zone confusion and toll/traffic", "Airport code, terminal, legal pickup and realistic buffer"],
  ]},
  { id: "daxing-rail-heading", type: "heading", level: 2, text: "One rail route from Beijing South to Daxing Airport" },
  { id: "daxing-rail-intro", type: "paragraph", text: "Use these station names on the signs and check that the lines are running for your arrival." },
  { id: "daxing-rail-steps", type: "list", ordered: true, items: [
    "After leaving the railway platforms at Beijing South (北京南站), follow signs for Subway Line 4. Take the southbound train towards Tiangongyuan (天宫院), pass Majiabao (马家堡), and get off at Jiaomen Xi (角门西).",
    "Change to Line 10 and choose the direction whose next station is Caoqiao (草桥). Travel one stop and get off at Caoqiao.",
    "Follow the interchange signs for Daxing Airport Express (大兴机场线), then board towards Daxing Airport (大兴机场). Stay on past Daxing Xincheng (大兴新城) to the airport.",
    "At the airport, follow signs to your airline's departure area. Count interchange walks and waiting for each train separately from time on board."
  ]},
  { id: "warning", type: "callout", title: "Do not follow the words 'Beijing Airport'", tone: "warning", body: "Show the driver PEK or PKX plus the terminal. Daxing is not a new terminal at Capital Airport, and Capital is not a terminal at Daxing. Reaching the wrong airport means another major transfer, not a small detour." },
  { id: "clock-heading", type: "heading", level: 2, text: "Work backward from the airline cutoff" },
  { id: "three-hour-gap", type: "paragraph", text: "A three-hour gap from scheduled train arrival to flight departure is the whole connection, not three hours at the airport. Judge it against your flight's own domestic or international check-in and bag-drop deadlines, including every interchange. Allow for station exits, transfer walks, waiting and delays as well as the Airport Express ride." },
  { id: "clock", type: "list", ordered: true, items: ["Airline check-in/bag-drop and boarding deadline.", "Correct airport terminal walk and security/exit procedures.", "Road or rail journey plus extra time for delays.", "Beijing South platform-to-exit walk and pickup/transfer.", "Train-delay allowance and a decision point for abandoning the connection."] },
  { id: "groups", type: "comparison", title: "What the traveller changes", columns: [
    { heading: "Light, daytime", items: ["Rail gives a predictable structure", "Keep every transfer name", "Check last service anyway"] },
    { heading: "Family or many bags", items: ["Count lifts and corridors", "A direct road vehicle may simplify", "Keep child-seat needs explicit"] },
    { heading: "Late arrival or international flight", items: ["Use a much larger buffer", "Know the live bus/rail cutoff", "A near-airport night can be the safer itinerary"] },
  ]},
  { id: "station-heading", type: "heading", level: 2, text: "The transfer clock starts before the railway exit" },
  { id: "station-copy", type: "paragraph", text: "A train arrival time is the time at the platform, not the moment a traveller enters a taxi or airport train. The group may still need to leave the carriage, collect bags, follow the correct exit, cross a large concourse and find a pickup or metro entrance. Keep everyone together until the mode is confirmed. If a driver is meeting you, exchange the train number, passenger name, live delay and an exact signed meeting point rather than the words ‘Beijing South’." },
  { id: "risk-heading", type: "heading", level: 2, text: "Classify the connection before selecting a vehicle" },
  { id: "risk-matrix", type: "table", caption: "Same transfer, different consequences", columns: ["Connection", "Planning position", "Required response"], rows: [
    ["Domestic flight on one protected booking", "Airline rules determine protection; city transfer is still the traveller's responsibility", "Confirm the operating carrier, terminal and cutoff"],
    ["Separate international ticket", "Highest consequence if the train or city transport fails", "Use a larger buffer or sleep near the airport"],
    ["Late-night arrival", "Public-transport choices may narrow while road demand rises", "Verify the final usable service and legal taxi queue before boarding the train"],
    ["Group with checked bags", "Platform exit, vehicle size and bag drop all take longer", "Do not calculate from the fastest solo, hand-luggage case"],
  ]},
  { id: "road", type: "callout", title: "A road vehicle removes transfers, not uncertainty", tone: "neutral", body: "Traffic, pickup-zone rules and finding the vehicle remain part of the trip. Put the airport code, terminal and flight number in writing, confirm that the vehicle can hold every passenger and suitcase, and use the regulated taxi queue or the legal ride-hailing pickup shown in the app. Ignore unsolicited drivers inside the station. If road conditions worsen, recalculate the airline cutoff rather than assuming a taxi must be faster." },
  { id: "go-no-go-heading", type: "heading", level: 2, text: "Set a go/no-go point before the train reaches Beijing" },
  { id: "go-no-go", type: "list", ordered: true, items: ["Record the airline's own check-in, bag-drop and boarding deadlines; do not replace them with a generic airport recommendation.", "Subtract a terminal-security margin, city-transfer margin and railway-exit margin from the earliest relevant cutoff.", "Choose a trigger—such as a specified train delay—at which the group contacts the airline and changes transport immediately.", "Keep the flight booking, passport, airport code, terminal and legal pickup instructions available offline.", "If the arithmetic has no defensible margin before travel, change the train or add an airport night rather than hoping every segment runs at its minimum."] },
  { id: "recovery-heading", type: "heading", level: 2, text: "Wrong airport or failing connection" },
  { id: "recovery", type: "table", caption: "Make the flight deadline the priority", columns: ["Problem", "Response"], rows: [
    ["Train arrives late", "Recalculate against the airline cutoff and switch only to a verified faster route"],
    ["At the wrong airport", "Contact the airline immediately, then use the current official inter-airport or road option"],
    ["Direct Daxing bus appears in an old guide", "Do not rely on it: the Beijing South Daxing Night Line 2 was suspended from April 7, 2026"],
    ["Last rail service missed", "Use the official airport-bus platform or legal taxi queue; do not accept hall solicitors"],
  ]},
  { id: "facts", type: "callout", title: "Dynamic transport facts checked August 13, 2026", tone: "neutral", body: "Beijing's April 2026 notice retained/adjusted the Capital Airport–Beijing South bus and suspended Daxing Airport–Beijing South Night Line 2. A July 2026 notice extended the Capital Airport line's downtown-bound late service. Subway, airport express, buses, stops and hours remain date-specific." },
  { id: "help", type: "callout", title: "Need the rail-to-flight connection checked?", tone: "decision", body: "Send the date, train number and arrival time, airport code and terminal, flight time, group size and luggage. Homeground can identify when you need to change plans and which backup to confirm; airlines and operators control live service." },
  { id: "links", type: "internal-links", title: "Protect the complete itinerary", items: [
    { label: "Which Beijing railway station?", href: "/guides/which-beijing-railway-station/", description: "Confirm the train really arrives at Beijing South." },
    { label: "China high-speed train first-time guide", href: "/guides/china-high-speed-train-first-time-guide/", description: "Prepare the rail segment before the airport handoff." },
    { label: "China's last night before an international flight", href: "/guides/china-last-night-before-international-flight/", description: "Decide when not to attempt a same-day link." },
    { label: "Where to stay in Beijing", href: "/guides/beijing-where-to-stay-first-trip/", description: "Use a hotel night if the transfer is not defensible." },
  ]},
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [
    { label: "April 2026 airport-bus route changes", url: "https://english.beijing.gov.cn/latest/news/202603/t20260330_4569792.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-12" },
    { label: "July 2026 airport-bus update", url: "https://english.beijing.gov.cn/livinginbeijing/transportation/bus/202607/t20260727_4792045.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-12" },
    { label: "Rail links to seven stations and two airports", url: "https://english.beijing.gov.cn/livinginbeijing/transportation/beijingsubway/202412/t20241216_3966828.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-08-12" },
    { label: "Line 4 southbound direction and Beijing South–Majiabao–Jiaomen Xi station sequence", url: "https://www.mtr.bj.cn/service/line/timetable/line-4", publisher: "Beijing MTR", reviewedAt: "2026-09-08" },
    { label: "Line 10 adjacent stations: Jiaomen Xi and Caoqiao", url: "https://www.mtr.bj.cn/service/line/distable/line-10.html", publisher: "Beijing MTR", reviewedAt: "2026-09-08" },
    { label: "Daxing Airport Express station sequence: Caoqiao, Daxing Xincheng and Daxing Airport", url: "https://www.bjmoa.cn/metroLineList.html?sline=26", publisher: "北京市轨道交通运营管理有限公司", reviewedAt: "2026-09-08" },
    { label: "Daxing Airport Express operating information and Line 10 interchange at Caoqiao", url: "https://www.bjmoa.cn/stationList_346.html?sline=26", publisher: "北京市轨道交通运营管理有限公司", reviewedAt: "2026-09-08" },
    { label: "Hero: Beijing South by N509FZ, CC BY-SA 4.0; cropped", url: "https://commons.wikimedia.org/wiki/File:North_square_of_Beijing_South_Railway_Station_(20180722170459).jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" },
    { label: "Hero derivative licence: CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-12" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
