import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "For a first Peking Opera (京剧, Jingju) in Beijing, choose the exact programme before choosing the famous theatre. A short visitor-oriented showcase is useful when you want several visual and musical techniques in one compact evening. A named 折子戏 programme gives complete scenes or excerpts and is not an inferior imitation. A clearly labelled 全本 or 整本 production is better when you want sustained plot and singing and can prepare beforehand. A gala or selected-arias concert is another product again. Before paying, verify the title, troupe, format, expected running time, synopsis, language support, seat sightline, entry document, photography rule and change terms for that date.",
    },
    {
      id: "answer",
      type: "callout",
      title: "The direct answer",
      tone: "decision",
      body: "Do not use ‘tourist show’ versus ‘authentic opera’ as your only test. The stronger question is whether the organiser accurately names what it is presenting. A well-labelled excerpt can be a credible first encounter; a vaguely advertised ‘traditional show’ can leave you unable to check the play, troupe or language support. Homeground's first-timer default is a named excerpt programme or a clearly described highlights showcase with a synopsis and verified seat-visible subtitles. Choose a full production when story continuity matters more than compact variety.",
    },
    {
      id: "format-heading",
      type: "heading",
      level: 2,
      text: "Choose the performance format before the theatre name",
    },
    {
      id: "format-table",
      type: "table",
      caption: "Four products that should not be sold to you as the same thing",
      columns: ["Listing language", "What it may offer", "What to verify"],
      rows: [
        [
          "Highlights, tourist showcase or experience performance",
          "A curated sequence of singing, movement, combat or costume moments; potentially accessible when time is short",
          "Named scenes, performing troupe, live versus recorded elements, duration and current language support",
        ],
        [
          "折子戏专场 (zhezixi programme)",
          "One or more selected scenes with their own dramatic shape; excerpts are legitimate units of Jingju transmission",
          "Scene titles, source plays, cast order, number of pieces and whether links between them are explained",
        ],
        [
          "全本 / 整本 / 本戏 (full or linked production)",
          "Longer narrative continuity, recurring characters and more time for vocal and dramatic development",
          "That the organiser explicitly uses this label, plus acts, duration, intermission and late-admission policy",
        ],
        [
          "演唱会 / 名家名段 / gala or hybrid",
          "Selected arias, star appearances, instrumental framing or a mixed presentation",
          "Whether it is staged drama, concert singing, lecture-demonstration or a combination",
        ],
      ],
    },
    {
      id: "format-p1",
      type: "paragraph",
      text: "Short does not mean false, and long does not guarantee clarity or quality. An official China ICH research account of repertoire transmission includes many 折子戏 and fewer 全本戏: excerpts are part of how the form is performed and passed on, not merely pieces cut for foreigners. Conversely, a performance using genuine costumes and techniques can still be packaged as a modern tourism presentation. The cultural form and the commercial product are two layers. Ask the seller to name both.",
    },
    {
      id: "listing-heading",
      type: "heading",
      level: 2,
      text: "Read the listing as evidence, not as decoration",
    },
    {
      id: "listing-table",
      type: "table",
      caption: "The minimum evidence to collect before payment",
      columns: ["Field", "Why it matters", "A weak answer"],
      rows: [
        ["Exact Chinese title and format", "Lets you find a synopsis and distinguish a scene, full production or concert", "‘Classic Beijing opera’"],
        ["Producing or performing troupe", "Separates the venue, ticket seller and actual artistic company", "Only a theatre address"],
        ["Cast or role list", "Shows which announced performers and role types belong to your date", "A generic promotional cast photograph"],
        ["Expected duration and intermission", "Determines whether the evening fits and when a safe exit is possible", "An old blog's duration for the same building"],
        ["Subtitle language and display location", "A subtitle claim is useless if your seat cannot see that screen", "‘English friendly’ without a screen or device"],
        ["Entry, change and refund terms", "Names, documents, collection and programme changes differ by channel", "‘Bring ID’ without saying which document"],
        ["Step-free route and access service", "The entrance, security/collection-to-seat path, wheelchair and companion place, lift, toilet and any hearing/visual device must work for this performance and seat", "A generic ‘accessible venue’ badge"],
      ],
    },
    {
      id: "listing-p1",
      type: "paragraph",
      text: "A current official calendar can be a starting point, not the whole decision. Rechecked on 4 September 2026, Beijing's municipal notice for that week listed several named Beijing Jingju Theatre productions at Chang'an Grand Theatre, with dates, troupe and venue. It separately listed a programme titled 经典折子戏专场 at Tianleyuan; that row did not identify the genre, so it proves only that ‘excerpt programme’ is an actual listing label—not that this event itself was Peking Opera. The notice warned that details could change and did not supply subtitles, running time, ticket stock or photography. Continue to the named organiser or venue's exact listing.",
    },
    {
      id: "listing-warning",
      type: "callout",
      title: "A venue's old product page is not tonight's promise",
      tone: "warning",
      body: "Liyuan Theatre is a real Beijing institution, and a 2026 Xicheng District page confirms its location and history. An older theatre page also describes a compact highlights product with Chinese and English subtitles. That older description cannot prove your date, duration or subtitle service in 2026. The same rule applies to every theatre: save a current official confirmation tied to the exact performance, not a search snippet or a years-old review.",
    },
    {
      id: "prepare-heading",
      type: "heading",
      level: 2,
      text: "Prepare one page of story, not a complete translation",
    },
    {
      id: "prepare-p1",
      type: "paragraph",
      text: "Peking Opera librettos and spoken passages use a stylised theatrical language; subtitles may summarise rather than mirror every sound. Fifteen minutes of preparation usually has more value than trying to read continuously during the show. Find an institutional or organiser synopsis for the exact play or scene. Write down the starting conflict, two or three character names, their relationship, and what each wants in this scene. If you bought a multi-excerpt programme, prepare each title separately. Do not assume that a familiar legend, film or novel follows the same sequence on stage.",
    },
    {
      id: "prepare-list",
      type: "list",
      ordered: true,
      items: [
        "Copy the exact Chinese title from the official listing, including the scene name after any separator.",
        "Read a short synopsis from the troupe, theatre, museum or reliable reference; avoid a full modern translation you do not have permission to reproduce.",
        "Mark who is on stage at the scene's beginning, who enters later, and the decision or conflict that changes the scene.",
        "Note whether the listing emphasises vocal performance, civil drama (文戏) or martial action (武戏), but treat these as useful orientations rather than rigid boxes.",
        "Save the synopsis offline. A theatre signal failure should not make the performance unintelligible.",
      ],
    },
    {
      id: "roles-heading",
      type: "heading",
      level: 2,
      text: "Use role categories as a map, not a personality horoscope",
    },
    {
      id: "roles-table",
      type: "table",
      caption: "A first orientation to 生旦净丑",
      columns: ["Role family", "First thing to notice", "What not to conclude"],
      rows: [
        ["生 (sheng)", "Male-role performance differentiated by age, status, voice and movement", "Every unpainted male face is the same character type"],
        ["旦 (dan)", "Female-role performance with distinct vocal, costume and movement conventions", "Costume beauty alone explains the dramatic role"],
        ["净 (jing)", "Strongly patterned facial design and an often forceful stage presence", "One colour always predicts a fixed moral personality in every play"],
        ["丑 (chou)", "A character commonly marked by a small white facial area and distinctive speech or movement", "The role exists only for disposable comic relief"],
      ],
    },
    {
      id: "roles-p1",
      type: "paragraph",
      text: "The Beijing Jingju Theatre's own introduction stresses that roles classify dramatic identity, character and social position, not only natural sex and age. Subtypes matter, and a performer may communicate rank or temperament through gait, vocal placement, sleeves, beard work and the way a prop is handled. Use the programme's cast list first. Face paint is one channel among several; a viral red-equals-loyal, white-equals-treacherous chart is too blunt to identify an unfamiliar figure with confidence.",
    },
    {
      id: "roles-warning",
      type: "callout",
      title: "Do not name a character from costume alone",
      tone: "neutral",
      body: "If the official programme does not identify the actor, role and scene, describe only what you can observe: a 净-style painted face, long water sleeves, armour, a beard movement or a fan. Different productions and characters can share visual vocabulary. This is also the rule for photographs: do not turn an unlabeled stage image into evidence of a specific play.",
    },
    {
      id: "first-ten-heading",
      type: "heading",
      level: 2,
      text: "Spend the first ten minutes finding sound, status and direction",
    },
    {
      id: "first-ten-list",
      type: "list",
      ordered: true,
      items: [
        "Locate the musicians if visible. 文场 commonly centres melodic strings and winds, while 武场 percussion marks action and structure; the exact layout varies.",
        "Listen for the drum and percussion cue before an entrance, turn, pose or burst of action. Sound often tells you that a movement matters before subtitles do.",
        "Identify the first character from the programme, then watch how everyone else makes space, approaches, kneels, sits or turns toward that person.",
        "Choose one channel at a time: voice during a long sung passage, footwork and sleeves during movement, then the subtitle at a pause. Do not keep your eyes fixed above the stage.",
        "At the scene's first clear change, ask silently: who gained information, authority or danger? That question restores the plot even when several lines were missed.",
      ],
    },
    {
      id: "first-ten-p1",
      type: "paragraph",
      text: "Peking Opera is conventionally described through 唱念做打: singing, reciting, acting/movement and martial technique. It is not necessary for every scene to display all four in equal proportion. The musical frame also matters. National and theatre sources distinguish melodic 文场 from percussion 武场, with the drum master coordinating musicians and stage action. For a first audience, hearing a cue connect to a turn or entrance is a more durable discovery than memorising an entire instrument list.",
    },
    {
      id: "stage-heading",
      type: "heading",
      level: 2,
      text: "Let one table, two chairs and a gesture build the place",
    },
    {
      id: "stage-p1",
      type: "paragraph",
      text: "UNESCO describes minimal scenery and props together with codified, symbolic movement. This does not mean an empty stage has no location. A table and chairs can be arranged differently for a hall, court or domestic space; an oar-like action can establish travel without a real boat; a repeated circular path can compress a journey; mounting, opening or crossing may be shown through trained movement rather than a realistic object. Read the actor's relationship to the object before asking what the object literally is.",
    },
    {
      id: "stage-table",
      type: "table",
      caption: "Three questions for a sparse stage",
      columns: ["What changed", "What to watch", "Working interpretation"],
      rows: [
        ["An object is moved or reoriented", "Who is permitted to touch it, where others stand and whether the music marks the change", "The social or physical setting may have changed"],
        ["An actor repeats a controlled path", "Direction, pace, gaze and the point where the pattern stops", "Distance, search, travel or hesitation may be compressed"],
        ["A long sleeve, beard, fan or weapon moves before speech", "Preparation, extension, pause and recovery rather than only the final pose", "The object is carrying emotion, status or force as well as decoration"],
      ],
    },
    {
      id: "language-heading",
      type: "heading",
      level: 2,
      text: "Treat subtitles as access support, not structural support",
    },
    {
      id: "language-table",
      type: "table",
      caption: "Language-support failures and the recovery path",
      columns: ["Failure", "Immediate recovery", "What to do next time"],
      rows: [
        ["English subtitles were advertised but are absent", "Ask front-of-house staff before the performance starts; use your offline synopsis if service cannot be restored", "Keep dated written confirmation and ask whether the problem affects a refund or seat change under that seller's terms"],
        ["The screen is blocked from your seat", "Ask for a permitted reseat before curtain or at the interval; do not move into an occupied seat", "Request the screen location and a compatible section before purchase"],
        ["The translation is too condensed", "Follow character objectives, entrances and percussion cues rather than chasing every line", "Prepare names and scene conflict instead of a word-for-word script"],
        ["The programme changed", "Ask for the replacement Chinese title and, if available, an official programme or synopsis. If none is provided, search by the exact title yourself and decide under the published policy whether to stay", "Recheck the official listing and messages on show day"],
      ],
    },
    {
      id: "language-warning",
      type: "callout",
      title: "Ask where the subtitles are",
      tone: "warning",
      body: "‘English subtitles available’ is incomplete. Ask whether they cover your exact programme, whether they appear above or beside the stage or on a device, and whether the proposed seat has a clear view. If English access is essential and the organiser cannot answer, do not let an old venue page or reseller badge make the decision for you.",
    },
    {
      id: "audience-heading",
      type: "heading",
      level: 2,
      text: "Follow the room without performing an audience stereotype",
    },
    {
      id: "audience-list",
      type: "list",
      items: [
        "Silence and darken the phone before the lights change. A bright screen distracts performers and nearby viewers even when no photo is taken.",
        "Assume photography, audio and video are prohibited until the exact venue expressly allows them. NCPA's prohibition is clear for NCPA, not wording to paste onto every Beijing theatre.",
        "Applaud with the room at a completed aria, scene, interval or curtain. You are not required to shout 好 to prove respect or cultural knowledge.",
        "If others call approval during a performance, listen to when it happens; do not imitate over dialogue or a quiet musical line you cannot yet read.",
        "Confirm late-admission and re-entry rules. Some productions may hold latecomers until a suitable break, and a ticket does not guarantee immediate seating after curtain.",
        "Photograph displays, makeup demonstrations or performers only where permission covers that object and those people; a public lobby is not blanket consent.",
      ],
    },
    {
      id: "audience-p1",
      type: "paragraph",
      text: "Etiquette belongs partly to the art and partly to the room. Official NCPA guidance asks audiences not to make unauthorised photographs or recordings and offers its own applause guidance. A smaller theatre may publish different lobby, drink or photo rules. None of this means visitors must remain emotionally blank. The useful principle is proportion: respond at a completed unit, preserve attention during the next one, and let venue staff—not an internet list of national taboos—settle operational questions.",
    },
    {
      id: "scenario-heading",
      type: "heading",
      level: 2,
      text: "Match the programme to the traveller you actually are",
    },
    {
      id: "scenario-table",
      type: "table",
      caption: "Four credible first-performance choices",
      columns: ["Traveller", "Best starting format", "Deal-breaker"],
      rows: [
        ["One free evening, curious but unsure", "A named excerpt programme or clearly described compact showcase with verified synopsis and language access", "No named content, troupe or current operational confirmation"],
        ["Story-first theatre viewer", "An explicitly labelled full or linked production whose synopsis you can prepare", "Unknown duration, no safe interval plan or a plot you cannot identify"],
        ["Movement and martial-action viewer", "A named 武戏 scene or mixed excerpt bill that specifies the scene rather than promising generic acrobatics", "A promotional stunt reel with no play, performers or stage context"],
        ["Voice and music listener", "A vocal-centred scene, full production or named-arias event, chosen with full knowledge of whether it is staged drama or concert form", "Buying a gala while expecting continuous dramatic action"],
      ],
    },
    {
      id: "scenario-p1",
      type: "paragraph",
      text: "Families should confirm age guidance, seat rules and total duration rather than assuming colour and combat make every production child-oriented. If access is material, ask about the step-free entrance; the route through security or ticket collection to the seat; wheelchair and companion positions; lifts and accessible toilet; hearing or visual support; and whether a device or staff service must be reserved. Tie every answer to the exact performance and seat. If a necessary route or service cannot be confirmed, do not buy on a generic ‘accessible’ or ‘foreigner friendly’ label. A visitor who cannot sit through a long evening has not failed the culture by choosing one well-identified scene.",
    },
    {
      id: "repair-heading",
      type: "heading",
      level: 2,
      text: "Build a show-day plan that survives one failure",
    },
    {
      id: "repair-table",
      type: "table",
      caption: "Final verification and recovery",
      columns: ["Checkpoint", "Confirm", "If it fails"],
      rows: [
        ["Before payment", "Exact date, title, format, troupe, duration, subtitle location, seat, required document and change terms", "Do not buy until the seller resolves the missing field or choose another official listing"],
        ["Morning of the show", "Official change/cancellation notice and the message channel attached to your order", "Use the organiser's process; do not travel on the strength of an old screenshot"],
        ["At the venue", "Correct building and entrance, name/document match, programme sheet, subtitle sightline and recording rule", "Ask front-of-house before scanning or surrendering a collection record"],
        ["A format mismatch appears", "Whether the programme is excerpts, concert, demonstration or full drama", "Before admission or curtain, pause use of the ticket, request written clarification and ask about change/refund under the seller's terms. If discovered after curtain, choose whether to continue or leave at a permitted break; preserve sales evidence without disrupting performers"],
        ["After language support fails", "Whether staff can restore, reseat or provide a current synopsis", "Follow the offline character map and stage cues, or leave at a permitted break if access is essential"],
        ["A promised access route or service fails", "A safe step-free alternative, the booked wheelchair/companion place or device, and any permitted reseating", "Ask front-of-house before proceeding. Do not accept an unsafe route or assume an alternative exists; use the seller's terms if the necessary access cannot be delivered"],
      ],
    },
    {
      id: "phrases-table",
      type: "table",
      caption: "Questions to show the official seller or venue",
      columns: ["Question", "Chinese"],
      rows: [
        ["What format is this?", "这是折子戏专场、全本戏、演唱会，还是旅游展示演出？"],
        ["How long and is there an interval?", "这场预计多长时间？有中场休息吗？"],
        ["Does this exact show have English subtitles?", "这一场有英文字幕吗？字幕在哪个位置？"],
        ["Can this seat see the subtitles?", "这个座位能完整看到英文字幕吗？"],
        ["What document must a foreign visitor bring?", "外国观众取票和入场要带护照原件吗？姓名必须一致吗？"],
        ["May I photograph or record?", "演出中可以拍照、录音或录像吗？哪些区域可以？"],
        ["Please confirm the accessible route and service", "请确认无台阶入口、从安检或取票到座位的路线、轮椅和陪同座位、电梯、无障碍卫生间，以及助听或视觉服务；需要预约吗？"],
        ["What happens if the programme changes?", "如果剧目、演员或场次变更，通知和退改规则是什么？"],
      ],
    },
    {
      id: "closing-p1",
      type: "paragraph",
      text: "The success test is simple. You should be able to say what kind of programme you bought, name the scene or play, follow one character's objective, hear one musical cue change the action, and distinguish the troupe's performance from the venue's tourism packaging. If you can do that, a compact excerpt can open the form more clearly than an unprepared long production. If you want help fitting a verified performance into a Beijing day, Homeground can review the exact official listing you are considering rather than sell you a permanent ‘best theatre’ answer.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Continue the performance route",
      items: [
        {
          label: "See Sichuan Opera beyond face-changing",
          href: "/guides/sichuan-opera-face-changing-with-context/",
          description: "Keep regional opera forms separate and choose a Chengdu or Chongqing programme by stage evidence.",
        },
        {
          label: "Verify a first Inner Mongolia long-song performance",
          href: "/guides/inner-mongolia-long-song-first-performance/",
          description: "Use a similar programme-first method for Urtiin Duu, short song, Khoomei and mixed shows.",
        },
        {
          label: "Choose where to stay in Beijing",
          href: "/guides/beijing-where-to-stay-first-trip/",
          description: "Select a base before committing to an evening venue and its return journey.",
        },
        {
          label: "Prepare payment in China",
          href: "/guides/how-to-pay-in-china-as-a-tourist/",
          description: "Keep a payment backup for official ticket channels and venue collection.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources",
      items: [
        {
          label: "Peking Opera on the Representative List",
          url: "https://ich.unesco.org/en/RL/peking-opera-00418",
          publisher: "UNESCO Intangible Cultural Heritage",
          reviewedAt: "2026-09-01",
        },
        {
          label: "National intangible-cultural-heritage project: Jingju",
          url: "https://www.ihchina.cn/project_details/13201",
          publisher: "China Intangible Cultural Heritage Network",
          reviewedAt: "2026-09-01",
        },
        {
          label: "About Jingju",
          url: "https://www.bjo.com.cn/approach_jingju.html",
          publisher: "Beijing Jingju Theatre",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Beijing commercial performances, 31 August–6 September 2026",
          url: "https://whlyj.beijing.gov.cn/spxx/content/202305/t20230519_3108207.html",
          publisher: "Beijing Municipal Culture and Tourism Bureau",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Liyuan Theatre institutional profile",
          url: "https://www.bjxch.gov.cn/zt/jytq/xxxq/pnidpv952339.html",
          publisher: "Beijing Xicheng District People's Government",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Jingju repertoire transmission research",
          url: "https://www.ihchina.cn/Article/Index/detail?id=26788",
          publisher: "China Intangible Cultural Heritage Network",
          reviewedAt: "2026-09-01",
        },
        {
          label: "Audience rules for performances",
          url: "https://www.chncpa.org/bzzx/gkyc_398/201607/t20160725_39961.shtml",
          publisher: "National Centre for the Performing Arts",
          reviewedAt: "2026-09-01",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
