import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "decision-lead",
      type: "lead",
      text: "You do not choose between T2 and T3 at Guangzhou Baiyun International Airport: your exact flight determines the terminal. Confirm it first, then choose the metro, intercity railway, road transfer or terminal connection that serves it.",
    },
    {
      id: "current-state",
      type: "paragraph",
      text: "Some directions published before May 7, 2026—especially those sending passengers to T1 or either Airport South station—are now obsolete. Terminal 1 stopped handling passengers that day, while Metro Airport South and intercity Baiyun Airport South became non-stopping stations. The airport currently operates passenger flights through T2 and T3, and both terminal assignments and ground services can change.",
    },
    {
      id: "quick-answer",
      type: "callout",
      title: "The short answer",
      tone: "decision",
      body: "Read T2 or T3 on the current itinerary for the exact flight, then verify it with the operating airline or Baiyun Airport on the travel day. For T2, compare the direct Metro Line 3 stop Airport North with the intercity station Baiyun Airport North. For T3, compare the directly connected intercity station Baiyun Airport East with Metro Lines 3 or 9 to Gaozeng plus the Gaozeng–T3 Airport Line 2 branch, or a road transfer. Do not travel to T1, Metro Airport South or intercity Baiyun Airport South while their passenger service remains suspended.",
    },
    {
      id: "terminal-snapshot-heading",
      type: "heading",
      level: 2,
      text: "The airport now has a two-terminal passenger decision",
    },
    {
      id: "terminal-grid",
      type: "comparison",
      title: "What T2 and T3 change",
      columns: [
        {
          heading: "Terminal 2",
          body: "The terminal with a direct Guangzhou Metro station as well as a Guangdong Intercity station.",
          items: [
            "Metro Line 3: Airport North (T2)",
            "Intercity: Baiyun Airport North (T2)",
            "Taxi, ride-hailing and airport buses also serve the terminal",
            "Confirm the exact flight; do not assume an airline always stays here",
          ],
        },
        {
          heading: "Terminal 3",
          body: "The newer terminal with a directly connected intercity station but no direct metro station as of this review.",
          items: [
            "Intercity: Baiyun Airport East (T3), inside the transport centre",
            "Metro alternative: Lines 3 or 9 to Gaozeng, then the Gaozeng–T3 Airport Line 2 branch",
            "Taxi, ride-hailing and airport buses use T3-specific pickup areas",
            "Domestic, international and regional flights can use T3",
          ],
        },
      ],
    },
    {
      id: "t1-warning",
      type: "callout",
      title: "T1 is closed for upgrading, not erased from every map",
      tone: "warning",
      body: "T1 ceased passenger operations on May 7, 2026; the official notices do not give a reopening date. Old guides, saved map pins and screenshots may still show T1, Metro Airport South or intercity Baiyun Airport South. Newer official notices override those older directions.",
    },
    {
      id: "terminal-decision-heading",
      type: "heading",
      level: 2,
      text: "Confirm the flight before opening the transport map",
    },
    {
      id: "flight-not-airline-rule",
      type: "paragraph",
      text: "A static airline list looks convenient but ages badly. Airlines have moved more than once during the T3 transition, and a codeshare can display the selling airline more prominently than the airline that actually operates the aircraft. Check each flight separately, including the return journey; two flights on one booking can still use different terminals.",
    },
    {
      id: "terminal-checklist",
      type: "list",
      ordered: true,
      items: [
        "Find the exact flight number and travel date in the latest booking confirmation, not an early search screenshot.",
        "Find the operating carrier. For a codeshare, this may differ from the airline that sold the ticket.",
        "Read the departure or arrival terminal shown for that specific flight and check any airline message about a terminal change.",
        "Recheck the flight on the airline or Baiyun Airport flight-status page on the travel day.",
        "Only then search the route to T2 or T3 and save the terminal name in Chinese for the driver or map app.",
      ],
    },
    {
      id: "codeshare-warning",
      type: "callout",
      title: "Terminal, check-in island and gate are different things",
      tone: "neutral",
      body: "T2 or T3 is the terminal. A check-in island is the counter area inside it, and the boarding gate is assigned later. Do not replace a terminal check with an old counter list, and do not use an arrival terminal from a previous trip to predict a future departure.",
    },
    {
      id: "station-names-heading",
      type: "heading",
      level: 2,
      text: "Five similar station names refer to different rail systems and terminal areas",
    },
    {
      id: "station-name-intro",
      type: "paragraph",
      text: "The presence or absence of “Baiyun” distinguishes the rail systems. Airport North and Airport South are Guangzhou Metro stations; Baiyun Airport North, South and East are Guangdong Intercity stations. The directional words refer to different terminal areas, not alternative translations of one stop.",
    },
    {
      id: "station-table",
      type: "table",
      caption: "Use the station that matches the terminal and rail system",
      columns: ["Passenger terminal", "Guangzhou Metro", "Guangdong Intercity", "Current planning note"],
      rows: [
        [
          "T2",
          "Airport North (T2) / 机场北（2号航站楼）",
          "Baiyun Airport North (T2) / 白云机场北（2号航站楼）",
          "Both rail systems serve T2, but they use different station names and networks.",
        ],
        [
          "T3",
          "No direct metro station as of August 11, 2026; use Gaozeng plus the Gaozeng–T3 Airport Line 2 branch if choosing metro",
          "Baiyun Airport East (T3) / 白云机场东（3号航站楼）",
          "The intercity station is in the T3 transport centre and is the direct rail stop for this terminal.",
        ],
        [
          "T1 — passenger operations suspended",
          "Airport South (T1) / 机场南（1号航站楼） — trains do not stop",
          "Baiyun Airport South (T1) / 白云机场南（1号航站楼） — trains do not stop",
          "Do not follow an old airport guide to either South station while the suspension remains in force.",
        ],
      ],
    },
    {
      id: "station-name-trap",
      type: "callout",
      title: "Airport North is not Baiyun Airport North",
      tone: "warning",
      body: "Airport North (T2) is the Metro Line 3 station; Baiyun Airport North (T2) is the Guangdong Intercity station. Do not shorten the intercity name in a search—the missing word changes the rail system, fare gates and route.",
    },
    {
      id: "t3-wayfinding-figure",
      type: "figure",
      src: "/images/guides/guangzhou-baiyun-airport-t2-t3/t3-baiyun-airport-east-wayfinding-1440.webp",
      alt: "Entry gates and platform signs inside Baiyun Airport East intercity station at Guangzhou Baiyun Airport Terminal 3.",
      width: 1440,
      height: 960,
      caption: "Baiyun Airport East has intercity fare gates and platform signs inside the T3 transport centre. Photo: Jacky Cheung/Wikimedia Commons, CC BY-SA 4.0; cropped.",
    },
    {
      id: "t2-route-heading",
      type: "heading",
      level: 2,
      text: "For T2, direct metro and intercity rail are both real options",
    },
    {
      id: "t2-route-copy",
      type: "paragraph",
      text: "T2 is the simpler terminal for a traveller already on Metro Line 3 because Airport North is directly at the terminal. Guangdong Intercity also serves T2 at Baiyun Airport North. The better choice is not automatically “metro” or “intercity”: it depends on the hotel, railway hub or city in which the journey begins, the live service pattern and the amount of luggage being moved.",
    },
    {
      id: "t2-options",
      type: "list",
      items: [
        "Use Metro Airport North when Line 3 creates the simpler chain from your actual starting point.",
        "Use intercity Baiyun Airport North when a connected intercity station reduces transfers or when moving between T2 and T3 during operating hours.",
        "Use an official taxi rank or the designated ride-hailing area when rail has stopped or the group cannot manage the corridors and transfers.",
        "For an airport bus, check the terminal stop, city stop and travel-date schedule rather than assuming every route serves both terminals.",
      ],
    },
    {
      id: "t3-route-heading",
      type: "heading",
      level: 2,
      text: "For T3, choose among direct intercity rail, the Gaozeng feeder bus, and road transport",
    },
    {
      id: "t3-route-copy",
      type: "paragraph",
      text: "Baiyun Airport East is on level B2 of the T3 transport centre and connects on foot to the departure hall. That makes it the direct rail answer, but not necessarily the door-to-door answer for every hotel. A traveller whose useful urban rail line is the metro may prefer Gaozeng plus the Gaozeng–T3 Airport Line 2 branch; a late arrival, family group or party with several large cases may prefer an official taxi or a correctly pinned ride-hailing pickup.",
    },
    {
      id: "t3-options",
      type: "comparison",
      title: "Three practical ways to reach T3",
      columns: [
        {
          heading: "Guangdong Intercity",
          body: "Travel to Baiyun Airport East (T3), then follow the connected terminal route.",
          items: [
            "Direct rail station for T3",
            "Useful from connected intercity corridors",
            "Check the live operating pattern and final train",
          ],
        },
        {
          heading: "Metro + Airport Line 2 branch",
          body: "Take Metro Line 3 or 9 to Gaozeng, use Exit B, then follow signs for the Gaozeng–T3 Airport Line 2 branch.",
          items: [
            "Not a one-seat metro ride to the terminal",
            "Add the bus wait and luggage transfer",
            "This route is not the 24-hour inter-terminal shuttle",
          ],
        },
        {
          heading: "Road transfer",
          body: "Use T3 Departures for drop-off or the terminal's current official pickup zones after arrival.",
          items: [
            "Simpler with children or heavy luggage",
            "Road time and price are not fixed",
            "Confirm T3 in Chinese before the vehicle moves",
          ],
        },
      ],
    },
    {
      id: "gaozeng-dynamic",
      type: "callout",
      title: "The Gaozeng feeder is not the inter-terminal shuttle",
      tone: "neutral",
      body: "An official English notice published May 8, 2026 placed the Gaozeng pickup at Exit B and the T3 return pickup at Stop 74, described the ride as roughly 15 minutes and listed operating hours and frequencies. Treat that as a dated snapshot of the Gaozeng–T3 Airport Line 2 branch, not a permanent timetable or the airport's 24-hour inter-terminal shuttle. Recheck the stop, first and last bus, frequency and fare for the travel date.",
    },
    {
      id: "origin-heading",
      type: "heading",
      level: 2,
      text: "Start from the real origin, not a generic “city centre”",
    },
    {
      id: "origin-matrix",
      type: "table",
      caption: "Which first option to compare from common starting situations",
      columns: ["Starting situation", "For T2, compare first", "For T3, compare first", "What can reverse the answer"],
      rows: [
        [
          "Hotel with an easy Line 3 route",
          "Metro to Airport North",
          "Metro to Gaozeng plus the Gaozeng–T3 Airport Line 2 branch",
          "An early or late flight, multiple transfers, large cases or a hotel far from the useful station",
        ],
        [
          "Guangzhou South railway hub",
          "Intercity search using Panyu → Baiyun Airport North",
          "Intercity search using Panyu → Baiyun Airport East",
          "The train you need may not use the same stopping pattern; allow for the large hub and live timetable",
        ],
        [
          "Pazhou, Panyu or another point close to a connected intercity station",
          "Intercity to Baiyun Airport North",
          "Intercity to Baiyun Airport East",
          "The first and last service, station access and the final walk with luggage",
        ],
        [
          "Late night, older parents, small children or several large suitcases",
          "Official taxi or correctly pinned ride-hailing pickup/drop-off",
          "Official taxi or correctly pinned ride-hailing pickup/drop-off",
          "Vehicle availability, road conditions and whether the hotel entrance is easy to reach",
        ],
      ],
    },
    {
      id: "south-station-copy",
      type: "paragraph",
      text: "The Guangdong Intercity station connected to the Guangzhou South complex is named Panyu. It is a separate rail system and paid area, so follow signs for the intercity station and allow time to move from the high-speed-rail arrival platform. Search the exact pair—Panyu to Baiyun Airport North for T2 or Panyu to Baiyun Airport East for T3—and check the current stopping pattern. A published “fastest” journey is not a promise for every train or every walk through the hub.",
    },
    {
      id: "wrong-terminal-heading",
      type: "heading",
      level: 2,
      text: "If you reach the wrong terminal, recover before you rush",
    },
    {
      id: "wrong-terminal-copy",
      type: "paragraph",
      text: "T2 and T3 are not a sensible luggage walk. First confirm that the flight terminal is truly wrong: check the operating carrier, current flight status and departure board, or ask airport staff. Then choose a documented landside connection. Do not ask a driver to take you to T1 because an old page still lists the airline there.",
    },
    {
      id: "recovery-list",
      type: "list",
      ordered: true,
      items: [
        "Stop and verify the exact flight; a codeshare or schedule change may explain the mismatch.",
        "If you are already checked in or making an airline-protected connection, contact the operating airline before leaving the current terminal.",
        "For a landside move, compare the airport's 24-hour T2–T3 inter-terminal shuttle with the one-stop intercity journey during rail operating hours.",
        "Carry passports, bookings, baggage receipts and the onward flight details with you; do not send one traveller away with the documents in another bag.",
        "After arriving at the correct terminal, locate the airline's current check-in or transfer desk and re-confirm the baggage status.",
      ],
    },
    {
      id: "terminal-transfer-copy",
      type: "paragraph",
      text: "Baiyun Airport's current terminal guide lists a 24-hour landside inter-terminal shuttle between T2 and T3, with stops in each terminal's transport centre and actual departure times managed on site. Guangdong Intercity provides a rail alternative between Baiyun Airport North and Baiyun Airport East during its operating hours. The short rail ride does not include finding the station, waiting, entering and leaving the fare gates, or reaching the next airline counter.",
    },
    {
      id: "airside-callout",
      type: "callout",
      title: "Do not assume there is a passenger airside train between T2 and T3",
      tone: "warning",
      body: "The airport's public passenger information documents landside shuttle and intercity options; it does not promise a self-directed airside link for every itinerary. Unless the operating airline confirms a protected airside process for your exact flights, plan for immigration, baggage collection or re-check, a landside terminal change and security wherever those steps apply.",
    },
    {
      id: "connections-heading",
      type: "heading",
      level: 2,
      text: "Changing terminals is not the same as making a protected flight connection",
    },
    {
      id: "through-ticket-copy",
      type: "paragraph",
      text: "A through itinerary can make a connection easier, but it does not prove that checked baggage will move automatically. At the first airport, confirm whether the onward boarding pass has been issued, read the final airport code on the baggage tag and ask whether immigration or customs in Guangzhou requires collection. Follow the operating airline's instructions for that exact connection.",
    },
    {
      id: "separate-ticket-copy",
      type: "paragraph",
      text: "With separate tickets, assume the risk sits with you unless both airlines explicitly say otherwise. The practical chain may include immigration permission, baggage claim, customs, a landside T2–T3 move, a new check-in deadline and security. No generic article can turn that chain into a guaranteed minimum connection time.",
    },
    {
      id: "connection-table",
      type: "table",
      caption: "What to establish before accepting a T2–T3 flight connection",
      columns: ["Ticket and baggage situation", "Ask the operating airline", "Time that is often omitted", "Planning stance"],
      rows: [
        [
          "One protected itinerary; baggage confirmed to final destination",
          "Which transfer desk and whether the airline provides an airside or escorted process",
          "Walking, document checks, border formalities and gate closing time",
          "Follow the airline's connection instructions, not a public-transport shortcut",
        ],
        [
          "One itinerary; baggage status unclear",
          "Whether the bag is through-checked to the final airport and, if not, whether it must be collected in Guangzhou",
          "Baggage claim, customs and re-check if the bag is not through-checked",
          "If staff cannot confirm through-checking, plan to collect and re-check",
        ],
        [
          "Separate tickets or self-transfer",
          "Whether either carrier accepts through-checking and who helps after a delay",
          "Every landside step plus the second airline's check-in deadline",
          "Plan as collection and re-check unless written confirmation says otherwise",
        ],
        [
          "International arrival connecting onward",
          "Entry, transit, customs, baggage and terminal procedure for the passport and route",
          "Immigration variability and any need to enter China",
          "Check eligibility separately; terminal transport does not grant entry permission",
        ],
      ],
    },
    {
      id: "late-heading",
      type: "heading",
      level: 2,
      text: "Late arrivals turn the terminal into an operating-hours decision",
    },
    {
      id: "late-copy",
      type: "paragraph",
      text: "The T2–T3 inter-terminal shuttle is listed as a 24-hour service, but metro, intercity rail and the Gaozeng–T3 Airport Line 2 branch are not. A scheduled landing time is not the time a traveller reaches ground transport: add immigration where applicable, baggage delivery and the walk to the correct pickup point. If the rail chain is likely to end before that, plan an official taxi or the terminal's current ride-hailing area instead.",
    },
    {
      id: "late-list",
      type: "list",
      items: [
        "Save the terminal, hotel name and destination address in Chinese before the flight.",
        "Check the last usable metro, intercity and bus departure for the date—not only the published landing time.",
        "Use the signed taxi queue or the airport's current designated ride-hailing pickup area; pickup levels can change.",
        "Tell the hotel about a late arrival and keep its front-desk phone number available offline.",
        "For a very early departure, check the full hotel-to-terminal plan against the airline's check-in deadline rather than assuming the first metro is early enough.",
      ],
    },
    {
      id: "people-heading",
      type: "heading",
      level: 2,
      text: "Let luggage and the people travelling break the tie",
    },
    {
      id: "traveller-grid",
      type: "comparison",
      title: "The same terminal map creates different best routes",
      columns: [
        {
          heading: "First time in China",
          items: [
            "Save T2 or T3 and the Chinese station name",
            "Keep the airport service number and airline contact available",
            "Prefer fewer handoffs over the lowest nominal fare",
          ],
        },
        {
          heading: "Family with children",
          items: [
            "Count lifts, queues and the bus transfer—not only ride time",
            "Keep one adult with the documents and one with the luggage",
            "Avoid a terminal change close to a separate-ticket deadline",
          ],
        },
        {
          heading: "Older parents or limited mobility",
          items: [
            "Ask the airline for airport assistance before travel",
            "Use a direct station or vehicle rather than stacking transfers",
            "Confirm wheelchair and baggage assistance with the responsible operator",
          ],
        },
        {
          heading: "Several large suitcases",
          items: [
            "Check lift access and the real station walk",
            "Do not treat the short T2–T3 rail ride as the total transfer",
            "Consider an official taxi when the group cannot move the bags together",
          ],
        },
      ],
    },
    {
      id: "luggage-copy",
      type: "paragraph",
      text: "The easiest-looking rail line can become the hardest route once the group must leave a platform and find another transport centre; after a landside terminal transfer, travellers may also need to pass security again. Choose the option the slowest traveller can complete while staying with the group. If airport assistance is needed, request it through the airline rather than assuming a driver or station attendant can provide the same service.",
    },
    {
      id: "verify-heading",
      type: "heading",
      level: 2,
      text: "What to recheck before leaving for Baiyun Airport",
    },
    {
      id: "final-checklist",
      type: "list",
      ordered: true,
      items: [
        "Exact flight number, date, operating carrier and T2 or T3 assignment",
        "Whether T1, Metro Airport South and intercity Baiyun Airport South remain suspended",
        "Live metro, Guangdong Intercity and Gaozeng–T3 Airport Line 2 branch operating times",
        "Current 24-hour inter-terminal shuttle stops and the next actual departure",
        "Baggage tag destination, onward boarding pass and any collection or re-check requirement",
        "Entry, transit and customs steps for the passport and itinerary",
        "Current taxi or ride-hailing pickup point if rail will not work",
        "Airline check-in and gate deadlines for that flight—not a generic airport rule",
      ],
    },
    {
      id: "fact-check-box",
      type: "callout",
      title: "Dynamic information reviewed August 11, 2026",
      tone: "neutral",
      body: "At this review, T1 passenger operations, Metro Airport South and intercity Baiyun Airport South were suspended; T2 had direct metro and intercity access; T3 had direct intercity access but no direct metro; and the airport published a 24-hour landside T2–T3 inter-terminal shuttle. Airline allocation, codeshares, rail timetables, bus stops and hours, pickup areas, baggage handling and border procedures remain travel-date checks. The airport lists its 24-hour service number as 020-96158. Within China, dial 020-96158; from outside China, use +86 20 96158, subject to your carrier's international-dialling format.",
    },
    {
      id: "help-callout",
      type: "callout",
      title: "Need a human check on the handoff?",
      tone: "decision",
      body: "Send the travel date, exact flight numbers, party size, luggage, onward hotel or train and approximate budget. Homeground can help identify where the terminal-to-hotel or terminal-to-train chain becomes risky, with live transport still rechecked for the date.",
    },
    {
      id: "internal-links",
      type: "internal-links",
      title: "Continue planning the whole transfer day",
      items: [ { label: "Guangzhou destination hub", href: "/destinations/guangzhou/", description: "Decide whether the city gets nights, then choose the terminal, the station and the base together." },
        {
          label: "Check whether a transit route is actually allowed",
          href: "/guides/china-240-hour-visa-free-transit-route-check/",
          description: "Airport transport and permission to enter China are separate questions.",
        },
        {
          label: "See whether the wider itinerary is too rushed",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Count terminal, station and hotel handoffs as part of the travel day.",
        },
        {
          label: "Plan China with older parents",
          href: "/guides/china-itinerary-with-older-parents/",
          description: "Build around walking, lifts, luggage and recovery time.",
        },
        {
          label: "Decide where human help is useful",
          href: "/guides/do-you-need-a-tour-guide-in-china/",
          description: "Use local support selectively instead of adding it to every step.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources, image credits and review record",
      items: [
        {
          label: "T1 airlines relocated to T3 and T1 rail stops suspended from May 7",
          url: "https://www.eguangzhou.gov.cn/gzlatest/content/post_42957.html",
          publisher: "Foreign Affairs Office of Guangzhou Municipal Government",
          reviewedAt: "2026-08-10",
        },
        {
          label: "T1 closure follow-up and T3 passenger guide",
          url: "https://www.eguangzhou.gov.cn/gzlatest/content/post_43024.html",
          publisher: "Foreign Affairs Office of Guangzhou Municipal Government",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Current Baiyun Airport terminal-to-terminal transport guide",
          url: "https://www.baiyunairport.com/byairport-web/guide/terminals?urlKey=terminals",
          publisher: "Guangzhou Baiyun International Airport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Current Baiyun Airport ground transport guide",
          url: "https://www.baiyunairport.com/byairport-web/traffic/index?urlKey=to-from-airport",
          publisher: "Guangzhou Baiyun International Airport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Current Baiyun Airport airline and terminal directory",
          url: "https://www.baiyunairport.com/byairport-web/flight/airlines?urlKey=airlines",
          publisher: "Guangzhou Baiyun International Airport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Current Baiyun Airport same-day flight search",
          url: "https://www.baiyunairport.com/byairport-web/index",
          publisher: "Guangzhou Baiyun International Airport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Official T3 transport guide from February 13; Airport South references superseded May 7",
          url: "https://www.gz.gov.cn/zwfw/zxfw/jtfw/content/post_10690829.html",
          publisher: "People's Government of Guangzhou Municipality",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Gaozeng–T3 Airport Line 2 branch snapshot published May 8",
          url: "https://www.eguangzhou.gov.cn/gzservice/content/post_42999.html",
          publisher: "Foreign Affairs Office of Guangzhou Municipal Government",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Official Guangdong Intercity station naming approval",
          url: "https://td.gd.gov.cn/attachment/0/412/412307/3220064.pdf",
          publisher: "Department of Transport of Guangdong Province",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Guangzhou South hub and airport intercity opening guide",
          url: "https://jtj.gz.gov.cn/xwdt/tpxw/content/post_10462631.html",
          publisher: "Guangzhou Municipal Transportation Bureau",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Guangdong Intercity timetable change effective March 15 and current T3 rail access",
          url: "https://www.gz.gov.cn/zwfw/zxfw/jtfw/content/post_10726817.html",
          publisher: "People's Government of Guangzhou Municipality",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Hero image: Baiyun Airport East concourse by Tim Wu, CC BY-SA 4.0; cropped and converted to WebP",
          url: "https://commons.wikimedia.org/wiki/File:Concourse,_Baiyun_Airport_East_Railway_Station,_PRDIR_20251221.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Body image: Baiyun Airport East entry gates by Jacky Cheung, CC BY-SA 4.0; cropped and converted to WebP",
          url: "https://commons.wikimedia.org/wiki/File:Entry_Faregates_at_Baiyun_Airport_East_Railway_Station_20251112.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
