import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body: StructuredPageBody = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead-answer",
      type: "lead",
      text: "“Is the Harbin Ice and Snow Festival open?” is really four questions wearing one coat: which venue, what operating state, whose announcement, and as of when. The festival umbrella, the Ice-Snow World park, the Sun Island snow expo and smaller ice lantern sites open on different dates and fail separately. This page gives you a repeatable verification chain — province culture-tourism announcements first, the operator's own site and hotline second, official ticket platforms third — plus a status table for reading any bulletin you find.",
    },
    {
      id: "first-steps",
      type: "list",
      ordered: true,
      items: [
        "Name the exact venue you mean: Ice-Snow World (冰雪大世界), Sun Island Snow Expo (雪博会), Zhaolin Park lanterns, or “the festival” as a whole — they publish separately.",
        "Check the Heilongjiang provincial culture-and-tourism department (wlt.hlj.gov.cn) and Harbin municipal channels for that venue's opening announcement; treat it as the authoritative signal.",
        "Cross-check on the operator's own property: ice.hrbicesnow.com and its season sub-sites carry ticket policy and hours, with hotline 400-639-1999.",
        "Look at official ticketing presence (the operator's WeChat store plus major platforms): tickets on sale usually means opening is confirmed or imminent.",
        "Within 72 hours of your visit, re-check same-day notices: cold snaps, wind or warm spells trigger single-day or partial closures.",
        "Distrust last year's dates: each season announces its own calendar, and trial-operation days differ from full opening.",
        "Write down plan B indoor venues now, not when you are standing in -20°C wind.",
      ],
    },
    {
      id: "states-heading",
      type: "heading",
      level: 2,
      text: "Eight states people confuse",
    },
    {
      id: "states-table",
      type: "table",
      caption: "What each status actually means for your day",
      columns: ["Status", "Meaning", "What you can rely on"],
      rows: [
        ["Festival umbrella announced", "The citywide season concept with a ceremony date", "Little by itself — individual venues still publish separately"],
        ["Construction / build phase", "Ice blocks being cut and stacked", "Nothing about public access; do not travel on rumours"],
        ["Trial operations (试运营)", "Park soft-opens with partial attractions, sometimes limited tickets", "Only what the notice lists; rides and zones may rotate"],
        ["Official opening (开园)", "Full park operations begin, announced by operator/government", "Standard ticketing and hours from that date onward"],
        ["Tickets on sale", "Sales window opened on official channels", "Strong evidence opening is real — verify the seller is official"],
        ["Partial facility closure", "Park opens but named rides/zones shut", "Check which attractions before buying express products"],
        ["Single-day temporary closure", "Weather/safety shutdown for one day", "Reconfirmation next morning; tickets usually follow refund rules"],
        ["Season end", "Thaw dismantling begins", "Dates vary with the weather — never assume a fixed closing year to year"],
      ],
    },
    {
      id: "chain-heading",
      type: "heading",
      level: 2,
      text: "The official verification chain",
    },
    {
      id: "chain-table",
      type: "table",
      caption: "Run top-down; stop at the first authoritative answer",
      columns: ["Layer", "Who", "What you get"],
      rows: [
        ["1. Government announcement", "Heilongjiang culture-tourism dept (wlt.hlj.gov.cn), Harbin municipal releases", "Season opening dates, ceremony facts — the signal other media copy"],
        ["2. Operator properties", "ice.hrbicesnow.com, season sub-sites, official WeChat account, hotline 400-639-1999", "Ticket policy, hours, attraction lists, closure notices"],
        ["3. Official ticket platforms", "Operator WeChat store; major named platforms per operator announcements", "Live sale windows — proof of an open or imminent state"],
        ["4. Weather authorities", "Local forecast services", "Basis for same-day closures; not an opening authority"],
        ["5. On-site day notice", "Park entrances and the service mini-program", "Final word on today's partial closures"],
      ],
    },
    {
      id: "example-heading",
      type: "heading",
      level: 2,
      text: "How a real announcement looked (dated example)",
    },
    {
      id: "example-para",
      type: "paragraph",
      text: "For its 27th season, the Ice-Snow World's 17 December 2025 opening was announced by the provincial culture-and-tourism department and carried by national media, with ticketing through the operator's WeChat store and major platforms; early-window and standard adult pricing were published on the operator's own site alongside free-entry reservation rules with a daily quota. That pattern is the point of this example — government announces, operator details, platforms sell — not the dates themselves. Next season gets its own announcement; last season's calendar proves nothing about this one.",
    },
    {
      id: "timeline-heading",
      type: "heading",
      level: 2,
      text: "When to check what",
    },
    {
      id: "timeline-table",
      type: "table",
      caption: "A five-touch verification rhythm",
      columns: ["When", "Check", "Decision it feeds"],
      rows: [
        ["Planning stage (months out)", "Last season's pattern + any early government notices", "Which week to target; realistic expectations about trial days"],
        ["Before buying flights/hotels", "Government/operator channels for THIS season's first announcement", "Whether your window matches announced openings"],
        ["One week before arrival", "Operator site/WeChat for hours, tickets-on-sale status, attraction list", "Whether to pre-buy; which express products make sense"],
        ["72 hours before", "Same-day notices begin appearing; weather outlook", "Backup indoor plan activation threshold"],
        ["Departure morning", "Venue hotline / mini-program / entrance notices", "Go / switch venue / switch day"],
      ],
    },
    {
      id: "backup-heading",
      type: "heading",
      level: 2,
      text: "The backup framework",
    },
    {
      id: "backup-list",
      type: "list",
      items: [
        "Indoor anchors that do not depend on ice weather: Harbin's major museums and the historic Russian-built quarter around Central Street.",
        "Hot-spring and indoor pool venues popular in winter itineraries.",
        "Neighbouring snow towns and ski areas operate their own calendars — verify them separately, never assume they share the city park's status.",
        "Food architecture: a planned long lunch converts a frozen morning into a workable day.",
        "If everything outdoor closes, rebooking one day later is often cheaper than abandoning Harbin entirely — closures are usually short.",
      ],
    },
    {
      id: "venues-heading",
      type: "heading",
      level: 2,
      text: "Know the venues before you verify",
    },
    {
      id: "venues-para",
      type: "paragraph",
      text: "“The festival” is an umbrella over several properties that publish independently. The Ice-Snow World on the Songhua's north bank is the flagship light-and-sculpture park with the big slides. The Sun Island Snow Expo across the river focuses on monumental snow sculpture and usually follows its own build-and-open rhythm. Zhaolin Park in Daoli keeps the older, smaller lantern tradition. Around the province, snow towns and ski fields run yet more calendars. When any source says “Harbin is open”, your first question is which of these it means — a headline about the lantern park tells you nothing about slide queues, and vice versa.",
    },
    {
      id: "wechat-heading",
      type: "heading",
      level: 2,
      text: "Living inside the operator's own channels",
    },
    {
      id: "wechat-para",
      type: "paragraph",
      text: "Most authoritative status lives in Chinese-first channels: the operator's WeChat account and mini-program carry ticketing store, queue information and same-day notices; the website mirrors policy pages in plainer form; the hotline answers what neither shows. Foreign visitors typically work around this by using the web ticket flow through major platforms named in operator announcements, then verifying anything unusual — refunds, free-entry quotas, attraction closures — against the hotline before travel day. Save the hotline number and the official site into your phone at planning stage, not at the bus stop.",
    },
    {
      id: "scenarios-heading",
      type: "heading",
      level: 2,
      text: "Three composite scenarios",
    },
    {
      id: "scenario-a-heading",
      type: "heading",
      level: 3,
      text: "Mid-December visitor meets trial days",
    },
    {
      id: "scenario-a",
      type: "paragraph",
      text: "A traveller lands in the second week of December chasing photos of the finished park. The chain shows trial-operation notices with a partial attraction list and no full-opening date yet. Honest options: visit on a trial day accepting that headline rides may rotate, or shift lodging later toward the announced opening. What they must not do is book non-refundable park products from resellers claiming “fully open” — the operator's own channels are the only list that counts.",
    },
    {
      id: "scenario-b-heading",
      type: "heading",
      level: 3,
      text: "Deep-winter cold snap",
    },
    {
      id: "scenario-b",
      type: "paragraph",
      text: "A January visitor wakes to a -28°C morning and an announcement that outdoor rides pause for the day while lights remain on. The status table's “partial facility closure” row applies: the evening light atmosphere can still justify entry for some travellers, while families with small children may prefer the indoor anchors plus a next-morning recheck. The decision input is which specific attractions shut, not the word “closed” itself.",
    },
    {
      id: "scenario-c-heading",
      type: "heading",
      level: 3,
      text: "Late-February thaw risk",
    },
    {
      id: "scenario-c",
      type: "paragraph",
      text: "A late-winter visitor hopes for sculptures in their final week. The verification chain matters most here: warm spells can compress closing dates earlier than any pattern suggests, and dismantling begins quietly zone by zone. Checking the operator channels within 72 hours — not reciting last year's closing week — is what separates a good finale visit from a demolition site.",
    },
    {
      id: "factors-heading",
      type: "heading",
      level: 2,
      text: "What moves openings — without predicting them",
    },
    {
      id: "factors-para",
      type: "paragraph",
      text: "Three forces genuinely move the calendar. Natural ice supply: the Songhua river freeze and harvest timing shape when builders can work, which is why seasons differ year to year. Build completion: a park this large opens in phases, and trial-operation days exist precisely because some attractions finish before others. Safety and weather on the day: extreme cold, wind or thaw can close rides or whole zones for a morning or a day. None of these can be predicted from an article — which is exactly why this page is a verification procedure instead of a dates list.",
    },
    {
      id: "scams-heading",
      type: "heading",
      level: 2,
      text: "Reading bulletins without being fooled",
    },
    {
      id: "scams-list",
      type: "list",
      items: [
        "A screenshot of last season's opening notice is not this season's status — check the date inside the image.",
        "Resellers announcing “official opening” before any government or operator channel does is marketing, not authority.",
        "Trial operation ≠ full opening: if your must-do attraction is the big slides or the ferris wheel, confirm those specific items are in the trial list.",
        "Free-entry quotas (when offered) usually require advance reservation in the official store with document checks at the gate — budget that step.",
        "Third-party “skip-the-line” products are not operator policy; verify against the operator's own price page.",
      ],
    },
    {
      id: "recovery-heading",
      type: "heading",
      level: 2,
      text: "Failure recovery",
    },
    {
      id: "recovery-table",
      type: "table",
      caption: "When your plan meets reality",
      columns: ["Situation", "Do first", "Then"],
      rows: [
        ["Arrived; park closed today", "Confirm reopening expectation via hotline/mini-program", "Activate backup framework for today; shift the park to tomorrow morning"],
        ["Open but your key ride shut", "Check whether closure is single-day", "Decide between waiting a day versus visiting anyway for lights and builds"],
        ["Tickets not yet on sale for your date", "Watch official channels daily", "Hold refundable lodging; do not buy third-party 'guaranteed' tickets"],
        ["Only trial days overlap your trip", "Read exactly which zones the trial covers", "Go if your favourites are listed; otherwise weigh a later-week visit"],
        ["Extreme cold snap forecast", "Layer strategy + indoor anchors", "Shorten outdoor blocks to 40–60 minutes with warm-up stops"],
      ],
    },
    {
      id: "states-intro",
      type: "paragraph",
      text: "Read any bulletin against this table before acting. The rows are ordered roughly by how a season unfolds: announcements and construction come first, trial operations bridge into an official opening, tickets open somewhere in between, and closures appear only after something is running. Most traveller mistakes are category errors — treating a festival ceremony date as a park opening, or a trial day as full service — rather than wrong facts.",
    },
    {
      id: "delegate-heading",
      type: "heading",
      level: 2,
      text: "Who can check status on your behalf",
    },
    {
      id: "delegate-list",
      type: "list",
      items: [
        "Your Harbin hotel front desk calls the venue hotline daily in season; ask the night before and again at breakfast.",
        "Licensed local guides track operator notices as part of their job; independent verification still costs you one screenshot.",
        "The operator mini-program's queue and notice sections update faster than any third-party app.",
        "Official ticket platforms push closure notices to buyers — another reason to buy through channels the operator itself names.",
      ],
    },
    {
      id: "refund-heading",
      type: "heading",
      level: 2,
      text: "If a closure hits after you bought",
    },
    {
      id: "refund-para",
      type: "paragraph",
      text: "Closure-day refunds follow the seller's published rules, which is why the verification chain insists on official sellers: operator-store purchases and major platforms carry documented refund paths, while grey-market tickets may promise everything and document nothing. Keep your order number, the closure announcement screenshot with its timestamp, and the payment reference together; that trio is what any legitimate refund conversation requires. Where a same-day closure is announced by the operator, rebooking to a later date is often smoother than refunding — but read the specific policy attached to your product rather than assuming either outcome.",
    },
    {
      id: "dynamic-boundary",
      type: "callout",
      tone: "warning",
      title: "This page verifies; it does not announce",
      body: "Every date, price and quota mentioned here is a dated historical example reviewed August 2026. Each new season publishes its own calendar through the chain above. Nothing here predicts next winter's dates, prices or hours.",
    },
    {
      id: "scope",
      type: "callout",
      tone: "neutral",
      title: "What this guide covers",
      body: "One task: verifying Harbin ice-season status across venues, states and channels. It does not rank venues, plan itineraries, quote live ticket inventory, or replace the announcements themselves.",
    },
    {
      id: "more-planning",
      type: "internal-links",
      title: "Related planning guides",
      items: [
        {
          label: "Public holidays and crowd pressure",
          href: "/guides/china-public-holidays-travel-calendar/",
          description: "Why late-December and early-January dates behave differently.",
        },
        {
          label: "Shoulder-season value trade-offs",
          href: "/guides/china-shoulder-season-value-tradeoff/",
          description: "What moving a week buys or costs in winter destinations.",
        },
        {
          label: "China climate regions for trip timing",
          href: "/guides/china-climate-regions-for-trip-timing/",
          description: "Where Harbin's winter sits among China's climate zones.",
        },
        {
          label: "Power banks, flights and trains",
          href: "/guides/china-power-bank-rules-flights-trains/",
          description: "Winter gear and battery rules before you board for the north.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        {
          label: "Heilongjiang Provincial Department of Culture and Tourism — 27th season opening announcement (dated historical example)",
          url: "https://wlt.hlj.gov.cn/wlt/c114169/202512/c00_31897123.shtml",
          publisher: "Heilongjiang Culture and Tourism Department",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Harbin Ice-Snow World operator site — ticket policy, hours, hotline",
          url: "https://ice.hrbicesnow.com/",
          publisher: "Harbin Ice & Snow World Co.",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Xinhua News — season opening corroboration (dated example)",
          url: "https://www.news.cn/local/20251215/18f2ae42d2054668a57b98440a1732be/c.html",
          publisher: "Xinhua",
          reviewedAt: "2026-08-22",
        },
      ],
    },
  ],
} satisfies StructuredPageBody;

export default body;
