import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "구이린과 양숴에는 각각 여러 출발·도착 지점이 있습니다. 구이린에는 공항과 여러 기차역이 있고, 양숴역은 대부분의 양숴 숙소와 떨어진 싱핑에 있습니다. 리강 유람선을 이용하려면 출발 선착장과 수하물 계획도 따로 세워야 합니다." },
  { id: "answer", type: "callout", title: "양쪽 주소와 하루의 목적을 기준으로 선택한다", tone: "decision", body: "문 앞 이동과 짐이 가장 중요하면 도로 이동을 비교한다. 정확한 역을 맞추고 양숴에서 숙소까지 갈 차량을 정한 뒤에 열차를 비교한다. 리강 자체를 하루의 경험으로 삼고 싶을 때 유람선을 선택하며, 지도상 빠른 셔틀처럼 보인다는 이유로 고르지 않는다." },
  { id: "matrix-heading", type: "heading", level: 2, text: "소요 시간 하나로 비교할 수 없는 세 가지 이동 방식" },
  { id: "matrix", type: "table", caption: "각 선택은 다른 곳에서 시작하고 끝난다", columns: ["선택", "잘 맞음", "빠진 구간", "확인"], rows: [
    ["양숴역 열차", "직통 열차나 편리한 구이린역과 연결", "양숴 쪽 역에서 호텔까지 도로 이동", "정확한 역, 당일 열차와 확인된 픽업"],
    ["사전 예약 차량 또는 현재 운행하는 정기 교통", "공항/호텔 양쪽, 가족이나 여러 가방", "도로, 정확한 승차와 여러 하차 지점", "현재 운영사, 양쪽 위치, 짐과 체크인 마감"],
    ["리강 관광 유람선", "강 여행 자체가 하루의 목적일 때", "구이린 쪽 선착장 접근, 편도 유람선의 짐 보관 부재와 도착 뒤 호텔 이동", "모판산 또는 주장 출발, 룽터우산 도착, 운항일과 공지"],
  ]},
  { id: "warning", type: "callout", title: "양숴역은 대부분의 양숴 숙소 바로 옆이 아니다", tone: "warning", body: "구매 전에 역과 숙소를 따로 표시한다. 구이린 출발역이나 양숴의 마지막 도로 이동이 맞지 않으면 짧은 열차 구간의 장점이 사라진다." },
  { id: "direction-heading", type: "heading", level: 2, text: "강 관광은 방향이 중요하다" },
  { id: "direction", type: "paragraph", text: "리강 공식 안내에 따르면 핵심 유람선은 약 60km, 약 4시간의 편도 일정이다. 3성급 유람선은 모판산 여객항, 4성급 유람선은 주장 여객항에서 출발하며 모두 양숴 룽터우산 선착장에 내린다. 구이린의 두 출발항은 서로 다른 장소이고 왕복 교통편도 아니다." },
  { id: "groups", type: "comparison", title: "여행자에 맞는 연결", columns: [
    { heading: "공항 도착", items: ["항공 지연에 대비한 여유 확보", "도로가 두 번의 환승을 줄일 수 있음", "늦으면 호텔에 알리기"] },
    { heading: "철도 통과", items: ["정확한 양숴 정차 검색", "역 픽업 확인", "이유 없이 구이린 시내로 우회하지 않기"] },
    { heading: "풍경과 여유", items: ["강을 하루의 목적으로", "짐 보관이 있다고 가정하지 않기", "날씨와 수위에 따른 대안 유지"] },
  ]},
  { id: "address-heading", type: "heading", level: 2, text: "구매 전에 양쪽 지점 표를 만드세요" },
  { id: "address-copy", type: "paragraph", text: "왼쪽에는 정확한 구이린 공항, 철도역, 호텔, 유람선 부두를 쓰고 오른쪽에는 정확한 양숴 호텔, 양숴역, 룽터우산 부두를 씁니다. 각 선택에 첫 도로 구간, 체크인이나 역 입장, 주 교통편, 마지막 도로·도보 구간과 귀로를 더합니다. 그러면 두 역 이동을 빼고 철도 시간표를 전용차와 비교하거나, 4시간 강 체험의 가치를 빼고 관광선을 단순 도로 이동과 비교하는 흔한 오류가 드러납니다." },
  { id: "cruise", type: "callout", title: "유람선을 고르기 전에 짐을 해결하세요", tone: "warning", body: "공식 안내는 핵심 유람선에 짐 보관 서비스가 없고 출발 부두까지와 양숴 이후 교통도 포함되지 않는다고 설명합니다. 구이린 호텔이 큰 가방을 맡는지 묻고, 별도 수하물 운송은 이름과 책임이 명확한 업체에만 맡기세요. 또는 짐은 일행과 도로로 옮기고 유람선은 다른 날 이용할 수 있습니다. 부두에 도착해서 임시 보관함이나 차량을 기대하지 마세요." },
  { id: "mode-heading", type: "heading", level: 2, text: "각 선택의 가장 약한 구간을 시험하세요" },
  { id: "mode-matrix", type: "table", caption: "주 교통편이 가장 약한 구간인 경우는 드뭅니다", columns: ["선택", "확인할 가장 약한 구간", "실용 대안"], rows: [
    ["철도", "싱핑의 양숴역에서 정확한 호텔까지", "미리 정한 합법 픽업 또는 원래 출발지부터 도로 이동"],
    ["도로 차량", "확정 차량, 픽업, 수하물 용량, 늦은 호텔 도착", "호텔이 돕는 대체 차량 또는 도착 쪽 숙박"],
    ["리강 유람선", "구이린 출발 부두 접근, 짐, 룽터우산 이후 교통", "운항·날씨·짐 조건 실패 시 도로 이동"],
    ["정기 지역 교통", "현재 운영사, 정확한 정류장, 막차, 짐 허용", "이름 있는 합법 차량; 표시 없는 길가 호객은 제외"],
  ]},
  { id: "return-heading", type: "heading", level: 2, text: "귀로는 왕로 체험에 의존하지 않아야 합니다" },
  { id: "return-plan", type: "list", ordered: true, items: ["숙박한다면 도착 지점으로 자동 복귀하지 말고 정확한 픽업 주소와 호텔 프런트를 확인합니다.", "당일치기는 예약한 열차·항공·도로편과 실제 마지막 이동에 맞춰 양숴 출발 시각을 정합니다.", "전체 중국어 역명, 부두, 호텔명을 오프라인으로 저장해 기사와 직원에게 보여줍니다.", "날씨가 강 일정을 바꾸면 마감 없이 기다리지 말고 미리 확인한 도로·철도 구조로 전환합니다.", "별도 환불 불가 항공편을 단방향 관광선과 불확실한 도로 귀환 직후에 두지 않습니다."] },
  { id: "recovery-heading", type: "heading", level: 2, text: "양쪽 위치가 맞지 않을 때" },
  { id: "recovery", type: "list", ordered: true, items: ["예약의 전체 역, 선착장 또는 정류장명을 읽는다.", "정확한 호텔 위치를 정식 운영사에 보낸다.", "교통을 바꾸기 전에 체크인과 다음 고정 열차 일정을 먼저 확인한다.", "실시간 변경은 철도와 현지 교통 공식 공지로 확인한다.", "양숴라고 적힌 이름 없는 길가 차량을 타지 않는다."] },
  { id: "facts", type: "callout", title: "변경 가능 정보 확인일: 2026년 8월 13일", tone: "neutral", body: "리강 공식 안내는 핵심 유람선을 약 60km, 약 4시간의 편도 일정으로 설명하며 3성급과 4성급 유람선의 출발항이 다르고 도착지는 양숴 룽터우산 선착장이라고 안내한다. 공식 안내는 성수기에는 적어도 하루 전 구매를 권하며, 선착장까지 가는 교통과 양숴에서 돌아오는 교통은 포함되지 않고 편도 유람선에 짐 보관 서비스가 없다고 밝힌다. 열차 정차는 날짜별로 12306에서 확인해야 한다. 양숴역에서 숙소까지의 현재 공식 고정 시간표나 요금은 찾지 못했으므로 오래된 가격이나 시간에 기대지 말고 따로 확인한다." },
  { id: "help", type: "callout", title: "양쪽 목적지를 비교할까요?", tone: "decision", body: "날짜, 구이린 도착 지점, 양숴 호텔, 인원, 짐과 강 이동이 교통인지 경험인지 보내 주세요. Homeground는 각 이동 구간을 비교하고 출발 전에 다시 확인할 정보를 정리해 드릴 수 있습니다." },
  { id: "links", type: "internal-links", title: "계속 계획하기", items: [
    { label: "중국 고속철도 첫 이용 안내", href: "/ko/guides/china-high-speed-train-first-time-guide/", description: "역을 고른 뒤 철도를 준비합니다." },
    { label: "중국 일정이 너무 빠듯한가요?", href: "/ko/guides/is-your-china-itinerary-too-rushed/", description: "강이나 도로 하루에 충분한 공간을 둡니다." },
    { label: "중국 여행자 결제", href: "/ko/guides/how-to-pay-in-china-as-a-tourist/", description: "마지막 구간의 결제 대안을 둡니다." },
    { label: "중국 호텔과 지하철", href: "/ko/guides/china-hotel-near-metro/", description: "역 이름이 숙소에 언제 도움이 되는지 봅니다." },
  ]},
  { id: "sources", type: "sources", title: "공식 출처와 사진 표기", items: [
    { label: "리강 교통과 선착장 공식 안내", url: "https://en.liriver.com.cn/page/article/lyfw.jtcx", publisher: "구이린 리강 풍경명승구", reviewedAt: "2026-08-13" },
    { label: "리강 공식 구매 채널", url: "https://en.liriver.com.cn/page/article/lyfw.pwxx", publisher: "구이린 리강 풍경명승구", reviewedAt: "2026-08-13" },
    { label: "편도 운항, 후속 교통과 짐 보관 부재에 관한 공식 안내", url: "https://www.liriver.com.cn/page/article/zxlj.jqdt/126", publisher: "구이린 리강 풍경명승구", reviewedAt: "2026-08-13" },
    { label: "철도 공식 예매 채널", url: "https://www.12306.cn/en/index.html", publisher: "중국철도 12306", reviewedAt: "2026-08-13" },
    { label: "양숴역 연결 도로가 싱핑진에 있음을 확인하는 공식 토지 공고", url: "https://dnr.gxzf.gov.cn/villageNews/show/450321?id=1240", publisher: "광시좡족자치구 자연자원청", reviewedAt: "2026-08-13" },
    { label: "대표 사진: Rat2의 양숴역, CC BY-SA 4.0, 크롭 편집", url: "https://commons.wikimedia.org/wiki/File:Yangshuo_Railway_Station_202102.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" },
    { label: "대표 사진 편집본 라이선스: CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/", publisher: "Creative Commons", reviewedAt: "2026-08-12" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
