import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {"schemaVersion":"1.0.0","blocks":[
{"id":"lead","type":"lead","text":"Read an archaeological site museum by connecting place, layer, findspot, object and conservation decision—not by counting complete artefacts or standing walls. Start with the site plan, identify what is genuinely in situ, follow one excavated group into the exhibition, and separate recorded facts from interpretation. Covered, backfilled or closed remains still carry evidence; they require a different route through it."},
{"id":"answer","type":"callout","title":"The short answer: follow an evidence chain","body":"Read in this order: site → chronology and layer → original position → related objects → conservation → interpretation and uncertainty. If one link is unavailable, reconnect it with an official plan, section drawing, model or findspot label. Never enter a restricted area.","tone":"decision"},
{"id":"boundary-heading","type":"heading","level":2,"text":"First identify what kind of institution you have entered"},
{"id":"boundary","type":"paragraph","text":"China does not use one layout for every archaeological site museum, while terms such as site museum, on-site museum and archaeological park can overlap. Official national-park rules join protection, archaeology, research, interpretation, public service and monitoring, but that designation does not cover every site museum. A venue may cover remains, stand beside a site, interpret a larger landscape or include non-public research spaces. The public route is not permission to enter an excavation or conservation workspace."},
{"id":"models-heading","type":"heading","level":2,"text":"Four arrangements change how you should look"},
{"id":"models","type":"table","caption":"Identify the arrangement before evaluating the display","columns":["Arrangement","Begin with","Important limit"],"rows":[["Protective hall over in-situ remains","Locate the excavation grid, preserved surfaces, sections and viewing boundary.","A shelter is part of conservation; it is not proof that active digging is visible."],["Museum beside the site","Connect objects to the site plan and their labelled findspots before reading them as art.","Nearby does not mean every displayed object came from the ground outside that building."],["Museum plus distributed ruins park","Use the museum model first, then recognise earthworks, waterways, platforms or marked underground remains.","The ticketed visitor area may be only one part of a much larger archaeological landscape."],["Research or conservation spaces","Read condition records, treatment explanations and viewing windows from designated public areas.","A laboratory, store or excavation zone may remain closed even when the museum is open."]]},
{"id":"workflow-heading","type":"heading","level":2,"text":"Use one repeatable viewing workflow"},
{"id":"workflow","type":"list","ordered":true,"items":["Check the current official notice for which site, exhibition and visitor-route components are open; use the venue's own guidance for tickets, hours and transport.","Find the whole-site plan before a famous object. Mark the settlement, cemetery, palace, workshop, water system or other identified zones.","Build a chronology: do the visible layers and displayed finds belong to one occupation, several phases or later disturbance?","Separate original in-situ remains, excavated and moved objects, reconstruction, and digital or physical models.","Choose one feature or object group with a documented findspot. Follow it into the display instead of collecting unrelated highlights.","Read what lay above, below, beside or inside it and whether the museum explains that relationship.","Find the conservation intervention—support, controlled light, shelter, drainage, backfilling, replacement material or restricted access—and separate it from ancient fabric.","Finish with one supported conclusion and one unresolved question. A good visit need not produce a complete story."]},
    {
      id: "site-to-label-evidence-chain",
      type: "table",
      caption: "Homeground site-to-label evidence chain: identify where certainty changes",
      columns: ["Link", "Responsible evidence", "Visitor check", "Safe conclusion"],
      rows: [
        ["Site and layer", "Excavation records, plans and stratigraphy", "Can the label locate the find in a layer or feature?", "The object or remain belongs to a recorded context"],
        ["Findspot to object", "Inventory number, association and sampling", "Is this object from this site, nearby, or comparative?", "Keep associated and illustrative material separate"],
        ["Object to conservation", "Condition report, treatment and replacement record", "Which parts are ancient, restored, supported or replicated?", "Visible completeness is not original completeness"],
        ["Conservation to interpretation", "Research question, reconstruction method and uncertainty", "Does the panel mark evidence, inference and unresolved alternatives?", "A reconstruction is a tested interpretation, not a photograph of the past"],
        ["Interpretation to your claim", "Exact label, date and source trail", "How far does this one site support the conclusion?", "State the site-level finding before any regional generalisation"],
      ],
    },
{"id":"labels-heading","type":"heading","level":2,"text":"Six label fields make an object archaeological evidence"},
{"id":"labels","type":"table","caption":"What to record from a label or official interpretation","columns":["Field","Question","Why it changes the reading"],"rows":[["Material and date","What is it made from, and is the date exact, ranged or relative?","The dating method and confidence may differ from the display headline."],["Exact provenience","Which site area, grave, pit, building, layer or excavation unit produced it?","A named region is less precise than a recorded archaeological context."],["Association","Which remains or objects were found with it?","Relationships may reveal activity, deposition or sequence better than beauty does."],["Original or reconstructed","Is this the excavated material, a restored whole, a replica or an interpretive model?","Reconstruction can explain form but must not be mistaken for in-situ survival."],["Treatment status","Was it consolidated, supported, reassembled, moved or reburied?","What you see now may combine ancient material with necessary conservation work."],["Confidence language","Does the label say shows, suggests, probably, possibly or remains debated?","Those words separate evidence from an institution's current interpretation."]]},
{"id":"evidence-heading","type":"heading","level":2,"text":"Keep three evidence levels separate"},
{"id":"evidence","type":"comparison","title":"Do not turn a plausible interpretation into a fact","columns":[{"heading":"Recorded or observable","items":["Layer, excavation unit and find position","Material, dimensions and visible condition","Marked boundary between original and replacement"]},{"heading":"Interpreted","items":["Probable date, function or social meaning","Reconstructed building, burial or activity","Relationship to a wider settlement or exchange network"]},{"heading":"Unresolved or revisable","items":["A person's identity without direct evidence","One final use for an ambiguous space or object","The complete extent of an unexcavated or inaccessible area"]}]},
{"id":"scenarios-heading","type":"heading","level":2,"text":"Two common visits where the evidence looks disappointing"},
{"id":"scenarios","type":"comparison","title":"Change method instead of declaring that there is nothing to see","columns":[{"heading":"The landscape looks like earth and grass","body":"Standing stone is not the standard for archaeological value. Use contour changes, platform edges, post-hole markers, waterways and section drawings to reconstruct scale and sequence. Compare the landscape with the museum model, then identify which zones remain buried for protection or future research. Do not treat a replica outline as an exposed wall."},{"heading":"The key area is closed, covered or backfilled","body":"A closure can reflect safety, weather, research or conservation; backfilling can be an intentional protective measure. At Jinsha, the museum documents one elephant-tusk pit that was backfilled when effective in-situ protection was unavailable. Use the official plan, excavation photographs, exhibition objects and conservation explanation as substitutes, and describe the condition only for your visit date."}]},
{"id":"conservation-heading","type":"heading","level":2,"text":"Conservation is evidence, not backstage decoration"},
{"id":"conservation","type":"paragraph","text":"Excavation changes a feature's environment, and earth, waterlogged organics, pigments, wood, metal and stone respond differently. A shelter must balance moisture, temperature, light, drainage, structural load, access and interpretation. Supports, dim light, monitors or an apparently unfinished surface may show a treatment choice. Ask what risk it addresses and what it obscures; more exposure is not automatically better."},
{"id":"conditions-heading","type":"heading","level":2,"text":"Conditions that should change your plan or conclusion"},
{"id":"conditions","type":"table","caption":"When the same method needs a different emphasis","columns":["Condition","Adjust the visit","Do not conclude"],"rows":[["No in-situ display","Prioritise plans, findspot records and links between galleries and the protected site.","That the institution is not a site museum."],["Reconstruction dominates","Find the legend for original, restored and hypothetical material before photographing details.","That every visible wall or roof is ancient."],["Only part of the site is open","Study the whole-site map, then state exactly which component you visited.","That the visitor route equals the entire archaeological property."],["Little English interpretation","Photograph permitted object numbers and bilingual headings, then check the museum's official digital material later.","That an app or unofficial post overrides the on-site label."],["Limited time, heat or mobility","Choose one site-to-object chain and a safe turnaround instead of chasing every zone.","That crossing barriers is necessary for a meaningful visit."]]},
{"id":"recovery-heading","type":"heading","level":2,"text":"Recover when the expected evidence is unavailable"},
{"id":"recovery","type":"table","caption":"A five-stage recovery chain","columns":["Problem","Next action"],"rows":[["Hall or site component is closed","Confirm the dated official notice and ask which public exhibition, model or viewing route still explains that component."],["Famous object is absent","Use the catalogue number or findspot to follow its archaeological group; do not substitute an unlabeled lookalike."],["Original and reconstruction are unclear","Find the plan legend, material change, caption or staff explanation and record the uncertainty if none is supplied."],["You cannot connect an object to the site","Return to the site map and select a better-documented feature or group instead of guessing its provenience."],["The visit still feels incomplete","Leave with the supported chain you established, save the source and visit date, and treat missing evidence as a limit—not an invitation to enter a closed zone."]]},
{"id":"checklist-heading","type":"heading","level":2,"text":"A final evidence checklist"},
{"id":"checklist","type":"list","items":["I know whether the museum is over, beside or interpreting a distributed archaeological site.","I can name the site component and period I actually viewed.","I separated in-situ fabric, moved objects, restoration, replicas and reconstruction.","I traced at least one feature or object group to a documented findspot.","I noted one association or layer relationship, not only an object name.","I identified one conservation decision and the risk it addresses.","I kept an official interpretation separate from what was directly recorded.","I recorded one uncertainty and respected every barrier and closure."]},
{"id":"warning","type":"callout","title":"Recheck the real venue, not this generic method","body":"Open components, routes, displays and conservation sightlines can change. Use a museum, heritage authority or local-government source dated for your visit. This guide promises neither live excavation nor access to laboratories, named objects or restricted routes.","tone":"warning"},
{"id":"links","type":"internal-links","title":"Continue reading archaeological evidence","items":[{"label":"Sequence Liangzhu Museum and the ruins park","href":"/guides/liangzhu-ruins-park-and-museum-sequence/","description":"Apply a museum-to-landscape sequence at one specific heritage property."},{"label":"Read Nanhai No. 1 through cargo and conservation","href":"/guides/nanhai-one-shipwreck-cargo-and-conservation/","description":"Follow context from a shipwreck assemblage into continuing treatment."},{"label":"Read ritual bronzes through form and inscriptions","href":"/guides/ritual-bronze-vessels-and-inscriptions/","description":"Use a focused object-reading method inside a museum gallery."},{"label":"Check whether the itinerary is too rushed","href":"/guides/is-your-china-itinerary-too-rushed/","description":"Protect enough time for a site, exhibition and recovery plan."}]},
{"id":"help","type":"callout","title":"Need to fit a site museum into a real route?","body":"Share the date, city, group mobility, museum and archaeological priority. A Homeground planner can check current public components and fit realistic viewing time into the wider trip without replacing official access rules.","tone":"neutral"},
{"id":"sources","type":"sources","title":"Official, professional and scholarly sources reviewed","items":[{"label":"National Archaeological Site Park Management Measures","url":"https://wwj.chengde.gov.cn/art/2022/7/26/art_2877_866682.html","publisher":"National Cultural Heritage Administration text via Chengde Cultural Relics Bureau","reviewedAt":"2026-08-13"},{"label":"2024 National Archaeological Site Park operation-assessment notice","url":"https://wwj.shaanxi.gov.cn/sy/dtyw/tzgg/qtgg/202410/t20241011_3017277.html","publisher":"Shaanxi Provincial Cultural Heritage Administration","reviewedAt":"2026-08-13"},{"label":"Cultural Relics Protection Law of the People's Republic of China","url":"https://www.npc.gov.cn/npc/c2/c30834/202411/t20241108_440882.html","publisher":"National People's Congress","reviewedAt":"2026-08-13"},{"label":"Jinsha Site Museum Relics Hall","url":"https://www.jinshasitemuseum.com/site-75/node/315","publisher":"Jinsha Site Museum","reviewedAt":"2026-08-13"},{"label":"Jinsha Site Museum composition","url":"https://www.jinshasitemuseum.com/site-75/node/287","publisher":"Jinsha Site Museum","reviewedAt":"2026-08-13"},{"label":"Issues of In Situ Conservation at Jinsha","url":"https://doi.org/10.1179/1350503312Z.00000000022","publisher":"Conservation and Management of Archaeological Sites","reviewedAt":"2026-08-13"},{"label":"Terminological Conflation in Archaeological Site Institutions","url":"https://www.tandfonline.com/doi/full/10.1080/13505033.2024.2414526","publisher":"Conservation and Management of Archaeological Sites","reviewedAt":"2026-08-13"},{"label":"Hero image: Jinsha Relics Hall excavation display by Gary Todd, CC0; cropped and resized","url":"https://commons.wikimedia.org/wiki/File:2014_Jinsha_Excavation_Site-_Sacrificial_Center_01.jpg","publisher":"Wikimedia Commons","reviewedAt":"2026-08-13"}]}
]} as const satisfies StructuredPageBody;

export default body;
