import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Build this route backwards from Dunhuang, not forwards from Xi'an. Dunhuang is the only stop on the corridor with a fixed, capacity-limited, weather-cancellable anchor, and it sits at the end of one very long leg. Once you have placed Dunhuang and decided how you cross that leg, everything else follows. Lanzhou is the real question: it earns a night when it is doing a job — breaking the long leg, connecting an air-rail transfer, or opening a side trip — and it costs you a whole day when it is only a change of trains." },

  { id: "answer", type: "callout", title: "Place the anchor, then the long leg, then Lanzhou", tone: "decision", body: "In order: (1) fix the Dunhuang dates around a confirmed cave reservation, because that is the least flexible thing in the trip; (2) decide how you cross Lanzhou–Dunhuang, because it is long in every mode; (3) only then ask whether Lanzhou deserves a night of its own. Do not build the route in the order the map suggests. This page owns the shape of the route and the night allocation; the reservation procedure itself belongs to the Mogao Caves guide linked at the foot." },

  { id: "geography-heading", type: "heading", level: 2, text: "Three names, more stations than you expect" },
  { id: "geography-copy", type: "paragraph", text: "The first correction most itineraries need is geographic. \"Dunhuang\" is a county-level city inside Jiuquan prefecture, roughly 1,100 kilometres of Hexi Corridor west of Lanzhou, and it has both a railway station of its own and its own airport. The Dunhuang railway line that serves it is not a high-speed line: China State Railway Group describes it as a single-track electrified line, designed for 120 km/h, running 671 kilometres from Liugou on the Lanzhou–Xinjiang railway through Dunhuang, Aksai and Subei, over the Qilian Mountains into Qinghai and on to Yinmaxia. It opened in December 2019. Meanwhile the Lanzhou–Xinjiang high-speed railway, which is the fast way west, does not call at Dunhuang at all — its nearest stop is Liuyuan South, well outside the city." },
  { id: "stations-table", type: "table", caption: "The names your ticket may carry, checked against China Railway's 12306 station dictionary on 22 August 2026", columns: ["Station", "Chinese", "Code", "Registered city", "Why it matters to this route"], rows: [
    ["Xi'an North", "西安北", "EAY", "Xi'an", "The eastern anchor and the usual westbound departure"],
    ["Lanzhou West", "兰州西", "LAJ", "Lanzhou", "The high-speed hub, and the station the airport line runs from"],
    ["Lanzhou", "兰州", "LZJ", "Lanzhou", "A different, more central station — not interchangeable with Lanzhou West"],
    ["Zhongchuan Airport East", "中川机场东", "ZRJ", "Lanzhou", "The station built into the airport's new terminal complex"],
    ["Dunhuang", "敦煌", "DHJ", "Jiuquan", "The station in Dunhuang itself, on the conventional Dunhuang line"],
    ["Liuyuan South", "柳园南", "LNR", "Jiuquan", "The Lanzhou-Xinjiang high-speed stop — fast, but not in Dunhuang"],
    ["Liuyuan", "柳园", "DHR", "Jiuquan", "The older conventional-line station, easily confused with the above"],
    ["Jiayuguan South", "嘉峪关南", "JBJ", "Jiayuguan", "The obvious high-speed break point if you want one"],
  ]},
  { id: "geography-warning", type: "callout", title: "Liuyuan South is not Dunhuang", tone: "warning", body: "This is the single most expensive mistake on the corridor. A fast train to Liuyuan South leaves you outside the city with a road transfer still ahead of you; a train to Dunhuang station puts you in Dunhuang but travels on a conventional line. Neither is wrong. Booking one while planning for the other is what strands people. Read the full station name on the confirmed order, and note that Dunhuang and both Liuyuan stations are all registered under Jiuquan, so a search on the city name will not separate them for you." },

  { id: "direction-heading", type: "heading", level: 2, text: "East to west, or west to east?" },
  { id: "direction-copy", type: "paragraph", text: "Both directions work, and they fail differently. The choice is usually settled by where your international flights are, but if you genuinely have a free hand, the difference is worth understanding, because it changes which day is the fragile one." },
  { id: "direction-comparison", type: "comparison", title: "The same three cities, two different risk profiles", columns: [
    { heading: "Xi'an to Dunhuang (west-bound)", items: ["The trip builds outward from the biggest, best-connected city", "The anchor sits at the end, so a delay early in the trip eats your Dunhuang buffer", "If you miss the cave reservation you have already travelled the whole corridor to get there", "Suits travellers flying home from Dunhuang or continuing further west"] },
    { heading: "Dunhuang to Xi'an (east-bound)", items: ["The anchor is resolved on day one or two, while your energy and buffer are intact", "The trip ends in a city with dense onward air and rail options, which protects a fixed departure", "You arrive at the hardest logistics first, with the least local knowledge", "Suits travellers with a fixed international departure from Xi'an"] },
  ]},
  { id: "direction-copy2", type: "paragraph", text: "If the trip has a fixed international departure at one end, put that end last, without exception. The corridor is long enough that a single cancelled leg near the end has nowhere to be absorbed, and Dunhuang has far fewer daily alternatives than Xi'an does. If both ends are flexible, running east-bound gets the fragile anchor out of the way first, and that is usually the calmer trip." },

  { id: "lanzhou-heading", type: "heading", level: 2, text: "Does Lanzhou earn a night, or is it just a change of trains?" },
  { id: "lanzhou-copy", type: "paragraph", text: "This is the question the route actually turns on, and the honest answer changed recently. In March 2025 Lanzhou Zhongchuan International Airport's Phase 3 opened: the new T3 terminal entered service on 20 March 2025, and the airport loop railway opened alongside it. Gansu's state-asset authority records the consequence plainly — T1 and T2 were suspended and passenger operations moved wholly to Zhongchuan Airport East station and T3, with the station built as a two-level underground side-platform station tucked beneath the ground transportation centre on T3's south side and connected to the terminal by an underground passage. It records twenty arriving and departing trains a day at that station, eighteen calling trains, and a fastest run from Lanzhou West of 38 minutes into the terminal without changing. That is a genuine air-rail node, and it makes Lanzhou a much stronger candidate than it was two years ago — but only for travellers whose route actually uses it." },
  { id: "lanzhou-matrix", type: "table", caption: "Give Lanzhou a night for a reason, or give it none", columns: ["Your situation", "Verdict on Lanzhou", "What you are actually buying"], rows: [
    ["You are flying into or out of Lanzhou", "Keep it, and consider staying near Lanzhou West", "The rail link runs from Lanzhou West into the terminal, so the airport leg becomes a train rather than a road transfer"],
    ["You are flying the Lanzhou-Dunhuang leg", "Keep it", "You have to be at the airport anyway; the night is already paid for in logistics"],
    ["You want to break the long leg for comfort", "Keep it, or use Jiayuguan South instead", "A real bed halfway, rather than a full day seated"],
    ["You want a side trip into the Qilian range or to the Yellow River grottoes near Lanzhou", "Keep it", "Lanzhou is the practical base for those, not a detour from them"],
    ["You are going Xi'an to Dunhuang on one through journey", "Cut it, or pass through without sleeping", "Nothing. A change of trains is not a stop, and calling it one costs a day"],
    ["You have nine days or fewer for the whole corridor", "Cut it first", "Put that night back into Xi'an or Dunhuang, where it buys actual sightseeing"],
    ["You are travelling with children or anyone who tires on long legs", "Keep it", "The ability to stop when the day goes wrong, rather than being committed to the full crossing"],
  ]},
  { id: "lanzhou-warning", type: "callout", title: "A transfer is not a visit", tone: "warning", body: "Changing trains in Lanzhou at midday and calling that \"a day in Lanzhou\" is the most common way this route quietly loses time. If Lanzhou is only a transfer, book it as a transfer, keep the luggage with you, and do not book accommodation to justify it. Conversely, if you do give Lanzhou a night, give it a real one — arriving at 22:00 and leaving at 07:00 is a hotel bill, not a stop." },

  { id: "longleg-heading", type: "heading", level: 2, text: "The long leg is the trip's real cost" },
  { id: "longleg-copy", type: "paragraph", text: "Lanzhou to Dunhuang is long in every mode, and the modes are not equivalent in the way a search result implies. The high-speed option runs on the Lanzhou–Xinjiang high-speed railway, which opened on 26 December 2014 and runs from Lanzhou through Xining to Urumqi — but it does not stop in Dunhuang. Trains that reach Dunhuang station itself run onto the Dunhuang line, which is conventional and single-track. The Civil Aviation Administration confirms that Dunhuang has an airport. Whether a nonstop Lanzhou–Dunhuang passenger flight operates on your date is a separate live-schedule question; confirm it with the airline before treating air as available." },
  { id: "longleg-list", type: "list", ordered: true, items: [
    "Decide first whether you are willing to arrive outside Dunhuang. If not, the choice is a train to Dunhuang station or a flight, and Liuyuan South drops out entirely.",
    "If you will accept Liuyuan South, price the road transfer to Dunhuang as part of the journey, not as an afterthought, and check what runs at the hour your train actually arrives.",
    "Compare the flight as a full chain, including the airport leg at both ends. From Lanzhou that leg is now a train from Lanzhou West into T3; at the Dunhuang end it is a short road transfer.",
    "Whatever you choose, treat the crossing day as a travel day. See the next section.",
    "Confirm every option on 12306 or with the airline for your exact date. Services on this corridor are not dense, and a plan that assumes daily frequency can fail on a specific Tuesday.",
  ]},

  { id: "dunhuang-heading", type: "heading", level: 2, text: "Dunhuang is a base, not a stop" },
  { id: "dunhuang-copy", type: "paragraph", text: "Travellers routinely allocate Dunhuang a single night and then discover the visit does not fit inside it. The reason is structural, and the Dunhuang Academy — the body that administers the Mogao Grottoes — publishes it plainly. The Digital Exhibition Centre is the first stop of a Mogao visit; there is no ticket office in the cave area itself, and visitors are told not to drive straight there. The centre sits some kilometres out of town, and the ticket and check procedures happen in two separate places, each verifying your booking. Add the seasonal shape: the Academy publishes an open-all-year site with peak-season hours from 1 April to 30 November and off-season hours from 1 December to 31 March, and — crucially for planning — ticket sales close hours before the site itself does." },
  { id: "dunhuang-copy2", type: "paragraph", text: "Then add weather. The Academy's own announcements for 2026 show this is not hypothetical: heavy rain suspended opening on 24 June from 11:00, with reopening the following day; rain closed the site again on 29 July after a delayed-opening notice the evening before, with normal opening resuming on 30 July; a further advisory went out on 9 July for a multi-day rain event. Its published visitor rules state that when heavy rain or severe dust occurs, the emergency plan is triggered, caves stop opening, and affected visitors receive full refunds. A refund protects your money. It does not protect a route that had exactly one Dunhuang day in it." },
  { id: "dunhuang-callout", type: "callout", title: "What this means for the itinerary, in one line", tone: "decision", body: "Two Dunhuang nights normally create one full cave day and no true spare. Use that only when one confirmed cave day is enough and the crossing is already protected. Give Dunhuang three nights if the route is meant to absorb a full-day weather closure or a late or cancelled crossing. A closure can consume the whole cave day, as it did on 29 July 2026; it does not merely cost a morning. If the trip cannot carry the nights its risk level needs, shorten the corridor rather than compressing the anchor." },

  { id: "pacing-heading", type: "heading", level: 2, text: "A travel day is not a touring day" },
  { id: "pacing-copy", type: "paragraph", text: "The arithmetic that ruins Silk Road itineraries is counting the day you cross the Hexi Corridor as a day in the place you arrive. On this route the long legs are genuinely long, the stations are genuinely far from where you sleep, and the useful hours at the far end are genuinely few. Count nights, assign each night to a place, and then ask what each place gets in daylight." },
  { id: "pacing-table", type: "table", caption: "Three honest shapes for the same corridor — pick one and stop trying to add to it", columns: ["Shape", "Nights", "What it actually delivers", "What it will not survive"], rows: [
    ["Minimum viable", "Xi'an 2, Dunhuang 2, Lanzhou 0", "One proper Xi'an day, one crossing day and one Mogao day, with no true spare", "A full-day Mogao closure, a late crossing or a cancelled crossing"],
    ["Comfortable", "Xi'an 3, Lanzhou 1, Dunhuang 3", "Xi'an with a second day, a broken long leg, and real slack at the anchor", "Very little; this is the version that absorbs a bad day"],
    ["Add a Hexi break", "Xi'an 3, Lanzhou 1, Jiayuguan 1, Dunhuang 3", "The corridor read as a corridor rather than a hop", "A tight overall trip length; this needs the days to exist"],
    ["Overreaching — do not build this", "Xi'an 2, Lanzhou 1, Dunhuang 1", "Three arrival days and one usable morning", "Anything at all"],
  ]},
  { id: "pacing-copy2", type: "paragraph", text: "Notice what the table does not do: it does not offer a variant for every possible trip length. If you have more days, add them to Xi'an and Dunhuang, in that order, or extend westward or eastward with a different guide. If you have fewer, remove Lanzhou first and the Hexi break second. Adding a fourth city to a corridor this long is almost always a way of seeing all of it badly." },

  { id: "failure-heading", type: "heading", level: 2, text: "When it breaks, decide what to drop" },
  { id: "failure-copy", type: "paragraph", text: "Things go wrong on this corridor more often than on a dense eastern route, simply because there are fewer daily services and a much larger sky. The instinct is to squeeze the original plan into less time. That is the wrong instinct here, because the anchor cannot be squeezed and the legs cannot be shortened. Drop a place instead." },
  { id: "failure-table", type: "table", caption: "Reshape rather than compress", columns: ["What failed", "What to drop", "Why this and not something else"], rows: [
    ["Mogao closed for weather on your only cave day", "Drop the Lanzhou night and move it to Dunhuang", "A third Dunhuang night can create a second usable cave day; the Academy gives no promise about when a closure will end, so check the live notice and reservation inventory before rebuilding"],
    ["The Lanzhou-Dunhuang crossing was cancelled", "Drop the western end and rebuild around Xi'an and the eastern corridor", "There is no fast alternative crossing to improvise; forcing it consumes the days you were saving"],
    ["You reached Liuyuan South with no onward transfer left", "Drop the next morning's plan, not that night's accommodation", "Arriving late in Dunhuang is recoverable; arriving exhausted at a timed reservation is not"],
    ["Your international departure moved earlier", "Drop the last inland night and add it to the departure city", "The whole point of putting the fixed end last is that it can absorb this"],
    ["You are simply running late across the whole trip", "Drop Lanzhou, then the Hexi break, then a Xi'an day", "In that order. Never take the days out of Dunhuang; that is the trip"],
  ]},

  { id: "facts", type: "callout", title: "Reviewed 22 August 2026", tone: "neutral", body: "Station identities come from China Railway's live 12306 dictionary on that date. Lanzhou Zhongchuan T3 opened 20 March 2025 and the airport loop railway opened alongside it, with T1 and T2 suspended; the train counts and the 38-minute fastest run are as published by Gansu's state-asset authority at the time and are subject to change. The Lanzhou-Xinjiang high-speed railway opened 26 December 2014; the Dunhuang line opened in December 2019. Mogao opening seasons and the Digital Exhibition Centre arrangement are as published by the Dunhuang Academy; the 2026 closure notices cited are historical examples of a recurring risk, not a forecast. No fare, seat availability, journey time or frequency in this guide should be treated as current — confirm on 12306 and with the airline for your dates." },

  { id: "help", type: "callout", title: "Want the night allocation checked before you book anything?", tone: "decision", body: "Send your total days, your fixed international flights, whether you have a cave reservation yet, and who is travelling. Homeground can tell you which shape the trip actually supports and what to drop if it does not. Live rail inventory stays with 12306, and cave reservations stay with the Dunhuang Academy's own channel." },

  { id: "links", type: "internal-links", title: "Continue planning", items: [
    { label: "Visiting the Mogao Caves independently", href: "/guides/mogao-caves-independent-visit-workflow/", description: "The reservation workflow itself, which this route guide deliberately does not repeat." },
    { label: "Hub-and-spoke or multi-base routes in China", href: "/guides/china-hub-and-spoke-or-multi-base-route/", description: "Whether this corridor should be one line or two bases." },
    { label: "Building a rail-only route in China", href: "/guides/china-rail-only-route/", description: "If you would rather not fly any leg of this." },
    { label: "Night train or daytime high-speed rail", href: "/guides/china-night-train-or-daytime-high-speed-rail/", description: "The long leg is exactly the case this decision was written for." },
    { label: "Qilian Mountains: choosing a lawful public gateway", href: "/guides/qilian-mountains-public-gateways-and-access/", description: "If the Lanzhou night is buying you a mountain side trip." },
    { label: "China's climate regions and when to travel", href: "/guides/china-climate-regions-for-trip-timing/", description: "The corridor's seasons are not the seasons of eastern China." },
    { label: "Beijing, Xi'an and Chengdu in what order?", href: "/guides/beijing-xian-chengdu-route-order/", description: "If Xi'an is a junction rather than the start of the trip." },
    { label: "Shoulder season in China: the real trade-off", href: "/guides/china-shoulder-season-value-tradeoff/", description: "This corridor rewards the shoulder months, and this is what you give up for them." },
  ]},

  { id: "sources", type: "sources", title: "Official sources and image credit", items: [
    { label: "12306 station dictionary used by the official booking site", url: "https://kyfw.12306.cn/otn/resources/js/framework/station_name.js", publisher: "China Railway 12306", reviewedAt: "2026-08-22" },
    { label: "Official railway ticket channel", url: "https://www.12306.cn/en/index.html", publisher: "China Railway 12306", reviewedAt: "2026-08-22" },
    { label: "Mogao Grottoes visitor information: opening seasons, Digital Exhibition Centre and visitor rules", url: "https://www.dha.ac.cn/skxl/mgk.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-08-22" },
    { label: "Dunhuang Academy announcements, including the 2026 weather closures and reopenings", url: "https://www.dha.ac.cn/xwzx/tzgg.htm", publisher: "Dunhuang Academy", reviewedAt: "2026-08-22" },
    { label: "First passenger trains between Golmud and Dunhuang, with the Dunhuang line's route and length", url: "http://www.china-railway.com.cn/xwzx/zhxw/202307/t20230711_128960.html", publisher: "China State Railway Group", reviewedAt: "2026-08-22" },
    { label: "Dunhuang railway opens over its full length", url: "https://www.yidaiyilu.gov.cn/p/113261.html", publisher: "Belt and Road Portal (China)", reviewedAt: "2026-08-22" },
    { label: "Lanzhou Zhongchuan airport loop railway enters service; T1 and T2 suspended", url: "http://www.sasac.gov.cn/n2588025/n2588129/c33097533/content.html", publisher: "State-owned Assets Supervision and Administration Commission of the State Council", reviewedAt: "2026-08-22" },
    { label: "Lanzhou Zhongchuan International Airport Phase 3 completed and in service; T3 opened 20 March 2025", url: "https://www.ndrc.gov.cn/xwdt/ztzl/dtfzgz/202504/t20250403_1397004.html", publisher: "National Development and Reform Commission", reviewedAt: "2026-08-22" },
    { label: "Dunhuang Mogao International Airport listed among Gansu's international transport airports", url: "http://www.caac.gov.cn/GYMH/MHGK/GJKAYSJC/XBDQ/GS/202404/t20240417_223898.html", publisher: "Civil Aviation Administration of China", reviewedAt: "2026-08-23" },
    { label: "Lanzhou-Xinjiang high-speed railway: opening date, route and length", url: "http://www.qinghai.gov.cn/dmqh/system/2024/12/27/030061694.shtml", publisher: "Qinghai Provincial People's Government", reviewedAt: "2026-08-22" },
    { label: "Hero: Dunhuang railway station by Hanno Böck, CC0 public domain dedication; cropped and converted to WebP", url: "https://commons.wikimedia.org/wiki/File:Dunhuang-station.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" },
    { label: "Hero licence: CC0 1.0 Universal", url: "https://creativecommons.org/publicdomain/zero/1.0/", publisher: "Creative Commons", reviewedAt: "2026-08-22" },
  ]},
] } as const satisfies StructuredPageBody;
export default body;
