export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "Treat the Forbidden City as one continuous south-to-north visit. Secure the Palace Museum reservation with the passport details of every visitor, bring those original passports, reach the Meridian Gate (Wumen) on the south side, begin the three-hour clock only after ticket inspection, keep the central axis and one side choice, then leave through the Gate of Divine Prowess (Shenwumen) in the north. Your morning entrance and your transport after the exit are different journeys; plan both before the visit.",
    },
    {
      id: "execution-summary",
      type: "callout",
      title: "The visit in six actions",
      body: "1. Check the official opening calendar. 2. Reserve through an official Palace Museum channel with the document each person will carry. 3. Decide whether Tiananmen Square is a separate stop at all. 4. Approach the only visitor entrance at the Meridian Gate. 5. Walk the central axis and only one optional side section. 6. Exit north and use a preselected bus, pickup point or next sight. Do not improvise the north-gate transport after everyone is already tired.",
      tone: "decision",
    },
    {
      id: "official-check-heading",
      type: "heading",
      level: 2,
      text: "What the official rules say this week",
    },
    {
      id: "official-check-table",
      type: "table",
      caption: "Standing Palace Museum rules reviewed on 11 August 2026",
      columns: ["Decision", "Official position", "What the traveller should do"],
      rows: [
        ["Advance booking", "No same-day tickets; tickets normally open at 20:00 China time seven days before the visit", "Set the release time in China time and do not build a Beijing day around an unconfirmed ticket"],
        ["Foreign documents", "A passport and several other accepted non-mainland documents can be used for real-name booking and inspection", "Enter every document number carefully and bring the original document used"],
        ["Entrance", "The Meridian Gate on the south side is the only visitor entrance", "Do not navigate to the north gate for the morning arrival"],
        ["Exit", "Visitors leave through the Gate of Divine Prowess in the north or the East Prosperity Gate", "For this route, plan the north exit before entering"],
        ["Weekly closure", "Closed on Mondays except statutory holidays; special notices can override the normal calendar", "Check the dated opening announcements again shortly before the visit"],
      ],
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "Step 1: book the Palace Museum, not a generic Forbidden City product",
    },
    {
      id: "booking-rules",
      type: "paragraph",
      text: "For a visitor booking with a passport, start with the Palace Museum's official multilingual ticketing portal. The museum uses real-name reservations for every visitor, including people receiving free or discounted admission and their companions. Its current Chinese rules say general admission, the Treasure Gallery, the Gallery of Clocks and exhibition reservations open at 20:00 seven days before the visit; there are no same-day tickets. The museum also states that it has not authorised any third-party organisation or individual to act as its ticket agent. A tour company may sell a wider service, but its listing is not proof that an official museum reservation has been issued.",
    },
    {
      id: "booking-paths",
      type: "table",
      caption: "Official booking paths for a visitor using a passport",
      columns: ["Path", "What the official source currently says", "Boundary"],
      rows: [
        ["Official multilingual ticketing portal", "The Palace Museum directs international visitors to https://bookingticket.dpm.org.cn/ for real-name reservations", "Enter the passport details exactly as shown and keep the completed booking record"],
        ["Palace Museum WeChat mini-program", "The Chinese visitor rules identify the official Palace Museum mini-program as the main reservation channel", "Use the exact official account and verify every traveller before payment"],
        ["Official English guidance", "Beijing's 12345 service confirms that foreign visitors can book with a passport and should bring the original document for inspection", "Use the current official process shown when booking and follow staff directions at the Meridian Gate"],
      ],
    },
    {
      id: "email-boundary",
      type: "callout",
      title: "Opening the booking page is not the same as holding a ticket",
      body: "Finish the transaction and keep a clear confirmation or booking record. Check every name, passport number, date and time period before treating the visit as secured. If the result is unclear, use the contact details shown on the Palace Museum's official site. Recheck the live process before travel because ticketing channels can change.",
      tone: "warning",
    },
    {
      id: "no-same-day",
      type: "callout",
      title: "Ignore anecdotal promises of a foreigner walk-up ticket",
      body: "Current search results still contain traveller reports about buying a ticket at the gate. The standing Palace Museum rule reviewed for this guide says it does not sell same-day tickets. Plan from the official rule, not from a past visitor's exception or an unofficial seller's promise.",
      tone: "warning",
    },
    {
      id: "timeslot-analysis",
      type: "paragraph",
      text: "The current rules divide visits into morning and afternoon periods. A morning reservation must be checked by 12:00; an afternoon reservation cannot be checked before 11:00. Those limits do not turn the approach into spare sightseeing time. Security, route controls and the walk to the Meridian Gate happen before the museum visit, so leave a buffer and follow the exact period shown in the live booking record.",
    },
    {
      id: "tiananmen-heading",
      type: "heading",
      level: 2,
      text: "Step 2: check the Tiananmen Square rule separately",
    },
    {
      id: "tiananmen-separate",
      type: "paragraph",
      text: "The Palace Museum and Tiananmen Square use different reservation systems, but that has not always meant making two reservations. Trial measures published by the Tiananmen Area Management Committee in 2021 state that visitors holding a valid Palace Museum reservation may enter the square without making a separate square reservation. The reverse is not true: a square reservation never replaces Palace Museum admission. Because access controls can change for major events and security operations, check the square's current rule separately before the visit. If the goal is only the Palace Museum, its current rules also allow an approach to the Meridian Gate along the East or West Tongzihe roads without turning a square visit into a compulsory stop.",
    },
    {
      id: "approach-options",
      type: "comparison",
      title: "Choose the southern approach before the morning",
      columns: [
        {
          heading: "Palace Museum only",
          body: "Use the current East or West Tongzihe approach to the Meridian Gate. Set the map destination to the correct side of the Palace and expect a final walk; Donghuamen and Xihuamen are approach landmarks, not visitor entrances.",
        },
        {
          heading: "Tiananmen Square plus the Palace Museum",
          body: "Check whether the current square rule still accepts the day's valid Palace Museum record instead of a second reservation. Carry whichever record the current rule requires, allow for security screening and visit the square first because the Palace route continues north.",
        },
      ],
    },
    {
      id: "entrance-heading",
      type: "heading",
      level: 2,
      text: "Step 3: arrive at the Meridian Gate with the right document",
    },
    {
      id: "entrance-reality",
      type: "paragraph",
      text: "The address of the Palace Museum, a Forbidden City map pin and the nearest visible gate are not enough. Visitor entry is through the Meridian Gate only. The Gate of Divine Prowess is an exit, the East Prosperity Gate is an exit, and the West Prosperity Gate is normally a staff passage. At inspection, a foreign visitor must present the original valid passport or other accepted document used for the reservation. A screenshot of the passport is not the booked original document.",
    },
    {
      id: "morning-checklist",
      type: "list",
      items: [
        "Carry the original passport used for each reservation; check renewed passports and digit transpositions before the ticket-release day.",
        "Keep the confirmed date, period and order record available, but understand that the identity document is central to inspection.",
        "Open the official notice page the night before for temporary closures, special opening days and changes to individual galleries.",
        "Set the route to the Meridian Gate approach, not to Shenwumen, Donghuamen or a generic Forbidden City pin.",
        "Agree on what to cut if the approach or security process takes longer than expected.",
      ],
    },
    {
      id: "luggage-plan",
      type: "callout",
      title: "Do not visit the Palace Museum with transfer-day luggage",
      body: "Suitcases are prohibited inside. The Palace Museum currently provides storage and free transfer for qualifying luggage, with deposit at the visitor service centre west of Duanmen Square and collection outside the north or east exit. That service has seasonal hours and storage conditions. Leaving luggage at the hotel is usually simpler; if storage is essential, check the current rule and choose the collection exit before handing over the bag.",
      tone: "warning",
    },
    {
      id: "route-heading",
      type: "heading",
      level: 2,
      text: "Step 4: use three hours for the central route and one deliberate detour",
    },
    {
      id: "route-definition",
      type: "paragraph",
      text: "The Palace Museum publishes two-hour, half-day and one-day visitor trails. The plan below is Homeground's three-hour option between the first two official route lengths: it protects the south-to-north central sequence, leaves room for one side interest and finishes at the north gate. The three hours begin after passport inspection at the Meridian Gate. They do not include travel from the hotel, Tiananmen-area security, ticket troubleshooting or transport after exit.",
    },
    {
      id: "route-table",
      type: "table",
      caption: "A realistic three-hour route from the Meridian Gate to the north exit",
      columns: ["Elapsed time", "Route", "Decision rule"],
      rows: [
        ["0:00–0:20", "Meridian Gate → Inner Golden Water Bridges → Gate of Supreme Harmony", "Orient yourself and keep moving; this is not yet the place for the longest stop"],
        ["0:20–1:05", "Hall of Supreme Harmony → Hall of Central Harmony → Hall of Preserving Harmony", "Protect this central Outer Court sequence on a first visit"],
        ["1:05–1:45", "Take one side branch at its actual junction: an east-side gallery after the Hall of Preserving Harmony, or one open palace cluster around the Gate of Heavenly Purity", "Choose one branch and return to the central route; do not save every detour for the far north"],
        ["1:45–2:15", "Gate of Heavenly Purity → Palace of Heavenly Purity → Hall of Union → Palace of Earthly Tranquillity", "Resume the Inner Court central axis after the chosen branch"],
        ["2:15–2:45", "Imperial Garden", "Keep enough time to enjoy the garden without endangering the exit plan"],
        ["2:45–3:00", "Walk to the Gate of Divine Prowess and exit north", "Finish the route rather than backtracking for a missed side room"],
      ],
    },
    {
      id: "side-choice",
      type: "callout",
      title: "Choose the side section before entering",
      body: "If objects matter most, reserve or select one confirmed-open gallery and branch toward it where the official map actually turns east, usually after the Hall of Preserving Harmony. If palace interiors and spatial layout matter more, choose one open east- or west-side cluster around the Gate of Heavenly Purity. If a current exhibition is the priority, follow its stated location and let it replace the side section rather than adding it. Some galleries require a separate ticket or reservation, and temporary closures can change the viable route.",
      tone: "decision",
    },
    {
      id: "three-hour-limit",
      type: "paragraph",
      text: "Three hours is enough for a coherent first route, not for the entire Palace Museum. Queues inside, photography, rest stops, weather and gallery capacity can use the side-section allowance. If the central axis alone takes longer, cut the detour and keep the Imperial Garden and north exit. The route succeeds when it preserves energy and direction, not when every named hall is checked off.",
    },
    {
      id: "parents-callout",
      type: "callout",
      title: "With parents or slower walkers, shorten before you accelerate",
      body: "Make the Palace Museum the day's main walking block. Use the official two-hour route as the fallback, add seated pauses, and do not place Jingshan automatically after the north exit. A three-hour admission block can still produce a much longer door-to-door outing once the southern approach and the journey from Shenwumen are included.",
      tone: "neutral",
    },
    {
      id: "route-cuts-heading",
      type: "heading",
      level: 2,
      text: "What to protect and what to cut when time slips",
    },
    {
      id: "route-cuts",
      type: "comparison",
      columns: [
        {
          heading: "Protect",
          items: [
            "The booked inspection period and original passport",
            "The Meridian Gate entrance",
            "The main south-to-north sequence",
            "A controlled finish at the chosen exit",
          ],
        },
        {
          heading: "Cut first",
          items: [
            "A second paid gallery",
            "Crossing from east-side rooms to west-side rooms",
            "A temporary exhibition that was not the main reason for booking",
            "An automatic Jingshan climb after the Palace",
          ],
        },
      ],
    },
    {
      id: "closures-heading",
      type: "heading",
      level: 2,
      text: "Step 5: check the calendar again, even after buying the ticket",
    },
    {
      id: "closures-analysis",
      type: "paragraph",
      text: "The standing calendar is seasonal and normally excludes Mondays, but statutory holidays and dated announcements can change opening days or individual buildings. In July 2026, for example, the museum issued a special notice opening on a Monday. That does not create a general Monday rule. The booking record, the current opening page and the latest dated notices must agree before the route is treated as final.",
    },
    {
      id: "hours-table",
      type: "table",
      caption: "Standing hours shown by the Palace Museum at the 11 August 2026 review",
      columns: ["Season", "Opening", "Last admission", "Museum closes"],
      rows: [
        ["1 April–31 October", "08:30", "16:00", "17:00"],
        ["1 November–31 March", "08:30", "15:30", "16:30"],
      ],
    },
    {
      id: "hours-boundary",
      type: "callout",
      title: "These hours are a checkpoint, not a guarantee",
      body: "The Palace Museum says holidays and special circumstances may extend, shorten or suspend opening. Individual halls, the Treasure Gallery, the Gallery of Clocks and current exhibitions can have separate last-entry or closure notices. Check the live official pages when booking and again before leaving for the museum.",
      tone: "warning",
    },
    {
      id: "exit-heading",
      type: "heading",
      level: 2,
      text: "Step 6: leave through Shenwumen with the next move already chosen",
    },
    {
      id: "north-exit",
      type: "paragraph",
      text: "The Gate of Divine Prowess is the Palace Museum's north exit and faces Jingshan Park across the road. It is not a morning entrance and it does not return you to the southern starting point. The museum's transport page lists bus stops at Shenwumen and Jingshan East Gate, says there is no dedicated Palace Museum car park and recommends public transport. Bus routes and road controls are operational details, so verify them in a live map on the day.",
    },
    {
      id: "exit-options",
      type: "table",
      caption: "What to do after the north-gate exit",
      columns: ["Next plan", "Best preparation", "Common mistake"],
      rows: [
        ["Finish sightseeing", "Use a confirmed bus stop or legal pickup point and return to the hotel area", "Assuming a taxi will wait directly under the gate"],
        ["Continue to Jingshan", "Cross only by the current pedestrian route and treat the climb as a separate energy decision", "Adding the hill automatically because it looks adjacent"],
        ["Continue into the northern old city", "Check the exact walking, bus or car connection to the named next place", "Using 'hutongs' or 'Shichahai' as an imprecise destination"],
        ["Collect stored luggage", "Use the exit selected when depositing the bag and check collection hours", "Leaving through the other gate and creating a recovery trip"],
      ],
    },
    {
      id: "pickup-plan",
      type: "callout",
      title: "A north-gate pickup needs a pin, not a promise",
      body: "Ask a driver, guide or hotel for the exact legal pickup point in Chinese and save it before entering. Mobile signal, road controls and stopping rules can change the practical meeting point. 'Meet at the Forbidden City exit' is not specific enough when the museum has two visitor exits and the north gate faces another busy attraction.",
      tone: "decision",
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "Questions that derail the visit",
    },
    {
      id: "faq-north-entry",
      type: "callout",
      title: "Can I enter at the north gate?",
      body: "No. The Gate of Divine Prowess is an exit. Visitor entry is through the Meridian Gate on the south side.",
      tone: "neutral",
    },
    {
      id: "faq-tiananmen",
      type: "callout",
      title: "Do I need a separate Tiananmen Square reservation?",
      body: "Not necessarily. Trial measures published by the Tiananmen Area Management Committee in 2021 allowed a visitor with a valid Palace Museum reservation to enter the square without a second square reservation. Check that the exemption is still in force for the visit date and carry the required record. A square reservation cannot replace the Palace Museum ticket.",
      tone: "neutral",
    },
    {
      id: "faq-passport",
      type: "callout",
      title: "Is a passport photo enough?",
      body: "No. The Palace Museum requires the original valid document used for booking. Keep a digital copy for general travel backup, but do not substitute it for the booked original at inspection.",
      tone: "neutral",
    },
    {
      id: "faq-three-hours",
      type: "callout",
      title: "Is three hours really enough?",
      body: "It is enough for the central axis, one controlled side choice, the Imperial Garden and a north-gate exit at a steady pace. It is not enough for a complete museum survey, multiple galleries, long interpretation stops and both east and west palace clusters.",
      tone: "neutral",
    },
    {
      id: "fact-label",
      type: "callout",
      title: "Official fact versus Homeground planning judgment",
      body: "The ticket release, accepted identity documents, original-document requirement, time periods, Monday closure, seasonal hours, one-way entrance and exits, published visitor trails, luggage service and transport listings come from the official sources below. The exact three-hour allocation, the instruction to choose only one side section, the default north exit and the pickup strategy are Homeground planning judgments built on those facts.",
      tone: "neutral",
    },
    {
      id: "prepublish-heading",
      type: "heading",
      level: 2,
      text: "Final checks before leaving for the visit",
    },
    {
      id: "prepublish-list",
      type: "list",
      items: [
        "The Palace Museum ticket page still shows the same release window, accepted foreign documents and inspection periods.",
        "The official multilingual ticketing portal still accepts the passport and shows a completed booking record.",
        "The latest notice does not change the Monday calendar, daily hours or the chosen visit date.",
        "The Meridian Gate remains the entrance and Shenwumen remains available as the intended exit.",
        "The selected side gallery or exhibition is open and any extra reservation has been secured.",
        "The current Tiananmen Square rule has been checked separately, including whether a valid Palace Museum record still removes the need for a second reservation.",
        "The north-gate bus, pickup or luggage-collection plan has been confirmed for the day.",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Continue planning Beijing",
      items: [
        {
          label: "Where to stay in Beijing on a first trip",
          href: "/guides/beijing-where-to-stay-first-trip/",
          description: "Compare Wangfujing, Qianmen, Sanlitun and northern hutongs using both the Palace entrance and north-gate exit.",
        },
        {
          label: "China with older parents",
          href: "/guides/china-itinerary-with-older-parents/",
          description: "Build the visit around walking tolerance, recovery time and a preselected exit.",
        },
        {
          label: "Is your China itinerary too rushed?",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Check whether the Palace day still leaves a realistic amount of energy for the rest of Beijing.",
        },
        { label: "Verify a China attraction ticket", href: "/guides/official-or-reseller-china-tickets/", description: "Identify the attraction’s ticket owner, compare reseller support and terms, and verify the booking state before trusting a China attraction ticket." },
        { label: "Choose a Summer Palace gate and route", href: "/guides/summer-palace-gates-route-and-boat-plan/", description: "Match the East, North or New Palace Gate to your priorities, understand base versus combined tickets and build a route that still works if boats stop." },
      ],
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        {
          label: "Palace Museum official multilingual ticketing portal",
          url: "https://bookingticket.dpm.org.cn/",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Palace Museum notice identifying the multilingual portal as an official real-name reservation channel",
          url: "https://intl.dpm.org.cn/news/detail/98706.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Palace Museum ticketing and identity-document rules",
          url: "https://www.dpm.org.cn/subject_booking/",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Palace Museum opening hours, visitor trails, gates and transport",
          url: "https://www.dpm.org.cn/Visit.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Palace Museum visitor, security and luggage rules",
          url: "https://www.dpm.org.cn/singles_detail/259831.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Palace Museum prohibited-items catalogue",
          url: "https://www.dpm.org.cn/singles_detail/259832.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Beijing 12345 guidance for Palace Museum booking with a foreign passport",
          url: "https://english.beijing.gov.cn/12345hotline/faqs/all/202506/t20250620_4117980.html",
          publisher: "People's Government of Beijing Municipality",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Tiananmen Square trial reservation measures and Palace Museum exemption",
          url: "https://tamgw.beijing.gov.cn/zhengwugongkai/tzgg/202111/t20211119_2541156.html",
          publisher: "Tiananmen Area Management Committee",
          reviewedAt: "2026-08-11",
        },
        {
          label: "Current official Tiananmen Square reservation channels",
          url: "https://english.beijing.gov.cn/travellinginbeijing/attractions/202603/t20260325_4566110.html",
          publisher: "People's Government of Beijing Municipality",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const;
