export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "Tiananmen Square and the Palace Museum are adjacent, but they are not one ticket or one planning task. Secure the Palace Museum reservation with the exact passport details of every visitor, decide separately whether the square is part of the morning, carry the original booked documents, and reach the Meridian Gate (Wumen) from the south. Only then does the museum visit begin: keep a south-to-north route, protect the central axis, choose at most one side focus, and leave through the Gate of Divine Prowess (Shenwumen) or the East Prosperity Gate with the next journey already planned.",
    },
    {
      id: "execution-summary",
      type: "callout",
      title: "The visit in seven decisions",
      body: "1. Check the visit date against the Palace Museum calendar and latest notices. 2. Reserve the museum through an official channel with the document each person will carry. 3. Treat Tiananmen Square as a separate access decision and verify its current rule. 4. Choose the square route or an East/West Tongzihe approach. 5. Budget for walking and security before the Meridian Gate. 6. Walk the central axis with at most one side focus. 7. Leave through a planned exit and connection. Do not let an unconfirmed ticket, a generic map pin or an improvised pickup control the day.",
      tone: "decision",
    },
    {
      id: "official-check-heading",
      type: "heading",
      level: 2,
      text: "What the official rules say this week",
    },
    {
      id: "official-check-table",
      type: "table",
      caption: "Standing Palace Museum rules reviewed on 22 August 2026",
      columns: ["Decision", "Official position", "What the traveller should do"],
      rows: [
        ["Advance booking", "No same-day tickets; tickets normally open at 20:00 China time seven days before the visit", "Set the release time in China time and do not build a Beijing day around an unconfirmed ticket"],
        ["Foreign documents", "A passport and several other accepted non-mainland documents can be used for real-name booking and inspection", "Enter every document number carefully and bring the original document used"],
        ["Booking identity", "One identity document can hold one ticket for a visit date; the ticket, date, time period and visitor cannot be changed after purchase", "Check the full party before payment; cancel and rebook only within the live refund rules and only if replacement inventory exists"],
        ["Entrance", "The Meridian Gate on the south side is the only visitor entrance", "Do not navigate to the north gate for the morning arrival"],
        ["Exit", "Visitors leave through the Gate of Divine Prowess in the north or the East Prosperity Gate", "For this route, plan the north exit before entering"],
        ["Weekly closure", "Closed on Mondays except statutory holidays; special notices can override the normal calendar", "Check the dated opening announcements again shortly before the visit"],
      ],
    },
    {
      id: "booking-heading",
      type: "heading",
      level: 2,
      text: "Step 1: book the Palace Museum, not a generic Forbidden City product",
    },
    {
      id: "booking-rules",
      type: "paragraph",
      text: "For a visitor booking with a passport, start with the Palace Museum's current official English Tickets page rather than assuming every language uses the same checkout. At the 22 August review, that page instructed international visitors to submit each visitor's full name, passport number and intended date to bookingticket@dpm.org.cn within the seven-day booking window and at least one calendar day in advance. The Chinese official rules separately identify the Palace Museum WeChat mini-program, a 20:00 release seven days before the visit and no same-day tickets. Treat these as distinct official channel instructions, follow the one currently addressed to your booking case, and require a completed reservation record before fixing the day. The museum has not authorised third-party ticket agents.",
    },
    {
      id: "booking-paths",
      type: "table",
      caption: "Official channel instructions are not identical across language pages",
      columns: ["Official path", "What it currently says", "Boundary"],
      rows: [
        ["Official English Tickets page", "International visitors are told to email each full name, passport number and intended visit date to bookingticket@dpm.org.cn, within seven days and at least one calendar day before the visit", "Use only the exact museum address, send only the fields the current official page requests, and do not treat a sent email as confirmation"],
        ["Palace Museum WeChat mini-program", "The Chinese rules identify the official mini-program as the advance-purchase channel and state the 20:00 seven-day release", "Use the exact official account, verify every traveller before payment and do not assume the English email timeline describes mini-program inventory"],
        ["Official ticket links and service help", "The Palace website links to its ticket service and publishes customer-service contacts; Beijing 12345 also confirms passport and original-document use", "Interfaces and access from abroad can change. Follow the current official instruction shown for the chosen channel and ask the museum if the status is unclear"],
      ],
    },
    {
      id: "email-boundary",
      type: "callout",
      title: "Sending an email or opening a booking page is not the same as holding a ticket",
      body: "Keep the museum's response or completed booking record and check every visitor, passport number, date and time period before treating the visit as secured. Passport data is sensitive: send it only through the exact official route currently published by the Palace Museum, do not copy Homeground or an unrelated seller, and do not forward the record publicly. If the result is unclear, use the contact details on the museum site.",
      tone: "warning",
    },
    {
      id: "no-same-day",
      type: "callout",
      title: "Ignore anecdotal promises of a foreigner walk-up ticket",
      body: "Current search results still contain traveller reports about buying a ticket at the gate. The standing Palace Museum rule reviewed for this guide says it does not sell same-day tickets. Plan from the official rule, not from a past visitor's exception or an unofficial seller's promise.",
      tone: "warning",
    },
    {
      id: "timeslot-analysis",
      type: "paragraph",
      text: "The current rules divide visits into morning and afternoon periods. A morning reservation must be checked by 12:00; an afternoon reservation cannot be checked before 11:00. Those are inspection boundaries, not suggested arrival times. Security, event controls and the final walk to the Meridian Gate all happen before entry, and the museum publishes no guaranteed security-wait duration. Follow the period on the live order and build a flexible buffer rather than promising yourself a fixed door-to-gate time.",
    },
    {
      id: "booking-recovery-heading",
      type: "heading",
      level: 2,
      text: "If the booking does not work, diagnose the failure before buying anything else",
    },
    {
      id: "booking-recovery-table",
      type: "table",
      caption: "Ticket failure and the least risky next move",
      columns: ["What happened", "What it means", "Recovery"],
      rows: [
        ["The date is sold out", "There is no official same-day walk-up inventory to rely on", "Move the Palace Museum to another available Beijing day, use the official cancellation inventory if it reappears, or replace it with a different confirmed attraction; do not let an unofficial promise anchor the itinerary"],
        ["Email, payment or foreign-phone flow fails", "A sent message or failed screen is not a reservation", "Keep screenshots that hide sensitive details, retry only through the current official route, and use the Palace Museum contact details or Beijing 12345 if the status remains unclear"],
        ["A name or passport number is wrong", "The visitor identity cannot simply be edited after purchase", "Read the live cancellation rule before acting. A corrected rebooking needs available inventory; never cancel a scarce valid order until the consequence is understood"],
        ["One traveller has no confirmed record", "Real-name entry applies person by person", "Treat that traveller as unbooked and redesign the group day rather than assuming staff can add a companion at the gate"],
        ["A reseller says the ticket is included", "The reseller product is not proof of museum issuance", "Ask for the Palace Museum booking record, visit date, period and document match before treating the visit as secured"],
      ],
    },
    {
      id: "tiananmen-heading",
      type: "heading",
      level: 2,
      text: "Step 2: check the Tiananmen Square rule separately",
    },
    {
      id: "tiananmen-separate",
      type: "paragraph",
      text: "The Palace Museum and Tiananmen Square have different owners, booking channels and access checks. A square reservation never replaces a Palace Museum ticket. Under the current publicly available Tiananmen measures, a visitor with a valid same-day Palace Museum reservation can enter the square without making a separate square reservation; show that valid record at the on-site check. This exemption does not remove security, visitor-flow controls or temporary restrictions, so recheck official notices before major events and special-control dates. If the museum is the only goal, the East or West Tongzihe approach remains a useful route that does not depend on crossing the square.",
    },
    {
      id: "approach-options",
      type: "comparison",
      title: "Choose the southern approach before the morning",
      columns: [
        {
          heading: "Palace Museum only",
          body: "Use the current East or West Tongzihe approach to the Meridian Gate. Set the map destination to the correct side of the Palace and expect a final walk; Donghuamen and Xihuamen are approach landmarks, not visitor entrances.",
        },
        {
          heading: "Tiananmen Square plus the Palace Museum",
          body: "Carry the valid same-day Palace Museum reservation for the square check; if a separate square record was also issued, carry both. Allow for security and follow the south-to-north flow from the square toward Duanmen and the Meridian Gate. Do not use a square reservation as evidence of Palace admission.",
        },
      ],
    },
    {
      id: "entrance-heading",
      type: "heading",
      level: 2,
      text: "Step 3: arrive at the Meridian Gate with the right document",
    },
    {
      id: "entrance-reality",
      type: "paragraph",
      text: "The address of the Palace Museum, a Forbidden City map pin and the nearest visible gate are not enough. Visitor entry is through the Meridian Gate only. The Gate of Divine Prowess is an exit, the East Prosperity Gate is an exit, and the West Prosperity Gate is normally a staff passage. At inspection, a foreign visitor must present the original valid passport or other accepted document used for the reservation. A screenshot of the passport is not the booked original document.",
    },
    {
      id: "arrival-budget",
      type: "table",
      caption: "What happens before the three-hour museum route",
      columns: ["Stage", "Plan for", "Do not assume"],
      rows: [
        ["Hotel to controlled area", "Normal city travel plus margin for congestion and the correct drop-off", "A car can stop at the nearest visible gate"],
        ["Tiananmen access, if chosen", "Its current reservation record, identity check, security and event controls", "The Palace ticket automatically clears every square checkpoint"],
        ["Final approach", "A substantial pedestrian segment via the selected south-side route", "The metro exit or taxi pin is the museum entrance"],
        ["Meridian Gate inspection", "Original booked document, order record and the time period shown", "A passport photo, another passport or a companion's record will substitute"],
      ],
    },
    {
      id: "morning-checklist",
      type: "list",
      items: [
        "Carry the original passport used for each reservation; check renewed passports and digit transpositions before the ticket-release day.",
        "Keep the confirmed date, period and order record available, but understand that the identity document is central to inspection.",
        "Open the official notice page the night before for temporary closures, special opening days and changes to individual galleries.",
        "Set the route to the Meridian Gate approach, not to Shenwumen, Donghuamen or a generic Forbidden City pin.",
        "Agree on what to cut if the approach or security process takes longer than expected.",
      ],
    },
    {
      id: "security-recovery",
      type: "callout",
      title: "A security queue is not a ticket exception",
      body: "Everyone must pass the applicable security checks. Review the official prohibited-items catalogue before leaving the hotel. If staff identify an item, follow their disposal, storage or return instructions; do not argue that a timed booking waives security. The visitor rules describe limited handling and possible refund assistance in qualifying cases, but they do not guarantee admission, storage or a replacement ticket. Removing the item from the day is the safest prevention.",
      tone: "warning",
    },
    {
      id: "luggage-plan",
      type: "callout",
      title: "Do not visit the Palace Museum with transfer-day luggage",
      body: "Suitcases are prohibited inside. The Palace Museum currently provides storage and free transfer for qualifying luggage, with deposit at the visitor service centre west of Duanmen Square and collection outside the north or east exit. That service has seasonal hours and storage conditions. Leaving luggage at the hotel is usually simpler; if storage is essential, check the current rule and choose the collection exit before handing over the bag.",
      tone: "warning",
    },
    {
      id: "day-of-recovery-heading",
      type: "heading",
      level: 2,
      text: "Day-of recovery: protect the trip, not the original script",
    },
    {
      id: "day-of-recovery-table",
      type: "table",
      caption: "When the morning does not match the plan",
      columns: ["Failure", "Immediate action", "Fallback"],
      rows: [
        ["You reached Shenwumen or another wrong gate", "Stop navigating to a generic Forbidden City pin and reset to the current Meridian Gate approach", "If the booked inspection boundary is no longer realistic, contact the official service point; do not expect entry through an exit"],
        ["The original booked passport is missing", "Retrieve it if the timing still works", "A photo or unrelated identity document is not a safe substitute; rebuild the day around another attraction if entry cannot be verified"],
        ["Security or walking consumes the buffer", "Protect the booked inspection period and remove Tiananmen sightseeing or the optional Palace side section", "Use the official two-hour museum route once inside"],
        ["A prohibited item blocks progress", "Use only the handling option staff currently authorise", "Leave the controlled area or follow the live refund process if the item cannot be accepted; storage and refund are not guaranteed"],
        ["The museum or chosen hall closes temporarily", "Read the dated Palace Museum notice and staff instructions", "Keep the central route if the museum is open; if the whole visit cannot operate, use the official refund notice and switch to a preselected Beijing backup"],
      ],
    },
    {
      id: "route-heading",
      type: "heading",
      level: 2,
      text: "Step 4: use three hours for the central route and one deliberate detour",
    },
    {
      id: "route-definition",
      type: "paragraph",
      text: "The Palace Museum publishes two-hour, half-day and one-day visitor trails. The plan below is Homeground's three-hour option between the first two official route lengths: it protects the south-to-north central sequence, leaves room for one side interest and finishes at the north gate. The three hours begin after passport inspection at the Meridian Gate. They do not include travel from the hotel, Tiananmen-area security, ticket troubleshooting or transport after exit.",
    },
    {
      id: "route-table",
      type: "table",
      caption: "A realistic three-hour route from the Meridian Gate to the north exit",
      columns: ["Elapsed time", "Route", "Decision rule"],
      rows: [
        ["0:00–0:20", "Meridian Gate → Inner Golden Water Bridges → Gate of Supreme Harmony", "Orient yourself and keep moving; this is not yet the place for the longest stop"],
        ["0:20–1:05", "Hall of Supreme Harmony → Hall of Central Harmony → Hall of Preserving Harmony", "Protect this central Outer Court sequence on a first visit"],
        ["1:05–1:45", "Take one side branch at its actual junction: an east-side gallery after the Hall of Preserving Harmony, or one open palace cluster around the Gate of Heavenly Purity", "Choose one branch and return to the central route; do not save every detour for the far north"],
        ["1:45–2:15", "Gate of Heavenly Purity → Palace of Heavenly Purity → Hall of Union → Palace of Earthly Tranquillity", "Resume the Inner Court central axis after the chosen branch"],
        ["2:15–2:45", "Imperial Garden", "Keep enough time to enjoy the garden without endangering the exit plan"],
        ["2:45–3:00", "Walk to the Gate of Divine Prowess and exit north", "Finish the route rather than backtracking for a missed side room"],
      ],
    },
    {
      id: "side-choice",
      type: "callout",
      title: "Choose the side section before entering",
      body: "If objects matter most, reserve or select one confirmed-open gallery and branch toward it where the official map actually turns east, usually after the Hall of Preserving Harmony. If palace interiors and spatial layout matter more, choose one open east- or west-side cluster around the Gate of Heavenly Purity. If a current exhibition is the priority, follow its stated location and let it replace the side section rather than adding it. Some galleries require a separate ticket or reservation, and temporary closures can change the viable route.",
      tone: "decision",
    },
    {
      id: "three-hour-limit",
      type: "paragraph",
      text: "Three hours is enough for a coherent first route, not for the entire Palace Museum. Queues inside, photography, rest stops, weather and gallery capacity can use the side-section allowance. If the central axis alone takes longer, cut the detour and keep the Imperial Garden and north exit. The route succeeds when it preserves energy and direction, not when every named hall is checked off.",
    },
    {
      id: "parents-callout",
      type: "callout",
      title: "With parents or slower walkers, shorten before you accelerate",
      body: "Make the Palace Museum the day's main walking block. Use the official two-hour route as the fallback, add seated pauses, and do not place Jingshan automatically after the north exit. A three-hour admission block can still produce a much longer door-to-door outing once the southern approach and the journey from Shenwumen are included.",
      tone: "neutral",
    },
    {
      id: "route-cuts-heading",
      type: "heading",
      level: 2,
      text: "What to protect and what to cut when time slips",
    },
    {
      id: "route-cuts",
      type: "comparison",
      columns: [
        {
          heading: "Protect",
          items: [
            "The booked inspection period and original passport",
            "The Meridian Gate entrance",
            "The main south-to-north sequence",
            "A controlled finish at the chosen exit",
          ],
        },
        {
          heading: "Cut first",
          items: [
            "A second paid gallery",
            "Crossing from east-side rooms to west-side rooms",
            "A temporary exhibition that was not the main reason for booking",
            "An automatic Jingshan climb after the Palace",
          ],
        },
      ],
    },
    {
      id: "closures-heading",
      type: "heading",
      level: 2,
      text: "Step 5: check the calendar again, even after buying the ticket",
    },
    {
      id: "closures-analysis",
      type: "paragraph",
      text: "The standing calendar is seasonal and normally excludes Mondays, but statutory holidays and dated announcements can change opening days, entry routes or individual buildings. A special Monday opening does not create a general Monday rule, and an open museum does not prove that every gallery is open. The booking record, the current Visit page and the latest dated notice must agree before the route is final.",
    },
    {
      id: "hours-table",
      type: "table",
      caption: "Standing hours shown by the Palace Museum at the 22 August 2026 review",
      columns: ["Season", "Opening", "Last admission", "Museum closes"],
      rows: [
        ["1 April–31 October", "08:30", "16:00", "17:00"],
        ["1 November–31 March", "08:30", "15:30", "16:30"],
      ],
    },
    {
      id: "hours-boundary",
      type: "callout",
      title: "These hours are a checkpoint, not a guarantee",
      body: "The Palace Museum says holidays and special circumstances may extend, shorten or suspend opening. Individual halls, the Treasure Gallery, the Gallery of Clocks and current exhibitions can have separate last-entry or closure notices. Check the live official pages when booking and again before leaving for the museum.",
      tone: "warning",
    },
    {
      id: "closure-checklist",
      type: "callout",
      title: "Use three live checks for a high-risk date",
      body: "Check once when booking, again 24–48 hours before the visit, and once more before leaving the hotel. On statutory holidays, major-event dates or days with severe weather, read the newest Palace Museum notice and current Tiananmen instructions rather than copying yesterday's route. Save a flexible backup such as the Temple of Heaven, Summer Palace or a neighbourhood day, but confirm its own ticket and opening rules before using it.",
      tone: "decision",
    },
    {
      id: "exit-heading",
      type: "heading",
      level: 2,
      text: "Step 6: leave through Shenwumen with the next move already chosen",
    },
    {
      id: "north-exit",
      type: "paragraph",
      text: "The Gate of Divine Prowess is the Palace Museum's north exit and faces Jingshan Park across the road. It is not a morning entrance and it does not return you to the southern starting point. The museum's transport page lists bus stops at Shenwumen and Jingshan East Gate, says there is no dedicated Palace Museum car park and recommends public transport. Bus routes and road controls are operational details, so verify them in a live map on the day.",
    },
    {
      id: "exit-options",
      type: "table",
      caption: "What to do after the north-gate exit",
      columns: ["Next plan", "Best preparation", "Common mistake"],
      rows: [
        ["Finish sightseeing", "Use a confirmed bus stop or legal pickup point and return to the hotel area", "Assuming a taxi will wait directly under the gate"],
        ["Continue to Jingshan", "Cross only by the current pedestrian route and treat the climb as a separate energy decision", "Adding the hill automatically because it looks adjacent"],
        ["Continue into the northern old city", "Check the exact walking, bus or car connection to the named next place", "Using 'hutongs' or 'Shichahai' as an imprecise destination"],
        ["Collect stored luggage", "Use the exit selected when depositing the bag and check collection hours", "Leaving through the other gate and creating a recovery trip"],
        ["Use the East Prosperity Gate", "Confirm that the exit is open and connect from the east side", "Assuming the east and north exits lead to the same transport plan"],
      ],
    },
    {
      id: "pickup-plan",
      type: "callout",
      title: "A north-gate pickup needs a pin, not a promise",
      body: "Ask a driver, guide or hotel for the exact legal pickup point in Chinese and save it before entering. Mobile signal, road controls and stopping rules can change the practical meeting point. 'Meet at the Forbidden City exit' is not specific enough when the museum has two visitor exits and the north gate faces another busy attraction.",
      tone: "decision",
    },
    {
      id: "faq-heading",
      type: "heading",
      level: 2,
      text: "Questions that derail the visit",
    },
    {
      id: "faq-north-entry",
      type: "callout",
      title: "Can I enter at the north gate?",
      body: "No. The Gate of Divine Prowess is an exit. Visitor entry is through the Meridian Gate on the south side.",
      tone: "neutral",
    },
    {
      id: "faq-tiananmen",
      type: "callout",
      title: "Do I need a separate Tiananmen Square reservation?",
      body: "Under the current published Tiananmen measures, no separate square reservation is needed when you hold a valid same-day Palace Museum reservation; show that record at the on-site check. Recheck official notices before major events or temporary controls. The reverse is not true: a square reservation never replaces the Palace Museum ticket.",
      tone: "neutral",
    },
    {
      id: "faq-sold-out",
      type: "callout",
      title: "What should I do if the Forbidden City is sold out?",
      body: "Do not travel to the gate expecting a foreigner exception. Check only official inventory, move the museum to another available Beijing day, or use a confirmed substitute and keep the rest of the city plan. A reseller can provide a wider service, but it must still produce a valid Palace Museum booking record for each visitor.",
      tone: "neutral",
    },
    {
      id: "faq-passport",
      type: "callout",
      title: "Is a passport photo enough?",
      body: "No. The Palace Museum requires the original valid document used for booking. Keep a digital copy for general travel backup, but do not substitute it for the booked original at inspection.",
      tone: "neutral",
    },
    {
      id: "faq-three-hours",
      type: "callout",
      title: "Is three hours really enough?",
      body: "It is enough for the central axis, one controlled side choice, the Imperial Garden and a north-gate exit at a steady pace. It is not enough for a complete museum survey, multiple galleries, long interpretation stops and both east and west palace clusters.",
      tone: "neutral",
    },
    {
      id: "fact-label",
      type: "callout",
      title: "Official fact versus Homeground planning judgment",
      body: "The ticket release, accepted identity documents, original-document requirement, time periods, Monday closure, seasonal hours, one-way entrance and exits, published visitor trails, luggage service and transport listings come from the official sources below. The exact three-hour allocation, the instruction to choose only one side section, the default north exit and the pickup strategy are Homeground planning judgments built on those facts.",
      tone: "neutral",
    },
    {
      id: "prepublish-heading",
      type: "heading",
      level: 2,
      text: "Final checks before leaving for the visit",
    },
    {
      id: "prepublish-list",
      type: "list",
      items: [
        "The Palace Museum ticket page still shows the same release window, accepted foreign documents and inspection periods.",
        "The current official English or Chinese channel instruction still matches the method used, and a completed reservation record exists for every visitor.",
        "The latest notice does not change the Monday calendar, daily hours or the chosen visit date.",
        "The Meridian Gate remains the entrance and Shenwumen remains available as the intended exit.",
        "The selected side gallery or exhibition is open and any extra reservation has been secured.",
        "The current Tiananmen Square rule has been checked separately, including whether a valid Palace Museum record still removes the need for a second reservation.",
        "Every traveller has a confirmed record that matches the original document they will carry; no one is relying on a companion's booking.",
        "The prohibited-items list has been checked and the approach budget includes walking and security rather than a promised queue time.",
        "The north-gate bus, pickup or luggage-collection plan has been confirmed for the day.",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Continue planning Beijing",
      items: [
        {
          label: "Where to stay in Beijing on a first trip",
          href: "/guides/beijing-where-to-stay-first-trip/",
          description: "Compare Wangfujing, Qianmen, Sanlitun and northern hutongs using both the Palace entrance and north-gate exit.",
        },
        {
          label: "China with older parents",
          href: "/guides/china-itinerary-with-older-parents/",
          description: "Build the visit around walking tolerance, recovery time and a preselected exit.",
        },
        {
          label: "Is your China itinerary too rushed?",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Check whether the Palace day still leaves a realistic amount of energy for the rest of Beijing.",
        },
        { label: "Verify a China attraction ticket", href: "/guides/official-or-reseller-china-tickets/", description: "Identify the attraction’s ticket owner, compare reseller support and terms, and verify the booking state before trusting a China attraction ticket." },
        { label: "Choose a Summer Palace gate and route", href: "/guides/summer-palace-gates-route-and-boat-plan/", description: "Match the East, North or New Palace Gate to your priorities, understand base versus combined tickets and build a route that still works if boats stop." },
        { label: "Plan a Temple of Heaven visit", href: "/guides/temple-of-heaven-gates-and-ritual-sequence/", description: "Use a separate gate, ticket and ritual-sequence plan for another major Beijing heritage site." },
      ],
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official sources reviewed",
      items: [
        {
          label: "Palace Museum official English ticket and international-visitor booking instructions",
          url: "https://intl.dpm.org.cn/ticket_details.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Palace Museum official ticket-service link",
          url: "https://bookingticket.dpm.org.cn/",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Palace Museum ticketing and identity-document rules",
          url: "https://www.dpm.org.cn/subject_booking/",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Palace Museum opening hours, visitor trails, gates and transport",
          url: "https://www.dpm.org.cn/Visit.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Palace Museum visitor, security and luggage rules",
          url: "https://www.dpm.org.cn/singles_detail/259831.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Palace Museum prohibited-items catalogue",
          url: "https://www.dpm.org.cn/singles_detail/259832.html",
          publisher: "The Palace Museum",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Beijing 12345 guidance for Palace Museum booking with a foreign passport",
          url: "https://english.beijing.gov.cn/12345hotline/faqs/all/202506/t20250620_4117980.html",
          publisher: "People's Government of Beijing Municipality",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Tiananmen Square trial reservation measures and Palace Museum exemption",
          url: "https://tamgw.beijing.gov.cn/zhengwugongkai/tzgg/202111/t20211119_2541156.html",
          publisher: "Tiananmen Area Management Committee",
          reviewedAt: "2026-08-22",
        },
        {
          label: "Current official Tiananmen Square reservation channels",
          url: "https://english.beijing.gov.cn/travellinginbeijing/attractions/202603/t20260325_4566110.html",
          publisher: "People's Government of Beijing Municipality",
          reviewedAt: "2026-08-22",
        },
      ],
    },
  ],
} as const;
