import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "In mainland China, a foreign licence or IDP alone is normally insufficient. Visitors usually need the temporary-permit route unless traffic management confirms current mutual recognition for that exact licence. Before renting, confirm the rental-location authority, documents, translation, learning, age/ability, body-certificate submission and validity. Neither same-day issue nor car release is guaranteed. Hong Kong and Macao differ." },
    { id: "answer", type: "callout", title: "Clear two gates before paying", tone: "decision", body: "First, get local traffic-management confirmation: normally a foreign licence, temporary permit and required translation; or a current mutual-recognition route expressly covering you and that licence. An IDP alone proves neither. Second, the rental firm must accept documents, vehicle, age/experience, payment, identity check and contract/coverage terms. If either fails, do not drive; use non-driving transport." },
    { id: "gate-heading", type: "heading", level: 2, text: "Start with the eligibility gate" },
    { id: "gate-table", type: "table", caption: "Verify before building a self-drive route", columns: ["Question", "Evidence", "If unconfirmed"], rows: [["Where to apply?", "Written answer from traffic management where the rental unit is located", "NIA's entry/residence reference and Article 11 differ; do not guess"], ["Is the foreign licence valid and full?", "Original, categories, expiry and accepted translation", "Learner, temporary or expired licences may fail"], ["Does an agreement apply?", "Current written answer for that country and licence", "Follow the normal permit path; IDP is no substitute"], ["Which vehicle?", "Categories on the licence and confirmed authority", "Do not exceed the narrower category"], ["Enough time?", "Appointment, checks, learning/test and rental verification", "Stay non-driving until both gates clear"]] },
    { id: "jurisdiction", type: "callout", title: "Mainland only", tone: "warning", body: "Hong Kong and Macao have separate visitor-driving rules. Importing your own vehicle is also outside scope: registration, inspection, insurance and plate procedures form another route. Ask the relevant authority." },
    { id: "materials-heading", type: "heading", level: 2, text: "Build a document pack, then ask the local office to validate it" },
    { id: "materials-list", type: "list", ordered: true, items: ["For a rental, ask traffic management at the rental-unit location to confirm the venue; save its reply.", "Carry the original accepted entry document and applicable stay evidence; visa-free entrants should ask what proves admission.", "Carry the valid foreign licence original; note categories and expiry. A scan or IDP alone is insufficient.", "Confirm who may translate and whether notarisation is accepted or required. Keep licence and translation together.", "Confirm photos. Beijing lists two one-inch white-background colour photos; Shanghai describes on-site photography. Neither is national.", "Confirm forms, appointment, learning, age/ability and body-certificate submission. Beijing says small cars 18+, ability test at 70+, and no body-condition certificate for temporary small-car/motorcycle applicants; confirm elsewhere.", "Confirm date, stages and payment without assuming hours, fees or same-day completion.", "Save the dated reply, offline copies and instructed originals."] },
    { id: "materials-table", type: "table", caption: "Separate identity, licence and process evidence", columns: ["Packet", "Check", "Failure"], rows: [["Entry identity", "Name/number match application and rental", "Old passport, unclear stay or name mismatch"], ["Foreign licence", "Valid full original covers the vehicle", "Expired, learner, provisional or wrong category"], ["Chinese translation", "This office accepts issuer and format", "App translation or unrecognised document"], ["Photo", "Local specification and on-site option", "Copying another city's requirements"], ["Process", "Venue, learning, age/ability, body-certificate rule and collection", "Missing a local step"]] },
    { id: "local-heading", type: "heading", level: 2, text: "Local pages illustrate variation; they do not create one national checklist" },
    { id: "local-table", type: "table", caption: "What reviewed official pages say", columns: ["Scope", "Current fact", "Boundary"], rows: [["National framework", "Three months, or up to one year for longer approved stay; mutual recognition can change the route", "Confirm the exact licence; no frozen country list"], ["Venue conflict", "NIA's reference page says entry/residence; MPS Order No. 90 Article 11 says rental-unit location for a rented Chinese vehicle", "Ask traffic management in the intended rental location; self-imported vehicles differ"], ["Beijing 2026", "Small cars: 18+; ability test at 70+; temporary entrants need not submit a body-condition certificate for small-car/motorcycle permits", "Beijing service instruction; reconfirm locally"], ["Shanghai 2026", "On-site photo/application, road-law learning, local translation, 18+ and 70+ ability test", "Shanghai only; service details change"]] },
    { id: "period", type: "callout", title: "A maximum is not your validity", tone: "warning", body: "National, Beijing and Shanghai pages describe three months for shorter stays and up to one year for longer approved stays. Printed permit dates, lawful stay and category control. ‘Up to’ is no entitlement; do not drive after a controlling document expires." },
    { id: "scenario-one-heading", type: "heading", level: 2, text: "Scenario: two-day city stop and a prepaid road trip" },
    { id: "scenario-one", type: "paragraph", text: "You land Friday and an advert offers evening airport pickup, but the permit counter, translation and rental verification are unconfirmed. Do not prepay a non-refundable car or depend on it for a remote first night. Ask authority and rental firm separately, save both replies and keep rail or a licensed driver as fallback." },
    { id: "rental-heading", type: "heading", level: 2, text: "Treat car release as a second approval" },
    { id: "rental-table", type: "table", caption: "Driving authority and booking prove different things", columns: ["Check", "Get in writing", "Do not infer"], rows: [["Driver eligibility", "Documents plus provider age/experience rules", "Online booking means approval"], ["Category", "Car fits confirmed authority, licence and permit if used", "Every rental car is covered"], ["Identity timing", "Foreign-customer deadline and result", "Same-day release; national guidance says first-time foreign renters should verify identity one working day ahead"], ["Payment/deposit/cover", "Card, deposit/refund, cover document, exclusions and incident route", "A logo, product or booking guarantees payment, cover or claim"], ["Additional driver", "Separate authority, provider eligibility and contract listing", "One approval covers a companion"]] },
    { id: "rental-boundary", type: "callout", title: "A booking is not driving authority", tone: "warning", body: "Take the car only after the branch accepts the documents, names every driver, matches the car to confirmed authority and provides applicable coverage documents and key exclusions. This promises neither coverage nor a claim result. Informal reassurance cannot expand a permit. If refused, do not take keys or use another account." },
    { id: "scenario-two-heading", type: "heading", level: 2, text: "Scenario: permit issued, rental company still refuses" },
    { id: "scenario-two", type: "paragraph", text: "Your permit is valid, but the branch rejects the translation or cannot verify you. Do not photograph staff/private screens. Request written reason and booking status, save payment and terms, then contact official support. Never drive an uncontracted car. If unresolved, read cancellation consequences and switch transport; a permit cannot compel a rental." },
    { id: "before-heading", type: "heading", level: 2, text: "Before the first kilometre" },
    { id: "before-list", type: "list", ordered: true, items: ["Check the authority document's name, dates, category and carry rules; correct errors before driving.", "On the permit route, carry it with the original licence and accepted translation; Shanghai also says carry the rental contract.", "Every driver must be named, authorised and meet provider age/experience rules.", "Record vehicle, damage, fuel/charge, toll method, equipment and return state without others' data.", "Save contract, cover/waiver, exclusions and official incident steps; none guarantees a claim.", "Load Chinese address/offline fallback; verify restrictions, weather and parking.", "If tired, impaired, unable to operate the car or read essential signs, use a licensed driver.", "Keep a non-driving exit if authority, contract, vehicle or route fails."] },
    { id: "failure-heading", type: "heading", level: 2, text: "Failure recovery" },
    { id: "failure-table", type: "table", caption: "Stop before the problem grows", columns: ["Failure", "Recovery", "Never"], rows: [["Document rejected", "Ask which item/rule/replacement; note office/date", "Alter it or shop informal counters"], ["Translation rejected", "Use the stated qualified/notarised route; recheck before paying", "Use phone translation as legal proof"], ["Step unfinished", "Move the trip; use transit/licensed driver", "Drive while pending"], ["Rental refuses", "Get written status; contact official support; save payment/terms", "Use another account"], ["Permit wrong/expired", "Stop; ask issuer about correction/applicable renewal", "Assume grace from a screenshot"], ["Official conflict", "Save URL/language/date/replies; ask local traffic authority; 12345 may route", "Choose the easier version silently"]] },
    { id: "change-table", type: "table", caption: "Facts that change the answer", columns: ["New fact", "Change"], rows: [["Current recognition covers this licence", "Ask traffic authority what it authorises and what to carry"], ["City changes", "Reconfirm office, validity and rental branch"], ["Age, health or capacity step applies", "Allow time for that local process; do not copy another city"], ["Vehicle changes", "Recheck licence, permit and contract"], ["Rental deadline missed", "Use non-driving plan; handle contract in writing"], ["Any controlling document ends sooner", "Earliest expiry ends driving"]] },
    { id: "freshness", type: "paragraph", text: "Reviewed 2026-09-01; freshness class: high-risk dynamic. Recheck national rules, recognition, venue rules, local pages, translation, age/ability, body-certificate submission, rental verification and stay. English summaries may lag Chinese pages. Preserve conflicting URL, language and date; ask traffic management in the intended rental location. Local 12345 may route but not issue. Until clarified, do not drive." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final go/no-go check" },
    { id: "verify-list", type: "list", items: ["Mainland trip; Hong Kong/Macao checked separately.", "Traffic authority confirmed the applicable route.", "Entry document, licence, translation, photos and local steps are accepted where required.", "The permit is issued and correct, or written confirmation says current mutual recognition covers you, this licence and carried documents.", "Today falls within every controlling validity.", "Vehicle fits the narrower category.", "Rental branch accepted originals, payment, identity, age and experience.", "Every driver is named; cover, exclusions and incident steps were read without assuming a claim result.", "Required authority and rental documents are carried.", "Safe non-driving fallback works. Any ‘no’ means do not drive."] },
    { id: "links", type: "internal-links", title: "Prepare the supporting travel record", items: [{ label: "Keep passport names consistent across China bookings", href: "/guides/passport-name-across-china-bookings/", description: "Prevent identity mismatches between the application, rental account and payment record." }, { label: "Confirm shifted map pins in China", href: "/guides/china-map-coordinate-offset-explained/", description: "Save Chinese addresses and verify destinations before driving." }, { label: "Set up tourist payments for China", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Keep a second payment route for deposits, tolls and transport fallback." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "State Council visitor guide — car leasing", url: "https://english.www.gov.cn/2025special/bizexpatsinchina2025", publisher: "State Council", reviewedAt: "2026-09-01" }, { label: "Current driver-licensing provisions", url: "https://www.gov.cn/gongbao/2025/issue_11866/material/gwygb202505.pdf", publisher: "State Council Gazette", reviewedAt: "2026-09-01" }, { label: "Temporary-entry motor vehicles and drivers regulation", url: "https://www.shanghai.gov.cn/grjszywgjj/20240826/3c73b5e4a7544a2aa382f7cdb6b38916.html", publisher: "Ministry of Public Security rule / Shanghai Government", reviewedAt: "2026-09-01" }, { label: "NIA temporary-driving-licence guidance", url: "https://en.nia.gov.cn/n147428/n147498/n147770/n147875/c158921/content.html", publisher: "National Immigration Administration", reviewedAt: "2026-09-01" }, { label: "Beijing inbound temporary-permit FAQ", url: "https://english.beijing.gov.cn/specials/beijinginboundtour/faqs/202601/t20260119_4446163.html", publisher: "Beijing Municipal Government", reviewedAt: "2026-09-01" }, { label: "Beijing temporary-driving-permit service", url: "https://jtgl.beijing.gov.cn/jgj/93950/jwgk/jsrgl/203470/index.html", publisher: "Beijing Traffic Management Bureau", reviewedAt: "2026-09-01" }, { label: "Shanghai temporary-driving-permit guide", url: "https://english.shanghai.gov.cn/en-Individuals-Transportation-Driving/20260826/e6a1cf154b104c1bbb64c19133abb530.html", publisher: "Shanghai Traffic Police Corps", reviewedAt: "2026-09-01" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
