export default {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "direct-answer",
      type: "lead",
      text: "Choose Dayan Old Town if this is a short first stay and you want Lijiang's main historic centre, central-city access and a wider choice of evening activity within one base. Choose Shuhe if you deliberately want a smaller historic cluster on the north-west side of town and do not mind making a separate trip to Dayan. But book the address, not the label: the nearest legal drop-off, the walk with luggage and the exact street at night can matter more than whether a listing says Dayan or Shuhe.",
    },
    {
      id: "quick-decision",
      type: "callout",
      title: "The practical default",
      body: "For a first visit of one or two nights, Homeground's default is the vehicle-accessible edge of Dayan rather than a room deep inside its lanes. Choose Shuhe when the accommodation and slower base are part of the reason for the trip—not because a search result promises it will always be quiet. Most travellers can stay in one and visit the other without changing hotels.",
      tone: "decision",
    },
    {
      id: "names-heading",
      type: "heading",
      level: 2,
      text: "First, untangle the name Lijiang Old Town",
    },
    {
      id: "names-explained",
      type: "paragraph",
      text: "On booking sites and maps, Lijiang Old Town often means Dayan, the large historic centre beside modern central Lijiang. The formal UNESCO property called the Old Town of Lijiang is wider: it comprises Dayan Old Town, including Black Dragon Pond, plus the Baisha and Shuhe housing clusters. Shuhe is therefore not outside the World Heritage site; it is a separate component of the same serial property.",
    },
    {
      id: "baisha-note",
      type: "callout",
      title: "There is a third heritage component",
      body: "Baisha is the third settlement in the UNESCO property. It deserves its own stay-or-visit decision, but adding it here would turn a focused Dayan-versus-Shuhe accommodation question into a general Lijiang guide. Do not assume that a hotel marketed simply as being in the World Heritage old town is in Dayan.",
      tone: "neutral",
    },
    {
      id: "at-a-glance",
      type: "table",
      caption: "Dayan and Shuhe as accommodation bases",
      columns: ["Decision point", "Dayan Old Town", "Shuhe Ancient Town"],
      rows: [
        ["Heritage relationship", "The largest settlement component and the historic commercial centre described by UNESCO", "A separate housing cluster within the same UNESCO World Heritage property"],
        ["Relative position", "Central Lijiang", "About 4 km north-west of Dayan according to UNESCO"],
        ["Inscribed-property area", "84 hectares for the Dayan Old Town component; Heilongtan Pool is separately listed at 17 hectares", "14.5 hectares for the Shuhe component"],
        ["Best planning fit", "A short first stay, central-city access and more choice after sightseeing", "A deliberately slower base, a specific hotel stay or plans concentrated north of central Lijiang"],
        ["Last-mile risk", "Ordinary motor vehicles need approval to enter Dayan; an inside-the-old-town address can still require a substantial walk", "Official records describe optimised bus and taxi drop-off points and shared e-bike parking management; exact access still depends on the entrance and property"],
        ["Quiet guarantee", "None; conditions vary by street, room and date", "None; Shuhe also has established tourism businesses and services"],
      ],
    },
    {
      id: "area-boundary",
      type: "paragraph",
      text: "The UNESCO areas above measure the inscribed heritage components. Heilongtan Pool is listed separately from the 84-hectare Dayan Old Town component, so the Dayan figure must not be read as the total size of every related heritage or visitor area. None of these figures measures the full accommodation district, commercial spillover, walking time or number of hotels. They are useful for understanding scale, not for calculating an itinerary by hectares.",
    },
    {
      id: "choose-dayan-heading",
      type: "heading",
      level: 2,
      text: "Choose Dayan for a short, central first stay",
    },
    {
      id: "dayan-fit",
      type: "paragraph",
      text: "UNESCO describes Dayan as the commercial centre established in the Ming period, and it remains Lijiang's main historic centre. Staying here keeps the old town, modern central Lijiang and a wide range of evening activity in the same daily orbit. That is useful when time is limited, but it does not mean every inner lane is equally convenient.",
    },
    {
      id: "dayan-reasons",
      type: "list",
      items: [
        "This is the easier default when Dayan itself is the main reason for visiting Lijiang.",
        "A perimeter hotel can combine old-town access with a shorter luggage transfer than a room deep inside the pedestrian lanes.",
        "Official visitor services and night-time cultural activity are concentrated around the main old-town area, although individual facilities and events have their own schedules.",
        "If different people in the group want different evening routines, the larger central district usually leaves more alternatives within the same base.",
      ],
    },
    {
      id: "dayan-limit",
      type: "callout",
      title: "Inside Dayan is not the same as easy access",
      body: "Provincial heritage rules restrict ordinary motor vehicles inside Dayan unless approved. A hotel can look central on a map yet require luggage to cross stone lanes, bridges, slopes or steps. Ask for the exact legal drop-off point and walking route before choosing an atmospheric interior address.",
      tone: "warning",
    },
    {
      id: "choose-shuhe-heading",
      type: "heading",
      level: 2,
      text: "Choose Shuhe when the base itself is part of the trip",
    },
    {
      id: "shuhe-fit",
      type: "paragraph",
      text: "Shuhe is a distinct historic settlement rather than a remote annex of Dayan. Official heritage and provincial sources describe a settlement organised around waterways, with its own residential, trading and craft traditions. Its smaller inscribed component and north-west position can keep more of the stay within a compact area—provided the property, street and transport plan actually match that intention.",
    },
    {
      id: "shuhe-reasons",
      type: "list",
      items: [
        "It can suit a longer stay built around one courtyard hotel or resort rather than repeated evenings in central Lijiang.",
        "Its location can reduce some geographic backtracking for selected northbound plans, but only after the actual pickup point is confirmed.",
        "Dated official records document Shuhe connections with the airport and railway-station network, so choosing it does not automatically require a private transfer; confirm the service for your date.",
        "You can visit Dayan from Shuhe without moving hotels; official sources have documented public links between the two settlements, although current service must be rechecked.",
      ],
    },
    {
      id: "quiet-myth",
      type: "callout",
      title: "Do not choose Shuhe on a promise of quiet",
      body: "Recent local-government material describes traffic management, organised bus and taxi drop-offs, visitor services and extensive commercial activity in Shuhe. That is evidence of a functioning tourism district, not proof that it is noisy—but it does rule out calling the whole town undiscovered or reliably empty. A back lane can be calm while a square is active, and the reverse can change with events and seasons.",
      tone: "warning",
    },
    {
      id: "address-heading",
      type: "heading",
      level: 2,
      text: "The exact hotel pin matters more than the old-town name",
    },
    {
      id: "vehicle-reality",
      type: "paragraph",
      text: "The clearest standing rule applies to Dayan: ordinary motor vehicles cannot enter without approval. Shuhe management material documents optimised bus and taxi drop-off points and shared e-bike parking management, but it does not establish one permanent access rule for every street and hotel. Treat access as property-specific in both places.",
    },
    {
      id: "hotel-checks",
      type: "list",
      items: [
        "Request the hotel's Chinese name, live map pin and the name of the closest legal drop-off—not only a screenshot of the old-town label.",
        "Ask how far luggage must be carried or rolled, whether the route has steps or bridges and whether staff collection is available at your arrival time.",
        "Confirm whether the room faces a bar, performance square, main lane, courtyard or service alley; a town-wide quiet label cannot answer this.",
        "Check late-night arrival and early-departure access separately from daytime sightseeing access.",
        "If reduced mobility matters, ask for a continuous route from drop-off to room and do not accept the word accessible without details.",
      ],
    },
    {
      id: "luggage-decision",
      type: "callout",
      title: "A useful booking test",
      body: "Imagine arriving after dark in rain with every suitcase. If the host cannot explain the final route in concrete terms, the room is not yet a reliable choice—however attractive its courtyard photos look.",
      tone: "decision",
    },
    {
      id: "transport-heading",
      type: "heading",
      level: 2,
      text: "Neither base is always better for airports, trains or day trips",
    },
    {
      id: "transport-intro",
      type: "paragraph",
      text: "Transport has changed enough that old blog instructions are a weak basis for choosing a base. The latest official records found in our August 2026 review document links for both Dayan and Shuhe, but those records have different publication dates. Confirm current timetables, pickup points and extra services for your travel date.",
    },
    {
      id: "transport-table",
      type: "table",
      caption: "What the dated official transport record supports",
      columns: ["Journey", "Supported fact", "Planning implication"],
      rows: [
        ["Lijiang airport", "A 2026 summer-flight-season update says the airport express added both Lijiang Old Town North Gate (Dayan) and Shuhe Ancient Town pickup points", "Neither base is uniquely convenient for the airport; check whether the service covers your date and direction"],
        ["Lijiang railway station", "A 2024 provincial transport article listed three station-to-Shuhe routes; a 2025 official interview said station services may be supplemented according to train demand", "These are dated records, so match the hotel entrance to a current stop rather than relying on an old route number"],
        ["Dayan to Shuhe", "Official destination material has published a tourist-bus connection between the two", "A visit from one base to the other is reasonable, but the old timetable and fare are not a 2026 guarantee"],
        ["Jade Dragon Snow Mountain", "A May 2026 scenic-area notice confirms the Baisha visitor centre, sightseeing train and internal sightseeing vehicles; separate city connections are date-sensitive", "Use the official channel to confirm the booked product and departure point before treating either base as better"],
      ],
    },
    {
      id: "snow-mountain",
      type: "paragraph",
      text: "Shuhe lies north-west of Dayan, in the broad direction of Jade Dragon Snow Mountain. That can reduce backtracking for some transfers. A 2025 official record documented a Shuhe bus loop to the sightseeing-train station, but it does not confirm that the same service is operating in 2026. A Dayan hotel near a current departure point may still be simpler. Confirm the mountain product and transport method before using this day trip as the deciding factor.",
    },
    {
      id: "altitude-note",
      type: "callout",
      title: "Do not choose between them for acclimatisation",
      body: "UNESCO describes the Old Town of Lijiang property as lying on the Lijiang plain at roughly 2,400 metres. Its material does not support presenting Shuhe as a higher acclimatisation base or Dayan as a meaningfully lower one.",
      tone: "neutral",
    },
    {
      id: "evening-heading",
      type: "heading",
      level: 2,
      text: "For evenings, compare streets and rooms—not slogans",
    },
    {
      id: "evening-analysis",
      type: "paragraph",
      text: "Dayan is the stronger default if you want a large historic centre around you after dinner; official tourism material identifies the old-town area as a night-time culture and consumption cluster. In Shuhe, it can be easier to keep the evening within a smaller area and finish earlier, but there are still squares, performances, restaurants and busy visitor periods. In either place, ask the hotel what happens outside the exact room between 20:00 and midnight and whether windows face the activity.",
    },
    {
      id: "heritage-heading",
      type: "heading",
      level: 2,
      text: "Heritage is not a contest between authentic and commercial",
    },
    {
      id: "heritage-analysis",
      type: "paragraph",
      text: "UNESCO recognises the shared value of Dayan, Shuhe and Baisha through their settlement forms, water systems, architecture and cultural interchange. Dayan's long commercial role does not make its heritage less real, nor does Shuhe's smaller scale mean it has been untouched by tourism. Choose the spatial experience that fits the trip without turning living heritage into a purity ranking.",
    },
    {
      id: "mobility-heading",
      type: "heading",
      level: 2,
      text: "Travellers with suitcases, strollers or limited walking stamina",
    },
    {
      id: "mobility-analysis",
      type: "paragraph",
      text: "The heritage landscape follows uneven topography and water channels; stone paving, bridges, gradients and steps can appear in both settlements. No official source reviewed for this guide supports calling either entire old town universally step-free. A perimeter stay with a verified drop-off can be easier than an interior stay in either place, and the room's internal stairs matter as much as the lane outside.",
    },
    {
      id: "mobility-checks",
      type: "list",
      items: [
        "Ask for a short phone video of the full route from drop-off to reception when access is critical.",
        "Confirm lift access, room level and bathroom setup; many heritage-style properties use stairs and courtyards.",
        "Keep the first and final nights near reliable vehicle access if an early train or flight cannot move.",
        "Do not assume a luggage cart will be available, permitted on every surface or operating late at night.",
      ],
    },
    {
      id: "hours-heading",
      type: "heading",
      level: 2,
      text: "Opening hours, entry fees and reservations need attraction-level checks",
    },
    {
      id: "hours-analysis",
      type: "paragraph",
      text: "Dayan and Shuhe are historic settlement areas, not two museums with one shared opening schedule. The current first-party record does not support publishing a single permanent town-wide ticket, reservation or closing-time rule here. Individual courtyards, museums, performances, events, transport services and any applicable heritage-fee arrangements can follow separate rules. Check the official Lijiang Old Town channel and the named venue shortly before travel.",
    },
    {
      id: "split-heading",
      type: "heading",
      level: 2,
      text: "Should you split the stay between Dayan and Shuhe?",
    },
    {
      id: "split-analysis",
      type: "paragraph",
      text: "Usually not on a short trip. UNESCO places Shuhe about 4 km from Dayan, and public connections have been documented. Moving hotels converts a simple visit into check-out, luggage transfer and check-in. A split becomes reasonable only on a longer stay when the second property is itself an experience or when the second half of the itinerary has genuinely different departure logistics.",
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "A simple way to choose",
    },
    {
      id: "decision-list",
      type: "list",
      ordered: true,
      items: [
        "First Lijiang stay, one or two nights and no strong hotel preference? Start with the accessible edge of Dayan.",
        "Want to walk out into the main historic centre and keep evenings flexible? Choose Dayan, then verify the exact room and lane.",
        "Have chosen a specific courtyard property or want the accommodation to anchor a slower stay? Compare Shuhe first.",
        "Building the trip around Jade Dragon Snow Mountain? Choose only after confirming the official pickup and access method for your date.",
        "Travelling with heavy luggage, a stroller or limited stamina? The verified drop-off-to-room route overrides the town label.",
        "Still undecided? Stay in one place and visit the other; do not move hotels just to experience both.",
      ],
    },
    {
      id: "fact-label",
      type: "callout",
      title: "What is fact, and what is Homeground judgment?",
      body: "The heritage relationship, component areas, relative position, Dayan vehicle rule and dated transport statements come from the official sources below. The recommendations about trip length, perimeter hotels, avoiding a split stay and which base fits a travel style are Homeground planning judgments built on those facts.",
      tone: "neutral",
    },
    {
      id: "final-check-heading",
      type: "heading",
      level: 2,
      text: "Recheck these details before booking",
    },
    {
      id: "final-check-list",
      type: "list",
      items: [
        "The property's exact Chinese name, live map pin and whether it is actually in Dayan, Shuhe or a surrounding development.",
        "The legal vehicle drop-off, walking surface, steps and luggage plan for the arrival time.",
        "The room's direction and the street's real evening use.",
        "Current airport express, railway-station bus and Dayan–Shuhe connection details.",
        "The confirmed pickup for Jade Dragon Snow Mountain or any other fixed-time excursion.",
        "Separate opening, ticket and reservation rules for every paid venue or performance.",
      ],
    },
    {
      id: "related-guides",
      type: "internal-links",
      title: "Keep planning your China trip",
      items: [
        {
          label: "Explore China",
          href: "/explore/",
          description: "Browse destination-led guides and practical comparisons.",
        },
        {
          label: "Is your China itinerary too rushed?",
          href: "/guides/is-your-china-itinerary-too-rushed/",
          description: "Check whether a hotel change or extra day trip creates more transfer pressure than value.",
        },
        {
          label: "Why are hotels in China so cheap?",
          href: "/guides/why-are-hotels-in-china-so-cheap/",
          description: "Understand what a low room rate may and may not include before comparing properties.",
        },
      ],
    },
    {
      id: "official-sources",
      type: "sources",
      title: "Official, first-party and image sources",
      items: [
        {
          label: "Old Town of Lijiang: heritage components, position and significance",
          url: "https://whc.unesco.org/en/list/811/",
          publisher: "UNESCO World Heritage Centre",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Official component maps and inscribed areas",
          url: "https://whc.unesco.org/en/list/811/maps/",
          publisher: "UNESCO World Heritage Centre",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Yunnan regulation on protection of the Old Town of Lijiang",
          url: "https://www.ljgc517.com/#/article?id=356ff004-ce41-4b79-97ec-8d4b519c961b&category=%E6%94%BF%E7%AD%96%E6%B3%95%E8%A7%84",
          publisher: "Lijiang Old Town official website",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Shuhe place-name heritage profile",
          url: "https://ynmz.yn.gov.cn/cms/dimingfengcai/10076.html",
          publisher: "Yunnan Provincial Department of Civil Affairs",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Shuhe visitor and traffic-management update",
          url: "https://credit.lijiang.gov.cn/ebcff3e78f99468e9ae6b46cbf6e8975.html",
          publisher: "Lijiang municipal government information platform",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Lijiang tourism transport and railway-station connections",
          url: "https://jtyst.yn.gov.cn/html/2025/zaixianfangtan_0611/3134349.html",
          publisher: "Yunnan Provincial Department of Transport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Dated railway-station routes to Shuhe",
          url: "https://jtyst.yn.gov.cn/html/2024/xingyexinwen_0307/131376.html",
          publisher: "Yunnan Provincial Department of Transport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "2026 airport express and summer-flight-season update",
          url: "https://www.lijiang.cn/article/170410.html",
          publisher: "Lijiang Media Center, with Lijiang Airport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Dated Dayan–Shuhe public-transport guidance",
          url: "https://www.ljgc517.com/#/article?id=0890611e-71e2-4258-a089-02e4ca619a34&category=%E6%97%85%E6%B8%B8%E6%94%BB%E7%95%A5",
          publisher: "Lijiang Old Town official website",
          reviewedAt: "2026-08-10",
        },
        {
          label: "2026 Jade Dragon Snow Mountain ticket and access notice",
          url: "https://www.lijiang.cn/news/travel/article/172717.html",
          publisher: "Jade Dragon Snow Mountain Scenic Area, via Lijiang Media Center",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Dated Shuhe–sightseeing-train bus-loop record",
          url: "https://szb.lijiang.cn/pc/concent/202507/15/c88750.html",
          publisher: "Lijiang Daily and Lijiang Public Transport",
          reviewedAt: "2026-08-10",
        },
        {
          label: "2026 Lijiang cultural-tourism and night-economy update",
          url: "https://mzzj.yn.gov.cn/html/2026/difangdongtai_0224/4062781.html",
          publisher: "Yunnan Ethnic and Religious Affairs Commission",
          reviewedAt: "2026-08-10",
        },
        {
          label: "Hero image: a pedestrian street in Lijiang Old Town (Dayan) by ChiralJon, CC BY 2.0; cropped and converted to WebP",
          url: "https://commons.wikimedia.org/wiki/File:Lijiang_Old_Town.jpg",
          publisher: "Wikimedia Commons",
          reviewedAt: "2026-08-11",
        },
      ],
    },
  ],
} as const;
