import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "If bleeding is heavy or cannot be controlled, the eye is seriously injured, breathing or consciousness is affected, or there is another immediate danger, call 120 and follow emergency instructions; do not delay life-saving care to finish washing. Otherwise, after a bite, scratch, saliva contact with broken skin or mucosa, or direct bat contact in China, wash exposed skin thoroughly and flush an exposed eye, mouth or other mucosa immediately, then seek professional assessment promptly. Do this even if the animal looks healthy, the mark seems small or you were vaccinated before." },
    { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "For exposed skin, wash with soap or cleanser and running water for about 15 minutes under China's specification or at least 15 minutes under WHO wording. For an eye, mouth or other mucosa, flush immediately with plenty of clean water or saline; never put soap or disinfectant into an eye. Obtain qualified clinical assessment and a written record. Do not wait for animal observation or choose a vaccine, schedule or immunoglobulin plan from an article." },
    { id: "now-heading", type: "heading", level: 2, text: "What to do immediately" },
    { id: "now-steps", type: "list", ordered: true, items: ["For uncontrolled bleeding, serious eye injury, breathing or consciousness problems, or immediate danger, call 120. Do not delay emergency care for a timer.", "Move away; do not catch, handle or closely photograph the animal.", "Wash exposed skin with soap or cleanser and running water: about 15 minutes in China's specification, at least 15 in WHO wording.", "Flush an exposed eye, mouth or other mucosa immediately with clean water or saline. Never put soap or disinfectant into an eye. Report the site even without a mark.", "Seek assessment promptly. If washing or care was delayed, report the real timeline rather than giving up.", "Record time, place, body site, contact, skin condition, bleeding and animal species—only observed facts.", "Bring identification and prior rabies-vaccination records. Previous vaccination does not remove assessment."] },
    { id: "wash-boundary", type: "callout", title: "Washing is first aid, not the completed decision", tone: "warning", body: "Skin washing and mucosal flushing are different actions, and both still require clinical assessment. Neither replaces the other. Do not improvise treatment, put cleaning agents into an eye, or delay for a preferred brand or English-speaking provider." },
    { id: "assessment-heading", type: "heading", level: 2, text: "Let the clinician classify the contact" },
    { id: "class-table", type: "table", caption: "China's category descriptions help you report facts; they are not a self-triage tool", columns: ["Official category description", "Examples named in the Chinese specification", "What the traveller should do"], rows: [["Category I", "Touching or feeding an animal, or a lick on intact skin", "Describe the contact and skin condition accurately; let the clinician confirm the category"], ["Category II", "Nibbling of uncovered skin, or a minor scratch or abrasion without bleeding", "Promptly obtain professional vaccine assessment; do not downgrade a small mark yourself"], ["Category III", "A bite or scratch through the skin, saliva on damaged skin or mucosa, or direct contact with a bat", "Promptly obtain professional assessment of vaccine and passive immunisation needs"]] },
    { id: "assessment-list", type: "list", items: ["Show the site, including small scratches; do not say only ‘a bite.’", "Separate observations from assumptions and mention covering clothing.", "Report when washing or flushing began and its duration.", "Share animal details obtainable without more contact; do not capture it.", "Ask for clinical assessment of the wound, other injury, infection and tetanus as well as rabies; do not choose treatments here.", "Request the category and plan in writing, not only in translated conversation.", "Request an identifiable, dated record of anything administered."] },
    { id: "scenarios-heading", type: "heading", level: 2, text: "Two situations that commonly change the traveller's decision" },
    { id: "owned-animal", type: "paragraph", text: "Scenario 1: an owned dog nips your hand; the owner says it is vaccinated and can be watched. Move away, wash fully and seek prompt assessment. Keep owner details only if safe, but do not make care depend on records or observation. A healthy-looking, owned animal is not permission to wait or self-classify." },
    { id: "unknown-animal", type: "paragraph", text: "Scenario 2: an unknown cat scratches your ankle without visible bleeding before an intercity trip. Wash and report the mark. Category II includes minor scratches or abrasions without bleeding, but a clinician classifies it. If travel cannot change, obtain assessment and a written handoff, then confirm the receiving facility's access and stock." },
    { id: "bat", type: "callout", title: "Direct bat contact has a specific boundary", tone: "warning", body: "China's 2023 specification places direct bat contact in category III. Do not dismiss it because no mark is visible or wait for symptoms. Wash any identifiable contact area and seek prompt assessment. If you only saw a bat, report that fact without self-classifying." },
    { id: "previous-heading", type: "heading", level: 2, text: "Previous vaccination changes the handoff, not the need to ask" },
    { id: "previous-table", type: "table", caption: "Bring evidence instead of reconstructing a history from memory", columns: ["What you know", "What to show", "Do not decide"], rows: [["Documented previous vaccination", "Dates, product or clinic record, and whether before travel or after exposure", "New schedule, product or that no action is needed"], ["Vaccinated, record missing", "Approximate place and dates; facility or insurer that may retrieve it", "That memory proves completion"], ["No vaccination or unknown", "State that the history is absent or uncertain", "A vaccine or passive-immunisation plan from an online table"], ["Doses in another country", "Original record and a clear image or translation", "Whether to substitute products or change timing"]] },
    { id: "handoff-heading", type: "heading", level: 2, text: "Continue care across a city move or flight home" },
    { id: "handoff-steps", type: "list", ordered: true, items: ["Obtain the category, assessment date, wound site and written plan.", "For anything administered, record time, product, available manufacturer and batch, dose, route or site, and facility contact; list passive immunisation separately.", "Ask what needs reassessment and when to attend; do not design a schedule.", "Keep the original, a photo and a private backup; redact identifiers before public sharing.", "Carry records, not vaccine. China's 2023 specification prohibits giving recipients vaccine to store or take to another clinic; facilities manage cold chain.", "Ask the next facility whether it can review the record and continue care. Never assume matching stock, brand, language or walk-in access.", "Show all records and let the receiving clinician resolve product or timing questions."] },
    { id: "access-heading", type: "heading", level: 2, text: "If access fails at the first facility" },
    { id: "access-table", type: "table", caption: "Failure recovery without invented availability", columns: ["Problem", "Recovery", "Boundary"], rows: [["Product unavailable", "Request referral; check that day's local health-commission or CDC official directory, then call with the first assessment", "Confirm opening, assessment and clinician-required components; no stock promise or self-carried vaccine"], ["No English", "Show: 请问附近的狂犬病暴露预防处置门诊（犬伤门诊）在哪里？ Use trusted interpretation and get the plan in writing", "This asks for the nearest rabies-exposure clinic; translation is not a provider record"], ["Payment blocked", "Ask accepted methods, keep receipts and contact the insurer or card issuer while seeking care", "Foreign cards, apps and insurance are not universal"], ["Leaving the city", "Obtain assessment, a complete handoff and a confirmed next provider", "Travel does not decide category or regimen"], ["Owner says wait", "Keep safely obtained details but continue washing and assessment", "Do not delay for observation or paperwork"]] },
    { id: "failure", type: "callout", title: "A closed door is a referral problem, not a reason to stop", tone: "decision", body: "Ask the first facility for a 狂犬病暴露预防处置门诊（犬伤门诊）, then check that day's local health-authority or CDC official directory or inquiry channel and call the next site. Confirm whether it is open, can assess you and can provide what its clinician decides is needed. If the next also cannot help, preserve both contacts and continue through another qualified facility or insurer assistance. Use 120 for serious or life-threatening injury, not as a product-inventory line. Stock, English, fees and insurance acceptance vary; this guide guarantees none." },
    { id: "record-table", type: "table", caption: "Your portable exposure record", columns: ["Field", "Minimum detail", "Use at next stop"], rows: [["Exposure", "Date, time, city, animal, contact and body site", "Reconstruct the event"], ["Skin or mucosa", "Observed intact skin, scratch, bite, bleeding, damage or mucosal contact", "Support clinical classification"], ["First aid", "Wash start and approximate duration", "Show what happened without claiming completion"], ["Prior vaccination", "Record, dates and provider, or ‘unknown’", "Prevent assumption"], ["Clinical decision", "Provider, date, category and written plan", "Create a handoff"], ["Products", "Name, available manufacturer and batch, date, dose and administration details", "Identify what was given"], ["Next contact", "Facility, phone, appointment or reassessment instruction", "Recover continuity after travel"]] },
    { id: "change-table", type: "table", caption: "Conditions that change the next practical step", columns: ["Condition", "Decision adjustment"], rows: [["Direct bat contact", "Report China's category III boundary and seek prompt assessment without waiting for a mark"], ["Minor scratch, no bleeding", "Report the category II descriptor; let the clinician classify"], ["Previous vaccination", "Bring records and still obtain assessment"], ["Unknown animal", "Use observed contact facts; do not await observation"], ["Departure ahead", "Obtain a written handoff and confirm the receiver"], ["Official wording differs", "Preserve source, language, date and advice; escalate instead of choosing silently"]] },
    { id: "freshness-heading", type: "heading", level: 2, text: "Freshness and official-source conflicts" },
    { id: "freshness", type: "paragraph", text: "This high-risk dynamic guide was reviewed on 2026-09-01 against China's 2023 specification, China CDC, WHO's fact sheet and 2024 protocol, and a 2026 Chinese reminder. Recheck after changes to those documents or local referral, stock or access. China says wash about 15 minutes; WHO says at least 15, so both are disclosed. If official editions, dates or current clinical advice conflict, preserve each and ask the provider or issuer to resolve them; never assemble your own regimen." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final verification before you move on" },
    { id: "verify-list", type: "list", items: ["Immediate danger went to 120 without waiting for washing.", "Skin was washed; mucosa was flushed without soap or eye disinfectant.", "A clinician heard the contact, site, condition and timeline.", "Wound, infection and tetanus were raised for assessment.", "Category and plan are written, not self-selected.", "Previous vaccination is documented or marked unknown.", "Products are identifiable; only records, not vaccine, move between facilities.", "The next route has stock, language and payment backups.", "Animal observation, symptoms or brand preference caused no delay."] },
    { id: "links", type: "internal-links", title: "Prepare the practical backup", items: [{ label: "Paying in China as a tourist", href: "/guides/how-to-pay-in-china-as-a-tourist/", description: "Set up more than one payment route before an urgent expense." }, { label: "China eSIM or local SIM", href: "/guides/china-esim-vs-local-sim/", description: "Choose data, a local number or dual-SIM access for calls and follow-up." }, { label: "Why map pins shift in China", href: "/guides/china-map-coordinate-offset-explained/", description: "Confirm a facility with its Chinese address and a local-map pin before travelling." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Technical Specification for Rabies Exposure Prophylaxis (2023 edition)", url: "https://www.ndcpa.gov.cn/jbkzzx/c100081/common/content/content_1715172596229992448.html", publisher: "National Disease Control and Prevention Administration", reviewedAt: "2026-09-01" }, { label: "Rabies prevention and control information", url: "https://en.chinacdc.cn/in_focus/202310/t20231025_270302.html", publisher: "Chinese Center for Disease Control and Prevention", reviewedAt: "2026-09-01" }, { label: "Rabies fact sheet", url: "https://www.who.int/news-room/fact-sheets/detail/rabies", publisher: "World Health Organization", reviewedAt: "2026-09-01" }, { label: "Protocol for a well-performed rabies post-exposure prophylaxis delivery", url: "https://www.who.int/publications/i/item/B09018", publisher: "World Health Organization", reviewedAt: "2026-09-01" }, { label: "2026 rabies-exposure health reminder", url: "https://www.beijing.gov.cn/fuwu/bmfw/sy/jrts/202604/t20260408_4576299.html", publisher: "Beijing Municipal People's Government / National Health Commission material", reviewedAt: "2026-09-01" }, { label: "Beijing rabies-exposure prophylaxis clinic directory (local example only)", url: "https://www.beijing.gov.cn/fwcj/chang/5d137a6be42c49809b5e9ce60e84999d.html", publisher: "Beijing Municipal People's Government", reviewedAt: "2026-09-01" }, { label: "Measures for the Administration of Pre-hospital Medical Emergency Care", url: "https://www.nhc.gov.cn/wjw/c100221/202201/26ea3c97e82d466f9aa2b4a9901ae187.shtml", publisher: "National Health Commission", reviewedAt: "2026-09-01" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
