import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "Do not fly an accompanied dog or cat to mainland China until five things align: one eligible animal per traveller, official export documents, a matching readable microchip, the correct origin/quarantine branch and an arrival port able to handle it. Airline acceptance is separate. Every exemption still requires a passed on-site quarantine inspection." },
    { id: "direct-answer", type: "callout", title: "The answer is conditional", tone: "decision", body: "A complete file does not guarantee admission. Use the current GACC service guide's Consultation link or call 12360, then ask the exact airport/terminal pet office. Silence is not permission." },
    { id: "humane-gate", type: "callout", title: "Plan failure before booking", tone: "warning", body: "Excess animals, missing certificates, a wrong port or failed quarantine can lead to time-limited return or destruction. Pre-arrange authorised custody, return transport, decision authority and funds. Without a humane fallback, do not fly the animal." },
    { id: "scope", type: "callout", title: "Accompanied mainland entry only", tone: "warning", body: "This covers cabin or checked-baggage pets. Air-waybill/manifest cargo is separate even when the owner travels. Other species, wildlife/CITES, Hong Kong/Macao/Taiwan, carrier rules, local keeping, onward transport and export are excluded." },
    { id: "gate-heading", type: "heading", level: 2, text: "Make the no-fly decision first" },
    { id: "gate-table", type: "table", caption: "Pre-departure status—not a clearance forecast", columns: ["Status", "Use when", "Action"], rows: [["Confirmation pending", "One dog/cat; file, chip, branch and port align", "Send exact facts to Customs"], ["Isolation candidate", "Exemption incomplete; 30-day route may exist", "Confirm facility, capacity and handoff"], ["Conflict hold", "Official versions disagree", "Save both; ask actual port"], ["Document hold", "Certificate, lab, test or chip mismatch", "Correct through issuer"], ["No-fly", "Ineligible case, unconfirmed port/fitness or no humane fallback", "Change the plan"]] },
    { id: "identity-heading", type: "heading", level: 2, text: "Lock the animal and journey identity" },
    { id: "identity-list", type: "list", ordered: true, items: ["Confirm dog/cat status; refer hybrid/wildlife doubt.", "Assign no more than one pet per actual traveller.", "Record export origin and every transit; ask which origin controls.", "Scan and copy the full chip number.", "Match it across animal, certificate, vaccination record and report.", "Record chip standard; ask if a reader is needed.", "Identify first mainland port/terminal; ask the carrier whether No. 133's defined international-through-flight service—not a self-built connection—applies.", "Ask a veterinarian about transport and quarantine fitness."] },
    { id: "branch-heading", type: "heading", level: 2, text: "Choose a branch, then confirm it" },
    { id: "branch-table", type: "table", caption: "No. 5 branches; none guarantees release", columns: ["Branch", "Extra evidence", "Route", "Still required"], rows: [["GACC-designated origin", "Valid chip", "Conditional isolation exemption", "Passed on-site inspection"], ["Non-designated origin", "Valid chip; recognised-lab report", "Conditional isolation exemption", "Accepted report/threshold; inspection"], ["Guide, hearing or search-and-rescue dog", "Valid chip; user/training proof", "Conditional isolation exemption", "Accepted evidence; inspection. Missing only rabies certificate may allow a narrow vaccination application"], ["No exemption completed", "Base file; confirmed handoff", "30-day designated isolation", "Capable port; passed quarantine"]] },
    { id: "threshold", type: "callout", title: "Do not gamble on exactly 0.5 IU/ml", tone: "warning", body: "The Chinese announcement uses ‘0.5 IU/ml以上’; official English/local versions vary between ‘above’ and inclusive wording. A recognised lab can confirm the report identity, result and unit, but only 12360 and the actual arrival Customs office can address acceptance of exactly 0.5 for this entry." },
    { id: "documents-heading", type: "heading", level: 2, text: "Build one document-to-chip pack" },
    { id: "documents-table", type: "table", caption: "Follow issuer and arrival-authority formats", columns: ["Item", "Verify", "If it fails"], rows: [["Official health/quarantine certificate", "China route; export authority; pet/chip match", "Issuer correction; no generic vet letter"], ["Rabies certificate", "Issuer, pet, chip and validity match", "Stop. Only a named working dog missing this alone may seek confirmed qualified-institution vaccination; no release promise"], ["Microchip record", "Number matches and scans", "Rescan; issuer correction"], ["Antibody report", "If non-designated: recognised lab, result/unit/date, chip", "No unlisted lab or screenshot"], ["Working-dog proof", "Named category; user/training evidence", "No emotional-support relabelling"], ["Journey/port record", "Origin, transit, first port/terminal; No. 133 facility/handoff if applicable", "Recheck every change"], ["Declaration/registration", "Current baggage declaration and dog/cat registration", "Ask port: paper or pre-registration, and where"], ["Official answer", "Authority, facts, date, language, reference", "Evidence, not pre-clearance"]] },
    { id: "timing", type: "callout", title: "Validate every date", tone: "decision", body: "No. 5 Annex 1 requires an official examination within 14 days before arrival. For non-designated origins, blood draw cannot precede the second rabies vaccination; the result lasts one year, but may continue after revaccination within the prior vaccine's validity. Vaccine and result must be valid on arrival. Have both authorities validate dates." },
    { id: "lists", type: "callout", title: "Do not route from a copied list", tone: "warning", body: "GACC's origin, lab and facility-port lists change. Freeze no list. Use the service guide's Customs link or 12360; confirm facility, terminal, date and branch before booking." },
    { id: "confirmation-heading", type: "heading", level: 2, text: "Ask a file-specific question" },
    { id: "confirmation-list", type: "list", ordered: true, items: ["Give species, traveller assignment and chip number/standard.", "Give origin, transits and first port/terminal; ask carrier if No. 133 service applies.", "Name issuer and examination/issue dates.", "Give vaccination details and conflicts.", "If non-designated, give lab, blood date, result/unit; ask recognition.", "Ask which No. 5 exemption or 30-day branch may apply, subject to inspection.", "For confirmed No. 133 service, verify first-port facilities and handoff even if exempt; otherwise verify them whenever isolation may apply.", "Ask copy/original, form, filing-place, reader and retention-record requirements."] },
    { id: "reply-table", type: "table", caption: "Save advice; it is not a permit", columns: ["Field", "Save", "If missing"], rows: [["Authority", "12360 or exact office via service-guide link", "Unresolved"], ["Journey", "Origin, transit, date, first terminal, No. 133 status", "Recheck after change"], ["Pet/file", "Species, chip, issuer, vaccine, lab/report", "Generic question fails"], ["Response", "Words, date, language, reference", "Clarify; keep versions"], ["Limits", "Inspection, capacity, return conditions", "Infer no time/cost/outcome"]] },
    { id: "packing-heading", type: "heading", level: 2, text: "Prepare two independent handoffs" },
    { id: "packing-list", type: "list", items: ["Customs: animal, readable chip, organised originals/copies and saved confirmation.", "Carrier: for cabin or checked-baggage carriage, verify every segment, airport, crate and check-in instruction; an air-waybill/manifest-cargo move uses a separate Customs process.", "Carrier acceptance never equals China admission.", "Never alter, backdate or relabel documents.", "Test any required compatible chip reader before travel.", "Keep veterinarian, emergency contact and safe-care details offline.", "Pre-arrange authorised return custody/transport and funds."] },
    { id: "scenario-one-heading", type: "heading", level: 2, text: "Scenario: an Australia-origin pet meets a conflicting local summary" },
    { id: "scenario-one", type: "paragraph", text: "No. 5 and Australia's current dog/cat export instructions require a rabies certificate. A Shanghai FAQ conflicts, but cannot justify omission. Follow the Australian process and No. 5 unless the export authority and actual arrival Customs jointly give a current, verifiable alternative for this file." },
    { id: "scenario-two-heading", type: "heading", level: 2, text: "Scenario: non-designated report is missing or exactly 0.5" },
    { id: "scenario-two", type: "paragraph", text: "The lab must be recognised, the chip/file must match and Customs must accept the threshold. Otherwise consider 30-day isolation only at a confirmed capable port. No. 133 requires every pet on its carrier-confirmed through-flight service—not an ordinary connection—to use a facility-capable first port even if exempt. Missing capacity, handoff, welfare or return answers means change the trip." },
    { id: "arrival-heading", type: "heading", level: 2, text: "At the first mainland Customs point" },
    { id: "arrival-list", type: "list", ordered: true, items: ["Declare the animal, submit the current passenger baggage declaration and dog/cat information-registration form as instructed, and follow the marked quarantine route.", "Present the animal and complete evidence pack.", "Allow document review, chip scan and on-site inspection.", "Answer with recorded origin, transit, identity and branch facts.", "If released, save the available record; later rules remain separate.", "If retained, isolated or returned, read the voucher/notice before leaving."] },
    { id: "failure-heading", type: "heading", level: 2, text: "If the plan fails" },
    { id: "failure-table", type: "table", caption: "Recover without endangering the animal", columns: ["Failure", "Act", "Never"], rows: [["Species/count invalid", "Activate authorised no-fly/return plan", "Split ownership or relabel"], ["Certificate rejected", "Get decision. For named working dog missing only rabies certificate, ask about qualified-institution vaccination; otherwise call issuer/return lead", "Edit, forge or assume release"], ["Chip mismatch/unreadable", "Offer reader/records; request written decision", "Change identity"], ["Report/threshold rejected", "Ask if port can isolate", "Assume lab or 0.5 passes"], ["No isolation facility", "Follow Customs; activate return team", "Self-transfer/remove pet"], ["Quarantine failed", "Request notice and permitted vet/return contact", "Interfere or promise release"], ["Return ordered", "Keep voucher; confirm deadline; arrange carriage", "Guess or abandon"]] },
    { id: "conflicts-heading", type: "heading", level: 2, text: "When official pages disagree" },
    { id: "conflict-table", type: "table", caption: "Conflicts change the decision", columns: ["Conflict", "Do", "Do not"], rows: [["No. 5 vs incomplete general summary", "Use unrepealed pet framework + current lists; ask port", "Treat summary as repeal/clearance"], ["Chinese vs English threshold", "Send report to Customs", "Let lab decide acceptance"], ["No. 5/Australia process vs Shanghai FAQ", "Carry rabies certificate; require joint-authority alternative", "Omit from FAQ alone"], ["Old No. 108 list vs dynamic/current details", "Confirm facility, terminal, date", "Trust count/name"], ["Advice vs on-site decision", "Save both; follow recorded direction", "Call advice a permit"]] },
    { id: "after-entry", type: "callout", title: "Release ends only this border task", tone: "decision", body: "Check destination keeping/licensing, housing, breed rules, veterinary care and onward transport separately. Entry clearance is not a return-country certificate or later carriage promise." },
    { id: "freshness", type: "paragraph", text: "ReviewedAt: 2026-09-04. This is a critical-freshness guide: recheck GACC rules and dynamic lists, the export authority, actual port and carriers after any route, date, document, chip, vaccination, report, animal-status or guidance change. Keep conflicting versions; silence is not permission." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final no-fly checklist" },
    { id: "verify-list", type: "list", items: ["One eligible dog/cat per actual traveller.", "Origin/transits classified by Customs.", "Official China-route certificate validated.", "Rabies rule resolved; narrow working-dog route confirmed if relevant.", "Chip scans and matches every record.", "If non-designated, lab/report/threshold accepted.", "Working-dog category/evidence confirmed.", "First port/terminal/facility confirmed; carrier states No. 133 status and handoff.", "Current baggage declaration and dog/cat registration method verified.", "Every carrier and airport accepts transport.", "Humane custody, return authority, carriage and funds arranged.", "Exact Customs/12360 answer saved; silence/conflict means no-fly.", "No assumed time, cost, language service, exemption or outcome.", "Local keeping, onward travel and export separated.", "Any unchecked item means no-fly; all checks still do not guarantee admission."] },
    { id: "links", type: "internal-links", title: "Keep arrival tasks separate", items: [{ label: "Choose the correct China Customs channel", href: "/guides/china-customs-red-green-channels/", description: "Use the declaration-lane workflow without treating it as pet clearance." }, { label: "Check food, plants and animal products", href: "/guides/food-plants-and-animal-products-into-china/", description: "Route pet food, bedding and other biosecurity items separately." }, { label: "Complete the China online arrival card", href: "/guides/china-online-arrival-card/", description: "The passenger card does not replace animal declaration or quarantine." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "GACC No. 5: accompanied pets", url: "https://www.mofcom.gov.cn/zcfb/zgdwjjmywg/art/2019/art_71739ec848d14deca4ec330fad835774.html", publisher: "GACC / MOFCOM", reviewedAt: "2026-09-04" }, { label: "Current quarantine guide and contact route", url: "https://online.customs.gov.cn/static/pages/guides/000629014001/000629014001.html", publisher: "GACC", reviewedAt: "2026-09-04" }, { label: "No. 5 official English translation", url: "https://english.beijing.gov.cn/livinginbeijing/lawsandpolicies/202104/t20210414_2355600.html", publisher: "Beijing Government", reviewedAt: "2026-09-04" }, { label: "Shanghai pet-entry guide, updated 2025-10-16", url: "https://english.shanghai.gov.cn/en-Individuals-DailyLife-Pets/20260813/76277aba545f43e78632b5d7b611741d.html", publisher: "Shanghai Government", reviewedAt: "2026-09-04" }, { label: "Chongqing pet-entry summary, 2026-06-09", url: "https://english.cq.gov.cn/services/entryandexit/EntryRequirements/202606/t20260609_15740129.html", publisher: "Chongqing Government", reviewedAt: "2026-09-04" }, { label: "GACC No. 64: list updates", url: "https://www.mofcom.gov.cn/zcfb/zgdwjjmywg/art/2019/art_f39e30c03fac42c89d3809d93d81023f.html", publisher: "GACC / MOFCOM", reviewedAt: "2026-09-04" }, { label: "Animal and Plant Quarantine Law regulation", url: "https://www.samr.gov.cn/fgs/zcfg/art/2023/art_1f6a53fff3364f50b00abab82ec5c013.html", publisher: "SAMR", reviewedAt: "2026-09-04" }, { label: "International Passenger Customs Guide", url: "https://english.customs.gov.cn/statics/88707c1e-aa4e-40ca-a968-bdbdbb565e4f.html", publisher: "GACC", reviewedAt: "2026-09-04" }, { label: "Hainan pet-entry guide, updated 2025-08-21", url: "https://en.hainan.gov.cn/englishsite/qli/202508/a56d0b8530fb47039455b57be1a248be.shtml", publisher: "Hainan Government", reviewedAt: "2026-09-04" }, { label: "GACC No. 31: dynamic site management", url: "https://swt.fujian.gov.cn/xxgk/jgzn/jgcs/dtgxdc/zcdt/202304/t20230424_6154486.htm", publisher: "GACC / Fujian Commerce", reviewedAt: "2026-09-04" }, { label: "Port-visa contacts/closure note—not pet facilities", url: "https://www.nia.gov.cn/n741440/n741542/c1633769/content.html", publisher: "NIA", reviewedAt: "2026-09-04" }, { label: "GACC No. 133: international through flights", url: "https://www.mofcom.gov.cn/zcfb/zgdwjjmywg/art/2019/art_b2850e5820014567931e8187d78723a6.html", publisher: "GACC / MOFCOM", reviewedAt: "2026-09-04" }, { label: "Australia Micor: dogs to China, reviewed 2026-08-18", url: "https://micor.agriculture.gov.au/live-animals/china/dogs", publisher: "Australian DAFF", reviewedAt: "2026-09-04" }, { label: "Australia Micor: cats to China, reviewed 2026-08-18", url: "https://micor.agriculture.gov.au/live-animals/china/cats", publisher: "Australian DAFF", reviewedAt: "2026-09-04" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
