import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "Staying on Gulangyu is not simply staying closer to Xiamen's best-known sight. It adds a ferry and a luggage handoff in exchange for island hours before and after the day-visitor peak. Zhongshan Road keeps the trip on the main island; Zengcuo'an shifts the stay toward the southeast coast. Choose the handoffs and evenings, not the prettiest listing photo." },
  { id: "answer", type: "callout", title: "The short decision", tone: "decision", body: "Choose Zhongshan Road for a first mixed trip, main-island flexibility and the simplest arrival/departure logic. Stay one night on Gulangyu when quiet island mornings and evenings justify booking the correct ferry, walking with a small bag and accepting limited vehicle access. Choose Zengcuo'an when coastal walks and a slower neighbourhood base repeat; avoid it when every day begins at a rail hub, ferry terminal or opposite side of the island." },
  { id: "boundary", type: "paragraph", text: "This guide chooses among three lodging bases. It does not provide a permanent ferry timetable, rank hotels or treat ‘near the beach’ as a guarantee of a swimmable beach or sea-view room. Ferry terminals and routes are dynamic; the official Xiamen ferry/port channel controls the travel-day answer." },
  { id: "matrix", type: "table", caption: "Three bases, three different handoffs", columns: ["Base", "What you gain", "What you accept", "Verify"], rows: [["Zhongshan Road area", "Main-island central evenings and flexible city days", "Not an island or resort stay", "Exact visitor ferry terminal, road entrance and station route"], ["Gulangyu overnight", "Island before/after day crowds and slower heritage time", "Ferry, walking, luggage and weather exposure", "Passenger terminal, sailing, island pier, steps and hotel route"], ["Zengcuo'an / southeast coast", "Coastal walks and a neighbourhood-led stay", "Longer trips to some hubs and ferry departures", "Road pickup, exact shoreline access and repeated-day fit"]] },
  { id: "trip-fit", type: "table", caption: "Use the repeated day to choose", columns: ["Trip pattern", "First base to test", "Reason"], rows: [["First Xiamen visit, two to four nights, varied sights", "Zhongshan Road", "Keeps ferry and city days flexible"], ["Gulangyu atmosphere is a main purpose and bags are light", "One Gulangyu night", "Island hours outside the busiest visit window justify the handoff"], ["Coastal cycling/walking and southeast-island time repeat", "Zengcuo'an", "The neighbourhood becomes part of several days"], ["Early flight or train after an island night", "Main island for the final night", "Removes a ferry dependency from departure"], ["Older parents, stroller or large cases", "Main-island accessible property", "Island paths and pier-to-room route require stronger evidence"]] },
  { id: "ferry", type: "heading", level: 2, text: "The ferry is part of the hotel check-in" },
  { id: "ferry-copy", type: "paragraph", text: "Xiamen Port's official route list distinguishes visitor and resident routes, multiple mainland terminals and Gulangyu piers. Do not copy a local resident's route or an old timetable. Use the official channel for the travel date, enter every passenger's required identity details correctly and match the mainland terminal, island pier and hotel. A ticket to the wrong pier may create a long island walk with luggage." },
  { id: "ferry-steps", type: "list", ordered: true, items: ["Choose the official visitor route for the date and passenger type.", "Book using the same valid passport or travel document carried to the terminal.", "Save the Chinese names of the mainland terminal and Gulangyu pier; similar ferry names are not interchangeable.", "Ask the hotel which pier suits its entrance and how long the actual walk takes with luggage.", "Leave buffer for identity check, boarding and weather/operating changes; use the live notice rather than a saved schedule."] },
  { id: "gulangyu", type: "heading", level: 2, text: "An island night should change how you use the island" },
  { id: "gulangyu-copy", type: "paragraph", text: "Stay overnight when you will deliberately use an early walk, a late quiet period or a slower two-part visit. If you arrive after lunch, check in, eat and leave early next morning, the ferry and bags may consume the benefit. Plan one island-only overnight bag, a pier-to-property route and a weather fallback. Confirm stairs, room access, breakfast and the first staff contact if the ferry is delayed." },
  { id: "luggage", type: "heading", level: 2, text: "Design the luggage handoff before buying the room" },
  { id: "luggage-copy", type: "paragraph", text: "Gulangyu is walked, not driven like a mainland hotel district. Xiamen's official reporting describes luggage collection points at Sanqiutian and Neicuo'ao with delivery points around the island, but current availability, eligibility and destination still need confirmation. Do not assume informal porter help. Store the main case on the mainland when practical, carry valuables yourself and ask the island property about lawful support." },
  { id: "zhongshan", type: "heading", level: 2, text: "Zhongshan Road: the flexible main-island base" },
  { id: "zhongshan-copy", type: "paragraph", text: "Zhongshan Road works because a traveller can combine an urban evening with different next-day directions without crossing water to sleep. It does not automatically sit beside the correct daytime visitor ferry terminal; routes differ by time and passenger type. Check the exact hotel road entrance, the chosen terminal and the rail/airport transfer. A pedestrian-street address may add a suitcase walk even in a central area." },
  { id: "zengcuoan", type: "heading", level: 2, text: "Zengcuo'an: choose a coastal routine, not a vague beach promise" },
  { id: "zengcuoan-copy", type: "paragraph", text: "This base makes sense when the southeast coast, village streets and a slower evening repeat. Ask what ‘near the sea’ means from the lobby: road crossing, actual public shoreline, sand access and swimming conditions are separate questions. Check road congestion, vehicle drop-off, room noise and the complete journey to any ferry, railway station or early departure you will use." },
  { id: "arrival", type: "heading", level: 2, text: "Protect the first and last transfer" },
  { id: "arrival-copy", type: "paragraph", text: "Xiamen and Xiamen North are different rail stations. Use the full ticket name, airport terminal and actual arrival time. After a late flight or train, stay on the main island unless a valid ferry and island check-in are both confirmed with buffer. Before an early departure, move the final night to a road-accessible mainland hotel if ferry uncertainty would endanger the train or flight." },
  { id: "mobility", type: "callout", title: "A short map distance can still be a hard island walk", tone: "warning", body: "For a wheelchair, stroller, painful knees or large cases, ask for pier surface, slopes, steps, doorway and lift all the way to the room. An official concession or assistance policy for transport does not make every island hotel accessible. If the property cannot describe the complete route, use a main-island hotel and visit Gulangyu with a day bag." },
  { id: "verify", type: "table", caption: "Questions for the final property", columns: ["Question", "A useful answer includes"], rows: [["Which ferry route?", "Visitor route, mainland terminal and island pier for the date"], ["How do bags reach the room?", "Walking surface, steps, confirmed service and storage"], ["Who handles late arrival?", "Staffed contact tied to the booked sailing"], ["What does ‘coastal’ mean?", "Actual route to public shoreline, not a map label"], ["How do we leave early?", "Road/ferry plan with operating buffer"], ["Can every passport check in?", "Named property process at the stated hour"]] },
  { id: "failure", type: "table", caption: "Recover when the handoff changes", columns: ["Problem", "Immediate action", "Safer plan"], rows: [["Booked sailing changes", "Use the official notice and contact the hotel", "Keep a cancellable main-island arrival night"], ["Ticket is for the wrong terminal/pier", "Do not rush across the city; replan through official channels", "Match property and pier before paying"], ["Weather disrupts island plan", "Protect the fixed onward train/flight", "Day visit or later island night"], ["Luggage route is harder than promised", "Use confirmed official/property support", "Store main bag and carry one night only"], ["Early departure has no safe ferry chain", "Move to mainland the previous day", "Do not gamble a fixed departure"]] },
  { id: "registration", type: "paragraph", text: "Ask island and mainland properties alike to confirm passport check-in and reception hours. Ferry access and heritage setting do not replace normal accommodation-registration duties." },
  { id: "dynamic", type: "paragraph", text: "Xiamen Port and ferry information was reviewed on August 12, 2026. Routes, terminals, sailings, ticket channels and luggage services can change with operations and weather. Recheck the official channel before booking transport and immediately before travel." },
  { id: "links", type: "internal-links", title: "Continue planning", items: [{ label: "Xiamen hubs to Gulangyu ferry terminal", href: "/guides/xiamen-hubs-to-gulangyu-ferry-terminal/", description: "Build the full station/airport-to-ferry handoff." }, { label: "Minsu, homestay or hotel", href: "/guides/minsu-homestay-or-hotel-china/", description: "Verify the island property's operation and room." }, { label: "China's last night before an international flight", href: "/guides/china-last-night-before-international-flight/", description: "Protect an early departure from an island base." }] },
  { id: "sources", type: "sources", title: "Official sources and image credit", items: [{ label: "Xiamen Port official passenger-route list", url: "https://port.xm.gov.cn/75549/202508/t20250807_2949332.html", publisher: "Xiamen Port Administration", reviewedAt: "2026-08-12" }, { label: "Xiamen Ferry official channel", url: "https://www.xmferry.com/", publisher: "Xiamen Ferry Co., Ltd.", reviewedAt: "2026-08-12" }, { label: "Official Gulangyu visitor and luggage-service guidance", url: "https://www.xm.gov.cn/jdhy/rdhy/202407/t20240722_2879674.htm", publisher: "Xiamen Municipal Government", reviewedAt: "2026-08-12" }, { label: "Hero: Xiamen ferry at Neicuo'ao by Mx. Granger, CC0; cropped and converted", url: "https://commons.wikimedia.org/wiki/File:Xiamen_ferry.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-12" }] }
] } as const satisfies StructuredPageBody;
export default body;
