import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    {
      id: "lead",
      type: "lead",
      text: "The lowest-risk way to approach Yunnan wild-mushroom hotpot is to choose cultivated mushrooms or another meal: national health guidance treats not eating wild mushrooms as the safest prevention. If you still choose a restaurant wild-mushroom meal, do not order from photographs or rarity claims. Ask which items are wild, which are cultivated, what each wild item is called, how the kitchen processed it and whether the proposed pot mixes species. Current Yunnan guidance says not to mix multiple wild varieties, to cook them thoroughly and not to drink alcohol with them. If the restaurant cannot make those controls clear, stop before the order is placed.",
    },
    {
      id: "answer",
      type: "callout",
      title: "Homeground's conservative first order",
      tone: "decision",
      body: "Choose one clearly named wild-mushroom item only if the restaurant can explain its source and kitchen process; pair it with ordinary cooked food and non-alcoholic drinks. This is an editorial response to official no-mixing guidance, not a declaration that one species or restaurant is safe. Decline an unexplained mixed wild set. If names, provenance or handling remain vague, ask for an all-cultivated-mushroom pot or leave. Once cooking starts, let staff control the release point, add no late raw mushrooms, and never use a taste test to decide whether the pot is ready.",
    },
    {
      id: "restaurant-heading",
      type: "heading",
      level: 2,
      text: "Choose a restaurant by evidence, not by a dramatic promise",
    },
    {
      id: "restaurant-p1",
      type: "paragraph",
      text: "A business licence, a busy dining room and a local companion are useful context, but none identifies a mushroom or guarantees safe handling. Yunnan's provincial food-safety notice places concrete duties on catering operators: control purchasing, refuse unfamiliar mushrooms, know an emergency process, use appropriate pre-treatment such as boiling or blanching, and retain a sample. Those are backstage controls, so a traveller cannot verify all of them by looking at a bubbling pot. The useful test is whether staff can give a consistent, specific account and are willing to remove an uncertain item rather than reassure you with confidence alone.",
    },
    {
      id: "restaurant-table",
      type: "table",
      caption: "Six checks before the burner is switched on",
      columns: ["Ask or observe", "A usable answer", "Reason to stop"],
      rows: [
        ["Restaurant identity", "The exact branch, current menu and a displayed valid food-business credential can be matched", "An unnamed temporary stall, improvised meal or seller who will not identify the operator"],
        ["Wild versus cultivated", "Staff point to every proposed mushroom and state which category it belongs to", "Everything is called only ‘mountain mushroom’ or ‘mushroom platter’"],
        ["Name and source", "The house records a Chinese market/product name and its supplier or purchasing channel", "The answer is only ‘the locals eat it’ or ‘picked this morning’"],
        ["Kitchen preparation", "Staff explain what the kitchen has already cleaned, sliced, blanched, boiled or otherwise processed for this item", "A claim that the dining-table boil alone makes any mushroom safe"],
        ["Species mixing", "The order avoids mixing wild varieties and keeps the named item traceable", "A fixed mixed wild set with no explanation compatible with current no-mixing advice"],
        ["Emergency record", "The operator knows its incident procedure and confirms that a sample/order record is retained", "No one knows what was served, what was retained or whom to contact"],
      ],
    },
    {
      id: "restaurant-warning",
      type: "callout",
      title: "‘Specialises in wild mushrooms’ is not a safety certificate",
      tone: "warning",
      body: "A restaurant may use a timer, hold back chopsticks or ask staff to manage the pot. These can be sensible house controls, but no province-wide rule found in this review requires every restaurant to use the same ritual. Ask what today's procedure means for today's item. A timer measures elapsed time; it cannot prove species identity, source, pre-treatment, temperature throughout the pot or whether somebody added a new raw piece.",
    },
    {
      id: "menu-heading",
      type: "heading",
      level: 2,
      text: "Turn the menu into three categories before choosing a pot",
    },
    {
      id: "menu-p1",
      type: "paragraph",
      text: "In everyday Yunnan restaurant language, 野生菌 means wild mushrooms or fungi, while 人工栽培菌 refers to cultivated products. A translated menu may flatten both into ‘mushroom’. A house name can also cover more than one biological species, and the same-looking specimen can be hard for non-specialists to distinguish. You are not performing taxonomy at the table. Your task is to make the restaurant state the classification, keep the order simple and refuse what cannot be described. A phone photograph, image-search result or bilingual menu icon is not an identification method.",
    },
    {
      id: "menu-table",
      type: "table",
      caption: "What the menu label changes",
      columns: ["Menu category", "Decision", "Do not infer"],
      rows: [
        ["Named wild mushroom / 野生菌", "Ask for the Chinese product name, source and item-specific kitchen process; order only one wild type in the conservative workflow", "The name proves a biological species, edibility or correct handling"],
        ["Cultivated mushroom / 人工栽培菌", "Useful fallback when you want a mushroom meal without the wild-source identification decision", "Cultivated means allergen-free, contamination-free or suitable for every diet"],
        ["Mixed wild set / 野生菌拼盘 or house set", "Decline unless a competent current authority and the operator can clearly reconcile it with Yunnan's no-mixing guidance; this guide found no such general exception", "Popularity or a fixed set makes the mixture approved"],
        ["Prepared mushroom dish from the kitchen", "Ask whether it is wild or cultivated and whether it contains several varieties, alcohol or an animal-based stock", "Kitchen-cooked automatically means risk-free"],
        ["Broth, chicken pot or mushroom-chicken pot", "Confirm chicken, pork, beef, lard, dairy and seasoning bases before treating it as vegetarian or allergy-compatible", "A pale or clear broth is plant-based"],
      ],
    },
    {
      id: "menu-warning",
      type: "callout",
      title: "Do not ask the internet to identify your plate",
      tone: "warning",
      body: "Yunnan and national health sources warn that toxic and edible mushrooms can look similar and that experienced people can still be wrong without specialist methods. A cropped cap, cooked slice or market-name caption removes even more evidence. If the restaurant cannot identify and document what it is serving, the recovery is not a better photo. Remove the wild item from the order.",
    },
    {
      id: "order-heading",
      type: "heading",
      level: 2,
      text: "Place one small first order with an exit built in",
    },
    {
      id: "order-p1",
      type: "paragraph",
      text: "A large mushroom banquet creates more names to track, more batches to time and more leftovers to explain if something goes wrong. Homeground's first-timer default is deliberately smaller: one restaurant-identified wild item at most, one cultivated-mushroom or ordinary vegetable option, one familiar cooked protein or tofu dish if wanted, plain rice, and water or tea. Confirm that the wild item will not be combined with another wild variety in the kitchen or pot. Order more only after the first batch is complete: choose ordinary food, cultivated mushrooms or the same recorded wild item under a new full staff-controlled process—not a second wild type. This is a decision aid, not an official portion prescription.",
    },
    {
      id: "order-table",
      type: "table",
      caption: "Four tables and the safer first move",
      columns: ["Situation", "Start here", "Exit condition"],
      rows: [
        ["Solo traveller", "Choose a kitchen-cooked cultivated-mushroom dish, or one clearly named wild dish only if the restaurant offers a small, traceable portion", "Skip the wild option if the only product is a large mixed set or staff cannot manage one person safely"],
        ["Two curious first-timers", "Share one small, clearly named wild item, add familiar cooked foods and keep both diners on the same batch", "Do not split attention across several raw plates or add a second wild type"],
        ["Group with one cautious diner", "Keep the whole shared pot cultivated, and order any separately managed wild dish only for willing diners if cross-contact and serving tools can be explained", "A divided pot does not by itself create an allergy-safe or preference-safe boundary"],
        ["Nobody can explain the menu in a shared language", "Use the Chinese phrase card below, a staff translation or an all-cultivated dish with an ingredient list", "Do not let a photo, price or queue substitute for a clear answer"],
      ],
    },
    {
      id: "order-p2",
      type: "paragraph",
      text: "Dietary requirements remain a separate decision. Mushroom broth may contain chicken stock, pork fat or other animal seasoning; a dipping sauce may contain soy, sesame, peanuts or another allergen; raw and cooked ingredients may share prep space. Ask about the whole preparation chain, not only the mushroom. With a severe allergy or strict religious/vegetarian boundary, leave if the restaurant cannot confirm ingredients and cross-contact controls. Choosing cultivated mushrooms removes one wild-identification problem, not every food-safety or dietary risk.",
    },
    {
      id: "clock-heading",
      type: "heading",
      level: 2,
      text: "Use one pot, one batch and one release decision",
    },
    {
      id: "clock-p1",
      type: "paragraph",
      text: "Exact cooking time depends on what the mushroom is, how it was cut and pre-treated, how much enters the pot and the restaurant's controlled process. This guide therefore gives no number of minutes. Before anything goes in, ask staff to state who adds the mushroom, when the cooking period begins, whether the lid stays on and who says it is ready. If staff temporarily remove serving utensils, do not retrieve replacements or taste from the pot. Their house procedure is meaningful only if the sequence remains intact.",
    },
    {
      id: "clock-list",
      type: "list",
      ordered: true,
      items: [
        "Photograph or write down the Chinese name on the order before cooking; do not use the image to identify the species yourself.",
        "Confirm that this batch contains only the agreed wild item and that kitchen pre-treatment has already been completed.",
        "Let the assigned staff member add the mushroom and start the restaurant's process. Keep other raw plates away from the pot.",
        "Do not lift a piece to inspect, taste or return it. Moving it out and back does not establish doneness and can confuse the sequence.",
        "Add no fresh mushroom, topping or leftover raw piece while the process is running. Ordinary vegetables go later only if staff says they will not disrupt the control.",
        "Accept the pot only after the responsible staff member gives an explicit release for this batch—not because the broth bubbles, the timer rings or another table begins eating.",
        "If raw mushroom was added late, tell staff immediately. Only the same confirmed, recorded wild item can begin a new complete staff-controlled process from its latest addition. If the added mushroom is different or unknown, stop eating from the entire pot; a restarted timer cannot recover it.",
      ],
    },
    {
      id: "clock-warning",
      type: "callout",
      title: "Thorough cooking is necessary, but it cannot repair a wrong species",
      tone: "warning",
      body: "Yunnan guidance requires conditionally edible mushrooms to be processed and cooked thoroughly. The same public-health material warns that some mushroom toxins remain dangerous after high heat. These statements are not contradictory: correct identification and source control come first; item-appropriate pre-treatment and thorough cooking come next. ‘It boiled for a long time’ is not a rescue for an unknown or poisonous mushroom.",
    },
    {
      id: "myths-heading",
      type: "heading",
      level: 2,
      text: "Reject six shortcuts that cannot prove a mushroom is safe",
    },
    {
      id: "myths-table",
      type: "table",
      caption: "What official guidance says the shortcut cannot do",
      columns: ["Shortcut", "Why it fails", "Useful replacement"],
      rows: [
        ["‘Only brightly coloured mushrooms are poisonous’", "Dangerous species can be pale or ordinary-looking, while colour alone does not determine edibility", "Rely on controlled sourcing and professional identification, never colour"],
        ["‘Worms or insects ate it’", "Animals can feed on mushrooms that are toxic to humans", "Treat insect damage as irrelevant to the dining decision"],
        ["‘It smells clean or grew in a clean forest’", "Smell and habitat do not divide poisonous from edible species", "Reject unknown-source or unfamiliar mushrooms"],
        ["‘Silver, garlic or ginger did not change’", "These household tests do not react reliably with mushroom toxins and garlic/ginger do not detoxify them", "Use none of them as a test"],
        ["‘A local person recognises it’", "Experience can reduce uncertainty but does not replace traceable sourcing and specialist identification", "Make the operator document the product and process"],
        ["‘If it causes visions, that is the fun kind’", "Neuropsychiatric effects can accompany serious poisoning, and other species can injure the liver, kidneys, heart or muscles", "Treat altered vision, confusion or hallucinations as medical warning signs"],
      ],
    },
    {
      id: "myths-p1",
      type: "paragraph",
      text: "见手青 (jiànshǒuqīng) appears in the 2026 Yunnan warning as the food involved in a poisoning case after insufficient cooking. That name does not let a traveller identify a cooked plate or predict its risk. The same warning uses the case to show neurological harm; Homeground does not turn it into a challenge dish. If a seller promotes visions, secrecy or undercooking as part of the experience, leave rather than negotiate a shorter timer.",
    },
    {
      id: "table-heading",
      type: "heading",
      level: 2,
      text: "Keep alcohol, portions and group behaviour under control",
    },
    {
      id: "table-table",
      type: "table",
      caption: "Small choices that preserve the safety process",
      columns: ["Issue", "Do this", "Do not do this"],
      rows: [
        ["Alcohol", "Choose water, tea or another non-alcoholic drink for the mushroom meal", "Treat beer, wine or spirits as a traditional pairing; Yunnan guidance says not to drink alcohol with wild mushrooms"],
        ["Portion", "Share a modest first round with ordinary foods and stop when satisfied", "Order a parade of rare mushrooms or eat repeatedly to get value from a set"],
        ["Table control", "Give one diner and one staff member responsibility for the pot and the order record", "Let each person add an untracked handful or move raw pieces between pots"],
        ["Children or distracted groups", "Seat anyone not managing the pot away from the burner and serve only after the responsible adult receives the staff release", "Let the table game, photo session or conversation override the newest raw addition"],
      ],
    },
    {
      id: "table-p1",
      type: "paragraph",
      text: "The shared-meal instinct to let everyone contribute can work against a controlled mushroom sequence. This is one meal where ‘helping’ by adding another plate is not helpful. Tell the group before the burner starts: nobody adds raw mushrooms except the assigned person; nobody drinks alcohol; nobody eats until staff releases the batch. If a companion wants a different wild item, save it for another meal rather than another dish or compartment at this sitting. Choose cultivated mushrooms or ordinary cooked food for variety now.",
    },
    {
      id: "emergency-heading",
      type: "heading",
      level: 2,
      text: "Treat suspicious symptoms as an emergency, not a dining dispute",
    },
    {
      id: "emergency-callout",
      type: "callout",
      title: "Stop eating and seek urgent professional help",
      tone: "warning",
      body: "After a mushroom meal, dizziness, nausea, vomiting, abdominal pain, diarrhoea, agitation, weakness, double vision, altered vision, confusion or hallucinations require prompt medical assessment. Symptoms can differ by toxin and diner; do not wait for everyone at the table to feel the same. Call China's medical emergency number 120 or go promptly to the nearest suitable hospital. Tell responders that wild mushrooms may be involved.",
    },
    {
      id: "emergency-list",
      type: "list",
      ordered: true,
      items: [
        "Stop the meal. Do not taste another piece to compare symptoms and do not let unaffected companions finish the pot.",
        "Call 120 or seek urgent medical care; follow the dispatcher or clinician rather than an online remedy. Do not drive yourself if vision, confusion, weakness or coordination is affected.",
        "State the restaurant name and branch, meal time, first symptom time, number of diners and every mushroom or dish name you recorded.",
        "Ask the restaurant to preserve the retained food sample and order record. Keep remaining food only if it can be secured without exposing anyone to another taste.",
        "Save clear photographs of the menu/labels, the receipt and any remaining ingredient. A photo assists investigation; it does not replace medical care or laboratory identification.",
        "Tell the restaurant promptly so it can activate its emergency process, but do not delay transport while arguing about blame or payment.",
      ],
    },
    {
      id: "emergency-p1",
      type: "paragraph",
      text: "Do not let a sleep-and-wait plan, an internet remedy or an argument with the restaurant delay 120 or transport. Official pages reviewed here are not uniform about immediate first-aid details, so this guide does not tell a traveller to perform or avoid a particular intervention. Follow instructions tailored to the person's condition by the 120 dispatcher or clinician. A retained sample can help professionals investigate; it does not protect the diner in real time. Keep every diner contactable because clinical or public-health staff may need the complete exposure history.",
    },
    {
      id: "language-heading",
      type: "heading",
      level: 2,
      text: "Use a Chinese question card before ordering",
    },
    {
      id: "language-p1",
      type: "paragraph",
      text: "Show the questions in sequence instead of asking only ‘Is it safe?’ A yes/no reassurance hides the evidence you need. Start with classification and mixing, then ask about source, kitchen work and the table release. Save the final emergency line offline. If staff cannot understand the questions, that is not an invitation to simplify the risk into a thumbs-up; choose the cultivated option or another meal.",
    },
    {
      id: "language-table",
      type: "table",
      caption: "Restaurant-ready questions",
      columns: ["Need", "Show or say"],
      rows: [
        ["Separate categories", "请逐样告诉我：哪些是野生菌，哪些是人工栽培菌？"],
        ["Get the exact product name", "这份野生菌的中文名称是什么？今天从哪里进货？"],
        ["Reject a mixture", "我们不混吃多种野生菌。可以只点一种，并单独加工吗？"],
        ["Ask about kitchen preparation", "这种菌进锅前，厨房已经做了什么预处理？"],
        ["Confirm sample retention", "这份菌和这桌的订单有留样、留记录吗？"],
        ["Keep cooking control with staff", "请由工作人员下锅并告诉我们什么时候可以吃；我们不会中途加新的菌。"],
        ["Cultivated fallback", "如果这些不能确认，请给我们只含人工栽培菌的锅或菜。"],
        ["Dietary check", "汤底、蘸料和配菜里有鸡汤、猪油、牛肉、奶、花生、芝麻或___吗？会交叉接触吗？"],
        ["No alcohol", "我们吃菌时不喝酒，请给无酒精饮料。"],
        ["Late raw addition", "刚才新加的是不是同一种、同一批记录的野生菌？如果是，请从最后加入时重新完整计时和处理；如果不同或不能确认，这一整锅我们都不吃。"],
        ["Emergency", "有人吃菌后不舒服。请立即帮我们拨打120或联系急救，不要等其他人也出现症状；请保留留样和订单记录，告诉急救人员吃了什么，但不要耽误送医。"],
      ],
    },
    {
      id: "decision-heading",
      type: "heading",
      level: 2,
      text: "Know who should choose the wild option—and who should skip it",
    },
    {
      id: "decision-table",
      type: "table",
      caption: "A final go, change or stop decision",
      columns: ["Traveller", "Decision", "Why"],
      rows: [
        ["Curious diner with clear restaurant evidence and no relevant dietary barrier", "Proceed conservatively with one small, clearly documented wild item and the intact staff process", "The decision reduces avoidable uncertainty but does not remove risk"],
        ["Traveller who mainly wants Yunnan flavours without wild-species risk", "Choose cultivated mushrooms and other Yunnan dishes", "You still get a regional meal without needing to identify or process a wild product"],
        ["Severe allergy, strict ingredient boundary or communication failure", "Skip the shared wild-mushroom pot unless the entire chain and cross-contact controls can be confirmed", "A divided pot, translation app or confident waiter is not a guarantee"],
        ["Restaurant offers only mixed wild sets, playful undercooking or ‘visions’ marketing", "Leave and choose another restaurant or meal", "The product conflicts with the evidence boundary rather than merely your level of adventure"],
      ],
    },
    {
      id: "decision-p1",
      type: "paragraph",
      text: "The useful memory is not a list of supposedly safe mushrooms. It is a sequence: classify, trace, simplify, hand off, protect the clock, refuse alcohol, and escalate symptoms. A good restaurant conversation may end with a wild dish, a cultivated pot or a decision to leave. All three can be culturally attentive choices. Yunnan's mushroom season is a living food economy, not a test of bravery; respecting it means taking both the ingredient and the province's own safety warnings seriously.",
    },
    {
      id: "links",
      type: "internal-links",
      title: "Plan the rest of the meal and route",
      items: [
        {
          label: "Build a regional food route",
          href: "/guides/china-regional-food-route/",
          description: "Choose where a carefully planned Yunnan mushroom meal fits among China's regional food experiences.",
        },
        {
          label: "Your first shared meal in China",
          href: "/guides/first-shared-meal-in-china/",
          description: "Understand seating, shared dishes, tea and payment while keeping this mushroom-specific safety workflow separate.",
        },
        {
          label: "Order Chongqing hotpot",
          href: "/guides/chongqing-hotpot-first-order/",
          description: "A different hotpot task centred on red broth, portions, raw/cooked tools and heat recovery.",
        },
        {
          label: "Read a Yunnan coffee experience",
          href: "/guides/yunnan-coffee-from-cherry-to-cup/",
          description: "Use another evidence-led workflow to distinguish farm, processing, roasting and café claims in Yunnan.",
        },
        {
          label: "Pay in China as a tourist",
          href: "/guides/how-to-pay-in-china-as-a-tourist/",
          description: "Prepare payment backups so a restaurant bill does not become a second failure point.",
        },
      ],
    },
    {
      id: "sources",
      type: "sources",
      title: "Sources",
      items: [
        {
          label: "2026 Yunnan wild-mushroom poisoning risk map and prevention guidance",
          url: "https://ynsjkj.yn.gov.cn/html/2026/jikongkepu_0527/2008.html",
          publisher: "Yunnan Provincial Disease Control Bureau",
          reviewedAt: "2026-09-04",
        },
        {
          label: "2026 poisoning cases and mushroom-identification myths",
          url: "https://ynsjkj.yn.gov.cn/html/2026/jikongkepu_0606/2117.html",
          publisher: "Yunnan Provincial Disease Control Bureau",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Provincial health warning on wild-mushroom poisoning",
          url: "https://www.yn.gov.cn/hdjl/msgq/202505/t20250518_313292.html",
          publisher: "Yunnan Provincial Government",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Provincial food-safety warning and catering-operator controls",
          url: "https://amr.yn.gov.cn/info/1030/39259.htm",
          publisher: "Yunnan Provincial Food Safety Office / Administration for Market Regulation",
          reviewedAt: "2026-09-04",
        },
        {
          label: "Wild-mushroom poisoning prevention and identification myths",
          url: "https://ynsjkj.yn.gov.cn/html/2024/jikongkepu_0715/176.html",
          publisher: "Yunnan Provincial Disease Control Bureau / Yuanjiang County CDC",
          reviewedAt: "2026-09-04",
        },
        {
          label: "National Health Commission summer food-safety briefing",
          url: "https://www.nhc.gov.cn/xcs/c100122/202406/03d4253c5a8e4b9cad4c695ddc7d2e25.shtml",
          publisher: "National Health Commission of China",
          reviewedAt: "2026-09-04",
        },
        {
          label: "National consumer warning on poisonous mushrooms",
          url: "https://www.nhc.gov.cn/sps/c100087/202006/43f7eb3844d74fe18c23db66f0ed8282.shtml",
          publisher: "National Health Commission of China",
          reviewedAt: "2026-09-04",
        },
      ],
    },
  ],
} as const satisfies StructuredPageBody;

export default body;
