import type { StructuredPageBody } from "../../../lib/content-system/page-body";

const body = {
  schemaVersion: "1.0.0",
  blocks: [
    { id: "lead", type: "lead", text: "Mainland China only; Hong Kong and Macao have separate official systems. If your location is threatened or officials order evacuation or closure, follow the competent authority or site staff now—do not wait for screenshots or booking replies. If neither staying nor an official route is safe, do not cross flooded or controlled areas; ask staff and local emergency services. Otherwise confirm the shelter, read hazard, issuer, area, time and defence guide, then verify bookings." },
    { id: "direct-answer", type: "callout", title: "Separate safety from booking state", tone: "decision", body: "Stay only in a shelter confirmed appropriate for this hazard; move only by a verified safe route to a confirmed place. Weather authorities describe hazards; operators control service states. Warning colour alone proves no cancellation, closure, refund timing or compensation." },
    { id: "decode-heading", type: "heading", level: 2, text: "Decode the warning before changing the itinerary" },
    { id: "decode-table", type: "table", caption: "Copy five fields from the current official notice", columns: ["Field", "Question", "Avoid"], rows: [["Hazard", "Which named hazard?", "Searching only colour"], ["Issuer", "NMC, local authority or another authorised service?", "Treating a repost as issuer"], ["Area", "Is your hotel, route, hub or destination named?", "Applying one headline everywhere"], ["Time", "When issued, updated or cancelled?", "An untimed screenshot"], ["Defence guide", "What actions apply here?", "Replacing it with social advice"]] },
    { id: "colour-boundary", type: "callout", title: "Colour is severity context, not an operating-state code", tone: "warning", body: "China's meteorological-disaster warning signals generally use a four-level blue, yellow, orange and red framework—levels IV, III, II and I. Hazard-specific and local standards, signals and instructions can differ, so read the notice text. A higher colour does not cancel a booking; a lower one does not prove a route safe." },
    { id: "checkpoint-heading", type: "heading", level: 2, text: "Build a verified checkpoint before moving" },
    { id: "checkpoint-list", type: "list", ordered: true, items: ["Confirm the shelter suits this hazard; obey evacuation or closure first.", "When safe, save the official notice, issuer, time and area.", "Read its defence guide before moving.", "Check each flight, train, attraction, hotel and transfer separately.", "Save official operator state and confirmation time.", "Ask whether service operates, changes, suspends or cancels.", "Choose stay/move/replace and set a meeting point.", "Recheck at a set time or new official notice."] },
    { id: "four-paths", type: "table", caption: "Choose from safety plus booking state", columns: ["Path", "Use when", "Record"], rows: [["Stay", "Shelter suits this hazard and movement is not advised or no safe route exists", "Shelter, warning, next check"], ["Move", "Place is threatened/evacuated and a safe route plus destination are confirmed", "Chinese addresses, authority instruction, fallback"], ["Replace", "Original fails and a safer alternative is verified", "Original state, replacement terms, reason"], ["Refund/escalate", "Notice/terms provide a remedy or delivery remains disputed", "State, changer, effective time, offer, references"]] },
    { id: "scenario-one-heading", type: "heading", level: 2, text: "Scenario: typhoon warning, flight still shown as scheduled" },
    { id: "scenario-one", type: "paragraph", text: "A typhoon warning names your coastal area, but tomorrow's flight remains scheduled. Do not treat colour as cancellation or make a risky airport transfer to avoid a no-show. Follow the defence guide, ask about the exact flight, and verify airport access separately. Timestamp a stay decision; if the flight changes, save the new state and remedy notice." },
    { id: "scenario-one-table", type: "table", caption: "Four clocks run independently", columns: ["Clock", "Verify", "Decision"], rows: [["Warning clock", "Latest issuer, area and defence guide", "Whether movement should pause"], ["Flight clock", "Exact flight in the carrier's official channel", "Scheduled, changed or cancelled"], ["Road/transit clock", "Official local route or operator notice", "Whether the airport can be reached safely"], ["Booking clock", "Ticket terms and carrier remedy notice", "Accept, replace, document or escalate"]] },
    { id: "scenario-two-heading", type: "heading", level: 2, text: "Scenario: heavy rain, train suspended, attraction silent" },
    { id: "scenario-two", type: "paragraph", text: "Your 12306 order or official train query shows suspension while an attraction booking remains valid. The query is reference-only; station announcements control. Avoid flooded/controlled routes, save both states, then ask the attraction ticket owner. Rail treatment does not rewrite that booking; the failed connection is context, not a refund guarantee." },
    { id: "booking-heading", type: "heading", level: 2, text: "Read every booking as a separate state machine" },
    { id: "booking-table", type: "table", caption: "Warning and booking state are different evidence", columns: ["Booking", "Official check", "If unclear"], rows: [["Flight", "Carrier order/status and direct notice", "Ask about that flight; check airport access separately"], ["Train", "12306 order and train-status query", "Reference-only: check the train; rely on station announcements"], ["Attraction", "Ticket owner, reservation and dated closure notice", "Ask whether the slot stands, changes or has a remedy"], ["Hotel", "Property and booking channel", "Confirm the room and safe access"], ["Local transfer", "Municipal/operator notice for that route", "Verify alternate route and destination before replacing"]] },
    { id: "state-boundary", type: "callout", title: "Do not overwrite the original booking state", tone: "warning", body: "Before cancelling/changing, save state, changer, effective time and offered remedy; read the consequence of traveller action. When safe, send one record to booking channel and operator. Ask both for the booking owner, terms and next step in writing. Evidence does not predetermine refund or legal result." },
    { id: "evidence-heading", type: "heading", level: 2, text: "Build the recovery record while facts are visible" },
    { id: "evidence-list", type: "list", items: ["Official warning URL or screenshot with issuer, hazard, area and timestamp.", "Defence guide and any later update, downgrade or cancellation.", "Order number masked for sharing, exact service/date and passenger name as booked.", "Current booking state, booking owner, who changed it, effective time and remedy offered.", "Original ticket, cancellation and change terms saved before they update.", "Messages, call time, channel, staff role and promised next step.", "Payment reference, replacement receipt and actual delivery or non-delivery facts.", "A timeline separating weather facts, operator facts and your actions."] },
    { id: "remedy-table", type: "table", caption: "Keep remedies evidence-led", columns: ["Stage", "Action", "Do not claim"], rows: [["Clarify", "Send evidence to channel and operator; request owner, state, changer, time and remedy", "Warning already cancelled it"], ["Choose", "Read consequences before accept/replace/traveller-cancel; preserve original state", "Replacement cost is recoverable"], ["Request", "Ask both to name terms and answer in writing", "Universal refund timing or success"], ["Escalate", "If ignored/passed around, use both official complaint routes; keep references; follow card/payment dispute rules", "Unstated compensation or legal conclusion"]] },
    { id: "failure-heading", type: "heading", level: 2, text: "When information or access fails" },
    { id: "failure-table", type: "table", caption: "Fallbacks during a moving event", columns: ["Failure", "Fallback", "Stop"], rows: [["Shelter threatened/no route", "Follow official/site direction; ask emergency services", "Do not await bookings or cross flooded/controlled areas"], ["No data/app", "Use staff, official broadcast or SMS; note time", "Do not travel on unverified screenshots"], ["No operator answer", "Try another official channel; record attempts; secure shelter", "Do not move only for a counter"], ["Water/closure on route", "Verify Chinese address and official route; shelter/reroute", "Never enter controlled/flooded sections"], ["Replacement changes", "Stop stacking bookings; preserve states; rebuild safely", "Do not multiply losses without a usable chain"]] },
    { id: "change-table", type: "table", caption: "Conditions that change the conclusion", columns: ["New fact", "Change"], rows: [["Warning area no longer includes your route", "Still verify local conditions and operator state before moving"], ["Warning upgraded or defence guide tightens", "Pause movement and rebuild the safety decision"], ["Operator confirms cancellation", "Move from status checking to the stated remedy path"], ["Service operates but access route closes", "Treat access and booking as separate problems; document both"], ["Safe lodging becomes unavailable", "Confirm a receiving place before relocating"], ["Conflicting official notices appear", "Compare issuer, area and timestamp; ask the responsible authority/operator rather than choosing silently"]] },
    { id: "freshness", type: "paragraph", text: "This high-risk dynamic guide was reviewed on 2026-09-01. Recheck when warning rules, national alert service, 12306, aviation law or operator processes change, and whenever a live notice updates. If official notices conflict, preserve both issuers, areas and times; identify the competent safety authority for the affected place and ask it to clarify. If scope or authority remains uncertain, pause exposure rather than choosing silently. Never convert conflict into a transport or refund promise." },
    { id: "verify-heading", type: "heading", level: 2, text: "Final check before staying or moving" },
    { id: "verify-list", type: "list", items: ["Evacuation/closure/rescue preceded evidence work.", "Shelter suits this hazard.", "Hazard, issuer, area, time and defence guide are saved.", "Bookings record owner, state, changer, effective time and offer.", "Movement uses a verified route and destination.", "Traveller cancellation did not erase the original state.", "Terms, notices, contacts and payments are saved.", "Replacement is usable, not merely purchasable.", "Next check has a time or notice trigger.", "Colour was not called automatic cancellation/refund."] },
    { id: "links", type: "internal-links", title: "Strengthen the recovery chain", items: [{ label: "Confirm shifted map pins in China", href: "/guides/china-map-coordinate-offset-explained/", description: "Cross-check a safe destination with its Chinese address and local map." }, { label: "Protect the last night before an international flight", href: "/guides/china-last-night-before-international-flight/", description: "Build a larger departure buffer when disruptions could break a same-day transfer." }, { label: "Build a booking-dispute evidence pack", href: "/guides/china-booking-dispute-evidence-pack/", description: "Organise order, terms, payment and delivery facts before escalation." }] },
    { id: "sources", type: "sources", title: "Official sources", items: [{ label: "Current meteorological warnings", url: "https://www.nmc.cn/f/alarm.html", publisher: "National Meteorological Center", reviewedAt: "2026-09-01" }, { label: "Typhoon monitoring and forecast", url: "https://typhoon.nmc.cn/", publisher: "National Meteorological Center", reviewedAt: "2026-09-01" }, { label: "Meteorological disaster warning signal rules", url: "https://www.cma.gov.cn/zfxxgk/gknr/flfgbz/gz/202005/P020220628619411458474.pdf", publisher: "China Meteorological Administration", reviewedAt: "2026-09-01" }, { label: "National emergency warning information service", url: "https://app.gjzwfw.gov.cn/jmopen/webapp/html5/zhyjssxx/index.html", publisher: "National Government Service Platform", reviewedAt: "2026-09-01" }, { label: "12306 train-status query", url: "https://www.12306.cn/index/view/infos/train-query-status.html", publisher: "China Railway 12306", reviewedAt: "2026-09-01" }, { label: "12306 internet-refund FAQ", url: "https://kyfw.12306.cn/otn/gonggao/onlineRefund.html", publisher: "China Railway 12306", reviewedAt: "2026-09-01" }, { label: "Civil Aviation Law of the People's Republic of China", url: "https://www.caac.gov.cn/XXGK/XXGK/FLFG/202512/t20251227_229597.html", publisher: "Civil Aviation Administration of China", reviewedAt: "2026-09-01" }, { label: "Heavy-rain emergency safety guidance", url: "https://www.cneb.gov.cn/kepuku/ziranzaihai/qixiangzaihai/baoyu/", publisher: "China National Emergency Broadcasting", reviewedAt: "2026-09-01" }, { label: "Hong Kong weather warnings and signals (excluded jurisdiction)", url: "https://www.hko.gov.hk/en/wxinfo/dailywx/wxwarntoday.htm", publisher: "Hong Kong Observatory", reviewedAt: "2026-09-01" }, { label: "Macao weather-warning service (excluded jurisdiction)", url: "https://www.smg.gov.mo/", publisher: "Macao Meteorological and Geophysical Bureau", reviewedAt: "2026-09-01" }] }
  ]
} as const satisfies StructuredPageBody;

export default body;
