import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body = { schemaVersion: "1.0.0", blocks: [
  { id: "lead", type: "lead", text: "와이탄과 루자쭈이는 같은 전망의 두 버전이 아닙니다. 서쪽 와이탄에서는 역사적 상업 건물을 등지고 황푸강 건너 현대 스카이라인을 봅니다. 동쪽 루자쭈이에서는 그 고층 건물 사이에 서서 와이탄을 돌아봅니다. 원하는 장면을 먼저 정하고 강은 한 번만 건너세요." },
  { id: "answer", type: "callout", title: "바로 답하면", tone: "decision", body: "첫 저녁에는 좋은 빛이 남을 때 와이탄에서 한정된 구간을 걷고, 당일 운행을 확인한 페리나 지하철로 루자쭈이에 건너가 고층 도시를 가까이 보세요. 시간 예약 전망대·박물관·푸둥 일정이 있으면 반대로 갑니다. 한 시간뿐이면 와이탄에 머무는 편이 두 강변의 대비를 가장 간단히 보여 줍니다." },
  { id: "difference-heading", type: "heading", level: 2, text: "두 강변은 서로 다른 질문에 답합니다" },
  { id: "difference", type: "table", caption: "명성보다 경험으로 선택", columns: ["쪽", "잘 맞는 것", "대가"], rows: [["와이탄/푸시", "역사적 외관, 전체 루자쭈이 스카이라인, 긴 공공 산책로와 대비", "고층 안이 아니라 바라보며 혼잡이 큼"], ["루자쭈이/푸둥", "타워 규모, 전망대·상가·박물관과 와이탄 역전망", "지상에서 타워가 시야를 나누고 일부 지점은 와이탄이 약함"], ["둘 다", "상하이를 연결된 두 도시 이야기로 읽기", "건너는 시간이 좋은 빛을 지울 수 있음"]] },
  { id: "bund-heading", type: "heading", level: 2, text: "와이탄에서는 앞과 뒤를 모두 보세요" },
  { id: "bund", type: "paragraph", text: "상하이 정부는 와이탄을 약 1.5km의 보호 역사 수변 지구로, 서쪽에 고딕·바로크 계열 건물 52채가 있다고 설명합니다. 한 번의 스카이라인 사진으로 끝내지 말고 적당한 구간을 걸으며 뒤쪽 외관과 출입구를 본 뒤 강변으로 돌아와 옛 무역·금융 전면과 푸둥의 관계를 읽으세요." },
  { id: "lujiazui-heading", type: "heading", level: 2, text: "루자쭈이에서는 지상 또는 수직 경험 하나" },
  { id: "lujiazui", type: "comparison", title: "푸둥 옵션을 모두 합치지 마세요", columns: [{ heading: "지상 강변", body: "동쪽 산책로와 가까운 타워 하나를 봅니다. 유료 전망대보다 강 건너기와 도시 규모가 중요할 때 좋습니다." }, { heading: "전망대 하나", body: "현행 시간, 날씨, 시야와 접근으로 한 건물을 고릅니다. 예약이 강변 순서를 정할 수 있으며 이 글은 상업 순위를 매기지 않습니다." }, { heading: "박물관·실내 앵커", body: "한 곳을 날씨 대안으로 쓰고 짧은 야외 구간을 남깁니다. 운영은 해당 장소의 책임입니다." }] },
  { id: "light-heading", type: "heading", level: 2, text: "낮에서 밤으로 바뀌는 시간을 지키세요" },
  { id: "light", type: "table", caption: "한 번 건너는 순서", columns: ["시간", "행동", "이유"], rows: [["늦은 오후", "외관 디테일이 보일 때 와이탄 걷기", "어두우면 스카이라인이 이야기를 압도"], ["해질녘", "서쪽 한 전망점에 머무름", "다른 핀보다 하늘 변화가 중요"], ["불이 켜진 뒤", "확인한 페리/지하철로 한 번 건넘", "두 강변 구도를 이미 봄"], ["밤", "루자쭈이 강변 또는 타워 경험 하나", "근거리 도시 규모가 두 번째 이야기"]] },
  { id: "crossing-heading", type: "heading", level: 2, text: "실제 운행에 맞는 강 건너기" },
  { id: "crossing", type: "comparison", title: "페리·지하철·관광터널", columns: [{ heading: "공공 페리", body: "강 건너기 자체가 경험입니다. 노선과 시간은 운영 사실이므로 ‘상하이 페리’ 채널에서 재확인합니다." }, { heading: "지하철", body: "악천후에 안정적이고 출발·도착이 역과 가까울 때 실용적입니다. 강 전망은 없고 역 도보가 남습니다." }, { heading: "관광터널", body: "강 아래 별도 유료 관광 시설입니다. 터널 자체가 목적일 때 현행 운영을 확인해 사용하세요." }] },
  { id: "ferry", type: "callout", title: "페리 시간표를 고정하지 마세요", tone: "warning", body: "상하이 공식 방문 안내는 동진 노선의 두 부두를 소개하면서 ‘상하이 페리’ 위챗에서 최신 시간을 보라고 명시합니다. 날씨·정비·노선 변경이 가능합니다. 걷기 전 정확한 부두 이름과 운행을 확인하고 지하철 대안을 저장하세요." },
  { id: "short-plans-heading", type: "heading", level: 2, text: "실제로 가진 시간만 쓰세요" },
  { id: "short-plans", type: "table", caption: "시간별 선택", columns: ["시간", "계획", "뺄 것"], rows: [["약 1시간", "와이탄 한 구간과 루자쭈이 스카이라인", "강 건너기와 전망대"], ["2~3시간", "와이탄 디테일, 해질녘, 한 번 건넘, 짧은 푸둥 강변", "여러 전망대·상가·박물관"], ["반나절", "날씨에 맞는 실내/수직 앵커 하나 추가", "같은 기능의 두 번째 상업 전망"]] },
  { id: "recovery", type: "table", caption: "계획이 깨질 때", columns: ["문제", "회복"], rows: [["안개·비로 스카이라인 없음", "와이탄 건축과 푸둥 실내 한 곳; 전망표를 무작정 사지 않음"], ["페리 중단", "저장한 지하철로 바꾸고 단방향 유지"], ["난간 혼잡", "합법적인 덜 붐비는 구간으로 이동"], ["예약 전망대 지연", "새 순서가 예약을 지킬 때만 양안 역전"]] },
  { id: "boundary", type: "callout", title: "상하이 명소 백과사전이 아닙니다", tone: "neutral", body: "이 글은 양안 선택, 빛의 순서와 건너기만 담당합니다. 모든 타워, 크루즈, 식당과 박물관을 평가하거나 공항 이동을 반복하고 외탄 건물을 얇은 글로 나누지 않습니다." },
  { id: "links", type: "internal-links", title: "상하이 계획 이어가기", items: [{ label: "상하이 도시 허브", href: "/ko/destinations/shanghai/", description: "강변을 도시 전체 일정에 넣습니다." }, { label: "상하이 숙소 지역", href: "/ko/guides/shanghai-where-to-stay-first-trip/", description: "한 번의 야경보다 반복하는 일로 고릅니다." }, { label: "푸둥 또는 훙차오 공항", href: "/ko/guides/shanghai-pudong-or-hongqiao-airport/", description: "공항 선택과 푸둥 관광을 분리합니다." }, { label: "상하이 근교 수향 고르기", href: "/ko/guides/shanghai-water-town-zhujiajiao-tongli-wuzhen/", description: "장난 당일치기를 비교하고 상하이 수변 하루와 섞지 않습니다." }, { label: "상하이–항저우 교통", href: "/ko/guides/shanghai-hangzhou-transport-route/", description: "다음 도시 티켓과 역을 맞춥니다." }] },
  { id: "sources", type: "sources", title: "공식 출처와 사진 크레디트", items: [{ label: "와이탄 역사 지구와 수변", url: "https://english.shanghai.gov.cn/en-ScenicSpots/20231205/584672cc6d044eabb5f7f6fc9049a19f.html", publisher: "상하이시 인민정부", reviewedAt: "2026-08-22" }, { label: "공식 페리와 황푸강 이동 안내", url: "https://english.shanghai.gov.cn/en-Transportation/20250910/65267b72530645bdacc119d56380d363.html", publisher: "상하이시 인민정부", reviewedAt: "2026-08-22" }, { label: "대표 사진: Kallerna의 루자쭈이, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Lujiazui_from_The_Bund.jpg", publisher: "Wikimedia Commons", reviewedAt: "2026-08-22" }] }
] } as const satisfies StructuredPageBody;
export default body;
