import type { StructuredPageBody } from "../../../lib/content-system/page-body";
const body:StructuredPageBody={schemaVersion:"1.0.0",blocks:[
{id:"answer-first",type:"lead",text:"Choose the land route if you want temples, cliff paths, changing scale and the possibility of reaching the Buddha's feet when that platform is open. Choose the daytime boat if your priority is the complete seated figure and the relationship between statue, cliff and rivers. Choose both only with a full day and confirmed operations: they use separate access, transport and tickets, and a suspended boat must not break the return plan."},
{id:"compare-heading",type:"heading",level:2,text:"The two visits answer different questions"},
{id:"compare",type:"table",caption:"Land and boat visit comparison",columns:["Option","What you gain","What can fail"],rows:[
["Land / mountain visit — 游山","Close changes of scale, Lingyun area, cliff context and—when open—the descent toward the feet.","Stairs, one-way controls, heat, queues, conservation closures and a temporarily closed foot platform."],
["Daytime river boat — 游江","A frontal, whole-statue view and the broader meeting of cliff, water and landscape.","Water level, fog, wind, storms, safety controls, pier changes, waiting and suspension."],
["Both","Near and distant readings of the same monument.","Two ticket/check-in systems and ground transfer between zones; it is not one continuous attraction loop."],
]},
{id:"separate-ticket",type:"callout",title:"Do not treat the boat as part of the mountain ticket",body:"The official operation describes mountain entry and daytime water tourism as separate projects with different ticketing and boarding points. Read the live official purchase page. A reseller bundle can hide which product, pier and refund rule you actually bought.",tone:"warning"},
{id:"land-heading",type:"heading",level:2,text:"A realistic land sequence"},
{id:"land",type:"list",items:["Enter the named scenic-area gate on the current order and orient to the Lingyun temple/cliff zone.","See the head and upper cliff before committing to the descent. This already gives close scale without promising the foot platform.","Read the live board for stair direction, platform opening and return flow; conservation and crowd management can change them.","Descend only if every traveller can manage steep, narrow stairs and the climb/exit afterward. Turning back may be restricted on managed one-way sections.","Keep the Buddha as part of a protected mountain and river landscape, not an isolated sculpture."]},
{id:"boat-heading",type:"heading",level:2,text:"A boat is a viewpoint with an operating decision"},
{id:"boat",type:"list",items:["Confirm ‘daytime water tour’, not a night cruise or river-crossing product with a similar name.","Save the current boarding pier, ticket office or digital check-in, and disembarkation point in Chinese.","Ask whether the service is rolling departure or fixed sailing on that date; do not copy an old timetable.","Keep the passport/order and enough time for the road transfer after disembarkation.","If boats stop, switch to the land-only or city plan. Do not wait indefinitely when a train to Chengdu constrains the day."]},
{id:"dynamic",type:"callout",title:"Water level and weather are operational facts, not small print",body:"Leshan's official visitor information says departure times can change with water level and weather. Government notices also show individual piers or crossing products can be suspended. Check the scenic area's official portal and official WeChat on the morning of travel and again at the pier.",tone:"decision"},
{id:"who",type:"comparison",columns:[
{heading:"Older or stair-limited traveller",body:"The boat may offer the whole view with less climbing, but boarding steps and pier walking still need confirmation. Do not promise barrier-free access without a current operator answer."},
{heading:"Photography priority",body:"Boat gives the classic whole figure but the vessel may not stop in ideal light or position. Land gives details and scale. Neither guarantees an uncrowded frame."},
{heading:"Short day from Chengdu",body:"Choose one mode. Two modes plus station transfers create fragile timing, especially when a boat has no fixed immediate departure."}
]},
{id:"time-heading",type:"heading",level:2,text:"Choose by usable hours, not attraction labels"},
{id:"time-matrix",type:"table",caption:"A half day and a full day support different promises",columns:["Available day","Defensible choice","Do not promise"],rows:[
["Short stop with fixed Chengdu train","One mode, selected before arrival, with a firm station-departure buffer","Both modes, a guaranteed boat departure or the foot platform"],
["Full day in Leshan","Land first plus boat only if live operation and ground transfer still fit","That one ticket or one entrance connects the two products"],
["Heat, rain or limited stair capacity","Boat may reduce climbing if boarding is currently suitable; otherwise use an abbreviated land route","Barrier-free access or effortless boarding without operator confirmation"],
["Photography priority","Boat for overall figure; land for scale and detail","A fixed pause, angle, light or uncrowded view from a moving vessel"],
]},
{id:"land-check",type:"callout",title:"Assess the return climb before descending",body:"The cliff path is not only a descent toward the feet. The traveller must also complete the managed route and leave the scenic area. Before entering the steep section, check the live access direction, the least mobile person's balance and stamina, heat or wet surfaces, and the time needed afterward. Seeing the head, temple area and upper cliff can still be a meaningful land visit when the lower route is closed or unsuitable.",tone:"decision"},
{id:"boat-expectations",type:"paragraph",text:"A daytime boat is a shared operating service, not a private photography platform. Boarding queues, safety instructions, seating or standing position, river conditions and the vessel's movement affect what can be seen and photographed. Save the exact daytime product and pier in Chinese, carry the booking document and accept that the operator may alter or suspend the service for safety. A night cruise or local crossing with a similar river label does not replace the daytime Buddha-viewing product."},
{id:"both-heading",type:"heading",level:2,text:"If doing both, write the transfer between them"},
{id:"both-plan",type:"list",ordered:true,items:["Identify which product comes first and why; do not buy both before checking the day's live operation.","Save the exit from the first product and the exact entry or pier for the second.","Add road travel, ticket collection, queues and a meal/rest window between them.","Set a latest time for dropping the second product while the return still works.","Keep one-mode value: the day should remain worthwhile if weather, water or conservation control removes the other."]},
{id:"return",type:"callout",title:"Protect the return before adding the second mode",body:"Identify the final land transport point, road time to Leshan Station and a rail buffer. The boat's published closing time is not a guaranteed sailing or instant disembarkation. If the return train matters, set a stop-waiting time and keep a taxi or official ground-transport alternative.",tone:"neutral"},
{id:"final-check",type:"list",items:["The order names mountain, daytime boat or both.","The latest official notices have been checked for foot-platform access and daytime-boat operation.","Exact gate, pier and disembarkation point are saved.","Everyone accepts the stair/boarding demands.","A boat-free return reaches the station with buffer."]},
{id:"internal-links",type:"internal-links",title:"Connect Leshan to Sichuan",items:[
{label:"China high-speed trains for first-time visitors",href:"/guides/china-high-speed-train-first-time-guide/",description:"Keep the Leshan return separate from the station and passport process."},
{label:"Do you need a tour guide in China?",href:"/guides/do-you-need-a-tour-guide-in-china/",description:"Decide whether site interpretation adds value beyond transport."},
{label:"China with older parents",href:"/guides/china-itinerary-with-older-parents/",description:"Place stairs, boat boarding and recovery in the wider route."}
]},
{id:"consultation",type:"callout",title:"Need the choice checked for your date?",body:"A Homeground travel consultant can review the latest operation, mobility limits, Chengdu connection and stop-waiting point. Share the date, group pace, preferred view and return train.",tone:"neutral"},
{id:"sources",type:"sources",title:"Official and image sources reviewed",items:[
{label:"Official scenic-area information portal identified by the management committee",url:"http://www.lsdf517.com/web/list/97",publisher:"Leshan Giant Buddha Scenic Area",reviewedAt:"2026-08-12"},
{label:"Official Leshan visitor guide linking the current mountain, daytime-boat and river-crossing services",url:"https://www.leshan.gov.cn/lsswszf/jgjj/92337818/687756313100357.html",publisher:"Leshan Municipal People's Government",reviewedAt:"2026-08-12"},
{label:"Official international visitor information for seasonal land and water operations",url:"https://www.hi-leshan.com/index.php?a=index&aid=660&c=View&m=home",publisher:"Hi Leshan / Leshan international portal",reviewedAt:"2026-08-12"},
{label:"Government notice showing a river pier/crossing operation can be suspended",url:"https://www.leshan.gov.cn/lsswszf/bmdt/92337815/3e865b0e7eee473a94ee6972e.html",publisher:"Leshan Giant Buddha Scenic Area Management Committee",reviewedAt:"2026-08-12"},
{label:"Hero: Leshan Giant Buddha by Suicasmo, CC0; cropped and converted to WebP",url:"https://commons.wikimedia.org/wiki/File:Leshan_Giant_Buddha_20260514-5.jpg",publisher:"Wikimedia Commons",reviewedAt:"2026-08-12"}
]}
]};export default body;
